### ISSUE TITLE
Speed cameras are announced 2 times

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#3967] opened 2017-06-25 11:21 UTC
Osmand 2.7.0#17686D. Offline maps: Spain June,1, 2017. Navigation service: OSMAND

Speed cameras tagged using a relation in OSM are announced 2 times in OSMAND. Speed cameras that are not tagged using a relation are announced only 1 time (correctly).

**Comment by polarbearing** [comment] 2017-06-25 11:40
You need to give specific cases with links to the OSM objects. 

I had a similar observation, need to find the ticket, but could not draw the conclusion about relation or not.

**Comment by OpenSourceForEver** [comment] 2017-06-26 17:00
Speed cameras with no relations (it is announced 1 time):
https://www.openstreetmap.org/node/992001666
https://www.openstreetmap.org/node/2491235774#map=19/40.30379/-3.91350&layers=D
https://www.openstreetmap.org/node/992001156#map=19/40.41044/-3.73897&layers=D

Speed camera with relation (it is announced 2 times):
https://www.openstreetmap.org/node/992001056
https://www.openstreetmap.org/node/992003052#map=17/42.00551/-5.65816&layers=D
https://www.openstreetmap.org/node/992006571

I think OSMAND announces speed camera on "device" and on "from"

**Comment by maraf24** [comment] 2017-06-29 09:57
That's because the "device" from relation - https://www.openstreetmap.org/node/992001056 - shares the node with highway=motorway. So Osmand sees the speed camera twice.

**Comment by OpenSourceForEver** [comment] 2017-06-29 21:55
Is the solution to change the "device" to another situation outside the highway=motorway on OSM?

**Comment by polarbearing** [comment] 2017-07-12 11:52
> "device" from relation ... shares the node with highway=motorway. So Osmand sees the speed camera twice.

ok, that fits my enforcement relations. Where I hear it twice the device node is on the highway, where I hear it once it is next to the highway.

The first case is in the tunnel with 2 devices on both tunnel walls, so when mapping it as a single device on-road is plausible, otherwise we would need to put 2 devices in the relation. 

Probably osmand should not announce a device if the from-node is already announced.

**Comment by bitboy85** [comment] 2017-10-12 16:04
Have a look at my suggestions here: https://github.com/osmandapp/Osmand/issues/3757
Osmand should ignore the from node because there no exact definition where to place it.
Announcements could be too early or too late. Focusing on the device (multiple devices within a smal range) would resolve both issues

**Comment by pebogufi** [comment] 2017-10-12 16:12
But if Osmand ignores the from position for announcing,  and only make an announcement at the device, the announcement should come up early enough which is normally ensured with from position. So it should come up a defined time or defined distance before passing the device.

**Comment by vshcherb** [comment] 2017-10-16 07:41
Nope the OsmAnd uses only "from" cause that's the node located exactly on the way, it can't use "device". For this issue we should generate directional speed_camera point.

**Comment by vshcherb** [comment] 2018-01-24 22:36
The issue is that "device" is located directly on the road where by Wiki it is should be located at physical location. The solution on OsmAnd site would be to understand that "device" belongs to the road and skip adding it as speed_camera.

**Comment by vshcherb** [comment] 2018-01-24 22:41
Fixed on the client side when speed cams are located within 150 meters

**Closed by vshcherb** 2018-01-24 22:41 UTC
Labels: Observed
