### ISSUE TITLE
Nice to have: Fuel price plugin

### ISSUE THREAD

**Issue by Almorca** [osmandapp/OsmAnd#13866] opened 2022-03-06 21:20 UTC
# 🚀 feature request

Hello.

I would like to suggest the creation of a plugin that shows the prices of gasoline at gas stations.  Osmand's team could take care of making a generic plugin that reads the information in a standard format so that the part that obtains the fuel prices could be created separately (this part will probably be different for each country but the community will surely works to develop it for different countries).

The plugin should allow the user's preferred fuel to be saved in its configuration, the price of which would be the one displayed in the UI.  It would also be useful if the price is shown with a colored traffic light (green cheap, red expensive) to be able to see at a glance the most interesting gas stations to refuel.

As example I actually use http://www.mobialia.com/apps/gas-stations/ for Spain.

Related: #5533

**Comment by Lee-Carre** [comment] 2022-03-06 23:41
This data can be tagged in OSM directly. See [`charge:conditional`](//wiki.openstreetmap.org/wiki/Key:charge).

That way, it's available for everyone, worldwide. All while preserving freedom (rather than yet another proprietary plugin, as a workaround).

The problem of maintaining recent prices remains, regardless. However, a StreetComplete quest could solve that.

While prices (in machine-readable format) are a nice-to-have (automation for the win), there's a whole lot more basic data to add, first. Such as which fuels are available at each station.

**Comment by Lee-Carre** [comment] 2022-03-07 00:09
> [example I actually use for Spain](//www.mobialia.com/apps/gas-stations/).

France-only: [OpenFuelMap](//www.openfuelmap.net/). Seems to get the data from a published dataset (perhaps a result of regulatory requirements).

**Comment by letypequividelespoubelles** [comment] 2022-03-07 09:25
> The problem of maintaining recent prices remains, regardless. However, a StreetComplete quest could solve that.

@Lee-Carre In France data comes from [governement open data](https://www.prix-carburants.gouv.fr/) and are updated daily. A tag that changes everyday (like prices) is imho not something wanted in OSM. In France, we have a [special ref](https://wiki.openstreetmap.org/wiki/Key:ref:FR:prix-carburants?uselang=fr) to create a link between the OSM object and the daily updated price. I have no idea if the same existes in other countries.

And yes, it would be so nice if OsmAnd could have an option / plugin to show the price as exposed by @Almorca

**Comment by scaidermern** [comment] 2022-03-07 09:32
Duplicate of #13039.

**Comment by Lee-Carre** [comment] 2022-03-07 10:03
@letypequividelespoubelles

> A tag that changes everyday (like prices) is imho not something wanted in OSM.

I wasn't aware that the French market was so volatile. I'm accustomed to prices which might change every several months.

Fair enough, then. Thanks for the pointer to the dataset 👍.

Trouble, then, is needing a per-nation implementation, if there's no standardised format or API. Similar to road traffic (congestion) data.

Governments and their non-standards 😆.

Though, I'm (also) mindful of [XKCD #972 “Standards”](//www.xkcd.com/927/).

Unless OpenFuelMap itself is adapted to become *the* OSM-based site for fuel prices (beyond France), drawing on multiple datasets, presenting them in a uniform way (with API).

**Comment by pebogufi** [comment] 2022-03-07 10:12
In Germany it is extreme. It is normal, that there are chages of 5 times PER DAY and often more !! ... and of course for each sort of fuel. There are a lot of apps, which show the current prices in your city or near a defined position. And if you arrive at the petrol station be aware that it may have changed in meantime.

**Closed** 2022-03-07 15:01 UTC
