### ISSUE TITLE
Vehicle metrics doesn't reconnect OBD Bluetooth 

### ISSUE THREAD

**Issue by Davi427** [osmandapp/OsmAnd#21257] opened 2024-11-06 07:34 UTC
### Description

Since updating to OsmAnd+ 4.9.3, Released: 2024-11-01, the OBD Bluetooth connection isn't automatically reestablished on relaunch of osmand, after having had the car ignition turned off and on.

### Steps to reproduce

Connect obd Bluetooth
Turn off car ignition 
Turn on car ignition
exit osmand
Start osmand

### Actual result

The obd Bluetooth connection isn't automatically  reestablished 

### Expected result

Connection should be reestablished.
Preferably without having to relaunch osmand but definitely on relaunch the connection should establish automatically, since it takes 11 touches to get it working again (when Osmand is already running in foreground)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.9.3, Released: 2024-11-01
Android/iOS version: 14
Device model: FP5
Crash-Logs: ?
```

**Comment by vshcherb** [comment] 2024-11-06 16:35
We will implement that OBD will reconnect automatically once AA is connected again. Otherwise we don't want to continoulsy lookup connections

**Comment by Davi427** [comment] 2024-11-06 16:40
> We will implement that OBD will reconnect automatically once AA is connected again. Otherwise we don't want to continoulsy lookup connections

I do not have AA, I am just using my phone.

**Comment by vshcherb** [comment] 2024-11-12 12:55
We've implemented after connection to Android Auto though we can't receive signal that device is connected by bluetooth. Suggested api doesn't work as it requires to manually connect to Bluetooth device or constant Bluetooth scanning which is very bad for battery.

**Comment by Davi427** [comment] 2024-11-14 17:25
> We've implemented after connection to Android Auto though we can't receive signal that device is connected by bluetooth. Suggested api doesn't work as it requires to manually connect to Bluetooth device or constant Bluetooth scanning which is very bad for battery.

I see the dilemma, yeah.

Would it be possible to have "reconnect obd Bluetooth" as a custom button action? 
Then anyone who wants can add that button and mash it as often as they like without the structural battery drain.

**Comment by vshcherb** [comment] 2024-11-15 15:51
Yes I think quick action should definitely ok, though I'm thinking we could try to discover on route recalculation

**Comment by BipedalPossum** [comment] 2024-11-19 00:58
> Yes I think quick action should definitely ok, though I'm thinking we could try to discover on route recalculation

That sounds like a good idea! There are likely a decent number of us with older vehicles that lack AA.

**Comment by DmitryAlexei** [comment] 2024-11-19 16:58
To be implemented:
- [ ] before attempting to reconnect you should check, that OBD plugin is on and widgets are added to the navigation profile (if no, no reconnection) 
- [ ] app should try to connect to the pre-connected OBD, 2 attempts will be enough

**Comment by Zirochkabila** [comment] 2024-11-26 15:30
**Cannot be tested** - OsmAnd **crashes** if connected to simulated sensors and display widgets on the main screen


https://github.com/user-attachments/assets/c7b9d4d3-a67f-4ef9-9916-547bf6448075

**Comment by Corwin-Kh** [comment] 2024-11-26 16:38
Not reproduced on last build

**Comment by Chumva** [comment] 2024-11-27 12:26
Crash should be fixed [here](https://github.com/osmandapp/OsmAnd/pull/21463)

**Closed by Chumva** 2024-11-27 12:26 UTC
Labels: Observed

**Comment by Zirochkabila** [comment] 2024-11-28 11:33
> This depends on your car and the model of your OBD Bluetooth adapter. In most cases:
> 	1.	OBD port always active: If the OBD port receives power even after the ignition is off, the Bluetooth adapter will stay on until you manually unplug it.
> 	2.	OBD port powers down with ignition: In some cars, the OBD port automatically loses power when the ignition is turned off. In this case, the Bluetooth adapter will also turn off.


Considering the **first point** above, this behavior can only be tested with the actual presence of OBD sensors.

However, if we consider the **second point**, this case can be tested by turning Bluetooth off and on (on the mobile device, as demonstrated in the video).

**Therefore, the issue is **still present**, as after “Turn off car ignition, Turn on car ignition” - “Turn off, Turn on Bluetooth module,” the Bluetooth connection does not automatically reconnect.**


`OsmAnd~ 5.0.0#3830m, Released: 2024-11-28`


https://github.com/user-attachments/assets/1dedacfc-fbd6-4b64-a887-fc05ccc4ce34

**Comment by vshcherb** [comment] 2024-11-28 11:35
I've tested with real device and real car and with AA it works as expected. Based on the code I see, once route is calculated (after restart or in old session) attempt to reconnect widgets will be made
