### ISSUE TITLE
Track distance 

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#9956] opened 2020-10-06 07:46 UTC
[ezyzip.zip](https://github.com/osmandapp/OsmAnd/files/5332126/ezyzip.zip)

track's distance is different in the description and Plan a route
![image](https://user-images.githubusercontent.com/50198677/95173062-dd216280-07c0-11eb-9736-ac405bbfb910.png)
![image](https://user-images.githubusercontent.com/50198677/95173074-e0b4e980-07c0-11eb-903f-cf1fff3f1d8c.png)

OsmAnd Version: 3.8

**Comment by njohnston** [comment] 2020-10-07 08:34
Possible duplicate of #9869.

**Comment by pebogufi** [comment] 2020-10-07 09:37
On recorded tracks distance looks identical.

**Comment by pebogufi** [comment] 2020-10-07 14:04
if i have a gpx file with more than one track, and click on one of them, the information should not be displayed of the whole file, but of THIS tack.

**Comment by vshcherb** [comment] 2020-10-07 18:37
Duplicate https://github.com/osmandapp/OsmAnd/issues/9869

**Closed** 2020-10-07 18:37 UTC
