### ISSUE TITLE
Cluttered map

### ISSUE THREAD

**Issue by FTno** [osmandapp/Osmand#9490] opened 2020-07-20 16:43 UTC
As seen in the map screenshot from Osmand below it is cluttered with OSL...

![Screenshot_Osmand](https://user-images.githubusercontent.com/16176811/87962387-645f1400-cab7-11ea-9b1a-98a635293e6e.png)

I'm not sure what this is all about, but in OSM (https://www.openstreetmap.org/#map=12/60.0191/10.6585) there is no such clutter in the same area, as can be seen in the next screenshot.

![Screenshot_OSM](https://user-images.githubusercontent.com/16176811/87962423-72149980-cab7-11ea-9e41-6ac4adb66b20.png)

Osmand 3.7.4
Norway offline map 1. jul. 2020

**Comment by xmd5a2** [comment] 2020-07-23 13:27
Duplicate of https://github.com/osmandapp/Osmand/issues/9070
![Screenshot from 2020-07-23 16-23-53](https://user-images.githubusercontent.com/5829014/88291456-f017b100-cd00-11ea-8b78-4bfe8f3d8c95.png)
Fixed

**Closed by xmd5a2** 2020-07-23 13:27 UTC
