### ISSUE TITLE
Backup as file opens the share menu instead of saving the file 

### ISSUE THREAD

**Issue by arncor** [osmandapp/OsmAnd#15146] opened 2022-08-23 20:25 UTC
### Description

When trying to backup everything as a file, at the last step, osmand opens the share menu with useless choices instead of just saving the backup file. 

### How to reproduce?

Go to settings > backup and restore > back up as file 
Select everything except maps (to reduce the backup size), press continue, a progress bar shows up and when it reaches the end, the android share menu shows up (you can choose many apps but no way to save the file directly onto the sd card). 

### Your Environment
OsmAnd Version: 4.2.6 fdroid
Android version: 9
Device model: Ulefone Armor 6E

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by scaidermern** [comment] 2022-08-24 05:58
Duplicate of #12264.

**Comment by arncor** [comment] 2022-08-24 08:10
> Duplicate of #12264.

Yes you're right, sorry my prior search wasn't thorough enough...

**Comment by vshcherb** [comment] 2022-08-24 13:31
Merged to https://github.com/osmandapp/OsmAnd/issues/12264

**Closed** 2022-08-24 13:31 UTC
