### ISSUE TITLE
Directions dialog laggy while GPX tracks are displayed

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#6740] opened 2019-03-25 07:31 UTC
I just notice that our new 'Directions' UI reproducibly reacts extremely laggy when I have one or more GPX files displayed on the map. There is an enormous  time lag of beteeen 7 and 16 seconds (!) between when you tap the map screen's 'Directions' button and when the dialog finally appears.

Also then tapping actions on the new dialog itself like 'Previos route' seems to carry a time lag of several seconds before reacting.

Looks like the app is VERY busy doing 'something' in this state. The navigation portion of OsmAnd 3.3.6  is almost unusable, at least on older devices with many (dozens/hundreds of) files in the tracks folder.

This is reproducibly gone when you deselect all GPX files from being displayed on the map. Also: Having 'Show current track' selected does not cause the issue as long as there is no current track.

**Comment by sonora** [comment] 2019-03-25 08:47
I guess the issue started when we added GPX card to route info (probably https://github.com/osmandapp/Osmand/commit/24fcf4bfa83078073f105f65b764f692cb66678b), may have to remove that functionality, unless we find a performant way to do it. Navigation is pretty unusable for many users as is now.

**Comment by scaidermern** [comment] 2019-03-25 10:44
Is it (from a technical point of view) possible to collapse the list of activated GPX track and let OsmAnd populate it dynamically when the user expands it? This will at least move the performance problem. It still needs to get investigated, of course.

**Comment by sonora** [comment] 2019-03-25 12:35
Just found out that displaying tracks with just waypoints does not cause the issue. It seems the app is not non-reponsive by finding out which tracks are selected as visible, but rather somehow by analyzing the content of visible tracks with trp points?

**Comment by crimean** [comment] 2019-03-26 09:36
@sonora thank you for report, but we cannot reproduce the issue. BTW - there no some new code. I just moved previous dialog with requesting route along the GPX to the card.

**Comment by sonora** [comment] 2019-03-26 22:57
Thanks for checking! I am currently out traveling and have only 2 devices on me: A Samsung S4 mini (stock ROM Android 4.4.2), and a Samsung XCover 4 (stock ROM Android 8.1.0).

I have just verified with our master-nb build of 3/26 that the XCover does NOT show the issue at all! But it is 100% reproducible on the S4mini. It is not the number of gpx files which causes the issue:  I usually carry over 2000 GPX files in some 40 sub-folders of our tracks folder on each device. But I can perfectly reproduce the issue on the S4mini also with a fresh tracks folder and just one gpx file in it.

Looks like the issue may only affect older Android APIs, not sure. Maybe other users can post their experience here to see which devices are affected.

**Comment by sonora** [comment] 2019-03-27 06:37
Interesting also: Displaying the Dashboard is never laggy, this only affects the new Directions dialog.

**Comment by sonora** [comment] 2019-03-27 08:34
I have checked our code and could not find anything I suspect to be API version specific. I think what we are dealing with here is a case of GPX database corruption. Maybe this happened because of gping back and forth between versions on this device because it is one where I heavily test all our new releases.

For those who also experience this,it can be resolved as follows:

In a file manager, rename the (correct!) net.osmand (.plus) data folder. Then in Android settings, force stop OsmAnd, then reset the app data. Then restart OsmAnd, and restore your preferred app settings (in particular the data folder location), but skip the map download. Then in a file manager again, delete the newly created data folder and rename the old one back.

For me this also resolved some other lagginess like when opening My Places or Configure map/GPX files.

If it is just from my heavy version testing, we can probably ignore this issue. But if other users experience this in regular use, we may have to implement better protection against database corruption or implement a regular or manual reset? I am not even sure it is the db, or some other caching? In any case, it is resolved per device by the above procedure.

**Comment by njohnston** [comment] 2019-05-28 16:35
Since I installed OsmAnd+ 3.3.8 on my Samsung Galaxy S8+, I have the same problem as @sonora, and it's rather annoying. Unlike @sonora , I do not use this phone for testing: I only install the released OsmAnd+ versions from Google Play.

I looked at `logcat` output but didn't see any clues. I haven't yet tried the workaround, because it seems rather disruptive, and I don't want to restore all my settings by hand unless absolutely necessary.

An extra setting such as "Do not suggest using displayed tracks for navigation" could be useful. I know some people use OsmAnd's support for navigating along tracks, but for me (and many others I suspect), showing the tracks is pointless. They appear after I have selected a point and pressed "Directions" to set the destination, even if the tracks are for thousands for kilometres away.

**Comment by sonora** [comment] 2019-05-28 18:00
I am rather convinced it has to do with our GPX database, either it can become corrupted, or maybe this happens in a transient fashion while it is being updated to a new version.

I sometimes also do get related crashes when accessing the GPX tracks too soon during an app restart, particularly after an app version change when testing something. Related seems also what I reported in (2) and (3) of https://github.com/osmandapp/Osmand/issues/6943, including a related "index out of bounds" crash report attached there.

**Comment by sonora** [comment] 2019-07-20 09:49
Just for the record: The issue has returned for me on an S4 mini, so it was not a one-time effect. I reopen this issue so we keep it on the radar for further feedback and investigation.

**Comment by scaidermern** [comment] 2019-09-25 18:03
Not sure if this is caused by the same bug. The track overview located under my places is also super slow. Opening a track, closing a track and deleting a track takes multiple seconds. Looks like OsmAnd is reindexing all tracks each time or performs other unnecessary calculations on each of these actions. This is really annoying.

**Comment by sonora** [comment] 2019-10-09 13:24
Regarding scaidermem's observation: Yes, I have the same observation from time to time. Annoying. I am convinced it is a bug, we are performing some unnecessary, costly operation under some circumstances.

**Comment by scaidermern** [comment] 2019-10-09 14:21
> Regarding scaidermem's observation: Yes, I have the same observation from time to time. Annoying. I am convinced it is a bug, we are performing some unnecessary, costly operation under some circumstances.

To me it looks like these costly operations are always performed. Even when switching to a different app and switching back to OsmAnd with the track overview opened. The screen freezes for several seconds until it finally gets shown. This doesn't happen in any other settings but only with the track overview.

**Comment by max-klaus** [comment] 2019-10-14 15:34
Made some fix that could impact on the issue (https://github.com/osmandapp/Osmand/commit/e9eb1fd2a01038013b3243d026e75046342b8273)
Looks like we were calling gpx database at the gpx layer. Please check if issue is still present.

**Comment by sonora** [comment] 2019-10-14 21:20
Thanks, but by my testing both issues described above are still in our latest nightly.

**Comment by vshcherb** [comment] 2019-10-15 14:31
If you see ANR screen, probably you can send it via Google ANR-report and we can see it in console

**Comment by sonora** [comment] 2019-10-16 13:54
There is no ANR for me, it is just awfully slow, like there is a complete pause of 5+ seconds before either the Directions or the My places screen appears. The pause seems to always occur for the My places screen, and for the Directions screen only if any (or several) GPX tracks are being displayed on the map. The 'currently recorded' track is excluded, it alone does not cause the hang.

As I said, reinstallation seems to fix it for a while, then it comes back.

**Comment by max-klaus** [comment] 2019-10-24 18:35
@sonora Could you please test again after small fix (https://github.com/osmandapp/Osmand/commit/222b0ccaad712bb0dfa3f685e7945d1297320d75)

**Comment by sonora** [comment] 2019-10-24 22:03
Unfortunately no luck here. Also with this new nightly, on my current test device:
- If there are tracks displayed, after tapping the Directions button the OsmAnd screen freezes for 12 seconds duting which it reacts to no taps, zooming or panning at all
- In all cases: Tapping 'My places' (or in some other fashion going to / returning to the fav/track list screen) causes an about 12 second delay (hang) before the favorite list shows up. During that tine the OsmAnd screen is entirely black (I use the dark theme)

**Closed** 2019-10-27 17:06 UTC

**Comment by max-klaus** [comment] 2019-10-27 17:08
@sonora Please check this fix. 
Is there opened issues about losing recordings?

**Comment by sonora** [comment] 2019-10-27 23:10
@max-klaus  That does the trick, I think! WELL DONE! A huge performance plus for anybody using lots of gpx and favorite data!
Thx - Hardy

The issue I recently saw about track saving, though I use it frequently and never had an issue myself so far, is #7666, and Victor's summary is #7712.
