### ISSUE TITLE
option without freeway, impossible to calculate route on freeway

### ISSUE THREAD

**Issue by sazearte** [osmandapp/OsmAnd#18365] opened 2023-10-17 09:21 UTC
### Description

Hello, when I'm on the freeway, if I ask osmand to calculate a route without freeway, it can't calculate a route.
I have to leave the freeway, restart the route calculation for it to work.

I think the best behavior would be for him to calculate a route and get me off the highway as quickly as possible.
what do you think?

i use the last version (osmand plus 4.10)

### Steps to reproduce

go to a freeway and start a route without freeway

### Actual result

impossible to calculate a route

### Expected result

calculate a route and get me off the highway as quickly as possible.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.10
Android/iOS version: 11
Device model:  xiaomi 11
```

**Comment by DmitryAlexei** [comment] 2023-10-17 12:49
duplicate of https://github.com/osmandapp/OsmAnd/issues/16452

**Comment by sazearte** [comment] 2023-10-19 12:36
i use OsmAnd~ 4.5.10
I'll test it when 4.6 comes out (it's beta for the moment right ?), if the bug is fixed that's great :)

**Comment by vshcherb** [comment] 2023-10-20 18:56
Yes motorway is not excluded but gives a huge penalty so it should be possible to calculate route as on video.

**Closed by vshcherb** 2023-10-20 18:56 UTC
