### ISSUE TITLE
Not rendered landuse=residential causing flooded areas

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8743] opened 2020-04-01 10:03 UTC
When enabling Configure map - Details - More details or in the Touring view map style, the area in Netherlands, 52.15235/4.78458, is flooded

![image](https://user-images.githubusercontent.com/50198677/78124995-1e534700-7419-11ea-907a-a8202922b07c.png)
![image](https://user-images.githubusercontent.com/50198677/78125015-21e6ce00-7419-11ea-8d90-63c5db9093bc.png)

**Comment by AnkEric** [comment] 2020-04-01 11:36
Correction, addition:
Not "flooded", which means water OVER land.
But [landuse=residential] is OVER [natural=water].
So: too little [natural=water] is visible, too much [landuse=residential] is visible in first image.
Second image is okay.

IMO: this is an issue in Map Style "draworder".
To reproduce, Configure Map:
- Map Style “OsmAnd” is okay, Map Style “Touring view” is not okay;
- Details: “More details” = [no] is okay, “More details” = [yes] is not okay.

/ AnkEric

**Comment by vshcherb** [comment] 2020-04-09 15:05
This is an issue of map data cause residential should not overlap water

**Comment by AnkEric** [comment] 2020-04-10 11:46
> This is an issue of map data cause residential should not overlap water

I couldn't disagree more!

Configure map, MapStyle = "OsmAnd" will render OK.
Configure map, MapStyle = "Touring View" will render NOT OK.

Configure map, Details, "More details" = <no> will render OK
Configure map, Details, "More details" = <yes> will render NOT OK

So: "an issue of map data" will be rendered OK by OsmAnd AND will be rendered NOT OK by OsmAnd, depending on "Configuration map".
Which is an "issue of OsmAnd not rendering consistently".

> issue of map data cause residential should not overlap water

I agree.
Most specific [landuse=...] and [natural=...] in the west part of the Netherlands (where I live) is "garbage", "sloppy", "messy": overlapping, crossing, duplicated, flooding, white space gaps (OsmAnd only), unconnected. 
Even more specific: [landuse=residential] is extreme garbage. [landuse=residential] will cross/overlap [landuse=forest/grass], [natural=water/wetland], [building=...].
Three houses in a green area will be mapped by an overly large [landuse=residential] area covering a complete area of "green meadows". Because it's easier to draw one area instead of three.
And to make things even worse: a Dutch OSM Mapper once replied to me: it's "best practice" to draw [landuse=residential] inside [natural=water]. My method to follow/connect [landuse=residential] and [landuse=.../natural=...] was considered to be "overdone".

It's best practice for a Renderer to Render [natural=water] ON TOP of [landuse=...] (draworder).
Because water IS ALWAYS on top of landuse. Unless it's "ground water", but this is not rendered because it's not visible "on the ground".
Only objects to be rendered ON TOP of water: [pier], [bridge], [highway], [building], "floating Solar panels", and... 

It's best practice for a Renderer to CORRECT Mapping Errors if Rendering these Errors will produce a BAD Map. And yes, it's a challenge to do so.

I know, OSM states: "Don't Map for the Renderer" (nonsense: "Don't Map INCORRECTLY for the Renderer just to have an object being Rendered by your own preferences") and this - bad - attitude implies a challenge for a Renderer to produce a GOOD Map based on – sometimes – SLOPPY or MESSY OSM Data.

Also: Fix OSM data "residential should not overlap water" would take years to accomplish. And would be "mopping with the tap open".

As a Renderer myself, I have resolved the issue by:
landuse=residential & mkgmap:country=NLD {delete landuse}
In the Netherlands ALL buildings have been imported into OSM from land registry data.
So [landuse=residential] is where the buildings are and not being [landuse=farmyard/industrial/retail].
IMO: [landuse=residential] IN THE NETHERLANDS is SLOPPY, MESSY and USELESS.
I don't know if other countries also have all buildings imported into OSM.

Not rendering [landuse=residential] by OsmAnd would be acceptable to me (I can see buildings "on the ground" while traveling, but I will never navigate to a residential area), but I guess I am alone in this opinion.
Water "hidden" underneath landuse is unacceptable: IMO.
On the other hand: If OsmAnd Map quality is downgraded by Rendering sloppy [landuse=residential] and Users don't agree with OsmAnd not rendering [landuse=residential], than these users should correct sloppy [landuse=residential].

**Comment by sonora** [comment] 2020-04-10 15:42
Our order statement for landuse=residential in default render is blanked out, not currently sure why ...

(Touring view draws more details than default for details=yes, so that could explain why Touring view suffers more from this issue than the default renderer itself.)

**Comment by sonora** [comment] 2020-04-10 16:27
I think landuse=residential belongs on level 5, where we also have most other basic landuse (and even cemetary!). This seems risk-free. Water is also on 5, but changing water would require major verification and a long cascade of other changes.

**Comment by vshcherb** [comment] 2020-04-14 16:19
I also struggle quite a lot with overlapping areas in the Netherlands in OSM. It is really a big mess caused by initial ANT import. 
By default everything is land and OsmAnd is not an exception, water should be filled in only when it is needed. If an island exists inside water it should be displayed correctly though 
* We always should avoid situation when areas are not exist inside each other but overlap. It is really a bad practice cause every slight change to the areas will change the order of display and it will be incorrect * 

@sonora residential and water are rendered on the same level to be sorted by area and no change here could be done cause it will create other unwanted side-effects

**Comment by vshcherb** [comment] 2020-04-14 16:24
Reaction to different rendering styles: every rendering style serves own purposes and decides to display certain types of objects, so obviously they have different rendering output. 

I don't think is 'landuse=residential' is an island synonym.

**Comment by AnkEric** [comment] 2020-04-14 18:32
I don't dare saying anything (I'm Dutch).
And I do know: this area is extremely difficult (hundreds of islands, grass over residential IN multipolygon water) but also an extreme mess!

FWIW, Garmin Maps default style draworder:

- residential (0x010) = 2
- grass (0x01c) = 2
- water (0x03c) = 5

> @sonora: I think landuse=residential belongs on level 5

I think landuse=residential belongs on level 2 as compared to Garmin mkgmap default style. 
In the past "we" even did {set residential to "layer=-1"} to make sure it's underneath everything.
Residential is only visible if we can see the ground.

Blades of grass was stopped being rendered completely on some Dutch Maps years ago. 
Grass is now simply:  {background, color = green}. Which reduced map size by 10%.

> @vshcherb: We always should avoid situation when areas are not exist inside each other but overlap.

Again, I couldn't agree more. But also: dream on. ALL water in this part of the Netherlands is OVER grass (I will resolve every month and within three months garbage is back), landuse/natural and landuse=residential are (almost) ALWAYS overlapping.

> @AnkEric: 

Is "Detail" or "Touring view" really this important??
Please verify by comparing two OsmAnd maps side by side!

**Comment by sonora** [comment] 2020-04-14 20:06
For what it's worth, I think this would fix it: https://github.com/osmandapp/OsmAnd-resources/pull/614

**Comment by vshcherb** [comment] 2020-04-16 14:37
@sonora We don't render "landuse=residential" so I don't think it is a correct fix

**Comment by vshcherb** [comment] 2020-04-16 14:48
All the orders are made aligned with Mapnik, so we don't break compatibility with other places. The only question here that default rendering style doesn't render "landuse=residential"

**Comment by sonora** [comment] 2020-04-16 20:57
Here are the screenshots without and with the little fix I proposed above:

![Screenshot_20200416-224559_OsmAnd~](https://user-images.githubusercontent.com/845735/79505910-6ab39f00-8035-11ea-94ab-800975c7d6a1.jpg) ![Screenshot_20200416-224624_OsmAnd~](https://user-images.githubusercontent.com/845735/79505907-69827200-8035-11ea-93f5-d68972887e84.jpg)

**Comment by AnkEric** [comment] 2020-04-17 07:59
Impressive, great, thanks!

1. A side-by-side image is by far better than my original two images (but for me it's a challence to create a side-by-side image, or too much effort).
2. North upwards image is by far more obvious than the two up-side-down images created by OsmAnd Help Desk.
3. The result is exactly as I was hoping for: landuse is rendered and landuse is not covering/hiding water. Now, looking at the map, is quite obvious why this is one of the best - nearby - places to have dinner with a view! Although no option for tonight (Corona).

OT (perhaps new ticket for OsmAnd): I stumbled upon this problem because only [tourism=viewpoint] is rendered by OsmAnd. Not rendered (only minor visibility by polygon, no POI) is:

- leisure=outdoor_seating
- operator=Restaurant Tijsterman
- restaurant=yes
- weather_protection=parasol 

Out of curiosity:

- How does your applied fix relate to selected Map Style ("OsmAnd" or "Touring view") and to Details ("yes" or "no")?
- Was the issue related to draworder? Or not?

**Comment by sonora** [comment] 2020-04-17 19:54
@AnkEric The fix implements the theorem that landuse=residential should never cover water, no matter wrong people map. The fix includes Touring view and More details=yes/no.

I would need a little more time,  but it may be worth to systematically go through the bottom layers of our default renderer to detect similar effects we could easily fix. This requires a systematic activity, I once did it in aspreadsheet years ago for a childhood generation of our renderers. :)

**Comment by vshcherb** [comment] 2020-04-20 12:55
I cc @xmd5a2 cause indeed Touring view / more details yes/no could be reviewed and fixed though there is no agreement on rendering "residential" by default. As for now we would like to avoid that situation and render other objects

**Closed** 2020-04-20 14:27 UTC
Labels: Observed

**Comment by xmd5a2** [comment] 2020-04-20 14:29
Manually applied Hardy's fix, but as side effect if landuse=residential is inside water polygon then it will be hidden. But it is a more rare situation and usually is an error.

**Comment by AnkEric** [comment] 2020-04-20 14:52
> if landuse=residential is inside water polygon then it will be hidden

- But it is a more rare situation: +1
- and usually is an mapping error: +2

So: I'm - very - happy with this result!

But in my original ticket I have stated, I noticed this issue in two instances (details and/or Touring View).
I did not investigate other Map Configuration options. Now I did.
Other Map Styles having the same issue:
LightRS, Mapnik, Nautical, UniRS.
