### ISSUE TITLE
Multi-polygon water bodies not rendered properly

### ISSUE THREAD

**Issue by james2432** [osmandapp/Osmand#1535] opened 2015-08-05 18:00 UTC
I've noticed when water is a huge multi-polygon they render as beige instead of blue on the map
Example:
http://www.openstreetmap.org/#map=14/45.4663/-75.6211
renders like this:
http://i.imgur.com/zzD1qsO.png

**Comment by vshcherb** [comment] 2015-08-05 22:02
May be there is a boundary issue ?

**Comment by james2432** [comment] 2015-08-05 22:05
The boundery is correct, but might be what is causing it

**Comment by sonora** [comment] 2015-08-06 16:56
Victor, not sure, we may in deed have a new issue here. Take any place on
the Mediterranean coast, Spain, Italy, etc.

Old builds render the sea ok, newer builds seem to fail. see two
screenshots attached the file names denote the build dates used.

Best, Hardy

**Comment by sonora** [comment] 2015-08-06 21:16
PS: Looks like the issue started with our nightly build of July 25.

**Comment by xmd5a2** [comment] 2015-08-07 19:26
I have discovered some things. All multipolygons that are crossing poly (boundary of extraction area) are included  in our OSM extracts. But these multipolygons are missing in obf maps. I checked this relation http://www.openstreetmap.org/relation/2711743
and this way http://www.openstreetmap.org/way/220248439
All of them are included in extracts but missing in maps (checked by osmconvert and josm). So I think it's an obf related issue.

**Comment by fnicollet** [comment] 2015-08-12 21:15
Also interested in this issue, having the same rendering (or data?) bug in Belleville (Ontario region, Canada). The river across it doesn't get rendered

**Comment by vshcherb** [comment] 2015-08-31 22:21
Coastline is completely different issue because it is not a multipolygon technically :) 
About this issue generated a small map and I don't really see it.
https://www.dropbox.com/s/pf8q5jfpr3xnxgp/Screenshot%202015-09-01%2000.19.09.png?dl=0
https://www.dropbox.com/s/ji9y8t2w2u0iixq/map.osm.zip?dl=0
https://www.dropbox.com/s/eg2wt11getnisl6/Map.obf?dl=0

**Comment by vshcherb** [comment] 2015-08-31 23:45
Coastline issue confirmed and fixed

**Comment by xmd5a2** [comment] 2015-09-01 08:29
Can't reproduce issue at all with new maps from 06.08.2015. I have old map dated 24.06.2015. See screenshot (top - old map, bottom - new map). But I have'nt changed anything related to this.
https://dl.dropboxusercontent.com/u/4624786/osm/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2015-09-01_11-16-15.png

**Comment by sonora** [comment] 2015-09-01 22:19
I just checked the latest build (still with my old maps), and the coastline issue really seems fixed now. Thanks - Hardy

**Comment by james2432** [comment] 2015-09-10 01:02
![tmp_2807-screenshot_2015-09-09-20-57-33-2144256689](https://cloud.githubusercontent.com/assets/498547/9777712/bf65805a-5735-11e5-9689-98caa098db2a.png)
Not sure if this is related but I get a weird map flooding effect around 2km scale. I no longer get the water not showing up as I used to with 06/09/2015 version of map

**Closed** 2015-09-27 22:16 UTC
