### ISSUE TITLE
Endless route calculation

### ISSUE THREAD

**Issue by tuxayo** [osmandapp/Osmand#5922] opened 2018-08-22 19:34 UTC
I can reproduce this.
I'll still wait if the routing calculation finishes and update the time until I give up.
It's been 20 minute for [this 300 km car route](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=43.28593%2C5.37760%3B45.05650%2C6.52976#map=8/44.449/7.262)
The logs keep getting spammed at the rate of 2100 times per seconds

#### Context:
OsmAnd version: 3.1.6 from F-Droid
Phone: Nexus 5
Android version: 7.1.2 (LineageOS for microG 14.1)

#### Logs:
[logcat.txt](https://github.com/osmandapp/Osmand/files/2311730/logcat.txt)
- started logging
- ran the app
- launched last route calculation
- stopped logging

**Comment by tuxayo** [comment] 2018-08-23 20:07
Ok I forgot the phone.
It's hot, the `top` command show that 2 over 4 CPU threads are used by OsmAnd. (53% CPU usage on quad core processor)
And I can tell that the routing calculation is moving forward.

It's still spamming the logs.
Much most slowly. Few dozens of lines per seconds.
So the operation that triggers the logs is happening less frequently.
It might be an indication about which part of the routing process is happening. (or maybe it's just an algorithm that goes slower and slower as it's goes far in the graph)

Anyway I stopped it. It's been 3 hours and some temperature sensors report 65°C

**Comment by PaulStets** [comment] 2018-09-17 07:50
Sorry, but I cannot reproduce this with the latest nightly. The log statement was commented out.
For me, the route is calculated within a minute. Could you please specify the device model and the Android version you have?
![image](https://user-images.githubusercontent.com/20681525/45611241-6a24e200-ba67-11e8-92db-c5c50774906f.png)

**Comment by tuxayo** [comment] 2018-09-17 10:33
I haven't downloaded that region so I can't try the same itinerary as you.

Can you try the [same itinerary](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=43.28593%2C5.37760%3B45.05650%2C6.52976#map=8/44.449/7.262) as me?

I can still reproduce on a Galaxy S5 
OsmAnd version: 3.1.6 from F-Droid
Android version: 7.1.2 (LineageOS for microG 14.1)

[logcat-S5.txt](https://github.com/osmandapp/Osmand/files/2388170/logcat-S5.txt)

I can't retry on the Nexus 5 of the original report because of #6051 😭

**Comment by PaulStets** [comment] 2018-09-17 15:20
@tuxayo The route on the screenshot uses the exact points from the itinerary you provided. Please make sure you use the latest maps. It would also be great if you could test the nightly version.

**Comment by tuxayo** [comment] 2018-09-19 20:29
I can reproduce on a Wiko CINK PEAX 2
- Android 4.1.2 (stock ROM)
- OsmAnd 3.1.6 from F-Droid, fresh install

**Comment by tuxayo** [comment] 2018-09-19 21:40
I can reproduce with latest nighly on same Galaxy S5 as one of the previous reports.

As you said, the logging statement is commented. So at least I don't end up with more than a million of lines and a more than 100MiB file

It still doesn't seems to route faster and will likely get killed due to lack of RAM.

**Comment by PaulStets** [comment] 2018-09-20 12:41
@tuxayo We have looked into the issue. Seems like this month's map of the region was generated with an error. The routing log shows the following:```Warning not connected road  9742998015```. The problem is with this way:https://www.openstreetmap.org/way/152234343#map=16/45.0284/6.5564. Somehow it was not connected to the other segments. You can check this by shifting the endpoint to the beginning of this way.
It should be fixed with the next map update, however, if it isn't fixed next month, please re-open this issue.

**Comment by tuxayo** [comment] 2018-10-08 13:18
I can still reproduce with the October maps.

@PaulStets 

> The problem is with this way:https://www.openstreetmap.org/way/152234343#map=16/45.0284/6.5564. Somehow it was not connected to the other segments.

If OpenStreetMap data has a mapping mistake, then why «Seems like this month's map of the region was generated with an error.» which seems to mention an OsmAnd processing mistake?
Maybe I didn't understand something.

> The problem is with this way:https://www.openstreetmap.org/way/152234343#map=16/45.0284/6.5564. Somehow it was not connected to the other segments.

I had checked this When you posted you reply. Using JOSM, the way was connected and history didn't show a recent fix.
And this does match the facts that OSRM and Graphopper were able to route. And that OsmAnd can route from a less long distance than Marseille.
And now when I reproduce I can not route (*from Marseille, distance is important*) at the end of this way. But I can route at the beginning of this way. This is very disturbing. I reproduced dozens of time to find the "point of no routing". And recheck now to confirm that this isn't a mistake or my imagination.

>  It should be fixed with the next map update, however, if it isn't fixed next month, please re-open this issue.

I can't :P

**Comment by tuxayo** [comment] 2018-11-02 10:56
Additional info: it's possible to know in advance that the routing is deemed to take forever by looking at the progress bar:
- will finish: it progresses regularly and takes 10/15 sec to the first 98% of the screen(the last 2% takes most of the time)
- will not finish: jumps to 80% in 2 seconds


(note: I can still reproduce on latest nightly.)

**Comment by xmd5a2** [comment] 2019-04-04 12:57
In my tests I get NPE with OsmAndMapCreator

> SEVERE: Error occurred
java.lang.NullPointerException
	at net.osmand.router.PrecalculatedRouteDirection.build(PrecalculatedRouteDirection.java:78)
	at net.osmand.router.RoutePlannerFrontEnd.searchRoute(RoutePlannerFrontEnd.java:187)
	at net.osmand.swing.MapRouterLayer.selfRoute(MapRouterLayer.java:730)
	at net.osmand.swing.MapRouterLayer$17.run(MapRouterLayer.java:351)

And endless GC on device
`04-04 15:56:56.320  5325 13312 I net.osmand:native: Run GC (before 57.643135 Mb after 44.728491 Mb) unload 155 of 715 tiles`

**Comment by vshcherb** [comment] 2019-07-08 16:16
It can't calculate point directly to 45.056, 6.530 cause this road is not routable somehow (probably road graph is broken) but the route but the route to this point could be calculated pretty fast https://www.openstreetmap.org/#map=16/45.0188/6.6077

**Closed** 2019-07-08 16:29 UTC

**Comment by vshcherb** [comment] 2019-07-08 16:53
This is quite exceptional case, the endless calculation is fixed, though it is not possible today to calculate exactly to that point. It is possible to do a bit earlier 2-3 km and via waypoint
