### ISSUE TITLE
Zoom in/out is very slow

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#5007] opened 2018-02-10 14:01 UTC
Zoom in/out is very slow on android 8.0 and 8.1. It can only be fixed by disabling animation in OsmAnd. Also reproducible on OsmAnd 2.7.
![screenshot_einstellungen_20180207-132054](https://user-images.githubusercontent.com/12711814/36062775-a42240e4-0e7b-11e8-93a5-23f734702385.png)

**Comment by scaidermern** [comment] 2018-02-10 19:13
Duplicate of #4323.

**Closed** 2018-03-08 06:56 UTC

**Comment by ADepic** [comment] 2018-06-03 18:49
Disabling animations doesn't fix this for me.

OS: Lineage OS 15.1 (oreo 8.1)
Device: Oneplus 2
