### ISSUE TITLE
Water disappears from marine chart when zooming

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#18593] opened 2023-11-20 14:54 UTC
### Description

Here's a track of a recent paddle. If I zoom to view better, the lake disappears and the track is drawn against ground color (on a marine chart, ground is beige.

### Steps to reproduce

View a track on a marine chart and zoom in.

### Actual result

The (water) blue disappears and the nautical track appears on ground.

### Expected result

Water should be blue on a marine chart, and should remain blue when zooming, which is not the case here.

I suspect Osmand+ sort of froze during map redraw. I later had to force kill it to fetch its version. Map redraw then returned no normal.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/57163823/f761798e-1dba-4588-9f0b-49a9fff06d8f"  width="300" height="auto"/> </td>
  </tr>
</table>

### Your Environment (required)

OsmAnd Version: 4.5.10
Android/iOS version: 8
Device model: Samsung Galaxy A5 (2017) cellphone
Crash-Logs: None

**Comment by DmitryAlexei** [comment] 2023-11-22 11:00
to test:
- go to coordinates [44.7902590, -73.1577639](https://www.openstreetmap.org/#map=18/44.7902590/-73.1577639) and check water display in water profile

**Comment by yuriiurshuliak** [comment] 2023-11-24 16:12
The bug was not reproduced. Here are the steps:

- Choose the boat profile and activate the Nautical map view plugin.
- Download the Nautical maps and configure the Nautical map style for the required profile.
- Navigate to coordinates 44.80953° N, 73.18500° W and build a navigation.
- Attempt actions like maximum zooming of the map, profile switching, closing and reopening the application, etc.

Under such conditions, the bug was not reproduced. Please provide more details on how step by step you are noticing this bug. Also import us your profile settings.

Also try to reinstall the application and update the map and let us know the result.

OsmAnd~ 4.6.0#1086m, released: 2023-11-24

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/73ae18c4-8870-43c7-98a4-889193646275"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a4ac6dfa-bac9-4e5f-99d5-74769826ea59"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by speleoluc** [comment] 2023-11-26 21:32
Here are my settings, just change the extension to OSF.

[Export_2023-11-26.txt](https://github.com/osmandapp/OsmAnd/files/13468129/Export_2023-11-26.txt)

BTW, the export progress line starts at NAN% ;)

Like I wrote earlier, everything came back to normal after doing a force close of the app.

**Closed** 2024-02-01 15:06 UTC

**Comment by josail** [comment] 2024-06-28 18:54
@vshcherb  
may I ask you to reopen or double check this issue. I can clearly reproduce this in iOS OSMAND Version 4.7.6 as follows and especially at following location: 

https://osmand.net/map/#17/36.66918/25.38369

![IMG_2133_small](https://github.com/osmandapp/OsmAnd/assets/93162192/67626d28-7a64-4866-a8d7-45768f524c8b)
![IMG_2131_small](https://github.com/osmandapp/OsmAnd/assets/93162192/2da78d7b-3090-4f10-beac-6ab333cbd548)
![IMG_2132_small](https://github.com/osmandapp/OsmAnd/assets/93162192/7ea11453-8e40-4ec7-a9df-a26d92ab4203)

to reproduce, open this location in OSMAND app, hover over the bay in different zoom levels 16, 17, 18 and see how the squares of yellow extend into and appear in the water of the bay of Tris Klissies

I reporduced this behavior at another location just one bay to the north, Papas bay, but nowhere as prominent as at this location. Most often it is restricted to a little square at the side of the water or linearisation of a section of coastline.

However, it seems not to appear in many other narrow bays in the area?

Can this be traced to the source of error and improved either in OSMAND or is there something special in the OSM data in these bays that is causing a problem?

**Comment by josail** [comment] 2024-06-28 19:15
This is in Papas bay @Zoom18.7 and after updating all relevant map data for this area, including the global seamark-basic chart

https://osmand.net/map/#17/36.68440/25.38501

![IMG_2141_small](https://github.com/osmandapp/OsmAnd/assets/93162192/0b80d2dd-8854-47da-b3f0-f4d8c196b40d)

**Comment by josail** [comment] 2024-06-28 19:18
Could it be related to the area OSM data in the water for the fill pattern of seagrass? It's a seamark, so it should not be a problem, but the area related OSM data might trigger something additional (not only the seagrass fill pattern) in the rendering?

**Comment by josail** [comment] 2024-06-28 19:46
However, reproducible also in the German Beight at light tower Roter Sand @ Zoom 15. So the problem is not related to the seagras: 

https://osmand.net/map/configure/#14/53.8621/8.0542

![IMG_2144_small](https://github.com/osmandapp/OsmAnd/assets/93162192/fb182651-ee5d-423e-b10d-a75ecb657a2e)

**Comment by vshcherb** [comment] 2024-06-30 15:39
@yuriiurshuliak please create new issue once to reproduce

**Comment by yuriiurshuliak** [comment] 2024-07-01 09:56
The issue has been created. Here is the link: https://github.com/osmandapp/OsmAnd/issues/20215
