### ISSUE TITLE
Moveable POIs (OSM Edit)

### ISSUE THREAD

**Issue by mfbehrens99** [osmandapp/OsmAnd#9250] opened 2020-06-16 06:04 UTC
Whenever you want to move a POI in OSMAnd you have to select that POI, press edit, press save, deselect and select it again (due to a bug #9249) and then you can move it.

It would help many mappers if you could just select a POI and then use the move tool. A green local edit circle should appear wherever the POI was moved to.

Since editing is required this option should only be available when the OSM editing plugin is enabled.

**Comment by NotSoImportant** [comment] 2021-04-11 00:01
is this a duplicate of https://github.com/osmandapp/OsmAnd/issues/3459?
Does the move actually get stored, or as in the last comment mentioned there be only a visual illusion?

**Comment by mfbehrens99** [comment] 2021-04-11 21:01
Yes I think the data is actually change on the OSM server. However, I would like the change position (or however it is called) option work for normal POIs as well. When I select a "normal" POI the option is grayed out.
![Screenshot_20210411-225552](https://user-images.githubusercontent.com/58851724/114321140-7edf8e80-9b19-11eb-8170-88a1b2a91a47.png)

**Comment by NotSoImportant** [comment] 2021-04-11 21:28
The double pressing bug is fixed and for me it shows also not greyed out, but then "apply" cannot be hit.
Using version 3.9.10
I agree this is a bug, but wanted to confirm if the linked #3459 is actually the same.
![image_2021-04-11_23-25-10](https://user-images.githubusercontent.com/35758921/114321883-8e60d680-9b1d-11eb-8f4a-680bc8da4998.jpg)

**Comment by Sorunome** [comment] 2022-03-29 16:28
Moving POIs in this way does not seem to update it on the OSM server for me, sadly :/

**Closed** 2022-03-29 16:42 UTC
Labels: Nice to Have
