### ISSUE TITLE
Osmand twice warns for speed camera

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/Osmand#4513] opened 2017-10-02 13:03 UTC
For roads with a direction of travel in both directions, it is recommended ([See Example 4](http://wiki.openstreetmap.org/wiki/Proposed_features/Relation:enforcement)) to designate speed cameras using two relations with points roles "From" and "To". I drew a  [diagram](https://s1.postimg.org/34lhxqiz67/P02-10-17_15.48.jpg) with speed camera.

Perhaps OsmAnd does not check the direction of movement and warns of the speed camera when each of the points with role "From". So I get a warning twice.

**Comment by vshcherb** [comment] 2017-10-02 17:03
Currently OsmAnd ignores a direction of speed camera. So it is not supported yet.

**Comment by scaidermern** [comment] 2017-10-03 07:35
Duplicate of #3967

**Closed** 2017-10-03 07:54 UTC
Labels: Observed
