### ISSUE TITLE
support for heart rate sensors

### ISSUE THREAD

**Issue by gitka** [osmandapp/Osmand#5484] opened 2018-05-24 20:58 UTC
Hi Osmand-Team,
Thanks for your great app.
I often use the feature trip recording, for creating a gpx file during cycling. So, I can improve the OSM map and Osmand.
The only thing I am missing, is a feature to display a heart rate from ANT+/Bluetooth-sensors and save the heart rate in the gpx file. This woud be helpfull for every outdoor fan.
Thank you in advance.

**Comment by riedel** [comment] 2018-06-10 13:07
Definitively nice to have. In general a way to write plugins that provide sensors would be be nice (see also #3204, #4932) .

**Comment by vshcherb** [comment] 2018-07-18 17:39
Duplicate of other issues.

**Closed by vshcherb** 2018-07-18 17:39 UTC
