### ISSUE TITLE
Sometimes wrong article is used in German language voice notifications

### ISSUE THREAD

**Issue by sicherist** [osmandapp/Osmand#8053] opened 2019-12-08 19:21 UTC
This is probably only relevant for german speakers but I try to put it in English: I noticed today when I used Osmand (latest Android version) to navigate, it told me "links abbiegen in **den** Carl-Spitzweg-Straße". **Den** is the wrong article in this case - it should be "**die** Carl-Spitzweg-Straße". How does Osmand determine the grammatical gender of a street name?

**Comment by sonora** [comment] 2019-12-09 19:46
I have checked the grammar in our German voice config file, have have also tested left turns a onto street names of the type XYZ-Straße. I cannot reproduce the issue you describe. The German voice prompt pronounces "... rechts abbiegen auf die XYZ-Straße.", which should be the correct accusative case.

To help debug, can you please do the following:
1. Specify an example of a street corner where you observe this
2. Specify the version number of OsmAnd you are using
3. Temporarily enable the "OsmAnd Development Plugin", then go to its Settings, find the line item "Test Voice prompts", select de-tts, and play button number 3.6. It should play an example of the prompt you are talking about. What does it say?

**Comment by sicherist** [comment] 2019-12-09 20:10
1. Here is a route where it occurs: https://www.openstreetmap.org/directions?engine=graphhopper_car&route=48.96443%2C9.11571%3B48.96362%2C9.11569#map=19/48.96399/9.11566

2. Osmand 3.5.5

3. It says "Scharf rechts abbiegen auf die Dr.-Quinn-Straße". Which is correct.

I have a theory, why this problem might exist: In Germany street names often are "**der** ... Weg" (->male article) or "**die** ... Straße" (->female article). In my example "Carl-Spitz**weg**-**Straße**" both words are part of the street name so the software might assume it is a "Weg" (=male article) instead of a "Straße", while in fact "Spitzweg" is the name of he painter who the street is named after. I don't know, just an idea.

**Comment by sonora** [comment] 2019-12-14 09:17
Yes, you are right. The code detects both weg and straße, and in this case falsely returns masculine. I assume the actual gender is determined by the ending of the street or ref name, not what's found in the middle.

Willl have to deploy a solution when I find a little time.

Thanks for pointing out!

**Comment by sonora** [comment] 2019-12-16 08:57
I changed it to using the end of the street name for the gender determination, should be fixed now.

**Closed by sonora** 2019-12-16 08:57 UTC
