### ISSUE TITLE
Names of rivers bend too much and get unreadable

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2793] opened 2016-07-08 14:26 UTC
Maybe there's a way we can fix this?
![screenshot_2016-07-07-00-26-39](https://cloud.githubusercontent.com/assets/12711814/16690509/059bd6d4-4531-11e6-9c5c-4211b06e089b.png)

**Comment by sonora** [comment] 2016-11-24 13:29
Duplicate of #1756.

**Closed by sonora** 2016-11-24 13:29 UTC
Labels: Observed, Offline Rendering
