### ISSUE TITLE
The search just doesn't find some places

### ISSUE THREAD

**Issue by bk6t** [osmandapp/OsmAnd#17409] opened 2023-06-12 15:46 UTC
### Explanation

I am trying hard to love Osmand. And I appreciate the work that is done here for free. So in the spirit of constructive criticism, I do hope my issue report helps to make this software even better.

A friend told me about a visit to Byron Bay, Australia. So, me being curious and all started Osmand to check that region out. But, how the heck do you find Byron Bay with Osmand. No chance. And that sucks. Even more so, because I run into cases like this all the time where there's just not the right result returned even though those places I am looking for are pretty well known. I cannot be bothered to write an issue ticket for every single place that is not found by the search, so take this as an example.

### Steps to reproduce

1) Start Osmand
2) Click the search lens in the main screen
3) Search for: 
a) Australia byron bay
b) byron bay australia
c) byron bay

Additionally, click increasing the search radius. Eventually some strange but totally unrelated places appear.

### Actual result
The region is not found. Instead random unrelated results appear in the search.

### Expected result

I expect the mf search to show me the results I am looking for. In this case byron bay as a result! How hard can this be?

Please, put some more resources into the search - it sucks.

### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: Android 13
Device model: Pixel 5a

**Comment by zipav** [comment] 2023-06-13 17:29
### Steps to reproduce: 
Download Australia New South Wales map → Open search bar → tap "byron bay" 

OsmAnd Nightly 4.5.0#196m, released: 2023-06-13

https://github.com/osmandapp/OsmAnd/assets/123936521/394eeea2-0102-4ce5-987b-aaf5b4cee472



Please note that in order to search in an area, you must have a map of that area loaded.
Try downloading a map of New South Wales Australia and the result should load without difficulty in your location.

**Comment by bk6t** [comment] 2023-06-13 17:52
@zipav Thanks for replying to the issue and posting a solution.

While this might work, it somehow doesn't make a lot of sense, because 

1) When searching Byron Bay and not having the Australian map, the search offers me a town called Byron instead, somewhere in north-east Canada. I don't have the Canadian map installed either. So you see there's a flaw in that logic. Why would the search know about a random small town called Byron from a map I also didn't install? How can it work for Canada but not Australia?

2) It's not very intuitive to need to install the map first and then being able to search for a random town. This doesn't make sense from a users point of view. I expect the search to know about the towns I do a search for, then the view to jump to that town and then get the map download offered. Not the other way around.

While 2) can be a question of debate, 1) clearly doesn't make any sense.

**Comment by sonora** [comment] 2023-06-13 18:08
Well, regarding "sense" It's hard to find something on a map you don't have.... 😉

Do you have the latest World map installed? Because I do find both towns "Byron" and "Byron Bay" all right, with neither a Canada map ot any Australia map installed...  So both seem on the latest World map - don't expect the same for every small hamlet, though. 😉

**Comment by bk6t** [comment] 2023-06-13 18:42
> Well, regarding "sense" It's hard to find something on a map you don't have.... wink

If you put it this way... ;) However, not the UX I would expect (and other offline maps apps I tested don't have this limitation).

> Do you have the latest World map installed? Because I do find both towns "Byron" and "Byron Bay" all right, with neither a Canada map nor any Australia map installed... So both seem on the latest World map - don't expect the same for every small hamlet, though. wink

Interesting, I do have the latest World map installed. Makes me wonder even more why search works for you and not for me. However, I guess this is not going to be fixed because it seems to be a design decision. 

Closing this.

**Comment by sonora** [comment] 2023-06-13 19:04
Please don't close this prematurely - if I find it and you can't, it's worth investigating if there is some bug.

![Screenshot_20230613-205304_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/f1ab5f68-6366-4aa2-9977-65646fa41dc6)

Also: You mentioned you have more occurrences. Can you give some examples, please? Maybe that helps nail it.

Regarding "by design": That's probably misnaming it. But fact is the things you find in a search need to come from somewhere. Somewhere offline, unless you want to use an online source. And if you don't have a regional map, you can only find things (towns? villages? restaurants?) someone decided is worth putting on the world map.

For debugging: I have our world map Edition 3/15/23, which I just notice is not the latest any nore. So it could also be a bug (or deliberate limitation) of our latest world map edition.

**Comment by letypequividelespoubelles** [comment] 2023-06-14 02:38
> Well, regarding "sense" It's hard to find something on a map you don't have.... 😉

Not totally true, it could be via online search, but this nice feature is well hidden ... see #7716

**Comment by vshcherb** [comment] 2023-06-17 20:50
Tested

It's not part of mini basemap so it's not searchable.https://www.openstreetmap.org/node/26010100
@sonora probably you have full basemap and it has that city included

**Closed by vshcherb** 2023-06-17 20:50 UTC
