### ISSUE TITLE
[Feature Request] Show address in search result

### ISSUE THREAD

**Issue by ana-dav** [osmandapp/OsmAnd#9586] opened 2020-08-07 08:54 UTC
When user search by the place name it would be nice to see the address in the search result

**Comment by mutipg** [comment] 2020-11-20 06:32
It should be done, because search results are useless today. Below is search result of POI named "Biedronka" with city name "Banino". I have no idea which one is exactly that one I'm loking for.
![Zrzutekranu_2020-11-20-07-21-11-906](https://user-images.githubusercontent.com/10333015/99766872-44416f00-2b02-11eb-8b02-c30b26c87d1e.jpeg)

**Comment by mutipg** [comment] 2021-01-20 14:25
Is there any chance to add this feature to OsmAND?

**Comment by scaidermern** [comment] 2021-01-24 08:19
Probably a duplicate of #3327.

**Comment by vshcherb** [comment] 2022-10-01 13:08
Merged to https://github.com/osmandapp/OsmAnd/issues/2993

**Closed by vshcherb** 2022-10-01 13:08 UTC
Labels: Nice to Have
