### ISSUE TITLE
OSM Edit: introduce a check for moving node location (limit node in Denmark moved to Cuba)

### ISSUE THREAD

**Issue by Hjart** [osmandapp/OsmAnd#6607] opened 2019-03-03 12:43 UTC
The city limit node https://www.openstreetmap.org/node/27164326/history was recently moved from  Denmark across the Atlantic to Cuba by the same OsmAnd user for the second time in 2 months. I reverted the moves both times.
I suspect there may be a problem with OsmAnd (or maybe the specific version used)

**Comment by Hjart** [comment] 2019-03-03 13:50
Also the footway https://www.openstreetmap.org/way/25535434/history in Wolfsburg Germany was for some mysterious reason tagged place=city by the above mentioned OsmAnd user.

**Comment by vshcherb** [comment] 2019-03-03 22:15
It looks strange cause we didn't experience it yet. It is possible that user has an old map data and there is no validation that it was modified before. We need definitely introduce a check that at least a location of modified object is the same.

**Comment by jfburke3** [comment] 2019-03-06 15:38
Are we sure that Queen Margrethe just isn't expanding her empire?

**Comment by Hjart** [comment] 2019-03-06 20:26
I think the old lady is more interested in designing costumes than expanding empires :-)

**Comment by Hjart** [comment] 2019-04-09 20:26
Three hours ago the node mentioned above was moved to Cuba again (for the third time). I reverted the move just now. Would it be possible to prevent this behaviour? The node is part of a road which has now stretched across the Atlantic on three occasions

**Comment by scaidermern** [comment] 2019-04-10 08:11
> Three hours ago the node mentioned above was moved to Cuba again (for the third time).

How is this even possible? As far as I know you can't move nodes in OsmAnd. This must be some serious bug.

**Comment by scaidermern** [comment] 2019-04-10 08:17
> It is possible that user has an old map data and there is no validation that it was modified before. We need definitely introduce a check that at least a location of modified object is the same.

No, [node 27164326](https://www.openstreetmap.org/node/27164326/history) has always been around [55.662, 11.131](https://www.openstreetmap.org/#map=18/55.6626932/11.1316166) until it was moved by OsmAnd over hundreds of kilometers. This can't be caused by old map data since there is no old version which has been this far away.

However the first node version (version 0) got redacted. Maybe this leads to a problem in OsmAnd? Does OsmAnd look at previous versions when editing a POI?

**Comment by vshcherb** [comment] 2019-04-10 21:28
Probably redaction causes that kind of problems. Good idea to check

**Comment by vshcherb** [comment] 2020-12-07 12:22
https://github.com/osmandapp/OsmAnd/commit/7af466ea1a6451b74fe76af0e572617beb4ca4a6
Fixed by introducing a check. Actually in OsmAnd you can move the node by clicking Move Point on Edited point (if you use offline editing - upload later), so we decided to keep that functionality and introduce a check so the node doesn't move to more than 10km.

Proper fix would be to track version of the node though unfortunately osmand maps doesn't store object versions

**Closed by vshcherb** 2020-12-07 12:22 UTC
