### ISSUE TITLE
"tree" among the Сategories with tag "denotation=natural_monument"

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10214] opened 2020-11-17 10:37 UTC
looking for "tree" among the categories, you get only the trees with "name" while I am interested only in the remarkable trees, those with tag "denotation=natural_monument" that do not always have a proper name.

**Comment by xmd5a2** [comment] 2020-11-19 12:24
Duplicate of https://github.com/osmandapp/OsmAnd/issues/9915

**Closed** 2020-11-19 12:24 UTC
