### ISSUE TITLE
Authorization in OsmAnd Tracker is stucking

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13763] opened 2022-02-16 12:05 UTC
### Description
When you enter the confirmation code t log in to the OsmAnd tracker, the app is stuck. The progress circle is moving, but the log in process is not finishing. 

### How to reproduce?
1. Install OsmAnd tracker
2. Enter confirmation code to log in 
3. The app is stuck

-------------
```
java.util.NoSuchElementException: 
  at kotlin.collections.CollectionsKt___CollectionsKt.last (_Collections.kt:368)
  at net.osmand.telegram.TelegramService$startWidgetUpdates$1.run (TelegramService.kt:234)
  at android.os.Handler.handleCallback (Handler.java:938)
```
```
Caused by: java.lang.ClassCastException: 
  at net.osmand.telegram.TelegramService.app (TelegramService.kt:28)
  at net.osmand.telegram.TelegramService.onStartCommand (TelegramService.kt:128)
  at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:4643)
```
```
org.drinkless.td.libcore.telegram.Client$ClientException: TDLib fatal error (1): [ 0][t 3][1648034636.481235980][MessagesManager.cpp:5601][#1][!Td]	Check `have_dialog(dialog_id)` failed
at org.drinkless.td.libcore.telegram.Client$1ThrowError.run(Client.java
  at java.lang.Thread.run (Thread.java:920)
```

**Comment by lead-legs** [comment] 2022-02-21 15:23
There appears to be a brief error message when first installing Osmand Tracker App - "400 - server name must be non-empty"

**Comment by anastasiia936** [comment] 2022-04-04 07:34
+1

**Comment by vshcherb** [comment] 2022-05-03 10:53
Should be fixed already, please report if the issue is still there

**Closed by vshcherb** 2022-05-03 10:53 UTC
Labels: Observed
