### ISSUE TITLE
OsmAnd live: POI data displayed

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17898] opened 2023-08-11 08:16 UTC
The map still shows the old POI name (Istrien Gourmet) while the POI info already shows the new name (Verde 22):
https://www.openstreetmap.org/node/9123988124
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/1040784/666354a7-7d87-4b96-8839-c66aadca98f1"  width="300" height="auto"/> </td>
  </tr>
</table>

Map and POI info show a brewery although the brewery tags have been removed:
https://www.openstreetmap.org/way/316383846
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/1040784/e033adc5-8a0c-466e-b659-3c9b7588f423"  width="300" height="auto"/> </td>
  </tr>
</table>

Map Germany_bayern_europe.obf is from August. No overlapping maps activated. Deleting and redownloading live data doesn't help.

OsmAnd 4.5.10.

(This is actually the same report as #17893. However, in my case I can still reproduce this bug.)

**Comment by Nine-Tailed** [comment] 2023-08-11 08:32
See https://github.com/osmandapp/OsmAnd/issues/17887

**Comment by Citro12** [comment] 2023-08-11 14:47
Problem is solved by deleting the base map of the respective federal state and downloading it again

**Comment by scaidermern** [comment] 2023-08-11 21:11
> Problem is solved for me by deleting the base map of the respective federal state and downloading it again

Didn't work for me. I already tried re-downloading Bavaria and live data, two times. The old data is still displayed.

**Comment by DmitryAlexei** [comment] 2023-08-14 07:29
https://github.com/osmandapp/OsmAnd/issues/17887

**Comment by DmitryAlexei** [comment] 2023-08-25 07:40
@UserMicha try to clear the live updates cache. Sometimes opening and closing OsmAnd multiple times can help.

**Comment by UserMicha** [comment] 2023-08-25 11:49
Unfortunately, that doesn't help. I also deleted the cache of the app in the Android settings and ended it hard. Map is rebuilt, but the same appearance. As before, only switching to Engine 1 helps. It is Android 10 on a Samsung XCover.

**Comment by vshcherb** [comment] 2023-08-30 11:00
To be fixed with this issue - https://github.com/osmandapp/OsmAnd/issues/14714, https://github.com/osmandapp/OsmAnd/issues/17834

**Comment by vshcherb** [comment] 2023-10-11 10:57
Tasks need to be retested (probably related to https://github.com/osmandapp/OsmAnd/issues/18153)

**Comment by ivanPyrohivskyi** [comment] 2023-11-13 14:11
I can not reproduce this bug and no idea what happen.
I think need to check order of map during rendering and check if request to retrieve POI information is no depended from rendering.
<img width="360" src="https://github.com/osmandapp/OsmAnd/assets/1040293/9018bd35-71d1-49fb-bb9f-97375725e383" /> <img width="360" src="https://github.com/osmandapp/OsmAnd/assets/1040293/26a8cc57-42a3-43af-a72f-c220407ee058"/>

**Comment by ivanPyrohivskyi** [comment] 2023-11-13 14:34
One idea yet.
Need to check order of map using in rendering.
As I can see from [code for amenity](https://github.com/osmandapp/OsmAnd/blob/428f15833e352c2725dc482e978a3f3eb9eef036/OsmAnd/src/net/osmand/plus/views/layers/MapSelectionHelper.java#L311C26-L311C26) after retrieve info from rendering layer we launch of finding amenity from map, so data on screen and POI info.
Same issue I think with deleted amenity. Even with [check on closed amenity](https://github.com/osmandapp/OsmAnd/blob/112bbf317fc5bc391d1b535b475aac4ad5bdca5e/OsmAnd/src/net/osmand/plus/views/layers/MapSelectionHelper.java#L630) we forgot that they are searching in all maps (base and live updates).

**Comment by vshcherb** [comment] 2023-11-14 10:15
@ivanPyrohivskyi how will it fix road duplicates problem with code for amenity?
https://github.com/osmandapp/OsmAnd/issues/18153

**Comment by ivanPyrohivskyi** [comment] 2023-11-14 10:39
> @ivanPyrohivskyi how will it fix road duplicates problem with code for amenity? #18153

On amenity example I explained that problem in rendering side and separate request to data from Java produce right info.

**Comment by UserMicha** [comment] 2023-11-14 22:32
It is really strange.  I even see a key that was removed in 2019. Updating the card does not help.
![Clipboarder 2023 11 14-003](https://github.com/osmandapp/OsmAnd/assets/143121427/835765ab-e775-479a-99de-30ae9e33b9e3)
![Clipboarder 2023 11 14-002](https://github.com/osmandapp/OsmAnd/assets/143121427/037e82c5-8927-475d-9436-bdec98e3504c)

**Comment by vshcherb** [comment] 2023-12-15 15:18
To do: try to reproduce the issue similar to (https://github.com/osmandapp/OsmAnd/issues/14714#issuecomment-1676236664) - be aware it's not present with v1

**Comment by vshcherb** [comment] 2023-12-18 15:12
@scaidermern are you able to reproduce it lately? We still can't catch the bug but if you can pinpoint to latest changes related to this https://github.com/osmandapp/OsmAnd/issues/14714#issuecomment-1676236664

**Comment by Dimitar5555** [comment] 2023-12-18 16:11
> To do: try to reproduce the issue similar to (https://github.com/osmandapp/OsmAnd/issues/14714#issuecomment-1676236664) - be aware it's not present with v1

I've been able to reproduce it at 42.50239 27.46734 (December 2023 map of Bulgaria with live updates, OsmAnd 4.5.10 on Android 10). The problem is present regardless of the rendering engine. To reproduce it, delete ways which are part of route relation.

![Screenshot_20231218_180332.jpg](https://github.com/osmandapp/OsmAnd/assets/19364673/28e09684-3f21-45e4-a520-d9d1c1e9bfe1)

**Comment by scaidermern** [comment] 2023-12-20 10:51
> @scaidermern are you able to reproduce it lately? We still can't catch the bug but if you can pinpoint to latest changes related to this [#14714 (comment)](https://github.com/osmandapp/OsmAnd/issues/14714#issuecomment-1676236664)

No, I can't reproduce it with OsmAnd 4.6.8. But I rarely update roads and I'm not sure under which exact circumstances the bug did occur. So maybe it is fixed, maybe it isn't.

**Comment by ivanPyrohivskyi** [comment] 2023-12-25 08:45
I could not reproduce this bug. Previous request was wrong.

**Closed** 2023-12-25 11:48 UTC
Labels: live-updates
