### ISSUE TITLE
Add seek for curvature / winding roads option for motorcycle 

### ISSUE THREAD

**Issue by noelelias** [osmandapp/OsmAnd#14934] opened 2022-07-25 22:41 UTC
There is an OpenSource project by @adamfranco which rates roads on their curvatures. This would be amazing for motorcycle riders (The two toms for example specifically advertise their products with being able to find those winding roads).

A slider to define how much this should influence the routing would be amazing.
Something like:
1 (only if the route will take the same time)
2 (only if the route will not take more than 10% of the normal time)
3 ...

https://github.com/adamfranco/curvature

#14074

**Comment by scaidermern** [comment] 2022-07-26 05:16
Duplicate of #7049.

**Closed** 2022-07-28 13:40 UTC
