### ISSUE TITLE
Show addresses for results in search

### ISSUE THREAD

**Issue by Qwertie-** [osmandapp/OsmAnd#3964] opened 2017-06-25 09:55 UTC
I was trying to locate a store using Osmand and I ran into an issue because multiple of the store locations came up but I was unable to tell which one was the one I was looking for, I know the suburb and street the store is located on but all Osmand showed me was the distance away from me which makes it very hard to know which one is the one I want to go to.

I ran the same search on google maps and as well as telling me the distance it also shows underneath the street, suburb, state which made it possible to find the one I wanted.

Osmand version I was using is 2.6.3

**Comment by jfburke3** [comment] 2017-07-02 16:13
I concur. This would be very useful to have.

**Comment by mutipg** [comment] 2020-11-20 06:47
It should be done, because search results are useless today. Below is search result of POI named "Biedronka" with city name "Banino". I have no idea which one is exactly that one I'm loking for.

![Zrzutekranu_2020-11-20-07-21-11-906](https://user-images.githubusercontent.com/10333015/99766872-44416f00-2b02-11eb-8b02-c30b26c87d1e.jpeg)

**Comment by scaidermern** [comment] 2022-03-30 08:23
Duplicate of #2993.

**Closed** 2022-10-01 13:07 UTC
Labels: Nice to Have
