### ISSUE TITLE
Lake Geneva has disappeared since 1 April map update

### ISSUE THREAD

**Issue by dafadllyn** [osmandapp/OsmAnd#16979] opened 2023-04-15 17:20 UTC
After I have updated the "Switzerland" map (standard map) to the version as of 1 April 2023, the [Lake Geneva](https://www.openstreetmap.org/relation/332617) has disappeared:

I've checked the lake relation using JOSM and have found that it included an [address node](https://www.openstreetmap.org/node/1230851850). I've now removed it from the relation. Otherwise the relation was fine (i.e. not broken).

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/79018751/232241103-216e52b5-90de-4e13-a9df-8e35345e129f.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

PS: OsmAnd+ 4.4.7

**Comment by scaidermern** [comment] 2023-04-17 05:31
Climate change?

Or maybe caused by the same bug as #16975.

**Comment by vshcherb** [comment] 2023-04-17 12:51
Need to test whether it's fixed now by map regeneration

**Comment by vmicho** [comment] 2023-04-17 20:46
Yep. I have the broken maps from 1.apr. and the lake is not there. I've deactivated all world maps and the lake is not there on any zoom level.
Re-install roads map: lake not there
Re-install standard map: still white
v4.3.12

**Comment by Zirochkabila** [comment] 2023-05-02 10:31
@vmicho @dafadllyn A second test is required - with the May maps on the nightly build of 02.05 - it cannot be reproduced.

**Closed** 2023-05-02 11:16 UTC

**Comment by dmpr0** [comment] 2023-05-05 06:59
Fixed
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/236395016-ef7c92b3-034a-4abd-b211-66a64221aad9.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/236395029-084f9fce-7845-493a-9638-c88a3a39c558.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>
