### ISSUE TITLE
"Use elevation" Walking routing finds shorter route

### ISSUE THREAD

**Issue by mokelly** [osmandapp/OsmAnd#14379] opened 2022-05-24 22:51 UTC
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Pedestrian, comparing "Use elevation" on or off

### Start and end points

[](url)
From [Sawtooth Trailhead](https://www.openstreetmap.org/node/4875372925) to [Guitar Lake campground](https://www.openstreetmap.org/search?whereami=1&query=36.57224%2C-118.31471#map=18/36.57224/-118.31472)

### Actual and expected routes

With "Use elevation" on, OSMAnd found a short route (42.5 miles).  With "Use elevation" off, OSMAnd took a longer route (48.2 miles).  I expected the reverse, with the "Use elevation" feature sometimes finding a longer route that avoided steep slopes.

Strangely, the longer route also has bigger elevation changes (13k' climb vs 10k' climb).  The behavior was the same with the suboptions "Hilly", "Less Hilly" and "Flat".

<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/1460497/170143836-519aabc4-4669-4441-a08f-8660ef6b70f6.jpg"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/1460497/170143860-c98db9c8-a94a-4847-8dc2-16959cc6b2e3.jpg"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Is this a regression?

This route worked as expected in the 4.1.x series.  I tested and found this same behavior in 4.2.0 and 4.2.1.

## 🌍 Your Environment

**OsmAnd Version:**

4.2.1

**Device and Android/iOS version:**

Galaxy S20, Android 12

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps

**Comment by vshcherb** [comment] 2022-05-25 22:34
Route data. https://osmand.net/map?start=36.453275%2C-118.596752&end=36.572264%2C-118.314605&mode=pedestrian#10/36.5373/-117.9601

Use elevation data:
Route: <b>68.2 km</b>, <b>23:11</b>. Cost: 108793

Without elevation data
Route: <b>68.2 km</b>, <b>17:04</b>. Cost: 51421

Same route actually

**Comment by vshcherb** [comment] 2022-05-25 22:36
To be honest I didn't manage to generate longer routes as it mentioned so I assume the issue is already fixed in 4.2

**Comment by mokelly** [comment] 2022-05-25 22:39
Hi, vshcherb.  I tested using 4.2.1 from the Google Play Store beta
program.  Were you using a later version?

**Comment by vshcherb** [comment] 2022-05-25 22:43
That's a bit strange... We will retest on android version to be sure with latest maps.

**Comment by mokelly** [comment] 2022-05-25 22:50
Thanks!  In case it matters, I was using the latest monthly California map
set, and the most recent downloadable contours.

**Comment by vshcherb** [comment] 2022-06-02 12:04
Point of 2 alternatives routes: 
https://osmand.net/map?start=36.475689%2C-118.604603&end=36.572264%2C-118.314605&mode=pedestrian

I - use elevation data. Route: <b>72.2 km</b>, <b>24:27</b>. Cost: 126154
II - use elevation data. Route: <b>71.8 km</b>, <b>24:58</b>. Cost: 126612
I - no elevation data. Route: <b>72.2 km</b>, <b>18:04</b>. Cost: 54425
II - no elevation data .Route: <b>71.8 km</b>, <b>17:57</b>. Cost: 53846

**Comment by mokelly** [comment] 2022-06-06 23:31
@vshcherb , is that a confirmation of my bug report?  I see that "North - use elevation data" finds a shorter and slightly steeper route than with "no elevation data".

**Comment by mokelly** [comment] 2022-06-06 23:34
I found one cause of my unexpected results.  In `Navigation Settings / Route parameters / Prefer` I had "Prefer hiking routes" set.  The 42.5 mile route uses a short stretch of road, which is avoided by the 48.2 mile route.  When I uncheck "Prefer hiking routes", the shorter 42.5 mile route is found in both cases.

Is it a bug that "Use elevation" doesn't respect "Prefer hiking routes"?  I recall it doing so in 4.1.x; or at least that the road-less route was found with either setting in that version.

**Comment by vshcherb** [comment] 2022-06-07 16:37
No, it's confirming there is no bug. Use / not use elevation data here is not critical difference cause in both cases you need to make +900m (uphill), the main difference that north route might have less steep uphills, so it's usually more preferrable by (72.8-71.8) = 1 km distance which is around 2% of the route distance.

**Closed by vshcherb** 2022-06-07 16:37 UTC
