### ISSUE TITLE
Slow Route Calculation (bicycle profile)

### ISSUE THREAD

**Issue by anten1222** [osmandapp/OsmAnd#19483] opened 2024-04-05 17:47 UTC
### Describe the routing engine used (required)

- [ ] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

In 4.7 Nightly, the calculation of the route over longer distances was quick some time ago. Now it is very slow again. 10 minutes or more

### Describe your start and end points (required)

In 4.7 Nightly, the calculation of the route over longer distances was quick some time ago. Now it is very slow again. 10 minutes or more

### Describe the actual route (required)

In 4.7 Nightly, the calculation of the route over longer distances was quick some time ago. Now it is very slow again. 10 minutes or more

### Describe the expected route (required)

In 4.7 Nightly, the calculation of the route over longer distances was quick some time ago. Now it is very slow again. 10 minutes or more

### Describe what Maps you used (online or offline) (required)

- [ ] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version:4.7
Android/iOS version:
Device model:
```

**Comment by yuriiurshuliak** [comment] 2024-04-08 15:16
Please provide a detailed steps to reproduce this issue.  Include a video demonstrating the issue occurrence. Additionally, specify the starting and ending coordinates of the route that is showing slow computation.

**Comment by anten1222** [comment] 2024-04-09 04:17
With Osmand Nightly

For example

Profile Bike

From 53.82286° N, 9.28587° E

To 50.38578° N, 6.65635° E

Some time ago 45 seconds

Now 10 minutes or more

**Comment by zipav** [comment] 2024-04-12 16:42
OsmAnd Nightly 4.7.0#2046m, released: 2024-04-12

Not reproduced on OsmAnd Nightly. The route is built in about 60 seconds. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/de0d5a7d-7801-43dc-9513-501a7573b5b3"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by anten1222** [comment] 2024-04-17 15:29
Version 4.7.9 Route by car, calculation under 10 seconds. By bike over 10 minutes or crash

**Comment by vshcherb** [comment] 2024-04-18 19:16
@anten1222 did you update all the maps? did you use specific bicycle settings? Please try to switch off all the settings for navigation and try. 
If you use any specific avoids please let us know

**Comment by RZR-UA** [comment] 2024-04-19 11:12
bicycle with default params is ok

https://test.osmand.net/map/?start=53.822860,9.285870&end=50.385780,6.656350&profile=bicycle&params=bicycle,noglobalfile,nativerouting,hhonly#7/52.500/5.164

**bicycle with height_obstacles = HH-native routing failed:**

![test](https://github.com/osmandapp/OsmAnd/assets/90444451/228a3443-36a4-436a-a0c3-3a6583ba2f32)

**Comment by anten1222** [comment] 2024-04-19 16:49
Handy Pixel 6a
Android 13
Osmand 4.7.9
![XRecorder_19042024_085526](https://github.com/osmandapp/OsmAnd/assets/73232079/26498814-3762-4d4a-8171-b803e9bad4a4)
![XRecorder_19042024_085735](https://github.com/osmandapp/OsmAnd/assets/73232079/4dc05778-145c-4baa-8d5f-69ca69f6be53)
![XRecorder_19042024_090350](https://github.com/osmandapp/OsmAnd/assets/73232079/a7d6ec14-2d59-4f2c-9408-eff8edaba2d3)
![XRecorder_19042024_101710](https://github.com/osmandapp/OsmAnd/assets/73232079/3d44c067-041f-41ce-aa5a-249a48e347d6)


All maps currently
Calculation bicycle 12 Minutes
Calculation car 10 seconds

**Comment by RZR-UA** [comment] 2024-04-19 20:20
The problem was empty parameters in new HH routing when "Use elevation data" option enabled.

Now fixed. Requests are attached.

tests:

![fixed](https://github.com/osmandapp/OsmAnd/assets/90444451/dc1dbecb-dbe2-4c94-bb42-61185b231366)

bicycle, default options = 12 seconds:

![0](https://github.com/osmandapp/OsmAnd/assets/90444451/27fadf08-f3e4-43f9-a749-d5385b9264c1)

bicycle, use elevation data = 26-29 seconds:

![1](https://github.com/osmandapp/OsmAnd/assets/90444451/8ceb76eb-5214-4afa-bb18-a8e569c5400e)

**Comment by vshcherb** [comment] 2024-04-19 21:55
- [ ] ios to test

**Comment by anten1222** [comment] 2024-04-20 14:51
Mobile phone Pixel 6a
Android 13

Osmand Nightly from 20.04.2024
and with this profile the calculation with the bike and 380 km only takes a few seconds
@
[2_5269545884277819457.txt] (https://github.com/osmandapp/OsmAnd/files/15048639/2_5269545884277819457.txt)
Original osf

**Comment by RZR-UA** [comment] 2024-04-21 10:05
@anten1222 please clarify your last message (is the problem fixed at your device with fresh nightly build?)

**Comment by RZR-UA** [comment] 2024-04-21 10:07
@vshcherb iOS is pretty good:

bike default ("any" elevation):

![ios1](https://github.com/osmandapp/OsmAnd/assets/90444451/bbfeae21-d5be-4c63-b767-cd760983c8cc)

bike with less hilly elevation:

![ios2](https://github.com/osmandapp/OsmAnd/assets/90444451/b9ef27c7-9b9d-469b-b6b4-9c59558824a5)

HH log (height_obstacles is used by "selected files") - ~70 seconds:

![ios-log](https://github.com/osmandapp/OsmAnd/assets/90444451/982144f1-fae1-456f-8ad6-c7ed45923888)

**Closed** 2024-04-22 07:54 UTC
Labels: routing

**Comment by anten1222** [comment] 2024-04-22 12:10
Osmand Nightly from 22.04

By bike 12 minutes

With this attached profile

Without highs 72 seconds

With highs 6 minutes then crash

**Comment by anten1222** [comment] 2024-04-22 12:44
by car 8 seconds
Your Profile Bicycle_1 is for car

**Comment by zipav** [comment] 2024-04-24 18:39
OsmAnd Nightly 4.8.0#2172m, released: 2024-04-24
Android 12
Nokia 5.3

It took 42.80 sec. to build the route with default parameters of the Bicycle profile.
Route building with Use elevation data took 1 min. 56.76 sec.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/8b01ef07-5276-4fb6-8637-ba53dbf3b740"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/b74f0618-ae0a-4a1e-af89-8a62b68d3e8b"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by anten1222** [comment] 2024-04-24 18:55
For OsmAnd-android-full-arm64.apk
IT IS very good.
