### ISSUE TITLE
Gpx read failed: EBADF - Bad File Descriptor

### ISSUE THREAD

**Issue by crostad** [osmandapp/Osmand#5522] opened 2018-05-30 15:43 UTC
Hello there, 

I'm having issues with imported gpx files. This has never happened before the latest update of the app.
I'm using the Osmand+ app version 3.0.2 on Huawei P10 Lite, Android 7.0, with offline maps offered within the app.

Issue: when trying to import a Gpx file, I get the error "GPX read failed: EBADF (Bad file descriptor)".
I tried several gpx files, you can find one attached to try.

Thanks!
D.

[Swar_2018_01.zip](https://github.com/osmandapp/Osmand/files/2054630/Swar_2018_01.zip)

**Comment by sonora** [comment] 2018-05-30 20:33
I can reproduce the issue, in addition can contribute the following findings:
- The issue only occurs in connection with **importing** this file: When you either tap on the GPX file in a file manager app and chose OsmAnd to import it, or when in OsmAnd on the "Tracks" tab you tap the "+" button, then navigate to the file to import it.
- **Not all GPX files are affected**: e.g. files recorded by OsmAnd itself seem to import ok. So it looks like only some files (like the one attached above) in combination with the import mechanism produce the issue.
- **The file  attached above works ok**, when you place it manually (via a file manager or a PC) anywhere in OsmAnd's data folder's tracks folder (or subfolders thereof). It then appears as usual in OsmAnd tracks tab, and works. So this is also your workaround for now.

**Comment by crostad** [comment] 2018-05-31 07:12
Hi Sonora,

Thank you for your quick feedback and proposed workaround!

I tried to place manually the same gpx file into the Osmand track folder and it works fine with me.

Update on the issue, if you need to further investigate it:

- I tried several gpx files and it seems to me that only large gpx files (more than 150 km routes) are affected by this issue.

- The issue never happened with previous versions of the app, in the osmand's google groups other users are having the same issue and solved it installing a previous version of the app (2.9.3)

https://groups.google.com/forum/#!topic/osmand/WSO0J_Ac13I

Thank you for your help!
D.

**Comment by sonora** [comment] 2018-05-31 08:29
It looks like the issue is not related to the contents of the GPX file at all (and that is also what the error message indicates): This is somehow related to file operations or the file system.

Yesterday I had downloaded your zip file via a PC, unzipped it there, then placed the GPX on the Android device's Internal memory card, and the OsmAnd import failed.

Today I have downloaded again directly in Android (Download folder), unzipped it there (using Flashlight + Clock's "File Manager +"), and everything worked just fine. Looks like at the moment I cannot reproduce the issue any more no matter what I try, very strange.

**Comment by sonora** [comment] 2018-05-31 08:44
Chances are the mystery is this: This may be fixed in our nightly build of 2018-05-30, because only after going back to 2018-05-29 the issue appears again for me. Let me cc @crimean because he made related commits yesterday and I had just commented on one of them with another observation.

**Comment by sonora** [comment] 2018-06-02 15:46
Almost looks to me like fixing the D8 issue https://github.com/osmandapp/Osmand/commit/54038b03de28576017108a0947a869b97ca099f3 also fixed this? Can anyone confirm? (@vshcherb , @crimean )

**Comment by vshcherb** [comment] 2018-06-02 17:47
Possibly it is related

**Comment by crostad** [comment] 2018-06-04 11:41
Hello, quick update:

It appears to me that the issue has been solved with the updated version 3.0.3
The same gpx file attached above works perfectly now.
Thank you for your feedback!

Given that it is the first time I use this platform, who is in charge of closing the issues? Am I allowed to do so? Thanks.

D.

**Comment by sonora** [comment] 2018-06-04 22:16
Thanks for confirming, I do believe the commit I refeence above fixed the issue.

**Closed by sonora** 2018-06-04 22:16 UTC
