### ISSUE TITLE
Route disappears when the display is resized

### ISSUE THREAD

**Issue by sis651** [osmandapp/OsmAnd#17476] opened 2023-06-21 19:11 UTC
### Steps to produce
1. Choose a point to navigate.
2. Calculate the route.
3. Start navigation. Blue track with arrows on it and yellow direction signs appear and you follow it.
4. If the device is folded, unfold it. Or if it's unfolded, fold it. Or resize the app in window mode, switch to window or multi app mode etc. Sometimes this happens if you go back etc.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/137331144/3626b3d6-46db-4193-a34d-367bdaa96706"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/137331144/18fd54f9-e172-49ee-a2f6-38535620bec2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/137331144/878eeefe-2b6d-4a9b-ac27-57fc2f5eb8d9"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Actual result
Osmand display resizes and the blue track with little arrows on it disappears until the next or a few turns. However, yellow turn signs are kept displayed. If the routing redraws a new route it appears.

### Expected result
Display is resized and the blue track appears normally.

### Your Environment
OsmAnd Version: Osmand 4.4.7, 2023-04-10
Android/iOS version: Android 13, OneUI 5.1
Device model: Samsung Galaxy Z Fold 4,  SM-F936B/DS

**Comment by Zirochkabila** [comment] 2023-06-22 08:24
@sis651 The shadow display may be related to https://github.com/osmandapp/OsmAnd/issues/16787
Route disappearance - needs to be reproduced

**Comment by Zirochkabila** [comment] 2023-06-23 09:50
OsmAnd~ 4.5.0#283m, Released: 2023-06-23

<img width="1436" alt="Screenshot 2023-06-23 at 12 49 16" src="https://github.com/osmandapp/OsmAnd/assets/104760013/0ed87bec-cfa2-4a7f-9f4e-2ab4d6abb421">

**Comment by sebastianschauenburg** [comment] 2023-08-11 08:16
I've also encountered this issue (blue line disappearing). Can't reproduce it reliably, but noticed that it happened more often when the screen rotated (I use OSMand in landscape mode).

**Comment by DmitryAlexei** [comment] 2023-08-14 06:30
https://github.com/osmandapp/OsmAnd/issues/17506

**Comment by DmitryAlexei** [comment] 2023-08-14 06:48
https://github.com/osmandapp/OsmAnd/issues/17908

**Comment by vshcherb** [comment] 2023-08-18 09:38
Merged to https://github.com/osmandapp/OsmAnd/issues/17506

**Closed by vshcherb** 2023-08-18 09:38 UTC
Labels: and-ui
