### ISSUE TITLE
Announcing current road in navigation guidance

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12670] opened 2021-09-03 17:18 UTC
### Description
 When a turn is coming, the voice navigation says to turn onto [the name of the road you are on, combined with the name of the road you will be turning onto]. It should just say turn onto [the name of the road you are about to turn on]

### How to reproduce?
Create navigation between points: 
41.61831° N, 81.42414° W
41.62506° N, 81.41933° W
https://photos.google.com/share/AF1QipPUKFX56jMRFOUiw7cqrawqjpyRv1A_p9fLnE7aJM729AOI9hJM4D82Zo4TzMEe1A/photo/AF1QipPRaFIPAmhW-j3S_JfCZs3-1tVPjfo5kTQAjUP8?key=VGFIbVFodGM3TzhhcnFKTmxSSFRFdnkyS0gxVHFR

**Comment by vshcherb** [comment] 2021-09-03 21:29
Duplicate of https://github.com/osmandapp/OsmAnd/issues/12180

**Closed by vshcherb** 2021-09-03 21:29 UTC
