### ISSUE TITLE
Background color is blue?

### ISSUE THREAD

**Issue by spaanse** [osmandapp/OsmAnd#17450] opened 2023-06-19 13:47 UTC
### Description

With the newest update, a lot of the map is now colored blue, like the color of water.

### Steps to reproduce

- Disable extra details
- Zoom in on a populated region

### Actual result

![Screenshot_2023-06-19-15-42-51-34_54166e5c6f8ad9491c65e2397c495c92](https://github.com/osmandapp/OsmAnd/assets/19549928/fd6649e9-9d6b-41ca-949b-669cd1ab7a99)

### Expected result

Grey background for the populated areas

### Your Environment
OsmAnd Version: 4.5.2 beta (released 17-06-2023)
Map: all, updated 01-06
Android/iOS version: 
Device model:

**Comment by scaidermern** [comment] 2023-06-19 14:18
Duplicate of #17442

**Closed** 2023-06-19 14:19 UTC
