### ISSUE TITLE
TTS dont use destination

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3181] opened 2016-10-18 17:41 UTC
Some times ago _destination=..._ worked fine, but on my last trip nothing announced from the TTS.
So I tested some and none of them worked.
tested with English, Italian, and German TTS voice on 2.4.7.

Also are missing the direction name in the "next road box" in the middle of the above screen.

Is there something changed inside the _ttsconfig.p file or in the latest map?

**Comment by sonora** [comment] 2016-10-25 09:56
I have tested this and it works fine.  Can you please make sure that in the Navigation settings you have "Announce / Street names" activated.

Another test: Once the route is calculated, on the route config dialog, can you please tap on the line which shows the route details (distance, travel time), which will get you to a screen showing the detailed turn instructions and the data associated. On the turns in question, you should see the destinations in the text column, something like "towards XYZ".

If you do not see any such data, it may be an issue with our maps. But as I say, I cannot reproduce this at all (latest nightly, August maps). Please report exact builds of app and map.

(Cross ref: A similar occurrence of this issue seems to have been reported here: https://github.com/osmandapp/Osmand/issues/1786#issuecomment-251293628)

**Comment by hakuchi** [comment] 2016-10-25 17:55
Yesterday I made a new clean installation from OsmAnd+ (Beta) v2.5 from Playstore with map from October and now _destination=..._ works.

But if there is a way with _destination:backward_ or _destination:forward_, nothing is announced.

I tested this on this 2 intersections.
Example1(backward):
http://www.openstreetmap.org/way/191799180
with this route:
http://www.openstreetmap.org/directions?engine=mapzen_car&route=47.8097%2C12.1214%3B47.8084%2C12.1124#map=17/47.80868/12.11687

Example2(forward):
http://www.openstreetmap.org/way/24711338
with route:
http://www.openstreetmap.org/directions?engine=mapzen_car&route=47.8018%2C12.1625%3B47.8052%2C12.1498#map=17/47.80346/12.15657

If I use route 1 in OsmAnd, _destination:backward=München;Innsbruck_ is not announced.
![route1](http://img5.fotos-hochladen.net/uploads/screenshot2016576cpf8hi2.png)


On route 2 the destination from 2th exit in roundabout is announced but the left turn into motorway not.
![route2](http://img5.fotos-hochladen.net/uploads/screenshot20162j5da4bfhp.png)

**Comment by sonora** [comment] 2016-10-25 21:47
I have verified that both situations announce the correct destinations with my August 1 Bavaria map, so if there is really an issue it seems to be with our recent map preparation, not with TTS.

**Comment by sonora** [comment] 2016-10-26 08:53
@hakuchi : I guess I found and fixed the glitch, I assume you are using a fixed setting for a Map language, not just "Local names", right?

@vshcherb 
Victor, I guess destination:forward/backward should take precedence over destination:language-code, which I committed here: https://github.com/osmandapp/Osmand/commit/641901e289fac62cb4446633b4cee16eb21b5562

At the same time I changed us using `destination:langage-code` to `destination:lang:language-code` for this feature (I think it is still proposed tagging only) to work at all? Looks like this was another bug, can you double-check this is correct now?

Thx - Hardy

**Closed by sonora** 2016-10-26 08:53 UTC

**Comment by hakuchi** [comment] 2016-10-26 16:16
yes I use fix Map language.

correct keys for destination are:
```
destination=...
destination:backward=...
destination:forward=...
destination:lang:XX=...
destination:lang:XX:backward=...
destination:lang:XX:forward=...
```
and for lanes with destination:
```
destination:lanes=...
destination:lanes:backward=...
destination:lanes:forward=...
destination:lang:XX:lanes:backward=...
destination:lang:XX:lanes:forward=...
```

**Comment by sonora** [comment] 2016-10-26 19:01
Ok, I did some more work here https://github.com/osmandapp/Osmand/commit/958ea414462a20e4d9af6050790483e3a8b67b01 and here https://github.com/osmandapp/Osmand/commit/a610e23988b61f070e423c5deb6e82e0912bd797, and we should now support all these combinations except the ones involving ":lanes". This could be expanded if it is worth it, but we also need to double-check our data preparation contains all these combinations.

**Comment by hakuchi** [comment] 2016-10-26 20:27
_destination:lanes_ are around 17000 on OSM
_destination:lanes:forward/backward_ are each around 2000
_destination:lang:XX:lanes_ are rare in OSM. around 50-100 including forward/backward

**Comment by vshcherb** [comment] 2016-10-30 16:02
I think lang is easy to ignore for now

**Comment by sonora** [comment] 2016-10-31 08:17
- I have documented here https://github.com/osmandapp/Osmand/blob/ab95d0d0590ba558797adb7cc25ae66bbcc8c781/OsmAnd-java/src/net/osmand/binary/RouteDataObject.java#L140 what destination tags we now support, and by what priority order the one to be announced must be selected. `lang:` should now also work now, there was an old bug. Maybe @xmd5a2  could check if we support all these in our data generation.

- I am not currently sure how to support any tag involving `:lanes`, as I guess we need to somehow reference our code of which lane is needed, and also then parse the key value somehow. No rocket science, but it would take me some research, maybe someone in our team could provide a jump start here.
