### ISSUE TITLE
Displayed paths from intermediate points overlay each other

### ISSUE THREAD

**Issue by DDzwiedziu** [osmandapp/OsmAnd#20986] opened 2024-10-06 10:54 UTC
### Description

Paths between the current intermediate point and next intermediate point overlay the current navigation path, decreasing readability.
![Screenshot_20241006-124457](https://github.com/user-attachments/assets/871dc466-5e8f-476a-bc68-3335a24ddbb8)

### Steps to reproduce

Take any two points on the map that would have the same path in both directions.
Set a route from point A to B and back to A.

### Actual result

The path displays in both directions at the same time.

### Expected result

The path from the intermediate point to the next point is either hidden or displayed in a different way to differentiate quickly.

### Your Environment (required)

```
OsmAnd Version: 4.8.5 (however I seen this for years)
Android/iOS version: Android 14
Device model: Asus Zenphone 11/AI2401 H
Crash-Logs: not a crash
```

**Comment by scaidermern** [comment] 2024-10-06 15:04
Duplicate of #9975

**Closed** 2024-10-06 19:06 UTC
