### ISSUE TITLE
Navigation issue - unnecessary turns suggested

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7087] opened 2019-06-24 10:40 UTC
The calculated route suggests making a long loop, while in OSM there is a simple 90° right turn.
Changing navigation settings does not affect the route calculation results. 

from: 53.67696, 10.24849
to: 53.67703, 10.25023
![image](https://user-images.githubusercontent.com/50198677/60012744-6d4b9f00-9685-11e9-803b-9b29462d0834.png)

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=53.67717%2C10.24864%3B53.67711%2C10.24996#map=19/53.67718/10.24918

**Comment by xmd5a2** [comment] 2019-07-18 07:31
Not reproducible. Looks like it was fixed in OSM
![Screenshot from 2019-07-18 10-30-31](https://user-images.githubusercontent.com/5829014/61438020-292b8180-a947-11e9-9eee-0cbc14483856.png)

**Closed by xmd5a2** 2019-07-18 07:31 UTC
