### ISSUE TITLE
Show parkings with the "access=private" tag with icon

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16730] opened 2023-03-17 14:57 UTC
### Description
Show parking lots with the "access=private" tag - currently, they are not displayed on the map

[Taginfo](https://taginfo.openstreetmap.org/search?q=access%3Dprivate)
<details><summary>access=private 493 721 - 10% of all parking lots </summary>
<img width="1000" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/225946166-91a5c27d-d163-4cd6-9590-f563efcb5006.png">
</details> 

<details><summary>Overpass 50197 - Berlin</summary>
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/225945357-4a82fb86-34d2-4e14-85f6-631aabc436ba.png">
</details>

[OSM](https://www.openstreetmap.org/way/1147628335#map=19/52.50596/13.39723)

[Map for checking](https://drive.google.com/file/d/1RrqkvtDKk_mNCXLbhmtBu6WBTHKBeD7o/view?usp=sharing)

### Steps to reproduce
Download the map and check that parking lots are not displayed `52.50592, 13.39719`

### Actual result
Parking lots are not displayed on the map and as POI in search

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/225940675-c75c8c91-db24-48b0-ab46-e6053407ff98.jpeg"  width="400" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/225940682-952c10e8-0ef4-4ba3-a227-3bd62680c07b.jpeg"  width="240" height="auto"/> </th>
  </tr>
</table>  

### Expected result
Parking lots are displayed on the map and as POI in search

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14249mqta, Released: 2023-03-17
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Discostu36** [comment] 2023-03-21 11:37
Duplicate of #13013

**Comment by xmd5a2** [comment] 2023-04-07 07:43
I've done a slight tweak of rendering parkings with access. Now it looks like this.
**Default, no style options:**
![Screenshot_2023-04-07_10-38-09](https://user-images.githubusercontent.com/5829014/230565202-e6d095cc-9f80-4ef2-8e33-10a00f910051.png)

**Show access option:**
![Screenshot_2023-04-07_10-39-08](https://user-images.githubusercontent.com/5829014/230565286-29310354-d21c-4b1a-bdd3-cc495f2d59e3.png)

**More detailed:**
![Screenshot_2023-04-07_10-38-22](https://user-images.githubusercontent.com/5829014/230565313-e2717c38-5f6f-4644-8f10-de1e940568db.png)

**More detailed and show access:**
![Screenshot_2023-04-07_10-38-33](https://user-images.githubusercontent.com/5829014/230565369-2a410ddd-a25e-4972-85b9-b0a3bf7399f6.png)

**Comment by Zirochkabila** [comment] 2023-04-27 10:13
It may be worth adding some kind of marking on the map that this is a parking place + it would be nice if these places were displayed in the search results

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/234832678-278e06d2-bf29-42dd-b899-aa4f1742317d.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment] 2023-04-28 13:27
## Review 
* Unable to select from the map, even with More details is On, no labels or icons on the map.

**Closed** 2023-06-01 07:20 UTC
Labels: rendering

**Comment by xmd5a2** [comment] 2023-06-01 07:21
Added icon to private parking starting from zoom 18. No new maps required.
