### ISSUE TITLE
Show on map disables and doesn't reenable Wikipedia/POI layer

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17944] opened 2023-08-17 07:53 UTC
When enabling POIs via Search / Show on map, currently displayed Wikipedia entries get disabled.

Steps to reproduce:
* Enable Wikipedia layer
* Search / select something / show on map 
* Wikipedia layer gets disabled

However, doing the same via POI Overlay works:
* Enable POI overlay
* Enable Wikipedia layer
* Both POIs and Wikipedia entries are displayed
(order of the first steps is irrelevant)

Shouldn't show on map behave the same as POI overlay? 

OsmAnd 4.5.10.

**Comment by zipav** [comment] 2023-08-21 09:20
OsmAnd Nightly 4.6.0#648m, released: 2023-08-19

The issue is reproduced in the latest version of OsmAnd Nightly.

https://github.com/osmandapp/OsmAnd/assets/123936521/c6fa17c7-3994-4f5b-847d-1b06e41363c0

**Comment by vshcherb** [comment] 2023-09-04 12:58
I think Bug is different, Show on map closes POI / Wikipedia / ... to not disturb from Search. Though it's a technical implementation but it makes sense .

What definitely doesn't make sense and should be fixed. 
- [ ] TODO: once show on map is closed ("cross" is clicked), POI / Wikipedia / Travel (other dependent on POI filter) should be restored

**Comment by vshcherb** [comment] 2024-05-06 14:07
- [ ] Wikipedia should be separate layer (not POI Layer), so it's independent
- [ ] Show on Map should store previous POI Layer in a separate setting and then restore if user clicks Back

**Closed** 2024-08-20 11:09 UTC
Labels: and-bugs
