### ISSUE TITLE
Glyphs are not rendered correctly for local names

### ISSUE THREAD

**Issue by sdranju** [osmandapp/Osmand#3136] opened 2016-10-02 15:53 UTC
Glyphs are not rendered correctly for south Asian languages, i.e. Bengali.
Please see the screenshot (in the link provided) so that you can realize about how the local names are rendered.

https://groups.google.com/forum/#!topic/osmand/8LjkBUF1jBk

**Comment by Zian** [comment] 2016-10-03 04:05
The text is shown correctly on my Samsung Galaxy Nexus in the search results but not on the map. See below screenshots for an example.

![search results](https://cloud.githubusercontent.com/assets/1581929/19027306/e8240558-88e3-11e6-9b05-2a16f327b7a8.png)
![map](https://cloud.githubusercontent.com/assets/1581929/19027305/e8237318-88e3-11e6-9ee7-9b99f622542a.png)

**Comment by osMatt** [comment] 2016-10-06 03:36
The issue mentioned by @sdranju looks similar to #3096. 
The issue raised by @Zian is a duplicate of #1161.

**Comment by onkarshinde** [comment] 2016-10-07 06:30
I can confirm that issue mentioned by @sdranju is same as #3096 logged by me. It seems to affect complex characters in all scripts used by various Indian languages.
Since the text shows properly in search results I assume the fix is straight forward.

**Comment by vshcherb** [comment] 2016-10-19 22:57
Duplicate issue

**Closed by vshcherb** 2016-10-19 22:57 UTC
