### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Nutomic** [osmandapp/Osmand#1386] opened 2015-06-24 00:09 UTC
I tried to build the current master (1c3cbf1816d1a62195f4737798fe7a63f06c643c), but get the following errors running `gradle assembleDebug`:
```
/home/felix/workspace/Osmand/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java:687: error: cannot find symbol
                                        return uiCtx.getResources().getDrawable(R.drawable.mx_highway_speed_camera);
                                                                                          ^
  symbol:   variable mx_highway_speed_camera
  location: class drawable
/home/felix/workspace/Osmand/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java:689: error: cannot find symbol
                                        return uiCtx.getResources().getDrawable(R.drawable.mx_barrier_border_control);
                                                                                          ^
  symbol:   variable mx_barrier_border_control
  location: class drawable
/home/felix/workspace/Osmand/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java:703: error: cannot find symbol
                                        return uiCtx.getResources().getDrawable(R.drawable.mx_toll_booth);
                                                                                          ^
  symbol:   variable mx_toll_booth
  location: class drawable
/home/felix/workspace/Osmand/OsmAnd/src/net/osmand/plus/activities/MapActivityLayers.java:295: error: cannot find symbol
                        it.icon(R.drawable.mx_user_defined);
                                          ^
  symbol:   variable mx_user_defined
  location: class drawable
/home/felix/workspace/Osmand/OsmAnd/src/net/osmand/plus/views/RouteLayer.java:157: error: cannot find symbol
                                Bitmap originalArrowUp = BitmapFactory.decodeResource(view.getResources(), R.drawable.h_arrow, null);
                                                                                                                     ^
  symbol:   variable h_arrow
  location: class drawable
/home/felix/workspace/Osmand/OsmAnd/src/net/osmand/plus/activities/search/SearchPoiFilterFragment.java:261: error: cannot find symbol
                                        icon.setImageResource(R.drawable.mx_name_finder);
                                                                        ^
  symbol:   variable mx_name_finder
  location: class drawable
/home/felix/workspace/Osmand/OsmAnd/src/net/osmand/plus/activities/search/SearchPoiFilterFragment.java:263: error: cannot find symbol
                                        icon.setImageResource(R.drawable.mx_user_defined);
                                                                        ^
  symbol:   variable mx_user_defined
  location: class drawable
```

I also noticed that the [build instructions](http://osmand.net/help/TechnicalArticles.html#Install_Development_Environment) don't contain instructions for gradle/Android Studio.

**Comment by tomeeeS** [comment] 2015-08-09 12:31
Hi, I have the same issue

**Comment by GaidamakUA** [comment] 2015-08-10 13:03
The problem is, you haven't downloaded resources. 
https://github.com/osmandapp/OsmAnd-manifest/blob/master/android_build.xml. This is manifest for repo.
I'm not using repo myself, so I did everything by hand.
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/build.gradle#L233
As this line suggests. Project depends on folder "resources".
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/build.gradle#L195
And if you want to see help, you need help folder.

**Comment by GaidamakUA** [comment] 2015-08-10 13:15
If you are not programmer, and have no idea, what this means.
This is project structure.
.
├── core-legacy
├── Osmand
├── help
└── resources
Osmand - project folder. core-legacy and help are optional.
core-legacy you get from https://github.com/osmandapp/OsmAnd-core
help you get from https://github.com/osmandapp/osmandapp.github.io
resources you get from https://github.com/osmandapp/OsmAnd-resources
You might need to rename folders created by git.
Probably we need to write readme or something. If you succeed building project, I'm closing issue.

**Closed** 2015-08-11 11:06 UTC

**Comment by MichaelSp** [comment] 2016-05-30 21:35
for the googlers: https://code.google.com/p/osmand/wiki/GradleCommandLineBuildEnvironment
