### ISSUE TITLE
Avalanche-focused slope map

### ISSUE THREAD

**Issue by timound** [osmandapp/OsmAnd#10989] opened 2021-02-23 14:39 UTC
Hi, it would be a great feature to have an outdoor activity slope map more focused on avalanches. Risk is basically 0 from 0 to 30% then it increase from 30 to 35 and so on from 35 to 40 and 40+. Such slope map are precious for any outdoor skier, snowshoeing, alpin trail and so on. You can find it on camptocamp.org/yeti or geoportail / carte des pentes. 

À great feature would either:
- generating this map as a layer
- or even better, allowing personalised slope map with precise range

In the actual map, it is nearly impossible to define if a slope is 28 or 34%. Such difference is crucial on site.

Thanks so much,

**Comment by letypequividelespoubelles** [comment] 2021-02-26 14:45
@timound the map from geoportail is only for France, do you know if there is a worldwide map (and usable ! :) )I use fatmap app to have this information, but I guess the data is not open.

**Comment by timound** [comment] 2021-02-26 15:40
@letypequividelespoubelles I have no clues for a usable map like the one on geoportail for other countries. I guess Osmand generated it from srtm datas, so it should be possible to generate it per country.

**Comment by vascotenner** [comment] 2023-02-12 12:46
Duplicate of https://github.com/osmandapp/OsmAnd/issues/9283

**Comment by vshcherb** [comment] 2024-05-14 21:09
Progress made https://github.com/osmandapp/OsmAnd/issues/6636

**Closed by vshcherb** 2024-05-14 21:09 UTC
