### ISSUE TITLE
Vehicle icon jumping along the driven road

### ISSUE THREAD

**Issue by C6competition** [osmandapp/OsmAnd#17364] opened 2023-06-06 10:03 UTC
While driving on a road in moto bike mode the position of the vehicle jumps extremely from one position to the next.
It looks like, the position doesn't get updated often enough. I don't think it's a missing GPS signal, because the orientation of the map on the diplay is updated very rapidly. On the 2 video examples you can see, the higher the speed, the bigger the jumps seemed to be.
The effect is less extrem, when you are running on straights. I am sure, this hasn't been the case on last year version 4.2.7 

https://github.com/osmandapp/OsmAnd/assets/99248549/62252f3a-5700-439f-8957-bb09681e8cbd

https://github.com/osmandapp/OsmAnd/assets/99248549/f93754b9-0653-4e6e-96de-e196fe6e79f3

OsmAnd Version: 4.5.0
Android/iOS version: 10.0
Device model: BV 9900E

**Comment by scaidermern** [comment] 2023-06-06 10:21
Sounds like another duplicate of #16081.

Disable Settings / Profile / General settings / Animate own position

**Comment by C6competition** [comment] 2023-06-06 13:15
Okay, I will try other setting and come back with result when done.
Thank you

**Comment by C6competition** [comment] 2023-06-09 10:59
Thank You @scaidermern 
Your guess was, correct!
Disable Settings / Profile / General settings / Animate own position solves the problem.
The movement of the vehicle symbol is still a little bit rough, but it moves on the road and doesn't jump any more.
May be the roughness has been already as well on OsmAnd Version: 4.5.0, I don't remember.

**Closed** 2023-06-09 10:59 UTC
Labels: Observed
