### ISSUE TITLE
GPX tracks are incorrectly shown with gaps at low zoom levels

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#2522] opened 2016-05-06 14:22 UTC
Since upgrading to OsmAnd 2.3.5, some GPX tracks are shown with gaps at low (less detailed) zoom levels, even though the GPX file consists of a single, contiguous track:

![osmand_gpx_track_gaps_small](https://cloud.githubusercontent.com/assets/638458/15075757/f82b269a-139d-11e6-8208-bd0b3ef0feb8.jpg)

In the previous version it looked like this:

![osmand_gpx_small](https://cloud.githubusercontent.com/assets/638458/15075768/050f4a58-139e-11e6-9cdc-1dfe26ae4371.jpg)

The "shimmering" effect has been fixed in 2.3.5, but now the track is shown with gaps in it.

Here's the [GPX file](http://www.nationaltrail.co.uk/gpx_download?filename=national_trails_cotswold_way_2014.gpx) I'm using.

**Comment by andrew-davie** [comment] 2016-05-06 14:26
Could this be because the tracks are drawn as “dashed lines” instead of solid?
In other words, is the line style giving the appearance of gaps?
When you zoom in, is the line drawn as a dashed line, or solid?

**Comment by njohnston** [comment] 2016-05-06 14:39
When zoomed in, the line is drawn as a series of "lozenges":

![osmand_gpx_zoomed_in](https://cloud.githubusercontent.com/assets/638458/15076242/9f0f7a54-13a0-11e6-8963-8a3273a7752a.jpg)

**Comment by andrew-davie** [comment] 2016-05-06 14:45
Very hard to see from your image, and your word usage is a bit odd. But basically, this is a dashed line.
It’s the line style being passed to the GPX draw code.  It simply honours what is already set, and this is what dashed lines look like when drawn with that particular line thickness and colour. I have two basic thoughts on this;  1) the system should not used dashed line styles or 2) the GPX code should do its own version of dashed-line drawing (which is quite simple for me to do).  But as it stands right now, I do not believe this behaviour is INCORRECT.  That is, the GPX draw code is being passed a dashed line, and it draws with that dashed line - and that’s what it looks like when you do that.  If it were to change to a solid line, we wouldn’t see this problem.
The question is:  why is it being passed a dashed line?

**Comment by njohnston** [comment] 2016-05-06 18:05
Sorry for the unclear screenshot. Here's one where I'm zoomed in much more on part of the track:

![gpx_zoomed_in_small](https://cloud.githubusercontent.com/assets/638458/15081911/0239688a-13bd-11e6-905d-11eff0d51dbb.jpg)

The rendered track is made up of many little segments--they look lozenge-shaped to me, hence my earlier comment.

**Comment by njohnston** [comment] 2016-05-06 23:46
@andrew-davie: you were right. It's being drawn with a dashed line because it's a GPX __route__ rather than __track__. (GPX distinguishes between the two. A route is where you should go; a track is where you've been.)

The rendering can be changed using a custom rendering style derived/inheriting from the default, which includes the `<renderingAttribute name="gpx">` section but deletes or comments out this line:

```xml
<apply_if additional="routePoints=true" pathEffect="6_5"/>
```

It's subjective whether this is a bug or not. Is it desirable to show routes and tracks differently by default? Is using a dashed line wise? At low zoom levels the gaps could be misinterpreted as missing data.

**Comment by andrew-davie** [comment] 2016-05-07 05:50
I could simply write a much better “dashed line” drawing routine. One that, for example instead of on-off dashing could use evenly spaced light/dark. Really easy to do

**Comment by vshcherb** [comment] 2016-05-07 22:21
No need Andrew, we should display it solid since 11th zoom or whatever style is. I will CC @xmd5a2

**Comment by xmd5a2** [comment] 2016-05-11 17:40
I have fixed "lozenges" effect. Closing because  it is a feature not a bug.

**Closed by xmd5a2** 2016-05-11 17:40 UTC
