### ISSUE TITLE
Postcode search: Show name of city/village in case of ambiguous street name

### ISSUE THREAD

**Issue by fe60** [osmandapp/OsmAnd#21357] opened 2024-11-16 13:45 UTC
### Describe the idea

To make it possible to identify the correct street in case of ambiguous names within the area of a postcode, the name of the town or village the street belongs to should be shown to the user. So far the list shows of potential hits show the name of suburbs or hamlets only, which is not sufficient. I do not know the name of suburbs and hamlets without local knowledge.
<table>
<tr>
<td>current</td><td>expected (shows name of city/village)</td>
</tr>
<tr>
<td>
<img width=300 src="https://github.com/user-attachments/assets/7734e14a-9574-448c-90cd-3822c6c07451" />
</td>
<td>
<img width=300 src="https://github.com/user-attachments/assets/8e6c89d6-80ca-4eed-80e5-e4f830108a8d" />
</td>
</tr>
</table>

### Expected behaviour

Add the name of the city/village as mentioned an shown above.

### Alternatives you've considered

Searching for addresses using the name of the city is an alternative. Depending on the name of the city this requires to type more characters compared to the postcode.

### Context

OsmAnd~ 4.8.6
Shown example requires map of Germany => Brandenburg, Berlin

Steps to reproduce:
* Search for Address
* use "Postcode search"
* type `16321` and select the only match
* type `Bahnhofstr`

**Comment by DmitryAlexei** [comment] 2024-11-16 18:18
Duplicate of https://github.com/osmandapp/OsmAnd/issues/2993
will be available in the 4.9 release

**Closed** 2024-11-16 18:39 UTC
