### ISSUE TITLE
New “faster” rendering is super slow

### ISSUE THREAD

**Issue by erik55** [osmandapp/OsmAnd#15977] opened 2022-12-15 09:14 UTC
### Description
A recent update changed to OpenGl rendering and was advertised as being faster. The opposite is true: it is unusably slow. The favorites appear very very late. And only a gray checker board is visible everywhere in new regions. The old rendering always showed something for orientation, although details were loaded a bit later. 

I recommend to change the priorities to the way it was before: Always show something, so that you know where you are on the map and where your favorites are. Priority now seems to be only show it beautiful and with full detail OR nothing. 

https://user-images.githubusercontent.com/1608326/207825719-76541bee-9441-4366-b69c-8a77889d4461.mp4

https://user-images.githubusercontent.com/1608326/207825832-7400e9e2-15ed-44f5-86ee-eb52860a841d.mp4

### How to reproduce?
Compare OpenGl rendering with the old one. 

### Your Environment
OsmAnd Version: Osmand+ 4.3.3
Android/iOS version: Android 10
Device model: Samsung Galaxy S9

**Maps used (online or offline):**   
Many offline maps loaded, many favorites collected over the years.

**Comment by MarioSwitch** [comment] 2022-12-15 09:36
How old is your phone? As the app says, the first version remains recommended for old devices.

**Comment by erik55** [comment] 2022-12-15 09:43
Yes, my phone is not from this year, but still new I would say. It works perfectly otherwise. 

It is just the priorities that Osmand should change like it was before again: Always show something (in lower quality and also the favorites) to have an orientation. Now I only see gray checker board and NO favorites until after many many seconds. See the attached videos above in my edited issue.

**Comment by sonora** [comment] 2022-12-15 09:55
I have also seen this on several devices, not even very old ones. We have implemented a manual switch in `Menu button > Settings > OsmAnd settings > Map rendering engine` where you can select between using the Version 1 or 2 rendering engine.

**Comment by erik55** [comment] 2022-12-15 11:28
If there is this problem on several even newer devices, you should have tried to find the bug first. How can I help to find this bug? I don’t think that many casual users will find this switch. They will just be annoyed and stop using Osmand.

What is causing this behaviour? Why are the favorites loaded with such a big delay? And why are gray areas shown instead of a rough map (like with the old rendering)? Could this be changed?

**Comment by sonora** [comment] 2022-12-15 11:42
It certainly was a risk. I understand that devices not capable of using OpenGL automatically stay with the Version 1 engine, only devices where OpenGL initializes ok will default to Version 2. The problem seem devices which initialize OpenGL ok but in fact have significant issues with it. Currently unclear to me if that is a very small or a rather significant fraction.

**Comment by scaidermern** [comment] 2022-12-15 19:57
> EDIT: This also connects to a suggestion I had raised here #15034: In the v1 engine we instantaneously scaled the existing screen content, and then started re-rendering it (in the case of pinch-zooming even after you took your fingers off). In the v2 engine it seems we immediately start re-rendering, which in any case is slower than re-scaling, even on fast devices.

Yes. There are even more cases where unnecessary redrawings are happening, for example here: #15983.

**Comment by erik55** [comment] 2022-12-15 22:09
My phone is fast enough. 

The rescaling and then re-rendering (also for the favorites etc) is the correct approach for a smooth user experience.

When this is done, THEN you can make the announcement that Osmand has become faster. 

Is there any technical reason it wasn't done that way? Or just forgotten testing and no UI/UX expert to ask?

**Comment by mdykierek** [comment] 2022-12-16 08:22
I have a different question though. I often use OsmAnd on bicycle and when hiking.
How does OpenGL compare to V1 renderer when it comes to battery drain?
A current hungry smooth renderer is fine when plugged in a car's socket, but out in the mountains I really need battery life.

**Comment by vshcherb** [comment] 2022-12-16 09:46
Based on the attached video I couldn't say it's super slow, so the issue is closing. There are other more specific issues mentionned here about rendering flickering and rendering frozen when there are multiple tracks

**Closed by vshcherb** 2022-12-16 09:46 UTC

**Comment by erik55** [comment] 2022-12-16 10:10
The map is usable only after many seconds have passed. Especially the favorites, but also new surroundings (gray). Can’t you just say something about WHY you have decided to change the behaviour, showing gray (= nothing) instead of a scaled version like it was before? Is there a technical reason?

**Comment by erik55** [comment] 2022-12-16 10:33
Here is another video, where you see the many many gray areas. And the loooooong time until the favorites appear. Sometimes they don’t appear at all (even after more than one minute). But I was not able to capture that, as it only happens sometimes.

With version 1 of the rendering at least I always know exactly where I am on the map, and the favorites are always visible (good for orientation). 

And the third video is of Magic Earth where there is NO visible lag, no flickering. Details appear smoothly. I know, they show way less details, but still interesting, that I never see gray areas. (by the way: there are some jumps in the video/map, but they were not there when using the map, seems that the video recording software was to slow or something, everything was totally smooth when using)

**Comment by sonora** [comment] 2022-12-21 08:48
Regarding the immediate re-rendering of the map in v2 rendering **already while pinch-zooming**, there is a related call for feedback by Product Management in issue #15009, maybe someone cares to comment there, too.

**Comment by vshcherb** [comment] 2023-01-04 20:53
probably related https://github.com/osmandapp/OsmAnd/issues/16098
