### ISSUE TITLE
Expired Online tiles don't get deleted/updated when set as Overlay/Underlay map

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#18578] opened 2023-11-17 17:51 UTC
### Description

When setting Online tiles as an Overlay/Underlay map, the expiry time of the tiles is not respected. Tiles are loaded correctly as the map is panned, but are never discarded and redownloaded. The sqlite file is not updated if the tiles are already downloaded even if expired (last date of modification and filesize are not changed). The only way to update them is to use the Map menu>Download Maps>Local (Online and cashed)>Delete all tiles option to delete them and force a new download. 

This seems to be a bug as when set as a base map (Map source option), the expiry time is respected and the tiles are deleted automatically after the correct time. The sqlite file is reduced in size as the expired tiles are deleted.

### Steps to reproduce

Load an Online tile layer as an Overlay/Underlay (OpenTopoMap in my case)
In Map menu>Download Maps>Local (Online and cashed)>Edit:
- set the expiry to a short time (5 minutes in my case)
- set the format to SqliteDB
Explore the map and change zoom levels. Tiles are downloaded but never discarded.

### Actual result

Expired Online tiles don't get deleted/updated when set as Overlay/Underlay map

### Expected result

Online tile expiry in an Overlay/Underlay map behaves the same as when loaded as a base map layer (Map source option). 

### Your Environment (required)

```
OsmAnd Version: fresh install 4.5.10
Android/iOS version: Android 13
Device model: Sony Xperia 10 III
Osmand is installed in manual folder in Storage/emulated/0/Android/media/net.osmand.plus 
```

**Comment by DmitryAlexei** [comment] 2023-11-22 10:52
Opentopomap is not the best example for checking how tiles are updated, since this layer does not change frequently. Expiry time is used to check if tiles have been changed and redownload them if needed.

So this issue is a duplicate of https://github.com/osmandapp/OsmAnd/issues/17776. Please read comments below this request. 

Summary: 
- the app really doesn't refresh online tiles automatically (i.e. do not upload them in background after 1 minute or how it is specified in the settings)
- tiles are only reloaded when the map screen is refreshed (when location or zoom level are changed or when portrait mode changes to landscape mode)
- this is expected behavior.

**Comment by Guylby** [comment] 2023-11-22 11:18
I've read the issue and I see the reasoning but there's still other issues:
- why is the behaviour different with expiring tiles when loaded as a base map (expired tiles are discarded and reloaded as expected) and when used as an overlay/underlay (tiles are never discarded). For the exact same settings (same source, database setting, expiry, etc, only change is loaded as a base map or underlay/overlay). 
- the issue is not that the tiles are not refreshed automatically, as you said they are only reloaded when panning/zooming, etc, and that works as expected when the online tiles are set as a source map (base map). But doing the same when set as overlay/underlay, the tiles are never reloaded. You can zoom, change location, orientation, restart the app and the already loaded tiles will never be updated. New tiles will load fine but the only way to update existing ones is to manually delete them.

I've tested some more: I've setup two profiles, one with the same online tile source loaded as a Map source (base map), the other with it loaded as an Overlay. I've tested with 3 different Online tile sources: Microsoft Earth, OpenTopo and a custom Google traffic layer. 
The behaviour is the same for all sources:
- In profile when set as a Map source: everything works as expected, when the tiles are expired, they are deleted (temporary blank on the map until I change location, dezoom to reload the tile). No problem here, works as intended as you said.
- In profile when set a an Overlay: new tiles are loaded fine, but expired ones are never deleted/updated. Even after multiple hours, zooming, changin location, etc and when I know for sure that the online data has been updated (in the case of the google traffic layer).
- When switching back to the Map Source profile: then the tiles will be deleted/updated again with all online tile sources and works again as intended. 

This is my issue: the difference of behaviour between loading online tiles as an Overlay/underlay or as a Map source, which is not quite the same as #17776

**Comment by vshcherb** [comment] 2023-11-22 15:21
Overlay or Main layer should work identically and probably we need to retest if it's a case

**Comment by yuriiurshuliak** [comment] 2023-11-28 14:57
The bug has been reproduced. Experimenting with OpenTopoMap in SqliteDB format and a 5-minute expiry time:

- Checking with the set map source, you can notice that the expiration time isn't followed, and updates don't occur every 5 minutes. However, refreshing the map by moving or zooming, triggers updates.
- Similarly, when only using overlay/underlay without specifying the map source,  the situation is the same. The map updates when moved or zoomed in; otherwise, it doesn't update automatically.

In other words, tiles are not automatically loaded in any case; they require a zoom action to refresh their status.

Regarding tile removal, I conducted tests with both the internet on and off, for confirmation:

- With a set map source and the internet off, zooming in results in an empty map. On re-enabling the internet, the map displays again.
- In the case of only using overlay/underlay and turning off the internet, the map retains its state without any changes even after the internet is turned back on.

OsmAnd~ 4.6.0#1104m, released: 2023-11-28

<table style="width:100%">
  </tr>
  <tr>
    <th>Updating with map source</th>
    <th>Updating only with overlay/underlay</th>
    <th>Deleting tiles with a map source</th>
    <th>Deleting tiles only with overlay/underlay</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/700ba4ae-41f8-45c2-b8ee-84b4c2197527"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/a31f33d4-89ab-4f88-9971-0d6a2823abd4"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/7dcf4dae-0fff-4b47-9a1b-49c847870a8d"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/1ef73472-0f38-4f63-ab6a-f4f1fa284b60"  width="300" height="auto"/>   </td>
  </tr>
</table>

<table style="width:100%">
  <tr>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9b1c8af1-81e7-40d8-8c91-538039fbb0fc"  width="150" height="auto"/> </th>
  </tr>
</table>

**Closed** 2023-12-10 12:51 UTC
Labels: opengl

**Comment by yuriiurshuliak** [comment] 2023-12-12 16:49
Up until now, I've investigated the issue concerning the map source and overlay/underlay. Presently, the maps within the tiles folder receive updates continuously rather than only upon zooming in or shifting the map. They consistently reflect a status of "just now."

In my testing of tile removal, I've run tests in both online and offline modes. The map source and overlay/underlay functions now operate identically, consistently displaying the map regardless of whether the Internet connection is on or off.

OsmAnd~ 4.6.0#1203m, released: 2023-12-12

<table style="width:100%">
  </tr>
  <tr>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0464f817-0b2d-4efc-98c3-b148752c7800"  width="300" height="auto"/> </th>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/7cd089a5-688b-45a8-853d-2bf96df8d83c"  width="300" height="auto"/>   </td>
  </tr>
</table>
