### ISSUE TITLE
Add a search bar to more easily pick destination among favorites

### ISSUE THREAD

**Issue by serpico** [osmandapp/Osmand#6925] opened 2019-05-11 07:53 UTC
Please give us the following information so that we can try to **reproduce** your issue:

When selecting origin or destination for routing, the user can choose between different options ( Select on map, Favorites , Markers, etc...).

When choosing Favorites we can again toggle between "sort by name" or "sort by distance", it'd be great to have a search bar on top to narrow it down in case of a long list of favorites (see screenshot)
![Screenshot_2019-05-11-09-30-52](https://user-images.githubusercontent.com/1227077/57566944-87ca0180-73d2-11e9-914f-6656c4a200d7.png)
. 

What version of OsmAnd are you using, on what device and Android/iOS version?
OsmAnd~ 3.3.8 from F-droid
Samsung GT-I9195
Android 4.2.2

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
offline maps

**Comment by scaidermern** [comment] 2019-05-12 10:02
Duplicate of #5468.

Also related: #6702

**Comment by vshcherb** [comment] 2020-02-10 11:26
Duplicate #5468

**Closed by vshcherb** 2020-02-10 11:26 UTC
Labels: Nice to Have
