### ISSUE TITLE
search history handling is confusing

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#18657] opened 2023-12-02 09:05 UTC
### Description

I know there are three sections in the "search" area (settings > osmand settings > history): 

the search history, 
the navigation history and 
the map marker history.

Now I enter the search results via the magnifying glass. 
Here I see the content of _two of this three_ sections: the "search history" and the "navigation history", but not the "map markers history". 

Why?

Next: 
I select one of the via magnifying glass listed points (long tap), that is included in the "search history"-list: it leads me to the search history and I can delete this entry.
But if I select a point thats included in the "navigation history", I´m also lead to the "search history" and here I can do nothing, because the selected point does not exist here.

Why it´s that confusing?

Selecting a searched point listed via the magnifying glass should lead the user to the section it´s listed in and not to somewhere else. 

### Steps to reproduce

try as described.

### Actual result

confusing as described

### Expected result

not confusing, easy to understand?

### Your Environment (required)

OsmAnd Version: +4.6.6
Android/iOS version: 13
Device model: S20+

**Comment by DmitryAlexei** [comment] 2023-12-03 14:50
It is a duplicate of https://github.com/osmandapp/OsmAnd/issues/18053

**Closed** 2023-12-05 13:39 UTC
