### ISSUE TITLE
Crash on calculating Public Transport route

### ISSUE THREAD

**Issue by Araly** [osmandapp/OsmAnd#10990] opened 2021-02-23 15:36 UTC
### Description

Whenever I try to calculate a route with the Public Transport mode, it crashes, and I have to open the app again. This happens in every city I tried. This happens on the F-droid version, 3.9.

On the latest nightly opengl one, doing the same thing doesn't crash the app, but it never finds a Public Transport route.

### How to reproduce?

- Select a place in the city
- Press Directions
- Select Public Transport (the Bus icon)
- App crashes

### Your Environment
OsmAnd Version: 3.9.6 (and 4.0.0#12653mqta for the nightly build)
Android/iOS version: 10 (LineageOS 17.1 with microG)
Device model: POCO F1 (beryllium)

**Maps used (online or offline):**   
Offline maps, most specifically I tried in Bordeaux, Montpellier, Avignon, all in France

**Comment by starsep** [comment] 2021-02-23 22:56
I confirm the issue. It's likely a duplicate of #10446

**Comment by muchuelo** [comment] 2021-03-25 16:49
I can also confirm this is happening.
Version 3.9.10 from F-Droid

**Comment by sepplhans** [comment] 2021-04-05 20:53
Same here. 
Lineage OS with Micro-g on a oneplus6T.
Osmand version 3.9.10 from F-Droid with offline maps.

**Comment by starsep** [comment] 2021-04-06 07:21
I tested `master` branch a while ago and this issue seemed to be fixed. Any chances of getting it released?

**Closed** 2021-06-02 11:34 UTC
Labels: Observed
