### ISSUE TITLE
Routing error at Steinbergerstrasse, Feldmoching 48.218540 N, 11.545648 E

### ISSUE THREAD

**Issue by hman2** [osmandapp/OsmAnd#9951] opened 2020-10-05 11:42 UTC
# 🐞 routing report

### Routing engine

- [x ] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

bike

### Start and end points

Lerchenstrasse, Feldmoching to Unterschleißheim

### Actual and expected routes

Two highways have to be crossed under. There are two ways to this: Either follow the state street ST 2342 north (has a bike lane nearby, but because of heavy motor traffic undesirable) or follow Frankaustrasse north. That DOES go under the highways although that is not on OSM street maps.

But OSM follows Steinbergerstrasse beyond the coordinates 48.218540 N, 11.545648 E, which is totally wrong. There is NO road there. None at all. It is agricultural farm land, there isn't even a path that could be followed. Steinbergerstrasse is a dead end at these coordinates!

Look at the satellite image on Google Maps: https://goo.gl/maps/kyJY4rAWshNFoJMW9

There is nothing. Delete anything that's in OSM maps there.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

3.7.4

</code></pre>

**Device and Android/iOS version:**
Fairphone Open OS 19.11.2 (AOSP 7.1.2)

**Maps used (online or offline):**

- [x ] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

Streep maps of upper bavaria (Oberbayern), dated September 1st 2020

**Anything else relevant?**

**Comment by hman2** [comment] 2020-10-05 12:27
Remark: The cross-under IS on Open Street Maps, but possibly blocked because of a former (!) construction site due to bridge maintenance. But that is gone, the cross-under is freely passable. I opened another ticket for the cross-under (9952).

**Comment by hman2** [comment] 2020-10-05 12:33
2nd remark: Optimal route would be Raheinstrasse, not Frankaustrasse (other side of the railway).

**Comment by aceman444** [comment] 2020-10-08 22:33
As can be seen in the OSM note on that spot, it is not clear whether the road really does not exist: https://www.openstreetmap.org/note/2374855 . Anyway, that would be an OSM data error, not with OsmAnd.
The road is tagged with vehicle=agricultural, which I would say forbids bicycle access, but OsmAnd explicitly allows bikes on vehicle=agricultural roads in its routing rules. It may depend on country laws, but sadly OsmAnd still didn't implement per-country routing defaults...

**Comment by vshcherb** [comment] 2020-10-09 15:28
@aceman444 
Well it's quite easy to implement. We usually propagate extra tags based on the country name region.
Feel free to take a look at rendering_types and propagate let's say "region:access=no" to backend, please feel free to make pull request if you would like to contribute.

**Comment by hman2** [comment] 2020-10-10 07:06
The remark in OSM is from me. Look at the Google maps link I provided here in this report. Then you can see that the road (Steinbergerstrasse) DOES exist, but only up until the coordinates I gave. It comes from South and extends north only to the coordinates. There this road simply ends, end further north, there is only farm land without a path. Very clear to see on the satellite images from Google. OSM has a map error there. Possibly, if you look at on a larger scale, there are (or have been) plans to prolong Steinbergerstrasse, but they have never been put into construction. Today Steinbergerstrasse is a dead end precisely at the coordinates I gave...

**Comment by aceman444** [comment] 2020-10-19 17:05
Then you have to get this fixed in OSM data itself (www.openstreetmap.org), OsmAnd can't do anything about it, it just consumes the OSM data.

**Comment by hman2** [comment] 2020-10-20 12:16
The OSM people say OsmAnd should not route bicycles further north, as the non-existent path is marked as being pedestrian passable only. They say. I cannot check this.

**Comment by pebogufi** [comment] 2020-10-20 12:48
@hman2 
Which of the remarks is of you, there is more than one. If you have been there and tell us there is no path, then we can delete it. 
Anonymos remarks and as well satelite photos are treates as **not reliable**. 
So we need a clear comment of somebody who was there.

**Comment by hman2** [comment] 2020-10-20 13:10
I made more than one remark, because it is not possible to add remarks to remarks, and positioning a new marker almost always is a tiny little bit off in one direction or the other. I just don't want to make hundreds of user accounts for multiple services, so wherever possible I run without. For Github I have one, for OSM not.
But how can a satellite image be "not reliable"? Do you suspect fakes? I know OSM (and OsmAnd) cannot integrate Googles images for copyright reasons, but no one can prohibit LOOKING at them. Steinbergerstrasse ends at the coordinates I gave. I have been there in person (actually I got stuck there. I followed OsmAnds route, it was night and all of a suddend I had to make a full stop in order not to ride into the rough (I don't have a mountain bike, only a plain city bike).
Btw., this reminds me that I always wanted to make a feature request that while using OsmAnd I could declare the current road "blocked", requesting a different route to target without use of this road.
I know also that for reasons unknown Google maps draws Steinbergerstrasse further, but this can only be explained by Googles access to official (local government) maps. Maybe there have been plans to extend Steinbergerstrasse, which I do not know, but visible to the naked eye they have never been put into construction.

**Comment by pebogufi** [comment] 2020-10-20 13:30
I deleted the way.

-- But how can a satellite image be "not reliable"? 
Because we don't know the age of the image, it might be outdated. 
"might be outdated" is not reliable.
Don't use outdated information for tagging.

**Comment by aceman444** [comment] 2020-10-20 19:24
@hman2 you are not allowed to look at Google maps/photos and then enter any data into OSM based on them, regardless if the maps are integrated into any OSM editor or not (and you just viewed Google in a browser). If there is no road on Google and there is one in the allowed imagery, deleting the road based on the Google imagery is prohibited. You can only do it if you personally were on the place and are 100% sure the road is not there. Also note there are many levels or road quality and some track with tracktype=grade5 could be there passable with an agricultural machine or an offroad car. Such roads may not be seen on the spot, but could be visible on imagery because of better context and different light conditions or state of vegetation.

**Comment by hman2** [comment] 2020-10-22 15:01
I have been there in person. There is no road. And if "agricultural machines" count, then almost the entire planet would be one huge road (only buildings, mountains and water bodies would be unpassable), because with agricultural machinery you can drive anywhere in the open and do not need any road, path or track - because that is the use case for these machines, driving on open farm land... 

@pebogufi: You cannot "unbuild" a road. Even you do, at least the vegation would take a year to grow after a road has been demolished, but no one demolishes roads that were once built. There has never been a road, and there is no road now.

**Comment by pebogufi** [comment] 2020-10-22 15:26
@hman2 
I think with deleting this path the problem is solved. So you can close this issue.

**Closed** 2020-10-22 20:12 UTC

**Comment by aceman444** [comment] 2020-10-24 17:06
@hman2, agricultural machines can repeatedly use a part of the field and then they puch the grass/crop and create a "track", which is then visible in the aerial imagery. Of course, there is no paving, which would need to be demolished or grown over. Still, bicycles or pedestrians can use such a way and it can be added into OSM, using proper tracktype and surface values.
Such a road can vanish in a year by growing grass or just the next seeding of the crop in question. So if you did not see the road today, it does not mean it wasn't there a year before and it can be seen in all imagery, that's why people ask.

**Comment by hman2** [comment] 2020-10-27 16:27
Not everyone owns a mountain bike. With a regular bike you can NOT ride on open terrain (and most of the time that is prohibited anyway, just talk to the owner of that land whether or not he/she approves of riding a bike on his/her farm land), and THAT should be what OSM bike routes should be selected for. You need at least a road with dirt or sand coating to ride a bike without accident (unless it's a mountain bike with proper tires for terrain use).
