### ISSUE TITLE
2.8.2: Default profile: always starts "World" despite set to "Bicycle"

### ISSUE THREAD

**Issue by ProBackup-nl** [osmandapp/Osmand#4889] opened 2017-12-31 08:58 UTC
What version of OsmAnd are you using? 2.8.2
On what device: GT-I9505 (Samsung Galaxy S4)
What Android version? 6.0.1 (SlimRom)

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps? offline

Reproduce: 100%
 1. OsmAnd Hang / Force quit -> reopens with "World": 100%
 2. Phone reboot  -> reopens with "World": 100%

General Settings shows correctly: "Default profile": "Bicycle" selected.

--- 
Side note for my own administration: OsmAnd Hang happens a lot with "Configure Screen"-> "Remaining elements" -> "Street name" enabled.

**Comment by sonora** [comment] 2017-12-31 14:00
I think you "hang" issue may be related to #4734.

Regarding the "default" profile: I cannot reproduce this, I guess it is already fixed in 2.8.3 and later.

**Closed** 2018-01-16 09:55 UTC
