### ISSUE TITLE
Touring view: road surface and quality doesn't render (OpenGL)

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#15049] opened 2022-08-10 08:31 UTC
### Description
**Road surface** and **Road quality** don't render when Touring view map style is selected using OpenGL build, in previous rendering engine is shown.

**OsmAnd versions:**
OsmAnd~ 4.3.0#13700mqta, released: 2022-08-10
OsmAnd Nightly 4.3.0#34467m, released: 2022-08-09

**Maps used (online or offline):**   
Vinnytsia oblast, Ukraine • Aug 1, 2022.

**Coordinates** 
49.73730° N, 28.67977° E

<table style="width:100%">
  <tr>
    <th>OpenGL, Map style OsmAnd</th>
    <th>OpenGL, Map style Touring view</th>
    <th>Default, Map style Touring view</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/183854199-3df2a533-8223-4bd7-8055-0846765d05f3.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/183854196-214f1c60-f0cf-481f-ac78-6fbce2de3e70.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/183854155-80d24cb4-cb31-4ccb-aeaf-cdadea650251.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Velomeloman** [comment] 2022-08-10 21:07
Duplicate of #14884

**Closed** 2022-08-11 14:47 UTC
