### ISSUE TITLE
Search for transport routes fails

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#18708] opened 2023-12-10 13:41 UTC
The use case is you are trying to display a certain public transport route, say "Bus N11" in Rome/Italy, to figure out where to pick it up.

On our search we have e.g. the search category"Bus" or even "Public Transport", but selecting that and then typing the route name like "N11" does not seem to produce the desired result.

**Comment by sonora** [comment] 2023-12-10 16:59
PS: It looks like hiking / cycling routes are also not searchable by name. May be a nice feature to include them also.

**Comment by vshcherb** [comment] 2023-12-11 15:21
It's even in roadmap

**Comment by DmitryAlexei** [comment] 2023-12-12 08:28
duplicate of https://github.com/osmandapp/OsmAnd/issues/5924

**Closed** 2023-12-12 14:22 UTC
