### ISSUE TITLE
GPX Display - OsmAnd crashes with OOM in my places/tracks menu

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17290] opened 2023-05-28 08:26 UTC
### Description
Osmand crashes frequently when being in the new my places/tracks menu. Even when doing nothing, just having the menu displayed and leaving the device alone for a minute or so. Sent many similar crashlogs the last two weeks to your mail. The attached ones are from today. Happens always and only when being around in the new tracks menu.

Additional note: in this new myplaces/tracks section I can´t see if a track is already displayed or not (like in the old menu, there was a gray or coloured track symbol, if displayed or not). I know, there is a section "displayed tracks". But there I never know, if _all_ tracks of a certain folder are displayed or not (like it was possible before).
 
### Steps to reproduce
being around in the new my places/tracks menu, no specific action; sometimes doing nothing at all 

### Your Environment
OsmAnd Version: began somewhere around 4.5.0#15m, and still in 4.5.0#99m
Android/iOS version: 13
Device model: S20+

[exception.log](https://github.com/osmandapp/OsmAnd/files/11584015/exception.log)
[exception-1.log](https://github.com/osmandapp/OsmAnd/files/11584018/exception-1.log)
[exception-2.log](https://github.com/osmandapp/OsmAnd/files/11584020/exception-2.log)

**Comment by Rowin63** [comment] 2023-06-04 21:04
It seems to be a "Engine 2" problem.
Did a fresh install and first what happened at startup was a crash related to Engine 2. Tried again with Engine 1. Then I could display 280 short tracks and change their appearance without any problem. Doing the same with 100 short tracks and Engine 2 ends up in crash by crash. Can send you every day XX exception logs.

**Comment by Rowin63** [comment] 2023-06-08 10:13
Hello!

The last weeks/months I was planning a 3-4 weeks away-from-asphalt trip through the balkans, from Greece via N. Macedonia, Albania, Montenegro, Serbia, BiH, Croatia and Slovenia back home to Austria. For this, I very often have a variety of tracks displayed; tracks I´ve collected from friends, tracks I found online, tracks downloaded from the TET page. Some of them are longer ones (a TET can cover 3000 or more kilometers), some are just short connection tracks, but in sum it´s always many tracks and many kilometers.

Until some time ago, it was no problem to display all those tracks, set a different appearance to different track groups and beside this doing my own planning, creating the route and also set lots of favorites of our interest. Again, since a few weeks this is not possible anymore. Not in the latest playstore version and not in all the beta builds (android-full-arm64). Its not possible even  to display only a part of the tracks I was usuing before. Osmand crashes even with only eight selectet TET tracks (the ones that cover the balkans). 

Things that were possible before are not possible at all now.
I really hope, I soon can use Osmand like it was possible before.

Thanks.

**Comment by Rowin63** [comment] 2023-06-08 12:50
Unfortunately not, also happens in V1.
Here´s the actual logfile, the last entry is with V1

[exception-1.log](https://github.com/osmandapp/OsmAnd/files/11688282/exception-1.log)

**Comment by Rowin63** [comment] 2023-06-08 13:15
Tried it now with only one track, the attached TET France (needed to rename the .gpx to .txt for uploading).
Osmand crashes while loading/displaying this file.

[TET_France_2023-01-30.txt](https://github.com/osmandapp/OsmAnd/files/11688640/TET_France_2023-01-30.txt)

**Comment by sonora** [comment] 2023-06-08 13:25
Hm. That track works for me ok, shows a length of 12 653km, criss-crossing all over France.

**Comment by Rowin63** [comment] 2023-06-08 13:44
I´ll try that again (did this a few days ago - did a fresh install and had only two countries installed after that, did not help).
Right now I began deleting track folders one by one from the my places / tracks and osmand crashed while doing so...

**Comment by Rowin63** [comment] 2023-06-08 14:03
Thanks for your investigating!

**Comment by sonora** [comment] 2023-06-08 14:40
Device model: S20+? Very weird, in deed!

**Comment by Rowin63** [comment] 2023-06-08 15:04
The last thing I could do:
I deleted ALL my tracks/folders except the 34 European TET tracks.
Then began to display them one by one.
At track 11 osmand crashed, from this point is the attached log.

After this crash I restarted osmand and those 11 tracks were displayed.
So I continued selecting the next ones, what caused the next crash.
Restart: 13 tracks displayed. Selected the next ones: crash again.
Resart: 15 tracks (takes some time) are displayed. Selected the next ones: crashed again.

Didn´t continue at this point.
But by now it seems, the amount of tracks-data is causing this problem (and not the maps/contour lines/wikis)

[exception-3.log](https://github.com/osmandapp/OsmAnd/files/11689841/exception-3.log)

**Comment by Rowin63** [comment] 2023-06-09 06:11
As this crashes don´t happen on my Tab Active 3 (running Osmand +4.5.0) I noticed also some other different behaviour:
When adding tracks to the already displayed ones (like written in the previous post), ALL visible tracks are re-drawn again (it starts with an empty map, and the previous displayed as well as the new selected ones are drawn step by step).

In the 4.5.0 (wich still has the "old" my places / tracks menu) the previous selected/displayed ones remain visible and only the additional selected ones get (slowly) added/displayed.

**Comment by sonora** [comment] 2023-06-14 06:16
@Chumva Here's a number of different crashes with yesterdsy's build:  [exception.log.txt](https://github.com/osmandapp/OsmAnd/files/11742273/exception.log.txt)

**Comment by vshcherb** [comment] 2023-06-17 19:26
- [ ] https://github.com/osmandapp/OsmAnd/issues/17382

**Comment by Rowin63** [comment] 2023-06-18 07:15
New release 4.5.2 and the crashing continues...

**Comment by Zirochkabila** [comment] 2023-06-18 08:40
@Rowin63 this issue is still in progress

**Comment by Rowin63** [comment] 2023-06-18 08:44
Ok, thanks

**Comment by Rowin63** [comment] 2023-06-25 08:48
One of the numerous "out of memory"-crashes, when doing nothing. Just watching the map.

[exception-3.log](https://github.com/osmandapp/OsmAnd/files/11859195/exception-3.log)

**Comment by Rowin63** [comment] 2023-06-29 05:59
I don´t know whats going on, and can´t believe that I´m the only one having this "out of memory" problem.
Since weeks Osmand keeps on crashing. Sent already >100 crash reports to your "crash"-address, without any single feedback from there  Don´t know what to to. It´s impossible to use Osmand for my next trips planning.

**Comment by sonora** [comment] 2023-06-29 06:44
Yes, it's really weird. My tracks folder has 3500 files and about 280MB. What are your numbers?

Perhaps it's the overall folder size causing this?  Or certain tracks, the 10 MB TET _France you once shared still sits in my import folder. Causing no obvious issue while not displayed, but making OsmAnd sluggish while visible.

In any case, I think the situation deserves a diligent review, rock solid management of GPX file must be one of OsmAnd's core features.

I am using rendeter V1. I have a feeling that from its very start V2 had issues of being slower when e.g. displaying GPX. It also seems that all the track screen rework has not yet reached the stability and performance of the prior MyPlaces>Tracks screen.

**Comment by Rowin63** [comment] 2023-06-29 07:22
I know, the collection of all my tracks is extensive (main difference to yours is in it´s data size!): 1600 tracks / 50 folders / size ~1Gb (and about 50 maps/contour lines/wikis).

But also a fresh install of the free 4.4.7 with reduced data (170 tracks / 6 folders / size ~150Mb) and only one single small map (Lower Austria) makes no difference, like mentioned three posts above.

**Comment by vshcherb** [comment] 2023-06-29 07:26
Most of the crashes related to displaying or loading GPX tracks.
```
	at net.osmand.gpx.GPXUtilities.loadGPXFile(GPXUtilities.java:1324)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:82)
```

I doubt that 1 track can cause this issue. 
1. What can cause that during track preparation multiple threads allocate too much memory - unlikely cause we limit number of threads and not reproduced 
2. Too many tracks are displayed at the same time - likely

We didn't reproduce it yet and it is hard to reproduce with simulated data cause it can have different structure. You can provide an export of your tracks to our support email, so we can investigate on your data with our devices and say whether it crashes and then we can take it from that point. 

Until we got it reproduced ourselves we won't be able to provide an optimal algorithm I think

**Comment by Rowin63** [comment] 2023-06-29 07:41
So one of the remaining 170 tracks will cause this? But it also happens without having any tracks displayed? Or is it just "by the contents" in the tracks folder? (Osmand is processing all the contents at starting the app?)

I can try another fresh install, then checking tracks folder by folder. But if it is not one certain track but a combinatione of some, I will never find out...

**Comment by sonora** [comment] 2023-06-29 07:47
One additional hint: I am a bit baffled by the fact that ever since we have the new track screens, whenever I enter My Plces > Tracks, and again the Visible on maps tab, I receive 3-5 seconds of waiting time, looking at the spinner (spinner in the first case, the running ribbon in the second). I remember entering the old tracks screen as essentially instantaneous. So not really sure what we always do now at these points... and if that already may create issues? The "running ribbon" also gets stuck quite often, so we seem to keep the device really busy with something...

**Comment by vshcherb** [comment] 2023-06-29 22:21
We need to have better logs to see if there are some wrong. @sonora if you introduce log somewhere in the method GPXFile.prepareInformation we might see if there are some strangely too many expensive operations going on. Other ideas might come

**Comment by Rowin63** [comment] 2023-06-30 06:27
Sent the exported data to your crash address, referring to this issue.
When creating this export, there were only these three track sub-folders, containing 86 tracks (56Mb), in the devices tracks folder (all others I did delete). Selecting and displaying this 86 tracks leads to OOM.

But in different ways: sometimes the app crashes while "building" the map (displaying the selected tracks very slowly one by one). Sometimes (after a few crashes and restarts) it is possible to reach the end of this displaying process with all tracks being displayed. After this, waiting some extra time (2 minutes around), then it is possible to pan the map. But never zoom in, this leads to freeze and crash. Always. 

The OOM-crash is reproduceable here on my device, with this exported data. 
Trigger seems to be the 8 tracks in the TET folder, in combination with the others.
Tried it several times, crashes without exception (S20+, Android 13, V+4.5.3).

**Comment by Rowin63** [comment] 2023-07-07 06:33
Ran the update to 4.5.4, then started the app and after two minutes without doing nothing, Osmand crashes.

[logcat.log](https://github.com/osmandapp/OsmAnd/files/11975350/logcat.log)

**Comment by Rowin63** [comment] 2023-07-08 08:52
The previous logcat was after the crash and probably useless.
This one here is shortly before a crash.

Until then I did:

) fresh install +4.5.4
) copied my tracks in Osmands tracks folder
) start osmand with no tracks displayed > running fine.
) displaying about 50 tracks / 2500km, osmand crashes.
) at next start, those previous selected 50 tracks are displayed (somewhere in the logcat I see memory 18%)
) when selecting additional tracks osmand crashes again
) at the next start I deselected all the displayed tracks, but still osmand is very slow
) re-started osmand again, it is busy for minutes and slow > from this point is the attached logcat.
) after this I closed the app and restarted
) Osmand starts with a crash immediately at start (after one or two seconds)
) next start is fine again, it runs smooth ( with no tracks displayed)

And here I can start again displaying tracks, leading to the next crash ;-)

Maybe this attached logcat can help, it was before the crash...

[logcat-1.log](https://github.com/osmandapp/OsmAnd/files/11990286/logcat-1.log)

**Comment by Rowin63** [comment] 2023-07-08 10:40
Importing this track (needed here to rename it gpx > txt)

[TET_Spain_2023-06-28.txt](https://github.com/osmandapp/OsmAnd/files/11990461/TET_Spain_2023-06-28.txt)

leads to this (after about three minutes of loading)

![20230708_122747](https://github.com/osmandapp/OsmAnd/assets/95540936/1547cee1-7a74-4604-ae3c-f3cb33f81da6)

and a few seconds later to this

![20230708_122808](https://github.com/osmandapp/OsmAnd/assets/95540936/2e42e58f-e408-4826-834c-9a6a741ab682)

**Comment by Rowin63** [comment] 2023-07-12 08:59
Crashing also here (closed issue #17463).

**Comment by Rowin63** [comment] 2023-07-16 12:18
In the "new" my places menu, the second tab contains "all" tracks. Here on my device this is ~1500 tracks.
I can't scroll all down or up again without crashing.

Anyway, scrolling through a long list of tracks is laborious (no "all up/down" or a slider)

**Comment by sonora** [comment] 2023-07-16 12:34
I guesshaving an "All" folder may actually be obsolete. The search works on "All" tracks anyway. If we implemented an "All visible" folder in connection with this mechanism #17538, it would likely suffice and we had much less to debug?

**Comment by Rowin63** [comment] 2023-07-16 12:37
Crash also happens with no displayed track.

**Comment by Rowin63** [comment] 2023-07-16 13:07
I really don't know what to do or better let be.
Now, after the last crash when scrolling the "all" tab, I can do so and nothing happens. It seems, as soon as I touch any track, the evil begins.

**Comment by Rowin63** [comment] 2023-07-17 04:43
It seems like every action related to tracks leads to a OOM crash. Moving tracks from one folder to another does. Renaming a folder does. 🤔

**Comment by Chumva** [comment] 2023-07-25 17:50
Last npe should be fixed [here](https://github.com/osmandapp/OsmAnd/blob/e2148912703e2698a7b63b227035e19d4080becf/OsmAnd/src/net/osmand/plus/views/layers/PointLocationLayer.java#L521-L522)

**Comment by Rowin63** [comment] 2023-07-31 06:45
Again. App was in the background, doing nothing. When I switched back to the app, it crashed or was already crashed.

Crashlog was sent to your crash-mail (don't know why, I can't attach it on the mobile)

**Comment by Rowin63** [comment] 2023-08-03 06:28
I absolutely don´t understand, that no other Osmand user in this world has this problem, and I here can reproduce it on all my devices (S20+, S20+5G, Tab S6, Tab Act3) and in all available Osmand versions (free, nightly, pro). No tracks, no crashes. Many tracks, many crashes. Absolutely reproduceable.
Unfortunately it is not possible for me. to save the logcat, which seems to show the way to the crash (going OOM), because it is resetted after every crash. You, respectively your crash-mail recipient, have seen XXX´s of my crashlogs, which I sent since March, since months now. 

I can´t solve this problem. 
But I actually can reproduce it.

**Comment by sonora** [comment] 2023-08-03 06:43
I can only think of the number of tracks/folders or the nature of the tracks causing the issue.

I run OsmAnd with 3500 tracks in about 75 subfolders, have no such issue.

So assuming the sheer number of tracks or folders is not the issue, it could be the size of your tracks. I remember a track from you which had over 10MB, covering entire France. Do you have many of these? To debug this, can you perhaps test without the very large ones? (My largest ones seem 1.6 MB, no or few waypoints in each.)

**Comment by Rowin63** [comment] 2023-08-04 09:39
Yes, some of the tracks are large, you´re right. And yes, this issue is depending on (large) tracks.
But until now I could not find out any value, until the crashes begin. 
The crashes appear reproduceable on displaying a "critical" amount of track data. But, and this confuses me, sometimes Osmand also crashes with no tracks on display (like processing them in the background?) And after a crash, very often the tracks that caused a crash, at Osmands next start are being displayed properly. And after a while, often doing nothing, Osmand crashes again.

I really don´t see this "red line" (like "stop here adding tracks"...) If it would be that simple to me, I´d do so.
I´ll keep on trying... 
The only thing I know is, **_I_** can´t solve this.

And on crashing Osmand tells me "help us getting better and tell us about this issue". So I do :-)

**Comment by sonora** [comment] 2023-08-04 14:53
Since it is an "out of memory" error, it may not depend on _displaying_ tracks. Perhaps indexing them in the background, adding them to the GPX database, etc. is enough to cause the error. In a sense, it may be connected to things we do differently now with tracks than before,. similar to #17805.

**Comment by Rowin63** [comment] 2023-08-04 16:07
I don´t want to contradict you, but the beginning of a series of crashes mostly happens after selecting a bunch of tracks to be displayed. Tracks appear on the map, one by one, getting slower and slower. If I then go to "Extensions>Osmand-Development>Settings>Logcat-Buffer" there is hundreds of lines scrolling by. And one line shows a number of percentage, this percentage is going lower one by one. Reaching 0% or shortly before, the crash happens.

And this 
...
"Caused by: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 4949576 free bytes and 4833KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC." 
...
is always in the exception log.

Sometimes it happens, that all selected tracks get displayed on the map. But then I just need to pan or zoom in, and osmand is getting jerky, is going to freeze and crashes.
Sometimes it happens, at the next start after a crash, that all previous selected tracks are properly displayed.
Sometimes I can use Osmand then, and sometimes it crashes after a while, even if I´m doing nothing but watching the map.

This is the percentage in the logcat I mentioned before:
![Crash-Memory](https://github.com/osmandapp/OsmAnd/assets/95540936/da7b2547-2b6f-4d43-94f6-d3c1f480f3b1)

**Comment by Rowin63** [comment] 2023-08-04 16:18
This logcat I "cought" a few moments before the crash, right now.

[2023-08-04 18-10-13.772 logcat.log](https://github.com/osmandapp/OsmAnd/files/12262591/2023-08-04.18-10-13.772.logcat.log)

**Comment by Rowin63** [comment] 2023-08-05 07:41
Starting Osmand > no tracks on display > doing nothing > after 6 minutes Osmand crashes > Starting Osmand again > no tracks on display > doing nothing > after 6 minutes nothing happens > going to "configure maps/tracks/all" scrolling down and up and down > Osmand is getting jerky and crashes

**Comment by Rowin63** [comment] 2023-08-05 09:39
It also happens when entering the old "my places / tracks"-menu.

**Comment by Rowin63** [comment] 2023-08-05 11:38
Now I did add folder by folder.
When it came to those large tracks and the stored track data reached ~780MB it was exactly the point, where adding or removing one track makes the difference between crashing or not.


![Crash-Memory](https://github.com/osmandapp/OsmAnd/assets/95540936/455fd65d-e21f-4b10-8f96-509ff3760482)

**Comment by Rowin63** [comment] 2023-08-05 15:42
Unfortunately that´s only a part of the story.
To be continued...

**Comment by Rowin63** [comment] 2023-08-05 16:56
I reduced the stored tracks to a minimum: 7 Folders / 192 Tracks / 168,51MB.
Can´t be displayed on the map, Osmand crashes OOM.

Please define a performance limit of Osmand (XX tracks, XX MB track-data, whatelse). 

I don´t know, if favorites, maps and/or contour lines are also a part of this problem.
Sent a zip file with those ~190 tracks to your crash-mail, referring to this issue. 

Now you can try it.
Thanks.

**Comment by Rowin63** [comment] 2023-08-05 17:48
> I don´t know, if favorites, maps and/or contour lines are also a part of this problem.
> 
No, they are not. 
Same behavior happens on a fresh install (free 4.5.9) without any favorites and no contour lines. Only the few Balkan maps, needed to cover the tracks.

**Comment by Rowin63** [comment] 2023-08-06 09:46
In fact, it is so simple to reproduce.

Just select as many large tracks, that the app requires more than 512MB memory (it´s easy using the TET tracks for this, some of them are quite large). If you don´t want to go through them, checking one by one, just select all to be displayed and have fun.

This way I can force any osmand release on any of my devices to crash, as often as I like to.
Please don´t tell, you can´t reproduce it ;-)

I know, it is far off practice, having all 35 TET tracks on display. It´s just for demonstration (for a critical memory use anyway you don´t need all of them).

**Comment by vshcherb** [comment] 2023-08-07 17:06
Files arrived

**Comment by vshcherb** [comment] 2023-08-07 17:20
After import analyze and view in folder - so I can see all the length  of all tracks in the folder (means track analyzed) - 170 MB is used. In total distance is 26 000 km, 
![telegram-cloud-photo-size-4-5947113869447117910-y](https://github.com/osmandapp/OsmAnd/assets/1042025/6e959d44-52bf-4a4a-bf3c-e533609bdf43)

**Comment by vshcherb** [comment] 2023-08-07 17:20
Enabling all TET tracks to get visible on the map leads to crash 470 MB is used

**Comment by vshcherb** [comment] 2023-08-07 17:24
The problem is only to display > 100 000 points, I think we have a current limit to 100 000. We will try to reduce memory footprint though in order to display 1 000 000 point, you need to convert tracks to OBF files.

**Comment by Rowin63** [comment] 2023-08-08 08:16
I never had a look at the track´s number of points. It just was "big tracks" to me. 
So I´ll try to reduce this number in the tracks I´m going to need next.

Thanks!

**Comment by sonora** [comment] 2023-08-11 10:50
Here's my stats of the OsmAnd tracks folder for comparison - no such crash ever observed (Samsung XCover 4s, stock Android 11, using mostly map rendering engine v1):
![Screenshot_20230811-124652_My Files](https://github.com/osmandapp/OsmAnd/assets/845735/a52121b3-be15-43c7-b284-54abe184ccbd)

**Comment by Rowin63** [comment] 2023-08-11 10:58
I´m far below this, now...
The only diifference, I´m using rendering engine V2. 
I´ll give V1 a try.

(and just because I noticed it, but not knowing anything about: the logcat contains so many "E" and "W")

**Comment by Rowin63** [comment] 2023-08-13 09:17
I just want to mention: 
After this extensively reducing tracks data to a minimum, the problem is much better now, but still existing. 
Also there seems no noticeable difference V1/V2. Happens on both.

**Comment by Chumva** [comment] 2023-08-22 08:52
@sonora In MyPlaces>Tracks heaviest thing at the start is [loading tracks folder](https://github.com/osmandapp/OsmAnd/blob/814e0495610ca9c76e70e7aeb227a8c076ed81e5/OsmAnd/src/net/osmand/plus/configmap/tracks/TrackFolderLoaderTask.java#L45), but it`s hard to say why your setup became slower after fixes with additional tracks analysis

I will investigate it this week

**Comment by sonora** [comment] 2023-08-22 10:45
Subsequent visits to the screen are faster than (more like 6 sec). But still it seems somehow flawed to always have to wati that long just to see a basic file/folder listing...

**Comment by sonora** [comment] 2023-08-24 11:16
@Rowin63 Is your original issue actually fixed?

While I never had that very issue you reported  I have with new builds now problems opening the My tracks screen: Long waits, and sometimes even that screen freezes for a minute or so with Android reporting that OsmAnd is unresponsive...

**Comment by Rowin63** [comment] 2023-08-24 11:49
No it's not.
If I bring back my (previous large) tracks into Osmand, the +4.5.10 as well as the 4.6.0#663 do crash. Was this meant to be fixed by now?

**Comment by Rowin63** [comment] 2023-08-24 11:57
I don't even need to display any tracks, just going to "configure map / tracks / all" and scrolling around still kills both releases. So it's ike before.

**Comment by Rowin63** [comment] 2023-08-24 14:29
No solution for my problem, no...

**Comment by Rowin63** [comment] 2023-08-24 14:44
I also use Locus Map with a premium account. If I wouldn't know Osmand, I probably would be happy with it. In the last months, because of this issue, I often switched over to it.
But always came back. I'm used to Osmand and I really like it. It could be the perfect app for me, without this track-crashing issue.
And even though it drives me crazy sometimes, I still like it a lot 😉👍
I'm hoping for a solution...

**Comment by Chumva** [comment] 2023-08-24 14:52
It looks like these fixes with removing unnecessary track analysis were not enough to fix OOM on your phone...

**Comment by sonora** [comment] 2023-08-24 17:14
@Chumva Vitaliy, why do we do "track analysis" at this point?

The focus of this screen should simply be to list folders and/or track files? We could offload any statistics or analysis to a "Details" context menu entry you can tap when needed,  like any file manager does?

**Comment by Chumva** [comment] 2023-08-24 17:20
We show analysis info on item descriptions, also data from it is used in sorting (distance, duration, start time, nearest)
But it should be processed and then stored in the database until there are new changes in gpx

**Comment by sonora** [comment] 2023-08-24 17:56
Ok, that caching in the database seems to not work then, because after every fresh app start I have a long delay when first entering the screen (13 sec, with new builds even often 30sec), and upon re-entering the screen still 6sec every time. Plus aditiinal delays if I then tap "Visible on map"  to get to that (unfortunately separate) screen.

**Comment by sonora** [comment] 2023-08-24 21:22
Yes, that's why I suggested https://github.com/osmandapp/OsmAnd/issues/17538, i.e. make the "Visible" screen simply a special case of the My Places > Tracks > "Search" hits screen. It would not only save code, could also harmonize the UI between the two screens.To be considered together with https://github.com/osmandapp/OsmAnd/issues/17717#issuecomment-1686648083.

**Comment by vshcherb** [comment] 2023-08-25 11:08
This issue was reproduced with specific tracks under specific conditions and it needs to be tested with these conditions.

Regarding track analysis it should happen once and it should happen first time values are used.

**Comment by vshcherb** [comment] 2023-08-25 11:16
Reopening cause crash occurs in latest build
This what will be tested
- [ ] Enabling all TET tracks to get visible on the map leads to crash 470 MB is used - calculate how much MB is used per 100K points
- [ ] Time is not correctly calculated as   this time per track ```<time>2017-06-09T21:00:03Z</time>``` not for first point / end point
- [ ] java.util.Map.get(java.lang.Object)' on a null object reference
	at net.osmand.gpx.GPXTrackAnalysis.getAttributesData(GPXTrackAnalysis.java:131)
	at net.osmand.gpx.GPXTrackAnalysis.getSpeedData(GPXTrackAnalysis.java:126)
	at net.osmand.router.RouteColorize.<init>(RouteColorize.java:125)
	at net.osmand.plus.track.CachedTrack.createGpxColorization(CachedTrack.java:137)
	at net.osmand.plus.track.CachedTrack.getTrackSegments(CachedTrack.java:88)
	at net.osmand.plus.views.layers.GPXLayer.getCachedSegments(GPXLayer.java:1209)

**Closed** 2023-09-01 13:11 UTC
Labels: and-bugs

**Comment by Chumva** [comment] 2023-09-01 14:45
@Rowin63 can you check new nightly build?

**Comment by Rowin63** [comment] 2023-09-01 23:04
> @Rowin63 can you check new nightly build?

I really would like to, but unfortunately I can't check it now, I'm on tour and the phone with the nightly builds is at home...

**Comment by sonora** [comment] 2023-09-02 07:51
Can this possibly have an impact on Search? I find the following:
- Fresh App start
- Go to e.g. Search > Categories > Accommodations. The first page of search hits will fill almost instantaneously.

- Now go back, then go to the My Places > Tracks screen.
- Go back to the map screen, now repeat the above search.

I receive an empty results screen with a running spinner, for at least minutes, perhaps endlessly.

Restarting the app resolves the issue.

I am not entirely sure I had not seen this on previous builds also, but recent builds seems to have aggravated this and made it very reproducible.

**Comment by Rowin63** [comment] 2023-09-02 10:45
This is exactly the problem I described in the "slow search issue", but I didn't see the connection between them.

**Comment by Rowin63** [comment] 2023-09-22 09:06
> @Rowin63 can you check new nightly build?

Hi!
Sorry for my delayed answer, I was on a great tour ;-)
Yes, it works, displaying all my balkan-area-tracks (my planning, TET, some others) does not crash anymore!
Thanks for investigating and finding a solution!!!
