### ISSUE TITLE
Live updates: Roads produce duplicates 

### ISSUE THREAD

**Issue by Jerome-Herbinet** [osmandapp/OsmAnd#18153] opened 2023-09-14 08:04 UTC
## Description
I'm an OSM contributor, mainly with ID (browser).
I recently installed and tested OSMand and noticed that my recent changes were overlapping previous remaining state of the map. If you check OSM on https://www.openstreetmap.org, you'll see that the map is clean, with my last changes. Problem occurs with and without map auto update (OsmAnd Live). I've also tried to delete the maps and download it again, or even tu flush the app's cache. The issue remains.

# Example n°1 (Location : 45.60125/6.25476) : 

## On OSMand : 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/33763786/fe5f9444-6b12-4c71-af69-c28226645a61"  width="300" height="auto"/> </td>
  </tr>
</table>

## On ID : 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/33763786/3d12f46b-7ad7-47ae-9a6c-8cb9dd408a08"  width="300" height="auto"/> </td>
  </tr>
</table>

# Example n°2  (Location : 45.65303/6.35691)  : 

## On OSMand : 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/33763786/67794f73-d8a1-4623-a9c8-955fd6f029b4"  width="300" height="auto"/> </td>
  </tr>
</table>

## On ID : 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/33763786/c82ec86c-9ccf-48ee-838d-a0d4639164b8"  width="300" height="auto"/> </td>
  </tr>
</table>

# Example n°3 (Location : 45.63541/6.31085) : 

## On OSMand : 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/33763786/c0b3d572-aa15-4ea9-8c44-844cd7a3b6e3"  width="300" height="auto"/> </td>
  </tr>
</table>

## On ID : 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/33763786/fd882e9a-f50a-4189-a925-57b6b9b1320d"  width="300" height="auto"/> </td>
  </tr>
</table>

**Environment**
OsmAnd Version: 4.5.10
Android/iOS version: Android 13
Device model: Xiaomi 11T

**Comment by scaidermern** [comment] 2023-09-14 08:17
Duplicate of #14714

**Comment by 32Vache** [comment] 2023-09-23 18:24
I have similar issues, seems like deleted ways are not properly deleted in the live data.
Examples:
![Screenshot_2023-09-23-20-13-31-904_net osmand plus-edit](https://github.com/osmandapp/OsmAnd/assets/42336759/267b808d-10fa-44d6-9646-e851f92a94ad)
![Screenshot_168](https://github.com/osmandapp/OsmAnd/assets/42336759/37421a97-79e6-4336-9b41-bfd1309f1d52)
^ at https://www.openstreetmap.org/#map=18/50.42761/2.82703

![Screenshot_2023-09-23-20-14-08-978_net osmand plus-edit](https://github.com/osmandapp/OsmAnd/assets/42336759/f1ae680e-93e7-4a00-befe-f67b5646ec48)
![Screenshot_169](https://github.com/osmandapp/OsmAnd/assets/42336759/8005c35b-61d7-46a5-9027-1b9b71013cfb)
^ at https://www.openstreetmap.org/#map=18/50.42491/2.91835

**Comment by scaidermern** [comment] 2023-09-30 19:20
Same problem also still exists for POIs in OsmAnd 4.6.2.

**Comment by ivanPyrohivskyi** [comment] 2023-10-20 10:44
For begin I open map on certain place without live-updates, after to download live-updates and can see the duplication of the data. If relaunch application then bug does not happen again.
Seems like some rendering cache of data.
For begin I open map on certain place without live-updates, after to download live-updates and can see the duplication of the data. If relaunch application then bug does not happen again.
Seems like some rendering cache of data.

**Closed** 2023-11-13 15:26 UTC
