### ISSUE TITLE
Incorrect pronunciation of prompts in Bulgarian TTS

### ISSUE THREAD

**Issue by zipav** [osmandapp/OsmAnd#19924] opened 2024-05-22 08:37 UTC
### Description

Our user complains that in Bulgarian TTS The pronoun ‘turn’ is ‘zav'ii’, not ‘z'avii’, the accent is placed on the second vocalic, not the first.
When it says ‘keep going through some street’, Bulgarian uses ‘prodaljete po some street’, not ‘prodaljete varhu some street’.

### Steps to reproduce

Try to use the Bulgarian TTS while navigating. 

### Actual result

Incorrect pronunciation of the prompts.

### Expected result

The prompts are pronounced correctly so it is possible to recognise them.

### Your Environment (required)

```
OsmAnd 4.7.15 4715
Android 13
Xiaomi Redmi Note 10 Pro

```

**Comment by Koceto1973** [comment] 2024-05-22 11:50
Guys, I did the complaint.

Sure there are other items oddly pronounced.
If you provide the complete set,
I would return back for you proper audio files with male/ female voices in prefferable format.

Best Regards,
K.

**Comment by Koceto1973** [comment] 2024-05-22 12:39
Don't know how to manipulate TTS settings, but Google Maps through browser does it pretty well. Not sure how much open source is your app/ tts engines used, but there are also basic grammar mistakes over the audio.

**Comment by sonora** [comment] 2024-05-22 17:14
This is the file to look at: https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/bg/bg_tts.js.

Please study it and see how much sense you can make of it. Essentially there is a section on vocabulary, and a section governing sentence formation ("grammar").

The trick is often to compare to other, grammatically "similar" languages, in this fashion I had once created base versions of a lot of these files without actually speaking the language.

To start talking about improvement points, in OsmAnd please activate the "Development" plugin. In its settings there is a point "Test voice prompts" with numbered buttons. If you can indicate how the numbered sentences _are_ vs. how they _should be_, that would be a great start for us to work on this.

**Comment by Koceto1973** [comment] 2024-05-22 18:31
Ok, I will give it a try.

1,1 ok
1.2 says "edno kilometar", should be "edin kilometar"
; says "edin chas edna minuta", should be "edin chas i edna minuta"
1.3 says "kil'ometra", should be "kilo'metra"
 ; says "dve chasove dve minuti", should be "dva chasa i dve minuti"
1.4 says "ki'lometra", should be "kilo'metra" ;
says "tri chasove tri minuti", should be "tri chasa i tri minuti"
1.5 says "ki'lometra", should be "kilo'metra" ;
says "edin chas dvaiset minuti", should be "edin chas i dvaiset minuti"
2.1 says "pre'izchislen marshrut" should be "preizchi'slen marshrut";
 says "ki'lometra", should be "kilo'metra";
 says "pet chasove deset minuti", should be "pet chasa i deset minuti"
2.2 says "pre'izchislen marshrut" should be "preizchi'slen marshrut";
 says "ki'lometra", should be "kilo'metra";
 says "sedem chasove dvaiset i pet minuti", should be "sedem chasa i dvaiset i pet minuti"
2.3 says "pre'izchislen marshrut" should be "preizchi'slen marshrut";
 says "ki'lometra", should be "kilo'metra";
 says "petnaiset chasove triiset minuti", should be "petnaiset chasa i triiset minuti"
2.4 says "pre'izchislen marshrut" should be "preizchi'slen marshrut";
 says "ki'lometra", should be "kilo'metra";
 says "dvaiset i pet chasove chetiriiset i pet minuti", should be "dvaiset i pet chasa i chetiriiset i pet minuti"

to be continued...

**Comment by Koceto1973** [comment] 2024-05-22 18:44
Ok, I will give it a try.

1,1 ok
1.2 says "edno kilometar", should be "edin kilometar"
; says "edin chas edna minuta", should be "edin chas i edna minuta"
1.3 says "kil'ometra", should be "kilo'metra"
 ; says "dve chasove dve minuti", should be "dva chasa i dve minuti"
1.4 says "ki'lometra", should be "kilo'metra" ;
says "tri chasove tri minuti", should be "tri chasa i tri minuti"
1.5 says "ki'lometra", should be "kilo'metra" ;
says "edin chas dvaiset minuti", should be "edin chas i dvaiset minuti"
2.1 says "pre'izchislen marshrut" should be "preizchi'slen marshrut";
 says "ki'lometra", should be "kilo'metra";
 says "pet chasove deset minuti", should be "pet chasa i deset minuti"
2.2 says "pre'izchislen marshrut" should be "preizchi'slen marshrut";
 says "ki'lometra", should be "kilo'metra";
 says "sedem chasove dvaiset i pet minuti", should be "sedem chasa i dvaiset i pet minuti"
2.3 says "pre'izchislen marshrut" should be "preizchi'slen marshrut";
 says "ki'lometra", should be "kilo'metra";
 says "petnaiset chasove triiset minuti", should be "petnaiset chasa i triiset minuti"
2.4 says "pre'izchislen marshrut" should be "preizchi'slen marshrut";
 says "ki'lometra", should be "kilo'metra";
 says "dvaiset i pet chasove chetiriiset i pet minuti", should be "dvaiset i pet chasa i chetiriiset i pet minuti"

to be continued...

**Comment by sonora** [comment] 2024-05-22 18:56
I suggest the following:
- Your phone is set to use the Bulgarian language  right?
- In Android's TTS settings, please make sure you have downloaded both the latest version of the (google?) TTS version plus the latest version of its Bulgarian voice data.
- Pleae select Bulgarian as the default language, and tap the setting's Play button and make sure the voice sounds ok and without accent.

Now let's turn to the `bg_tts.js` file.
- Look at the vocabulary section first: Are the words which you feel sound bad correctly spelled?

- If not, please store a copy of the file locally, rename it to `bg2_tts.js`, and edit it to correct the spelling.
- Then place the file on your phone under `<osmand-data-folder>/voice/bg2-tts` (create a bg2-tts folder there)
- Test the pronunciation using OsmAnd's Test voice prompt Dev plugin menu.

After that is ok, we can try to move on to word order and grammar...

**Comment by Koceto1973** [comment] 2024-05-22 19:23
3.1 says "dve ki'lometra", should be "dva kilo'metra";
says " 'zaviite", should be "za'viite"
3.2 says "vav cheti'ristotin I petdeset metra", should be "sled 'chetiri'stotin i petdeset metra" ;
 says " 'zaviite", should be "za'viite";
 sais "varhu name_shtrasse", should be "po 'ulica_name";
 says "draj nadiasno", should be " 'drajte vdi'asno"
3,3 says " 'zavii naliavo", should be "za'viite naliavo";
 says "vav sto metra 'zaviite", should be "sled sto metra za'viite"
3.4 says "ki'lometra 'zavii", should be "kilo'metra za'viite";
 says "varhu SR-80 .... Rome", should be "po SR-80, po'soka Rome"

to be continued....

**Comment by Koceto1973** [comment] 2024-05-23 06:45
My phone is set to Bulgarian.
In TTS settings page, I have two engines - Google and eBook Prestigio. I can toggle the active one, but have no options to force update them, or any Bulgarian voice data. The phone has the latest update.  Voice test is available and it sounds well.

Had also friend to do similar samples test on his phone, he also confirmed same issues for pronunciation and grammar.

Will try amending the js file.

**Comment by Koceto1973** [comment] 2024-05-23 07:36
Now I browse your dictionary items definitions. Some are simple edits, but some are questionable how to edit, because your ENG keys are short and brief. Best option for me is to have complete context phrase as a hint, so I can judge the key intention context and provide proper BG translation variant.

**Comment by Koceto1973** [comment] 2024-05-23 08:19
Guess I have no access to OsmAnd folders, can't find them to place the amended config file and do the testing.

**Comment by sonora** [comment] 2024-05-23 19:01
Perhaps you have access connecting the phone to a PC via USB cable, or in OsmAnd's Data storage folder option use the media folder https://github.com/osmandapp/OsmAnd/issues/19512#issuecomment-2045660259

**Comment by Koceto1973** [comment] 2024-05-23 19:32
Can't find any OsmAnd folders on my phone, too loaded to risk rooting it. PC and cable are at hand.

Found one Motorola moto e7 power for testing. Set dev mode, usb debugging and oem unlocking. Installled latest motorola drivers to pc, phone and folders are accessible. Installed last Android Studio for Windows, downloaded and unzipped latest Google binary android sdk kit in separate folder. Phone enters fastboot mode by adb command, or by buttons via Android Recovery, but is not seen after adb devices, and fastboot command can't get serial to ask motorola for code and unlock the bootloader.

**Comment by Koceto1973** [comment] 2024-05-23 19:55
Thanks, now testing is possible on my phone.
Have some progress with the amends, will continue.

**Comment by sonora** [comment] 2024-05-23 21:31
Ok, sure.

You well overdid it! All you need is copy the file to the right folder. That will work without special drivers, without Android Studio or SDK  without debugging mode,etc. 😉

**Comment by Koceto1973** [comment] 2024-05-24 08:29
[bg_tts.zip](https://github.com/osmandapp/OsmAnd/files/15430289/bg_tts.zip)

Here is what I did.
All gramar issues found are cleared.
All pronunciation issues were addressed by word fragmentation, so current Google tts engine is forced to speak them out almost clearly ( far better than what it was ).
Some context issues were also addressed to make advices more fluent/ intuitive.

You will see some function amends done, to achive the above, and code style preserved as possible. Anyway, file.ogg amends may be needed.
Miles/foots/yards logic is preserved, only km-m is amended as typical for BG users.

**Comment by sonora** [comment] 2024-05-24 13:53
Yes, works, from what I can tell ...  :wink:

Merged here https://github.com/osmandapp/OsmAnd-resources/pull/1076, thank you!

I will close the issue, but if you have updates, feel free to post I will continue to monitor!

**Closed by sonora** 2024-05-24 13:53 UTC
Labels: Observed

**Comment by Koceto1973** [comment] 2024-05-29 06:37
Now I continued using the app voice navigation.

There are other phrase combos not seen in the above file. Is there another file with more Bulgarian preset words/phrases?

**Comment by sonora** [comment] 2024-05-29 20:05
No, this is the one. Can you give examples of phrases, then I can probably point out how they are created.

**Comment by Koceto1973** [comment] 2024-05-31 07:51
Maybe I have to gather more ststistic for one file edit. So far it was mostly numbers oddly pronounced. Probably the file edit would be more case-like for different numbers.

By the way, how can I add more variants in dev pluging test options set? Some corner cases are missing.

**Comment by sonora** [comment] 2024-05-31 08:13
The app has built in static test cases only. For all more specific cases, in particular situational cases involving testing grammar , numbers, names and certain turns, I advise to have a collection of approriate routes (I simply use favorites for the start/end points), and run them with the Simulation feature turned on in OsmAnd's config route settings. You can play a prompt at any time by tapping the 'next turn' widget.

If you have doubts about how your configured TTS engine interprets and pronounces a certain text or numbers, you can use an app like "TTS Test App" to find out independently from OsmAnd.
