### ISSUE TITLE
Import Favorites doesn't work 

### ISSUE THREAD

**Issue by MarioSwitch** [osmandapp/OsmAnd#15932] opened 2022-12-10 10:57 UTC
### Description
When I try to import only my favorites (exported from 4.2.7), app is continuously saying "Importing..."
When I try to import my favorites and other things, import takes few seconds and says all were imported but not favorites.

### How to reproduce?
Export favorites on the 4.2.7 and import it in 4.3.2

### Your Environment
OsmAnd Version: 4.3.2 from Google Play Store beta program
Android/iOS version: 13
Device model: Pixel 7

https://user-images.githubusercontent.com/58565980/206851815-7c045a42-042d-4612-b158-3eec9da6f304.mp4

**Comment by vshcherb** [comment] 2022-12-11 08:38
You can try to export favorites on Favorites tab - Share as a workaround

**Comment by sonora** [comment] 2022-12-11 09:10
I have tried and it works for me. Does the name of any of your favorite groups start with a dash "-", by any chance? (Your video does not seem to work for me...)

**Comment by sonora** [comment] 2022-12-11 13:25
@vshcherb The issues seems present exactly when in a v4.2.7 export the _items.json_ file contained in the _.osf_ backup file contains **several (comma-separated) values** like
```
{
  "version": 1,
  "items": [
    {
      "type": "GLOBAL",
      "file": "general_settings.json"
    },

(...)

    {
      "type": "FAVOURITES",
      "file": "favourites.gpx"
    }
  ]
}

```

To test, shorten such a file to contain just the favorite-related block, then the fav import works again, (both via _Import from file_ and via the _Import profile_ menus):

```
{
  "version": 1,
  "items": [
    {
      "type": "FAVOURITES",
      "file": "favourites.gpx"
    }
  ]
}
```

So it looks like v4.3.2 has some issue correctly interpreting these longer _.json_ files....

**Comment by MarioSwitch** [comment] 2022-12-11 18:45
Like @sonora said, exporting only favorites in v4.2.7 and then importing the file on v4.3.2 perfectly works!

**Comment by sonora** [comment] 2022-12-11 22:22
Wrong logic is in this line, I believe:
https://github.com/osmandapp/OsmAnd/blob/fbf6f426489ce899cbb05766fd9efbf394ffe1d8/OsmAnd/src/net/osmand/plus/settings/backend/backup/SettingsHelper.java#L539

**Comment by sonora** [comment] 2022-12-12 16:54
It's tested. Am I supposed to merge it, or someone else?

**Comment by vshcherb** [comment] 2022-12-12 18:19
I don't think it's correct @sonora cause it needs to be reviewed by someone else - peer review. 
For example an obvious problem that issue was not merged in 4.3 branch and not clear whether it's safe to merge to 4.3 or not.

**Comment by sonora** [comment] 2022-12-12 18:22
Yes, ok, that' why I asked. So what's the proper state to leave these at? Just open the PR, or move them to any swim lane?

**Comment by vshcherb** [comment] 2022-12-12 18:25
If you open PR the task will be assigned, if it's not an urgent could take a full week (sprint) to review base on other people tasks

**Comment by sonora** [comment] 2022-12-12 18:37
Ok! This one's release-relevant, that's why I offered it in a hurry. Safe to merge to r4.3, from my testing.

**Comment by Zirochkabila** [comment] 2022-12-12 19:50
OsmAnd~ 4.4.0#14016mqta, released: 2022-12-12
Reproduced

1. When importing **only Favourites** via Profile and Backup - the result is the same, Favourites are imported and displayed on the map
[Archive.zip](https://github.com/osmandapp/OsmAnd/files/10211383/Archive.zip)

https://user-images.githubusercontent.com/104760013/207136683-357f258c-679b-4d30-ac9a-eb6f99956a08.mp4

https://user-images.githubusercontent.com/104760013/207136665-b77ff74c-4d24-4988-a8cd-83af07aeaff9.mp4

2. When importing a file, **where in addition to Favourites there are also Settings** via Profile and Backup - the result is the same, Favourites starts loading, but does not finish
[Archive 2.zip](https://github.com/osmandapp/OsmAnd/files/10211431/Archive.2.zip)

https://user-images.githubusercontent.com/104760013/207137950-410789e1-d421-41f8-b968-82b60d588b4d.mp4

https://user-images.githubusercontent.com/104760013/207137940-ad11ea47-6538-4691-a68e-e092681bf546.mp4

3. When importing **Favourites and Settings** via Profile and Backup - the result is the same, only Settings are imported
The files are the same as in p.2

 https://user-images.githubusercontent.com/104760013/207139028-fe3343ef-017b-4739-a5d7-c9da80da88e9.mp4


https://user-images.githubusercontent.com/104760013/207139057-d75e2e88-2bda-4767-8ff6-1a537569af6b.mp4

**Comment by sonora** [comment] 2022-12-12 22:02
@Zirochkabila Anatolii, can you please re-run this? The build 14016mqta you have used for testing was built sevaral hours before the fix was merged (https://github.com/osmandapp/OsmAnd/pull/15939).

**Comment by Zirochkabila** [comment] 2022-12-13 09:10
OsmAnd~ 4.4.0#14020mqta, released: 2022-12-13
@sonora Fixed

**Closed** 2022-12-13 09:10 UTC
Labels: Observed
