### ISSUE TITLE
AndroidAuto: Map not on correct Position

### ISSUE THREAD

**Issue by it-open** [osmandapp/OsmAnd#18390] opened 2023-10-20 10:07 UTC
### Description

Wow. a bit hard to explain:
When you show the Map in Android Auto and you have the rotation to "rotate in moving direction" the Map does not move correctly. 
When you move the Car the Map does update. But when you drive a curve the Map rotates but does not move the Car. (Every other Information ist updated). When you come back to a straight movement then the Map moves to the correct position.
So the Map moves OR rotates but when it rotates it does not move. 
When you have two roundabouts after another you see the (car icon) on the start of the first, till you come to a straight road again. 

Never seen this behaviour in the Android Display only on Android Auto display in my car.

### Steps to reproduce

- Pixel 7a
- Android Auto (Skoda if it matters)
- Map rotation in movement direction
- Drive a roundabout or a long curve

### Actual result

The icon (car in my case) stopps at the beginning of the curve but rotates correctly
The Map moves again when you come to a straight road

### Expected result

The (car icon) should follow the curve: Map moves and rotates at the same time.

### Your Environment (required)

OSM AND+ 4.6.3  2013-10-12
Pixel 7a
Android 14
Skoda Fabia with Android Auto.

**Comment by DmitryAlexei** [comment] 2023-10-20 15:58
It seems, that this issue is duplicate of https://github.com/osmandapp/OsmAnd/issues/18194

**Comment by vshcherb** [comment] 2023-10-20 16:06
There is a certain delay and we need to fix it first, so the issue is merged to https://github.com/osmandapp/OsmAnd/issues/18194

**Closed by vshcherb** 2023-10-20 16:06 UTC
