### ISSUE TITLE
Feature request - manual height limitation

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#6935] opened 2019-05-13 10:16 UTC
Might it be possible that the height limitation can be set with a manual limit without using the steps. Our car has a height of 3.2m and in my region there are many Bridges with height of 3.4m.

**Comment by Discostu36** [comment] 2020-08-11 05:27
Duplicate of  #6182

**Closed** 2020-08-11 07:30 UTC
Labels: Nice to Have
