### ISSUE TITLE
OsmAnd+ and SystemUI freezes right after opening and moving

### ISSUE THREAD

**Issue by magical-obama** [osmandapp/OsmAnd#17818] opened 2023-08-05 10:39 UTC
## Description
The app OsmAnd+ freezes when I open it and move around the view or zoom. As long as I don't do anything or only open the side drawer, everything is ok. However, when I move the view or zoom, first OsmAnd+ freezes and shortly afterwards the whole phone is unresponsive. After about a minute, the screen goes black, the app crashes and the home screen is rebuilt.

### How to reproduce
Open OsmAnd+, move the view or zoom.

### Actual result
The app + system freezes and crashes

### Expected result
The app works...

**Environment**
OsmAnd Version: 4.5.9
Android/iOS version: Android 13
Device model: OnePlus 10T

**Comment by grzebo** [comment] 2023-08-06 08:38
I have the exactly same issue with version 4.5.9.

Did not occur with previous version. Using different map styles or turning off hill shading and other features doesn't make a difference, Osmand still freezes after a couple of map moves or zooms.

Samsung Galaxy S10E
Android 12

**Comment by magical-obama** [comment] 2023-08-06 13:31
How did you find out your OsmAnd version? Because I couldn’t even look it up in the app, I had to take the one from the Google Play Store…

Hope they find a solution soon.

**Comment by MarieLataretu** [comment] 2023-08-06 21:40
Hi there,

I have the same issue:
Pixel 4a
Android 13
OsmAnd 4.5.9

**Comment by sonora** [comment] 2023-08-07 05:38
@magical-obama The version of any app installed can always be found also in the _Android Settings > Apps > (tap on any app)_.

**Comment by DmitryAlexei** [comment] 2023-08-07 07:46
Could you provide crash logs (https://osmand.net/docs/user/troubleshooting/crash-logs#send-logs-from-osmand-app-android) with short video of your issues?

App version can be found in Help > About > long tap on that field copies the data

**Comment by grzebo** [comment] 2023-08-07 11:44
Here are the logs:
[logcat.log](https://github.com/osmandapp/OsmAnd/files/12279149/logcat.log)
[exception.log](https://github.com/osmandapp/OsmAnd/files/12279150/exception.log)

And here's a short recording of how the bug looks like.

https://github.com/osmandapp/OsmAnd/assets/47195640/5a5757f9-fde5-403d-a509-f88ef53f1677


I've restarted the phone just before recording.

**Comment by vshcherb** [comment] 2023-08-07 18:07
Likely fixed with https://github.com/osmandapp/OsmAnd-core/pull/614 - waiting for 4.5.10 release

**Closed by vshcherb** 2023-08-07 18:07 UTC

**Comment by DmitryAlexei** [comment] 2023-08-31 11:07
The issue is probably already been solved. There have been no complaints about such freezes recently.
