### ISSUE TITLE
Poor contrast between motorways and trunk roads in 2.6

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#3678] opened 2017-04-18 20:30 UTC
I just updated to OsmAnd 2.6. With the map style changes, there's now poor contrast between motorways and trunk roads.

Motorways are no longer displayed in blue. I'm so used to seeing them in blue that it's very confusing seeing them in orange. Almost all UK maps (and many others) will show motorways in blue.

At low zoom levels, it's impossible to tell the difference between motorways and trunk roads:

![osmand_26_unclear_motorways](https://cloud.githubusercontent.com/assets/638458/25151100/2ec77d08-247c-11e7-8d73-1396ad2ce9df.png)

The road running east-west near the waypoints is a motorway (M4) but cannot be distinguished from the trunk road going north to Oxford.

In older versions of OsmAnd it was much clearer:

![osmand_26_unclear_motorways_24_comparison](https://cloud.githubusercontent.com/assets/638458/25151336/201c5098-247d-11e7-84ac-b5dbadb16bb8.png)

The motorways are immediately obvious, even at this zoom level.

At higher zoom levels, motorways are _slightly_ distinguishable from trunk roads (see M4 and A315), but mostly due to the shields:

![osmand_26_unclear_motorways_zoomed_in](https://cloud.githubusercontent.com/assets/638458/25151423/7189c01e-247d-11e7-9015-fdef3a5a22b3.png)

Please restore the blue colour for motorways, or let me know what I can put in a custom rendering file to get motorways in blue.

**Comment by sonora** [comment] 2017-04-19 06:32
As a side note: Our "OsmAnd" default map style has to make a number of compromises. In general our Map style "Touring view" offers more contrast and better visibility of all features particularly relevant for traveling.

**Comment by njohnston** [comment] 2017-04-19 08:59
@sonora: I understand that compromises have to be made. After all, OsmAnd shows highly detailed maps, so it's challenging to make everything clear.

The contrast between motorways and trunk roads in touring view is better, but the motorways are rendered even more unusually: yellow lines with red borders.

I think the default style with motorways in blue was almost perfect. The default style is also much more appealing than the touring one, to me at least.

I think it's very important to have clear contrast between motorways and trunk roads in the default style. As things currently stand, there is no way of distinguishing motorways and trunk roads at low zoom levels, and little contrast at higher zoom levels. Can the blue can be restored?

**Comment by sonora** [comment] 2017-04-19 16:21
Understood. **Touring view**'s motorway style is customary in some countries it seems, hence we will leave it there as is, mostly for a special community of travelers, professional drivers, etc. Even if that map style is admittedly much more "intense" with travel features and contrast than most people expect from a "default" map.

Regarding the "blue" turned to "red" in our **default "OsmAnd"** style: I am not advocating that change, neither did I perform it. It looks like http://openstreetmap.org have recently changed their default Mapnik style (perhaps in an attempt to resolve "blue" conflicts with water), and in OsmAnd we may have made an attempt to assimilate that convention again. But I will have to leave it here for others to comment.

**Comment by njohnston** [comment] 2017-04-19 16:42
I was disappointed when Mapnik changed motorway rendering. I understand their reasoning but don't agree with it. I actually used OsmAnd more afterwards because of its better rendering.

In this old OsmAnd screenshot, ECP (the motorway along the coast) is still clear in blue, even though it's very close to the sea:

![singapore_clear_motorways](https://cloud.githubusercontent.com/assets/638458/25191415/6f080f62-2527-11e7-8e35-fc746eecf6ec.png)

The sea uses a lighter shade of blue, and the motorways have subtle grey borders too.

Even if blue isn't restored, the contrast needs to be improved in a different way.

Looking forward to others providing their input.

**Comment by Barrocas** [comment] 2017-04-19 21:20
I totaly agree, and also disliked when OSM changed colours.

Osmand took a while, but eventually I knew it would unfortunately go the
same way...

So I changed the roads map style to the American Atlas rendering, because
It's closer to what we had before.

Default map rendering now has Red tones everywere, and I can't clearly
visually see the different roads as before. Not using it!

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment] 2017-04-20 08:43
"Mapnik" old style is still available in the app.

**Comment by Barrocas** [comment] 2017-04-20 10:47
Mapnik is not the issue.

We are refering to the road style colouring, as in the Touring view, or
American Atlas, versus the Default red colouring.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment] 2017-04-20 14:23
I just notice we have: Map style=OsmAnd", the select Road style="American road atlas". Guess we have had for a long time, but I had never used it. Is that what you are requesting?

**Comment by stevegdavis** [comment] 2017-04-20 15:44
I too wanted different road colours from the default, I just changed the rending xml file to suit my needs for example the minor/unclassified road where white which is difficult to see in high sunlight when cycling and I have also changed the motorways to blue and other roads colours too
![screenshot_2017-04-20-16-38-48 1](https://cloud.githubusercontent.com/assets/15140454/25239571/43b564c4-25e8-11e7-8d73-5567c50d1075.png)
it is easy to do (much easier than maps.me!)

**Comment by njohnston** [comment] 2017-04-20 16:12
@sonora: I just tried the "American Road Atlas" road style and motorways are blue, but because of the borders they look more like rivers to me.

@vshcherb: thanks for your response. The Mapnik rendering style shows motorways much more clearly than the new default style. However, I think it's really important that motorways are displayed clearly in the default style--otherwise new users might stop using the app. That would be a real shame, particularly as with the GPX improvements and elevation support in 2.6, OsmAnd is approaching perfection :) It shouldn't be necessary to switch to a different rendering style just to get good contrast between motorways and other roads. I realise not every country uses blue for motorways but along with green it's one of the colours specified in the [Vienna Convention on Road Signs and Signals](https://en.wikipedia.org/wiki/Vienna_Convention_on_Road_Signs_and_Signals#Road_signs). Even if blue isn't used, better contrast is essential.

@stevegdavis: could you please show what changes you've made to the rendering file?

**Comment by stevegdavis** [comment] 2017-04-20 18:21
See my default.render.xml file,do a file compare with your render file on your phone to see the changes i have made. I have had to zip it in order to attach it here. Look in the file for motorway color. Note you may have to re-boot osmand after you have made changes to the render file.
[default.render.zip](https://github.com/osmandapp/Osmand/files/945063/default.render.zip)

**Comment by sonora** [comment] 2017-04-21 06:35
@xmd5a2, @vshcherb  Leonid, Victor, I just notice that motorways and trunk roads have **exactly** the same color in our default render with default settings, ever since https://github.com/osmandapp/OsmAnd-resources/commit/1b1ddfc23ef045367a28aa309be16fcf1617567a? (Line 371) Surely that has got to be  a bug??

**Comment by njohnston** [comment] 2017-04-21 09:33
@sonora: I noticed this last night too. I changed motorways to blue in my custom rendering file (thanks @stevegdavis) and then noticed that trunk roads near me were appearing in blue too. At first I thought I'd had made a mistake, but when I switched back to the default rendering and checked, I realised that motorways and trunk roads are the same colour, like you point out. Definitely a bug.

**Comment by stevegdavis** [comment] 2017-04-21 10:00
@njohnston you could change the **renderingAttribute name="trunkRoadColor"** section where it says:-		**case attrColorValue="$motorwayRoadColor"**
I change it to:-
**case attrColorValue="#ff8095"**

to differentiate the 2 road types only for the default of course.
I use [https://www.w3schools.com/colors/colors_picker.asp](url) hope that helps.

**Comment by sonora** [comment] 2017-04-21 12:37
Yes, you should exactly revert the changes in made lines 371 and 372 of the commit I linked to above. After discovering this commit this morning, I now believe Leonid may have made these 2 changes in error. 

Sorry for not catching this earlier, I feel like I do **A LOT** of testing whatever gets updated in our code by anybody, but it seems that it is never enough.  :)

**Comment by vshcherb** [comment] 2017-04-21 18:43
The issue is acknowledged and will be fixed upcoming 2.6.2 release. The color will keep the contrast though it will be in the default color scheme.

**Comment by vshcherb** [comment] 2017-05-19 07:58
2.6.2 was released

**Closed by vshcherb** 2017-05-19 07:58 UTC
