### ISSUE TITLE
"Avoid Motorways" not working

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6737] opened 2019-03-24 14:11 UTC
Start 53.1711155, 8.154345
End 53.245549, 10.397354
Tested in the latest Night build
![image](https://user-images.githubusercontent.com/40493090/54880635-60819a00-4e4f-11e9-9812-945620e33bf0.png)

**Comment by aceman444** [comment] 2019-03-24 23:37
The option does not completely avoid motorway if your start or end point is on a motorway. Is that your case? It is not visible on the screenshot.

**Comment by vshcherb** [comment] 2019-03-25 22:49
Needs to be checked

**Comment by alyonapinchuk** [comment] 2019-03-27 13:28
OsmAnd only avoids motorways if fuel efficient option is off 
When both avoid motorways and fuel efficient are selected then it still uses motorways 

Start: Location: geo:51.311974,-0.3337468?z=12
https://osmand.net/go?lat=51.311974&lon=-0.3337468&z=12
End: Location: geo:50.837597,0.47505692?z=16
https://osmand.net/go?lat=50.837597&lon=0.47505692&z=16

**Comment by xmd5a2** [comment] 2019-04-01 15:32
It works as expected with intermediate points, but this is not a perfect solution, of course.
![Screenshot from 2019-04-01 18-30-01](https://user-images.githubusercontent.com/5829014/55339901-42014b80-54ac-11e9-9180-6aa447fcf2bf.png)
Duplicate of https://github.com/osmandapp/Osmand/issues/6278

**Comment by winduptoy** [comment] 2019-04-06 01:56
Can confirm:

1. By default, motorways are not being ignored when I ask for them to be avoided
2. Forcing "Fuel efficient" option off will correct this

Maybe fuel efficient option should be turned off automatically when specifying "avoid motorways" to make this more intuitive?

**Comment by xmd5a2** [comment] 2019-04-12 12:14
Fixed. Please test without "fuel efficient" option.

**Closed** 2019-04-12 12:13 UTC

**Comment by aceman444** [comment] 2019-04-13 09:48
Another random change of constants? You increased those values to higher ones and now you are going back? https://github.com/osmandapp/OsmAnd-resources/commit/f1304ac9ab4c07debad3ec58531cb6f5b6cf5218#diff-dbc3b73746ed4cac0d1b5912f839ca0e

Surely you now regress the issue for which you increased them.

**Comment by vshcherb** [comment] 2019-04-17 10:18
@aceman444 You are referring to wrong commit - https://github.com/osmandapp/OsmAnd-resources/commit/14fa568ebf185f7433ee92fc36e2393b3fa735a8. We follow the rule having less penalty as possible so if we find a solution how to decrease penalty from 1000 -> 100 we will obviously do it! Increasing penalty by a margin is very easy operation though increasing it by a factor leads to enormous time calculation. 
This solution was reviewed & tested and we are expecting new test cases to calibrate it.  Though we can see that initial approach was wrong and required fix anyway.

**Comment by aceman444** [comment] 2019-04-19 01:24
No, you are referring to the wrong commit, the one done in this issue, which is already linked above. I wanted to point out a older commit, where the same values were changed in the opposite direction (much increased).

**Comment by vshcherb** [comment] 2019-04-29 11:09
(much increased) was a mistake and we had to revert after review
