### ISSUE TITLE
The ford icon is drawn twice

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18353] opened 2023-10-15 23:15 UTC
### Description

The ford icon is drawn twice.
![IMG_20231016_021230](https://github.com/osmandapp/OsmAnd/assets/12549744/dab04d9d-095d-4fdd-8531-d6a717bc4cd8)

### Steps to reproduce

1. find a ford
2. look at it

### Actual result

The ford icon is drawn twice.

### Expected result

Don't draw two icons.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.6.0#871m, Дата выпуска: 2023-10-13
Android/iOS version:13
Device model:poco f3
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment] 2023-10-16 06:00
OsmAnd~ 4.6.0#871m, released: 2023-10-13 Reproduced 

**Steps to reproduce:**
- go to node https://www.openstreetmap.org/node/9082308666 Coordinates 47.6075017 13.8005450
- zoom to 16th zoom level and see, that ford is displayed singular on the map
- zoom closer, to the 17th zoom level and see, that now there are two fords on the map, one under another
- duplicate of the ford is present on the map on zoom levels 17-22 and disappears on zoom level 16



<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/2bd95d5c-b57f-4959-ade4-2fc6508c6d30"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f14d877e-8ed0-40eb-ad30-fc1736f644ed"  width="300" height="auto"/> </td>
  </tr>
</table>

**Closed** 2023-10-26 06:33 UTC

**Comment by zipav** [comment] 2023-11-13 17:44
OsmAnd Nightly 4.6.0#1020m, released: 2023-11-13

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/b851033b-1d08-4a2b-b39f-5eca6b094966"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/2cac1f82-42a3-4993-ba02-d48fc827c39e"  width="300" height="auto"/> </td>
  </tr>
</table>
