### ISSUE TITLE
Some entrances are shown outside buildigns on high zoom levels

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#10411] opened 2020-12-15 23:40 UTC
![image](https://user-images.githubusercontent.com/14617699/102285561-98940f00-3f47-11eb-81c7-eed411cf3aff.png)![image](https://user-images.githubusercontent.com/14617699/102285574-9cc02c80-3f47-11eb-8e0b-bd1052dead7c.png)

Exact example: https://www.openstreetmap.org/node/1438799463
Looks good:
![image](https://user-images.githubusercontent.com/14617699/102285738-edd02080-3f47-11eb-9242-c541ad7c43f1.png)
Looks bad:
![image](https://user-images.githubusercontent.com/14617699/102285707-df820480-3f47-11eb-8198-0a40a34e3622.png)

OsmAnd Version: 3.8.5

**Comment by scaidermern** [comment] 2020-12-16 08:24
Duplicate of #8788 and #6130. Should be fixed in the next OsmAnd version as far as I can see.

**Closed** 2020-12-16 11:06 UTC
