### ISSUE TITLE
Roundabout symbol shows weird icon for 3'd exit

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#2263] opened 2016-02-22 15:57 UTC
Hi

I have noticed that icon for roundabout is showing funny direction for this particular roundabout 3'd exit.

Regards, 
Areg 

![screenshot_2016-02-22-15-04-04](https://cloud.githubusercontent.com/assets/2562730/13223602/dcfc1f38-d97c-11e5-9441-71181aebfe9f.png)

**Comment by vshcherb** [comment] 2016-02-22 17:08
I think it is duplicate of something nice to have, the main reason that left or right driving side is detected by General Settings - Driving Region.

**Comment by vrtareg** [comment] 2016-02-22 18:31
Hi

No this is not a duplicate. 
Driving region is correctly set to UK but this specific roundabout shows wrong.

I have driven these couple of days and other roundabouts shows normally for 3'd and 4th exits. 

If this is duplicate could you please let me know the other issue id? 

Regards, 
Areg

**Comment by Goodingn** [comment] 2016-02-24 11:56
The angle to the turn depicted in the guidance is bigger than shown on the map.  As a consequence, it is easy for the guidance depiction to go further round than 360deg and end up with the weird graphic you've shown.

Or so it looks to me:

https://github.com/osmandapp/Osmand/issues/1512

**Comment by vrtareg** [comment] 2016-02-24 15:43
Hi

Any options to fix this?

Regards,
Areg

**Comment by vrtareg** [comment] 2016-02-24 19:27
Hi

I am curious how it can calculate angle more than 360 degree. 

Can someone please point me to the code where this is done?

Interesting to have a look. 

Regards, 
Areg

**Comment by vshcherb** [comment] 2016-06-15 20:44
Location http://www.openstreetmap.org/way/99184182#map=16/52.0619/-0.0108

**Comment by vshcherb** [comment] 2016-06-17 07:06
Fixed

**Closed by vshcherb** 2016-06-17 07:06 UTC

**Comment by vrtareg** [comment] 2016-07-01 20:28
Something new for 4th exit

Regards,
Areg
