### ISSUE TITLE
Not displaying protected areas

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2171] opened 2016-01-18 12:21 UTC
I was noticing that osmand isn't displaying protected areas.

For example, here http://www.openstreetmap.org/#map=17/-21.80041/-48.19097 we have this in OSM:
![OSM](http://i.imgur.com/Cbgyscn.png)

and in osmand:
![osmand](http://i.imgur.com/BrfOk1o.png)

Likewise in http://www.openstreetmap.org/#map=14/-24.0120/-46.3962
![OSM](http://i.imgur.com/ZPC3t20.png)

and in osmand:
![osmand](http://i.imgur.com/f4zwp5r.png)

The example objects are http://www.openstreetmap.org/relation/5216225 and http://www.openstreetmap.org/relation/5419145

**Comment by hakuchi** [comment] 2016-01-18 18:12
something is wrong whit the multipolygon.
you have to report this on OSM.

**Comment by naoliv** [comment] 2016-01-18 19:58
They are not wrong.

**Comment by xmd5a2** [comment] 2016-01-19 13:13
Very strange screenshot. This multipolygon as tagged as leisure=nature_reserve too and it renders correctly in my test
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-01-19%2016%3A12%3A48.png

**Comment by naoliv** [comment] 2016-01-19 14:07
I am using a nightly version, if this makes any difference.
Installed version is `OsmAndF~ 2.3.0#11483D`

I am viewing the map in "Browsing mode", using the "OsmAnd" style and without any other option:

![Options](http://i.imgur.com/DlF6bUu.png)

**Comment by xmd5a2** [comment] 2016-01-19 14:37
You may be using roads-only map.
Fixed by https://github.com/osmandapp/OsmAnd-resources/commit/9aaf82d2090d4e5fc8ad31de8da44466ceaec8d8

**Closed by xmd5a2** 2016-01-19 14:37 UTC

**Comment by naoliv** [comment] 2016-01-19 14:39
It's the full map that I am using. I will test it later.
Thanks!

**Comment by vshcherb** [comment] 2016-01-19 21:22
This might be related to corrupted pbf file, which we sometimes get especially with multipolygon. In that case we need to test exactly on the the target file. And if it is wrong pbf that we used, we need to addresss it as well.

**Comment by naoliv** [comment] 2016-01-22 16:19
The problem here seems to be related with objects with multiple properties.
For example, this relation:

http://www.openstreetmap.org/relation/3507935
![](http://i.imgur.com/aWYoE26.png)

It's both a `amenity=community_centre` and `landuse=grass`

But osmand isn't displaying the grass:

![](http://i.imgur.com/BIzNOLj.png)

The same is happening with later examples.
They are `leisure=nature_reserve` + `natural=wood` + `boundary=protected_area`

Note that they are all technically valid: `natural`, `leisure`, `landuse`, `landcover`, `boundary`, etc are all representing a different aspect of the same object.

They are also properly rendered in, at least, the standard OSM layer, cycle map, transport map, MapQuest open and humanitarian.

**Comment by hakuchi** [comment] 2016-01-22 18:23
"community_centre" is a tag for town hall and that's why Osmand symbol is a building.
https://en.wikipedia.org/wiki/Community_centre
https://pt.wikipedia.org/wiki/C%C3%A2mara_municipal_%28Brasil%29


for this area the better tagging is:
1. ["amenity=festival grounds"] (http://www.openstreetmap.org/way/122395230) with "name=Recinto de Festa do Carmo"
2. "landuse=village_green" with "name=Recinto de Festa do Carmo"

I would prefer example 1 but if you don't will use proposed features you can use example 2

**Comment by naoliv** [comment] 2016-01-22 18:27
`amenity=festival grounds` is proposed.
`amenity=community_centre` is right if you look at the wiki:

_As the place for all-community celebrations at various occasions and traditions._
_As the place for public meetings of the citizens on various issues._

The issue here is not how the objects are tagged, but how osmand manages objects with multiple features.

**Comment by hakuchi** [comment] 2016-01-23 01:26
I know that the issue is how Osmand displaying this, but you sold also use the correct tagging for places in OSM.

1.
"shopping center" = building
"dive center" = building
"sports center" = building
"garden center" = building - sometime with outdoor part from shop
"social center" = building or only room
"adult gaming center" = building/hall
"community center" = is for me a building or minimum one building inside the area.
and on this field I can't see any building.
so why you don't use village green for this place?

which "[community_centre] (http://taginfo.openstreetmap.org/keys/community_centre#values)" tag will you use to describe this center?

which "[community_centre:for] (http://taginfo.openstreetmap.org/keys/community_centre:for#values)" tag will you use?

2.
Why are you using all this multipolygons?
This is absolutely confusing for beginners and therefore they will no make more editing on OSM.
OSM need beginners, but multipolygons don't help, to keep them. 

3.
Finally a correct mapped community_centre(not a field for partys) with the same tagging as that reported from you:
http://www.openstreetmap.org/way/386678849
http://www.openstreetmap.org/way/174995885
this 2 examples are displayed correct in Osmand.

**Comment by naoliv** [comment] 2016-01-23 01:34
Please, here is not the place to discuss tagging.

**Comment by xmd5a2** [comment] 2016-01-23 09:05
Case with amenity=* + landuse=grass fixed https://github.com/osmandapp/OsmAnd-resources/commit/44bd28d25e85cafcf8195337338faccdf6c8ddbf

**Comment by naoliv** [comment] 2016-01-26 13:39
@xmd5a2 thanks!
But for the first examples (like http://www.openstreetmap.org/relation/5216225) it's still not displaying it:

![](http://i.imgur.com/74FVC2A.png)

**Comment by xmd5a2** [comment] 2016-01-26 16:23
Yes, it's still a problem with multiline relations.

**Comment by xmd5a2** [comment] 2016-01-26 17:54
Problem is fixed.
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-01-26%2020%3A54%3A04.png
Fix will come with new maps generation.
