### ISSUE TITLE
Elevation widget stuck at 50 

### ISSUE THREAD

**Issue by Fedsmachine** [osmandapp/OsmAnd#19218] opened 2024-02-29 21:16 UTC
Detail location info is correct but elevation widget on screenstuckat 50 m.

**Comment by Fedsmachine** [comment] 2024-02-29 21:17
Detail location info is correct but elevation widget on screenstuckat 50 m.

**Comment by DmitryAlexei** [comment] 2024-02-29 22:15
@Fedsmachine have You downloaded World altitude correction map? 
Please indicate, what is your OsmAnd version
Please update your app to the latest version or try nightly and see if the elevation widget is working.

**Comment by Fedsmachine** [comment] 2024-02-29 22:33
Updated altitude correction already.
Version: OsmAnd+ 4.7.1, released: 2024-02-06
 Still no luck. Info correct on "detail" but widget stuck on 50 m.

**Comment by sonora** [comment] 2024-03-01 09:09
Duplicate of #18998.

**Closed** 2024-03-06 17:42 UTC

**Comment by Fedsmachine** [comment] 2024-03-06 20:58
Problem not resolved.

**Comment by Fedsmachine** [comment] 2024-03-08 13:38
Very dissappointed problem NOT solved.

**Comment by sonora** [comment] 2024-03-08 20:12
So are you sure you updated to a version which already contains the above referenced fix?

**Comment by Sebf69** [comment] 2024-03-11 05:55
Same issue, its Always AT 50m elevation

**Comment by yuriiurshuliak** [comment] 2024-03-11 14:08
Please try to update the app or use our [nightly](https://osmand.net/docs/versions/nightly_versions#nightly-builds) version where this should be fixed.
