### ISSUE TITLE
[3.3.4] Placing a note with quick-actions jumps to a different location

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6679] opened 2019-03-14 11:30 UTC
OsmAnd beta 3.3.4, Android 8.1 (LIneage 15.1)

When placing a POI/Note with quickactions, the note is placed in the (absolute) middle of the screen, not where the oragne marker is placed.

See video:

![ezgif-4-f3fa6fabc0e0](https://user-images.githubusercontent.com/1466478/54353627-cc485380-4654-11e9-920f-1e7b6a022ad9.gif)

**Comment by scaidermern** [comment] 2019-03-14 11:48
Duplicate of #6508 and #6624.

**Closed** 2019-03-14 13:10 UTC
