### ISSUE TITLE
Flooded: Quebec region

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6203] opened 2018-10-21 16:11 UTC
![image](https://user-images.githubusercontent.com/40493090/47269323-c1d1d400-d564-11e8-9440-a04873f3c700.png)
![image](https://user-images.githubusercontent.com/40493090/47269327-c72f1e80-d564-11e8-8f32-a2a37f6df898.png)

**Comment by pangoSE** [comment] 2018-11-04 13:34
#6239 is a duplicate of this.

**Comment by tuxayo** [comment] 2019-01-21 17:08
Since few months, it happens to me from time to time in Marseille(fr)
I can't reproduce reliably for now.

![screenshot_20190121-180141](https://user-images.githubusercontent.com/2678215/51488800-d5c8e400-1da6-11e9-9311-d39d4e21bad0.png)

**Comment by tuxayo** [comment] 2019-01-21 17:50
I'm not sure if related[1] but the opposite happens in Tuvalu:

[1] because around the 180th meridian, a lot of issues happen

## The whole ocean is land
![screenshot_20190121-183214](https://user-images.githubusercontent.com/2678215/51490271-0f035300-1dab-11e9-821b-30152294fdfc.png)

## The water inside the "island" is rendered as land
![screenshot_20190121-183219](https://user-images.githubusercontent.com/2678215/51490683-4f170580-1dac-11e9-9415-9147b05a451e.png)

## Good rendering
![screenshot_20190121-183235](https://user-images.githubusercontent.com/2678215/51490687-50e0c900-1dac-11e9-9d8a-c2b0a21f7717.png)


## Expected rendering
https://www.openstreetmap.org/relation/2177266#map=12/-8.5442/179.1166

**Comment by xmd5a2** [comment] 2019-02-27 14:03
Quebec an Marseille were fixed by https://github.com/osmandapp/OsmAnd-core/commit/b5caf37d261063b92f76a039b72857fb9080aa99
Tuvalu is a separate issue

**Closed by xmd5a2** 2019-02-27 14:03 UTC
