### ISSUE TITLE
Unrendered background should depend on day/night mode (white flicker at night)

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#4879] opened 2017-12-24 13:58 UTC
When the map moves and portions have to render, the unrendered background should have a colour depending on the day or night mode. 

In particular in night mode, the background is currently white, which causes the screen to show flashing white rectangles for the split-second of rendering. This is annoying and causes distraction. Thus in night mode the background should be black. 

![screenshot_20171114-161903_render-flicker_left](https://user-images.githubusercontent.com/8266355/34327040-a9363b62-e8ba-11e7-90da-076f77508231.png)

**Comment by vshcherb** [comment] 2017-12-24 21:40
It might be dependent on custom rendering style. That needs to be checked cause similar issue was fixed in 2.8

**Comment by polarbearing** [comment] 2017-12-26 20:42
When exactly was it fixed? 
The screenshot was in my backlog, taken on Nov 14 with OsmAnd-master-nb-2017-11-13.apk.

**Comment by vshcherb** [comment] 2017-12-26 21:11
Just double checked on the latest build and I can't reproduce that issue

**Comment by vshcherb** [comment] 2017-12-26 21:11
Maybe somebody else can?

**Comment by polarbearing** [comment] 2017-12-28 13:46
Tested Nov-04, nov-11 and today's dec-28 nightlies, not even the version that caused the glitch can reproduce it. Keeping eyes open, but closing the issue.

**Comment by CJTmmr** [comment] 2017-12-28 19:42
I think it happens after night-colors switch to daylight-colors (or vice versa) at sunrise (sunset).
Issue still present in builds from this week.
After a fresh start all is okay, until the next sunrise/sunset...
Please reopen.

**Comment by polarbearing** [comment] 2017-12-28 23:36
Yes had the same experience today, with December-28 nightly.

How to reproduce in the lab:

- check in the OsmAnd debug settings for current sunset. Close OsmAnd. 
- set device to manual time setting, adjust time to daytime (I tried 2h before sunset)
- start OsmAnd, see the map in day mode. 
- adjust device time to a minute before sunset
- watch the widgets turn to night. A minute later, the map turns to night (why does the map not turn the same moment as the widgets?)
- see the bright margins when zooming/moving map. 

I have the device now for 65 min in this mode, still the bright margins.
However, putting it to sleep and waking up refreshes the background and it is black as it should be.

**Comment by sonora** [comment] 2017-12-29 06:48
Yes, we have had this for years, it is not anything introduced just lately.

**Comment by crimean** [comment] 2017-12-29 07:18
@sonora it was fixed, but not completely (issue with sunrise/sunset setting still present)

**Comment by sonora** [comment] 2017-12-29 07:51
Yes, changing the app mode or map resume correctly updates the defaultColor, but sunrise/sunset induced change seems to fail doing so. Will have to investigate unless you are already on the right track?

**Comment by sonora** [comment] 2017-12-29 07:59
PS Same issue in light sensor mode.

**Closed** 2017-12-29 11:41 UTC
Labels: Observed

**Comment by polarbearing** [comment] 2018-01-04 12:11
Confirmed, thanks.
