### ISSUE TITLE
[solved] oreo 8.1: crash on opening dashboard & navigation settings

### ISSUE THREAD

**Issue by nicky-one** [osmandapp/Osmand#5220] opened 2018-04-08 16:47 UTC
**EDIT / solved: enable animations in android developer options**

The same issues on 2 devices with Oreo 8.1

    phone "wileyfox swift", arm64, crDroid 4.1
    tablet "sony xperia z2", arm, ResurrectionRemix 8.1

OSM 2.9.3 & (latest) nightly 2018.4.26 simply crashes: "Osmand / nightly has stopped": 

    when tapping on settings/dashboard (dashboard never opens)
    during navigation: when trying to open the navigation settings by tapping the blue arrow-up + settings at the bottom of the screen
(but no crash when opening general app "settings / navigation settings")

There were no such issues on the same devices earlier with android 7.1.2.

**Comment by jeleba** [comment] 2018-04-19 06:54
Same problem here on samsung s8 oreo. This is the exception that I get:
Version  OsmAnd+ 2.9.3
13.04.2018 4:12:34
Apk Version : 2.9.3 293
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Animator has already started, cannot change it now!
	at android.view.RenderNodeAnimator.checkMutable(RenderNodeAnimator.java:150)
	at android.view.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:325)
	at android.view.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:323)
	at android.animation.AnimatorSet.updateAnimatorsDuration(AnimatorSet.java:774)
	at android.animation.AnimatorSet.getTotalDuration(AnimatorSet.java:1742)
	at android.animation.AnimatorSet.forceToEnd(AnimatorSet.java:446)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:995)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:655)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Version  OsmAnd+ 2.9.3
15.04.2018 9:29:26
Apk Version : 2.9.3 293
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Animator has already started, cannot change it now!
	at android.view.RenderNodeAnimator.checkMutable(RenderNodeAnimator.java:150)
	at android.view.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:325)
	at android.view.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:323)
	at android.animation.AnimatorSet.updateAnimatorsDuration(AnimatorSet.java:774)
	at android.animation.AnimatorSet.getTotalDuration(AnimatorSet.java:1742)
	at android.animation.AnimatorSet.forceToEnd(AnimatorSet.java:446)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:995)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:655)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by nicky-one** [comment] 2018-04-22 09:55
hmm... who could give us some hint about a solution for those issues?
Otherwise osmand seems hardly usable on the newest oreo 8.

**Comment by EvgenyTerebenin** [comment] 2018-04-26 12:16
I have such problem too. My device Nokia 6 2017 (TA-1021) android 8.1.

**Comment by schrod** [comment] 2018-04-26 13:05
As another data point. I have a Pixel XL running android 8.1. I'm running a version from the current master branch with some custom modifications (not related to dashboard or navigation) and I do not see this issue.

**Comment by Hocceruser** [comment] 2018-05-04 13:40
Could this be a duplicate of https://github.com/osmandapp/Osmand/issues/5006?

**Comment by jeleba** [comment] 2018-05-05 08:27
If I enable animations in android developer options everything is working fine again. So indeed seems to be the same bug at least in my case.

**Comment by nicky-one** [comment] 2018-05-05 08:39
@jeleba: thanks a lot for your hint! 
Yes, animations seems in some way related, which i had disabled as well, and more exactly the _**"animator duration scale"**.
When set to 0.01x everything seems to work again.

**Closed** 2018-05-06 21:10 UTC
