### ISSUE TITLE
Vehicle does not turn right

### ISSUE THREAD

**Issue by tronta** [osmandapp/OsmAnd#10981] opened 2021-02-23 05:48 UTC
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

Car, no restrictions

### Start and end points

This routing does not work:
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=47.72867%2C11.32319%3B47.72858%2C11.32557#map=18/47.72786/11.32403

The vehicle will not do a right turn, but take a long detour:
![routing](https://user-images.githubusercontent.com/5135577/108806487-1ad12d00-75a2-11eb-80c3-258a86e0ca8a.png)

### Actual and expected routes

Expected result, is that the car turns right.
![grafik](https://user-images.githubusercontent.com/5135577/108806517-2b81a300-75a2-11eb-80fc-cd33e0a44ebf.png)

### Is this a regression?
I don't think it ever worked.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
Android 3.9.6
</code></pre>

**Device and Android/iOS version:**
Android 8.1, BBB100-2

**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by naoliv** [comment] 2021-02-23 11:58
Probably caused by this `turn_restriction`?
https://www.openstreetmap.org/relation/2165874 (which seems to make no sense and could probably be deleted)

**Comment by scaidermern** [comment] 2021-02-23 12:14
Could be. Nevertheless this is a valid (but useless) restriction. So it shouldn't lead to problems.

**Comment by tronta** [comment] 2021-02-27 05:18
Would it make sense to remove this constraint to (probably)  get a correct behavior for now?
Or do you need this to be able to reproduce it?

**Comment by vshcherb** [comment] 2021-03-01 17:50
Nope, we will need to investigate first. Probably it's OsmAnd issue

**Comment by Dima-1** [comment] 2021-03-10 11:43
Issue was fixed in 3.9.7

**Closed** 2021-03-10 11:45 UTC
