### ISSUE TITLE
¨No auto zoom¨ issues

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6342] opened 2018-12-06 14:36 UTC
When ¨No auto zoom¨ is chosen, zoom changes when approaching a turn if the map is not in the following mode.

**Comment by vshcherb** [comment] 2018-12-11 22:59
Not clear what does it mean "not in the following mode", I guess route is calculated in that case?

**Comment by vshcherb** [comment] 2019-04-16 14:34
Couldn't reproduce if it's Android

**Comment by sonora** [comment] 2019-05-10 22:25
I have to re-open this because of the commit above: While I am not certain the commit really fixed anything, it causes the following issue:

Now when in map viewing mode (i.e. no navigation) and zoomed far out, tapping the blue back-2-location button does not zoom in to the default zoom any more, due to changing `backToLocationImpl(15);` to `backToLocationImpl(15, false);`.

**Comment by sonora** [comment] 2019-05-11 07:12
@crimean I think you may simply have mixed up true and false in your commit, meaning it should be
'backToLocationImpl(15, true);.' and 
'mapActivity.getMapViewTrackingUtilities().backToLocationImpl(17, false);' ?

**Comment by crimean** [comment] 2019-05-11 07:23
@sonora sorry for the issue. Fixed by https://github.com/osmandapp/Osmand/commit/1c362b7112f5177df32a54403fcfccead8f65780

**Closed by crimean** 2019-05-11 07:23 UTC

**Comment by sonora** [comment] 2019-05-11 10:44
Not a problem, godd we caught it. ;)
