### ISSUE TITLE
Offline Routing: Car Mode - routing through bollard?

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#3095] opened 2016-09-19 19:13 UTC
Both in latest nightlies as in PlayStore-version 2.4.6
Using The Netherlands-map (with Live Updates enabled)
OsmAnd Offline Routing, Car-mode.

OsmAnd routes through a node tagged with "barrier=bollard"
(By default access=no, foot=yes, and bicycle=yes is implied, according to the wiki.)
Also in routing.xml there is the line:
`<select value="-1" t="barrier" v="bollard"/>`

Two examples:
[from Bodegraven, Noordzijde 17 to Bodegraven Dirk Bavolaan 11](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.08345%2C4.75532%3B52.08489%2C4.75305#map=17/52.08430/4.75327)
OSRM gives the right result,

But OsmAnd routes via Noordhof, which has  [this node](http://www.openstreetmap.org/node/45172023#map=18/52.08407/4.75365&layers=D), tagged with:
`barrier=bollar`
`bicycle=yes`
`foot=yes`
![2016-09-19 18 44 37](https://cloud.githubusercontent.com/assets/15076257/18644911/73aa08a4-7eab-11e6-96e9-7c26fd1ef70f.png)

This is the [situation](https://www.google.nl/maps/@52.084094,4.7535531,3a,51.9y,27.4h,84.86t/data=!3m7!1e1!3m5!1shgcV6jM1-PCc9TbiOHM1SQ!2e0!6s%2F%2Fgeo2.ggpht.com%2Fcbk%3Fpanoid%3DhgcV6jM1-PCc9TbiOHM1SQ%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D46.376003%26pitch%3D0!7i13312!8i6656):
![image](https://cloud.githubusercontent.com/assets/15076257/18644986/b67daec4-7eab-11e6-9eb8-aa870daa3990.png)

Another example:
Routing [from Gouda, Achterwillenseweg 6 to Gouda Goudvlinderstraat 10](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.01845%2C4.72309%3B52.01677%2C4.73369#map=16/52.0209/4.7264)
OSRM gives the right route.

OsmAnd uses [this road with barrier=bollard](http://www.openstreetmap.org/node/516285621#map=19/52.01810/4.72952&layers=D)
![2016-09-13 06 51 58](https://cloud.githubusercontent.com/assets/15076257/18645264/cb348760-7eac-11e6-8cd9-294030915e02.png)

It used to be all right, I don't know when this was changed.

Thanks for investigating

Kees-Jan

**Comment by d1g** [comment] 2016-09-24 06:22
@CJTmmr, you should add tags about motor_vehicle=*, current tagging of http://www.openstreetmap.org/node/516285621/history:
> barrier 	bollard
bicycle 	yes
foot 	yes
horse 	yes

is not enough to decide motor_vehicle permissions. If bollards were placed to prevent ANY motorized vehicle (http://wiki.openstreetmap.org/wiki/Key:motor_vehicle) - motor_vehicle=no.

Use motorcar=* for motorcars only (more details at http://wiki.openstreetmap.org/wiki/Key:access)

**Comment by d1g** [comment] 2016-09-24 06:31
@CJTmmr, alternately, there better tagging scheme about physical barriers: 
http://wiki.openstreetmap.org/wiki/Proposed_features/Obstacle#Subkeys -but it is not widely used yet to get support in most routing programmes and default profiles.

**Comment by aceman444** [comment] 2016-09-27 20:12
Why? If the wiki says default is access only for foot+bicycle, OsmAnd can (and does) follow that. No need to add redundant tags. I think the tagging is fine here and OsmAnd should not (and didn't in the past) route through the bollard.

@CJTmmr, why are the bollards not shown on the screenshot? Do you have a correct uptodate map? Or is that some special rendering style?  I can see bollards in OsmAnd normally.

**Comment by d1g** [comment] 2016-09-27 20:37
> Why? If the wiki says default is **access only for foot+bicycle**,

@aceman444, can you link to this page where is it stated? Because it doesn't, it never stated this in last 10 years and it shouldn't

MOREOVER, it states **Implies access=no** very clearly 

it only states that foot bicycle are assumed to be passable. Motorized vehicles and mopeds permissions are unknown.

> OsmAnd should not (and didn't in the past) route through the bollard.

For cars.

**Comment by CJTmmr** [comment] 2016-09-28 08:56
@d1g: [Wiki: Tag:barrier=bollard](http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbollard)
its says: "By default **access=no, foot=yes, and bicycle=yes** is implied"

@aceman444:
the bollard is obscured by streetname and routing-line:
This is a close-up of the first example Noordhof(in nightmode)
![noordhof bollard](https://cloud.githubusercontent.com/assets/15076257/18906656/b26344d4-8568-11e6-885b-d2f6463f282f.png)


And yet another example this morning, routing: [in Woerden](http://map.project-osrm.org/?z=17&center=52.084837%2C4.886781&loc=52.085433%2C4.886883&loc=52.083350%2C4.880118&hl=en&alt=0)
OsmAnd, Car profile, economic route: through [this bollard](http://www.openstreetmap.org/node/796476500#map=19/52.08349/4.88568&layers=D)

![woerden route trough bollard](https://cloud.githubusercontent.com/assets/15076257/18906917/d0a687ca-8569-11e6-87b3-534bed1c9fb4.png)

and close-up:
![woerden bollard](https://cloud.githubusercontent.com/assets/15076257/18906935/e1da590e-8569-11e6-8bfe-71ce2a5f36b3.png)

**Comment by vshcherb** [comment] 2016-09-28 17:11
The only issue is present and I think it is duplicate of https://github.com/osmandapp/Osmand/issues/2499

**Closed** 2016-09-28 17:11 UTC

**Comment by CJTmmr** [comment] 2016-09-28 19:39
In the examples above the bollars were not changed for months or even years.
Still a Live Updates issue?

The barrier from #2499 is not used for routing in September maps Tne Netherlands
![2016-09-28 19 39 09](https://cloud.githubusercontent.com/assets/15076257/18929231/f4345e1a-85c3-11e6-8caa-5867558f94e0.png)

**Comment by d1g** [comment] 2016-09-29 14:04
@aceman444, @CJTmmr  yes both of you are correct, I was wrong in https://github.com/osmandapp/Osmand/issues/3095#issuecomment-249990692

Not "for cars" (as I said), but "for everyone except foot/bicycle" (as wiki "implied" says)

**Comment by CJTmmr** [comment] 2017-02-28 10:55
@vshcherb : please check routing.xml
In block `<point attribute="obstacle">`
there is a section:
`<if param="short_way">
	<select value="0"/>
</if>`

It was introduced [13th Aug 2016](https://github.com/osmandapp/OsmAnd-resources/commit/165e2b61eec1da626bb3185dba98c881aea73bf8) trying to fix #1778

I think maybe this causes the problems routing through a barrier.
The line ` <select value="-1" t="barrier"/>` is not read on short/economic route

If you delete lines `<if param="short_way">
	<select value="0"/>
</if>`
no longer routing through bollards in short way and fast way!

Please also check [this discussion](https://groups.google.com/forum/#!topic/osmand/CpNZKPXdR7c) on the forum: entries as from 19th Feb.

Thanks to Aceman444, P Wat and Poutnik

**Comment by aceman444** [comment] 2017-02-28 20:48
Yes, I think too that this is the problem.

**Comment by aceman444** [comment] 2017-02-28 20:55
I have proposed the change in https://github.com/osmandapp/OsmAnd-resources/pull/428 .

**Comment by dreua** [comment] 2026-08-06 19:21
I just found out that it still routes through bollards if you set "Allow private access" on the routing settings. Hadn't expected that as a bollard on a bridge in the middle of my route is usually not opened for me passing through. Is that intentional or another bug worth fixing?

Example: https://www.openstreetmap.org/node/206101461/history (Just added motorcar=no explicitly, not sure if that'll change it.)
