### ISSUE TITLE
Feature suggestion: Show altitude graph for tracks without altitude information

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/OsmAnd#4770] opened 2017-11-16 12:22 UTC
A few versions ago OsmAnd received a feature to show altitude graph. OsmAnd can show graph for tracks with altitude information and for calculated route (in this case the altitude is also calculated, if the user downloaded file with altitude info for this region). Yet, in case when a track doesn't have altitude information, OsmAnd doesn't show altitude graph, even if it can calculate it exactly the same way as for navigation. I suggest to add calculation of altitude graph for track that doesn't have altitude info.

![10 screenshot_2017-11-16-12-34-13](https://user-images.githubusercontent.com/22505250/32890960-91169666-cad9-11e7-9b9e-4244d9fae34e.png)
![11 screenshot_2017-11-16-12-34-19](https://user-images.githubusercontent.com/22505250/32890963-94fbbfae-cad9-11e7-9dad-077c2dd862ab.png)
![12 screenshot_2017-11-16-12-17-36](https://user-images.githubusercontent.com/22505250/32890971-98fa05b6-cad9-11e7-85d0-0297e96da3a4.png)

**Comment by rindlerblabla** [comment] 2017-11-17 19:53
Isn't this a duplicate of #3908 ?

**Comment by scaidermern** [comment] 2017-11-17 21:27
Not really. It shouldn't be necessary to match the track against the road to get height information. The height information isn't part of the road data.

**Comment by SergeyP2** [comment] 2017-11-18 18:21
It can be outdoor tracks, you should not try to match them to any road, there can be none nearby on OSM. Just use the same infromation as for drawing altitute lines. I believe the algorithm that draws altitude graph for calculated route already do exactly the same, so just use the same code.

**Comment by erik55** [comment] 2018-08-14 18:07
See  #4967 where it is explained that:
The standard osmand offline maps contain elevation data only for roads, paths etc. (osm highways).

If you also download contour lines (and install the Contour lines and Hillshade plugin), then you have elevation data “in the middle of the empty forest”. :-D But that is a lot of additional data, as you can see by the download size.

That means: If you have the Contour lines and Hillshade plugin installed and you have the contour lines downloaded, then the distance and mesure could use that information, and also the gpx tracks that contain no height information could use that height data of the contour lines.

But the (usability) question is: How to indicate, that the height information is not the “true” gps recorded information, but the height data for the track is extrapolated from the contour lines data. Because: Yes, it would help, but it should be clear, that this is only the not very accurate data from the contour lines which could have an x-y-offset (and also the gpx track could have a x-y-offset) and therefore could be wrong. You know what I mean? Offset of 30 meters could mean, that the altitude graph show that you where walking up the mountain, but in reality you were going down.

Does anybody have an idea, **how to indicate, that the height data is taken from the contour lines** data and **not part of the gpx track?**

**Comment by SergeyP2** [comment] 2018-08-25 18:44
You exaggerate the problem. Actually there is no problem, because I think nobody cares is it 3910 meters above sea level or 3920 meters or even 3930 m -- that is the kind of precision of countour lines. I can say, that I had a few phones, and they all show altitude with precision of +/-30 m -- you basically stay in some spot, and as far as there are more/less satellites used the altitude drifts in this +/-30 m range -- so that is the precision of recorded GPX -- not better then what you can calculate based on countour lines. So you can show no indication where altitude info is taken from, or you can add some "GPX" / "Calculated" somewhere in the corner of the graph if you like.

**Comment by vshcherb** [comment] 2018-08-26 16:34
There is no such algorithm yet and I've never saw it so far, so I couldn't judge if it is working approach or not. Obviously it is not bad cause current SRTM data has errors for +-5 meters and contour lines extrapolation could only delete these errors. Anyway the data precision is 5m^2 per alt point so far on average

**Comment by dmpr0** [comment] 2021-11-03 09:47
Current OsmAnd version, have the option "Attach to the roads" in Plan a Route menu, using attach GPX to the nearest roads and adds all available data into the track file including altitude information.

**Comment by SergeyP2** [comment] 2021-11-03 11:47
It is NOT a solution. As I wrote

> It can be outdoor tracks, you should not try to match them to any road, there can be none nearby on OSM.

**Comment by erik55** [comment] 2021-11-03 12:03
I'd also vote for reopening, as it is still nice to have. And maybe some day a junior developer wants to earn some merit and write the code. Could be even me.

**Comment by wmbr** [comment] 2022-02-20 21:13
I searched for a way to calculate the elevation profile for 15+ minutes because I could not believe that this feature is really missing. (Note that I did buy the contour lines plugin, so all the required data is already present.)

Sorry for the harsh words but this is really a big disappointment. Almost a must-have when planning (ski) hiking routes.

**Comment by dmpr0** [comment] 2022-05-03 13:24
Current nightly builds have options to calculate altitude for tracks online or using offline "Attach to the roads" options.

**Closed by dmpr0** 2022-05-03 13:24 UTC
Labels: and-ui

**Comment by SergeyP2** [comment] 2022-05-03 14:37
Looks like a person who closed the issue, haven't spend any time to read the conversation.

> It can be outdoor tracks, you should not try to match them to any road, there can be none nearby on OSM.

**Comment by dmpr0** [comment] 2022-05-03 14:44
@SergeyP2 Look like you didn't try the new "Calculate online" option for tracks.

**Comment by vshcherb** [comment] 2022-05-03 15:55
<table style="width:100%">
  <tr>

  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/156590585-85468377-4b8d-4f74-9b69-8afea2d33f41.png"  width="300px" height="auto"/></th>
    <th valign=top><img src="https://user-images.githubusercontent.com/9365308/159737292-bb7ef035-fb28-4e09-a8cf-051fe391b3d6.png"  width="300" height="auto"/></th>

  </tr>
</table>
