### ISSUE TITLE
streets are not rendered on zl 9 to 12

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#8371] opened 2020-02-01 09:23 UTC
other zl are ok.
map is France_new-aquitaine_europe, date 2020-01-01
map positions of markers where gaps are:
46.10188° N, 0.86936° E
46.18379° N, 1.21205° E
46.19688° N, 1.27770° E

![Screenshot_20200201-102002_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/73589949-e4c79380-44dc-11ea-9bcf-4f65f49e05e2.jpg)

**Comment by vshcherb** [comment] 2020-03-31 21:43
The problem is present only in the merged map (so subprovince maps are ok)

**Comment by vshcherb** [comment] 2020-04-20 22:05
https://github.com/osmandapp/OsmAnd-core/commit/5e4cb298c5f90c2dcb560a1c205284d78f43248f

**Closed by vshcherb** 2020-04-20 22:05 UTC
