### ISSUE TITLE
Text Input Widget Doesn't Account For System Font Change

### ISSUE THREAD

**Issue by H--W** [osmandapp/Osmand#6621] opened 2019-03-06 00:32 UTC
The widgets for entering From: and To: locations do not account for changes to the system font. See attached image below. When the system text size is increased, the From: and To: text is truncated (the bottom is chopped off).

OSMAND+: 3.3.2
Android: 8.1.0
Kernel: Samsung 3.18.14
Samsung Experience: 9.5
Phone: J3 Prime

Background: With this version of Android, notifications are displayed in a font that only a teenager can read. Changing system "Screen Zoom" to small and "Font Size" to (almost) huge fixes font sizes for most situations. OSMAND+ does not appear to take these changes into account.

Best Rgds, -H-
![screenshot_20190305-203010_osmand](https://user-images.githubusercontent.com/5553887/53847070-bcaa7a00-3f85-11e9-8ae8-70ed9c29e748.jpg)

**Comment by sonora** [comment] 2019-03-06 05:59
I think this is a duplicate of #6606, and is already fixed in v3.3.3.

**Comment by H--W** [comment] 2019-03-06 19:14
I just installed the 3.3.3 update and it does appear to be fixed. Nothing in  [#6606](https://github.com/osmandapp/Osmand/issues/6606) mentioned text size else I wouldn't 'ave bothered anyone with a new issue. Assuming it really is fixed, you can mark this one closed. Best Rgds, -H-

**Comment by sonora** [comment] 2019-03-06 19:47
The one thing I am not sure about is the tine/distance line (45.7 km, 43 min in your screenshot above). On some devuces it looks like it has a second text line, but most or all of it seems hidden. I leave this open so someone can doublecheck.

**Closed** 2019-09-26 14:36 UTC
