### ISSUE TITLE
Crashes since 2017-07-06

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4135] opened 2017-07-17 22:26 UTC
Looks like all builds newer than 2017-07-05 crash on me upon trying to select "My Places", or starting a search action, and some other menu actions, see log attached: [exception.log.txt](https://github.com/osmandapp/Osmand/files/1154161/exception.log.txt) (S4 Mini, Stock Android 4.4.2.) Falling back to the 2017-07-05 build remediates the situation.

**Comment by scaidermern** [comment] 2017-07-18 07:32
Same exception as in #4070?

**Comment by sonora** [comment] 2017-07-18 17:24
Lokks like not, I still got a crash this morning with last night's nightly when tapping on Menu / My Places.

**Comment by jfburke3** [comment] 2017-07-19 16:07
This sounds like the same thing I logged in #4125 .

I can get into Plugins and Settings, but anything that involves the map file causes a crash.

**Comment by jfburke3** [comment] 2017-07-19 18:58
I cannot reproduce the problem on my S7 / Android 6.0.1.  It only happens on the S4 / Android 4.2.2.

**Comment by vshcherb** [comment] 2017-07-20 08:05
Merged in #4125

**Closed by vshcherb** 2017-07-20 08:05 UTC
