### ISSUE TITLE
Latest OsmAndMapCreator bloats files (again)

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/OsmAnd#10180] opened 2020-11-13 15:38 UTC
Hi!
Same problem as in #10055 ?
vshcherb: "I checked rendering_types and description shouldn't be indexed any more"

**Comment by vshcherb** [comment] 2020-11-13 16:35
Description is now correctly part of the POI section, so now the problem is different. In case you don't want to index description for POI you can probably disable POI indexing.

**Comment by MAlfare** [comment] 2020-11-13 17:27
How can I do this?
It is not only the increased size.
Osmand crashes when I try to open a POI.

**Comment by vshcherb** [comment] 2020-11-13 18:12
Can you please send the crash?

If you don't need POI, you can unselect it in MapCreator or run with cmd
```
./utlitities.sh generate-map ...
```

**Comment by MAlfare** [comment] 2020-11-13 19:39
But the POI are exactly what I want, the only thing that I want.

[exception.log](https://github.com/osmandapp/OsmAnd/files/5538953/exception.log)

**Comment by vshcherb** [comment] 2020-11-19 15:20
The crash is related to MGRS system, looks like it won't work unfortunately on your device. It's missing some system methods.

**Comment by MAlfare** [comment] 2020-11-19 23:14
The crashes happens on a tablet with an intel-processor and Android 4.3.
When I tap the POI, sidebar opens and when I tap the POI there, OsmAnd craches.
Now I tried two other devices:
Tablet with Android 4.4.4 does not even show the POIs on the map.
Smartphone Motorola G4+ with Android 8.1 everything seems to be O.K.

This a very unsatisfying situation.
Building my POI- obf-files from the same gpx->osm-files with older Map Creator, all three Devices work.
Doing the same with newer Map Creator, 2 of 3 devices fail.

O f course I can stay with old MC, but when some time in the future, with a change anywhere inside OsmAnd, the files produced by this old fellow, will no more accepted

**Comment by vshcherb** [comment] 2020-11-20 18:34
Exception that I see is here 
```
java.lang.NoSuchMethodError: java.lang.Character.isAlphabetic
	at com.jwetherell.openmap.common.MGRSPoint.toFlavoredString(MGRSPoint.java:677)
	at net.osmand.plus.OsmAndFormatter.getFormattedCoordinates(OsmAndFormatter.java:525)
	at net.osmand.data.PointDescription.getLocationData(PointDescription.java:174)
```

It has nothing to do with changes of include description tag or not. Exception happens MGRS-system which could be disabled and used native LatLon. It will be hard to fix MGRS-system cause it's an external library.

Do you have any other exception?

**Comment by MAlfare** [comment] 2020-11-21 12:22
Hi Victor!
No, I had and I have no Problems with any of the three devices.
The history:
No problems on all 3 until 13. November, when I created new POI-obf files with MC from 13.11.
One tablet crashes as described earlier, the second die not even show the POIs on map, smartphone worked.

Created these files with MC from 31.10. which works on all3 devices without problems. 

Now, after some updates of OsmAnd:
Tablet one now crashes even with the old obf- files
Tablet two no works with old and new obf-files.
 Smarthone works with old and new obf-files.

So it seems to be, that:
With older MC and older OsmAnd all Devices work.
With newer MC and older OsmAnd,  tablet one crashes, the second did not even show POI, smartphone works.
With newer MC and newer OsmAnd, tablet one crashes, the second works, smartphone works.

**Comment by vshcherb** [comment] 2020-11-23 16:38
This is really interesting issue cause obviously there was a change (introducing description for POI items) but now it is an intentional change cause we want to display it in Context menu. Though we can't reproduce the crash and crash itself is very weird... Probably you can share full log somehow (Development Settings -> Log) if it has a crash

**Comment by MAlfare** [comment] 2020-11-23 17:46
I did removed all my POI-files from the 'bad' tablet, after I observed, that it crashes even if I long tap anywhere in the map.
I think, side bar should open, and tell something about the region I tapped.
It crashes again, so the POI-files are unguilty, as MC is?
I have problems to log the crashes, seems this new variant makes no entries in exception.log. No entries for yesterday an today.
I sent a log per mail at the start of OsmAnd after the last crash and I attach her the comglete exception log, which is two day's old :-(
[exception.log](https://github.com/osmandapp/OsmAnd/files/5584797/exception.log)

I have now copied my POI-files to the tablet, but I cannot see any POI of it.
I'll keep on trying, to deliver information.
Any tip to get some are welcome

**Comment by vshcherb** [comment] 2020-11-26 17:54
There was a change as well how we zip long strings that might be crashful but it was fixed on this week. After the crash you can also share the log from LogCat (Development Settings -> Log, not exception.log)

**Comment by MAlfare** [comment] 2020-11-26 19:52
You think of something like this:
file:///home/alf/TEMP/LogCat.txt

**Closed** 2020-12-07 15:09 UTC
Labels: Observed

**Comment by MAlfare** [comment] 2020-12-07 21:19
Hi Victor!
It works!
On 3.9#31043m

Thank you very much!
