### ISSUE TITLE
Non-square elements

### ISSUE THREAD

**Issue by efi99** [osmandapp/OsmAnd#13925] opened 2022-03-15 11:15 UTC
### Description
The buildings are not completely square, despite being converted to a right angle in the osm editor. However, they appear correctly on the openstreetmap site.

### How to reproduce?
Zooming.

### Your Environment
OsmAnd Version: latest
Android/iOS version: 12
Device model: Samsung A52
![osm](https://user-images.githubusercontent.com/62113872/158366101-04d015ef-ec08-4b90-bd37-0cc89d609b70.jpg)

**Maps used (online or offline):**   
Offline with Live Update

**Comment by scaidermern** [comment] 2022-03-15 11:57
Duplicate of #12366.

**Closed** 2022-03-15 13:38 UTC

**Comment by vshcherb** [comment] 2022-03-22 12:13
Merged to https://github.com/osmandapp/OsmAnd-Issues/issues/1049

**Comment by vshcherb** [comment] 2022-03-22 12:17
Merged to https://github.com/osmandapp/OsmAnd/issues/9821
