### ISSUE TITLE
can not update to 3.0.2 from Playstore

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#5505] opened 2018-05-27 18:57 UTC
I have subscribed to the Beta from OsmAnd+ on the Playstore long time ago, but if I click on Update, the phone freeze and make a reboot.
After reboot, I am stil on 2.9.3.

Can there be a bug in the apk from Playstore, because latest nightly works fine for me.

I have a Moto G2(XT1068) with Android 6

**Comment by DrVanScott** [comment] 2018-05-28 10:49
Maybe same/similar problem: Whenever i try to install a version > 2.9.3 i got a "Error -504" within play store. Trying to manually install the apk also fails. If i manually install apk of version 2.9.3 it succeeds.

I have a Huawei Y6 (I)

Can i provide more information? How?

**Comment by GerasDraugas** [comment] 2018-05-28 20:06
same problem as hakuchi.

--
Motorola E 2

**Comment by vshcherb** [comment] 2018-05-29 08:15
Google Play - Error 504
Problem
App could not be downloaded due to an error.

First solution
The usual, please: go to Settings > Apps > All > Google Play Store and Clear cache and Clear data. Also Clear cache and Clear data for Google Services Framework.

**Comment by DrVanScott** [comment] 2018-05-29 09:28
Of course i already did all of those magic stuff. Also removed/reapplied google account. Should have mentioned this in my last post...

Please keep in mind, that manual installation of apk > 2.9.3 does not work. 2.93 itself does

**Comment by lfoppiano** [comment] 2018-05-29 10:30
@vshcherb I've tried several time the solution you propose and it never worked. 

I have also tried to reset the phone and reinstall the application but it looks like the last release installation doesn't work. It worked though on a more recent phone (Huawei smart P)

**Comment by GerasDraugas** [comment] 2018-05-29 14:16
I do not get any errors while updating.
Other applications from playstore updating good.

Updaiting OsmAnd+, downloading, updatingi, phone freeze and after same time reboot.

Any clear cache not help.

**Comment by vshcherb** [comment] 2018-05-29 14:17
@lfoppiano can you install latest nightly, independent application http://download.osmand.net/latest-night-build/OsmAnd-default.apk.

**Comment by vshcherb** [comment] 2018-05-29 14:19
Can you please specify following: 
- Paid or free applciation
- Phone & Android version

**Comment by GerasDraugas** [comment] 2018-05-29 14:36
My version: OsmAnd+ 2.9.3 (2018-02-08)
updaiting from playstore: 

My phone: Motorola Moto E (2en Generation) with 4G LTE

**Comment by GerasDraugas** [comment] 2018-05-29 14:53
https://youtu.be/C1Juq7RLAOs (sorry for the angle)

**Comment by hakuchi** [comment] 2018-05-29 15:58
thx to GerasDraugas for the video.
Exact the same for me if I will update OsmAnd+ from 2.9.3 to 3.0.2

**Comment by lfoppiano** [comment] 2018-05-29 20:18
I have a Motorola Moto G 4G XT1039 with Android 5.1. 
When I install the version OsmAnd-default.apk it works correctly on my phone.

**Comment by lfoppiano** [comment] 2018-05-29 20:42
@stephan75 I have successfully installed the apk mentioned by @vshcherb in https://github.com/osmandapp/Osmand/issues/5505#issuecomment-392793004
Using Google Play I get `Error Code -504`.

**Comment by lfoppiano** [comment] 2018-05-29 20:42
@stephan75 where can installt he latest nightly apk from the paid version?

**Comment by vshcherb** [comment] 2018-05-30 10:28
Can we also mention what's Google Play version is running. We see the problem happens on 0.1-2%  devices and unfortunately we didn't manage to reproduce it on our dev devices.

Our dev devices has various Android version: 4.0 - 8.0 . Google Play version between 10.1 - 10.2 ( you can check it APP INFO about Google Play)

**Comment by vshcherb** [comment] 2018-05-30 11:17
Another idea: that device is probably low on memory

**Comment by vshcherb** [comment] 2018-05-30 11:19
So far: we can't find the source of the issue and it looks like to be related with Google Play. We are planning to release 3.0.3 tomorrow and hope that new build will be indexed and will be available for download properly

**Comment by PaulStets** [comment] 2018-05-30 11:26
Please try to do this as a workaround: Download OsmAnd then let it install for a few minutes.  After a few minutes and while the app is still installing, press and hold the power button until the device shuts off.  Once it starts back up on its own, you should see a screen stating "optimizing app 1 of 1."  Let this do its thing. 
Let us know if it works.

**Comment by GerasDraugas** [comment] 2018-05-30 12:34
no any optimizing :(

**Comment by lfoppiano** [comment] 2018-05-30 12:37
@vshcherb I have tried also to factory reset the device and reinstall OsmAnd but I have got the same problem. It should have worked because it was the first application I was installing. Unfortunately there is no way to see any log from Google Play and theferefore understand the issue more in details.

**Comment by annasoloviova** [comment] 2018-05-30 12:49
A user reported that removing Google Play updates (https://support.google.com/googleplay/answer/7512202?hl=en) helped.

**Comment by GerasDraugas** [comment] 2018-05-30 12:55
this is not google play problem, other apps updating normally.

**Comment by stephan75** [comment] 2018-05-30 20:39
@lfoppiano ... about the nightly apk:

please see this thread on Osmand's googlegroup,
https://groups.google.com/d/topic/osmand/FE_7PxGzfj8/discussion
and please write an email to me, I am the one with email address "der.stephan...."

**Comment by simonjanosbalint** [comment] 2018-05-30 21:40
Since the last update, two completely different brands devices with Android 5.x doesn't update with the 504 error code while Samsung & Android 6.x has no problem with this - fix it! The "clean" the Google Play store & Service Framework method (Clear Data and Clear Cache) doesn't solve the problem!

**Comment by nortonrs** [comment] 2018-05-31 12:21
I have Motorola G2 (XT1068) working with Android 6. Exactly the same issue... when trying to install Osmand+ v3 through PlayStore the phone frozen in a black screen and a reboot is needed.

**Comment by jbelien** [comment] 2018-05-31 18:44
Same issue on my phone (Gigaset GS160 - Android 6.0) !

Impossible to update OSMAnd+ (paid version) : the phone freeze and then reboot.
I uninstalled the app and tried to re-install both free and paid version with same result (freeze + reboot).

**Comment by nortonrs** [comment] 2018-06-01 00:54
Osmand sent to me the download link of Osmand+ 2.9.
 I installed it while a fix for version 3.0 isn't available.
Cheers,
--------------------------------------------
Em qui, 31/5/18, Jonathan Beliën <notifications@github.com> escreveu:

 Assunto: Re: [osmandapp/Osmand] can not update to 3.0.2 from Playstore (#5505)
 Para: "osmandapp/Osmand" <Osmand@noreply.github.com>
 Cc: "nortonrs" <norton_rs@yahoo.com.br>, "Comment" <comment@noreply.github.com>
 Data: Quinta-feira, 31 de Maio de 2018, 15:45
 
 Same issue on my phone (Gigaset
 GS160 - Android 6.0) !
 Impossible to update OSMAnd+ (paid version) : the phone
 freeze and then reboot.
 
 I uninstalled the app and tried to re-install both free and
 paid version with same result (freeze + reboot).
 
 —
 You are
 receiving this because you commented.
 Reply to this
 email directly, view
 it on GitHub, or mute
 the thread.

**Comment by rodoviario** [comment] 2018-06-01 13:53
I have similar issue. When updating from F-droid, it downloads... but when try to install, the phone freezes and reboot.
Also tried to uninstall OSMand...and also F-droid, and start over...but the phone hangs... Installing 3.0 for now until news on the issue

**Comment by hakuchi** [comment] 2018-06-01 16:21
@rodoviario What Android version have your phone?
For now a lot of Android 6 devices are not able to download/update the 3.0.2 from Playstore.

**Comment by rodoviario** [comment] 2018-06-01 16:51
Sorry, I forgot to tell
Android 6.0 stock, with systemless root via Magisk
Some /system apps I have erased. The 2.9.3 f-droid version was working and I am going to use that until someone figures out the reason for the issue

**Comment by vshcherb** [comment] 2018-06-02 12:06
Fixed with https://github.com/osmandapp/Osmand/commit/14e11eaff309e336d82d7c2483a716fc90994591.

The issue was related to D8 compiler which is not working properly on Android 5.1

**Closed by vshcherb** 2018-06-02 12:06 UTC
Labels: Observed

**Comment by jbelien** [comment] 2018-06-02 13:37
Awesome !  Thanks a lot @vshcherb and @crimean ! 👍 

How will the new version will be released, so we know when it's safe to reinstall our favorite app ? 😋

**Comment by hakuchi** [comment] 2018-06-02 15:00
3.0.3 works perfect on my phone.
It is released as a Beta version in Playstore.
you can download this beta version by subscribing the Beta program.

**Comment by simonjanosbalint** [comment] 2018-06-02 17:05
So now how do we go? I do not want to install a beta application whenever possible. Will it work on the next version of Android5.x? 
On my Android 6, I'm happy with it but I would like to have the latest version on my other two smartphones.

**Comment by sonora** [comment] 2018-06-02 17:33
It is officially updated - you should see it within a few hours at the latest. From my testing so far on all devices I have available, confirmed on all Android versions 4.03 and up.

**Comment by simonjanosbalint** [comment] 2018-06-02 17:49
yes it's finally updated! great job & thx

**Comment by stephan75** [comment] 2018-06-02 19:14
Thanks a lot! I can confirm that manually installation of Osmand~ apk file from nightly builds also installs without error on Android 5.1 .

**Comment by simonjanosbalint** [comment] 2018-06-02 20:17
@stephan75 ... also from Google Play (Android 5.0.1, 5.1.1)

**Comment by GerasDraugas** [comment] 2018-06-02 20:37
Updated to 303 and work fine. Fnx.

**Comment by jbelien** [comment] 2018-06-02 21:35
> 3.0.3 works perfect on my phone.
> It is released as a Beta version in Playstore.
> you can download this beta version by subscribing the Beta program.

Confirmed ! 3.0.3 works just fine 👍

**Comment by DrVanScott** [comment] 2018-06-03 10:12
Works for me, too! Thanks a lot!

**Comment by nortonrs** [comment] 2018-06-03 17:33
3.03 working perfectly now. I installed it fromPlaystore. 
Motorola G2 (XT1068) running with Android 6.0 (rooted).
Thanks!!

**Comment by EmmanuelMess** [comment] 2018-06-09 23:02
Experiencing issue on for version 3.0.3 from FDroid:
Android: 6.0
Phone: Moto E Gen 2 4G
Osmand version: 2.9.3

**Comment by hakuchi** [comment] 2018-08-07 10:26
Same issue again with update to 3.1.2 from Play Store!

**Comment by dmpr0** [comment] 2018-08-07 10:39
@hakuchi Thank you for the feedback! We found that on some devices there is a problem when updating/installing OsmAnd. At the moment, we stopped the distribution version 3.1.2. We will return it to Google Play, immediately after fixing the error.
