### ISSUE TITLE
Make ways clickable and show their properties

### ISSUE THREAD

**Issue by NotSoImportant** [osmandapp/OsmAnd#9800] opened 2020-09-13 13:36 UTC
Data of roads like maxspeed, maxheight, access (...?) are available in OsmAnd map data (obviously, because it is used / displayed while routing).
Hover there is no way to show maxspeed & maxheight at the map.
This request is about to make roads clickable (maybe with a different configuration / selection method) in order to show all available properties of this way / non-point map feature.
This would help much with mapping (althouh I know this is not the main purpose of this app).

This might be an easier / first step compared to completely implement #3380

**Comment by pebogufi** [comment] 2020-09-13 16:28
Perfect would be to see ALL tags.
A list like following would be ok.
tag=value
tag=value
..-

**Comment by Discostu36** [comment] 2020-09-15 09:47
Duplicate of #2232

**Closed** 2020-09-15 14:06 UTC
Labels: Nice to Have

**Comment by Lee-Carre** [comment] 2022-01-28 05:06
There are already a few ways of doing this:
* use OSMfocus (or the newer OSMfocus Reborn), which is intended for exactly the desired use-case described here. It can follow your GNSS position, so you literally just have to walk up to an element to have its tags listed
* from within OsmAnd
  * enable the editing plugin
  * select the element of interest
  * in the details, the URL for the element is a clickable link
  * tapping it will open it in a browser of your choosing, and show all the data which OSM has about the element

**Comment by scaidermern** [comment] 2022-01-28 06:54
> There are already a few ways of doing this:
> 
>  [...]
>     * from within OsmAnd
>       
>       * enable the editing plugin
>       * select the element of interest
>       * in the details, the URL for the element is a clickable link
>       * tapping it will open it in a browser of your choosing, and show all the data which OSM has about the element

This works only for POIs but not for regular ways like roads and paths.

**Comment by NotSoImportant** [comment] 2022-01-28 07:02
Thanks. I tried it. It looks really nice, but it has the same issue than clicking the link in OsmAnd
- does not (really) work offline. Yes it is caching a frw requests, but then throws errors and hangs. 

And although there are again cross-links:
- not edit is possible inside
- constantly switching apps is required for this use case.
    - this reduces the number of possible users to the ones having installed both
    - it adds an extra obstacle of "na, I won't do this now"
    - even if context of the object is preserved it adds other distraction like
        - different style
        - different interaction model

With this beeing said, from a technical perspective it might be a challange, but I am talking about a use case here. And as a user it would be so helpful to just get the properties inside of the already existing properties list.

**Comment by Ben3094** [comment] 2024-05-12 17:55
Need this too, please reopen the issue.
