### ISSUE TITLE
Could Not Start TTS Engine

### ISSUE THREAD

**Issue by seniorm0ment** [osmandapp/OsmAnd#9637] opened 2020-08-14 12:46 UTC
Having trouble with Text to speech, it's not playing during nav.
If I go to development settings and test the TTS, It shows an error stating "Could not start tts engine", and none of the prompts voice.

Am using the F-Droid version of OSMAnd~, Android 10

**Comment by grravity** [comment] 2020-08-25 18:59
Still have not been able to figure this out? Is anyone able to reproduce, or have any suggestions?

**Comment by grravity** [comment] 2020-08-25 22:58
I have gotten it "working" with en-gb and en
But en-tts and en-gb-tts still give the error.
Not sure the difference? But worth noting.

**Comment by sonora** [comment] 2020-11-08 08:06
en-gb and en are recorded voices, way inferior to using TTS voices.

Have you gone to your **device's** (nòt OsmAnd's) language and region settings, selected a TTS engine there, and used the button there 'listen to an example'?

Have you tried different TTS engines? Many devices come pre-installed with 2, and you can also download further ones.

Once you configure a TTS engine there which works for your device, OsmAnd should be able to initialize it.

**Comment by bellera** [comment] 2021-05-25 09:34
**TTS doesn’t work if offline mode (air-plane mode on or not network signal)**. This is a problem in many hiking areas. It's using the TTS engine or your device. Usually Google Text-to-Speech. You can download TTS apps that can be configured as your TTS engine for Android. But I didn't find any that works offline. TTS voices are expensive and licensed.
**In fact, for hiking that is needed is just an alarm deviation.** I prefer this, but the Google bell that comes with **OsmAnd** is sometimes difficult to hear (for example when you are near a mountain river). Other apps such **ViewRanger**  permits to configure alerts with personal sounds.

**Comment by bellera** [comment] 2021-05-25 12:41
[Found & tested 3 TTS offline engines for Android](https://github.com/osmandapp/OsmAnd/issues/7173#issuecomment-847834553)

**Comment by seniorm0ment** [comment] 2021-05-26 01:15
from what I gather, you are, confirming that there is currently no good solution to the TTS issue?

**Comment by bellera** [comment] 2021-05-26 07:29
I'm not an OsmAnd developer. Just an user with advanced computing skills. **Is not a TTS issue. It's a TTS limitation.**
Please read [Found & tested 3 TTS offline engines for Android](https://github.com/osmandapp/OsmAnd/issues/7173#issuecomment-847834553)
I you do **offline hiking**, try to use a non-TTS voice. I tried English, French & Spanish. They look pretty. Non-TTS voices are standard text to sound in OGG files. They are similar to a standalone car GPS (such TomTom). If you aren't pleased with the OGG files for your language you can change them. I didn't test it but I think with non-TTS voice you will not have POIs. You will have an standard sound like "you arrived to a POI" or "you arrived to your destination". It's impossible to reproduce the name of a place.

- ViewRanger (I use it since 2014) -> Alarm sounds
- Wikiloc (Used for other colleagues) -> Alarm sounds,  [https://help.wikiloc.com/article/107-do-the-apps-guide-you-with-voice-messages](https://help.wikiloc.com/article/107-do-the-apps-guide-you-with-voice-messages)
- OutdoorActive (Used for another colleague on iPhone) -> Voice. Not working in offline mode.
- OsmAnd Android (I'm using it now) -> TTS voice doesn't work in offline mode.
- OsmAnd iOS (Used for another colleague) -> TTS voice doesn't work in offline mode.

**Comment by sonora** [comment] 2021-06-01 08:00
@bellera This statement bogs me: "_TTS doesn’t work if offline mode (air-plane mode on or not network signal)._"

I have never experienced this EVER, and have always been on expeditions entirely without hope of being online at all (in fact the very reason why I joined the OsmAnd project from day 1). What device and engine do you experience this with?

**Comment by bellera** [comment] 2021-06-01 09:55
BQ Aquaris X | Android 8.1.0

**Comment by sonora** [comment] 2021-06-01 12:45
So i assume you are using the google TTS rengine?

While I am personally not very fond of the google one, I have tested it on mostl my devices in the last 10 years or so and there was not one where you could not go into its settings (the Android settings, not OsmAnd's), drill down deerp enough, and download the language file for each language you intended to use. All these languages will then work completely offline, not tequiring to blow everything via the google servers. (Same quality ,also. Unlike in  the vice versa case of speech recognition, where naturally the online servers pick up a lot more dialect than the offline version can... ;) l.

**Comment by bellera** [comment] 2021-06-01 13:46
> So i assume you are using the google TTS rengine?

Yes.

> While I am personally not very fond of the google one, I have tested it on mostl my devices in the last 10 years or so and there was not one where you could not go into its settings (the Android settings, not OsmAnd's), drill down deerp enough, and download the language file for each language you intended to use. All these languages will then work completely offline, not tequiring to blow everything via the google servers. (Same quality ,also. Unlike in the vice versa case of speech recognition, where naturally the online servers pick up a lot more dialect than the offline version can... ;) l.

Do you mean I must to **Install voice data** from Google as explained at [https://www.howtogeek.com/442761/how-to-modify-google-text-to-speech-voices/](https://www.howtogeek.com/442761/how-to-modify-google-text-to-speech-voices/) ?

**Comment by sonora** [comment] 2021-06-01 19:34
While most of that pages revolves around Accessibility features, yes, the relevant section is below `'In the “Google TTS Options” menu, tap the “Install Voice Data” option.'`

Just download the language pack (or several) you intend to use, and it should perfectly work offline. Or not?

**Comment by IzzySoft** [comment] 2021-06-30 16:19
I've OsmAnd running on a BQ Aquaris X5 Plus here (LineageOS, still Nougat as development stopped). It ships with Pico. No dice getting that working with OsmAnd – all I get is the very same "Could not start tts engine" toast. Installed eSpeak from F-Droid and configured it (including the download of its language files) – same results. And no, I won't download Google's stuff (my devices run Google free, so I don't even have Google Services or Play Store installed – for reasons, and I plan to keep it at that).

From system settings, both TTS engines work. Trying Favo's [TTS-Tool](https://gitlab.com/FAvO/tts-tool), both are available (and work). Still, OsmAnd fails using any of them. No idea why. The pre-recorded voices work fine, though, and I'm greatful for that – but they don't give street names etc.

**Comment by sonora** [comment] 2021-07-01 06:11
I once again went through all the test devices I have accunulated over the years, and cannot reproduce on a single one.  Depending on the device, I have tried the google, Samsung, and pico TTS engines, both on devices with and without google services active, and they all worked flawlessly and completely offline.

I deduce this is not a general issue but must somehow correlate to a special setup or circumstances. I notice that e.g. reference is made above to the F-Droid version, how do things look with an OsmAnd native build, like from our web site?

**Comment by seniorm0ment** [comment] 2021-07-01 10:57
@sonora
>Google services active

Have you tried on a device with Google services completely removed (Which means no Google TTS as well)?

>F-Droid version

Yes because people who care about privacy do not run Google services on their phone, this is a big reason why OSM has such high popularity. The F-Droid version does not contain Google services. 
No Google services means no Google TTS.

Have you not tried testing with the F-Droid Build? (Without Google)

@IzzySoft
>eSpeak; same results

Yeah same as you. Pre-recorded works fine, but no street names or anything.

**Comment by sonora** [comment] 2021-07-01 11:44
Short clarification: I am 99% testing devices with **stock ROM**, meaning 'google' is in some fashion part of the ROM. When I say "no google services active", I mean the following: There is no google account registered for the device. And at least the following apps and system apps are set to "Disabled": Gmail, Google, Google Play Services, Google Play Store, Maps, Google Calendar Sync, Google Contacts Sync, Google One Time Init, Google Partner Setup,Google Services Framework.

Google Text-to-Speech would, of course, be enabled in order to test it.

But as I said, I do not encounter that TTS would only work while Online in this setup, and I would not really know a reason why that should be, either. Looks like an Internet search for this issue mostly produces that for most TTS engines you must pre-download the offline data for any respective language you intend to use offline....

 PS: To my knowlwdge, if you test the nightlies from our website, they should completely not use any google specifics or services.

**Comment by seniorm0ment** [comment] 2021-07-01 13:30
>I am 99% testing devices with stock ROM , meaning 'google' is in some fashion part of the ROM. When I say "no google services active"

Even on stock rom, you can do a (soft?) removal of Google services I believe using ADB. I say idk because I know they still show in the app list, however they are "removed", as in apps won't even detect it. Not entirely sure what the deal is with that. That's currently my situation with one of my devices, due to the inability to flash a custom rom on it, that's the best that can be done.
But from a privacy perspective it's of course better to be using a different ROM such as AOSP or GrapheneOS. That aside simply disabling the services within Androids app menu doesn't disable them all, and going through ADP removes/disables them further than that. I know because I've tried both and just disabling within Android still allows apps to detect Google services, but using ADB they don't.

>Google Text-to-Speech would, of course, be enabled in order to test it.

Well this sounds like the issue. You have Google TTS and are testing with it, and we don't. That's what the entire issue here is about. Unless I misunderstand what you meant by that statement.
But if you have Google TTS installed, then you're probably going to be unable to replicate our issue. As well as possibly not having the F-Droid version, but the Google TTS being installed or removed seems to be the bigger issue.

Also yes I see no reason why being online or offline matters if you have the packs installed offline (which I personally do).

**Comment by sonora** [comment] 2021-07-01 13:58
Let me summarize:
- I have tested all of these: google, Samsung, pico , SVOX, IVONA, and eSPEAK TTS engines on at least one occasion. OsmAnd can use any of these.
- They all work **offline** with OsmAnd. Hence the above statement somewhere "TTS doesn’t work if offline" is generally false.
- I am not aware our code uses, or even needs, any kind of google service to initialize the TTS engine  set as device default in Android. Unless I am overlooking something, we simply use the documented Android methods

So I guess we now need to come back to the original issue reported: We need to establish for which OsmAnd app sources, on which ROMs some people receive "Could not start tts engine", and for which tts engines installed and functional on that device. And if this is for all TTS engines, or only for some. And is this a regression, or has this never worked for you.

Let's find out how to reproduce. Looking through our Issue log,, considering the gravity of this, it does not seem a frequently occurring at all ...

**Comment by seniorm0ment** [comment] 2021-07-01 18:47
>Which ROM

Again, personally stock Android 10, with services removed via ADB. I can't test it on anything else currently.

>All TTS engines

I've tried everything on f-droid, especially flite and espeak. no cigar.

>Has this never worked for you

Never has worked for me.

**Comment by sonora** [comment] 2021-07-02 05:10
- How about with http://osmand.net/downloads. Can you plesse install and try that version (works in parallel).
- When you say '_with services removed via ADB_', which ones exactly?

**Comment by seniorm0ment** [comment] 2021-07-02 10:25
>Can you plesse install and try that version (works in parallel).

I don't have time to play around with it I've been busy. If I find time I'll let you know.

>When you say ' with services removed via ADB ', which ones exactly

Literally ALL Google services, apps, anything google that I can.

>Is " Could not start tts engine " the exact message you receive? I cannot find the source of that currently.

I can't check atm, but i'll get back to you. I want to say yes, it popped up when doing the tests in developer settings so it might be part of that plugin.
But again, it "works" with the prerecorded names it just doesn't read the street names and stuff like the same exact problem Izzy mentioned.

**Comment by sonora** [comment] 2021-07-02 12:19
Maybe it helps you to look at the Issue I have linked above. It seems to me that , based on reading that, if you are on a system with all native TTS support removed from the ROM, any post installed TTS engines may appear installed and available from some point of view, but in order to  be fully usable system-wide they may require proper activation in either the system's general TTS settings, or Acessibility settings, or both.

If it was something along those lines, it would explain why I cannot reproduce. 

The fact the pre-recorded voices work is something rather differen:t That's more like triggering a media player to play a file, while using TTS involves activating the Android capability to synthesize audio from text.

**Comment by seniorm0ment** [comment] 2021-07-02 13:01
Yes, that sounds like it would cause the issue, however the "fix" suggested (select it in Android TTS/Accessibility settings) does not resolve that issue. I've done that with,both FLite and Espeak already.

**Comment by sonora** [comment] 2021-07-02 13:43
Check out https://github.com/GrapheneOS/os-issue-tracker/issues/377#issuecomment-872963672, it sounds like simply 'selecting' it may not be enough on such devices.

**Comment by thestinger** [comment] 2021-07-02 15:23
Selecting it by pressing on it will open a dialog for activating it. The usability issue is that it will show it as being the active TTS before it has been activated. It happens even on a device with Google apps and services if their TTS app is disabled. If you install another app, the Settings UI shows it as active since it's the only one. It's just a slightly bad UI. It should show none as active when none is active, rather than always showing one selected in the radio menu.

**Comment by IzzySoft** [comment] 2021-07-04 23:49
> But if you have Google TTS installed, then you're probably going to be unable to replicate our issue.

I second this being likely.

> Never has worked for me.

Same here.

> How about with http://osmand.net/downloads. Can you plesse install and try that version (works in parallel).

<s>On the device I currently use with OsmAnd (BQ Aquaris X5 Plus stuck on Android 7/LOS), no dice: TTS remains dead for both, the F-Droid version and the one from the indicated page.</s> On a Fairphone 2 running Android 10/LOS with eSpeak from F-Droid both work. So it doesn't seem the F-Droid build versus "other builds", but must be something else. But admitted, the presence (or rather absence) of Google-TTS seems to be unrelated as well, as none of these two devices have Google stuff installed: both have eSpeak from F-Droid, the BQ additionally has Pico pre-installed with LOS.

> Is "Could not start tts engine" the exact message you receive? I cannot find the source of that currently.

It is here – though I'm not 100% sure how the exact English phrase is (devices are set to German).

> the "fix" suggested (select it in Android TTS/Accessibility settings) does not resolve that issue.

Same here. And I did what that Graphene comment mentioned as well without success.

**Update:** You might have noticed I applied <s>strike-through</s> to the device I couldn't get it to work with for. I finally managed getting it to work there with PicoTTS. A quite profane issue ***in this case*** (not applyable to all): XPrivacyLua seems to have blocked it (not sure which of the boxes as I had only some ticked, unticked all for testing, then re-ticked some and it still remained working). As only few users will have Xposed and XPrivacyLua running, this is probably not the cause here – but I'm out of the "testing carousel" as I'm no longer affected (lucky for me)…

Short **TL;DR:**

* it's not F-Droid build vs. `net.osmand.huawei` build (I tried both)
* it's not Google TTS present or absent (obviously works with, and in my cases also without)
* it *may* be XPrivacyLua configured to restrict OsmAnd too much (easy to test for those using it: just do not apply it to OsmAnd at all) – @seniorm0ment could that be your culprit, too?
* offline mode definitely works with TTS (just tested on the FP2: I only switched on WiFi after having tested the `net.osmand.huawei` to cross-check with the F-Droid version which I had to install first, and the FP2 has no SIM currently)

**Comment by seniorm0ment** [comment] 2021-07-05 12:48
Sorry for the late response, As I've stated the Android settings (activate) don't work.
My language is English, not German just for reference, so that is seeminlgy unrelated.
Also I am not using (XPosed)XPLua at all on my device, although have you tried it on your other devices (I presume aren't running XPLua?) Or are your other devices still having trouble?

Are there any debug logs we can grab that might be of help?

**Comment by IzzySoft** [comment] 2021-07-05 20:26
> Also I am not using (XPosed)XPLua at all on my device, although have you tried it on your other devices (I presume aren't running XPLua?) Or are your other devices still having trouble?

If that was directed at me: I no longer have that issue. XPLua was the cause on one of my devices (which I suspected when the problem was not reproducible on the FP2 which I had not yet fully set up with it), but I doubt it is the same thing for others. Many affected users have not even rooted their devices, not to speak of running Xposed. Please consider my incident an edge case, the problem here was in front of the display (I should have tried disabling XPLua much earlier to find out).

One thing you *could* test, though, is whether [TTS-Tool](https://apt.izzysoft.de/fdroid/index.php/apk/de.favo.ttstool) detects your TTS fine and can use it. I've read reports that with this tool installed and configured, even OsmAnd suddenly started using TTS fine (though I think that a side-effect of having to configure the TTS through the tool, thus even performing the overlooked steps).

**Comment by seniorm0ment** [comment] 2021-07-05 23:19
Yes that entire comment was a reply to your points (except for the debug logs question).
Also didn't know that test tool existed thanks, I just tried it and it looks to be working no issues.

**Comment by IzzySoft** [comment] 2021-07-06 00:33
With that tool installed and working, did that help getting OsmAnd doing the same (have TTS working) as reported by some?

**Comment by seniorm0ment** [comment] 2021-07-06 12:02
Thought it was just to test if TTS was working system wide or not, however I just reinstalled it and then tried running OSM and it seems to be working interestingly.
What exactly is the tool doing that would cause it to cause OSM to work though?

That being said, slightly related, any chance you could provide an audio clip of your eSpeak TTS? I can't tell if the voice is just really shit (probably, and I know they're not as good as the proprietary TTS options currently) or I'm doing something wrong.
Would appreciate a sample of how yours is just so I can compare it to mine.

**Comment by IzzySoft** [comment] 2021-07-06 15:20
> I just reinstalled it and then tried running OSM and it seems to be working interestingly.

Glad to read that – and thanks for confirming the rumors!

> What exactly is the tool doing that would cause it to cause OSM to work though?

Good question. I've asked myself the very same thing – and I guess I'm not the only one eager to hear/read the answer to that :smile: Because if that would be clear, it might be possible to integrate it with OsmAnd directly.

> eSpeak TTS? I can't tell if the voice is just really shit

Thanks for confirming that, too :speak_no_evil: Took me a lot of playing with provided options to get at least the worst out of it (variant: NVDA (Jacky), speed: 152WPM makes it easier to bear that burden – and might even be called "acceptable" with English; with German, it cannot deal with umlauts and some more). Depending on what language you need, [RHVoice](https://github.com/RHVoice/RHVoice) is available [at F-Droid](https://f-droid.org/packages/com.github.olga_yakovleva.rhvoice.android/) and might be an option – if your language is one of American English, Brazilian Portuguese, Esperanto, Georgian, Ukrainian, Kyrgyz or Tatar.

**Comment by sonora** [comment] 2021-09-16 05:51
Let me close this, from what I see these were system issues, not OsmAnd issues.

**Closed by sonora** 2021-09-16 05:51 UTC
Labels: Observed

**Comment by kd4e** [comment] 2025-04-21 03:26
Using OsmAnd with Graphene - the SherpaTTS works for travel prompts.
