### ISSUE TITLE
Favorite import: "show on map" state gets reset to "on"

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12402] opened 2021-08-06 10:59 UTC
After importing favorites each favorite group has "show on map" set to "on" even if it was set to "off" during export.

**Comment by cepprice** [comment] 2021-09-05 23:43
Duplicate of https://github.com/osmandapp/OsmAnd/issues/11503

**Closed** 2021-09-06 07:40 UTC
