### ISSUE TITLE
Longer route instead of straight navigation

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#6321] opened 2018-11-30 06:55 UTC
#6245 NOT FIXED

![screenshot_20181102-051613_osmand](https://user-images.githubusercontent.com/14617699/47890115-7bcb1900-de5e-11e8-8959-f991c035986c.png)
OsmAnd (offline) Navigation service

From: 60.00502, 30.32685
To: 60.00185, 30.32810

[osm graphhopper_car ](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=60.00502%2C30.32685%3B60.00185%2C30.32810#map=18/60.00345/30.32764)
and
[osm osrm_car ](https://www.openstreetmap.org/directions?engine=osrm_car&route=60.00502%2C30.32685%3B60.00185%2C30.32810#map=18/60.00345/30.32764)
shows correct routing.

**Comment by vshcherb** [comment] 2018-12-11 23:02
Can't reproduce it as well :(

**Comment by c-e-p-x-u-o** [comment] 2018-12-23 22:59
Why have you added  Observed while you can't reproduce it?

Really I can't reproduce it every time. Sometimes it shoes correct (straight) routing, sometimes it show wrong routing as on screenshot. I don't change my osm setting and don't know what it depends on.

**Comment by c-e-p-x-u-o** [comment] 2018-12-23 23:00
It works correctly for me recent times. I'll reopen it in case of regression.

**Comment by 532910** [comment] 2020-04-14 21:24
Still not fixed, still not reproduceable:
![image](https://user-images.githubusercontent.com/14617699/79275742-707f7800-7eaf-11ea-9dbb-7b163d309b95.png)

**Comment by 532910** [comment] 2020-05-18 23:14
It's a fresh screen:
![image](https://user-images.githubusercontent.com/14617699/82267869-373a9c00-9976-11ea-9b7d-8e6b33e7cc18.png)
What the hell does he like this route?

**Comment by vshcherb** [comment] 2020-05-24 11:31
The main issue that UT is detected on very sharp turns via multiple ways. In that case it looks like it is a roundabout but it is not mapped as such. So it causes UT to be displayed.

To be honest I think it should be mapped as roundabout cause it is circle and oneway.

**Comment by 532910** [comment] 2020-05-25 20:03
Виктор, this issue is not about u-turn, but about wrong routing. The correct routing is:
![image](https://user-images.githubusercontent.com/14617699/82840612-e7128b00-9edb-11ea-925f-83ad72d51839.png)

**Comment by 532910** [comment] 2020-05-25 20:39
Should title be reverted?

**Comment by 532910** [comment] 2020-05-25 22:33
Forgot to apologize about bad initial issue explanation.

**Comment by 532910** [comment] 2020-05-25 22:34
BTW, pay attention on the first screenshot and the previous #6245 issue.

**Comment by vshcherb** [comment] 2020-06-09 15:05
![image](https://user-images.githubusercontent.com/1042025/84164874-54ddbb80-aa73-11ea-8c9d-ef87a8579ac0.png)
Map fix: The issue was fixed by setting right priority for primary way between segments (segments always take the highest road priority).
Secondly, proper fix will be assigned for traffic:signals - direction, here there was an extra penalty for passing same traffic signals

**Closed by vshcherb** 2020-06-09 15:05 UTC
Labels: Observed

**Comment by 532910** [comment] 2020-06-09 19:04
Sorry, what is `right priority`, could you point me to OSM wiki describing it and changeset that was done?

**Comment by vshcherb** [comment] 2020-06-11 13:05
I have no exact information but I guess it was fixed cause somebody changed secondary_link to primary_link on intersection. Anyway I didn't do investigation what has changed and I didn change anything

**Comment by 532910** [comment] 2020-08-20 14:48
The bad route is still offered:
![image](https://user-images.githubusercontent.com/14617699/90787254-33b80780-e30d-11ea-9478-36e1f90ea87b.png)
![image](https://user-images.githubusercontent.com/14617699/90787292-40d4f680-e30d-11ea-939d-359e05e8c32a.png)
