### ISSUE TITLE
Settings to set default speed for bicycle / boat / pedestrian routing

### ISSUE THREAD

**Issue by sicherist** [osmandapp/Osmand#5622] opened 2018-06-28 20:03 UTC
Thanks for creating and maintaining Osmand!

I noticed that when bicycle-routing Osmand seems to assume an average speed of 20 km/h and calculate the time the route will take based on this speed. This however is way too fast for me, not only because we have a lot of hills here. I couldn't find an option to adjust the bike-speed that Osmand uses to calculate routes.

I would love to see this feature in a future release.

**Comment by mahdi1234** [comment] 2018-07-05 16:12
One thing I noticed is "Use elevation data" works in walking mode, but does not change estimation for cycling mode, perhaps this could solve the issue as well.

**Comment by annasoloviova** [comment] 2018-07-07 15:45
The same adjustment has been requested for boat mode. To measure your speed by gps and divide distance by speed.

**Comment by bege10** [comment] 2019-04-16 17:53
duplicate of https://github.com/osmandapp/Osmand/issues/5982 ?

**Comment by maffe** [comment] 2019-05-26 13:01
I think OsmAnd should take into account:

1. The general riding speed. It seems OsmAnd always assumes higher speeds than I’m capable of. The only way to change that seems to be to modify routing.xml (?). Do I need to compile OsmAnd myself? It should be a simple setting inside OsmAnd, as requested here. Ideally OsmAnd could be told to adjust it by itself based on speeds in the past to match my fitness level automatically.
2. The speed on a particular trip. Sometimes it’s very windy and I’m way slower than usual (or maybe I just ride more relaxed), but even after riding for a while OsmAnd seems to calculate the time simply based on a fixed speed. Example: Let’s say I let OsmAnd calculate a route and the result is 60 minutes for 20 km. I then start the ride and after 20 minuted I only managed to ride 5 km. It’s reasonable to assume at this point that I need 60 minutes for the remaining 15 km, but OsmAnd would still display 45 minutes because the calculation is not based on the real speed.

**Comment by crimean** [comment] 2019-06-27 12:04
Fixed by https://github.com/osmandapp/Osmand/commit/d378fe9e5a85693f41e2cae6996e800456e14d95
Description will be added shortly.

**Closed by crimean** 2019-06-27 12:04 UTC

**Comment by hman2** [comment] 2020-07-30 15:38
Descriptioin will be added "shortly". Now it's 2020...

**Comment by vshcherb** [comment] 2020-07-30 16:49
It will be changed completely, so min/max speed will be moved to "Routing engine" options and only default speed will be left.

**Comment by xeruf** [comment] 2021-09-06 18:57
I've set a default speed at 10 km/h, but OsmAnd still uses 20...

**Comment by breversa** [comment] 2021-09-06 19:05
Bike faster ! :-P

**Comment by hobpet** [comment] 2021-09-07 21:22
> Bike faster ! :-P

We had to! We almost missed the last ferry yesterday at Illmitz, Austria. :)

**Comment by pineirod** [comment] 2021-09-14 13:47
Same here
The times for biking are too short (it assumes a very high speed)

**Comment by aSemy** [comment] 2023-10-08 06:24
I still find that OsmAnd assumes a 20kph average speed, which is widely inaccurate when I cycle. Can this issue be reopened? Else I can make a new one.

**Comment by breversa** [comment] 2023-10-08 07:36
What about OsmAnd using 20km/h by default, but learning/adjusting that speed following the successive measurements of actual speed?

**Comment by aSemy** [comment] 2023-10-08 09:54
I've opened a new issue #18284 to ask that OsmAnd uses the more configurable duration estimate provided by Brouter

This issue is also relevant #5622
