### ISSUE TITLE
Rendering broken, some parks

### ISSUE THREAD

**Issue by robinpaulson** [osmandapp/OsmAnd#15923] opened 2022-12-09 13:05 UTC
-36.92040 174.83503

![](https://i.imgur.com/YhirOgJ.png)

There is a large park at the centre of the screenshot, which renders fine on osm.org but not in osmand.

**Comment by scaidermern** [comment] 2022-12-09 13:10
Check if the park gets rendered if you enable Configure map / Details / Nature reserve.

If so, the tag  `boundary=protected_area` is likely the cause of the problem. I think the tagging is correct, though. OsmAnd just fails to handle it properly.

**Comment by k-yle** [comment] 2022-12-09 22:48
👍 duplicate of #15573, should I close that issue? the other issue has been triaged

**Comment by scaidermern** [comment] 2022-12-10 07:15
Yes, close this duplicated issue.

**Comment by robinpaulson** [comment] 2022-12-10 12:19
I did as suggested, it still does not render.

**Closed** 2022-12-11 08:42 UTC
