### ISSUE TITLE
Strange rendering of rectangular shapes

### ISSUE THREAD

**Issue by rbovard** [osmandapp/OsmAnd#12366] opened 2021-08-03 14:39 UTC
### Description

Strange rendering of rectangular shapes, see screenshots:

OsmAnd
![image](https://user-images.githubusercontent.com/4549666/128034188-5736203d-626b-4383-a078-8f0dd7bda69b.png)

OSM
![image](https://user-images.githubusercontent.com/4549666/128034223-979892f2-f9ae-4c0c-a4fe-4de04e42db4b.png)

### How to reproduce?

Pan to rectangular shapes, like buildings or parking lots. The screenshots are from [here](https://www.openstreetmap.org/#map=19/46.77777/6.64123)

Maybe something related to coordinates precision (digits)?

### Your Environment

- OsmAnd Version: OsmAnd+ 4.0.2
- Android/iOS version: Android 10

**Maps used:**   

Offline: Switzerland Lake Geneva (01.07.2021), with Live data from today (03.08.2021)

**Comment by xmd5a2** [comment] 2021-08-04 07:12
Yes, it is related to coordinates precision

**Comment by scaidermern** [comment] 2021-08-04 09:06
Duplicate of #6130 I guess.

**Comment by rbovard** [comment] 2021-08-04 13:42
> Yes, it is related to coordinates precision

Thanks for the confirmation. Is something planned to handle that?

> Duplicate of #6130 I guess.

Not sure. As @vshcherb said it's because points and lines are generated by "slightly" different grid. Here were are talking of distorsions of same geometry types.

**Comment by vshcherb** [comment] 2022-03-22 12:13
Merged to https://github.com/osmandapp/OsmAnd-Issues/issues/1049

**Closed by vshcherb** 2022-03-22 12:13 UTC
Labels: Observed

**Comment by vshcherb** [comment] 2022-03-22 12:17
Merged to https://github.com/osmandapp/OsmAnd/issues/9821
