### ISSUE TITLE
Persistent trip recording on OS status screen

### ISSUE THREAD

**Issue by andrixnet** [osmandapp/OsmAnd#20712] opened 2024-08-28 18:37 UTC
### Description

Recently I've been on a medium trip. OsmAnd helped me find the way. Also, during my trip, I had it record it. 
After arriving at my destination, I stopped recording.
Afterwards, later at home I say that OsmAnd still persisted in the OS status screen (where app notifications appear), allegedly with a still active recording session. 

The problem happened after the return trip (for which I also used OsmAnd navigation with trip recording)

### Steps to reproduce

Start navigation. Start track recording. 
Drive to destination.
At destination, after navigation finished, initiate stop recording. 
AFAIK I pressed stop recording, then close on the next screen.

### Actual result

Later (at home) I saw this in my status:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/392607fa-f9de-41f0-8a91-325f386e27ec"  width="300" height="auto"/> </th>
  </tr>
</table>

I tap on the notification itself (not the resume/save) buttons. 
I am shown this screen in OsmAnd _(after obviously the app showing the splash screen of a fresh start)_ :

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e8de029b-2f4d-4880-89d6-1a6a73edd884"  width="300" height="auto"/> </th>
  </tr>
</table>

Notice that it is not recording. If I tap recording here, I am shown with the screen I saw when I started navigation, ie to start a new recording.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/f39d8c94-fa48-4972-a43f-4b16265883df"  width="300" height="auto"/> </th>
  </tr>
</table>

Trying to drag the notification to the right to dismiss it doesn't work. 

Checking, the actual track is properly saved as .GPX file already. 

### Expected result

I am not sure what the expected behaviour should be. 

- IMO I recorded trip, I saved recording, this notification should not have appeared anymore. 
- Since the notification said that recording is paused, I would have expected to enter the app to a screen that shows me a paused recording, but the notification doesn't correspond
- dismissing the notification was problematic. Given the contradicting context, I don't know what to say.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.6
Android/iOS version: Android 9
Device model:  SM-G965F
Crash-Logs: N/A
```

**Comment by opl-** [comment] 2024-08-28 23:12
I can also very reliably reproduce this issue on v4.8.6 480603.

Saving a trip recording with any points results in the notification becoming stuck saying "Paused", and being impossible to dismiss. Importantly, pressing on the "REC" trip recording widget brings up the bottom panel which sometimes *also* claims the trip recording is on pause, despite me having just finished it, and the track already being saved. If I press "finish" again on that panel, it gives me the name of the previously saved track.

Trip recording not showing me a panel with the "start" button despite me already pressing "finish" was already a problem at least in an earlier v4.8.x version, frequently leading me to question whether I already finished recording my track, or if I'm about to delete all of it by choosing to stop it without saving to avoid creating garbage tracks.

**Comment by scaidermern** [comment] 2024-08-29 07:05
Duplicate of #20536

@vshcherb This is now at least the third duplicate. Looks like this annoys a lot of people. How about a new minor release with this fix?

**Comment by vshcherb** [comment] 2024-09-02 15:12
At least we need to backport to 4.8 branch... and probably rerelease with Android auto fixes as well.

**Comment by vshcherb** [comment] 2024-09-04 09:34
Unfortunately that code has too many dependencies, so we decided to move forward with 4.9 beta this week.

**Closed by vshcherb** 2024-09-04 09:34 UTC
