### ISSUE TITLE
Flooded: South Africa

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6357] opened 2018-12-12 13:33 UTC
![image](https://user-images.githubusercontent.com/40493090/49872908-2b62b600-fe23-11e8-9089-ee6a6b50d97d.png)
 Android 7, Nexus, map is updated

**Comment by xmd5a2** [comment] 2019-02-27 14:52
Duplicate of https://github.com/osmandapp/Osmand/issues/6565

**Closed by xmd5a2** 2019-02-27 14:52 UTC
