### ISSUE TITLE
Show keys and tags about a highway by long-pressing for detail when browsing map to aid colorblind users

### ISSUE THREAD

**Issue by Busterama452** [osmandapp/OsmAnd#11056] opened 2021-03-02 16:58 UTC
As a user of OSMAND planning my travels and visually exploring the map for alternative routes, I need a way to be able to read the detailed condition and type of highway shown on the map without having to memorize a map style or be able to recognize colors so that I can make a decision as to which highway is best suited for my mode of transport.  

It would be awesome when I long press on any highway (in the OSM definition of highway) and chose to see the details, the card that opens up should show the tags and keys associated with that highway.

Keys of particular interest to read in text form would be.

- highway (Path, Track, Secondary, Residential, Unclassified, etc...)
- Tracktype
- Surface
- MTB Scale
- Smoothness
- All of the  access keys (access, motor_vehicle, horse, bicycle, etc...)
- Tiger:reviewed

Using the visual indicators in the rendering can be difficult and not convey all the desired information about the highway.

1. If you're color-blind, you're missing a significant amount of information by having to rely on the rendering.
2. Memorizing all of the styles in the legend is a pain unless you're working with them frequently.  There's a potential to make a pretty annoying mistake.
3. Not all of the tags are represented in rendering.   

Some of the questions I want to answer with this.

- Is that residential road cutting across the desert real, or is it a tiger import error?
- Is this track going over there really loose materials and not very well defined?
- What kind of vehicles are permitted on this highway?
- Am I allowed to access this highway?  Do I need a permit, is it private?
- Is this line a service road, driveway or alley?
- Has someone reviewed this tiger imported road so that I can trust it?
- How smooth is this path?   Will my bicycle handle it?
- How smooth is this track?  Do I need an ATV or can my Subaru make it?

**Comment by letypequividelespoubelles** [comment] 2021-03-03 06:52
Showing keys and tags by long pressing is interesting, not just for highway, but for all element (walking trail, ski path, polygons,  etc. ..)

**Comment by jojojones** [comment] 2021-03-21 12:10
+1

**Comment by tobiasBora** [comment] 2021-09-03 11:03
I'd be really interested by this feature, also because I can't see the differences in the bike lanes legend (shared with a bus, opposite to the street...), they all look the same to me... Also, it could be great to display advanced keys that are not visible in the legend, like minimum height for a vehicle to pass...

Right now, the method I'm using is to share the point position (method `geo:`) and open in the open software Vespucci (designed to edit maps on the phone directly)... but it's not very comfortable.

**Comment by cmoffroad** [comment] 2021-09-08 02:47
+1

OsmAnd is one of the rare apps that renders dynamically OSM data hence such a feature would be technically feasible and very valuable for OSM contributors.

One technical limitation to be aware of for users is that some of the original OSM tags may not be available since they are converted into potentially custom tags during the OBF creation process (have look at rendering_types.xml in OsmAnd-resources repository).

How could this UI feature look like:
- having a custom boolean option to enable this feature (e.g. Developer options, default false) 
- opening a dialog on any visual object with a long tap
- a toolbar with
  - the ID of the object as title 
  - icon buttons to jump to the original OSM object in view and edit mode.
  - X button to close popup
- a scrollable table containing tag-value pairs of the OBF content for this object
    - ordered by tag name ascending
    - with an icon indicating if the tag is custom or original (notosm="true")

**Comment by NotSoImportant** [comment] 2021-12-31 00:11
Related to https://github.com/osmandapp/OsmAnd/issues/2232

**Comment by Busterama452** [comment] 2023-09-27 17:50
Can we get an "Accessibility" tag added to this request? 

Under the EU accessibility act, "...goods and services should be designed in a way that allows them to be used by everyone, regardless of their particular difficulty...", and included in the list of disabilities is "...**color-blindness**, poor vision or complete blindness."

**Comment by dmpr0** [comment] 2024-01-23 11:26
Duplicate of https://github.com/osmandapp/OsmAnd/issues/2232

**Closed by dmpr0** 2024-01-23 11:26 UTC
Labels: Nice to Have
