### ISSUE TITLE
Route analysis marker stuck on map

### ISSUE THREAD

**Issue by kevinmcmurtrie** [osmandapp/OsmAnd#20037] opened 2024-06-09 06:03 UTC
### Description

The on-screen marker for the position of a route analysis remains stuck on the screen until the app is restarted.

### Steps to reproduce

1. Configure navigation to show elevation.
2. Start navigation.
3. Click on the elevation map. A blue marker dot shows the correlating position along the route.
4. Cancel navigation.

### Actual result

The blue marker dot remains on the screen until the app is restarted.

### Expected result

Blue marker dot goes away when route analysis is done.

### Your Environment (required)

Device : ASUS_AI2401
Brand : asus
Manufacturer : asus
Model : ASUS_AI2401_E
Product : WW_AI2401
Build : UKQ1.231003.002.WW_Phone-34.1420.1420.387-0 release-keys
Version : 14
App Version : OsmAnd+
Apk Version : 4.7.17 4717

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/50348022/616f490f-578a-4a71-9658-fb40fd3687ed"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/50348022/2d3e1797-0b10-4625-a7e6-cf0e185959fc"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by kevinmcmurtrie** [comment] 2024-06-09 06:05
![Screenshot_20240608-230133](https://github.com/osmandapp/OsmAnd/assets/50348022/612aff4d-b810-4677-ab90-6b83e91bf122)
![Screenshot_20240608-230143](https://github.com/osmandapp/OsmAnd/assets/50348022/404caf1e-c283-4962-8f56-8536bc001128)

**Comment by kevinmcmurtrie** [comment] 2024-06-09 06:09
![Screenshot_20240608-230133](https://github.com/osmandapp/OsmAnd/assets/50348022/616f490f-578a-4a71-9658-fb40fd3687ed)
![Screenshot_20240608-230143](https://github.com/osmandapp/OsmAnd/assets/50348022/2d3e1797-0b10-4625-a7e6-cf0e185959fc)

**Comment by yuriiurshuliak** [comment] 2024-06-10 09:42
Duplicate of # https://github.com/osmandapp/OsmAnd/issues/19936

**Closed** 2024-06-10 10:27 UTC
