### ISSUE TITLE
improve the app

### ISSUE THREAD

**Issue by FabioTetsuo** [osmandapp/OsmAnd#18922] opened 2024-01-16 17:58 UTC
### Describe the idea (required)

The GPS could facilitate route changes just by clicking on the desired route. The destination and origin points would not change, but the route between them would. And another improvement that is using the voice to create the frist route.

### Tell us about the expected behaviour (required)

When entering the destination, the route is created between A and B. If there is another route to be used, the user clicks on the map and only the route changes.

### Tell us about alternatives you've considered (required)

This is used a lot on Google Maps.

**Comment by mikehgentry** [comment] 2024-01-16 18:14
#1249

#18879

**Comment by yuriiurshuliak** [comment] 2024-01-17 09:14
Duplicate of https://github.com/osmandapp/OsmAnd/issues/1294

**Closed** 2024-01-18 14:46 UTC
