### ISSUE TITLE
Bike routing in OsmAnd~ 4.8.3 no longer works

### ISSUE THREAD

**Issue by wolfwehl** [osmandapp/OsmAnd#20492] opened 2024-08-04 15:53 UTC
### Description

While planning routes in OsmAnd~ 4.7.17 does not cause any problems, routing in OsmAnd~ 4.8.3 practically no longer works at all for the "Bike" type. I have not yet noticed any errors with the "Car" and "Pedestrian" types.

### Steps to reproduce

When entering locations that are close together, it takes an extremely long time for **OsmAnd~ 4.8.3** to find a bike route for the section. With version 4.7.17 this takes less than a second.

### Actual result

Unacceptable waiting time

### Expected result

No waiting time

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.3
Android/iOS version: 14
Device model: Samsung Galaxy A53 5G
Crash-Logs: no crash
```

**Comment by yuriiurshuliak** [comment] 2024-08-05 14:21
Duplicate of https://github.com/osmandapp/OsmAnd/issues/20426

**Comment by yuriiurshuliak** [comment] 2024-08-05 14:21
We need more details to reproduce the issue. Provide the exact coordinates of the start and finish points where you encountered the error. Attach a video of the reproduction process. Also, provide an export of your cycling profile settings: Menu → Settings → Import/export → Export to file.
Also, please try updating all maps.

**Closed** 2024-08-05 14:50 UTC
