### ISSUE TITLE
Improve POI selection in search results

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#15243] opened 2022-09-06 20:42 UTC
### Can't tell where my POI is
I enter Decathlon. There are several on the list. The distance is often similar. 

![Screenshot_2022-09-06-22-19-47-731_net osmand plus](https://user-images.githubusercontent.com/27214784/188730655-1187f9b1-9cd7-4284-b03d-285a3dfa6f9f.jpg)

### Describe the solution you'd like
Maybe an expansion with Address (City/Street will usually do - in bigger cities there can be a few same e.g. shops).

### Describe alternatives you've considered

City name next to POI type (Sporting goods in Gliwice, ATM in Berlin).

**Comment by scaidermern** [comment] 2022-09-07 06:33
Duplicate of #2993.

**Closed** 2022-09-16 13:40 UTC
