### ISSUE TITLE
Let users choose fonts

### ISSUE THREAD

**Issue by Vucumpra** [osmandapp/OsmAnd#19938] opened 2024-05-23 14:06 UTC
### Describe the idea (required)

Let users choose fonts by importing MyFontsFamily.ttf

### Tell us about the expected behaviour (required)

In "general Setup"

### Tell us about alternatives you've considered (required)

Alternative is put files.ttf on hardware memory but Android don't let this :(
Another alternative is use semi-condensed font for all osmand.

**Comment by DmitryAlexei** [comment] 2024-05-24 06:32
Partially duplicate of https://github.com/osmandapp/OsmAnd/issues/19123

**Closed** 2024-05-24 15:07 UTC
