### ISSUE TITLE
OsmAnd current-position stops working and position menu does not slide in (sporadic)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#2732] opened 2016-06-20 19:58 UTC
The snap-to-current-position button does not working anymore (although device has GPS fix) and the position menu does no more slide in after clicking any position on the map.

Both issues occur always at the same time sporadically. I experienced it about 10 times after using OsmAnd intensively several days (without reboot) for car and/or pedestrian navigation.

Workaround: Force close OsmAnd.

A memory leak?

Builds: OsmAnd+ 2.3.5 and older
Devices: Samsung Galaxy Note 4 and Huawei Y625

**Comment by vshcherb** [comment] 2016-06-22 23:15
So it sounds that issue doesn't appear at the start, but appears after intensive usage. So we can't call draw a precise path how to reproduce it, if I understood correctly.

**Comment by Norbert80** [comment] 2016-06-22 23:44
Yes it does not appear after a fresh start.

I cannot provide simple steps to reproduce. But I can say that it definitely will happen after time x of intensive routing.

**Comment by sonora** [comment] 2016-06-30 05:53
This sounds like it could be #2643 (a)-(d), which I have already fixed a few weeks ago. (Where-am-I button was equally affected, although I had not mentioned there.)

**Comment by sonora** [comment] 2016-07-04 11:58
I think this may have been fixed by this commit https://github.com/osmandapp/Osmand/commit/e4d546f7bd493ce7750a6e7187969fa315c36d20. If we do not have any reports for any occurrence after that commit, I think we can close this.

**Comment by sonora** [comment] 2016-09-18 11:37
It looks like this was fixed by my commit, I have not heard of any occurrences since.

**Closed by sonora** 2016-09-18 11:37 UTC
Labels: Observed

**Comment by Norbert80** [comment] 2016-09-19 19:44
@sonora: I comfirm that I did not see this bug occurring anymore.
