### ISSUE TITLE
Map is renderd in a wrong way on zoom level 19

### ISSUE THREAD

**Issue by thuryn** [osmandapp/OsmAnd#18121] opened 2023-09-08 10:45 UTC
## Description
When I try to zoom in from some level it works fine until I reach level 19 - then it seams that is on 30 (too close). When I go further, on level 20 is ok again. See attached video.

### How to reproduce
Just tap on + to zoom in to level 19

### Actual result
Wrong rendered map

### Expected result
Correctly rendered map

**Environment**
OsmAnd Version:4.5.10
Android/iOS version: Android 13, EvolutionX 7.9.7
Device model: OnePlus 9 Pro

https://github.com/osmandapp/OsmAnd/assets/11028346/edcad68c-1222-4f2f-983e-23c16f56c2d9

**Comment by scaidermern** [comment] 2023-09-08 11:17
Duplicate of #17764 / #17763 I think.

**Comment by vshcherb** [comment] 2023-09-15 14:09
Yes for 3D enabled issue needs to be fixed

**Closed by vshcherb** 2023-09-15 14:09 UTC
