### ISSUE TITLE
Osm Notes info Display

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1882] opened 2015-11-08 07:57 UTC
I'm unable to see the osmnote infos anymore. When tapping on a note, the streetname and coordination are shown.
Over the context menu I only can close or comment it.
![screenshot_2015-11-08-08-51-06](https://cloud.githubusercontent.com/assets/11144987/11019371/77f4283a-85f6-11e5-9f66-e1ccaaac97dd.png)
![screenshot_2015-11-08-08-51-22](https://cloud.githubusercontent.com/assets/11144987/11019373/812a6086-85f6-11e5-94f4-e80db62411cd.png)

Thanks Simon

**Comment by xmd5a2** [comment] 2015-11-08 11:34
Duplicate of https://github.com/osmandapp/Osmand/issues/1875

**Closed by xmd5a2** 2015-11-08 11:34 UTC
