### ISSUE TITLE
TTS does not restore background music volume properly

### ISSUE THREAD

**Issue by probonopd** [osmandapp/OsmAnd#5837] opened 2018-08-12 13:03 UTC
Tried using this app for cycling, listening to music using VLC. When the TTS is overlaid, the volume of the music is reduced. However, after approximately 15 minutes of using the app, the music volume does not return to normal and the music stays low volume all the time.

Also the fades are all but smooth.

Can l help with debugging Information somehow?
Moto G4, Android 7.0

Or even better, could a simple music player be included in the app, making it possible to set the music and TTS volume separately?

**Comment by probonopd** [comment] 2018-08-12 17:00
With another music player the fading transitions are smooth but otherwise the same bug exists.

**Comment by sonora** [comment] 2018-08-12 20:11
Can you please toggle the Navigation setting 'Pause music' to see if it makes a difference. Overall I have to say I cannot reproduce on any of my test devices, I assume it may be device specific or an issue of the music apps?

**Comment by sonora** [comment] 2021-09-16 05:22
Should be fixed, merged into #12715.

**Closed by sonora** 2021-09-16 05:22 UTC
Labels: Observed
