### ISSUE TITLE
links don't open

### ISSUE THREAD

**Issue by beatnickgr** [osmandapp/OsmAnd#18386] opened 2023-10-19 22:39 UTC
### Description

Openstreetmap.org links don't open the node.

### Steps to reproduce

Open the OsmAnd~ search
paste an openstreetmap link

### Actual result

The search returns 0.00000 0.00000 coordinates
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/17930530/cf80880c-1ff5-46c3-b4ba-6f138e4d1098"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

The search should return the Eiffel tower
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/17930530/58e80406-1a63-4327-905c-969325de7101"  width="300" height="auto"/> </td>
  </tr>
</table>

### Your Environment (required)

OsmAnd~ 4.5.10
LineageOS 20
FairPhone3

**Comment by DmitryAlexei** [comment] 2023-10-20 07:30
OsmAnd~ 4.6.0#885m, released: 2023-10-19
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ef06767b-882e-491b-9d13-bdee75bebadc"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/1538dbbf-8556-451c-8054-239116e0d9b4"  width="300" height="auto"/> </td>
  </tr>
</table>

- Search for OSM way or node returns 0.00000 S 0.00000 W coordinates
- Online search returns NO results

However, I cannot find any information about possibility to search for OSM objects in OsmAnd (see https://osmand.net/docs/user/search/), so it's more like *Nice to have*, rather a bug

**Comment by DmitryAlexei** [comment] 2023-10-20 07:54
I see, that this is rather duplicate of https://github.com/osmandapp/OsmAnd/issues/12202

As of now you can use OSM links from address bar instead. 
For example, for Tour Eiffel that can be https://www.openstreetmap.org/way/5013364#map=19/48.85827/2.29473&layers=N

**Comment by beatnickgr** [comment] 2023-10-20 12:54
Thanks @DmitryAlexei for replicating this bug.
@vshcherb said these links are working for him.

Links created with Organic Maps are working in OsmAnd~
Example https://osm.org/go/x0NdAg0v-?m=

But links of OsmAnd~ don't open in OsmAnd~ as they should. 

Most people receiving these links will have to open them in the web browser, and in my case there's not even a suggestion to open it with OsmAnd~ as they should.

**Comment by DmitryAlexei** [comment] 2023-10-20 13:37
@beatnickgr what is your use case with links?
If you want to share a link to an object between two OsmAnd apps, it's better to use direct link with a pin. Go to POI context menu: tap on an object or long tap on any place on the map > details > coordinates > swipe to the bottom > choose a link starting with **https://osmand.net/map?pin=**
That link automatically opens in OsmAnd or on web map (for more information see https://osmand.net/docs/user/map/map-context-menu#coordinates)
Recently we added support for OSM links with a pin, see https://github.com/osmandapp/OsmAnd/issues/16386. That feature will be available soon. 

and about OSM links. They are needed to check object details on OpenStreetMap, that might be useful for OSM mappers.
@vshcherb mentioned, that regular OSM links (from address bar) can be opened in OsmAnd

**Closed** 2023-10-20 14:08 UTC

**Comment by beatnickgr** [comment] 2023-10-20 14:19
Copying this link from the address bar to OsmAnd~ doesn't work https://www.openstreetmap.org/way/5013364

Copying from address bar only works when the coordinates are in the url which makes the link very long.

The link https://osmand.net/map?pin=48.85827,2.29451#20/48.85827/2.29451 is much longer than https://osm.org/way/5013364 but contains no useful information.

I don't see why only long links should work but not the short ones...

**Comment by vshcherb** [comment] 2023-10-20 14:42
https://github.com/osmandapp/OsmAnd/issues/12202#issuecomment-1772859989 - we don't have enough information to open the maps.
