### ISSUE TITLE
GPX import issue

### ISSUE THREAD

**Issue by Vlad-Sol** [osmandapp/OsmAnd#18086] opened 2023-09-03 15:38 UTC
## Descriptissue
Does not import favourites from gpx file in version 4.5.8 (devoid)
### How to reproduce
Import attached file
### Actual result
No favourites imported
### Expected result
A lot of new favourites after import
**Environment**
OsmAnd Version: 4.5.8
Android/iOS version: Android 10
Device model: GM1900

**Comment by Vlad-Sol** [comment] 2023-09-03 16:11
How to attach gps file here?

**Comment by Sonwon1** [comment] 2023-09-03 16:56
Attach files by dragging & dropping, selecting or pasting them.

Read the bottom of the post box when you make a post.

**Comment by Vlad-Sol** [comment] 2023-09-03 17:31
[iOverlander_Peru.zip](https://github.com/osmandapp/OsmAnd/files/12506661/iOverlander_Peru.zip)
Try to import this gpx, please. 
Older versions handle it without any issue.

**Comment by zipav** [comment] 2023-09-06 07:45
OsmAnd Nightly 4.6.0#729m, released: 2023-09-05

### Steps to reproduce:
- Download .zip file
- Unzip and save the track to the device
- OsmAnd Menu
- My Places
- Tracks
- three dots button in upper right corner (⁝)
- Import

When importing a track into the latest build of OsmAnd Nightly, all Favorites are imported as Checkpoints, they are sorted by category.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/2d713f67-20e0-474d-af5e-21eb886ce13b"  width="300" height="auto"/> </td>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/663e3d0f-cc20-47ec-8959-e6bff24355b6"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Vlad-Sol** [comment] 2023-09-06 23:48
What about favourites import?
Checkpoints are far less useful. Are you going to return possibility of 
favourites import?

-- 

Have a nice day, Vladyslav.

----------------------------------------

6 вер. 2023 р. 02:45:38 zipav ***@***.***>:

**Comment by zipav** [comment] 2023-09-08 10:21
@Vlad-Sol you are right, indeed, if import this track exactly through the steps My Places → Tracks, it is imported only as a track consisting of Waypoints.
If importing a track by opening it in the file manager with OsmAnd, then the dialogue appears "open as GPX" or "open as Favorites", when selecting "open as Favorites" it imports them properly folder by folder into the path: My Places → Favorites

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/33758b1e-36f2-4929-a655-05110e6a59eb"  width="300" height="auto"/> </td>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/4dc53b0c-87e7-4cf4-b20d-44ec311b070c"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment] 2023-09-11 08:49
This is expected behaviour:
-  < wpt > tags from [iOverlander_Peru.zip](https://github.com/osmandapp/OsmAnd/files/12506661/iOverlander_Peru.zip) .gpx file can be imported as *waypoints of a track* or as *favorites* depending on how the import was made.

To import waypoints of a track as favorites:
- use our guide, see https://osmand.net/docs/user/personal/favorites#all-favorites (go to menu > my places > favorites > + > choose your .gpx file) 
- using your file manager tap on a file > choose to open it in OsmAnd > open as favorites

**Comment by tom709** [comment] 2023-09-16 12:35
I agree, gpx import is broken in 4.5.8, in different ways.
1. When I tap My Places, then (+) and select a gpx file, nothing happens.
2. When I share a .gpx file to OsmAnd and import as Favorites, all waypoints appear in the one group called Favorites. I have so many waypoints, I need to structure them in groups. So I can rename Favorites to something else, and do the same with another gpx file. When I then tap on a waypoint on the map, 3 entries show at the bottom of the screen: the same waypoint name once in Favorites (where it is no more because I renamed Favorites), in the group created by the rename operation, and a third time with the file name of the gpx that I imported with a previous version of OsmAnd. The latter is not to be found anywhere in OsmAnd any more because I deleted it prior to starting the import; it is just referenced when I tap a waypoint.

Guys, this is completely broken just when I need it. One should think about whether this app is not too complex, both for the user and also for the developers to maintain it.

**Comment by Sonwon1** [comment] 2023-09-16 15:26
I would freeze new features until all existing bugs are fixed. And then clean up the menus to make it less confusing.

**Comment by DmitryAlexei** [comment] 2023-09-17 20:14
@tom709 Feel free to download latest build from Google play (you can also join beta test) and see if these bugs are present there.

**Comment by vshcherb** [comment] 2023-11-23 12:03
Closed as not reproduced, as a workaround so far you can always import as GPX track and later convert to Favorites folder

**Closed** 2023-11-23 12:02 UTC
