### ISSUE TITLE
Introduce map rotation North fixed / Less sensitive calculate map rotation

### ISSUE THREAD

**Issue by billmaurer** [osmandapp/OsmAnd#17086] opened 2023-04-29 15:19 UTC
It is very easy to accidentally alter the map orientation by many different gestures on the screen. 

This could be done by adding a checkbox "Lock map to this orientation" to the Map Orientation dialog.

The dialog can be opened in Profile - General settings - Map orientation or by long pressing the Map Orientation button on the top left of the map display. 

My preference is to keep the map orientation to always point north while in hiking mode.

**Comment by Zirochkabila** [comment] 2023-04-29 18:15
Related to https://github.com/osmandapp/OsmAnd/issues/7282

**Comment by billmaurer** [comment] 2023-04-29 21:10
Not true. This has nothing to do with the compass or bearing mode or anything like that.

The gesture for zooming in and out is very similar to the gesture for rotating the map. If you let your fingers drift even slightly doing the zoom gesture the map will flip out of the orientation mode you had previously set and into rotation mode. This is highly undesirable.

**Comment by Nine-Tailed** [comment] 2023-04-29 21:19
https://github.com/osmandapp/OsmAnd/discussions/16836

**Comment by billmaurer** [comment] 2023-04-29 22:15
Yes, this is definitely the same as #16836.

So I'm not the first to be annoyed by this! :-)

**Comment by arncor** [comment] 2023-04-29 22:16
I (and a few friends too) use osmand a lot and we all want a "north up" only view. We almost never need manual rotation. 

In our opinion the low threshold is very very annoying.

**Comment by Zirochkabila** [comment] 2023-04-30 07:19
@billmaurer in item **4. A large button for locking/unlocking the maps turns** (7282) - this is exactly the feature you are asking about, isn't it?
@Nine-Tailed Regarding the zoom change thing - in the latest nightly version it works well, I think (video attached)
Regarding the map tilting - I agree, it's probably worth fixing, @alex-osm  - comment with video added https://github.com/osmandapp/OsmAnd/discussions/16836#discussioncomment-5764948

OsmAnd~ 4.5.0#35865m, Released: 2023-04-29

https://user-images.githubusercontent.com/104760013/235340759-8e7ed62a-4c72-40d1-9bc0-db6367ad9def.mp4

**Comment by H--W** [comment] 2023-04-30 22:38
I would also like to have this feature. Some underpowered devices are only usable in continuous north up orientation. Also many navigators expect a map to follow a paper map/chart paradigm. I would be willing to edit a text config file to get this feature. Perhaps this should be a profile setting? Rgds, -H- ver 4.4.7 Android

**Comment by sonora** [comment] 2023-05-01 06:49
Folks, I think it's how I've said all along: The map orientation mode "_North is up (fixed)_" should be exactly what its name promises: _North should be up_,  and it must be reasonably _fixed_.  :wink:

That's how we've had it for 10 years without complaints. The flaw we recently introduced is that by a rather slight two-finger twist of the map, as it sometimes accidentally happens during a pinch zoom gesture, we now slip from "_North is up (fixed)_" to map orientation mode "_Manual rotation_".  There the map is statically rotated vs. the device orientation, a comparatively rare use for everyday operation(!)

I see 2 possible solutions:
-(A) We return for the "_North is up (fixed)_" mode  to the previous app behavior where we had a 30 degetee guard (or trigger)  interval, When initially in "_Northis is up(fixed)_" mode, only when twisting the map beyond 30 degrees, from north the app interpreted this as the trigger to now switch to  the "_Manual rotation_" mode (where map twisting is repected immediately without having to overcome a trigger). Or:
-(B) Use no trigger at all. Instead expect users who want to leave the "_North is ip_" map mode to explicitly do this via the "Configure map" settings (or by tapping the compass icon. if configured to be visible).

**Comment by sonora** [comment] 2023-05-11 17:43
> Now I see how development happens, first we rename option and then we constitute that option should work the same as name suggested ;-)

Pardon my little trick to nudge development in the right direction ... :wink::wink::wink: But as you can see, there's popular demand!  :wink:

Actually, what started the problems was not adding "_(fixed)_" in the string to clarify there is no rotation in play, it was removing the threshold which changed the formerly pretty "fixed" behavior to now allowing accidental changes: https://github.com/osmandapp/OsmAnd/discussions/16836#discussion-5018378  :wink:

**Comment by vshcherb** [comment] 2023-05-12 08:46
The issue is that it doesn't matter whether we fix rotation further or threshold there is clearly demand to not allow rotate map by any accidental click on compass or any harsh movement, so North up (fixed) makes sense but also make sense  Movement direction (fixed)

**Comment by rouelibre1** [comment] 2023-05-15 11:12
I just upgraded to the latest version and I am now impacted by this "fixed north" that isn't fixed...
I had heard complaints about it before and didn't understand why it was such a big deal.
Now I get it : this is incredibly frustrating... I like the previous behviour where it was already possible to override the "fixed" orientation, but there was no (or little) risk of doing so unintentionally.

Now it's just impossible to not override the "fixed" orientation by zooming in/out with two fingers. Which deafeats the whole purpose of this "fixed" option.

I'm considering rollback until this get fixed (hopefully) in a future version.

**Comment by scaidermern** [comment] 2023-05-15 11:18
I'm still wondering why this bug(!) has never been fixed in version 4.4.

**Comment by mnalis** [comment] 2023-05-16 00:51
> I'm still wondering why this bug(!) has never been fixed in version 4.4.

Is it fixed in some other version? Reading the user experiences with that change, there is no way I'll be upgrading from F-droid version `4.3.12` until there is confirmation that is either reverted, or at least configurable so old behaviour can be selected by the user.  

> Lock provided in settings (doesn't matter north is up or not)

While I do rotate map often, I also want `North is up` (when selected) to do exactly that, and not to be disturbed by slightest touch (as I use that one often too, depending on where I am and what I am doing). **Previous legacy behaviour was just fine with me, allowing both options easily**. 

If new (4.5+?) proposed solution would require me to go to options and enable/disable some `rotation lock` preference (if I'm understanding that correctly?), that would be horrible user experience to me, as I'd basically have to give up one of the options previously available (there is no way I'd be going into preferences all the time to change it on/off over and over again)

Does someone know if simply setting `ANGLE_THRESHOLD` back to `30` from new ultra-sensitive `5` would fix the issue (by "fix" I mean revert to legacy pre-4.4 behaviour)?

And if it would, **could we just have an advanced preference which allows user to set integer for that `ANGLE_THRESHOLD`?** That would seem to me very easy to implement, and allow the user to choose their side in this highly polarized decision. (or alternatively we could have that preference as boolean checkbox saying `Ultra-sensitive rotation` which can be set to `on` (setting new `ANGLE_THRESHOLD=5`) or `off` (setting legacy  `ANGLE_THRESHOLD=30`)?

**Comment by scaidermern** [comment] 2023-05-16 04:25
> > I'm still wondering why this bug(!) has never been fixed in version 4.4.
> 
> Is it fixed in some other version?

Sort of. In version 4.5 the threshold is higher (the same again as in version 4.3?).

**Comment by sonora** [comment] 2023-05-16 08:07
This PR https://github.com/osmandapp/OsmAnd/pull/17197 would revert to the old guarded  behavior for "North is up" mode while not affecting any other modes.

**Comment by sonora** [comment] 2023-05-17 06:57
PS - Wording: So do you think we should rename the two "fixed" modes to just "North is up" and "Manually rotated"? I have no preference, just thought that (fixed) would make it a bit clearer to separate these from the 2 dynamic modes.

**Comment by mnalis** [comment] 2023-05-19 21:32
> This PR https://github.com/osmandapp/OsmAnd/pull/17197 would revert to the old guarded behavior for "North is up" mode while not affecting any other modes.

Thanks, it seems to work for me. If other people are willing to try it, I've build [debug .apk](https://github.com/mnalis/OsmAnd/actions/runs/5020936569) so feel free to try it out and give your experiences. 

---

Of course people should not trust other random people on the .net offering them `.apk` files to run :smile:, so I'm glad to announce my PR https://github.com/osmandapp/OsmAnd/pull/17222 (which allows people without Android development environment to easily get compiled `.apk` of OsmAnd by making GitHub actions do it for them) has been merged into `master` so is available to all. 

If you'd prefer that method, fork this repo, create new branch, apply the PR to it, and then _in your fork_ click on `Actions` / `Build debug apk` / `Run workflow` and choose your branch where you applied the PR. Wait about 30 minutes, and there will be `.apk` ready for you.

**Comment by vshcherb** [comment] 2023-05-25 12:41
One decision to simplify situation is to make initial movement of rotation if it's not made then rotation won't be started even if fingers will be moving.

**Comment by mnalis** [comment] 2023-05-26 12:34
Thanks @vshcherb, disabling rotation for the whole length or the gesture if initial gesture looked like zoom should probably help (at least somewhat!) 

Please mention this issue when that lands in some PR or `master`, so interested parties can try it out and give feedback.

**Comment by Boothy99** [comment] 2023-05-30 23:46
> 4.5.1 beta is out and ready to upgrade from 4.4 - threshold is higher

Thanks Victor. Just updated Beta to 4.5.1. 
Much better angle before any rotation initiates ... OR ... rotate immediately (intentionally) and no hesitation in rotating. I for one like it so far. 

Tried a few "clumsy" zooms and no unintentional tilting until I force it to, by using a good / reasonable angle of rotation of 2 fingers.
👍👌

**Comment by Nine-Tailed** [comment] 2023-05-31 12:43
add rotation sensitivity setting please

**Comment by GallusMax** [comment] 2023-08-09 06:16
> One decision to simplify situation is to make initial movement of rotation if it's not made then rotation won't be started even if fingers will be moving.

Oops - no! Imagine Osmand being mounted on a bike. Try a two-finger-touch while riding. You will never ever be sure if the movement after first touch will be a "zoom" or a "rotate".

**Comment by milan11** [comment] 2023-08-10 08:00
I am a user of OsmAnd and I would prefer to be able to completely unconditionally disable the rotation gesture. The latest improvements maybe made the situation better, but the accidental rotation still happens for me.

It is a great annoyance to build a habit to constantly check whether the map was accidentally rotated or not.

But to be fair, e.g. Google Maps has this problem, too.

I made a pull request with a separate setting added allowing to disable the rotation using gesture per-profile: #17884

![screenshot](https://github.com/osmandapp/OsmAnd/assets/428839/6e25a44f-20de-4a3b-bf24-db93bb9513ca)

Until this is solved, I will maybe use the "double tap plus drag" gesture to zoom as a workaround to prevent accidental rotation.

**Comment by vshcherb** [comment] 2023-08-10 12:23
**Summary as of 10 August 2023**.
- Algorithm changes improved situation a lot but there are still fluctuations as you try to zoom too fast
- During our stress tests we didn't find any perfect algorithm that would allow any random zoom in gesture recognized as not turn. So after 20-50 quick zooms there is still a turn
- OsmAnd algorithm could be improved for recognizing quick zooms but not by creating a significant friction for turn 

**To do**
- Introduce a setting to disable rotation per profile (it could be a lock of a certain angle or a lock only to a north up). 
- Think if it's possible to unlock it only via settings or some double tap on the map

**Comment by sonora** [comment] 2023-08-10 12:53
Thanks for revisiting, Victor!

Repeating myself, but I still think an **initial twist threshold** may be the most intuitive solution, rather than any more or less hidden settings or double-taps. The threshold should of course
- only apply initially,
- and only if the user is in "North is up" mode - I think that's the only situation we need to safeguard against accidental change
 
My 5 cents.  :wink:

**Comment by ploink** [comment] 2023-08-10 13:07
Osmand is one of the greatest apps I use, but the only reason why I never recommend it to non-geek users is that it is overly complicated and has a myrad of settings. I know I could never explain to my mother in law why you can accidentaly rotate a map that is supposed to be fixed north up. She would phone me on a daily basis for support.

I see now how that evolves if issues like this waste a lot of people's time and energy. Taking 5 months to discuss a feature for rotating a fixed map that no one actually seems to want or need while annoying a crowd, then finally settling for "add another setting that Ploink's MIL won't understand". 
I suggest following the KISS guidelines and keep north up with a giant block of concrete unless one selects the rotation mode from the compass icon or settings menu.That I could explain to her.

**Comment by Boothy99** [comment] 2023-08-10 13:08
For what it's worth, I think a setting to disable any rotation (globally or profile specific) would be a great move to keep everyone happy. A (generous?) twist threshold in "North is up" mode as sonora highlights would also be appreciated.

**Comment by vshcherb** [comment] 2023-08-10 13:10
> @ploink Osmand is one of the greatest apps I use, but the only reason why I never recommend it to non-geek users is that it is overly complicated and has a myrad of settings. I know I could never explain to my mother in law why you can accidentaly rotate a map that is supposed to be fixed north up. She would phone me on a daily basis for support.


That's not true all apps have accidental map rotation and I didn't see any solution except **automatic rotation to north up** once app is restarted. That solution is no go for our users (as I see)

**Comment by scaidermern** [comment] 2023-08-10 13:14
> That's not true all apps have accidental map rotation

Can you name an app that has a mode called "North is up (fixed)" and still allows to rotate the map by accident?

Seriously, so much time and effort to discuss something that has a very simple solution. Make "North is up (fixed)" a fixed rotation mode and a lot of users will be happy.

**Comment by vshcherb** [comment] 2023-08-10 13:21
I think I should start cleaning up messages to avoid long issues and create parallel discussion where flood can go
@scaidermern  where do you see North is fixed?

<img width="20%" src="https://github.com/osmandapp/OsmAnd/assets/1042025/57e6f8c7-9e46-4b33-9bbb-c6dcc20ce1b8" />

**Comment by sonora** [comment] 2023-08-10 13:22
I supply all test users in my surroundings, novices and experts alike, with a special build which has an _initial_ 30 degree twist guard (could be increased to 45, does not matter) before any rotation from north would take effect.

After the threshold has been  surmounted, or if the map is twisted from North anyway, changes are immediate.

Nobody has yet reported an issue with this concept... 😉

**Comment by sonora** [comment] 2023-08-10 17:55
Regarding

> I think I should start cleaning up messages to avoid long issues and create parallel discussion where flood can go

Here's where that was tried on this very topic: https://github.com/osmandapp/OsmAnd/discussions/16836. Some floods are serious enough to come back... 😉 😉 😉

**Comment by osmonoid** [comment] 2023-08-12 19:40
@vshcherb
> [...] To do [...] Introduce a setting to disable rotation [...] it could be a lock of a certain angle [...]

@sonora
> [...] initial twist threshold may be the most intuitive solution [...]

@Boothy99
> [...] A (generous?) twist threshold in "North is up" mode as sonora highlights [...]

According to statements cited above, the best compromise of all suggestions / possible solutions for this problem is this "initial unlocking twist gesture" which will hopefully satisfy "95%" of the users:
- those who want to not accidentally rotate the map, simply assign a wrist-/finger-breaking high threshold 🤕😉
- those who want to "let's do the twist!", assign a jiggly-wiggly low threshold 🍮😉
- those who complain about novice users not being aware of that threshold could even be satisfied by a (permanently) dismissable help/info overlay upon rotating the first time(s) after installation which briefly informs them in a few words about the twist/rotation gesture threshold config/feature so that they are aware about that

(Please forgive my childish wording/jokes and the emojis, but I had to try to bring a bit more "fun" into this serious topic.)

So at least the 3 of you (but most importantly our dear developer @vshcherb) are mainly on the same track after all! 👍

**Comment by elf128** [comment] 2023-08-19 01:22
Why play with threshold values, when we can just disable rotation completely. There's two modes ( aside from auto-rotating cases ), there for two behaviors and two target audience.
Those who want to rotate map, set it to manual rotation and do whatever they want, never leaving that mode. Those people need compass button to keep track of their rotations. All thresholds has to be applied to this mode and only to this mode. Pressing Compass mode should reset map rotation, but keep it in "manual rotation" mode. 

Those who  don't rotate map, set it to North Up, expecting it's always north up. This is second use case. In this mode it should be impossible to rotate map. Those people don't need compass button, since North is always up. 
Right Now, people from second group unable to remove compass button cause you need it ONLY to check whether the map has been accidentally rotated.

Essentially, right now map is in Manual Rotate all the time, regardless of what the indicator says. Because you can always rotate the map and meaning of setting it to "North Up" is to **_temporarily_** reset map rotation. And I'm not saying someone broke it. It was always like this, it's just become much more noticeable with recent threshold reduction. 
But since we're talking about possible improvements, why not finally fix it?

**Comment by scaidermern** [comment] 2023-08-19 05:44
> But since we're talking about possible improvements, why not finally fix it?

Milestone 4.6 has been set, so let's wait and hope for the best.

**Comment by osmandlover** [comment] 2023-08-20 17:15
Thanks! I also reported this bug over here: https://github.com/osmandapp/OsmAnd/issues/17979

I just want to add that this doesn't only happen when zooming in and out with a pinch, sometime if you brush against the screen or something the map rotates. It happens sometimes that I take my telephone out of my pocket and the map is rotate. Grr!!

I never ever ever want the map rotated nor tilted. Not ever. Compass mode north fixed pointing up means north fixed pointing up. I want to permanently disable that function and I would be OK with editing the code or changing a config file something to achieve that. I have compiled the app from source. Is there a known workaround that I can do? Or if I could just fix this annoying bug properly can I submit a pull request?

I understand the idea to make the map behave intuitively by conceptually always having the touch points attached to the map. But, rotation and tilt is a feature that many people (most people?) don't want nor need. So this method is prioritizing the conceptual model over the usability. And it has such a simple fix - just make the "fixed" mode behave as the name indicates!

The "increase the rotation threshold" fix is a silly way to fix it. Because it breaks the conceptual "fix map to fingers" model, AND it breaks the idea behind having different compass modes for do the exact same thing (north fixed up and manual rotate). If you want to "force" users to have rotation active then may as well just take away the fixed north mode - what's the point in having both modes? 

I was very disappointed that this feature didn't work as I expected as the release notes for v4.4.7 suggested that "map fixed to north" mode would solve this problem that has been annoying me fore years!

just by the way. I love osmand and i dont want to make it sound like i am not greatful for an amazing app. this is just one devil of an annoying bug!!

**Comment by osmandlover** [comment] 2023-08-20 19:24
Submitted PR https://github.com/osmandapp/OsmAnd/pull/17981 which solves this issue for me.

**Comment by maltfield** [comment] 2023-12-29 21:19
Can someone please clarify which version of OSMAnd introduced this issue, and which version we should downgrade-to on F-Droid to fix it?

**Comment by sonora** [comment] 2023-12-30 00:49
@maltfield Going back to my original post about this https://github.com/osmandapp/OsmAnd/discussions/16836, it seems this was introduced in https://github.com/osmandapp/OsmAnd/pull/16746/commits, which would mean that probably 4.3.12 may have been the last official release without the issue.

**Comment by maltfield** [comment] 2024-01-20 22:51
Yay! In what version of OsmAnd is this fixed?

**Comment by elf128** [comment] 2024-01-21 14:21
Wait. The fix says it disable rotation only if zoom has been started. Which is not what this topic is about.

This does not disable rotation unconditionally. If you have random touches and first move recognised as rotation, roration will happen.

Jan 20, 2024 16:32:30 Vitaliy ***@***.***>:

**Comment by scaidermern** [comment] 2024-01-22 10:04
Sounds like only the second part got fixed. The first part (introduce map rotation North fixed) is still open? :thinking:

**Comment by dmpr0** [comment] 2024-01-22 14:54
## Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c1a77727-fba2-47a3-ba80-c083cfbe63f9"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/6534653c-5646-44d3-94c8-f41d6cd2baec"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   





- [ ] Map rotation works 1 of 4 times

**Comment by sonora** [comment] 2024-01-23 16:41
From my testing with a few users, also novice ones: Yes, this now helps in many cases where users happen to started a small zoom operation before any unintended twist. But there are still some who manage to unintentionally twist before zooming, and find their map rotated (there is very little threshold) without intent, often not even noticing it.

So I continue to vote for a _significant initial twist threshold_. We could of course
- chose to use the threshold solely if the starting map rotation is zero (i.e. map points North), so users would then have to overcome the threshold (and never leave "North is up" if they don't),
- while if the map is already rotated, we can drop the threshold, assuming that that only occurs for users who intentionally already have rotated the map.

PS: Please note that the coding is not clean, should be fixed in a final version: https://github.com/osmandapp/OsmAnd/commit/4d8e2088460f7f2c5385f8c892f81ddcb9504a42#commitcomment-137584766

**Closed** 2024-01-25 16:43 UTC
Labels: and-ui, ios-migrate

**Comment by realityexists** [comment] 2024-04-07 18:41
In what version is this supposed to be fixed? I installed 4.6.12 from F-droid and it's still the same - still incredibly annoying!

Look, I don't want workarounds to make the problem _less likely_. Just give me a setting to make it _impossible_ to orient the map any way other than north being up, except by changing that setting (deep in the settings screens somewhere, not on the map screen). The current "North is up" setting sounds like it should do exactly that, but it doesn't!

I just want north to be up always. _Always._ **Always!** No matter what. It's really _that_ simple!

**Comment by realityexists** [comment] 2024-04-07 18:42
> it seems this was introduced in https://github.com/osmandapp/OsmAnd/pull/16746/commits, which would mean that probably 4.3.12 may have been the last official release without the issue.

Is it still possible to download the APK of this verison somewhere? It's not on F-droid anymore. :(

**Comment by mahdi1234** [comment] 2024-04-07 18:45
@realityexists here https://apt.izzysoft.de/fdroid/index/apk/net.osmand.plus?repo=archive but that's not really solution. I would also wish for this "very simple toggle" to be present in most recent version.

**Comment by realityexists** [comment] 2024-04-07 19:09
Thanks! I realised I just have to select the "F-droid archive" repository to install 4.3.12 using the F-droid client.
Even in that version the map can be rotated when "north is up" is selected, but it seems to take more rotation, so it's an improvement.

**Comment by maltfield** [comment] 2024-04-07 21:16
> I just want north to be up always. *Always.* **Always!** No matter what. It's really *that* simple!

I also don't understand why this is so hard. Is there some technical issue? Or are devs not understanding users expectations here?

**Comment by XandrexOSM** [comment] 2024-04-07 22:36
> > I just want north to be up always. _Always._ **Always!** No matter what. It's really _that_ simple!
> 
> I also don't understand why this is so hard. Is there some technical issue? Or are devs not understanding users expectations here?

Hello @maltfield ,

there is no technical issue. the behaviour is the one intended by the OsmAnd team.
They perfectly understand the expectations expressed by several users here, but they simply do not agree. All arguments have already been opposed, and they are not enough. 

As stated by @Nine-Tailed in april 2023 above, please check conversation https://github.com/osmandapp/OsmAnd/discussions/16836 .

**Comment by realityexists** [comment] 2024-04-08 17:24
> the behaviour is the one intended by the OsmAnd team. They perfectly understand the expectations expressed by several users here, but they simply do not agree. All arguments have already been opposed, and they are not enough.
> 
> As stated by @Nine-Tailed in april 2023 above, please check conversation #16836 .

Thanks for the link, @XandrexOSM. I've read the top-level comments in that (very long) discussion, but it's unclear to me what exactly the maintainers do not agree about. The closest I could find is this comment by vshcherb:

> Fingers should stay intact with map points when they where pressed.

and then you (XandrexOSM) elaborating on that:

> when you put your two fingers on the map, they are on point A and point B of the map, and whatever you do with those two fingers, the principle says the fingers should always be at points A and B. Meaning you can always rotate & zoom, or zoom & rotate, depending on your swipe movements with each finger.

Is this what you're referring to when you say that the maintainers simply do not agree? 

I can totally see how the behavior you're talking about (fingers stay on the same map points) can be desirable to some users! However, there are clearly other users to whom it's undesirable, as you yourself acknowledged. Between this issue and the linked thread, I count no fewer than 20 (!!) users who have specifically requested a "north is always up" mode:

_In this issue:_

1. billmaurer
1. arncor
1. H--W
1. sonora
1. rouelibre1
1. mnalis
1. milan11
1. ploink
1. scaidermern
1. elf128
1. osmandlover (even provided a PR!)
1. realityexists

_In the discussion thread you linked:_

1. sonora (already counted from this issue)
1. pebogufi
1. Boothy99
1. Zyolix
1. alberto4github
1. bettrr01
1. asier70
1. navid-zamani
1. BoswachterMarc

Isn't this exactly what settings are for - to enable different users to have different behavior? Adding either another mode for this or a "movement threshold setting" (suggested above by mnalis) or even another setting entirely (buried deep somewhere, if you must) would make both groups happy, wouldn't it?

It's arguable what _the average user_ would expect when they select a mode named "North is up", but that's not the argument I'd like to focus on. I don't care what the mode is called. I don't care how well it's hidden. I don't care if I have to download a hacked binary and root my phone and edit a config file to get the "north is really-truly-always up" mode, as long as I can set it once and for all and have it stay like this. Please, just add a setting... any kind of setting!

**Comment by vshcherb** [comment] 2024-04-18 19:21
As 4.7.9 is out, there is a setting (until we have better solution for UI design) to have north fixed. It's in General Settings.

Thank you all for discussion, though this issue will remain blocked as too many off-topic. In case it doesn't work, you can open new issue
