### ISSUE TITLE
Some issues regarding our Track Analysis UI

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#6943] opened 2019-05-15 05:24 UTC
Confirmed for change:
 - [ ] **(6)** Create and option **Rename** in the overflow menu on the track analysis dialog (in addition to the existing "Edit" and "Delete"). (Also in light of #5033.)

 - [ ] **(7)** In addition, maybe also an an option **"Edit description"** to facilitate changing the content of the GPX `<metadata>` tag. (#6942).

 - [ ] **(1)** [Smaller issue] The map preview above the track analysis dialog correctly previews  when the track color is changed, but does not indicate the visibility of the split interval markers (hence some users are confused what the setting does.)

Go to MyPlaces / Tracks, tap on any track:

 - [X] **(2)** The "Color" setting next to "Split interval" acts on the split interval **markers** only (which are invisible here, see (1) ). But changing the "Color" here falsely changes the **track** color on the map preview above it (but the track's original color will finally be used on the map!): **_EDIT: Seems fixed._**

 - [X] **(3)** The "Color" setting only saves any changes to it when "Select on map" is on. But it does save changes then even if "Split Interval" is set to "None", this is inconsistent. I suggest we always accept changes (or we gray out the setting as long as not both "Show on map" is set to on **and** a Split interval is selected). **_EDIT: Seems fixed._**

 - [X] **(4)** The split interval markers drawn on the map (but missing in the preview) always have **white** border and caption color, which is hard to see on half of the available colors. Should be black for all bright colors. _**EDIT: Fixed with**_ https://github.com/osmandapp/Osmand/commit/e771eade6d9d5b94b3ed0b900a1eb831af8cf35f

 - [ ] **(5)** The split markers on the map are not tappable any more? We used to have this, tapping any showed you the details of the corresponding nearest track point.

 - [ ] **(8)** [Side finding]: For caption disambiguation we could rename the "Split interval" **setting** near the top to "Interval markers", which is really what this does, and the "Split interval" **button** near the bottom to "Interval analysis". **_(EDIT: Agreed to fix in UI, not via wording)_**

**Comment by sonora** [comment] 2019-05-26 08:35
EDIT regarding (2) and (3): I just notice that the Color button for most of my tracks behaves as descrubed above, but I seem to have a few very recently recorded tracks where the button always works and also affects the track itself and not just the split markers?!?

**Comment by vshcherb** [comment] 2019-06-23 23:12
(1) is Nice to Have (UX issue). It should indicate immediately on track preview though it works if you click Show on Map and go to Map. Also it could display probably a message what is going to do. Functionally it works.

**Comment by vshcherb** [comment] 2019-06-23 23:13
(2) and (3) are not clear and probably bug! But I didn't manage to reproduce it! I think issue is that some of your tracks have color inside GPX and it takes precedence.

**Comment by vshcherb** [comment] 2019-06-23 23:15
(4) I don't see such issue - @dmpr0  probably we need to work on color set or have a formula. I think on purple and orange white is better

**Comment by vshcherb** [comment] 2019-06-23 23:19
(5) I didn't know about that functionality and I'm not sure how much to do to get it useful

**Comment by vshcherb** [comment] 2019-06-23 23:20
(8) not sure, I think we need to work on display rather than on wording

**Comment by vshcherb** [comment] 2019-07-05 15:33
Yes we need to add edit description and delete but we need to refactor the overflow menus on top. (1) is referring to 1 track segment and is not related to the whole track. 

Partially it was fixed with parsing and storing description but we don't have UI to edit description yet.

**Comment by sonora** [comment] 2019-08-06 20:49
Revisited today, my status on the items not yet planned to be fixed is as follows:
 - **(2) and (3)**: In fact, cannot reproduce any more, either this is an unreliable occurrence, possibly related to old OsmAnd recordings or 3rd party tracks, or meanwhile fixed. Suggest we ignore, will open a new issue if I find how to reliably reproduce.
 - **(4)** This should be easy to fix, e.g. by using white font if sum of RGB <= 3*256, black if otherwise
 - **(5)** Yes, we used to have splitting points on the map tappable, this disappeared when we re-factored the entire track analysis. Before, we could tap on any of the split markers of a track (if displayed on the map) and we could see its context menu.
 - **(8)**  Caption disambiguation is the easiest fix I can think of (top item sets the interval, bottom button starts the action, i.e. changes the screen). Yes, we could also change this overall behavior, but then we would need a concept. We could simply hide the split interval setting on that screen and just keep the action button, so the interval can only be set on the subsequent split analysis scree. not a big difference, but maybe a little cleaner.

**Comment by vshcherb** [comment] 2019-08-09 13:16
(4) This should be easy to fix, e.g. by using white font if sum of RGB <= 3*256, black if otherwise - agree

**Comment by vshcherb** [comment] 2019-11-05 16:10
We need to create separate issues, this is getting cumbersome and it is hard to assign 1 task to finish something at least.

**Comment by sonora** [comment] 2020-03-16 12:04
Following e771ead I have updated my first post at the top to reflect what is already fixed now.

**Comment by vshcherb** [comment] 2020-03-16 20:25
(5) The split markers on the map are not tappable any more? We used to have this, tapping any showed you the details of the corresponding nearest track point.

Is going to be fixed with another request to make track itself tappable. Yes that was a regression long time ago but it is probably not that crucial to be fix it separately

**Comment by sonora** [comment] 2020-03-17 09:17
Regarding (5): Yes, agree! That would essentially leave (6), (7), and (1) and we have upgraded our Track management interface to a powerful and reasonably usable/transparent tool.

I would say, in light of this we could now develop the story further in ways described in #8685 ?

**Comment by vshcherb** [comment] 2021-01-11 15:22
The issue is quite big and I think now (6) is fixed and (7) is coming. For other issues it becomes quite difficult to track the progress cause it keeps changing. I suggest to open separate issues so it's possible to track them separtely

**Closed by vshcherb** 2021-01-11 15:22 UTC

**Comment by sonora** [comment] 2021-01-13 00:43
I don't see (6) fixed. The overflow menu of the track analysis dialog (3 dots menu to the left of the `Split interval` button) still only contains the items `Edit` and `Delete` (latest nightly).

**Comment by Chumva** [comment] 2021-01-13 09:53
There is a `rename` option in the toolbar next to the share button.

**Comment by sonora** [comment] 2021-01-13 23:03
Maybe we are not talking about the same screen, here is a screenshot (lower left corner is the pop-up menu I am talking about):
![20210113_235422](https://user-images.githubusercontent.com/845735/104520635-bb274f80-55fb-11eb-8a33-c238e2c1f698.jpg)

**Comment by Chumva** [comment] 2021-01-13 23:38
This screen is still in development. There should be new tab options added
this week. In old screen with track and similar tabs in my places, delete
and rename are already added.

чт, 14 янв. 2021 г., 01:03 Hardy <notifications@github.com>:

**Comment by sonora** [comment] 2021-01-15 08:39
Ah, ok, thanks!

I think the major use case is also that on our main track selection screen for `Visible` tracks we have no 3-dots action menu like `Rename` etc., because it is replaced by the "Visible" checkbox selector. So your options are to either locate the track in question again in its file structure below, or tap on the track in the `Visible` section, but that will put you to the screen I show above which does have only the incomplete action menu.

**Comment by sonora** [comment] 2021-01-19 07:29
I assume we are also retiring 'Analyze on map', it should be entirely obsolete now?

**Comment by vshcherb** [comment] 2021-01-19 14:46
hm.. no, analyze on map will be updated to be used in "Navigation mode", so it will be a simple screen, so user can see graphs during navigation (or just map browsing).

Context menu graphs will be more like in place usage and analyze on map will be a certain context related to be used with other widgets
