### ISSUE TITLE
Routing broken when GPX has segments/lines on both Android and iOS apps.

### ISSUE THREAD

**Issue by adegans** [osmandapp/OsmAnd#12472] opened 2021-08-14 03:20 UTC
I finally figured it out...
The wacky routing is because of track segments.
Every start and end of segments is added to the route calculation causing me to be sent all over town in straight lines.
First the route seems to nagivate fine, then at the end a 'straight-line' route is tacked on between all start and end points from all segments. 

When I edit the GPX and combine all segments in one long segment this does not happen.
In my test I also have to convert Lines to tracks and merge those into the main/primary track as well.

Then everything works perfectly fine.

This behavior happens on both iOS and Android versions of Osmand.
Please someone have a look for a near future fix.

_Originally posted by @adegans in https://github.com/osmandapp/OsmAnd/issues/12140#issuecomment-898808410_

**Comment by adegans** [comment] 2021-08-14 03:27
[gpx-test-files.zip](https://github.com/osmandapp/OsmAnd/files/6985835/gpx-test-files.zip)

Contains 2 test files of the same route:
- 1 has segments and thus renders broken navigation.
- The other has all segments merged and works fine for navigation.

**Comment by vshcherb** [comment] 2021-08-15 15:04
The issue is not related to segments mostly but it's because you have "route" and 2 <rte> points, once you have <rte> points in the track then track is ignored

**Comment by adegans** [comment] 2021-08-15 16:46
Points as in Waypoints? Then why does it work if I merge all segments (and keep the waypoints).
There is no Route in the files. So that's logically not it...

If you mean something else, please clarify.

**Comment by adegans** [comment] 2021-08-15 16:49
Oh I see the waypoints are missing in the 'segmented' file... Hmm. 
Well, either way, that file doesn't work in Osmand as the navigation/calculated route is all messed up. As described above.

The 'fixed' file has waypoints and works fine in Osmand for navigation.

**Comment by adegans** [comment] 2021-08-15 16:51
[Salina Cruz 1.segmented.waypoints.gpx.zip](https://github.com/osmandapp/OsmAnd/files/6988515/Salina.Cruz.1.segmented.waypoints.gpx.zip)
Does this work in your test?

**Comment by vshcherb** [comment] 2021-08-16 09:15
> The 'fixed' file has waypoints and works fine in Osmand for navigation.
It has waypoints but it doesn't have <rtept> any more. Anyway this issue will be investigated & fixed .

**Comment by adegans** [comment] 2021-08-17 01:00
The fixed file has a track, waypoints and one POI...

But I'll await the update. If you need any further information please let me know.

**Comment by vshcherb** [comment] 2022-05-24 11:06
To summarize the issue: track has 8 trk segments and 1 route with 2 rtept. User should be able to choose in navigation either 1 track or any of 8 trk segments or 1 route with 2 rtept

**Closed** 2022-06-28 13:41 UTC
Labels: and-bugs
