### ISSUE TITLE
Deleting a track doesn't remove it from the map if it was previously marked as visible

### ISSUE THREAD

**Issue by Player701** [osmandapp/OsmAnd#11347] opened 2021-04-05 16:02 UTC
### Description

Marking a track to be visible on the map and then deleting it will not remove the track from the map view. To clear the track from the map view, a complete app restart is required.

### How to reproduce?

1. Record or import a track.
2. Mark the track in "My Places" -> "Tracks" to display in the map view.
3. Go to "My Places" -> "Tracks" again and delete the track.
4. The track is still visible in the map view, and there's no way to remove it without restarting the app.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 11 (the issue was also observed on Android 10)
Device model: ASUS ZS-671KS (ZenFone 7 Pro)

**Maps used (online or offline):**   
Offline maps, but probably doesn't matter.

**Comment by scaidermern** [comment] 2021-04-06 05:35
Duplicate of #9778.

**Comment by vshcherb** [comment] 2021-04-07 18:16
Workaround is mentionned in #9778 -  merged with it.

**Closed by vshcherb** 2021-04-07 18:16 UTC
