### ISSUE TITLE
Language direction files keep re-appearing

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#15606] opened 2022-10-31 22:43 UTC
I would say only half a bug, but:
Regularly I find a lot of language direction files on my installed maps page. I remove all the languages I do not need. And after a while, I think usualy after an upgrade but I'm not sure, the whole list reappears.
Not a big issue because the files are not big, but not nessesary and illogical. I would expect these files to behave just like map files. Or at most only auto-update the already installed ones.

**Comment by scaidermern** [comment] 2022-11-01 08:27
Duplicate of #5994?

**Comment by tradavyvy** [comment] 2022-11-01 08:36
Yep, I think it is. (Sorry)
And vscherb closed that one in september so it will probably be solved in the next release.

**Comment by scaidermern** [comment] 2022-11-01 08:57
No, unfortunately it is still open. There are just some references to other closed tickets.

**Comment by tradavyvy** [comment] 2022-11-01 09:08
In that case I reopen the issue because the other one is realy old.

**Comment by scaidermern** [comment] 2022-11-01 09:38
Well, having a duplicate doesn't really help.

**Comment by vshcherb** [comment] 2022-11-10 13:54
Issue already fixed

**Closed by vshcherb** 2022-11-10 13:54 UTC
