### ISSUE TITLE
[Feature request] favorite description scroll

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#8618] opened 2020-03-04 13:10 UTC
The Favorite description is closed by the keyboard. It would be more convenient if it could be scrolled up and down to see what the user is typing
![1](https://user-images.githubusercontent.com/50198677/75882678-4f485800-5e2a-11ea-9a2f-53f1793e91f7.jpeg)

**Comment by scaidermern** [comment] 2020-03-04 15:00
Duplicate of #8556 and #6669.

**Comment by dmpr0** [comment] 2021-04-12 13:47
We implemented a new UI for adding favorites and gpx waypoints.

**Closed by dmpr0** 2021-04-12 13:47 UTC
Labels: Nice to Have
