### ISSUE TITLE
Sporadic FC when changing routes

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2295] opened 2016-03-01 09:38 UTC
When playing around with adding route points (intermediate destinations) with our latest nightlies, I sporadically get enclosed FC.
[exception.log.txt](https://github.com/osmandapp/Osmand/files/152477/exception.log.txt)

**Comment by vshcherb** [comment] 2016-03-17 08:37
ava.lang.RuntimeException: Loading data exception
	at net.osmand.router.RoutingContext.loadTileHeaders(RoutingContext.java:429)
	at net.osmand.router.RoutingContext.loadTileHeaders(RoutingContext.java:361)
	at net.osmand.router.RoutingContext.getRoutingTile(RoutingContext.java:498)
	at net.osmand.router.RoutingContext.loadTileData(RoutingContext.java:449)
	at net.osmand.router.RoutePlannerFrontEnd.findRouteSegment(RoutePlannerFrontEnd.java:62)
	at net.osmand.binary.GeocodingUtilities.reverseGeocodingSearch(GeocodingUtilities.java:164)
	at net.osmand.plus.CurrentPositionHelper.runUpdateInThread(CurrentPositionHelper.java:208)
	at net.osmand.plus.CurrentPositionHelper.access$000(CurrentPositionHelper.java:24)
	at net.osmand.plus.CurrentPositionHelper$1.run(CurrentPositionHelper.java:67)
	at net.osmand.plus.routing.RoutingHelper$5.run(RoutingHelper.java:924)
	at java.lang.Thread.run(Thread.java:841)
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.CodedInputStream.pushLimit(CodedInputStream.java:614)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.readRouteTree(BinaryMapRouteReaderAdapter.java:729)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.searchRouteRegionTree(BinaryMapRouteReaderAdapter.java:815)
	at net.osmand.binary.BinaryMapRouteReaderAdapter.searchRouteRegionTree(BinaryMapRouteReaderAdapter.java:818)
	at net.osmand.binary.BinaryMapIndexReader.searchRouteIndexTree(BinaryMapIndexReader.java:2459)
	at net.osmand.router.RoutingContext.loadTileHeaders(RoutingContext.java:408)
	... 10 more

**Comment by vshcherb** [comment] 2016-03-17 09:20
Should be fixed now

**Closed by vshcherb** 2016-03-17 09:20 UTC
