### ISSUE TITLE
Directions From: Start replaced by current position

### ISSUE THREAD

**Issue by VSCHULTE** [osmandapp/OsmAnd#21124] opened 2024-10-23 14:35 UTC
### Description

When I want to calculate a route somewhere else the selected start is ignored

### Steps to reproduce

Have Location switched on
Select any location > Actions > Directions from
Select any destination
navigate e.g. by foot

### Actual result

The route starts at the current location NOT at the selected start

### Expected result

The route is calculated from the selected start to the destination

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 480603 and many before
Android version: 15 and many before
Device model: Pixel6a, Fairphone 3
Crash-Logs: ?
```

**Comment by mikehgentry** [comment] 2024-10-23 15:48
Duplicate of #17498 I think

**Comment by VSCHULTE** [comment] 2024-10-23 15:51
thanks. i spent some time looking but not enough, obviously

**Closed** 2024-10-23 15:51 UTC

**Comment by sonora** [comment] 2025-05-17 06:02
Related: #22595.
