### ISSUE TITLE
Track route points not visible in track

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9205] opened 2020-06-11 08:56 UTC
After creating a track with waypoints and saving it as routing points, there are no points visible in the track description (My Places -Tracks - track - Point).

**Comment by sonora** [comment] 2020-06-11 09:20
Yes, and I just notice we are not using the GPX TopoGrafix `<rte> `or `<rtept>` namespace. Not sure if that's by design and if there are reasons to improve here.

**Comment by vshcherb** [comment] 2020-06-11 12:26
XML Namespace is not necessary and many other programs don't use it too.

**Comment by vshcherb** [comment] 2020-08-03 12:12
Looks like it's fixed now, tested with new plan route -> save as route points

**Closed by vshcherb** 2020-08-03 12:12 UTC
