### ISSUE TITLE
Bicycle Router is ignoring turn restriction’s exception for bicycles (Relation: 9375329)

### ISSUE THREAD

**Issue by Peter0** [osmandapp/OsmAnd#19206] opened 2024-02-28 15:47 UTC
### Describe the routing engine used (required)

- [×] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Bicycle; kind of driving: balanced; no considering of height data; no use of motor highways; no stairways; avoid fords

### Describe your start and end points (required)

50.72883 7.10242
50.72856 7.10267

### Describe the actual route (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/2462058/9425a67a-3f91-402f-bfe5-2e60aa45a6e0"  width="600" height="auto"/> </th>
  </tr>
</table>

### Describe the expected route (required)

At the "via" of the mentioned turn restriction relation I expect to propose turn left, followed by turn right, instead of taking the strange loop in the west, because there is an excepton for bicycles in the turn restriction.

### Describe what Maps you used (online or offline) (required)

- [×] Offline maps offered within the OsmAnd app for download. Edition from Feb. 2024, plus live updates
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: ~4.6.12
Android/iOS version: 9
Device model: Samsung Galaxy J5
```

### Anything else? (optional)

By occasion, I’ll test behaviour without live-updates. Experience: At #17047 this made a difference.

**Comment by vshcherb** [comment] 2024-03-11 22:07
Probably duplicate of https://github.com/osmandapp/OsmAnd/issues/7409

**Comment by zipav** [comment] 2024-03-12 16:57
OsmAnd Nightly 4.7.0#1815m, released: 2024-03-12

OsmAnd proposes an unnecessary U-turn instead of going straight through, the problem is most likely this relation:
https://www.openstreetmap.org/relation/9375329

The route itself is in the web version: https://osmand.net/map/?start=50.728830,7.102420&finish=50.728560,7.102670&profile=bicycle&params=bicycle,avoid_stairs,avoid_fords#20/50.72860/7.10236


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/4f3d984d-efb7-47c3-bee8-fa1e149397d5"  width="600" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment] 2024-03-16 15:39
Merged to https://github.com/osmandapp/OsmAnd/issues/7409

**Closed by vshcherb** 2024-03-16 15:39 UTC
