### ISSUE TITLE
Cannot choose user defined storage folder on external SD with Android 13

### ISSUE THREAD

**Issue by bege10** [osmandapp/OsmAnd#18745] opened 2023-12-15 20:11 UTC
### Description

OsmAnd refuses to accept user defined storage folder on external SD with Android 13. The same location works on a device with the same ROM but Android 12.

### Steps to reproduce

Choose user defined storage folder on external SD
Don't move data (is already in place)

### Actual result

"Maps could not be created in the defined directory" (translated from German)

But OsmAnd shows the places that are stored in that directory, no matter which storage location I choose.

### Expected result

Read all data from the defined directory

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5.10 (F-Droid
Android/iOS version: /e/OS-T (Android 13)
Device model: Shiftphone 6mq
Crash-Logs: 
2023-12-15 20:24:51.529 19484 19484 net.osmand.plus D CompatibilityChangeReporter : Compat change id reported: 147798919; UID 10288; state: ENABLED
2023-12-15 20:24:51.588 19484 19556 net.osmand.plus W Parcel : Expecting binder but got null!
2023-12-15 20:24:51.599 19484 19556 net.osmand.plus D OpenGLRenderer : endAllActiveAnimators on 0x7669788bb0 (RippleDrawable) with handle 0x757a052420
2023-12-15 20:24:51.629 19484 19556 net.osmand.plus E OpenGLRenderer : Unable to match the desired swap behavior.
2023-12-15 20:24:54.067 19484 19556 net.osmand.plus D OpenGLRenderer : endAllActiveAnimators on 0x766979e750 (RippleDrawable) with handle 0x757a108bb0
2023-12-15 20:24:57.909 19484 19484 net.osmand.plus V OsmAndCore:Android/MapRendererView : handleOnPause()
2023-12-15 20:24:57.932 19484 19484 net.osmand.plus D net.osmand : Disable sensor
2023-12-15 20:24:57.937 19484 19484 net.osmand.plus I net.osmand : MapRenderRepositories RENDER MAP: Interrupt rendering map
2023-12-15 20:25:04.180 19484 19501 net.osmand.plus W net.osmand.plus : Cleared Reference was only reachable from finalizer (only reported once)
```

**Comment by bege10** [comment] 2023-12-15 23:50
OsmAnd does not ask for permission to access all files. After I found this special permission and granted it OsmAnd had access to the selected folder.

**Comment by DmitryAlexei** [comment] 2023-12-17 23:09
It is a duplicate of a known issue with Android 13
https://github.com/osmandapp/OsmAnd/issues/17852 https://github.com/osmandapp/OsmAnd/issues/14165 https://github.com/osmandapp/OsmAnd/issues/16301 etc

**Comment by bege10** [comment] 2023-12-20 14:51
In the special app permissions it is possible to grant the access and OsmAnd works as before. Why does OsmAnd not ask for that permission after installation? I remember other apps do so.

**Closed** 2023-12-21 23:10 UTC
