### ISSUE TITLE
Show Ref of motorway-junctions (exit)

### ISSUE THREAD

**Issue by osmvermesser** [osmandapp/Osmand#3771] opened 2017-05-12 19:17 UTC
It would Mord helpful to show (say) the REF when motorways had to leave.

In Madrid it would be more helpful to find the correct exit.

Regads Jan

**Comment by jfburke3** [comment] 2017-05-16 04:47
You're referring to the exit number?

**Comment by osmvermesser** [comment] 2017-05-16 06:34
yes - look to https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway_junction#Name_and_number

**Comment by polarbearing** [comment] 2017-05-16 08:19
Duplicate of #1347

**Comment by vshcherb** [comment] 2017-05-20 13:12
Yes it is duplicate

**Closed by vshcherb** 2017-05-20 13:12 UTC
