### ISSUE TITLE
adjusting widget transparency

### ISSUE THREAD

**Issue by sazearte** [osmandapp/OsmAnd#18519] opened 2023-11-07 18:44 UTC
### Describe the idea (required)

you can only choose between no transparency and 100% transparency
I find that 100% is not very readable.
I'd like to have a slider below the option to choose the level of transparency, for example to set it to 50% or 75%.

### Tell us about the expected behaviour (required)

be able to choose the level of transparency of widgets

### Tell us about alternatives you've considered (required)

for the moment I'm not activating widget transparency because I don't find it very readable

**Comment by arncor** [comment] 2023-11-15 14:07
Duplicate of #16017

**Closed** 2023-11-17 15:31 UTC
