### ISSUE TITLE
Off-route situation should stop lane indication

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2747] opened 2016-06-24 10:10 UTC
When leaving the calculated route, I get the lane indication and speed limits, as if I still were on the calculated road. 
- The lane indication should be switched off. 
- The speed limit should be that of the road currently driven. 
- The space of the lane indicator could be used to show the road I am currently on. That would help a driver who is semi-familiar with the area to recognise his mistake, easier than glimpsing for street name signs.

**Comment by sonora** [comment] 2016-07-04 12:30
As far as the voice prompts are concerned, chances are we have a caching issue, we may at least have to push a TextToSpeech.QUEUE_FLUSH (and equivalent for MediaCommandPlayer) once we detect we are off-route.

**Comment by polarbearing** [comment] 2016-07-13 18:39
The visible recommendations are quite erratic when I drive off the recommended route. In the example below, I'm 640 m off-route, but are recommended turn:lanes in 263m that are pointless and misleading for me. Also the turn-right-to-Rudower_Chaussee is a remnant from where OsmAnd wished to be, impossible from where I am (Rudower_Chaussee is parallel to my current road, north of me). 
In other situations, the dotted-grey off-route indicator is intermittently replaced with a yellow 
turn instruction that is impossible to follow from my current situation, and again gives new turn:lanes that are not where I'm driving. 
Thus my suggestion, as soon as off-route is detected, switch off both the turn instruction and the turn:lanes, and show me on which road I am currently (including its maxspeed)

![screenshot_2016-06-25-21-29-31](https://cloud.githubusercontent.com/assets/8266355/16815041/a94a1916-4938-11e6-8a65-e8c27bf192df.png)

![screenshot_2016-06-25-14-53-08](https://cloud.githubusercontent.com/assets/8266355/16815363/d42a8b1a-4939-11e6-9ffa-7634c95af441.png)

**Comment by sonora** [comment] 2016-07-13 19:12
I think that's a valid point:

From what I see, the "dotted" arrow depicts the projected distance to the calculated route and is likely the only symbol which appears with some justification. The turn lane indications should be hidden when off route, this is likely a bug. And the intermediate turn instruction arrows should likely likewise be hidden, I think we mostly successfully suppress the voice prompts, but fails to hide the turn arrows in many situations.

**Comment by polarbearing** [comment] 2016-07-13 19:46
The last shot in my previous post is also an indicator that the maxspeed is from the planned route, not the driven road. Where my blue arrow currently drives, 30 is allowed, thus with 36 I need a warning.

**Comment by sonora** [comment] 2016-07-20 06:26
Ok, I think the issue is identified sufficiently. Looking at the code, we do in deed not check if we are still on the route or not before displaying the lanes control or the traffic warnings.

We do have a flag` isDeviatedFromRoute` we can and should use, but I am not convinced yet we maintain that reliably enough to indicate what its name says, so I think there may be some work here to fix this issue. (The flag is also used to stop the voice router, and I have seen similar stickiness issues there...)

**Comment by sonora** [comment] 2016-07-20 08:58
Ok, I have cleaned this up and implemented the proper masking, please help test.

MaxSpeed and traffic warnings should be taken off the current location and not the current route segment now if you are off route.

Lanes I am not sure yet, looks like we have code to show lanes even in the no-navigation case, not sure for what purpose. For now I am forking to that code if off route is detected.

**Comment by polarbearing** [comment] 2016-07-20 10:57
Will test, sure, thanks. 

> we have code to show lanes even in the no-navigation case

That's ok, it is helpful in non-navigation to see what lane layout is coming. Just the font size for the distance of the lane box is too small to be recognised while driving, that should be the same size as in the main navigation arrow. The distance is important since not all junctions have lane tagging yet, so often it applies to ta more distant jct.

**Comment by polarbearing** [comment] 2016-07-24 16:57
(nightly 23-Jul-2016 23:44) 
OK, the turn:lanes are mostly gone when we're off route.  Speed limit is switched off, both the large over-speed warning, and the mostly the small maxspeed widget as well. 

The driver has left Frankfurter Allee which he was supposed to stay on, and drives on Ruschestr in the shot below, still we see the old road name, and it is confusing if that means I should drive towards Frankfurter Allee, or an error in displaying which road I am actually on. 

We should get a warning since the speed is 62 with 50 allowed (and tagged) in Ruschestr. 

In this context, and other situations as well, it would be good if showing a recognised (snapped on) road name would have its own icon before the name (e.g. the cross-hair icon) so it can be better distinguished from navigation instructions. 

![screenshot_2016-07-24-10-28-21](https://cloud.githubusercontent.com/assets/8266355/17085047/9dd382d6-51ce-11e6-960d-3bd1a15beef4.png)

Here, the driver was supposed to turn into Greifswalder, but continued straight onto Michelangelo. So that nourishes the assumption that the name is where the system wants to be. No speed limit shown (but tagged).

![screenshot_2016-07-24-14-58-44](https://cloud.githubusercontent.com/assets/8266355/17085106/32081bb4-51d0-11e6-9a9a-33965257a8e3.png)

Occasionally, I get a fragment of a turn:lane box when off route. Interestingly, in this screenshot I also have a maxspeed widget, but it is unclear which road it belongs to:

![screenshot_2016-07-24-14-51-40](https://cloud.githubusercontent.com/assets/8266355/17085055/d4967634-51ce-11e6-8a57-a79fcb530af2.png)

**Comment by sonora** [comment] 2016-07-24 21:43
Here is the target situation to test against:

(0) As soon as our code detects that you are off route, a dashed grey arrow appears in the top left "next turn" widget. This can serve as the primary indicator of when this situation is detected.

(1) In sync, the lanes widget should either disappear, or switch to display lanes (if any) using not route but "where you actually are" info. (I wonder if the partial lanes info you occasionally see comes maybe from the widget not disappearing or being refreshed correctly if being displayed while you go off-route, needs some testing/investigation)

(2) In sync, the maxSpeed widget should switch to using "where you actually are" data

(3) Dito for the speed alarm widget (and any other traffic alarm info widgets)

(4) Dito for the street name display (fixed now, I had previously overlooked this, it is in a different module)

I will check the code again for  bugs.

**Comment by polarbearing** [comment] 2016-07-25 08:36
(1)-(4) sound good.

Not sure what you mean with 'in sync', maybe snapped on road?
The partial lanes popped up while already driving on the alternate road, and normally the lane widget is centred around the lane(s), so the screenshot shows an artefact. Will continue to observe. 

Trying to understand cases (1-4ab), with 'non-navigation case' you mean car-profile but not navigating? So,
(4a), when I move the map and look elsewhere, there is no street name until I press the blue button, or the app re-centers automatically. Plausible. Thus (1a,2a,3a) are reasonable as well. 
(4b), "Snap to road" is only in the navigation settings. Browse map has no navigation settings at all, thus showing them there would not work correctly anyway?

**Comment by sonora** [comment] 2016-07-25 16:47
Clarifications:
- By "in sync" I simply mean the code uses the very same trigger: So while you see the gray dashed arrow in (0), you know that at the very same time the reference for (1)-(4) should have changed from "taken off the routing segment information" to "derived from where you are actually driving and in what direction" (which is slightly less reliable). 
(So the lanes effect you saw in Breite Straße may per se not really be an artifact, it may actually depict there is really only one lane there (?) for you to take, and the bug may be this widget is shown there when it should be hidden).
- By "non-navigation" I mean any time you have not selected to see turn-by-turn navigation instructions, so before you tapped the "GO" button on the route configuration screen (which triggers the turn-by-turn arrows and the voice navigation), or after tapping the (X) on the route config screen (or reaching your destination). (Some folks drive with a route being calculated, but just follow the route line, without having these turn-by-turn instructions. So this situation about my "(a)" questions are only relevant to them).
- The "(a)" issues in this non-navigation case: They mean to say that the corresponding widgets (and of course warning prompts) would not show while you pan the map or after the map was panned, they only show while the blue position button in the lower right map corner shows blue dot on white. (Exactly like you can easily verify for the street name display in app mode CAR, it disappears after panning the map, until you tap the blue dot again. It may make sense, let's leave it for now. But it could mean that folks driving without the turn-by-turn nav mode on may miss traffic warnings and never know why.
- (4b) simply means to say that currently the street name display is not available (and we do not allow to configure it as available) in the map browsing mode (this is independent of Snap-to-Road, street name display does not depend on that feature.). An arbitrary restriction probably meant to simplify things to what's needed.

**Comment by polarbearing** [comment] 2016-07-25 19:25
> the corresponding widgets and ... warning prompts would not show while you pan the map ... folks driving without the turn-by-turn nav mode on may miss traffic warnings

Well, having the street name disappear while panning might explain them that warnings disappear as well, in particular if the small maxspeed widget disappears along, indicating that the app does not look for road details while panning.

> By "non-navigation" I mean...

Is seems we need some clearer taxonomy of the states the app can be in, so we no not need negative terms as non-something. In this case it could be 'route mode' and 'guide mode', with guiding including routing. 

That could also lead to simplification of the steps to target selection, e.g. I'd like to have a 'Route' button after selecting a target button immediately along with a 'Route and guide' button, so I save the extra step. If you agree I can describe that in more detail in an extra ticket. 

Anyway, for the situation definition we agree.

**Comment by sonora** [comment] 2016-07-25 21:43
Not sure there is much to gain by norming our vocabulary here ... Utlimately I need to "think code" anyway.  ::)

In the code we have the following states, simplified to the ones which matter here, mostly self-explanatory to some degree:
- Route planning dialog: Where you enter start and destination, and can access the navigation settings.
- While being on this screen, app works to get to status "isRouteCalculated=true"
- When you request turn-by-turn navigation, it enters status "isFollowing=true"
- When it is detected that you are off the route (different criteria, mostly distance from route and bearing-discrepancies), "isDeviatedFromRoute=true". This is now the only and common trigger for what we talk about in this issue, see (0) above. (And also trigggers status action "recalculate Route").
- The map itself can be in "isLinkedToLocation=true" state, which it automatically enters when tapping the blue "Where am I button", until you manually pan again.

Hope this helps.

I will doublecheck the code to and then we can test again. My feeling is the references for the widget states are correct now, but there may not always be a display refresh where needed.

**Comment by polarbearing** [comment] 2016-07-26 21:13
Testing nightly 26-Jul-2016 14:04 today.
Most of the time while re-calculation the route, the street name box was empty, and no maxspeed shown (dark shot 22:13). However that was also the case for then initial route calculation (bright shot 16:48).

![screenshot_2016-07-26-22-13-37](https://cloud.githubusercontent.com/assets/8266355/17155486/932a3e0c-5385-11e6-8e36-17517de8e2ad.png)
![screenshot_2016-07-26-16-49-07](https://cloud.githubusercontent.com/assets/8266355/17155508/b4767ef4-5385-11e6-99bd-d953e419d99f.png)

Only rarely in isDeviatedFromRoute, the street name was shown with the new + symbol, see shot below, name and speed limit would be correct for the L302 shown, however I'm already 65m around the corner in the residential road. 

We also have a lane layout here, now my suspicion is that is is much too wide for a single lane because it shares the widget wit the calculation progress bar. 

![screenshot_2016-07-26-22-17-34](https://cloud.githubusercontent.com/assets/8266355/17155629/2e5c181e-5386-11e6-8361-a7a955136005.png)

**Comment by sonora** [comment] 2016-07-26 21:53
Hmm, looks like my code works in principle. But we may have an issue with reverse geocoding, i.e. finding out what street name you are on (and maybe also the lanes layout and any maxSpeed tagging). Not sure but it seems to me that also in the map browsing app mode reverse geocoding seems somehow laggy lately - will wait sometime until the ongoing work on the new search settles down, could be related. Let's check future nightlies.

**Comment by vshcherb** [comment] 2016-07-27 21:36
Geocoding, Quick search and old search, use exactly the same files, manipulating with this functions in multiple thread could lead to crashes. They are mutually exclusive.

**Comment by sonora** [comment] 2016-07-28 18:03
Right. I think the principle request in this issue has been achieved. All collateral findings have been documented in separate issues, so let me close this.

**Closed by sonora** 2016-07-28 18:04 UTC
Labels: Observed
