### ISSUE TITLE
Serious problems with the new quick search

### ISSUE THREAD

**Issue by david-ukr** [osmandapp/Osmand#3325] opened 2016-12-05 15:40 UTC
I have serious problems with the new quick search in Osmand+ 2.5.4. I have about 10 country maps downloaded and several German states. Suppose I am currently in Germany and looking at a Bavaria map and I want to search for Bangkok, Thailand. If I enter "Bangkok" in quick search, it takes at least 10 seconds (sometimes 15 seconds) to find on my Galaxy Note 3 because it first finds and lists more than 40 Bangkok restaurants in Germany before it shows the city in Thailand. Then I tried to switch the map by searching for "Thailand". This also took at least 10 seconds to find because there are many restaurants mentioning Thailand in their names. Entering "country thailand" in quick search did not work either.
Please let me have back traditional search, for example on the Search button in the menu as you did when quick search was first released (leaving quick search on the Search button on the map). Then I can choose country Thailand by entering two characters (th) followed by Bangkok with two characters (ba).
I also tried to use Google Maps to copy the geo URL to Osmand, but searching on a url like www.goo.gle.com ... in Osmand didn''t work either, although this syntax example in shown in your help.
It's also a pity you must enter city then street and not vice versa, so you can't just paste in an address from an imprint of a web site. 

Osmand+ 2.5.4, offline maps

**Comment by njohnston** [comment] 2016-12-05 16:00
@david-ukr: it's possible to restore the old search, as I explained in #3261:

Enable the OsmAnd development plugin, open its settings and select "Show legacy search". The old search appears in the main menu as "Legacy search".

**Comment by vshcherb** [comment] 2016-12-05 17:20
There will be address search restored in a quick search for now you could restore the old search.

The issue is merged to #3261.

**Closed by vshcherb** 2016-12-05 17:20 UTC

**Comment by david-ukr** [comment] 2016-12-06 10:22
Thank you njohnston and vshcherb, it works. Please keep the hidden Legacy Search option in future versions of the app.
