### ISSUE TITLE
OpenGL: Tags `operator`, `note`, `fixme` and more are rendered alongside PoI/Area names.

### ISSUE THREAD

**Issue by nyanmeister** [osmandapp/OsmAnd#15568] opened 2022-10-26 12:37 UTC
### Description
When using the OpenGL renderer, `operator`, `note`, and `fixme` get rendered into labels on the map. There seem to be more tags than this that populate this way, when I was investigating for this I noticed `gnis:state_id` also populate onto a label.

### How to reproduce?
While using the OpenGL renderer from the OSMAnd Development plugin, go to an object that has the tags mentioned.

### Your Environment
OsmAnd Version: 4.2.7 Plus
Android/iOS version: 11
Device model: N/A

**Maps used (online or offline):** N/A

![Screenshot_20221026-052825_OsmAnd~-cropped-scaled](https://user-images.githubusercontent.com/26663716/198027692-5167ac2b-a625-48ae-b67f-64caafe112fd.jpg)
![Screenshot_20221026-052839_OsmAnd~-cropped-scaled](https://user-images.githubusercontent.com/26663716/198027704-343c0914-db58-4456-b111-4fbc9850b499.jpg)

**Comment by scaidermern** [comment] 2022-10-26 13:40
I guess this is a duplicate of #14950.

**Closed** 2022-10-27 09:22 UTC
