### ISSUE TITLE
Widgets on LH Panel don't show, or disappear when Navigation begins..

### ISSUE THREAD

**Issue by DennoTheMenno** [osmandapp/OsmAnd#18473] opened 2023-10-31 21:25 UTC
### Description

Widgets on LH Panel don't show, or disappear when Navigation begins..
 
 

### Steps to reproduce

I can see the Battery widget on the LH panel, but once I tap the Navigation icon the widget disappears.

### Actual result

As a result, all my selected widgets for the LH panel do not display.

If widgets disappear, if I tap the screen (which pauses navigation) then tap the navigation icon, then tap Details, then Resume, the widgets appear again.

EDIT: or, if widgets disappear, I can make them reappear by rotating screen from portrait to landscape (or vice versa)

### Expected result

I expect to see Next Turn, Second Next Turn, and Battery widgets, as selected, but they don't appear. I believe a small Next Turn indicator appears in the Top Panel instead.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.4 EDIT: Now on 4.6.5 and issue persists
Android/iOS version: Android 13
Device model: Samsung S20FE
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment] 2023-11-01 08:21
Probably duplicate of https://github.com/osmandapp/OsmAnd/issues/18387

**Closed** 2023-11-02 15:28 UTC
