### ISSUE TITLE
"OsmAnd+ isn't responding" when opening OsmAnd+

### ISSUE THREAD

**Issue by aSemy** [osmandapp/OsmAnd#18462] opened 2023-10-30 04:40 UTC
### Description

When I open OsmAnd+ it takes a long time to open. Eventually I see an error pop up, "OsmAnd+ is not responding". I'm not sure what the cause use.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/897017/8a395fb4-a8c7-4287-824a-cc8e8640ea20"  width="300" height="auto"/> </td>
  </tr>
</table>

When I hit 'force close' and reopen OsmAnd+ then usually it reopens correctly. However, it opens very slowly. 

### Steps to reproduce

Open OsmAnd+

### Actual result

I am not able to open OsmAnd+

### Expected result

I am able to open OsmAnd+

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.5.10, released: 2023-08-09
Android/iOS version: Android 13
Device model: XQ-DC54 
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment] 2023-10-30 06:16
Duplicate of https://github.com/osmandapp/OsmAnd/issues/18302

**Closed** 2023-10-30 11:16 UTC
