### ISSUE TITLE
Strange names in the world map

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#11455] opened 2021-04-18 07:09 UTC
There are some very strange names (mnTq@...) in the world map. This happens with the display language set to German or Spanish but not with English or French. Happens at least in Saudi Arabia and Yemen but at zoom level 6 only. However zoom level 5 also displays some strange names around this area (looks like random letters).

![IMG_20210418_082547](https://user-images.githubusercontent.com/1040784/115137323-c8524100-a025-11eb-9595-5deec9eb953f.jpg)

**Comment by xmd5a2** [comment] 2021-04-22 12:22
This happens only if transliteration is activated

**Comment by vshcherb** [comment] 2021-04-22 12:24
Then it's probably correct, cause user can disable "transliteration"

**Comment by scaidermern** [comment] 2021-04-22 13:19
"Map language" is set to "Local names". There is no setting for transliteration. The Display language in OsmAnd settings is set to "System (Device language)" which is German.

I can see a transliteration switch if I set "Map language" to anything else than "Local names". However I prefer to use "Local names" for which there is no transliteration setting. So I guess transliteration is automatically enabled for "local names"? If so, it should become configurable. So it looks like the user _can't_ (always) disable it.

**Comment by scaidermern** [comment] 2021-04-23 13:50
@xmd5a2 @vshcherb Can you elaborate how to deactivate transliterations? There is no such switch if "Map language" is set to "Local names".

**Comment by vshcherb** [comment] 2021-04-26 15:15
![image](https://user-images.githubusercontent.com/1042025/116107110-06e59c80-a6b3-11eb-8931-4b20af7860c4.png)This picture with local names

**Comment by scaidermern** [comment] 2021-04-26 18:02
Not for me. Switch the language to German or Spanish.

**Comment by vshcherb** [comment] 2021-04-29 17:51
Nope can't reproduce with latest version 
![image](https://user-images.githubusercontent.com/1042025/116596000-3818d380-a924-11eb-8064-4886e73fe3fd.png)

**Comment by vshcherb** [comment] 2021-04-29 17:51
Testing master to save some time, there was 1 issue fixed in last 2 months

**Comment by scaidermern** [comment] 2021-04-29 18:13
I just reproduced it with the latest nightly 4.0.0#31926m. 

It doesn't happen with the mini world map but with the larger world map. And only with some languages (German and Spanish, at least. Probably more).

**Comment by xmd5a2** [comment] 2021-05-05 07:20
Yes, I can confirm this issue when Display language is set to German and Map language to "Local names"

**Comment by xmd5a2** [comment] 2021-05-05 11:37
Basemap data is ok
```
Point types [place-state (139)] Names [name(1) - منطقة تبوك, name:en(6) - Tabuk, name:ar(28) - منطقة تبوك, name:fr(15) - Tabuk] id -457231 osmid -3573
```

**Comment by vshcherb** [comment] 2021-05-21 14:32
With latest version still can't reproduce. Unless we will get more information from @xmd5a2 probably

As workaround: you can try switch to Map Language English (Disable transliteration) -> Apply. Then switch back to Local names (it's probably that transliteration was cached somewhere).

**Comment by scaidermern** [comment] 2021-05-23 18:06
> With latest version still can't reproduce.

I can still reproduce it with the latest nightly from yesterday (Version 4.0.0#32038m). 

> As workaround: you can try switch to Map Language English (Disable transliteration) -> Apply. Then switch back to Local names (it's probably that transliteration was cached somewhere).

This workaround doesn't work, unfortunately.

Please reopen.

**Comment by vshcherb** [comment] 2021-05-25 14:09
Waiting for @xmd5a2 probably has more info how to reproduce.

**Comment by ivanPyrohivskyi** [comment] 2021-06-16 17:17
https://github.com/osmandapp/OsmAnd/pull/11932
https://github.com/osmandapp/OsmAnd-core-legacy/pull/15

**Closed** 2021-06-18 08:25 UTC

**Comment by scaidermern** [comment] 2021-06-18 09:38
Yep, finally fixed. Thanks!
