### ISSUE TITLE
Allow remaining map settings to be per map mode (profile).

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1276] opened 2015-05-26 20:58 UTC
Most of the map rendering settings (e.g. rendering style, zoom, details, routes) can be configured differently for each map mode (car, bike, pedestrian, etc). This is also true for the Hillshade layer.
Can you also enable this for the other settings, like POI, Point labels, Favorites, OSM Notes (online), recording layer?

**Comment by vshcherb** [comment] 2015-05-26 21:14
This is ongoing discussion and doesn't look easy to decide. There are very tricky cases related to POI, especially it is very unhandy to start changing layers while driving, because you cleared them before in Default Mode

**Comment by aceman444** [comment] 2015-05-26 22:09
Yes, that is also my use case. I need a car mode uncluttered with unneded POIs or Favorites (and many other settings). And another mode with full details and my POI changes (that are now displayed on map in v2) and Favorites and other mapping info.

**Comment by sonora** [comment] 2016-11-24 08:00
I think this will be fixed with the new "City view" map style.

**Closed by sonora** 2016-11-24 08:00 UTC
Labels: Nice to Have

**Comment by aceman444** [comment] 2016-11-25 22:16
How will a map style turn off displaying OSM changes or favourites? I hope that is not part of any style or "view".

**Comment by sonora** [comment] 2016-11-26 20:35
No I was referring to

> Yes, that is also my use case. I need a car mode uncluttered with unneded POIs

and I think the City view should be simplified to cater for exactly that (but I may be wrong).

In any case, I observe a tendency that most users rather request settings being as much profile independent as possibl , rather than the other way round which is very often a big root cause of confusion and support cases.

**Comment by aceman444** [comment] 2016-11-27 00:26
But I meant the active POIs (the layer that can be turned on), and mu favorites, OSM changes, etc.
Those are not part of the style. And I'd like to have them on in one profile, but not in another.

Maybe you could do one toggle whether the user wants those setting per-mode (profile), or profile-independent (global).

**Comment by sonora** [comment] 2016-11-27 12:33
Ok, I see! I will leave that for Victor to decide, although he has already commented above.

Frankly, in my opinion we probably have too many toggles and settings already. I see a lot of complaints from the average user, and not too much appreciation for too many settings, not even from very advanced users. It is a difficult discussion, I know, hard to please everyone...

**Comment by aceman444** [comment] 2016-11-28 19:40
Yes, there needs to be some balance. You will need to decide what is the target group of OsmAnd. I think it could be the average to advanced users, so a bit of options is no problem (actually a benefit). On the other side of the spectrum you have e.g. Maps.me that has NO options so is basically unusable.

Or you can make the options dependent on some plugin, e.g. the OSM editing. I think that is possible now.
