### ISSUE TITLE
Visually indicate whether POI is currently open or closed

### ISSUE THREAD

**Issue by sevku** [osmandapp/OsmAnd#12706] opened 2021-09-07 09:00 UTC
First of all, I want to thank the OsmAnd contributors for such an awesome and feature rich app. It has served me a lot in the past months.

While using it, a few ideas have come to mind and I want to share one of them here in the hope that it might be implemented one day. The fact that this is the first one doesn't mean that it is the best one and most urgent one, it just means it's the one that's currently on my mind.

It would be really nice if there would be a visual representation of whether a displayed POI is currently open or closed according to its opening hours. I'm not sure what the best way of doing that would be. I can think of two options:
1) "gray" out the icon on the map, alternatively make it reddish if it's closed instead of gray.
2) a red/green point on the corner of the icon.

to make things more complicated, in the second version, maybe you could display a question mark for the ones that have no opening hours in the details. but maybe that goes too far.

maybe there's a better option of doing it or maybe this goes too far and makes everything too complicated. but I would have found it to be useful. maybe some of you would too and maybe you have better ideas on how to implement this.

**Comment by Lee-Carre** [comment] 2021-09-07 11:52
Related, but possibly distinct; a search category which lists only currently-open places (of any type?) listed (by default) by distance from current location.

Else, when searching by type of PoI, the ability to filter the resulting list so that it shows only currently-open establishments (having seen this in other apps; CityZen being an example if I recall). I can well imagine other filtering criteria being of interest to others, so perhaps it should be a more generic framework rather than only a toggle for currently-open.

It might be sensible to include a threshold for how long places will remain open. Little point listing somewhere that closes in one minute when the user is 10 minutes away.

**Comment by scaidermern** [comment] 2021-09-09 11:38
Duplicate of #3350 and #6560?

**Comment by sevku** [comment] 2021-09-09 13:53
> Duplicate of #3350 and #6560?

I guess, sorry 🙂

**Closed** 2021-09-09 14:13 UTC
