### ISSUE TITLE
Configure map > Tracks needs a select/deselect toggle per folder

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17103] opened 2023-05-02 16:17 UTC
Users who have organized their tracks in sub-folders frequently want to add **all tracks of a certain sub-folder** to the "visbles", or remove all tracks belonging to a certain sub-folder from the "visibles".

- For that you need a `"Select all / Deselect all"` toggle which would (alternatingly) select or deselect all checkboxes on the current folder tab (leaving the selection status of all other folder tabs unchanged).

- At the same time we have a  rather similar dual-use toggle button `"Hide All" / "Select Recent"`. As this button affects ALL check boxes (not just that of the currently visible tab), we could avoid ambiguity by showing this button only on the folder-overarching tabs "On map" and "All".

There are 2 possible UIs I can think of:

- **(a)** We show the current button `"Hide all" / "Select Recent"` only on the tabs "On map" and "All". On the folder-specific tabs we instead give this button the `"Select all" / "Deselect all"` function.

- **(b)** Or we use a UI similar to e.g. the Samsung file manager's, where long-tapping any entry temporarily creates an additional checkbox column on the left headed by an "All" toggle (see yellow arrow).
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/845735/235722164-4feb1a3f-67ae-4940-b4cb-31b7a5308204.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by sonora** [comment] 2023-05-07 21:48
@dmpr0 Update: Dmytro, we now have alternating  the Select/Deselect button when using the "Search" functionality  on that screen, so it may be best to use that same one to solve this issue?

**Comment by sonora** [comment] 2023-05-11 15:56
@vshcherb In `MyPlaces > Tracks` it has been present for many years and works great (you can tap on each folder header's checkbox and it will alternatingly select /deselect all tracks of the folder). So this request is really only about `Configure map > Tracks`.

 - As I said above, on the folder-overarching tabs "On map" and "All" we should stay with the current `"Hide All" / "Select Recent"`. (Tab "All" potentially contains a lot of files.)

 - The subfolders, if people use them, contain mostly fewer, because people use subfolders to organize tracks in groups / topics.

 - The root folder "tracks" is maybe a thing to consider: if you want to be cautious, we could there stay with `"Hide All" / "Select Recent"` for a start?

**Comment by sonora** [comment] 2023-05-22 12:23
I am willing to code this, because it is such a blatant and basic usability nuisance for everybody who has their tracks organized in subfolders to not be able to select/deselect a folder content with one tap.

In order to not throw resources down the drain:
- **(A)** Would you prefer to have a `Select all/Deselect all ` **checkbox** in position 1 of each subfolder's track items list (like we have for section "Recently visible" on the On map" tab)?
- **(B)** Or rather re-dedicate the current **button** `Hide all` to `Select all / Deselect all` on all subfolder tabs?

**Comment by dmpr0** [comment] 2023-05-22 12:55
> I am willing to code this, because it is such a blatant and basic usability nuisance for everybody who has their tracks organized in subfolders to not be able to select/deselect a folder content with one tap.
> 
> In order to not throw resources down the drain:
> 
> * **(A)** Would you prefer to have a `Select all/Deselect all ` **checkbox** in position 1 of each subfolder's track items list (like we have for section "Recently visible" on the On map" tab)?
> * **(B)** Or rather re-dedicate the current **button** `Hide all` to `Select all / Deselect all` on all subfolder tabs?

Thank you but, no, currently until we finish polishing My Places > Tracks we didn't have plans to change anything.

**Comment by sonora** [comment] 2023-05-22 14:25
What's it got to do with "My Places > Tracks"? I am talking about **the new dialog* (under "Configure maps > Tracks").

**Comment by sonora** [comment] 2023-05-22 14:49
> They connected.

I would say "_They overlap_" ... :wink:: See table: https://github.com/osmandapp/OsmAnd/issues/11336#issuecomment-1557348965.

Only 3 items missing on the new screen, and the old is obsolete. (Or else, we could have kept the old screen from the start, not messing with the new one?)

**Comment by sonora** [comment] 2023-06-01 05:19
@dmpr0 So where are we taking this now? We have recently introduced **3 different designs** for a select/ deselect toggle, shouldn't these have been coded in a harmonized look and feel from the beginning?

- The bottom sheet button (used for search):
![Screenshot_20230601-070645_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/aa7f37a8-833d-4b46-8c1e-c71a0ef588d6)
- the in-list toggle (used for recents): 
![Screenshot_20230601-070729_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/afcc92aa-db9f-4b8c-8a33-b24648c3537d)
- the top bar (used for folder items and tracks): 
![Screenshot_20230601-071706_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/4df3a442-54f3-4350-82e9-9865590b3f32)

**Comment by dmpr0** [comment] 2023-06-01 07:26
I don't understand, I propose to delete tabs, because iOS doesn't have native solutions for that.

**Comment by sonora** [comment] 2023-06-01 16:03
What tabs? My question is what our layout of choice is to one-click select/deselect all items on a list screen, and if it is intentional we implemented 3 veey different layouts for this functionality in the last few weeks?

**Comment by sonora** [comment] 2023-06-02 19:39
@vshcherb Victor, my additional  feedback above was merely that we have very recently introduced 3 different methods for the same fubctionality "Select all / deselect all". I am 
- (a) interested to learn which one is our method of choice, so I could assist coding it for the folder tabs to solve this original issue
- (b) like to give feedback that harmonizing  things  like this before releasing would be more intuitive to our users.

**Comment by vshcherb** [comment] 2023-06-02 20:33
It should (4) action I'm missing - long tap on the item as in File Explorer. Selection is essential mechanism to do action in batch but it's completely different when you have already action selected like in Configure Map - where your main action to select visible tracks on map. So I think you are not right mixing "Browse All Tracks -> Select -> Action" with "Action (View on map) -> Select"

**Comment by sonora** [comment] 2023-06-02 21:08
Different situations - it's true. But it would still be possible to consistently use either a checkbox, or a bottom button, or an icon on the top bar, for all situations, but not a different one in each?

**Comment by Boothy99** [comment] 2023-06-02 23:01
I'm aware that the above issues regarding toggles / checkboxes is being looked into (hopefully), but I'd like to highlight my recent confused experiences as briefly as I can - for OsmAnd+ 4.5.1.

My Tracks are separated into folders.
I recently wished to show all tracks on the map from a number of folders -

Opened My Places > Tracks > 3-dot menu > Select > chose two folder checkboxes .....
.... 3-dot menu > " Show on map" > Done

On viewing the map - all is as expexted & all chosen tracks from the 2 folders are showing. Good so far.

I then wished to add a third folder of Tracks to the map - now the confusion starts....

Opened My Places > Tracks > 3-dot menu > Select > chose **one** other (additional) folder checkbox (expecting the previous selections to stay on the map!!)
.... 3-dot menu > " Show on map" > Done

However - on viewing the map, my original choices have all disappeared from the map. Only the tracks from my last single selection showed on the map.

It appears that for now, after my initial choices were made - to add more folders, I would need to **RE**-add the original choices yet again at "My Places > Tracks > 3-dot menu > Select".

In previous OsmAnd versions, I could go back into the My Places > Tracks menu and add more folders at any time without the need to RE-select the previous choices.

I'd strongly agree with Sonora's initial suggestion above ""_a Select all / Deselect all" toggle which would (alternatingly) select or deselect all checkboxes **on the current folder tab (leaving the selection status of all other folder tabs unchanged)**._"

**Comment by sonora** [comment] 2023-06-16 21:10
@vshcherb I now get your point regarding

> Selection is essential mechanism to do action in batch but it's completely different when you have already action selected like in Configure Map - where your main action to select visible tracks on map

But actually, it is not necessarily so that users expect "Configure map > Tracks" to solely configure the vsibility status (and in fact it does not, it e.g. also facilitates the appearance configuration as a second batch action).

Perhaps the more intelligible approach would be that each Tracks screen, in its status when the selection boxes are displayed, functions exactly alike, i.e. offers **all** batch actions, perjaps with the visibility status action  via explicitl buttons, the other actions via a static menu and/or popup menu. What is a bit confusing right now is that we have two screens which can both be brought into a status wuth checkboxes, both be used to show tracks on the map, but with different mechanisms to do so.

**Comment by sonora** [comment] 2023-06-17 10:36
@dmpr0 Dmytro, in summary, what I mean is: The "Visible on map" screen could look, behave, and be exactly like any other folder subscreen of  MyPlaces>Tracks, it would not have any different menus, additional folder tabbing or different long-tap behavior. etc.

**Comment by sonora** [comment] 2023-08-27 20:51
PS: Implementing https://github.com/osmandapp/OsmAnd/issues/18024 would be an elegant way to solve this issue.

**Comment by dmpr0** [comment] 2023-10-16 09:52
Duplicate of https://github.com/osmandapp/OsmAnd/issues/16913

**Comment by vshcherb** [comment] 2023-10-20 14:36
Closing as duplicate and pretty deviating from initial discussion

**Closed by vshcherb** 2023-10-20 14:36 UTC
