### ISSUE TITLE
Showing altitude at a marked position on the map

### ISSUE THREAD

**Issue by wolfwehl** [osmandapp/OsmAnd#11265] opened 2021-03-26 09:01 UTC
When marking a point on the map, the coordinates are displayed via the Details function. It would be very helpful for later route planning to additionally display the local altitude here.
If you lead a route over this point, you also get this information. However, this method is much too cumbersome for daily use.

**Comment by littlehelper** [comment] 2021-04-04 04:55
Would be very helpful, see #2487.

**Comment by scaidermern** [comment] 2022-06-14 10:23
Duplicate of #2487.

**Closed** 2022-06-14 15:56 UTC
Labels: Nice to Have
