### ISSUE TITLE
Missing or wrong information in rec subfolder

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#7908] opened 2019-11-12 17:19 UTC
At a  recorded file in rec folder there is additional information displayed: distance, number of waypoints, duration of track.
On subfolders of rec I see the files with date and size of file, which is unimportant.

In example the file is copied from rec/2019-11 to rec, so it is identical.
Version: 3.5.0#28371m

![rec_subfolder_problem](https://user-images.githubusercontent.com/18628183/68694103-cb1b4d80-0578-11ea-86d3-2206a56038f3.jpg)

**Comment by jensMF** [comment] 2019-11-17 00:40
I did some investigation, but I don't have an idea where the bug is, yet.
I found out some things:
  1. if you select "Show on map" for such a track, the distance, number of waypoints and duration of track are displayed
  2. when you disable visibility an map, these information disappear again.
  3. when I copy a track in such a directory, the distance, number of waypoints and duration of track are displayed until next (complete) restart

**Comment by scaidermern** [comment] 2019-11-27 07:37
Sounds like this is related to #7964.

>     1. if you select "Show on map" for such a track, the distance, number of waypoints and duration of track are displayed
>     2. when you disable visibility an map, these information disappear again.

Sounds very similar to the behavior from #7964 which could be caused by the changes made by #6740.

**Comment by max-klaus** [comment] 2019-11-27 11:44
Fixed by https://github.com/osmandapp/Osmand/commit/58d56a6d24639f9b743e40771a7515066d3979d0

**Closed by max-klaus** 2019-11-27 11:44 UTC

**Comment by pebogufi** [comment] 2019-11-28 11:30
Confirm fixed.
Thank you.
