### ISSUE TITLE
Footways are hard to see after update to 4.4.7

### ISSUE THREAD

**Issue by Rilele** [osmandapp/OsmAnd#17251] opened 2023-05-23 12:50 UTC
### Description

After the update from 4.13.12 to 4.4.7 some paths like footways are thinner and hard to see.

### Steps to reproduce

Install the version 4.4.7
Navigate to a place with footways; e.g. 53.05348 8.83154

### Actual result

The footways are thin with low contrast:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/122899461/3cf8f2b4-b75d-49d4-86b5-4fa5af6ebf0f"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result

The footways have the same visibility as in 4.3.12:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/122899461/64af3ff8-cabb-48f3-9f39-6d0272c4578f"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd~ 4.4.7
Android/iOS version: Android 13
Device model: Android Emulator 13.0 Google Play Intel x86_64 Atom System Image

**Comment by michaelblyons** [comment] 2023-05-25 15:12
I kind of like it, but I want an alternative mode with more emphasis on foot and bicycle paths (like UniRS, but with the current default style as a base, not the old one).

**Comment by Zirochkabila** [comment] 2023-05-27 14:55
@Rilele Most likely, these changes occurred due to the use of OpenGL Rendering - but as you can see in screenshots there is no difference
Try activating the Topo map style (Configure map)


<table style="width:100%">
  <tr>
    <th>4.3.0</th>
    <th>4.5.0</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/b360097c-339e-438f-af79-e1f91098dc1f)"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/37d4dd42-2d1d-4e23-9e46-a330566b823d"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment] 2023-06-04 17:14
I think it's Fixed in beta build

**Closed** 2023-06-04 17:14 UTC

**Comment by michaelblyons** [comment] 2023-06-04 17:44
Maybe you could do both: 
- Mute `footway=sidewalk` since there is going to be a road next to it
- Other `highway=path` and `highway=footway` are still visible because they don't follow a roadway.

No complaints if you ignore this, though. Just a suggestion.

**Comment by scaidermern** [comment] 2023-06-21 12:33
> I think it's Fixed in beta build

No, unfortunately it isn't. There isn't any visual change.

Same example from above, with OsmAnd 4.5.3:
![photo_2023-06-21](https://github.com/osmandapp/OsmAnd/assets/1040784/af7d18a9-cf45-4115-ab81-499c96533ca1)

The paths are still as hard to see as before.

**Comment by scaidermern** [comment] 2023-06-28 05:54
Please reopen, this bug is still unfixed.

**Comment by sonora** [comment] 2023-06-28 06:20
Is this a regression at all (possibly OpenGL?), or is it not rather a well known effect of using very saturated background colors in the default renderer, as I explain here https://github.com/osmandapp/OsmAnd/issues/15779#issuecomment-1366718327?

**Comment by scaidermern** [comment] 2023-06-28 06:25
Good question. My gut feeling says this is a regression that appeared when upgrading from 4.3 to 4.4 (I already did use OpenGL in 4.3). However, I'm not entirely sure.

**Comment by scaidermern** [comment] 2023-08-31 07:11
Since developers don't react on the reopen requests I've created #18055.
