### ISSUE TITLE
On the world map it fills the area where land is.

### ISSUE THREAD

**Issue by Lans-K** [osmandapp/Osmand#9034] opened 2020-05-20 16:21 UTC
On the world map fills the space where land is.

![200009600824_227921](https://user-images.githubusercontent.com/65672441/82470141-a080f300-9acd-11ea-9a5d-4a812521fe77.jpg)
![248204521_351806](https://user-images.githubusercontent.com/65672441/82471180-05891880-9acf-11ea-9bb9-77750a2aeaee.jpg)

Координата:
46.07851° N, 33.54157° E

![200016100637_140835](https://user-images.githubusercontent.com/65672441/82470431-ff466c80-9acd-11ea-80d5-d33e56845b7e.jpg)
![264421682_472643](https://user-images.githubusercontent.com/65672441/82471580-8b0cc880-9acf-11ea-9f32-72ec13c02cbf.jpg)

Координата:
46.06409° N, 62.63350° W

![200009600287_228397](https://user-images.githubusercontent.com/65672441/82470707-59473200-9ace-11ea-9210-a1474b5d7d9a.jpg)
Координата:
46.34098° N, 63.52557° W

![Screenshot_20200520-191751](https://user-images.githubusercontent.com/65672441/82471006-c2c74080-9ace-11ea-8ee2-78a237d5e634.png)
Координата:
46.22886° N, 32.56388° E

**Comment by Lans-K** [comment] 2020-06-18 11:01
Good day.
I have additions and refinements to these points and places of flooding lands.
If possible, I will supplement it here.

Place 1: Peru.
![Screenshot_20200616-230017](https://user-images.githubusercontent.com/65672441/85010060-11b4d400-b168-11ea-92f7-2d39a00531b4.png)
![Screenshot_20200616-230257](https://user-images.githubusercontent.com/65672441/85010118-23967700-b168-11ea-96e6-c72a54911ae5.png)
Coordinate:
3.80190° S, 80.57432° W
Scale 10 km.

Place 2: Kherson region, Ukraine.
![Screenshot_20200618-133900](https://user-images.githubusercontent.com/65672441/85010696-1c239d80-b169-11ea-95e4-c074e52b8038.png)
Coordinate:
46.07135° N, 32.52238° E
Scale 10 km.

Place 3: Zaporozhye region, Ukraine.
![Screenshot_20200618-113906](https://user-images.githubusercontent.com/65672441/85011268-f4810500-b169-11ea-89d9-e6b4fda7e219.png)
Coordinate:
46.77581° N, 36.58282° E
Scale 20 km.

Place 4: Gulf of Finland, Russia.
Here on the contrary, - the water mass shows as the land mass.
![Screenshot_20200617-001322](https://user-images.githubusercontent.com/65672441/85011535-56416f00-b16a-11ea-980c-f144c90ce203.png)
![Screenshot_20200618-135744](https://user-images.githubusercontent.com/65672441/85012488-c56b9300-b16b-11ea-8e41-da15f3a0b6e9.png)
Coordinate:
60.14696° N, 28.15788° E
Scale: 5 km, 10 km, 20 km.

Now I can’t find such new places.

**Comment by xmd5a2** [comment] 2020-07-03 13:08
1)Kherson oblast: reproducible, but not exactly in this place and with Russia_crimea obf. http://www.openstreetmap.org/#map=12/46.02125/33.46258
![Screenshot from 2020-07-03 10-21-43](https://user-images.githubusercontent.com/5829014/86470050-4bc6ce00-bd43-11ea-9fa4-de9603b7baa2.png)
looks like algorithm issue. Working on it.
2)Prince Edward island: not reproducible
3)Kherson-Lazurnoye: reproducible but near Skadovsk and with Russia_crimea obf. Looks like the same as 1)
![Screenshot from 2020-07-03 15-42-25](https://user-images.githubusercontent.com/5829014/86470359-f63ef100-bd43-11ea-8a41-30af45c2e033.png)

**Comment by xmd5a2** [comment] 2020-07-03 13:18
@Lans-K Please don't add different issues into one. Most of the have different cause. It makes it nearly impossible to estimate time needed to fix.

**Comment by xmd5a2** [comment] 2020-07-07 07:26
Place 1: Peru
  Not reproducible any more. Looks like it was fixed with new basemap (not available in release yet) after coastline fixes
Place 2: Kherson region, Ukraine
  Same as 3)
Place 3: Zaporozhye region, Ukraine.
  Not reproducible. Possible same as 1)

**Comment by xmd5a2** [comment] 2020-07-07 10:48
Place 4: Gulf of Finland, Russia
Not reproducible

**Comment by vshcherb** [comment] 2020-07-07 16:56
New issues are created https://github.com/osmandapp/Osmand/issues/9404

**Closed** 2020-07-07 16:55 UTC
