### ISSUE TITLE
road number overlaps road objects

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#7038] opened 2019-06-13 20:43 UTC
![image](https://user-images.githubusercontent.com/14617699/59466005-e00e7c00-8e34-11e9-8521-37363f366ee2.png)
![image](https://user-images.githubusercontent.com/14617699/59466022-ed2b6b00-8e34-11e9-8fdf-1d50265fd6f4.png)
![image](https://user-images.githubusercontent.com/14617699/59466046-fd434a80-8e34-11e9-864a-f467d5b21191.png)

**Comment by Zero3** [comment] 2021-08-31 13:39
I can confirm this issue. The road name badge covers a traffic light icon in this screenshot, even after zooming quite a bit in:

![2021-08-29 20 28 53](https://user-images.githubusercontent.com/82504/131512247-71a95442-3547-4d9c-8936-8c4dbb1854c6.png)

(The navigation line is also drawn slightly off-center, but that is a minor issue.)

**Comment by dmpr0** [comment] 2024-01-23 10:55
Duplicate of https://github.com/osmandapp/OsmAnd/issues/3216

**Closed by dmpr0** 2024-01-23 10:55 UTC
Labels: Observed
