### ISSUE TITLE
NPE in track context's Point appearance menu

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19993] opened 2024-06-02 13:39 UTC
Displayed as 'Track' a GPX file which has no `<trk>` or `<trkpt>`, just several `<wpt>`, each tagged with one of two different `<type>` tags.

On the map, tap any of its waypoint icons, tap "Open track", then on the track context menu tap the 'Point' button, then "3-dots>Change default appearance'. This produces this NPE 
[exception.log.txt](https://github.com/user-attachments/files/15525483/exception.log.txt).

**Comment by sonora** [comment] 2024-06-02 14:30
Possibly related to the issue described in https://github.com/osmandapp/OsmAnd/issues/19971#issuecomment-2143732489: We may fail to properly identify wpts' pointsGroups here, and hence also do not assign the right icon color.

**Comment by yuriiurshuliak** [comment] 2024-06-25 15:20
I was unable to reproduce this issue. I attempted to reproduce it by selecting a track containing only <wpt> tags, then tapped the waypoint icon on the map and tried to changing default appearance. No problems related to NPE occurred.

Here's the track I used: [Algeria.zip](https://github.com/user-attachments/files/15973462/Algeria.zip)

The problem might be specific to the track used. Please upload it here so we can investigate further.

**Comment by sonora** [comment] 2024-06-25 20:37
Probably because your track only contained one `points_group`. I have added a second one (called "Other 2"), and put the last `wpt` in it. Now that track produces the crash : [Algeria_2.gpx.txt](https://github.com/user-attachments/files/15978497/Algeria_2.gpx.txt)

**Comment by yuriiurshuliak** [comment] 2024-06-26 13:45
Unfortunately, attempting to access the specified track results in an error on my end.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9949e433-5644-4be8-b3c4-8aa85a9cab2e"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment] 2024-06-27 07:56
No, I have already renamed the track in Total Commander and removed the .txt extension. Please let me know if it opens correctly for you.

**Comment by sonora** [comment] 2024-06-27 16:47
My apologies, you are right - I must have fatfingered the file.

I have updated the post above with a very short _npe-test.gpx_ file, which produces the crash for me... can you reproduce?

**Comment by sonora** [comment] 2024-06-28 18:01
Interesting... yes, good finding. I can confirm that error when using one of OsmAnd's "import" mechanisms for file _npe-test.gpx_.

It is the same root cause I am reporting here, and you have it explicitly on your recording: There is some 'null' interpretation of this line <`{null}osmand:points_groups `.
- When you try to import the track, our import code notices the issue immediately.
- When instead you just place the track manually in OsmAnd's "tracks" folder tree, you can display the file ok. The NPE then only occurs when you try to change the Waypoint appearance using the steps I have outlined in post 1.

I see no reason why OsmAnd creates an NPE for this file at all, so I believe this needs fixing...

There is also a cross connect here to issue #19892. The 2 issues are in the same code, and should likely be fixed together.

**Comment by DmitryAlexei** [comment] 2024-07-10 12:19
Sonora, so this issue can be closed as duplicate of #19892 ?

**Comment by sonora** [comment] 2024-07-10 17:41
https://github.com/osmandapp/OsmAnd/issues/19892 is not exactly a duplicate, because it deals with a functionality bug, while this here is about an occurring NPE. But yes, both issues should be fixed together, and hence be known to whoever tackles this.

**Closed** 2024-07-31 15:24 UTC
