### ISSUE TITLE
When hiking trails are shown, names of towns/villages disappear

### ISSUE THREAD

**Issue by mp3comanche** [osmandapp/Osmand#2098] opened 2015-12-30 17:39 UTC
When tourist routes (color-coded paths/hiking trails/wanderwege) are displayed (enabled), they conflict with local village/town through which the trails pass. Such local names disappear when hiking trails are enabled in OSM and appear just briefly and randomly when changing zoom, only to disappear again at the slightest movement of the map or sometimes even without any map movement (the names just blink in and out and stay out). When trails are disabled, all local names are back. 
Example (area: N 50°31.13393', E 16°0.51575'):
--> trails are OFF, you can see "Suchovršice" and "Úpice" (local settlement names) rendered correctly in black:
![screenshot_2015-12-30-18-06-51](https://cloud.githubusercontent.com/assets/5768232/12054125/83ee6ee0-af20-11e5-8e24-b1aa6b719c6c.jpg)
--> identical screen, but with trails ON, you can see that "Suchovršice" and "Úpice" (local names) are not shown, while trails are:
![screenshot_2015-12-30-18-06-16](https://cloud.githubusercontent.com/assets/5768232/12054131/95c8d1c8-af20-11e5-84b0-9e256a205f37.jpg)
Note: Based on the above pics, it also appears that road numbering conflicts with street names (see 3012 in lower part of pic 1, in pic 2 there is this street's name shown correctly as "Poděbradova") - is this the same/similar issue?

Thanks for your attention and any replies.

**Comment by sonora** [comment] 2016-01-02 20:11
Well, in a way it is by design: Choosing the Hiking Symbol Overlay assumes that this is for now the most important thing you need to see, so it is put on top, and things below it are omitted wherever they would interfere, to reduce visual clutter and improve visibility. I agree that omitting village names may be overdoing it, Leonid should probably comment on this.

PS: Similarly, the labeling of street names and the display of street ref shields is dynamic to some degree, so it differs in different map configurations as space is available (or not).

**Comment by xmd5a2** [comment] 2016-01-02 20:20
Fixed by lowering osmc text priority to lower values than any "place" tag.

**Closed by xmd5a2** 2016-01-02 20:20 UTC

**Comment by mp3comanche** [comment] 2016-01-06 19:25
Thanks, folks.
