### ISSUE TITLE
Stop track recording after save

### ISSUE THREAD

**Issue by Ungoose** [osmandapp/Osmand#8911] opened 2020-05-07 14:46 UTC
Currently, when I hit “Save current track,” the track is saved but recording is resumed automatically. This can be quite an inconvenience, especially during hiking or cycling trips where one-handed use is common and keeping screen time to a minimum is important. Is it possible to add an option for customizing this behavior? Something like “Auto Resume Recording” in plugin options? Thanks.

**Comment by njohnston** [comment] 2020-05-07 15:43
Recording continues until you stop it. If you don't want to continue recording, first stop recording, _then_ save the track.

**Comment by Ungoose** [comment] 2020-05-07 16:12
> 
> 
> Recording continues until you stop it. If you don't want to continue recording, first stop recording, _then_ save the track.

That is true, and that is how I am saving my tracks now. However, this procedure requires going to the menu twice and requires four taps where it could be accomplished in two), which is inconvenient and a little bit tedious when you do it several times per trip. A solution here would be to have a single "stop and save" button (like the current "Save current track"), just with the auto-resume feature toggled on and off depending on user preferences.

**Comment by vshcherb** [comment] 2020-05-08 15:19
Agree it would be more convenient to stop after saving (or have an option in save dialog)

**Comment by Ungoose** [comment] 2020-05-08 17:33
Thank you! 
I too think it would be more convenient to stop after saving (especially since it’s possible to restart recording with a single tap). I only suggested having an option because I assumed that some people find auto-resume useful.
On a side note, adding an option in the save dialog will introduce an extra tap for every file. On the other hand, having a switch in plugin settings would allow a one-tap start, one-tap end recording.

**Comment by sonora** [comment] 2020-05-09 07:26
The problem is the following: If we had a combined option 'stop recording and save track', accidentally tapping it has an irreversible outcome. So either we introduce yet another 'Are you sure' confirmation tap, which I would hate because for runners it would delay when the action is  actually executed after crossing the finish line, or we leave things as is with 2 separate actions.I think how we have it now is not a bad compromise?

**Comment by Ungoose** [comment] 2020-05-09 08:07
> 
> 
> The problem is the following: If we had a combined option 'stop recording and save track', accidentally tapping it has an irreversible outcome. 

I absolutely agree that adding another "Are you sure" confirmation is undesirable - at least for saving. However, 'stop recording and save track' are already combined under "Save" button. So
the outcome is already irreversible (tapping "Save" stops recording, saves the track, and resumes recording), it just has an extra step that is inconvenient for some uses. Adding the “Auto Resume Recording” switch in options will just allow choosing whether the third step occurs or not. 
In fact, adding this setting will not eliminate the "2 separate actions" route - it will just add the possibility to take a shortcut.

**Comment by eumiro** [comment] 2020-05-13 09:57
I usually “pause” the tracking when immediately needed (single click in the notification bar) and “save” (and export) it only later when I have both hands free. So there's apparently no need to do both actions immediately.

**Comment by Ungoose** [comment] 2020-05-13 11:29
This is indeed a valid approach, and probably one intended by the developers. However, as is common with OsmAnd, it will work for some situations but not others. For instance, I record several tracks for different purposes during a single trip. Pausing the recording will produce a single GPX file with disconnected segments, which may be preferable or inconvenient depending on users' goals. 
In any case, note that the app already does both actions immediately when you press "Save current track" without pausing first. The goal of this request is to give users a choice whether the recording will auto-resume. In fact, the "pause now save later" route will not be affected by this addition at all.

**Comment by sonora** [comment] 2020-05-18 06:16
Ok, it appears to me that the use cases for 'Save track but continue to record' are slim to none, hence I recommend we do not invent yet another option but simply change the current action from 'Save' to 'Stop recording, save track'. (Likewise use 'Stop/save') in the recording notification.)

If we are in agreement I can offer to implement that fix.

**Comment by Ungoose** [comment] 2020-05-18 06:28
I am certainly ok with this, thank you.

**Comment by sonora** [comment] 2020-05-18 21:27
@vshcherb Unless I am overlooking something, this should do the trick: https://github.com/osmandapp/Osmand/pull/8996

But please take a moment to review, it is may a little involved due to all the different settings and profile dependencies we have implemented around track recording with and without navigation lately.

**Comment by Ungoose** [comment] 2020-06-05 15:15
Finally had a chance to try it out and looks like it did not work. :( In both 3.7.2 and 3.7.3 track recording still resumes after the Save button is pressed.

**Comment by sonora** [comment] 2020-06-05 17:55
We may have just too many way to perform the same action , and that's hard to maintain ... ;)

It is fixed for the map screen widget, for the system notification, and for the Dashboard.

But there may be more "Save current track" buttons... Which one are you talking about?

**Comment by sonora** [comment] 2020-06-05 18:54
That's strange, I cannot reproduce it: For me it works. Are you sure you have no otter setting active which would cause a recording, like e.g. `Auto-record track during navigation`?

**Comment by Ungoose** [comment] 2020-06-05 19:03
No, this one is definitely disabled, and I have noticed no other settings that would cause this behavior. I will try it on another device or after a full uninstall. 
In any case, thanks for your efforts. Hope it will work for me as well sooner or later.

**Comment by sonora** [comment] 2020-06-05 19:07
How about when you use the Save button when you pull down the Android system notification? Same issue there?

**Comment by Ungoose** [comment] 2020-06-05 19:14
Yes, same issue. The track is saved but the recording goes on.

**Comment by Ungoose** [comment] 2020-06-05 19:29
I just installed the 3.7.3 version from here https://osmand.net/releases/ on my old tablet with Android 7 and observed the same behavior.

**Comment by sonora** [comment] 2020-06-05 19:32
@vshcherb I just notice, the fix was never merged to the release branch r3.7, an oversight? Because it works just fine in the master branch and our nightlies!

  - [ ] Secondary issue I just discover: We also have yet another button called `Save current track` on the Settings screen of the trip recording plugin, and this one (unlike all others) does not call method `OsmAndMonitoringPlugin.saveCurrentTrack(...)` where we have applied the fix. Instead, it calls `SettingsMonitoringActivity.saveCurrentTracks(...)`, so either we would have to insert the equivalent of a `stopRecording()` there also, or we could perhaps throw out the `saveCurrentTracks(...)` method and use `saveCurrentTrack(...)` instead.

**Comment by vshcherb** [comment] 2020-06-07 22:18
@sonora probably it's quite late, 3.8 is planned for next month and for a while people could use a nightly version instead. 
2nd issue not sure... I think it is a rarely called method and I'm not even sure who uses it. 

I wouldn't rush to merge to 3.7 anything except major/critical fixes any more.

**Closed by vshcherb** 2020-06-07 22:18 UTC

**Comment by Ungoose** [comment] 2020-10-30 16:49
Finally tried it out in 3.8 and the issue is finally gone - great news! No need to pause track before saving anymore. 
However, the issue persists for canceling the recording ("clear recoreded data" in the menu). Should a separate issue be created for that or can it be resolved here?
