### ISSUE TITLE
Track width reset to thin after app restart

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#11879] opened 2021-06-09 15:32 UTC
### How to reproduce?
Create track in Plan a Route > Save. The track will be shown as "thin" without changing any appearance settings, try to restart OsmAnd. After restart track became really thin, it seems its width is "Custom – 1", but right after saving and after restart track width appearance doesn't have any item selected.
Image 1: Two tracks after saving.
Image 2: changing width for second track, first track without any changes after saving
Image 3: track after restart
<img src="https://user-images.githubusercontent.com/9365308/121384275-c7b49780-c950-11eb-9e86-3999526a457b.png"  width="800" height="auto"/> 

### Your Environment
**OsmAnd Version:** 4.0.0#32135
**Android**/iOS version: 10

**Comment by njohnston** [comment] 2021-06-09 17:45
Related to or duplicate of #11827?

**Comment by vshcherb** [comment] 2021-06-10 20:56
no it's not related to default

**Comment by sonora** [comment] 2021-06-11 05:52
The first screnshot above also demonstrates the issue that our new track appearance dialog does not indicate the actual track width being used at all: Neither "Thin" nor "Custom" are framed.

And related: Should you e.g. manually set "Medium", then later tap on "Custom" to see what's actually being used, the Custom dialog will always falsely display '1'.

**Comment by vshcherb** [comment] 2021-07-06 09:44
Merged with #11827 reason is the same. App defaults from with "thin" to custom "1"

**Closed** 2021-07-12 11:26 UTC
