### ISSUE TITLE
Filter GPS speed fluctuations near 0

### ISSUE THREAD

**Issue by pl71** [osmandapp/OsmAnd#19230] opened 2024-03-02 13:40 UTC
### Describe the idea (required)

1. Assume vehicle is stopped if GPS speed is less than 2 km/h
2. Assume vehicle is oriented properly (as per route calculated) in the beggining.

### Tell us about the expected behaviour (required)

Do not rotate car icon when speed is too low.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/4776779/65b3769b-da90-4e23-8c53-69f069bedc97"  width="300" height="auto"/> </td>
  </tr>
</table>

### Tell us about alternatives you've considered (required)

Icon should stay fixed. A car can't rotate too fast.

### Context (optional)

Kalman filter is ON.
_No response_

**Comment by sonora** [comment] 2024-03-03 14:00
I believe our default behavior is acually like you say it should be. Perhaps check the settings of you car profile, 'Kalman filter' should be on, and 'Use magnetic sensor' off.

**Comment by yuriiurshuliak** [comment] 2024-03-04 16:44
The bug has been reproduced. I attempted to reset the driver profile settings and reproduce the issue with standard settings, enabling the 'Kalman filter' and disabling 'Use magnetic sensor.'

In the first video, I attempted to initiate car navigation while moving on foot. In the second video, I simulated navigation at fixed speeds of 3 miles. The issue persists in both scenarios.

OsmAnd~ 4.7.0#1740m, released: 2024-03-04

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/c0814571-e2b5-4b78-8861-8fa809b6bce0"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/cdb2b482-e82e-4750-a7f1-d52fcba14988"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by pl71** [comment] 2024-03-04 20:20
> I believe our default behavior is acually like you say it should be. Perhaps check the settings of you car profile, 'Kalman filter' should be on, and 'Use magnetic sensor' off.

Yes, my settings are exactly the same. I don't know what Kalman filter exactly does, suppose it suppresses some GPS glitches. In fact it should be more aggressive at low speeds.

**Comment by Chumva** [comment] 2024-03-26 13:30
This should be fixed [here](https://github.com/osmandapp/OsmAnd/pull/19393) if snap to road is enabled & we follow route

**Closed by Chumva** 2024-03-26 13:30 UTC
Labels: and-bugs

**Comment by pl71** [comment] 2024-03-26 15:06
Where is snap to road?

**Comment by dmpr0** [comment] 2024-03-27 10:08
> Where is snap to road?

Menu – Settings – Select profile – Navigation settings – Map during navigation

**Comment by pl71** [comment] 2024-03-27 11:45
Yes, it is ON. I hope to be fixed at the next release. Otherwise, it is not common for a car to rotate so fast.

**Comment by limex** [comment] 2024-04-02 17:28
> This should be fixed [here](https://github.com/osmandapp/OsmAnd/pull/19393) if snap to road is enabled & we follow route

I'm confused. This fix is also relevant for non-driving profiles. Like hiking. Currently when standing, often there is still movement "detected". Leading to not showing the **viewing** direction, because the **movement** direction arrow is shown instead. 
But: There are often no roads we are walking at, we don't want to be "fixed" to the track. We want to know when we are off-track.
This is a major pain for hikers since 4 years. I trust that this fixes our our issues.

**Comment by vshcherb** [comment] 2024-04-02 18:50
> This is a major pain for hikers since 4 years.

Appellation to something going long enough without clear decscription won't work  cause of multiple and emotions don't help to make right decisions.

Movement direction is detected by GPS signal / driver so it depends on device / operating system. Viewing direction provides even worse results when movement detected 
So I think primary issue is wrong movement detection and fix is unknown yet.

**Comment by pl71** [comment] 2024-04-02 21:08
GPS fluctuations are not sometnig new. They exists for all positioning systems as well. Up to the software is to filter them appropriately. Car profile assume you are in an average car from mass production, not in Ferrari. Accelaration should be within some limits. As well as rotating speed. At low speeds (for example < 5km/h) you can't rotate too fast.

**Comment by limex** [comment] 2024-04-03 08:00
> GPS fluctuations are not sometnig new. They exists for all positioning systems as well. Up to the software is to filter them appropriately. Car profile assume you are in an average car from mass production, not in Ferrari. Accelaration should be within some limits. As well as rotating speed. At low speeds (for example < 5km/h) you can't rotate too fast.

You didn't understand my concerns. Let me make it clear: 
Don't bundle the new fix to the setting "snap to road"! Please! 

Because "snap to road" is bullshit when you are out in the wild. You dont want to be snaped to road. You want to know when you are off track!

**Comment by limex** [comment] 2024-04-03 08:08
> > This is a major pain for hikers since 4 years.
> 
> Appellation to something going long enough without clear decscription won't work cause of multiple and emotions don't help to make right decisions.
> 
> Movement direction is detected by GPS signal / driver so it depends on device / operating system. Viewing direction provides even worse results when movement detected So I think primary issue is wrong movement detection and fix is unknown yet.

1. Thanks for taking care of this.
2. Sorry for me being emotional but ...
3. ... since 4 years Hikers wrote numerous tickets, comments to get heard by the motorist's fraction of the OSMand Users/Developers.
4. Don't get me started on the "depends on device / operating system." statement. We had that over and over. Everytime we convinced one "motorist" he/she disappeared and another one showed up. #groundhoundday

Anyway. Thanks again that you are moving things forward.
 
And: I hope this fix standalone. Which means: It is not enabled with the "snap to road" setting. Please confirm.

**Comment by vshcherb** [comment] 2024-04-06 15:22
@limex I didn't understand much, only your statement that I didn't understand. Nothing is going to change if keep your messages short and precise.

Please describe what's the issue you occur, probably better start a new thread. Please focus on your issue, what do you want to achieve, what's your situation.  Don't focus on any specific solution cause it might not work for other scenarios

**Comment by limex** [comment] 2024-04-06 15:38
@vshcherb 
This explains everything in detail:  https://github.com/osmandapp/OsmAnd-iOS/issues/3553
 
But: Let's start from here:
Question: will the new fix "Filter GPS speed fluctuations" also be enabled, if the "snap to road" is disabled?
If YES: You are our hero, we will praise you for fixing an 4 year issue.
IF NO: We need to talk

**Comment by vshcherb** [comment] 2024-04-06 15:46
Ok, I will stop conversation and reply in https://github.com/osmandapp/OsmAnd-iOS/issues/3553#issue-2220829815 cause it's not you a topic starter. No description - no bug.
