### ISSUE TITLE
Wrong directons display

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8216] opened 2020-01-13 08:27 UTC
While riding 
from: -20.3002, 57.5361 
to: -20.29848, 57.53565
the directions in the upper-left corner of the screen display to take the second road to turn left, while there is a curved turn to the right is available only. 
![image](https://user-images.githubusercontent.com/50198677/72241350-4d62d500-35ef-11ea-80b1-b0f224bee2b0.png)

**Comment by Discostu36** [comment] 2020-01-13 13:17
Duplicate of #7668

**Closed** 2020-01-15 14:50 UTC
