### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#6571] opened 2019-02-20 15:19 UTC
Nightlies dated 19th and 20th Feb 2019 crash on launch. Only the flash screen appears for a second, and then vanishes. There is no error report/pop up.
 
Reporting for Android Pie 9 on ZenFone 5z.

**Comment by jfburke3** [comment] 2019-02-21 18:08
Having this problem, too, on Android 8 (Galaxy S7) and Android 9 (Galaxy S9).

At first, it ran fine for an hour or two, before crashing, and now I have the crash-during-launch problem as well.  Tried rebooting, tried deleting ind.cache.

**Comment by Zahnstocher** [comment] 2019-02-21 23:24
Duplicate of https://github.com/osmandapp/Osmand/issues/6570

**Closed** 2019-02-25 15:14 UTC
