### ISSUE TITLE
Opening overlay by quick-action; transparency seekbar is not visible, but "on"

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#5043] opened 2018-02-20 11:31 UTC
I open a overlay with a quick action, the overlay becomes visible, but "transparency seekbar" is not visible.
When I open the setting for overlay (by ...), the option "show tranparency seekbar" IS already  ON. 
If I want to show tranparency seekbar, I have to uncheck it, then to check it.
Version 2.9.0#23791

**Comment by rindlerblabla** [comment] 2018-02-20 11:57
Duplicate of #4944?

**Comment by pebogufi** [comment] 2018-02-20 12:00
May be partially, but what I want to point out is, the setting "show tranparency seekbar" IS already ON.
There is only a refreh necessary or something like that missing.

**Comment by pebogufi** [comment] 2019-03-20 08:33
Sometimes it works, sometimes not...
3.3.0#27028

**Comment by iriman** [comment] 2019-10-22 14:06
@vshcherb Maybe found its misbehavior:

* Turn on underlay using quick action:
  * If seekbar doesn't show up, then turn on (or maybe off then on) the _seekbar_ via menu. It should now be displayed.
  * If seekbar is showing up, then turn off _underlay_ via menu. Seekbar won't be displayed again if we use quick-action to turn on underlay.

Seems quick-action will forget about options if we use menu for switching underlay on/off.

**Comment by vshcherb** [comment] 2019-10-29 09:40
Moved to https://github.com/osmandapp/Osmand/issues/7750

**Closed by vshcherb** 2019-10-29 09:40 UTC
