### ISSUE TITLE
[Question] Online vs Offline Navigation and Maps

### ISSUE THREAD

**Issue by seniorm0ment** [osmandapp/OsmAnd#17511] opened 2023-06-27 02:04 UTC
Looking for clarification as to which most users use for driving, and how they work?

So for the vector maps, do most people use one or another? Do they switch between the two? A bit confused as to what each offers. 

Also if you choose online, if you happen to lose connection in a bad area, does maps start having issues? Or does it fallback to offline, and then switch back to online when it gets reception?

As for the navigation, same question. It seems like the way it navigates changes. Also the lane indicators at the top of the screen don't seem accurate on one of the modes, I think the online one. Like it'd show 4 lanes when it's only 2. But in the past I've driven on that road and it shows 2.

Also same question, currently I use online and it seems buggy. Not sure if its the app or not. But it SEEMS if I lose reception, the navigation freaks out and just refuses to work?

**Comment by Spielmops** [comment] 2023-06-27 16:52
Use offline i.e. vectormaps all the time. But keep them uptodate (3 month is enaugh). I am a traveller, just came back from 8 weeks in UK. About 6 roundabouts not in maps, that was all. Navigation was ok, but if you prefer certain highways, use waypoints.

Spielmops

**Comment by seniorm0ment** [comment] 2023-06-27 19:46
>use offline vectormaps

What is the reasoning, instead of online?

>but if you prefer certain highways, use waypoints.

Can you elaborate on this?

**Comment by sonora** [comment] 2023-06-28 06:11
> What is the reasoning, instead of online?

OsmAnd is designed to be used entirely offline, uses its very own routing engine for this purpose, and you are independent of mobile reception and corresponding glitches. OsmAnd also supports several online routing engines but has little to no control over their capacities, features and glitches, in particular also when mobile reception is flaky..

> but if you prefer certain highways, use waypoints.

OsmAnd calculates the offline route for the specified means of transport and parameters, by default trying to find the fastest one. If you want to force OsmAnd to take a certain highway, or go via a certain location, you may specify a point on that highway or that very location as an "interim destination" using OsmAnd's routing dialog, or the location's context menu (tap/long-tap it on the map, chose "Navigation > Select as interim destination"). Setting an interim destination may be required for very long routes (>>250km) in order for the offline routing engine to find a solution within acceptable time.

**Comment by scaidermern** [comment] 2023-06-28 06:20
> As for the navigation, same question. It seems like the way it navigates changes. Also the lane indicators at the top of the screen don't seem accurate on one of the modes, I think the online one. Like it'd show 4 lanes when it's only 2. But in the past I've driven on that road and it shows 2.

The offline routing engine has more features and supports more configurations than most online routing engines. That's why the user experience with online routing won't be as good as with offline routing. The only exception is probably the time it takes until the route has been calculated, this will always be faster with online routing due to limited resources of mobile devices.

**Comment by seniorm0ment** [comment] 2023-06-28 13:11
Did not know about the interim destination thing. That is good.

Also good information. The biggest issue I notice with offline maps, compared to online is that it is insanely slow and takes a while to load. 
On a Pixel 6 Pro, not exactly an underpowered device. 
Online maps are instant, smooth and responsive. Offline stuff takes forever to load in it seems. 
Is this something that is being worked on?

**Comment by sonora** [comment] 2023-06-28 13:41
Perhaps you can quantify "insanely slow" to see if there is a bug or something you can fix in your setup. Some devices seem to have performance issues with some storage locations since the latest escalation of google's storage limitations.

On average, I would say complete screen redraw should be sub-second in most situations (which is 100% faster than online for the odd case you lose your data conection in tunnels, mountains, wilderness, etc... 😉 😉 😉).

**Comment by seniorm0ment** [comment] 2023-06-28 14:41
So zooming in and out, takes maybe 8ish seconds to actually render the tiles (all the roads and stuff). It'd be like a blank grid then tiles would start popping in. and then the road names would be all blurry, and be not in the exact spots. Give it a few more seconds and it all the road names shift a little, become clear, road lines become clear, etc. And all is good.

It is not a good user experience at all, and is a major enough issue for me. This might have been why I had switched to the online maps in the past. But yeah losing connection seemed to mess with things so that's why I came here to see what others do.

When using online, everything is absolutely buttery smooth. Looks like high refresh rate, nothing missing or blurry or slow to load in. Zoomimg in and out and panning.

Don't notice these issues on other apps such as Snapchat maps, Google Maps, or even Organic Maps. It's an OSMAnd issue for me.

Maybe worth mentioning I am using GrapheneOS, with Google services enabled.

**Comment by vshcherb** [comment] 2023-06-28 15:20
Discussion may continue but the issue is closed as no action

**Closed by vshcherb** 2023-06-28 15:20 UTC

**Comment by DmitryAlexei** [comment] 2023-06-28 18:02
You can read more about OsmAnd routing by the link
https://osmand.net/docs/user/navigation/routing/osmand-routing

**Comment by seniorm0ment** [comment] 2023-06-28 20:54
How would I know which data folder to use? Why would it use one that might have issues to begin with?
Also it's all internal storage, so no sd card or anything obviously

**Comment by sonora** [comment] 2023-06-28 22:45
Can't say - I only remembered comments like https://github.com/osmandapp/OsmAnd/issues/10453#issuecomment-1483860476, which seems to have helped users on some devices.

**Comment by seniorm0ment** [comment] 2023-06-29 00:35
One comment states

Try moving to
/storage/emulated/0/Android/ media /net.osmand.plus/files
Use "manual" for setting path

I'm not seeing the option to set path when downloading.
Any ideas about this?

**Comment by scaidermern** [comment] 2023-06-29 05:02
> I'm not seeing the option to set path when downloading.

This is a global setting, not per file.

Check Settings / OsmAnd settings / data storage folder.

**Comment by Spielmops** [comment] 2023-07-06 18:12
Workaround to prevent dataloss: rename the folder with one more letter, let Osmand do its work and check, if it is ok. If yes, delete the renamed folder, if not, it's your backup ...
