### ISSUE TITLE
Opening POI info by a click (press and hold) on map

### ISSUE THREAD

**Issue by majkaz** [osmandapp/Osmand#5040] opened 2018-02-19 11:19 UTC
Did something changed in the code?

Previously, it was possible to click on the POI location and it opened info for nearby POIs. Currently, the same action starts location search and completely ignores the POI visible on the map at the same place.

At the moment, it is necessary to have the POI-layer switched on ("nearest POI") to get to the same info. This wasn't the always the case, one could get the same with the POI layer switched off.

Osmand version: 2.9.0#10182mqta, dated 2018-02-19

**Comment by pebogufi** [comment] 2018-02-20 16:57
I am not shure whether it is meant by this topic, but it looks at least simular to me.
The list of "Nearby Wikipedia acticles" is lost in newer version. Here is a screenshot of 3.0.0#23189
![screenshot_2018-02-20-17-53-30](https://user-images.githubusercontent.com/18628183/36437424-3ad64222-1667-11e8-9d29-cda9b09d7a17.png)

**Comment by dmpr0** [comment] 2018-02-20 17:02
@majkaz Could you please send screenshot of the map. Maybe you turn of POI icons on the map. Check it on "Menu - Configure map - Hide - POI icons".

**Comment by majkaz** [comment] 2018-02-20 18:12
@dmpr0 
No, I can see the icons without problems. That is not what I meant.
BUT:
Few versions ago, it was possible to get to the POI details without having POI layer switched on, you simply had to pick it on the map. [Currently](https://drive.google.com/file/d/1gKfcpEhy_VqHh9OJ4TpUU9V1PwJPqrwj/view?usp=sharing), it doesn't work any more. You simply have to switch the POI layer to get to the info.

With [POI layer on](https://drive.google.com/file/d/1X9S8di6OOS3xM2eDtbWr17yF1LRaITSk/view?usp=sharing)

Not sure when it changed.

**Comment by bambamal** [comment] 2018-02-20 23:40
I have the same issue. POIs are not selectable anymore.
I'm talking about the colored POI-symbols, NOT the ones from the POI-overlay. Tapping the POI-Overlay (orange markers) works just fine.

**Comment by PaulStets** [comment] 2018-02-23 10:42
@majkaz Could you please tell us the version code that has this error. Have you tried installing the newest nightly build?

**Comment by majkaz** [comment] 2018-02-23 11:07
At the moment when I have opened the issue, it was the latest nightly - see the initial message (Osmand version: 2.9.0#10182mqta, dated 2018-02-19) downloaded through the app itself.
I didn't try any later builds.

**Comment by majkaz** [comment] 2018-02-23 22:11
@PaulStets latest version (nightly 23.02.18; #23904m) works again as expected. 
"Dirty" upgrade was enough - install over existing app. No change in data or settings otherwise.

**Comment by PaulStets** [comment] 2018-02-24 06:04
@majkaz  In that case, I think we can close this issue. I suspect it was caused by the corrupt installation. Feel free to re-open it, if the issue reappears.

@pebogufi The screenshot  you've sent is from the old version. We have changed the menu since then. If you still experience the problem, please create a separate issue and we will look into it.

**Closed by PaulStets** 2018-02-24 06:04 UTC
Labels: Investigating
