### ISSUE TITLE
Indicate when Avoid... roads have been set

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2103] opened 2016-01-01 10:07 UTC
Avoid... roads are sticky between different navigations and may still be set while users are not aware of it. We do not indicate the fact if Avoid... roads are set, this sometimes leads to strange routes and pointless support cases.

We could at least eg indicate it on the Settings screen of our route config functionality if Avoid... roads are active, e.g by changing the button text label from "Select" to "Edit", and/or by changing the (construction sign) icon color to red or similar.

**Comment by vshcherb** [comment] 2016-01-05 08:44
Functionally duplicate of #2113

**Closed by vshcherb** 2016-01-05 08:44 UTC

**Comment by raindropsfromsky** [comment] 2016-01-16 19:25
Nope, this is not duplicate, but a supplementary suggestion.
(See #2113 for details)

**Comment by vshcherb** [comment] 2016-01-17 15:22
Yes, it is not a duplicate. This one is about having indiation that Avoid roads are turned on. For now it is not critical because Avoid roads are stored only temporarily and after restart they will be gone.

**Comment by raindropsfromsky** [comment] 2016-01-17 15:25
oh fantastic: Then there is no issue at all!

Thanks!

**Comment by sonora** [comment] 2016-01-18 21:32
Well, a restart of the app happens rather seldom under normal operating conditions (we don't even have an explicit EXIT button), and the "Avoid roads" are sticky between different routes/navigations, UNLESS the app (or the device) has really been restarted. My point was the user may nor be aware of this, neither notice that "Avoid roads" are still selected, unless we somehow indicate this.

But yes, I have looked at the code and it seems not so easy to make that dialog aware of whether selections have been made or not, so not a priority issue maybe.
