### ISSUE TITLE
The blue location dot becomes invisible when map is zoomed out.

### ISSUE THREAD

**Issue by anaxonda** [osmandapp/OsmAnd#17069] opened 2023-04-27 08:14 UTC
I have a recent problem where I cannot see the location dot, except when the map is very zoomed in. At the scale where building outlines are visible it is shown. When zooming out the scale of the blue dot also changes.

This seems to have been a problem just in the last few days without updating, however I am unable to find anything in the settings that pertains to it.

Hoping there is something in the settings I accidentaly changed.

**Comment by anaxonda** [comment] 2023-04-27 12:09
I figured out this is only when using opengl map rendering engine (2). Using 'map rendering engine 1' the location indicator is present on all zoom levels.

**Comment by Zirochkabila** [comment] 2023-04-27 19:12
@anaxonda The behavior is reproduced. But I'm not sure if it's a bug - needed to clarify this question with @vshcherb 


https://user-images.githubusercontent.com/104760013/234967744-a44f3c64-f086-4513-99cb-e52c49724c4a.mp4

**Comment by ChemoCosmo** [comment] 2023-05-03 06:55
I have the very same issue.
Device: Fairphone 3
OS: e/os 1.8.1
Osmand: ~4.3.12
Render-Engine: 2.0

I also know od someone else with this issue. 

https://user-images.githubusercontent.com/58092307/235849473-6c9eb0f5-7741-4bde-958a-8dfae23dd459.mp4

**Comment by sonora** [comment] 2023-05-03 09:05
When you switch to Render-Engine: V1, the issue is not present?

**Comment by anaxonda** [comment] 2023-05-09 09:16
Correct, switching to V1 the issue is not present.

**Comment by scaidermern** [comment] 2023-05-09 17:55
At least one user in the German Telegram group reports that this problem only exists when the height map is enabled.

**Comment by anaxonda** [comment] 2023-05-10 08:11
I just checked to see if disabling height map fixes the problem, strangely I have no option to disable/enable height map any more from plugins->Osmand Development->settings.

**Comment by scaidermern** [comment] 2023-05-10 08:51
> I just checked to see if disabling height map fixes the problem, strangely I have no option to disable/enable height map any more from plugins->Osmand Development->settings.

This option is only availabe with rendering engine v2. According to your previous post, you switched to v1.

**Comment by anaxonda** [comment] 2023-05-10 09:53
You're right. I can confirm that with height map disabled I can see the location indicator in  render engine V2.

**Comment by vshcherb** [comment] 2023-05-12 09:06
It should be fixed with https://github.com/osmandapp/OsmAnd/pull/17097

**Closed by vshcherb** 2023-05-12 09:06 UTC
Labels: opengl

**Comment by ChemoCosmo** [comment] 2023-05-14 16:19
The problem disappeared with updating from Osmand~4.3.12 to newly releslased Osmand~4.4.7.

Thanks a lot!
