### ISSUE TITLE
Small POIs not drawn in the right place

### ISSUE THREAD

**Issue by dead10ck** [osmandapp/OsmAnd#8788] opened 2020-04-12 22:50 UTC
On 3.6.3, it seems small POIs, such as door and gate entrances, are drawn slightly off from where they should be. A good example is in the San Francisco map at 849VCW4Q+85:

![Screenshot_20200412-153911](https://user-images.githubusercontent.com/846275/79081739-f5626a00-7cd4-11ea-88dc-ce24d76824c4.jpg)

And for comparison, here's the map in Vespucci:

![Screenshot_20200412-154003](https://user-images.githubusercontent.com/846275/79081756-188d1980-7cd5-11ea-9685-d438a6d54395.jpg)

All the door nodes are on this building, but some are drawn completely disconnected.

**Comment by Aiurek** [comment] 2020-04-17 07:18
Applies not only to entrances, but also to POIs like Shops, Restaurants,... mapped as point node as part of the area defining boarders of a building, leading to those POIs being illustrated like a few metres apart from the actual building

**Comment by vshcherb** [comment] 2020-04-17 16:45
Yes it applies to everything and probably it is a duplicate. We're going to disable that zoom level / prepare high detailed maps with high precision probably 4-8 times bigger size of the map

**Comment by matthijskooijman** [comment] 2020-09-15 16:35
This might be the same issue as #6130.

It's somewhat annoying, since I sometimes make notes about this in the field (e.g. about a gate that was mapped besides the road as a separate node, which sometimes happens), only to find that it is actually already correct when I get home.

**Comment by aceman444** [comment] 2020-10-19 16:35
@vshcherb , isn't this fallout from the "more precise placement of POIs", that was implemented some versions ago? Because I think this wasn't a problem in the past. Also, are 4-8 times bigger maps really needed? That would be quite heavy.
I know you have an algorithm that removes unneeded nodes from nodes, that barely affect geometry, thus optimizes the size of the maps. Can you try altering the algorithm to never optimize out nodes, that are shared by 2 objects? Wouldn't it fix this problem (and many others like disconnected buildings) ?

**Comment by vshcherb** [comment] 2020-10-23 13:47
Nope precise placement of POI's was implemented only for large objects, using it for small objects led to big data increase so we don't use it by default. Probably we could introduce a flag so people could build own map with precision locations

**Comment by aceman444** [comment] 2020-10-24 17:01
No, this must be enabled by default, because it is true that then advanced mappers think objects are placed wrongly in OSM there needs to be a fix in the data.
Also e.g. gates are drawn outside of fences and the road they are part of, which may be understood wrongly by map users, that there isn't a gate.

I think this problem didn't happen in the past, so if you didn't touch node objects placement recently (in the precise placement), it must be caused by something else.

**Comment by scaidermern** [comment] 2020-10-24 19:15
> I think this problem didn't happen in the past

It did, see #6130.

**Comment by MadWasp79** [comment] 2020-11-16 10:47
fixed with https://github.com/osmandapp/OsmAnd-core/pull/166

![image](https://user-images.githubusercontent.com/13146346/99243821-dfd49600-2809-11eb-85eb-a3f681dc8066.png)

**Comment by scaidermern** [comment] 2020-11-16 11:01
I guess this also solves #6130?

**Comment by scaidermern** [comment] 2020-12-16 10:26
> I guess this also solves #6130?

Nope, does still look the same with OsmAnd 3.9.1.

**Comment by vshcherb** [comment] 2020-12-16 17:52
To remove high expectation it won't make 3.9 release but the work is in progress :)

**Comment by vshcherb** [comment] 2020-12-16 18:07
Proposed solution wasn't correct we need to change data format and put extra bits of precision to POI

**Comment by ivanPyrohivskyi** [comment] 2021-02-15 08:34
https://github.com/osmandapp/OsmAnd-resources/pull/670
https://github.com/osmandapp/OsmAnd/pull/10848
https://github.com/osmandapp/OsmAnd-core/pull/199
https://github.com/osmandapp/OsmAnd-tools/pull/382
https://github.com/osmandapp/OsmAnd-resources/pull/670

**Closed** 2021-02-16 10:25 UTC
Labels: Nice to Have
