### ISSUE TITLE
Speed display does not change measurement unit when it is changed in settings

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#2690] opened 2016-06-13 10:13 UTC
This is OsmAnd+ version 2.3.5 using offline OpenStreetMap maps only, in the "Browse map" profile.

I have the "Current speed" displayed at the top right, along with elevation, GPS info and GPX recording items.  When starting OsmAnd, this is correctly displayed in the configured units.  However, if the measurement unit is changed in the "General settings" (e.g from kilometres/metres to miles/feet), the elevation unit here changes immediately but the speed unit does not.  The speed is still displayed in the old unit even after returning to the home screen and back to OsmAnd.  The only way to get the speed displayed in the correct units is to kill and restart the OsmAnd app.

This happens whichever way the unit is changed, whether by an explict choice from the "Unit of measure" option, or implied from the "Driving region".

**Comment by vshcherb** [comment] 2016-06-13 21:58
Workaround: restart helps. This setting is independently configurable in Navigation settings.

The issue is fixed in the new build.

**Closed by vshcherb** 2016-06-13 21:58 UTC
