### ISSUE TITLE
Increase priority for access=destination roads instead of motorway

### ISSUE THREAD

**Issue by gerhard-tinned** [osmandapp/OsmAnd#13740] opened 2022-02-11 20:57 UTC
# 🐞 routing report

This is partly linked to "OsmAnd is not choosing the optimal route" #13356 .

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car routing profile

### Start and end points

Startpoint: Schlachthammerstrasse 97, 1220 Wien
Endpoint: Stadlauer Straße 41A/Hof 4, 1220 Wien

<details>
    <summary>Details</summary>

![Osmand_BAD_route](https://user-images.githubusercontent.com/1536065/153668873-f38af8f7-325e-497b-a26a-d6cad9cde030.jpeg)

</details>

### Actual and expected routes

The route calculated by Osmand is about double as long in distance and time. Additionally, the route leads literaly onto the highway and exiting trough the tunnel walls - there is no exit. In short, it is impossible to follow that route!!!

<details>
    <summary>Details</summary>

![Osmand_BAD_route_detail](https://user-images.githubusercontent.com/1536065/153668868-08b91b97-c71f-410f-a6bb-9ebf1ddd94bf.jpeg)

</details>

I have used a different openstreet map based routing app to show the correct route. 

<details>
    <summary>Details</summary>

![Correct routes](https://user-images.githubusercontent.com/1536065/153668863-82ae9937-0570-4301-a3f5-68ce00b18b8a.jpeg)

</details>

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

I do not know if this particular route works in previous versions. I do know that I had overly long routes and huge detours in the routing in the past.

## 🌍 Your Environment

**OsmAnd Version:** 

<pre><code>

4.1.11, released: 021-12-15
</code></pre>

**Device and Android/iOS version:** 11 (OxygenOS 11.0.

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

Is there any way to fix that broken route calculation or use a different routing engine???

**Comment by Lee-Carre** [comment] 2022-02-12 12:59
> … the route leads […] and exiting trough the tunnel walls — there is no exit. In short, it is impossible to follow that route!

Part of the problem sounds like inaccurate map data, which should be fixed first.

Though, that detour route is amusing; quite the long way around(!) 😄

**Comment by Lee-Carre** [comment] 2022-02-12 13:29
> Startpoint: Schlachthammerstrasse 97, 1220 Wien
> Endpoint: Stadlauer Straße 41A/Hof 4, 1220 Wien

It took quite a while to find these on the (Web) map. Nominatum wasn't able to resolve the destination string.

In future, supplying coördinates or (better) a link would be far less ambiguous (perhaps the report template needs to be updated).

In the course of my digging, I yielded [a route which matches the original](//www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.21250%2C16.52270%3B48.23307%2C16.45536).
However, when changing the destination only slightly (and changing nothing else) the [optimal route](//www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.21250%2C16.52270%3B48.23301%2C16.45552) was yielded.

So, how exactly was that destination given to OsmAnd?

**Comment by Lee-Carre** [comment] 2022-02-12 13:59
> Is there any way to […] use a different routing engine?

Yes; in the profile configuration, under `navigation type`, you can use a Web-based API (of your choosing) for supplying routes. This, of course, requires that you have some kind of Internet connectivity (at the time the route is requested, at least).

Though, given my earlier comments, the assumption that the routing algorithm is faulty, and that a different one will yield better results, is demonstrably false. Especially when, as you say, the map data isn't accurate.

**Comment by gerhard-tinned** [comment] 2022-02-12 14:01
I am sorry. Did not know that. On the other hand my previous experience is that is gets closed without any attempt to fix it anyway so ... well, I hope this time is different. 

It does not help to change the destination by a few meters when the destination was selected by the address provided. 

I also think it should calculate the correct route even if the destination is a perfectly valid address (of a business by the way). 

The Destination was provided as I copy-pasted it "Stadlauer Straße 41A/Hof 4, 1220 Wien" which is the official address of the "Werksalon Co-Making Space GmbH".

**Comment by gerhard-tinned** [comment] 2022-02-12 14:05
>  Especially when, as you say, the map data isn't accurate.

Can you elaborate on this? What is wrong in the map data? And why do other openstreetmap navigation tools still manage to route correctly if the map data is bad? Would be interesting to understand it by getting more details. Thanks

**Comment by Lee-Carre** [comment] 2022-02-12 15:11
> […] my previous experience is that is gets closed without any attempt to fix it anyway so … well, I hope this time is different.

Which is why quality, thorough problem-reports make a difference. Firstly by checking that it is actually a problem with (in this case) OsmAnd.

Tickets can be reopened. So, opening a duplicate, instead of commenting in the original, is spammy. It contributes to maintainers being more hasty in closing dubious tickets.

While *ideally* tickets wouldn't be hastily closed, developers are busy, and the more time spent doing triage on tickets is less time for actual development.

There are frequent reports complaining about bad routing in OsmAnd, which often turn out to be a result of inaccurate map data. Software isn't magic; garbage in, garbage out.

Besides, even if the map data were (somehow) perfect, routing is imperfect. Graph Theory is far from a solved problem in mathematics, let alone computer science.
Perfection is difficult (read: practically impossible) to obtain, especially in every situation (including weird edge cases). Frankly, given that OSM (& arguably digital mapping) is still in its infancy, I'm often impressed that it does so well in most cases. But, then, I have technical insight into some of the challenges.

To elicit a desirable outcome, focus on helping the developers (or, since I notice you have experience with software development, contribute some PRs). If a user sounds like they're whining, amid complaining, then that tends to not be received well. Imagine being on the receiving end of that, every day.

> It does not help to change the destination by a few meters when the destination was selected by the address provided.

That entirely misses the point, and falls foul of what I had just advised against.

You seem to expect software to be flawless.

Simple example, for name-to-coördinates resolution problems; if the user inputs a city name (because they're travelling from another city), where ***precisely*** should the resolver place the marker? A city is a large area.

Just use the computed centroid? Well, what if the user doesn't want to go to the city-centre, but only the suburbs? He'll complain about bad routing.

Well, place it at the (nearest) outskirts, then? And what about the user who wants to go to the other side of the city? He'll complain about bad routing.

Seeing the pattern?

Or, in a different context; when a camera detects that the scene is too dark, should the auto-mode fire the flash (if allowed to) or increase the exposure-time, or increase the sensitivity, or open the aperture? How should it determine the trade-offs between each of those? Much of it comes down to the intentions of the photographer. Last I checked, software can't read the minds of users. So, if it has to make a decision (because it's not allowed to ask the user), then it'll have to make a guess, which is liable to be wrong.

I notice that you've contributed to a multimeter repo; imagine a user complaining that his multimeter didn't select the correct measurement mode for him (let alone the correct range). Well, how's the meter supposed to know?

OsmAnd did as it was told to; find a viable route to the coördinates which it was supplied with. If you're unhappy about the coördinates supplied by the address-resolver, well, that's a different problem. See my earlier remarks about the problems of address-to-coördinates resolution.

Another factor which comes to mind is that smaller access roads might be missing near the destination. Else, you expected the car profile to navigate a pedestrian area. Instead, set the carpark as the destination, since the remainder will be on foot.

Notice that, at the end, OsmAnd draws a straight line from the nearest road to the destination point. So, it's making a best judgement from ambiguous input.

> […] it should calculate the correct route even if the destination is a perfectly valid address (of a business by the way).

That's not how it works. Software needs coördinates. Thus, for human-readable input it relies on some kind of scheme to map from address to coördinates. Compare DNS; how would a host connect if it can't resolve the hostname to a numerical address?

How would software know what address is ‘perfectly valid’ or not? To software, human addresses are just text strings. Even to humans, textual addresses are ambiguous & messy. I often send people a geo: URI with coördinates (e.g. in messages), instead of a description, address, directions, or whatever. A URI is much more succinct, and unambiguous. If they want to navigate there, it's easy for them to pass the data to their favourite app.
Compare developers communicating with code snippets, for clarity instead of natural language descriptions, or in OSM we often refer to features by mentioning the relevant tagging (`amenity=parking` or whatever). Same idea.

Complaining that it should just auto-magically work *anyway* doesn't help. It ignores the problem (while demanding that someone else fix it).

> The Destination was provided as I copy-pasted it "Stadlauer Straße 41A/Hof 4, 1220 Wien" which is the official address of the "Werksalon Co-Making Space GmbH".

Where was this pasted? Into OsmAnd's `search`?

‘Official address’ is meaningless to software in this context.

Sounds like this maker-space needs to work on improving their OSM presence.

**Comment by Lee-Carre** [comment] 2022-02-12 16:39
> Else, you expected the car profile to navigate a pedestrian area. Instead, set the carpark as the destination, since the remainder will be on foot.

Having examined the map around the destination a little more closely, I noticed a couple carparks to the south-east. Setting either as the destination yields an efficient route (consistently, with either OSRM or GraphHopper).

Interestingly, when using the [same end-points that yield the objectionable route, but selecting GraphHopper as the algorithm, it suggests a radically different route](//www.openstreetmap.org/directions?engine=graphhopper_car&route=48.2125%2C16.5227%3B48.2331%2C16.4554) entirely. This suggests that the algorithms are having to guess (and each guesses differently).

Likely because they're being asked to do something invalid; find a route to drive up to the door of the building (in what I would assume, from various clues, is a pedestrian area).

Why the difference (for our budding student)? Well, because you're telling the algorithm to traverse a different part of the graph. So, yeah, the result will be different. Especially when there are no edges for it to traverse near the destination. So, it found the nearest vertex.

Better results require
* giving it valid input (setting destination to somewhere it can reach, such as the nearby parking)
* improving the map, so that it has more & accurate information to find optimal routes — for example, it appears that some of the carparks don't have connecting ways; checking signage for who's allowed to park there (and setting a suitable value for the `access` key) along with duration and other characteristics / properties; marking footpaths within the pedestrian area

I'm now starting to see why #13356 was closed. It's not a problem with OsmAnd, itself. 🙄

Smarter use of OsmAnd includes
* setting the carpark as an intermediate destination, and the entrance door at final, since you'll have to change mode of transport anyway
* for auto-switching profiles (from driving to walking), use the route planner with destinations like above, and select by-car for the first leg, and walking for the last

I'm reminded of an old quote
> “On two occasions, I have been asked [by members of Parliament], ‘Pray, Mr. Babbage, if you put into the machine wrong figures, will the right answers come out?’ I am not able to rightly apprehend the kind of confusion of ideas that could provoke such a question.” — Charles Babbage (1791-1871)

**Comment by pebogufi** [comment] 2022-02-12 17:04
THANKS A LOT to @Lee-Carre for this very detailed explanations !!!

**Comment by Lee-Carre** [comment] 2022-02-13 08:59
> you expected the car profile to navigate a pedestrian area

> Is there any way to fix that broken route calculation[…]?

After having slept, I had a different idea. I requested a [route using the same destination as originally, but selecting an on-foot profile](//www.openstreetmap.org/directions?engine=graphhopper_foot&route=48.2125%2C16.5227%3B48.2331%2C16.4554); it yielded a route much closer to what the OP demands 😄🤦‍♂️.

**Comment by Lee-Carre** [comment] 2022-02-13 11:17
An illustrative example of how map data can significantly affect routing, since I feel that it may help solidify several abstract concepts described earlier (and I seem to have attracted [an appreciative audience](/osmandapp/OsmAnd/issues/13740#issuecomment-1037313322) of my surgical analysis & rants 😉).

---

I like visiting the [library](//www.openstreetmap.org/way/185953209) when I'm able. My route toward it approached from the West. The building is part of a row (block?) of buildings which run North—South, with different roads on each side. The [only (public) entrance](//www.openstreetmap.org/node/9156456496) (& `entrance=main`) is on the Eastern side ([Halkett Place](//www.openstreetmap.org/way/227189363)). None on the Western side ([Don Street](//www.openstreetmap.org/way/116346609)). To [walk between the East & West sides](//www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=49.18664%2C-2.10490%3B49.18654%2C-2.10426) requires going around the block of other buildings; a several minute walk.

At the time, no entrances had been mapped; just the building's outline (from aerial imagery).

The effect was that, when approaching from the West, I would be routed to the back of the building ([Don Street](//www.openstreetmap.org/way/116346609)), since that was nearest. If the building stood alone (detached), then no problem; just walk around the perimeter to the (eastern) front. However, there are many other adjacent buildings, so the path involves several other roads. So, being routed to the back of the building, even if it's the nearest part, incurs some penalty.

The easy remedy, at the time, was to set my destination to the eastern side (where the entrance is). However, this wasn't as convenient as merely selecting the library from a list of results from querying for `amenity=library` (a feature of OsmAnd which I rather like). Note that it is the *building* itself which is tagged as a library (since it occupies the entire building), rather than a PoI node (which could be moved closer to the entrance, as a workaround).

Now, my point is that I **didn't** immediately assume that OsmAnd was broken and come to GH to bitch about it & whine at weary developers. I suspected that the map data didn't include the information necessary to route me to the entrance. Even if that weren't the case (or wouldn't help), it's the obvious place to start.

By that point, I'd already learned about `entrance=*` and encountered a few examples (including having noticed how they affected routing).

So, I [added the `entrance=main` to the building](//www.openstreetmap.org/changeset/112238042), in hopes that doing so would help the router.

After OsmAnd had had chance to fetch the update, and I was next heading to the library (again, from the West), I was delighted to see that, despite selecting the library (building) (rather than precisely placing the destination marker, or selecting the entrance node itself), I was instead being routed around to the front (Eastern side), avoiding the back entirely. No extra walking, or having to use manual workarounds. Wonderful. Just as it should be.

It's worked well ever since. The magic of a dataset (of sound schema design) which is used to both render tiles *and* form the graph which routing algorithms traverse (hence the advice of ensuring that ways (edges) which meet at a junction all share the same node (vertex)), combined with Internet distribution of data … 🥳. This isn't your grandfather's map(!)

When doing detailed (as time & opportunity permit) surveying of buildings, I make a point of adding the entrances (and whatever else) in order to help routing algorithms to determine the right path.

Besides benefitting me, it also benefits everyone else (now and in future), including the likes of tourists & visitors who are unfamiliar.

Contrast that against merely complaining about imperfect results regardless of any other factors. Nothing would have improved, then.

This, all from ‘eating my own dog food’ which caused me to notice the problem, and prompt me to fix it.

Notice, too, that OsmAnd itself didn't change; it merely received more information. The routing algorithm was already capable of doing the right thing. The problem was lacking map data.

For the sake of thoroughness; if adding the entrance (correctly) failed to yield better results, and I'd exhausted all other ideas, then yes I would've considered opening a ticket to report the matter. Especially if several other (public; it's no good citing an example which isn't available for inspection (of its code)) algorithms were yielding desirable results. That was never the case, though, just as I had predicted from the beginning of noticing the problem.

**Comment by gerhard-tinned** [comment] 2022-02-13 19:44
Thanks for your reply and the explanation. I would love to go through all of your statements but I do not waste anyone's time. I will try to focus on what I think is the most important points. I will also try to keep personal feelings out as much as possible - lets stick to the facts and the topic without getting personal.

You stated multiple times that the address is just a string and has no meaning for the software. I do agree on that. I do not agree however that you use it as an excuse. I do contribute to openstreetmaps. Maybe not in the depth like you might, but enough to understand that each address marker (the text you are talking about) is linked to an exact coordinate position on the map. So, by using the name as, lets say an alias, you get the same coordinates as well. To be exact the "Werksalon Co-Making Space" was added 31 Jan 2021 and is (according to the openstreetmap) linked to the coordinates "Location: 48.2329692, 16.4560617". Again, I agree the name is a human readable lable but I have to disagree that it is not linked to coordinates. 

You defend the routing as it chooses the closest point. Well, I am not sure if that is a rule in all countries (still I assume it is) but in Austria it is not allowed to Park on a motorway and definitely not in a motorway tunnel. And yes, it is marked as a "Motorway" as well as a structure "Tunnel". And that are properties that should be readable by the software without any problems.

As Openstreetmaps also contains structures for pedestrians, it is not clear how the tunnel could be left in the way routed. Then there is the detail of 3 or 4 Trail Tracks without a marking for a place to cross. Not to mention that the motorway is below ground (also stated in the openstreetmap properties). I am not trying to make fun of it, I ust want to state the details that are in the map. I know routing is hard, but in this case, I would call this end point for the route simply wrong - which could be improved. As this route is repeatable wrong, I thought it would be a good test while improving the routing engine.



To what I would have expected to see and why: 

Based on my understanding of the structures in OpenStreetmaps, the closest public accessible street for the given address (and its linked coordinates) is the Street Stadtlauerstrasse or the Dr.-Otto-Neurath-Gasse (both would be absolutely acceptable). The motorway is not the closest as it is contained/isolated in a tunnel which can not be left at a point even close enough to the destination.

Based on that, I do see that there is a service road through the "Wirtschaftshof Stadlau" (the lable asigned to the area the destination is in). Which is not a public accessible road. This street is not used for routing and that is from what I understand correct. But I see no indication that would make me think there is any problem with the map data. The motorway is declared as motorway, tunnel, underground. The streets Stadtlauer Strasse and Dr.-Otto-Neurath-Gasse are public roads (no indication of private access in OSM) ... 
... This is the reason I asked for details about what in the OSM data is wrong, incorrect or however you want to call it. (I am not hung up on wording here) It is not that I believe the map is perfect, I agree it is impossible, I just do not see the issues in the map data you see and I want to understand it - Understanding an issue means understand how to fix it, fixing it will improve OSM data and makes the experience better for everyone. Isn't that what we all want??



The duplicate / spammy ticket behaviour. I did not open a second ticket to spam. I opened it because the problem is, at least from my perspective different. Yes, there is a ridiculous detour, and yes, I have that 90% of the time I try to calculate a route but that is the case for the other issue. This issue is more about the, well lets call it for a second "Park in a motorway tunnel and jump head first through the tunnel wall" issue. I am not sooo deep into OSM and routing to be sure if those are the same issue or not, but at least to me they seemed different but related. And if am not mistaken I stated it is partly related (the detour part is the part) linked to the other case. 

If it is the same issue, please tell me and I will try to keep it in mind next time. In that case I am sorry to create a duplicate.


Your suggestions and my thoughts

You mentioned change the destination a few meters / choose a carparek close by / .... 
I agree, choosing a different destination can change the route that is deemed best. But The complete area called "Wirtschaftshof Stadtlau" basically has only two street leading to it. The "Stadtlauer Strasse" and "Dr.-Otto-Neurath-Gasse" based on that, I would basically expect the destination for the car (and the continue on foot) to be anywhere on those streets. If you move the destination slightly inside that hole area, only the end spot on those streets should change. (at least as long as a car profile is used for routing)


In one of your later posts in the ticket I saw those points ...

> **Yes**; better results require:
> 
>     * giving OsmAnd valid input (setting destination to somewhere it can reach, such as the nearby parking)
> 
>     * sanity-checking the results, rather than blindly following them on the assumption that everything is magically perfect
> 
>     * [improving the map](//www.openstreetmap.org/welcome), so that it has more & accurate information to find optimal routes — for example, it appears that some of the carparks don't have connecting ways; checking signage for who's allowed to park there (and setting a suitable value for the `access` key) along with duration and other characteristics / properties; marking footpaths within the pedestrian area
> 

First, I am contributing to OSM. Maybe not yet in the depth and details as you might, but I try to do my best to improve the map where I can and how I can. But that is not the pioint isn't it. 

On the other hand, a "valid input" is a location on the map, isn't it? That would be a name like the "Werksalon Co-Making Space" or an Address like "Stadlauer Strasse 41A, Hof 4, 1220 Wien" No matter what human lable is used, it is mapped to a coordinate location 48.2329692, 16.4560617 on the map. I like to understand it but I do not understand why this is not considered a valid input. When entered the name or the address Osmand finds it and points to the exact coordinate location on the map. Wouldn't that be the indication for a valid input??

For the sanity check, It is easy to check the result if you know the area or more like the area of the entire route. On the other hand, if you know the area and the streets, why would you use a routing app? You would know it anyway and not use it. Maybe you would use it to find the best route? Well, in my experience Osmand does not show a good route - but that is more a topic for the other ticket. My experience is to use a routing / navigation app to find the best route or if you do not know the area. Sanity check is down to a minimum like "am I allowed to drive there?" and that sort of thing. 

> 
> I'm now starting to see why #13356 was closed. It's not a problem with OsmAnd, itself. 🙄
> 
> Smarter use of OsmAnd includes
> 
>     * setting the carpark as an intermediate destination, and the entrance door as final, since you'll have to change mode of transport anyway
> 
>     * for auto-switching profiles (from driving to walking), use the route planner with destinations like above, and select by-car for the first leg, and walking for the last
> 
>     * if you want to follow an exact route of your choosing, then either use the route planner to specify one (and save the GPX) or record a track while driving your preferred route. Then, in either case, when you next want to navigate the route, tell it to follow your planned / recorded path. You can then micro-manage the details to your heart's content 😄
> 
>     * you could try experimenting with setting various (types of) highways as to-be-avoided, to influence the route-finder
> 
>     * as always, use the route-recalculation feature; deviate from the suggested route, where you deem best, and another route will be suggested

I agree, the mode of transport must be changed, but that is always the case as it is not very likely that you can drive with a car directly into the building (with very few exceptions). But I think it is a bit much to expect the user to inspect the destination area, find the closest parking area, and start adding those into the routing. I would argue that most users would expect the navigation software (in this case Osmand) to stop the navigation for a car at the closest public accessible road element and continue from there a walking route. And I have seen this approach a lot of times. Most often is the route with a different mode of transport coloured differently to indicate it. Other times the routing just ends at the nearest by car public accessible point. Both are acceptable ways and based on the route suggested, Osmand is trying to do the same (the way from the motorway to the destination). It is just the wrong spot to divert from the street.

Avoiding highways would work in that scenario but would not always result in an acceptable route. The recalculation feature also requires that you know the the area and the correct route (also part of the other ticket) which would make the use of a navigation app less useful. (my opinion)


I try to keep my emotions out of it and stick to the facts. But still I get the feeling, instead of admitting that something is wrong in the way the route is calculated (I am still only referring to the fact that it exits the motorway through the tunnel wall - not the detour) it is pushed away as a user error. I agree that calculating a route is hard, no doubt. But there is a degree of lets say miscalculation I still would consider wrong. Again, leaving a motorway through a underground tunnel wall - I would call wrong. Of course nobody in his right mind would attempt it when sitting in his/her car ... but it is pretty annoying to wait for the app to recalculate a different route that may or may not be better that the mistake calculated the first time. 




To sum it up, I am not trying to be mean, or annoy any of you. I just think the route suggested by Osmand is so far off anything considered an acceptable route that it needs improvement. I am willing to help and provide the details in a degree I thought is enough. If you need more to improve the routing, I am happy to help. If there really is an issue in the OSM data, please tell me exactly what it is and I am willing to fix it or at least try to get someone to fix it, if I can not do it myself.

If you insist the Users are the problem, Please let me know. In such a case, we have reached an in-pass which we will never fix. I thought it would be worth helping to improving Osmand as I thought, besides the routing, it is one of the best Android apps for OSM data. Most of the time I use navigation and map apps to find either the best route to a known destination or often find a route to a destination in unknown areas. Both situations would make it very difficult for the amount of "sanity check" suggested. 

I hope we can leave the emotions out of it and focus on a way to fix this issue either in Osmand or the OSM data. I am willing to help and I hope you are willing to work on it too.

**Comment by gerhard-tinned** [comment] 2022-02-13 20:22
Little Add on, I even tried to use a different OSM app with offline routing (the name of that app does not matter at this point) and tried to find the mistake in the in the OSM data. 

* I specified the start point on the motorway a bit before the area with the destination
* Specified the destination the same way as in Osmand (The name of the place or the Address both leads to the same result)
* Calculated the route.

I would have expected to see a similar issue with the routing as in Osmand if the OSM data is would be the issue. But the alternative app in that case even suggested 3 possible routes all either exiting the motorway on a regular exit before or after the area of the destination. None of them tried to exit ... well, through the tunnel walls (sorry, not the most scientifiy name for it but that is basically what Osmand suggests). 

![retesting_osm_data_issue](https://user-images.githubusercontent.com/1536065/153773373-1834b09c-6f51-44ce-bedb-f4fac882219f.jpeg)

**Comment by scaidermern** [comment] 2022-02-14 07:42
This is essentially a duplicate of #1578. There have been various similar reports (#7449, #7520 and others).

For now you always have to check the destination marker and move it slightly to the correct location, when required. In fact, you should always perform this check, with all navigation apps.

**Comment by gerhard-tinned** [comment] 2022-02-14 07:50
> > Startpoint: Schlachthammerstrasse 97, 1220 Wien
> > Endpoint: Stadlauer Straße 41A/Hof 4, 1220 Wien
> 
> It took quite a while to find these on the (Web) map. Nominatum wasn't able to resolve the destination string.
> 
> In future, supplying coördinates or (better) a link would be far less ambiguous (perhaps the report template needs to be updated).
> 
> In the course of my digging, I yielded [the original route (matching the OP)](//www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.21250%2C16.52270%3B48.23307%2C16.45536). However, when changing the destination only slightly (by a couple metres) (and changing nothing else) the [optimal route](//www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.21250%2C16.52270%3B48.23301%2C16.45552) was yielded.
> 
> So, _how **exactly**_ was that destination given to OsmAnd?

I checked the links you sent for the route. And it seems you have used some coordinates in the area of the destination. I used the test label in the destination and ... well, the expected route came up. I do not understand why the route does not work for the coordinates just a few meters away.

It is I think not OK to end the route in the middle of an underground motorway tunnel in any situation but ... at least the route I explained in the beginning works in the Car (OSRM) and the Car (GraphHopper) when the correct address is entered. It just does NOT work in the Osmand app. 

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=48.2125%2C16.5227%3B48.2330%2C16.4561

**Comment by gerhard-tinned** [comment] 2022-02-14 07:55
> This is essentially a duplicate of #1578. There have been various similar reports (#5395, #7449, #7520 and others).
> 
> For now you always have to check the destination marker and move it slightly to the correct location, when required. In fact, you should always perform this check, with all navigation apps.

As stated multiple times, that is possible if you knoe the best route or the destination area. But it does not work so well if you are in a country you do not know or drive into a reagion you do not know. And honestly that is the main reason to use an app like that. 

Of course, you will never be 100%, I get that. but there is a difference between having it 80% right and at least having the end point of the route in a place where there is even a remote chance of beeing able to stop (like a normal street) instead of in a tunnel on the motorway where (I believe in all countries) you can not really stop or park or ... well, you get the point. 

So at the end, do you consider this an issue with the routing engine or how to continue from here?

**Comment by scaidermern** [comment] 2022-02-14 08:08
> > For now you always have to check the destination marker and move it slightly to the correct location, when required. In fact, you should always perform this check, with all navigation apps.
> 
> As stated multiple times, that is possible if you knoe the best route or the destination area. But it does not work so well if you are in a country you do not know or drive into a reagion you do not know.

Well, I think it is rather obvious that you don't want your journey to end in a tunnel. You don't need to know the destination area for that.

> So at the end, do you consider this an issue with the routing engine or how to continue from here?

Sure. #5395 has a milestone set for the 4.2 release. Let's hope for the best.

**Comment by vshcherb** [comment] 2022-02-14 16:30
This is the route we talk about https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.2153%2C16.5219%3B48.2333%2C16.4560#map=17/48.23200/16.46101

The problem is not the route itself but the point "48.23320, 16.45609" which attaches to the motorway instead of private road. It's an issue related to customer roads: access=destination have very low priority.
https://www.openstreetmap.org/way/177654760

**Comment by gerhard-tinned** [comment] 2022-02-15 17:20
> This is the route we talk about https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.2153%2C16.5219%3B48.2333%2C16.4560#map=17/48.23200/16.46101
> 
> The problem is not the route itself but the point "48.23320, 16.45609" which attaches to the motorway instead of private road. It's an issue related to customer roads: access=destination have very low priority. https://www.openstreetmap.org/way/177654760

That is an interesting comment. Specifically because the destination "Werksalon Co-Making Space GmbH" or also by address "Stadlauer Straße 41A/Hof 4, 1220 Wien" has the location "48.2329692, 16.4560617".  
https://www.openstreetmap.org/node/4396476837
In both nodes related to the "Werksalon ..." which are a Jopiner and an Entrance show the address details for the main street "addr:street=Stadlauer Straße". 

Or do you realy mean the tags at the street (https://www.openstreetmap.org/way/177654760) you outlined? Shouldn't the address of the destination address / destination object define the access? Or am I mistaken? If it is the street that has the wrong tags, please let me know and I will try to get this changed in accordance to the OSM rules and practice.

**Comment by vshcherb** [comment] 2022-02-15 18:37
My theory: if https://www.openstreetmap.org/way/177654760 woulnd't have access=destination such bug wouldn't exist but that needs to be checked properly.

**Comment by scaidermern** [comment] 2022-02-15 20:16
It is not uncommon that a destination is located in a access=destination area.

(actually access=destination sounds wrong, most of the time it should be vehicle=destination or motor_vehicle=destination).

**Comment by gerhard-tinned** [comment] 2022-02-16 23:05
> It is not uncommon that a destination is located in a access=destination area.
> 
> (actually access=destination sounds wrong, most of the time it should be vehicle=destination or motor_vehicle=destination).

What is the meaning of those tags? Can you point me to an explanation or something?

**Comment by scaidermern** [comment] 2022-02-17 08:42
> > It is not uncommon that a destination is located in a access=destination area.
> > (actually access=destination sounds wrong, most of the time it should be vehicle=destination or motor_vehicle=destination).
> 
> What is the meaning of those tags? Can you point me to an explanation or something?

Check https://wiki.openstreetmap.org/wiki/Key:access. Not every combination is described explicitly but the concept stays the same. The _destination_ _value_ means "Only when travelling to this element/area", "no thru traffic" etc. The _key_ defines for which transportation modes this restriction applies. _access=destination_ means it applies for everyone, i.e. even pedestrians. That's why access=destination is rarely correct. _vehicle_ means it applies to all vehicles (cars, bicycles, ... but not pedestrians). _motor_vehicle_ means it applies to motorized traffic only (cars, motorcycles, but not bicycles and pedestrians).

**Comment by Lee-Carre** [comment] 2022-02-17 12:08
> actually `access=destination` sounds wrong, most of the time it should be `vehicle=destination` or `motor_vehicle=destination`

> `access=destination` means it applies for everyone, i.e. even pedestrians. That's why `access=destination` is rarely correct.

While I
* definitely agree with the principle re using specific, fine-grained tagging
* generally agree that `access=*` is (often) too broad

I have encountered some places which were *definitely* `access=destination` (and maybe `access=private`) *including* for pedestrians.

Though, I suppose one could disambiguate by setting multiple access sub-keys to `destination`:

    foot=destination
    vehicle=destination

As a surveyor, to give a little insight: aside from the case of a mapper not knowing about (or how to use) specific sub-keys, sometimes it's quite unclear what the exact rules are, even when there's signage. Sometimes there's only a sign which reads “PRIVATE”.

So, besides ambiguity, given OSM's principles of what's-on-the-ground & verifiability, I can see why `access*` may be set, sometimes.

I've encountered numerous situations which make me question ‘how do I tag this?’ (some are real head-scratches, even after doing research).

In other cases, it may be that other factors meant that detailed mapping wasn't possible at the time
* lack of time (surveying properly often takes longer than you think); what if he notices something important while passing on his way to somewhere else (which he can't be late for)?
* environmental: dark, cold, raining, very windy, Muggles (some of which are hostile, including aggression & threats)
* the surveyor's state / condition: cold, tired / fatigued, hungry (because surveying all day)
* low battery

I've been known to set `barrier=yes` due to some of the above factors. I deemed it better to mark that there was a barrier at all, than not. It can be refined later (since it's then a known concern).

I gather that many surveyors (particularly those using StreetComplete) don't like to stop to do detailed mapping.

Ideally, mappers setting `access=*` (as a quick & dirty measure; see above) would also set at least one of
* `note:access`
* `fixme:access`

so that the situation (ambiguity / incompleteness) is clear to other mappers.

Setting `access` at all (when it's restrictive), to indicate such, is better than leaving it unset. At least, then, it's identified / recognised as likely needing refinement.
Otherwise, it has to wait until the next surveyor discovers it. Some areas have very few mappers / surveyors, so that could be a very long time.

**Comment by gerhard-tinned** [comment] 2022-02-22 19:50
I got in contact with the OSM community and checked the signs on side. It was suggested to set "access=permissive". 

It seems now Osmand now routes as expected. Thanks. Still, I think ending the route on a motorway, specially in a tunnel should be changed.

**Comment by JenswBE** [comment] 2022-05-13 20:08
Facing a similar issue. Unfortunately, it's unclear if I should consider it a routing issue or a data issue. So, please feel free to point me to OSM community if you consider it a data issue or to create another PR in case you consider it another issue.

Starting point: 51.02120 N, 4.44816 E
Destination point: 51.18348 N, 4.39170E (reproducible with quite some points, see below screenshots)
Same OsmAnd version, routing, maps, ... as original PR. Only difference I'm on Android 12L (crDroid 8.4 on Samsung S10)

**Problem**
When trying to navigate to parking "P+R Olympiade", OsmAnd routes to an underground highway tunnel instead of the parking on top. This is reproducible with different points around the parking. Routing is correct on OSMR and GraphHopper: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=51.02814%2C4.48035%3B51.18340%2C4.39177#map=19/51.18300/4.39200

Routing to parking node:
![image](https://user-images.githubusercontent.com/6514515/168381272-277e4827-fddd-41d8-8b3e-ab5c92435ad4.png)

Routing to a public transport stop nearby:
![image](https://user-images.githubusercontent.com/6514515/168381343-bd02bb58-b770-4102-899b-a280733c7bb8.png)
![image](https://user-images.githubusercontent.com/6514515/168381355-01d65a3e-06d9-4ad4-8f44-8d02be9db119.png)

Explicit routing to a road of the parking:
![image](https://user-images.githubusercontent.com/6514515/168381444-95047920-7c5f-4025-9249-2e716ab2d979.png)

Explicit routing to the access road of the parking:
![image](https://user-images.githubusercontent.com/6514515/168381497-37242098-4358-4d39-b56d-91780419a259.png)

Routing to another public transport stop nearby works correctly:
![image](https://user-images.githubusercontent.com/6514515/168381744-03c3a9cb-28db-47ea-9059-4b956f471a64.png)

Tagging on the access road of the parking. My doubt if it's a mapping error is because I can reproduce with the public stop (see screenshot 2 and 3):
![image](https://user-images.githubusercontent.com/6514515/168382087-1c161cdf-5e88-4942-8a74-2fc5c6b19c80.png)

**Comment by vshcherb** [comment] 2022-05-19 17:06
@JenswBE
! It looks like we could deprioritize tunnel a lot cause almost nobody wants to have final point in the middle of a tunnel !

**Closed** 2022-06-07 11:04 UTC
Labels: routing

**Comment by JenswBE** [comment] 2022-06-08 20:39
Big thanks @alisa911 and @vshcherb for following up and fixing this :heart:
