### ISSUE TITLE
Background trip recording broken in latest update

### ISSUE THREAD

**Issue by olavmrk** [osmandapp/OsmAnd#21549] opened 2024-12-09 17:31 UTC
### Description

The trip recording plugin no longer logs any data when OsmAnd is running in the background. It shows the notification, but no data is logged. None of the numbers in the notification updates while the app is in the background.

This worked yesterday, but there was an app update today, and it no longer works.

I have tried both Google Play Services and Android API as location sources.

I have verified that the app is allowed to run in the background.

### Steps to reproduce

1. Start trip recording.
2. See that a track is shown on the map.
3. Pull down notifications from the top of the screen. See that new data is added.
4. Switch to the phone home screen.
5. Pull down notifications from the top of the screen. See that the notification no longer updates.
6. Switch back to OsmAnd. See that no data was logged while it was in the background.

### Actual result

No data logged when in background.

### Expected result

Data to be logged while in the background.

### Your Environment (required)

```
OsmAnd Version: 4.9.9
Android/iOS version: Android 15
Device model: Pixel 6a
Crash-Logs: -
```

**Comment by CJTmmr** [comment] 2024-12-09 21:42
Same problem on Samsung Galaxy S22 since last Saturday

**Comment by yuriiurshuliak** [comment] 2024-12-10 12:08
The bug has been **reproduced in the release version 4.9.9** with the following steps:  
1. Start trip recording in OsmAnd.  
2. Verify that a track is displayed on the map and that data is updating in the trip recording notification.  
3. Switch to the phone’s home screen.  
4. Check the notification again and observe that it no longer updates.  
5. Return to the application tab, and note that with the app open, the route is recorded again.  

**Result on the release version (4.9.9):**  
- No data is logged when OsmAnd is in the background, and the notification does not update.  

I also tested this on the **nightly version 5.0.0#3919m**, and the issue does not occur:  
- Trip recording works correctly with the application open, running in the background, and with the screen locked.  

This indicates that the issue has been resolved in the nightly build, and the fix will likely be included in the upcoming release.  


<table style="width:100%">
  </tr>
  <tr>
    <th>OsmAnd 4.9.9</th>
    <th>OsmAnd~ 5.0.0#3919m</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/9d83769b-e24b-4553-8958-4a2f40aaa331"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/184130c6-e4c6-4083-9de5-f06223f3b2bb"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Jo-Fri** [comment] 2024-12-11 12:22
Same problem on Samsung Galaxy A40 with OsmAnd V4.9.9

**Comment by sonora** [comment] 2024-12-11 12:59
This is probably the fix: https://github.com/osmandapp/OsmAnd/commit/16202c271d525d118b9a410342627838736e6730

**Comment by vshcherb** [comment] 2024-12-11 15:22
@sonora how ui layer is related to the background recording a bit lost here

**Comment by alex-osm** [comment] 2024-12-11 15:25
> This is probably the fix: [16202c2](https://github.com/osmandapp/OsmAnd/commit/16202c271d525d118b9a410342627838736e6730)

No, it is related to OsmAnd's new interpolated location feature only

**Comment by sonora** [comment] 2024-12-11 15:42
> @sonora how ui layer is related to the background recording a bit lost here

I was only talking empirically going through my test builds, the ones having this commit do no exhibit the issue. But it could be co-incident, I had not checked the factual content of the commit.

**Comment by Pastim** [comment] 2024-12-11 15:59
Me too, on version 4.9.9 date 2024-12-06 on a Samsung A41.  I did a successful walking trip recording that morning.  I did walking trip today and it started, then stopped quite quickly (within minutes), many times.  I tried to work out if there was a pattern to it (such as receiving a phone call, which has, I believe, caused a problem in the past), but I couldn't work this one out at all.  It doesn't make a difference if I am displaying the currently recording track or not.

Osmand+ has been extremely useful to me over the years.

**Comment by GvdBoomen** [comment] 2024-12-12 09:05
Similar on a Samsung S24. Since system update from 9 December 2024, track recording does not work anymore. Track time is recorded correctly but location and the track as usually visible on the map is not. Also, the map doesn't refresh/update: when I reopen the app after walking further a bit, the map shows the previous location and not the current. The distance, as usually visible in the top right of the screen is also not correct: seems to show the distance since last trackpoint not since start of track recording. Tried setting the track recording plug-in back to default, as well as many other things. I gave up.

**Comment by archiewestermann** [comment] 2024-12-13 06:17
Same issue on google pixel 6a, android 15. Last working track recording 2024/12/8

**Comment by petersohn** [comment] 2024-12-13 07:27
Same problem on Google Pixel 7 running GrapheneOS, OsmAnd 4.9.9. I tried setting background battery usage to unrestricted, but it didn't help either.

**Comment by navigatorXL** [comment] 2024-12-14 11:29
The issue as described is confirmed on Samsung Galaxy S21 Ultra / latest Android14 update / OsmAnd+ 4.9.9 of 2024-12-06.

For me the timing is bad since I currently do some once-in-the-lifetime trips. Currently I regret that I did the update. The first time that I'm disappointed: no fix of this prominent feature after one week!

**Comment by pebogufi** [comment] 2024-12-14 12:09
Just a workaround!!
If your recording is very important, you can use "OSMTracker for Android". After recording a track with this tool you can export gpx file and use it in osmand.

**Comment by Pastim** [comment] 2024-12-14 15:41
Would moving to the beta version 5 help?

**Comment by navigatorXL** [comment] 2024-12-14 17:50
The issue as described is confirmed on Samsung Galaxy S21 Ultra / latest Android14 update / OsmAnd+ 4.9.9 of 2024-12-06.

For me the timing is bad since I currently do some once-in-the-lifetime trips. Currently I regret that I did the update. The first time that I'm disappointed: no fix of this prominent feature after one week!

> Just a workaround until bug fixing !! If your recording is very important, you can use "OSMTracker for Android". After recording a track with this tool you can export gpx file and use it in osmand.

Thanks!
Looks minimalistic yet powerful.
It will do for the moment!

**Comment by vshcherb** [comment] 2024-12-14 20:12
Fix already in 4.9.10

**Closed by vshcherb** 2024-12-14 20:12 UTC

**Comment by GvdBoomen** [comment] 2024-12-15 10:14
Thanks for fixing my favorite navigation app. I can confirm its working again.👍

**Comment by Pastim** [comment] 2024-12-15 10:15
I joined the beta program on the 12th (not sure if that's necessary now) and tested 4.9.10 from Google Play today.  Working well.  Thanks to all those who keep putting in the effort.
