### ISSUE TITLE
crash immediately on start

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#6144] opened 2018-10-07 09:31 UTC
before anything is seen.
 Exception.log is NOT written

Device : gtaxllte
Brand : samsung
Model : SM-T585
Product : gtaxlltexx
Build : NRD90M.T585XXU3BRF1
Version : 7.0
App Version : OsmAnd~

Apk Version :
 3.2.0#26033 AND
 3.2.0#26034

**Comment by jfburke3** [comment] 2018-10-07 17:49
Just a note to help the devs track down the problem: I am NOT experiencing this issue.  Currently running 3.2.0#26036 on Samsung Galaxy S9+ (SM-G965U)

**Comment by pebogufi** [comment] 2018-10-09 06:39
Also crash in
26039, 26045, 26047, 26048

After version with crash i allways install older  25959 24/09/2018 which allways works fine.

**Comment by pebogufi** [comment] 2018-10-15 06:27
@vshcherb @crimean 
After uninstall and new install of 26075 it works with no more crash. 
But I don't understand why 25959 never had a problem, only the newer ones.
Peter

**Comment by vshcherb** [comment] 2018-10-16 12:53
Do you have log with crash itself?

**Comment by pebogufi** [comment] 2018-10-16 12:56
No, the crash was never logged, I suppose, it happend at a *very* early state at start.

**Comment by pebogufi** [comment] 2018-10-16 13:29
Yes, you are right. But now, after uninstall and new install it is too late, because there are no more crashes.

**Comment by sonora** [comment] 2018-10-17 14:52
Can confirm the crash, reproducible as follows:
Upgrade to an October nightly, e.g. Oct.16 - Everything works find. Now temporarily downgrade to e.g. Sept.22 nightly- things still work fine. Now re-upgrade to the previous Oct. build - Now it crashes upon every start - no log written ever. So far I have to stay with the September build now to avoid a complete re-installation - all upgrade attempts to Oct. builds fail with the immediate crash.

**Comment by sonora** [comment] 2018-10-17 15:41
No sweat, Peter! Hope we get this one sorted out soon. (Un-)fortunately sitting in a very remote location right now with no coding environment available to me... :)

**Comment by Zahnstocher** [comment] 2018-10-22 21:07
Thus the problem is at PoiFiltersHelper.java line 477:
```
			if (oldVersion < 6) {
				conn.execSQL("ALTER TABLE " + FILTER_NAME + " ADD " + FILTER_COL_HISTORY + " int DEFAULT " + FALSE_INT);
				conn.execSQL("ALTER TABLE " + FILTER_NAME + " ADD " + FILTER_COL_DELETED + " int DEFAULT " + FALSE_INT);
			}
```
Introduced here:
https://github.com/osmandapp/Osmand/commit/6ce93c1c8c106210e76fb00863780e219e792533#diff-8c46d08f2060427d41a1e006a1453ab2

**Comment by sonora** [comment] 2018-10-22 22:28
@AlexSyt

**Comment by vshcherb** [comment] 2018-10-23 08:44
That will be fixed in 3.2 (323 version)

**Comment by sonora** [comment] 2018-10-23 08:52
@Zahnstocher Thanks, but I think that fixes the symptom, but not the issue ... :)

**Comment by Zahnstocher** [comment] 2018-10-23 09:28
@sonora The issue is in the old OsmAnd versions downgrade the database version (but the added columns are still there), this should not have been done.
newVersion should not be set, if it is smaller than oldVersion.
In future it should be taken care, that upgraded database versions are not downgraded, if an older OsmAnd version is installed.
This fix is save.

**Comment by sonora** [comment] 2018-10-23 09:37
Yes, precisely what I meant to point out. DB+version is altered to inconsistent state when downgrading. Your fix is safe, but we need to take more care in the future. (It is already the second time we had this issue, first time about 2 years ago when we changed the db version for the Favorites upgrade.)

**Comment by Zahnstocher** [comment] 2018-10-23 09:37
DB check added

**Comment by sonora** [comment] 2018-10-23 13:16
@AlexSyt  Alexander, from what I see, this did not fix it: Clean install of our Oct. 16 nighty. Then upgrade to latest nightly containing the above commit. The down-grade to Oct 16, then re-update. -> You will still get the crash.

**Comment by Zahnstocher** [comment] 2018-10-23 13:36
My pull request, which fixes this issue was closed.
Now I created another pull request which really fixes this issue.
Alexander just fixed the DB version updates.

**Comment by sonora** [comment] 2018-10-25 06:51
(Only question still open here is if we want to catch the exception. Affected are only testers downgrading to older builds then re-upgrading.)

**Comment by pebogufi** [comment] 2018-10-26 12:51
@sonora This situation often happens: If I downloaded a new nightly, find something which looks to be wrong, then I reinstall a older version to compare the behaviour. Later I install a newer version or current version. I suppose a lot of testers do like that.

**Comment by sonora** [comment] 2018-10-26 13:07
Yeah, tend to agree, but do not want to merge it myself, this issue is kind of owned by @vshcherb and @AlexSyt.

**Comment by vshcherb** [comment] 2018-10-31 15:01
My current understanding that we have downgrade/upgrade db which leads to crashes. Obviously it should be "forbidden" but in many cases we can deal with downgrade nicely

**Comment by vshcherb** [comment] 2019-01-14 11:09
I assume the issue is fixed cause we can't reproduce it any more

**Closed by vshcherb** 2019-01-14 11:09 UTC
Labels: Observed
