### ISSUE TITLE
Voice guidance switches to Dutch after navigation completes first time

### ISSUE THREAD

**Issue by eighthave** [osmandapp/Osmand#2369] opened 2016-03-26 09:21 UTC
* OsmAnd 2.2.4 on Android 4.4.4
* offline maps via Osmand in-app downloads
* problem happens in the Austria map file for the past year

My phone is in English (United States) and I switch the "Voice guidance" to German in the "General Settings".  This works great for one navigation, then the next time I setup a navigation, it switches to Dutch.  First, just the voice switches to Dutch, then after a while, the preference itself will show that Dutch is chosen.  This happens every time, so now I just set up my navigation, then switch the language to English, then back to German, and I get the German voice.

It has been happening for at least the past year.  At first I thought it was speaking German with an English accent, but after a long time of just leaving it in that strange voice, I recently checked it, and Dutch was selected.

**Comment by hakuchi** [comment] 2016-03-26 11:00
what TTS engine are you using?
Do you have only German TTS voice installed in your mobile phone settings?

**Comment by eighthave** [comment] 2016-03-26 12:06
The menu looks like this for me:
* Do not use
* TTS voice  German
* TTS voice  English
* TTS voice  Spanish
* TTS voice  French
* TTS voice  Italian
* TTS voice  Russian
* TTS voice  Japanese
* TTS voice  Dutch
* TTS voice  Polish
* TTS voice  Portuguese
* TTS voice  Chinese
* Install more...

* TTS voice  
* TTS voice  
* TTS voice  
* TTS voice  
* TTS voice  
* TTS voice  
* TTS voice  
* TTS voice  
* TTS voice  
* TTS voice  
* TTS voice  
* TTS voice  
* TTS voice

**Comment by eighthave** [comment] 2016-03-26 12:09
I don't remember installing any of those, I only speak English, German, and Spanish anyway.  I'm trying deleting all but English and German.

**Comment by eighthave** [comment] 2016-03-26 12:12
Ah, I see what you mean.  In Settings -> Languages and Input -> Text-to-speech output, it says "Pico TTS".  The Language menu has:

* English (United Kingdom)
* English (United States)
* French (France)
* German (Germany)
* Italian (Italy)
* Spanish (Spain)

**Comment by hakuchi** [comment] 2016-03-26 13:14
Change the voice again to Dutch after deleting "TTS voice Dutch" in OsmAnd?

Do you have set a language in Configure map -> Map language -> German/English/Local names?

**Comment by eighthave** [comment] 2016-04-14 15:17
Deleting the Dutch voice makes it stick in German.

"Global app settings" -> "Map preferred language" is set to "Local names".

**Comment by sonora** [comment] 2016-05-06 09:29
eighthave, is this still an issue with the latest version?

I cannot reproduce this at all, not on any of my test devices. If you are still experiencing this, please do the following:

(1) In your Android (not OsmAnd) settings, go to your TTS engine's settings (most likely under "Sound" or similar), and make sure that the language selection there is set to German. Use the "Listen to an example" setting there to make sure it works, accent-free. (Mixed German/English settings in Android's TTS setting and then different in an app may actually produce accents which sound like Dutch  :) ). If there is a setting there specifying if apps should be able to override the global tts language selected, try playing with that being on or off.

(2) In OsmAnd, you should go to the General settings (while no navigation is ongoing !!), and set the voice guidance to German TTS.

That does the trick for me, reliably, and every time (Using the google tts on most devices, not Pico). (Can you maybe verify if our issue is also present using another TTS engine?)

If you still see an issue, can you please provide step by step instructions how to reproduce. In particular if this only happens when the navigation is performed to the end and reaches the destination, or if I should be able to reproduce this even when I just manually stop the first navigation and try a second one. Also, you mention this happens on the Austria map, but I guess not only there??

Thx - Hardy

**Comment by eighthave** [comment] 2016-06-03 10:09
I had fixed this by removing all languages but English and German.
Osmand upgraded to 2.3.5, and all of the languages were again there, and
the problem came back.  I deleted some langauges, including Dutch, but
this time it didn't make it go away.

This odd language mode is hard to describe.  I first thought it was the
English pronounciation of German words, then I thought it was Dutch (I
know a little Dutch).  I'm now thinking it is probably not pure Dutch.

When it is stuck in the odd language mode, I can switch the language to
anything, then back to German, and it fixes it for one navigation.  The
next time I navigate, its back to the odd language mode.

To reproduce:
* set phone to US/English
* set TTS language to German
* navigate in Vienna
* first time it works fine
* every other navigation, it is in odd language mode

**Comment by sonora** [comment] 2016-06-03 17:41
This is really weird, I cannot reproduce this at all, even following your guidance exactly. 5 points I can think of:

- What device (manufacturer, model) this?

- When OsmAnd is in "weird language mode", what happens when you go to `Android (not OsmAnd) Settings -> Languages and Input -> Text-to-speech output -> "Pico TTS"`, and perform a "`Listen to an example`" (I think most TTS engines have a test button like this). What language do you hear?

- When you then go back to OsmAnd and have OsmAnd say something, has anything changed?

- Then one more question regarding Android (not OsmAnd) Settings -> Languages and Input -> Text-to-speech output /  "Pico TTS": Many TTS engines have some sort of setting there saying something like "Allow applications t use their own language setting" or similar. Does Pico have this, too? Does your phenomenon change when you change this setting?

- Last not least: Does your deice have another TTS engine available for selection? Like "Google TTS", or "Samsung TTS"? If not, I think there may be some free ones on the Play Store, maybe you want to see if trying one of them makes the issue go away?

**Comment by eighthave** [comment] 2016-06-05 14:19
This is a Samsung Galaxy Note 2 running OmniROM 4.4.4.  I'm going to switch ROMs soon, so I'll report on whether that has an influence.  "Pico TTS" is the only engine installed.  There are settings for the default language, but I don't see something like "allow apps to use own settings".

There is a new twist to this now: I deleted all languages but German.  The first time it worked, as usual, but now there is no voice guidance at all any more.  Switching from "German" to "Do not use" and back didn't fix it.  Before, switching from "German" to "English" and back would always fix it.  I'm going to try reinstalling English.

Here are my TTS settings:

**Comment by eighthave** [comment] 2016-06-05 14:23
* device is Samsung Note 2 running OmniROM 4.4.4
* I'll try the "Listen to an example" next time it happens
* only Pico TTS is installed, here are the settings screens
![screenshot0](https://cloud.githubusercontent.com/assets/143465/15805998/b436f9ce-2b39-11e6-84f4-5d9fcb879854.png)
![screenshot1](https://cloud.githubusercontent.com/assets/143465/15806000/b55f0de6-2b39-11e6-8fbd-784e8280255b.png)
![screenshot2](https://cloud.githubusercontent.com/assets/143465/15806001/bab15510-2b39-11e6-980c-7d5dc3f476dc.png)

**Comment by sonora** [comment] 2016-06-07 12:16
It really looks like a device, i.e. ROM issue to me:  I think the device is somehow reverting back to English on some occasion even if apps like OsmAnd specify "German". As a result, you will either get "German with a strange English accent", (which can be mistaken for Dutch :smiley:), or, if when your device does not support English because you test-uninstalled the English TTS support, it does not play anything at all.

I guess either installing second TTS engine like from the Play store or a ROM change may the thing to experiment with here...

**Comment by sonora** [comment] 2016-07-20 12:42
After a lot of testing this, the only related behavior I can reproduce on some of my devices is this: If you set the device's (device engine's) TTS language to **English** (in the Android settings), and in OsmAnd select **German TTS**, it usually works fine immediately after making the selection in OsmAnd, but only until some point I have not identified yet. Either when the device had gone to sleep, or after OsmAnd was re-started, OsmAnd may start talking "German phrases with English accent".

The obvious solution is to simply set the device's TTS engine language always to the TTS language you chose in OsmAnd, with that (natural) setup I never observed any issue,

**Comment by sonora** [comment] 2016-07-31 10:24
PS: Re-tested this: It is quite reproducible
- that after the device had gone to sleep for some time with OsmAnd in the background and navigation finished or stopped,
- after waking up the device and starting a new navigation, the TTS engine produces "Germany sound with English pronunciation".
Please note that this is ONLY when the Android TTS setting is set to English, while the OsmAnd TTS language is set to German.

Re-starting the app resolves it, as does briefly toggling between different TTS languages in OsmAnd, which indicates that under these circumstances somehow the Android TTS-settings had been re-applied, and (if different), OsmAnd needs to trigger a re-init to again overwrite.

In theory, I guess we could perform a full OsmAnd TTS re-init after certain triggers like device wakeup, but this may have adverse side effects (delays). I think I close this issue with no further action planned.

Please report if anyone sees this issue with **Android and OsmAnd's TTS language set to the SAME language**, only then I think we should consider this as significant.

**Closed by sonora** 2016-07-31 10:24 UTC
Labels: Observed
