### ISSUE TITLE
Crash when on the map

### ISSUE THREAD

**Issue by secretmango** [osmandapp/OsmAnd#21022] opened 2024-10-11 15:14 UTC
```
type: crash
osVersion: google/bluejay/bluejay:14/AP2A.240905.003.F1/2024100800:user/release-keys
package: net.osmand.plus:480603
process: net.osmand.plus
processUptime: 0 + 0 ms
installer: dev.imranr.obtainium

signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xb400c22295e33000

backtrace:
      #00 pc 000000000054f49c  /data/app/~~si56RYql9cTUblIfkIHdaw==/net.osmand.plus-DM2nL_GZ12Lp8snEXGHEOA==/lib/arm64/libQt5Core.so (ffcps_default_utf+208) (BuildId: b628327ac87b186d2edf5abfdcae257d19eff494)
      #01 pc 000000000000fb58  <anonymous:c4c7b0714000>
```

OS GrapheneOS latest, Android 14

Installed from F-Droid.

Using hardened_malloc as memory allocator

**Comment by scaidermern** [comment] 2024-10-12 08:43
Duplicate of #21002 / #20951?

**Closed** 2024-10-12 14:42 UTC
