### ISSUE TITLE
not change back to day-light when routing stopped

### ISSUE THREAD

**Issue by osmvermesser** [osmandapp/Osmand#4533] opened 2017-10-05 06:33 UTC
If you route in the night the screen will be black.

when you are at the destination the screen changes automatically to daylight.

this was very hard for the eays.

i think it would better not to change the light at the destination.

regards Jan

**Comment by scaidermern** [comment] 2017-10-05 06:51
I think the problem is that the day/night settings can be configured individually for each routing profile (car, bicycle, ...). And after the routing finishes OsmAnd switches automatically from the routing profile to the world view. If you have different settings between your routing profile and the world profile then you will encounter the things you described.

In my opinion OsmAnd should *not* switch back to the world view after routing has finished. For me this has always been a very annoying and confusing behavior.

**Comment by osmvermesser** [comment] 2017-10-05 07:57
thanks for this Information - but i can not found the properties!

could you show a image - it is easier to find than in german gui.

reagards Jan

**Comment by scaidermern** [comment] 2017-10-05 09:47
Configure Map / Karte konfigurieren -> Map mode / Kartenmodus.

**Comment by osmvermesser** [comment] 2017-10-09 05:43
hi !

i try and change to sensor-light (but i think it was very sensitiv). it is a lighing day and you drive trough a streetpart with scrub then it change to night and back.

so i think it would be better by use default properties and not change the lightning status when you are at the place of destination.

Ich habe das einmal mit dem Umgebungssensor ausprobiert - aber ich finde das reagiert sehr empfindlich und schon wenn etwas dunkler ist (Schatten durch Bäume etc) wird in den Nachtmodus gewechselt und wieder zurück. Auf Dauer sehr nervig.

Daher würde ich es begrüßen wenn in der Standardeinstellung die Einstellung beibehalten wird die war als das Ziel erreicht wurde.

regards Jan

**Comment by vshcherb** [comment] 2017-10-11 11:00
This issue will be fixed with #4571

**Closed by vshcherb** 2017-10-11 11:00 UTC
