### ISSUE TITLE
Osm live "barrier" bug

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2499] opened 2016-04-27 07:36 UTC
https://www.openstreetmap.org/node/4090258858
Netherlands_gelderland_europe_16_04_01.obf
2016_04_01/netherlands_gelderland_europe_15_30.osm.gz
This barrier does not exists in 16_04_01 and 16_04_00. Parent highway (osmid 406991107) presents in 15_30, 17_00, 16_00.

**Comment by poutnikl** [comment] 2017-01-04 15:22
It may be worthy to reevaluate the approach to default access of obstacles, if there is lack of explicit relevant access tags. E.g. for nodes barrier=bollard and cars the default access should be NO unless tagged YES.
( like BRouter car profiles do )

**Comment by aceman444** [comment] 2017-01-25 20:13
The access for a car is intended to NOT be allowed by default on a bollard, see
https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml.

Is this a problem with live Updates as xmd5a2 marked it?

**Comment by poutnikl** [comment] 2017-01-25 21:01
As I mentioned earlier in osmand  group, it is done in routing.xml for way context only, not in point/OSM node context. And that is wrong, IMHO.

**Comment by poutnikl** [comment] 2017-01-25 21:14
Self-quoting my reply to the topic "Is this OsmAnd false routing, or OSMap false data?" from Dec-29, 2016:

It is easy. It occurs because OSMAnd incorrectly considers
for barrier=bollard node and cars the default access=yes,
instead of obviously correct access=no

So as there is no other explicit node access hint,
OSMAnd considers that bollard as free to go.

It should be fixed in the internal routing.xml,
or you can overwrite trhe file temporarily as workaround
in the routing.xml downloaded from the OSMAnd GitHub site,
placed in OSMAnd data folder.

After reviewing the routing.xml file, I have realized
bollards as obstacle are addressed in way context only, not in node context.
And at the map the bollard is the node.
So it is ignored, regarding the access.

Note that the crossing OSM ways are not "aware each other",
if they do not share the node, like if they were at different levels.
Seen often on water ways._

**Comment by poutnikl** [comment] 2017-01-26 06:55
I revoke my previous comment, based on some misunderstanding, or rather misreading of routing.xml content.

**Comment by vshcherb** [comment] 2017-02-22 22:14
@aceman444  the problem is related to fetching of the changeset, so during change the bollard won't be fetched in OSC (osm change file) and that's why OsmAnd will get an incomplete obf file where bollard won't exist on the line which obviously will lead to routing mistake.

**Comment by vshcherb** [comment] 2017-09-03 16:42
The issue fixed since September updates

**Closed by vshcherb** 2017-09-03 16:42 UTC
Labels: Live Updates
