### ISSUE TITLE
"Next turn" and "Second next turn" widgets missing after route recalculation.

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#15074] opened 2022-08-14 20:30 UTC
If in the process of movement I deviate from the route, and the route is recalculated, widgets at left panel disappears. 
To return the widgets back, you need to unload the application from the memory.

To reproduce the problem, you need to deviate from the route several times. After the first (or after several) recalculation of the route, the problem will be reproduced.

OsmAnd Version: 4.2.7
Android/iOS version: 6
Device model: Lenovo Tab 2 A10-70F

Screenshot with missing widgets during route:
![Screenshot_20220814-184056](https://user-images.githubusercontent.com/32092837/184553722-206d8345-483c-4837-b7b1-4c4e7c2db394.png)

**Comment by scaidermern** [comment] 2022-08-15 05:50
I've experienced the same issue with OsmAnd 4.2.7 but I'm not quite sure what I did. A route recalculation definitely happened. The only solution was to restart OsmAnd.

**Comment by Zirochkabila** [comment] 2022-08-15 15:46
Try to download the beta version of the application - was tested on it and could not reproduce. Most likely a bug fixed

**Comment by Zirochkabila** [comment] 2022-08-17 08:32
Was reproduced on two devices with Android 9 and below, on the night and release versions.
Most likely, it's the Android version.

**Comment by scaidermern** [comment] 2022-08-17 16:41
I've experienced this on Android 7 and can reproduce it via a simulated navigation on Android 10.

**Comment by Prusaker** [comment] 2022-08-17 18:46
I have attached a log file of my trip where I was able to get the bug.
(The bug appeared at 18.16)

[logcat.log](https://github.com/osmandapp/OsmAnd/files/9365352/logcat.log)

**Comment by Rowin63** [comment] 2022-08-19 14:46
already observed here #14900

**Comment by scaidermern** [comment] 2022-08-19 14:59
But still no milestone set? 🤔

**Comment by vshcherb** [comment] 2022-08-19 16:24
If it's an issue that widgets appear again after first turn executed then it's a long running and might android specific

**Comment by scaidermern** [comment] 2022-08-19 16:54
The issue is that widgets _disappear_. 

I'm pretty sure this issue didn't happen before the 2.7 release.

**Comment by scaidermern** [comment] 2022-08-19 17:13
See this video: https://drive.google.com/file/d/1JJE1DFKmN2GD32908SN5rLoCvlpH97Hf/view?usp=drivesdk

This is with Android 10

At around 15 seconds the navigation starts, the next turn widgets are present.

At around 40 seconds both next turn widgets disappear and never come back.

How to reproduce:
- Simulate a navigation
- Change the destination
- After several route recalculations the next turn widgets disappear

**Comment by scaidermern** [comment] 2022-08-29 18:15
Still no fix version? I consider this to be a serious bug. Without these turn instructions navigation is really hard.

**Comment by vshcherb** [comment] 2022-08-31 17:37
> Still no fix version? I consider this to be a serious bug. Without these turn instructions navigation is really hard.
They don't come back cause you don't follow route, I think they come back once you reach first turn

**Comment by Rowin63** [comment] 2022-08-31 17:57
No they don't. If you leave the route, it has to be recalculated including showing the turns. It was always like this.

**Comment by scaidermern** [comment] 2022-08-31 17:57
> > They don't come back cause you don't follow route, I think they come back once you reach first turn

Might be true for the simulation, I don't know.

However, I also experienced this with real navigation and they didn't came back, ever, until restarting OsmAnd.

**Comment by mdykierek** [comment] 2022-09-06 20:15
+1 from me. I have Android 11. I don't think it is related to re-calculation. It sometimes happens at the start, sometimes in the middle of navigation. Solution is to kill the app and start over.

**Comment by martenjj** [comment] 2022-09-10 11:57
Confirmed observed after route recalculation with OsmAnd+ 4.2.7, Android 12, Samsung Galaxy S10.  Closing the OsmAnd+ app and restarting it makes the turn arrows reappear.

**Comment by Rowin63** [comment] 2022-09-11 10:13
The arrows also reappear when turning the phone from portrait to landscape and/or back, until the next recalculation.

**Comment by Antheii** [comment] 2022-09-18 17:56
Same issue as described by OP.
As mentioned by multiple users, usually when for whatever reason the route was recalculated.

![image](https://user-images.githubusercontent.com/63048026/190921588-5c1ec35c-d7de-4f59-a560-7a5da6d8cb64.png)


OSMAND+ 4.2.7 released 2022-07-13
Android 13 
Pixel 6 Pro

**Comment by vshcherb** [comment] 2022-09-27 11:49
"Next turn" and "Second next turn"  should stay.

**Comment by MikeTango** [comment] 2022-10-11 00:11
Same issue, showed up at some poin , running 4.2.6 on android, rotating the device back and forth is a workaround.

**Comment by pahervin** [comment] 2022-10-18 10:52
Same issue, since 4.2.6 on android 9.
The widgets disappear when route recalculation overlap the old route next instruction change.
If the route recalculation ends before the previous route next instuction happens, the issue does not happen.

**Comment by nailyk-fr** [comment] 2022-11-06 19:38
I have the same issue and am very able to reproduce : 
* start navigation
* do not close the app (important)
* start another navigation

next turns are gone. It 'works' (the bug) if at step 3. you make a new navigation (because you arrived for exemple) or if you change the destination.

**Comment by Zirochkabila** [comment] 2022-11-17 11:15
[Need to fix](https://github.com/osmandapp/OsmAnd/issues/15733)

**Comment by Zirochkabila** [comment] 2022-12-01 13:56
OsmAnd~ 4.3.0#13989mqta, released: 2022-12-01
Turn widgets aren't displayed


https://user-images.githubusercontent.com/104760013/205070643-bfb0d671-cfa7-4109-ae4c-4c2a3b085753.mp4

**Comment by sonora** [comment] 2022-12-01 17:36
But we always only showed them after you started the turn-by-turn navigation? Only the they make sense?

Tap"Start", and then they work?

**Comment by sonora** [comment] 2022-12-02 09:04
I thing `appMode` here https://github.com/osmandapp/OsmAnd/blob/6ec0938ed70ac010409686aba1eb683957a5daf5/OsmAnd/src/net/osmand/plus/views/controls/WidgetsPagerAdapter.java#L151 should be `routingHelper.getAppMode()`

**Comment by sonora** [comment] 2022-12-04 18:04
The widgets show ok for me but just always **the very first time** you navigate after an app start. For all successive attempts they are invisible.

Something to do with how we query `isEnabledForAppMode` and/or `widget.isViewVisible()`, they somehow look at the last as is status instead of the profile settings?

What I have in mind is something like this: https://github.com/osmandapp/OsmAnd/commit/1deb3d9594aa40d44c34ade0025a5f8d7e47cc35.

- I am not sure if we need the logic change from `hasVisibleWidgets` to `hasEnabledWidgets`
- But putting `widgetsViews.add(widget.getView());` outside the "isVisible" if clause makes sure everything does not become invisible  the first time round and then stays invisible  forever. I have a feeling the method is not called again after tapping the start button to start followMode, hence the widgetsViews are not re-created accordingly.

**Comment by sonora** [comment] 2022-12-06 12:50
@Chumva Not sure if you struggle with this one as much as I do. But if for the release you need a dirty workaround, I have tested this https://github.com/osmandapp/OsmAnd/compare/master...hardy_TurnWidgetsWorkaround and it works. 


It does not make the views invisible but simply the widgets, hence they are reliably recreated when needed. It's of course not clean, but works around the issue that the method `collectVisibleViews(...)` seems never called with `routingHelper.isFollowingMode()=true`.

**Comment by vshcherb** [comment] 2022-12-06 17:20
@Chumva just started - thx for update :-)

**Comment by anastasiia936** [comment] 2022-12-07 14:50
When closing the Context menu for a second appear the lines widget: 

https://user-images.githubusercontent.com/80623554/206210481-81349832-231d-4141-a8bb-0501b133960d.mp4

**Comment by sonora** [comment] 2022-12-07 15:08
The "l**a**nes" widget, you mean. Good observation!

I had also already amended my comment above earlier today, I think the issue seems not _whether_ we do or do not call method `collectVisibleViews(...)` in followingMode, but rather that the first time round when we call it `Map.Entry<Integer, List<TextInfoWidget>>` still contains the turn-related entries, but later they have been removed and never come back. (While the lanes still seem present.)

**Comment by vshcherb** [comment] 2022-12-07 17:38
@sonora accepted patch temporarily https://github.com/osmandapp/OsmAnd/commit/b4977ba149e522c717846034296b2405c2f74dd1

**Comment by sonora** [comment] 2022-12-08 17:17
@Chumva: Cool!  ;)
- Small glitch is that now in the _Browse map_ profile we always show the little gray bar, i.e. the empty turn info widget:
![Untitled](https://user-images.githubusercontent.com/845735/206518693-d54c8bc3-c162-4c45-a309-1550ba1000dd.png)

- Also, less important maybe: I think for the other profiles we now always place the 'Profile selector' and 'Search' icons a bit further down like to make room for the (invisible) empty turn widget.

**Comment by vshcherb** [comment] 2022-12-08 20:50
(1), (2) didn't reproduce

**Comment by sonora** [comment] 2022-12-08 21:28
(2) takes an OsmAnd-experienced eye... 😉.

Here is a direct comparision, screenshot A is an old build, B and C from the current build. B exhibits issues (1) and (3), C exhibits issues (2) and (3).

![Screenshot_20221208-221439_OsmAnd~](https://user-images.githubusercontent.com/845735/206570604-0fd265d3-be67-42b3-adbd-b997a105ee24.jpg)
![Screenshot_20221208-221629_OsmAnd~](https://user-images.githubusercontent.com/845735/206570622-0c363a6b-b5e5-4bd7-939d-7f623a9f9e5f.jpg)
![Screenshot_20221208-221923_OsmAnd~](https://user-images.githubusercontent.com/845735/206570637-b4a82578-6c53-461c-8408-fcec71965627.jpg)

**Comment by sonora** [comment] 2022-12-08 23:17
PS: To fix (3), I guess https://github.com/osmandapp/OsmAnd/blob/01316baad1a8b942cc0b83f41064bc38fe32de81/OsmAnd/res/layout/widgets_panel_page.xml#L8 should be `"match_parent"` Interestingly, that change would re-instate the previous issue of the turn widgets dissappearing for the second and subsequent navigations (?!?)

**Comment by Zirochkabila** [comment] 2022-12-09 10:07
@sonora 
OsmAnd 4.3.2, released: 2022-12-08
1. Not reproduced - the bar isn't displayed.
2. **Reproduced** - the indentation from the top of the screen is greater than from the left - it should be the same.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/206677235-ae6cc6de-5b30-4c86-817c-b7421a140128.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

3. Not reproduced - "meters" are displayed completely

**Comment by sonora** [comment] 2022-12-09 10:16
@Zirochkabila

- **ad (1)** The permanent bar is only displayed when viewing the map in the _Browse map_ profile, can you provide a screenshot of that? (See my screenshot B above.)

- **ad (3)** Either put a few more widgets in the right stack which have a longer text, or do a navigation simulation and observe the left stack. All widgest now have permanent width `"@dimen/map_minwidth_widget"`, and that is often not enough. (But of course there are situations when it still is.)

**Comment by Zirochkabila** [comment] 2022-12-09 10:22
@sonora 
You are right, the strip is displayed. I think it's related to item 2

**Comment by Chumva** [comment] 2022-12-09 17:03
@sonora Can you check if these issues are fixed?

This bug with widgets disappearing was quite strange. The root cause was ViewPager2 which is used for controlling widget pages. It has recyclerView inside, which somehow discharged views and did not recreate new ones after all widgets on the page changed visibility to gone. I tried different approaches to fix it, but even changing to the previous version of the view pager did not help completely remove this bug. These fixes lead to small new issues, but I suppose all of them are fixed now.

**Comment by sonora** [comment] 2022-12-09 18:04
@Chumva Perfect work!

All side effect issues confirmed fixed!

Thanks also for the explanation! Cannot reliably verify that the original is fixed, but all signs are good now.

Have a great evening!

**Comment by Zirochkabila** [comment] 2022-12-13 15:45
OsmAnd~ 4.4.0#14020mqta, released: 2022-12-13
[All](https://github.com/osmandapp/OsmAnd/issues/15074#issuecomment-1344105787) done

**Comment by Rowin63** [comment] 2022-12-15 19:47
Closed and fixed...? 
Widget still disappears.


![Screenshot_20221215_175032_OsmAnd+](https://user-images.githubusercontent.com/95540936/207952612-6b22c054-0cea-456f-8119-6868a3d240f9.jpg)

**Comment by sonora** [comment] 2022-12-15 23:38
@Rowin63 What build number is that?

**Comment by sonora** [comment] 2022-12-16 17:59
If it relates to device rotation, I think that's another root cause now, but let me re-open this so it can be checked.

**Comment by Rowin63** [comment] 2022-12-16 18:44
No, it's not CAUSED by rotation, but rotation brings the widget back 👍

**Comment by Zirochkabila** [comment] 2022-12-18 15:51
OsmAnd~ 4.4.0#14031mqta, released: 2022-12-18
Turn widgets don't disappear


https://user-images.githubusercontent.com/104760013/208307357-d71944d4-d8f1-4de6-b769-218ffe1e6373.mp4

**Comment by Rowin63** [comment] 2022-12-19 10:11
Yes, you´re right. 
I forced now for more than one hour continous route re-calculating and the widget never disappeared.
There were just a few short moments at new calculating, where the widget was not displayed (profile, search and compass went to the top that moments), but it always reappeared after a very short second or so.
I´m sorry, but this last screenshot with the disappeared widget was made with the latest 4.3.3. 
Don´t know, why it happened.
Thanks for solving this!

**Comment by sonora** [comment] 2022-12-19 11:43
@Rowin63 Thanks for clarifying!

**Closed by sonora** 2022-12-19 11:43 UTC
Labels: and-bugs, !
