### ISSUE TITLE
wrong coastline rendering due to world overview map at high zoom levels

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#6320] opened 2018-11-30 06:53 UTC
#5838  #6008  The issue is NOT fixed!

With "World overview map":
![screenshot_osmand _20180820-170250](https://user-images.githubusercontent.com/14617699/44345106-0bd20700-a49b-11e8-9b4c-755c51804bea.png)

With deactivated "World overview map":
![screenshot_osmand _20180820-170325](https://user-images.githubusercontent.com/14617699/44345119-17bdc900-a49b-11e8-9d6d-f56456731c18.png) 

Mustaniiemi geo:60.967663,30.34531

**Comment by xmd5a2** [comment] 2018-12-03 08:35
Note: coastline data used in basemap updated. Will be fixed with the release of a new basemap.

**Comment by c-e-p-x-u-o** [comment] 2018-12-03 08:44
osmand shows all maps are up to date

**Comment by xmd5a2** [comment] 2018-12-03 08:49
It is not done yet

**Comment by robinpaulson** [comment] 2019-01-10 23:54
Would it be possible to get an ETA for the basemap update? Cheers

**Comment by vshcherb** [comment] 2019-01-19 19:16
ETA was supposed to be Q4 2018 but it turned to be a much bigger problem with new  basemap size and it looks the target is updated to Q2 2019.

**Comment by robinpaulson** [comment] 2019-08-09 05:51
I saw the new basemap and mini basemap were released recently. I'm still getting the same flooding in Te Atatu, nz.

**Comment by xmd5a2** [comment] 2020-06-26 07:26
Issue with Mustaniiemi is fixed
![Screenshot from 2020-06-26 10-25-30](https://user-images.githubusercontent.com/5829014/85831729-658e7100-b797-11ea-8db5-ffb2813d19c9.png)

**Closed by xmd5a2** 2020-06-26 07:26 UTC

**Comment by 532910** [comment] 2020-06-26 07:30
ack

**Comment by robinpaulson** [comment] 2020-06-26 09:15
Yeah, still not fixed in Te Atatu, New Zealand. I checked it yesterday in the latest release from f-droid.

**Comment by DiJuMx** [comment] 2020-06-29 20:21
Still not fixed in F-Droid version. F-Droid is still on Osmand~ 3.7.4. Will check again on F-Droid update.

**Comment by 532910** [comment] 2020-06-29 20:57
Mustaniiemi looks fine for me in Osmand~ 3.7.4 from F-Droid.

**Comment by DiJuMx** [comment] 2020-06-29 21:00
Zoom in to at least 50m scale at 51.40151N 0.53462E. Doesn't happen at 100m.

**Comment by 532910** [comment] 2020-06-29 21:02
> 51.40151N 0.53462E

This looks bad.

**Comment by xmd5a2** [comment] 2020-06-30 07:04
Original issue was about Mustaniiemi. Please don't mix different issues in one.

**Comment by 532910** [comment] 2020-06-30 07:22
Original issue was about high zoom levels, not only Mustaniiemi. #6008 is also fixed now.
But 51.40151N 0.53462E looks like a different issue, as it's reproducable only on low zoom levels.

**Comment by DiJuMx** [comment] 2020-06-30 18:32
My mistake. I think I was getting my issues mixed up as there are a number where the problem is fixed by disabling the basemap (and basemap mini)

**Comment by robinpaulson** [comment] 2020-07-01 01:29
@xmd5a2 
> Original issue was about Mustaniiemi. Please don't mix different issues in one.

This implies that the multiple different locations around the world where this happens are being fixed individually. It appears (from my low-knowledge vantage point, admittedly) that these are all the same problem, over and over again, with the same symptoms.

So, is there any particular reason why they are being dealt with individually?

Also, rather than merely saying this is not the correct place to post this, could you let us know where would be appropriate? Cheers

**Comment by vshcherb** [comment] 2020-07-01 14:00
@robinpaulson Most of the issues we dealt last 5 years had different underlying reasons:
1. Algorithms - roughly 30%
2. OSM Data  - 30%
3. Basemap data - 10%
4. Mixing different regions data and basemap data - 20%

So every issue requires different solution. Same applies for rendering and routing issues, so we need to maintain order. Obviously problems of same location are the same issue.
