### ISSUE TITLE
Reorder profiles (car, bike etc.)

### ISSUE THREAD

**Issue by maffe** [osmandapp/Osmand#7121] opened 2019-06-28 13:45 UTC
I can disable and enable profiles, but it seems to be impossible to change the order.

I use OsmAnd~ 3.3.8 from F-Droid (paid you anyway via Play Store 😃).

**Comment by dmpr0** [comment] 2019-11-15 11:54
Duplicate of #7850

**Closed** 2019-11-15 11:54 UTC
