### ISSUE TITLE
"Germany adresses nationwide" not available

### ISSUE THREAD

**Issue by micw** [osmandapp/Osmand#1911] opened 2015-11-13 19:08 UTC
The german address list "Germany adresses nationwide" which was a good workaround for #1732 is not available for download anymore. So you have to select the (probably not known) german state before selecting a city.

**Comment by vshcherb** [comment] 2015-11-15 23:37
That basically duplicate of #1732 and yes we aware of it, but we need to change quite many places to get it working and we are working on it.

**Closed by vshcherb** 2015-11-15 23:37 UTC

**Comment by micw** [comment] 2015-11-16 08:33
Thank you for your feedback. IMO, this is not a dupplicate to #1732. #1732 adresses the feature to search over multiple regions. This issue addresses the fact that the "Germany adresses nationwide" map is not available anymore (which is required unless #1732 is solved).

**Comment by vshcherb** [comment] 2015-11-23 08:04
They are not duplicate, but we are going to solve them together, that's why I closed one. Though they could be solved separately and that's also true.
