### ISSUE TITLE
[Feature request] map objects names display

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8350] opened 2020-01-29 08:53 UTC
when only a part of an object is visible on the screen, its name can be present outside the screen. 
E.g. 48.02670° N, 10.69996° E, Johann-Josef-Schmitz-Straße in Buchloe town is displayed only in the middle of the road.

**Comment by scaidermern** [comment] 2020-01-29 13:05
Duplicate of #7303.

**Closed** 2020-02-10 17:33 UTC
