### ISSUE TITLE
Distorted route rendering on Xiaomi devices

### ISSUE THREAD

**Issue by rododevr** [osmandapp/Osmand#2726] opened 2016-06-19 20:59 UTC
On a Xiaomi Redmi Note 2 device, the route rendering shows weird graphics.
See video:  www.justmapzz.com/downloads/div/route%20rendering.mp4
To check if the issue was introduced recently, I went back several Osmand versions until 2.1.1, but the behaviour remains the same.
Changing several system settings does not help.
Tested environment:
Device: Xiaomi Redmi Note 2
Android version: 5.0.2
MIUI version: 7.2.3
java.vm.version: 2.1.0
java runtime version: 0.9
Other apps using vector graphics don't seem to have this problem.

**Comment by sylvaticus** [comment] 2016-06-19 21:21
This is a duplicate of https://github.com/osmandapp/Osmand/issues/2024.

**Comment by rododevr** [comment] 2016-06-19 21:40
Agreed, I missed that one.
Hope my video gives the developer a better insight of the issue.

**Closed** 2016-06-19 21:49 UTC
