### ISSUE TITLE
Problems with URL's of POI's

### ISSUE THREAD

**Issue by rene78** [osmandapp/OsmAnd#10343] opened 2020-12-06 12:41 UTC
### Description
Some URL's are not rendered properly. When clicking on them OsmAnd crashes.
![Unbenannt](https://user-images.githubusercontent.com/36115705/101280622-6efe1980-37ca-11eb-890a-036ec51f6b04.png)

### How to reproduce?
Open this POI - https://osmand.net/go?lat=47.653725&lon=9.473885&z=20
See messed up URL encoding. After clicking on the URL the app crashes.
The app seems to have problems with the following POI's:

[POI 1](https://www.openstreetmap.org/node/2427125314)
[POI 2](https://www.openstreetmap.org/node/940682495)
[POI 3](https://www.openstreetmap.org/node/420051569)

(URL possibly too long?)

### Your Environment
OsmAnd Version: OsmAnd+ 3.8.4
Android/iOS version: 9 (MIUI Global 11.0.3)
Device model: Xiaomi Redmi Note 5

**Maps used (online or offline):**   offline
Map file: "Baden-Württemberg Regierungsbezirk Tübingen, 1 Dec 2020"

**Comment by scaidermern** [comment] 2020-12-06 17:14
Duplicate of #10250.

**Comment by vshcherb** [comment] 2020-12-06 23:11
Beta is coming this week

**Closed by vshcherb** 2020-12-06 23:11 UTC
