### ISSUE TITLE
Feature request: Plugin for Environmental protection zones

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd#6427] opened 2019-01-09 11:36 UTC
Unfortunately, there are more and more of the environmental protection zones coming up in Germany, like e.g. this one here: 
https://www.stuttgart.de/diesel-verkehrsverbot 
Not only here, but also in other cities and also in France, these zones will be established. It is for now restricting cars with diesel engines, later also others.

Would it be possible to implement a plugin that will do routing around these restricted areas?

**Comment by mahlzahn** [comment] 2019-03-21 14:07
See here (in German) already some implementation by someone: https://blog.christosoft.de/2019/01/navi-diesel-fahrverbote-umfahren-osmand-routing/

**Comment by crazy4chrissi** [comment] 2019-03-22 09:14
I am the author of the blog article listed above. The problem with the environmental protection zone ("Dieselfahrverbot") in Stuttgart is that it is not a single street but a whole area. I don't know how to make OSMand avoid this area. I thought it would be the same as avoiding borders. But I found that the option to avoid borders is actually not avoiding borders ("boundarys") but border crossings (points). Of course, there are no such points in the map when crossing the border of the environmental protection zone. And it is not feasible to add them, as it requires adding one for each street that is crossing the border of the zone. This is really error-prone, as it requires somebody adding a new street crossing the border would also need to add that point.

But as mentioned in the blog post, I added the attribute to openStreetMap, so it is just a matter of making osmAnd avoid it:
![grafik](https://user-images.githubusercontent.com/6806325/54812155-b9540580-4c8a-11e9-9230-8c693e24354a.png)

**Comment by pietervdvn** [comment] 2019-04-04 11:38
Duplicate of #4922, please close this one.

**Comment by pietervdvn** [comment] 2019-04-06 22:35
The best option would be to add another phase to creating the .obf-files:

- Make a first pass, and keep track of all LEZ
- Make a second pass. Every street intersecting with the LEZ gets cut on the intersection; every street within the LEZ gets conditional access tags.

**Comment by vshcherb** [comment] 2020-09-14 16:01
https://github.com/drolbr/Overpass-API/issues/595

**Comment by vshcherb** [comment] 2021-03-05 17:06
All pull requests accepted / merged, some maps will be ready in April, some in March. And there will be 1 more option to avoid roads with low emission zones.

**Closed** 2021-03-05 17:12 UTC
Labels: Nice to Have
