### ISSUE TITLE
2nd navigation start issue

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#2026] opened 2015-12-04 21:17 UTC
I tend to use POIPocket to store POIs and to start navigation.
When I reach my destination, the map switches from the car profile to the browse profile.
I then press back to exit Osmand.
Next I select a new POI in POIPocket to navigate to with Osmand.
When I press the navigate to button in Osmand it starts calculating the route. Doesn't matter whether I do this during or after the route is calculated, but when I press Go, nothing happens. The screen stays centered on the destination, even though navigation is otherwise working ok.

This fault only occurs on the second trip.

If I cancel this second navigation and attempt it again, it works fine again.

**Comment by vshcherb** [comment] 2015-12-07 00:26
>> The screen stays centered on the destination, even though navigation is otherwise working ok.
Could you please explain what exaction it means.

**Comment by Goodingn** [comment] 2015-12-07 06:06
The screen doesn't jump to your current position as you would otherwise expect it to when you press go. It doesn't follow your position either.

**Comment by vshcherb** [comment] 2015-12-09 22:57
>> It doesn't follow your position either.

There is a setting to go back to your location in 15 seconds about, so if it doesn't work, then navigation didn't start at all?

**Comment by Goodingn** [comment] 2015-12-10 06:09
It's not true to say "navigation didn't start at all", because all the other components of navigation are there.

The route is shown on the map, the navigation HUD is there, the arrow current location moves and progesses along the route line, it's just that the map view location never changes and the snap to location setting, as you described, never does anything.

On 9 December 2015 22:57:37 GMT+00:00, vshcherb <notifications@github.com> wrote:
>>> It doesn't follow your position either.
>
>There is a setting to go back to your location in 15 seconds about, so
>if it doesn't work, then navigation didn't start at all? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/2026#issuecomment-163427762

-- 
Neil Gooding

**Comment by Goodingn** [comment] 2015-12-10 17:10
Slight update- the screen doesn't update anything, unless I touch the screen.

All the navigation components are there and th map is fully rendered, but it is all frozen until I touch the screen, then all the navigation updates. It still doesn't move to my current location. Also, there's a blue crosshair circular button to press, but it doesn't help. When I arrived at my destination, the theme changed and fully rendered the map, but the screen still didn't update my position until I pressed the screen again.

I'm not using audio navigation. I'm also sharing a destination to Osmand from POIPocket and it only does this after I've reached my first destination, exited Osmand, picked a new destination from POIPocket to share to Osmand and then attempted to navigate to it.

On 10 December 2015 06:09:00 GMT+00:00, Neil Gooding <neil.gooding@googlemail.com> wrote:
>It's not true to say "navigation didn't start at all", because all the
>other components of navigation are there.
>
>The route is shown on the map, the navigation HUD is there, the arrow
>current location moves and progesses along the route line, it's just
>that the map view location never changes and the snap to location
>setting, as you described, never does anything.
>
>On 9 December 2015 22:57:37 GMT+00:00, vshcherb
><notifications@github.com> wrote:
>>>> It doesn't follow your position either.
>>
>>There is a setting to go back to your location in 15 seconds about, so
>>if it doesn't work, then navigation didn't start at all? 
>>
>>---
>>Reply to this email directly or view it on GitHub:
>>https://github.com/osmandapp/Osmand/issues/2026#issuecomment-163427762
>
>-- 
>Neil Gooding

-- 
Neil Gooding

**Comment by Goodingn** [comment] 2015-12-11 09:00
It's been doing this all the time I've used OSMAnd, some months ago on the other releases of OSMAnd.  I've also got the GPX track recording happening automatically, set to Prevent standalone logging.  May try turning this off for a bit.

**Comment by sonora** [comment] 2016-07-17 16:10
This could be a duplicate of #2643, if it is it would be fixed now.

**Closed** 2016-11-24 11:08 UTC
Labels: Observed
