### ISSUE TITLE
Oriëntation button disappaers / not visible

### ISSUE THREAD

**Issue by davidq1973** [osmandapp/OsmAnd#15016] opened 2022-08-06 08:33 UTC
### Description

The button to toggle between map-orientation-modes is not visible or disappears.

### How to reproduce?

Button is not visible or by touching it - sometimes after toggled all options - it disappears.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 12
Device model: Samsung S20

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by scaidermern** [comment] 2022-08-07 12:53
Duplicate of #14987?

Btw I strongly suggest to make this button visible all the time. Quite frequently users are irritated by this behavior and ask how to bring this button back. If anyone doesn't want this button it can still be disabled via the settings. The current default is a bad choice according to my observations.

**Comment by pebogufi** [comment] 2022-08-07 12:59
Fully agree, or at least make "allways visible" to default.

**Comment by vshcherb** [comment] 2022-08-08 12:12
Delay was already introduced back. Though it will be in 4.3 release only

**Closed by vshcherb** 2022-08-08 12:12 UTC
