### ISSUE TITLE
Areas without any tags are colored with water-blue 

### ISSUE THREAD

**Issue by summoner001** [osmandapp/OsmAnd#17474] opened 2023-06-21 18:36 UTC
### Description
OpenGL coloring Areas that are not tagged or are still empty with water blue.
![Screenshot_20230621-203606](https://github.com/osmandapp/OsmAnd/assets/11212632/85f0fc86-b4d1-43b0-8972-fba2f324dce4)

### Steps to reproduce
Go here: 47.35803° N, 21.74329° E and zoom
### Actual result
Empty areas are colored with blue color.
### Expected result
Coloring with normal colors
### Your Environment
OsmAnd Version: v4.5.2
Android/iOS version: Android 9
Device model: Cubot Quest

###Regression
Yes

**Comment by scaidermern** [comment] 2023-06-21 18:41
Another duplicate of #17442. Already fixed in version 4.5.3.

**Comment by summoner001** [comment] 2023-06-21 18:50
Ok. Sorry for the dupe.

**Closed** 2023-06-22 08:18 UTC
