### ISSUE TITLE
Newly edited POI is not moveable

### ISSUE THREAD

**Issue by mfbehrens99** [osmandapp/Osmand#9249] opened 2020-06-16 06:02 UTC
When you press save to edit OSM a small green circle is added to the map to indicate you edit. These green circles can also be moved around to move the POIs position.
However, the first time you exit that edit screen the move button in the context menu is disabled.

**Comment by scaidermern** [comment] 2020-06-16 07:53
Duplicate of #5970.

**Closed** 2020-06-16 09:13 UTC
