### ISSUE TITLE
Navigation issue: inappropriate use of _link roads

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#2974] opened 2016-08-18 00:46 UTC
OsmAnd versions 2.4.3 (released 2016-08-11) and nightly build 2.4.0#18150M (released 2016-08-17), on Android.

Map:  United States of America Georgia, dated July 31, 2016

When navigating from http://osm.org/go/ZQqt9neRY?node=2692168557 to http://osm.org/go/ZQqt~l_L7?node=1894137664, OsmAnd improperly tried to direct me onto the pair of link roads leading to/from Powers Ferry Road (see attached screenshot), instead of through the intersection.

I can't find anything wrong with the intersection node in OSM.

![screenshot_20160817-204259](https://cloud.githubusercontent.com/assets/11140831/17758197/67d7d86c-64bb-11e6-94b8-a937f7aa3e79.png)

**Comment by jfburke3** [comment] 2016-08-18 00:56
If this is related to the same cause as github #2737 then it isn't fixed in the nightly build I referenced above.

**Comment by polarbearing** [comment] 2016-08-18 06:41
#2737 was fixed by adding a turn restriction to OSM, not changing OsmAnd. I have done that here as well, as the white lines indicate such restriction.

**Comment by jfburke3** [comment] 2016-08-18 15:40
That means every intersection like this would have to be edited in OSM, and it doesn't cover the cases where such a turn is legal, but still a bad routing decision.

**Comment by vshcherb** [comment] 2016-08-18 17:47
Not reproducible in the latest nightly, so it seems to be fixed in 2.4.4 which is coming.

**Closed** 2016-08-18 17:56 UTC
