### ISSUE TITLE
Android display size should (optionally?) be decoupled from osmand UI size

### ISSUE THREAD

**Issue by barathrm** [osmandapp/OsmAnd#16630] opened 2023-03-08 14:05 UTC
# 🚀 feature request

### Context

- Phone: Pixel 4a 5G android 13
- Osmand v4.3.8

### Description

I'd like to decouple android's native "display size" setting from the UI size in osmand.

By "osmand's UI size" I mean the on-screen UI elements like current driving speed, the rotation buttons, search button etc.

Until recently there was a bug which would make osmand's UI size bigger when android's display size was decreased. This happened to give me just about the right UI size for my phone and usage.

Now this bug appears to be fixed and the UI size in osmand is tiny on my phone. In the android settings, I've put the display size to the minimum possible setting because that's what fits my *android UI needs*. However, this causes the osmand UI size to become tiny (imo), especially when the phone is a bit further away (such as mounted in a phone holder or similar). This makes the UI very hard to use in some circumstances.

I don't think the osmand UI size should be tightly coupled to the android UI display size, as osmand's UI and android's UI are used differently and in different circumstances.

### Describe the solution you'd like

I'd like a toggle or similar in osmand's settings which allows me to set osmand's UI scaling independently from android's display size scaling. This would help people use osmand in the way they use it regardless of their display's resolution and physical size.

### Describe alternatives you've considered

I've considered simply increasing android's display size, but then all the icons, buttons etc of the native android UI become huge and almost unusable to me.

**Comment by arncor** [comment] 2023-03-08 23:15
I would really appreciate that too

**Comment by vshcherb** [comment] 2023-03-09 12:54
Screenshots are welcome cause it's hard to understand what's the issue is about

**Comment by arncor** [comment] 2023-03-09 13:21
I would really appreciate that too

Edit :

![Screenshot_20230309-141452.png](https://user-images.githubusercontent.com/91597340/224035597-42a0fe22-40d1-43d7-8ad2-c320a8c8dc7a.png)

![Screenshot_20230309-141431.png](https://user-images.githubusercontent.com/91597340/224035682-5fe00856-7555-4902-8724-8ef010be3f78.png)

**Comment by barathrm** [comment] 2023-03-09 21:42
Don't know whether it helps, but I'm adding photographs, since I don't feel like screenshots show how big the perceived difference in UI scaling is. The pictures show the difference between the minimum and maximum android display sizes on my phone and how they affect the osmand gui. The biggest android size makes the android UI basically impossible to use (huge icons), but it makes the osmand gui comfortable to use when my phone is at arm's length.

![small](https://user-images.githubusercontent.com/76487253/224166639-16040481-593f-454d-b34c-93915de580e4.jpg)
![big](https://user-images.githubusercontent.com/76487253/224166644-b4a1c423-fa75-4ca7-a6e3-44db912b8297.jpg)

**Comment by jotoeri** [comment] 2023-05-02 19:10
Hmm, i'd more call it a bug, instead of a purpose.
-> If i reduce the display size in android settings, everything should shrink, including the Apps UI elements. Instead, OSM UI does the opposite by increasing the size (not only compensating the android shrinking, but even more increasing)! Feels just like a +/- sign bug resp. multiplication/division bug.

**Comment by vshcherb** [comment] 2023-05-10 23:03
OsmAnd UI elements are not different than other system elements they are measured in dp https://developer.android.com/training/multiscreen/screendensities. System increases dp / px ratio and the OsmAnd does with UI elements.

**Comment by sonora** [comment] 2023-05-11 07:40
As a side note: All my (at least Samsung) devices have 2 relevant Android settings under "Display":
- One is called "Screen zoom"  and that one you may not wanti to change from the fafault: It changes e.g. icon sizes device-wide and is enormously intrusive to the overall look and feel.
- The second one is called "Font size and style", and one of its sub-settings "Font size" is an 8 notch slider which scales **only font size** across your device. OdmAnd seems to obey that one flawlessly, both for its menus as well as for all screen widgets which have text, while others like zoom or menu buttons are not affected.

I believe this is prescribed Android behavior, and I cannot reproduce any bug in connection with this second setting.

Of course this does not address the request to separate the OsmAnd widget size from any device-wide settings, which may be justified, but may also in the future collide with potential Android OS developments.

If we decouple, we need to decide if this is to apply to text only (sp units), or the overall screen setup (also dp units).

**Comment by jotoeri** [comment] 2023-05-14 21:43
> I believe this is prescribed Android behavior, and I cannot reproduce any bug in connection with this second setting.

Right, with the second setting. And with the first?
Within lineageOS i have the two settings called as 'Font size' (4 options slider) and 'Display size' (6 options slider). The font size i keep as default, while i intentionally reduce the display size. The reason for this is the reduction not only of the font, but especially of app-icons, which makes the overall view much more clear (imo). But, with reducing the display size, the OSM display size increases, while overall app-icons etc. decrease as intended. 🤷‍♂️

**Comment by tbart** [comment] 2023-10-12 21:54
I don't mind buttons being a little smaller or bigger, but something's off with the scaling calculation on the map's widgets I think. Take this example. Font size and scaling looks perfect in the menu:
![Screenshot_20231012-232645_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/9994131/aebb4b3c-4a0c-467f-9115-52a392a90973)
But that doesn't look right:
![Screenshot_20231012-232419_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/9994131/8a0faafc-495b-4fc3-826d-18101c3eb555)
Widgets are over-compensated (this is on a *small* setting, not a large one!) to the point where they even get cut off.

The interesting thing is that from "Display size" 6 down to 3 everything gets smaller in OsmAnd as well (which is OK and expected).
But at 2 and 1 it gets *bigger*.
This somehow feels as if the display size may be a value with a range like e.g. `-2,-1,0,1,2,3` and OsmAnd casts it to int/throws away the sign bit. Or these are probably fractions or floats that don't get interpreted correctly.

**Comment by irgendwie** [comment] 2023-10-13 07:23
Related: https://github.com/GrapheneOS/os-issue-tracker/issues/2520

I experience the same weird behavior. When decreasing the display size, the buttons in the overlay of OsmAnd get bigger, not smaller. While when increasing the display size (from its default) value, the button sizes increase as expected (I guess?). Only the smallest setting seem to be interpreted incorrectly by OsmAnd.

I thought this only started occurring when I switched from Android 13 to Android 14. At least weird glitches started occurring in other Apps too with this Upgrade.

**Comment by barathrm** [comment] 2023-10-13 08:53
I think that bug is off-topic for this issue ticket. There have been multiple reports about the osmand UI getting *bigger* when the android UI size is configured to be *smaller*. 

This issue ticket is about being able to have a *small android/general app UI* while being able to make the map view's UI *big*, for cases like having a phone with a high resolution or having the phone far away from your face while driving, riding a bicycle etc.

**Comment by vshcherb** [comment] 2023-10-20 14:23
Merged to https://github.com/osmandapp/OsmAnd/issues/18357

**Closed by vshcherb** 2023-10-20 14:23 UTC
Labels: Observed
