### ISSUE TITLE
Misalignment of POI symbols for unsymmetrical areas

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/OsmAnd#5440] opened 2018-05-19 07:20 UTC
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 2.9.3, released 2018-02-08
May style: OsmAnd

POI symbols of POIs mapped as unsymmetrical areas in OSM exhibit a decent misalignment in OsmAnd, leading to the POI icon hovering e.g. over the sea instead over the beach or over the building instead over the parking area.

https://www.openstreetmap.org/#map=18/37.85194/15.30040
https://www.openstreetmap.org/#map=19/48.79751/9.67440

![asdasd](https://user-images.githubusercontent.com/27865200/40266040-648fddfe-5b44-11e8-96e9-bfff588175aa.png)

**Comment by Aiurek** [comment] 2019-08-08 12:42
Here's a pretty special case, where the parking POI symbol is located outside of the actual parking area.

https://www.openstreetmap.org/#map=19/43.31712/6.63123

![Bild2](https://user-images.githubusercontent.com/27865200/62703928-8d8fad00-b9ea-11e9-8a3f-0c62e02b32c3.jpg)

**Comment by scaidermern** [comment] 2019-08-09 06:32
@developers:

You could try to place the POI icon at the _visual_ center of the polygon. Possible solutions:
- [A new algorithm for finding a visual center of a polygon](https://blog.mapbox.com/a-new-algorithm-for-finding-a-visual-center-of-a-polygon-7c77e6492fbc) by MapBox.
- PostGIS function [ST_PointOnSurface](https://postgis.net/docs/ST_PointOnSurface.html)

**Comment by MadWasp79** [comment] 2020-01-31 14:26
Fixed. Will be released in next version + you will need to update maps (in February)

![image](https://user-images.githubusercontent.com/13146346/73546519-0cb7e800-4446-11ea-9018-4732f092596e.png)

**Comment by scaidermern** [comment] 2020-10-22 16:53
Here is an example where the POI symbol is still outside the POI area:
![IMG_20201022_185036](https://user-images.githubusercontent.com/1040784/96904585-9bb6d580-1497-11eb-956c-f6c9e8014290.jpg)
https://www.openstreetmap.org/way/194028869
geo:51.562214,12.969355?z=18

**Comment by scaidermern** [comment] 2020-10-23 13:53
Maybe compare your label placement algorithm with the Carto/Mapnik one. They do a pretty good job, as can be seen from the link of my comment above.

**Comment by MadWasp79** [comment] 2020-10-23 14:31
Cannot reproduce on august and current (october) maps.
![image](https://user-images.githubusercontent.com/13146346/97016518-82745e80-1555-11eb-8e28-2fee013c4497.png)

**Comment by scaidermern** [comment] 2020-10-23 14:42
I see. This occurs only with OsmAnd live. Without live I c can't reproduce it either.

**Comment by vshcherb** [comment] 2020-11-04 09:55
https://github.com/osmandapp/OsmAnd/issues/8788

**Comment by scaidermern** [comment] 2020-11-04 09:58
> #8788

I don't see any relationship here. My issue is about the position of an POI symbol of an area. Without OsmAnd live the symbol is inside the area. With OsmAnd live it is outside of the area.

**Comment by pebogufi** [comment] 2020-11-04 10:36
-- Without OsmAnd live the symbol is correctly drawn inside the area. With OsmAnd live it is drawn outside of the area.

I can reproduce that. After downloading the sachsen map, the poi is ok - in the left part INSIDE parking area. After activating live for sachsen and update live, the poi symbol is moved outside of parling area to the center of geometric area.

**Comment by pebogufi** [comment] 2020-11-04 10:42
After switching off live, position of poi symbol is ok again, surprising !

**Comment by vshcherb** [comment] 2020-11-04 12:26
The issue related to OSM Live is fixed

**Closed by vshcherb** 2020-11-04 12:26 UTC
