### ISSUE TITLE
Crashes while using Bulgarian 

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#1604] opened 2015-08-26 14:38 UTC
Constant crashes occur when trying to enter the Manage map files menu or download maps if the app is running in Bulgarian language. App version 2.1.1.

**Comment by GaidamakUA** [comment] 2015-08-26 15:03
This issue was caused by wrong format string in bolgarian and was fixed by this commit 503e48c275e8969f0911a134c6c5c58d682e1d78. Problem will be gone in new release.

**Closed** 2015-08-26 15:03 UTC

**Comment by vshcherb** [comment] 2015-08-26 21:58
Was it fixed in the branch https://github.com/osmandapp/Osmand/tree/r2.1? We might do a hotfix.
