### ISSUE TITLE
Speed sign in AA Dark mode not readable

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/OsmAnd#21305] opened 2024-11-12 09:41 UTC
### Description

Using AA. The speed sign is black text on black sign. Using osmand+ 4.9.3. See image
![screendump - 2024-11-11-09_12_57](https://github.com/user-attachments/assets/5138c9ea-6c46-4744-b0a8-60ca6de6390e)

### Steps to reproduce

Use darkmode

### Actual result

Sign not readable

### Expected result

Readable sign

### Your Environment (required)

OsmAnd Version: osmand+ 4.9.3
Android/iOS version: 12
Device model: Samsung s10e

**Comment by vshcherb** [comment] 2024-11-12 13:25
Merged

**Closed by vshcherb** 2024-11-12 13:25 UTC

**Comment by yuriiurshuliak** [comment] 2024-11-12 13:27
Duplicate of #21280
