### ISSUE TITLE
Transliteration can't be disabled

### ISSUE THREAD

**Issue by radry** [osmandapp/Osmand#3861] opened 2017-05-31 05:04 UTC
There are similar issues opened but not specifically for this setting. #3738 #3739 

The problem is that (japanese) names are transliterated (incorrectly with chinese transliteration), although "transliteration" is turned OFF in the map language setting.

There are several issues. #3738 is about the incorrect transliteration but this issue is about the transliteration setting not beeing disabled.

How it should work when "transliteration" is disabled:

-Display names in language selected in "map language"
-If that name isn't available, display the local name "name", without transliteration.

**Comment by vshcherb** [comment] 2017-06-02 07:50
This is duplicate of #3738. The transliteration could be disabled for detailed maps and couldn't for basemaps.

**Closed by vshcherb** 2017-06-02 07:50 UTC

**Comment by radry** [comment] 2017-06-02 11:22
@vshcherb 
What are you tlking about? detailed maps? basemaps? 
I'm using offline vector maps and transliteration can not be turned off.

This issue is not a duplicate since #3738 is about the incorrect transliteration but this issue is about it not beeing able to turn off.
