### ISSUE TITLE
Off-line navigation isn't smooth

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#16336] opened 2023-01-27 09:31 UTC
Off-line navigation is going in steps rather than smooth and fluent.
https://user-images.githubusercontent.com/623412/215053385-816d2b4e-b090-4605-b8d0-0e1b58915d9f.mp4

**Comment by scaidermern** [comment] 2023-01-27 10:25
Duplicate of #16081?

**Comment by MarioSwitch** [comment] 2023-01-27 11:12
> Off-line navigation is going in steps rather than smooth and fluent.
> https://user-images.githubusercontent.com/623412/215053385-816d2b4e-b090-4605-b8d0-0e1b58915d9f.mp4
> 
> 

Try using V2 rendering map, maybe it can resolve the bug 🤔

**Comment by miramikes** [comment] 2023-01-27 11:45
> Duplicate of #16081?

Might be ... Video from 16081 looks very similar to mine

**Comment by miramikes** [comment] 2023-01-27 11:46
> Try using V2 rendering map, maybe it can resolve the bug 🤔

I will try.

**Comment by TheSnoozer** [comment] 2023-01-27 15:59
I think the issue IS unrelated to the map Rendering used (at least in my case it was/is).

Try to disable "animate own Position" unser Settings Android Menu → Settings → Profiles → Car profile (or any other profile) →General settings.

Note there is also a "no animations" which IS something else and didn't help in my case.

**Comment by vshcherb** [comment] 2023-01-27 18:12
It's a legacy rendering v1, it has lags with animate own position, you can disable it.

**Comment by vshcherb** [comment] 2023-01-27 18:13
Navigation Settings -> Map During animation -> Animate own position

**Closed by vshcherb** 2023-01-27 18:12 UTC

**Comment by miramikes** [comment] 2023-01-27 19:51
Tested with new engine ... Works perfectly ;)
Probably it is time to switch to ve ;)
Thaks
