### ISSUE TITLE
Zoom levels 19 and 20 almost identical with 3D relief enabled

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17763] opened 2023-07-30 17:00 UTC
With Configure map / 3D relief enabled, zoom levels 19 and 20 are almost identical.

Example:
https://github.com/osmandapp/OsmAnd/assets/1040784/b0ca11c8-d604-4913-8e86-23e76f2e3732

With 3D relief disabled, zoom levels 19 and 20 are more different.

OsmAnd 4.5.8

**Comment by vshcherb** [comment] 2023-07-31 12:33
I think the problem that it doesn't zoom in at all > 19

**Comment by DmitryAlexei** [comment] 2023-07-31 12:54
OsmAnd~ 4.6.0#514m, released: 2023-07-31
If 3D Relief in Configure map enabled + **Heightmap of tested area downloaded**:
- when zooming in or out, 19 and 20 zooms are almost identical in the Düsseldorf (112 m above sea level)
- everything is ok on the sea level
- in mountainous areas (3000 m above sea level) above 16th zoom you zoom underground

NB **Elevation widget: map center** do not show data on 20-22 zoom levels when 3D Relief is enabled

1. 51.0537724, 13.7336570 reproduced 
[logcat.log](https://github.com/osmandapp/OsmAnd/files/12214665/logcat.log)

<details><summary>Without 3d</summary>
<video src="https://github.com/osmandapp/OsmAnd/assets/116079541/f9690219-cb04-40c5-a260-a59e59121d49"></video>
</details>

<details><summary>With 3d</summary>
<video src="https://github.com/osmandapp/OsmAnd/assets/116079541/ba9b54bb-29f6-4d72-8894-91703deeaf2b"></video>
</details>


2. 45.4614662, 12.3519886 not reproduced 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/904bdcfc-e0ae-49e7-9fe8-d37d6daa0cec"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/0eb38366-0bed-41cc-829c-549502760353"  width="300" height="auto"/> </td>
  </tr>
</table>


3. 47.1171377, 10.6151540 (834 m above sea level)  18 and 19 zoom levels are skiped
[logcat.log](https://github.com/osmandapp/OsmAnd/files/12215126/logcat.log)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f912642f-c474-4d25-a7a1-61027741ecd0"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/67ba913d-d867-40f2-b0ef-d2cfb4fbdc31"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/02193068-dfa7-4207-8b8f-9c40fbed3010"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/57207c49-7769-43df-a4d6-52df1c077f29"  width="300" height="auto"/> </td>
  </tr>
</table>

4. 47.10334° N, 11.02653° E (3178 m above sea level) 16-22 zooms are white screens

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/456ecf8e-450a-4e90-b628-535d68b2c1b5"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/64c93167-be93-4bb5-b2b1-3afc12a8ac96"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment] 2023-07-31 15:57
To do:
- [ ] https://github.com/osmandapp/OsmAnd/issues/17764

**Comment by vshcherb** [comment] 2023-08-01 14:15
To do:
- [ ] Check this issue (Don't allow to zoom in / out 3D closer than 50m - is fixed)
- [ ] Check blinks / flickering on zoom 6-7 between (Video)

**Comment by michaelblyons** [comment] 2023-08-12 17:26
Is this why I can't see street names at high zoom anymore?

**Comment by vshcherb** [comment] 2023-08-15 11:52
**Main issue**
The problem is in 3D relief when reaching 19th zoom you have only 50m left on top of relief, so further zoom in goes under relief. Camera height is calculated based on zoom and it's based on 0m relief. So zoom is consistent around the world but it allows then for some places to go under relief.

**To do**
The most obvious we can do don't allow to zoom in further than possible and display toast that maximum level is reached

**Comment by littlehelper** [comment] 2023-08-19 04:20
> **Main issue** The problem is in 3D relief when reaching 19th zoom you have only 50m left on top of relief, so further zoom in goes under relief. Camera height is calculated based on zoom and it's based on 0m relief. So zoom is consistent around the world but it allows then for some places to go under relief.
> 
> **To do** The most obvious we can do don't allow to zoom in further than possible and display toast that maximum level is reached

Did I understand and observe it right that on high mountains, e.g. above 2000m altitude, the maximum zoom level will be around 16 for example? Does this mean that POIs shown only at higher zoom levels cannot be displayed anymore in mountain areas?
This will affect mountain huts and restaurants for example.

**Comment by vshcherb** [comment] 2023-08-19 08:40
Yes valid point, I don't see solution yet

**Comment by spaanse** [comment] 2023-08-26 12:23
Would it work to offset the camera's vertical coordinate with the height at the center. This gives the same relative position compared to the point we want to look at. I think the main issue is that when panning the height becomes jittery.

**Comment by scaidermern** [comment] 2023-08-26 15:35
> Would it work to offset the camera's vertical coordinate with the height at the center. This gives the same relative position compared to the point we want to look at. I think the main issue is that when panning the height becomes jittery.

Sounds like a good solution to me (not sure how hard it is to implement this, but sounds feasible).

A jittery height while panning is probably better than the current problem where you can pan "into" a mountain.

**Comment by ManDay** [comment] 2023-08-27 18:03
Would it not be consistent to keep the camera at a fixed altitude, but instead make zoom **change the FOV**, analogous to the behaviour in the orthographic projection?

There are also artefacts in perspective projection, such as the map scale no longer matching anything. That becomes very apparent when the camera is low above the terrain, while the terrain is far from sealevel (at which, I suspect, the map scale is drawn).

**Comment by jojoob** [comment] 2023-09-01 07:22
Even if the point was already made I want to add some screenshots to illustrate the problem on a high mountain area. **The map also becomes very blurry on high "mid-zoom" levels.**

<details>
<summary>Terrain: ON, Zoom 15</summary>

![terrain-on-zoom-15](https://github.com/osmandapp/OsmAnd/assets/4180675/52bc90e4-6164-497b-8464-cbf464069eb4)

</details>

<details>
<summary>Terrain: OFF, Zoom 15</summary>

![terrain-off-zoom-15](https://github.com/osmandapp/OsmAnd/assets/4180675/15007aa8-930d-4895-be36-eade20099990)

</details>

<details>
<summary>Terrain: OFF, Zoom 18</summary>

![terrain-off-zoom-18](https://github.com/osmandapp/OsmAnd/assets/4180675/0ae2e26b-2ff4-4318-b360-3dd40cd96346)

</details>

<details>
<summary>Terrain: ON, Zoom 18</summary>

![terrain-on-zoom-18](https://github.com/osmandapp/OsmAnd/assets/4180675/482fcfed-cbc8-4f42-a8c8-cad28513131f)

</details>

**Comment by scaidermern** [comment] 2023-09-01 07:40
I've also noticed the bluryness with enabled 3D relief. That's why I keep this feature disabled.

**Comment by jojoob** [comment] 2023-09-08 11:18
Closing this through https://github.com/osmandapp/OsmAnd-core/pull/624 seems like a mistake?!

**Comment by scaidermern** [comment] 2023-09-08 11:19
Yep, also looks wrong to me. Please re-check.

**Closed** 2023-10-17 11:26 UTC
Labels: opengl

**Comment by jojoob** [comment] 2023-10-19 08:48
Hi @vshcherb which pull request /commit exactly fixes this issue?

**Comment by vshcherb** [comment] 2023-10-20 15:13
https://github.com/osmandapp/OsmAnd-core/pull/634
https://github.com/osmandapp/OsmAnd/pull/18324
