### ISSUE TITLE
Pause navigation at intermediate stops

### ISSUE THREAD

**Issue by sjvudp** [osmandapp/OsmAnd#19069] opened 2024-02-09 23:08 UTC
### Describe the idea (required)

I had planned a shopping route with intermediate stops for each shop. I also recorded the route.
Unfortunately when arriving at the first intermediate stop, route recording allowed to "pause" the recording, but navigation did not. So OsmAnd talked to me while I was in the shop with the phone.
It would be very useful, to pause the route at an intermediate stop, and also offer the option to store the parking position.

### Tell us about the expected behaviour (required)

When reaching an intermediate stop that is not just there for routing selection only, it's typical that one stops there for some time.
Thus allow to pause navigation.

### Tell us about alternatives you've considered (required)

Stop navigation and plan a new route after the first stop 8-(

**Comment by scaidermern** [comment] 2024-02-10 08:13
Duplicate of #19057?

**Comment by vshcherb** [comment] 2024-02-27 17:03
Yes make it easier to pause navigation should solve this case https://github.com/osmandapp/OsmAnd/issues/19057

**Closed by vshcherb** 2024-02-27 17:03 UTC

**Comment by sjvudp** [comment] 2024-03-28 22:41
> Duplicate of #19057?

I think there is a difference: While I was using intermediate stops for each shop, #19057 just stopped along the tour (as I understand it).
Considering that "intermediate stops" are not "vias" (preference of routing), the default action should suggest to stop there (maybe also with marking the parking position (when going by car)), etc.
