### ISSUE TITLE
Next turn gets skipped

### ISSUE THREAD

**Issue by tbertels** [osmandapp/Osmand#8072] opened 2019-12-11 14:52 UTC
(OsmAnd 3.5.4 on Android 6.0.1, using OsmAnd's in-app offline routing)

During this trip, at least one turn got skipped:

The screenshots show this place: https://www.openstreetmap.org/?mlat=50.59256&mlon=5.26222#map=17/50.59256/5.26222
The next turn direction shows https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.58713%2C5.26217%3B50.58417%2C5.26047

![Screenshot_20191211-131856](https://user-images.githubusercontent.com/3265870/70627357-652cef00-1c26-11ea-8900-ee58f91be303.jpg)
![Screenshot_20191211-132001](https://user-images.githubusercontent.com/3265870/70627365-66f6b280-1c26-11ea-8e5e-ed8f1e06d55b.jpg)

**Comment by vshcherb** [comment] 2019-12-11 15:16
Can't reproduce with fresh maps, so if it is still in December maps it will be fixed in Live or January maps

**Closed by vshcherb** 2019-12-11 15:16 UTC

**Comment by tbertels** [comment] 2019-12-11 20:57
I'm actually using OsmAnd Live, but I don't think it's related to map data anyway because I can't reproduce with simulate route.

**Comment by vshcherb** [comment] 2019-12-16 17:57
This is quite strange we used to have a problem prior 3.5 on OsmAnd Live version but it should be fixed with 3.5. So I would give it a try without Live and with. Usually bugs with Live is quite hard to reproduce cause it is possible that there is a big collection of deprecated files
