### ISSUE TITLE
Feature improvement: Different PI display (map style dependant) 

### ISSUE THREAD

**Issue by homersimpsons** [osmandapp/Osmand#2556] opened 2016-05-16 20:21 UTC
I created a special list of POI name z_car to display in car mode, but when I select : POI (in overlay settings) Osmand activate those POI on all map style (general, car, pedestrian, bike) then, in my mind, it should be configurable for each map style and not for all map.

**Comment by homersimpsons** [comment] 2016-05-21 12:39
And, in addition, add a feature to choose which POI icon/Text to display in the map because I activated fuel and parking in POI and there are all double rendered: one by the map, the other one clickable. To improve performance it would be useful to get POI display limitation (in number) to show only nearest POI.

**Comment by sonora** [comment] 2016-06-01 16:20
Issue 1 is a duplicate of #2611.

**Closed** 2016-11-24 12:32 UTC
Labels: Nice to Have
