### ISSUE TITLE
Pedestrian navigation issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8035] opened 2019-12-04 08:55 UTC
From: 52.50087, 13.44474
To: 52.49986, 13.44433
OsmAnd builds the route longer than the OSM navigation for the pedestrian navigation profile.
![image](https://user-images.githubusercontent.com/50198677/70127901-9c2e5e00-1684-11ea-8014-0be9b351aa1d.png)

https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=52.50087%2C13.44474%3B52.49986%2C13.44433#map=18/52.50054/13.44512

**Comment by scaidermern** [comment] 2019-12-04 10:03
Duplicate of #8023.

**Comment by MadWasp79** [comment] 2020-01-09 10:49
fixed by setting 'highway=residental' priority higher (to 1.1 from 1) in routing.xml

**Closed by MadWasp79** 2020-01-09 10:49 UTC

**Comment by VIMVa** [comment] 2020-01-09 13:37
> fixed by setting 'highway=residental' priority higher (to 1.1 from 1) in routing.xml

Searched my phone top to bottom but I can't find any routing.xml file.
Please be so kind to indicate where to find it. Thanks.

**Comment by vshcherb** [comment] 2020-01-10 15:57
@VIMVa osmand-data/routing/routing.xml

**Comment by VIMVa** [comment] 2020-01-10 16:15
I do have a folder:
/storage/emulated/0/Android/data/net.osmand.plus/files/routing
But it is empty. No files (hidden or other) in the folder.

**Comment by vshcherb** [comment] 2020-01-21 19:43
You can add a file there and use it in OsmAnd
