### ISSUE TITLE
Can't search building names

### ISSUE THREAD

**Issue by tobiasBora** [osmandapp/OsmAnd#17907] opened 2023-08-12 18:42 UTC
## Description

The search engine often gives really weird priority (e.g. if I put multiple words, it seems to output all items that matches at least one word instead of the "and" of all words), and often misses some important results. For instance, after downloading the maryland map, I can't find the building called "Brendan Iribe Center for Computer Science and Engineering" after typing "Brendan Iribe Center". OSMand only outputs street containing Brendan, like "Brendan avenue" or "Brendan court", but not a single entry mentions the building. However, the map does contain this building, labelled "Brendan Iribe Center for Computer Science and  Engineering (8125)" in OSMand.

### How to reproduce
1. Download the maryland map
2. Go close to the Brendan Iribe Center that is located in [8125 Paint Branch Dr, College Park, MD 20742.](https://goo.gl/maps/m6TfZezHoabJfroC6)
3. search for "Brendan Iribe Center"

### Actual result

Only unrelated streets are displayed

### Expected result

I expect the first result to be the Brendan Iribe Center.

**Environment**
OsmAnd Version: OsmAnd~ 4.3.12 (fdroid)
Android/iOS version: 11
Device model: Samsung XCover 4s

**Comment by DmitryAlexei** [comment] 2023-08-14 06:59
Please use address search https://osmand.net/docs/user/search/search-address
or POI search https://osmand.net/docs/user/search/search-poi

**Comment by vshcherb** [comment] 2023-08-14 10:14
Nominatim finds it ok - https://nominatim.openstreetmap.org/ui/search.html?q=Brendan+Iribe+Center+for+Computer+Science+and+Engineering+8125.

So no change in OSM needed, not clear does OsmAnd finds in any situation or not

**Comment by DmitryAlexei** [comment] 2023-08-15 09:58
OsmAnd~ 4.6.0#609m, released: 2023-08-13
finds ok

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/dc52669c-7c38-419c-9fc6-430e4b3e6a45"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/101c918b-42dd-4978-a060-1a2be82c8edf"  width="300" height="auto"/> </td>
  </tr>
</table>

@tobiasBora try updating OsmAnd to the latest version (4.5.10 from Google Play)

**Comment by vshcherb** [comment] 2023-08-18 10:13
Tried on a website (same search engine) - near that location https://osmand.net/map#14/38.9792/-76.9355 - search is fine by "Brendan Iribe Center for Computer Science and Engineering".

So probably the issue is fixed with new update

**Closed by vshcherb** 2023-08-18 10:13 UTC

**Comment by tobiasBora** [comment] 2023-08-18 14:07
Thanks for your answers. So I don't know why, but after connecting to internet, I can't reproduce this bug anymore… I don't know what happens, if internet brought new data to be cached by OSM or if I just made a stupid mistake…

**Comment by vshcherb** [comment] 2023-08-19 08:42
it might be there was an issue with typo , osmand search doesn't handle typos in a good way for now
