### ISSUE TITLE
Driving triangle and shadow

### ISSUE THREAD

**Issue by DaanLT** [osmandapp/OsmAnd#16787] opened 2023-03-23 16:37 UTC
### Description
Driving triangle and shadow when driving. Triangle got smaller in this version and not representing real position, real position is where shadow center is.

### Steps to reproduce
just regular app use

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/128729388/227272527-44ca9760-cf7a-4d34-8fe5-f8c967cc18fe.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.4.4, released 2023-03-22

Android/iOS version: car android 10 head unit, 1280x720 screen, 

Device model:

**Comment by Zirochkabila** [comment] 2023-03-23 16:55
OsmAnd~ 4.4.0#14261mqta, Released: 2023-03-23
Not reproduced

@DaanLT Please clarify:
1. Profile
2. What cards do you use
3. Logcat file: Menu > Help > Send logcat log

**Comment by DaanLT** [comment] 2023-03-24 08:09
hi, 
browse and car driving profile
logcat attached
[logcat-4.4.4.log](https://github.com/osmandapp/OsmAnd/files/11059782/logcat-4.4.4.log)

![20230324_100218](https://user-images.githubusercontent.com/128729388/227461780-ef8759bf-7a86-49be-9052-863fa0956378.jpg)

**Comment by DaanLT** [comment] 2023-03-24 13:29
The same after full data wipe

**Comment by benoitsauvard** [comment] 2023-04-02 18:22
Same issue for me on my samsung tabactive 3 but not on A52 phone. Both run same version.
On the tab, pointers are also "buggy", there are too big when zooming despite change police size and/or zoom in tab's parameters.
Can we change pointers by import pictures? can we edit size somewhere in a file?

**Comment by DaanLT** [comment] 2023-04-03 09:34
same issue with versions:
OsmAnd 4.4.6 released 2023-03-31
nightly: OsmAnd~ 4.5.0#14290mqta released 2023-04-03

**Comment by jf-simon** [comment] 2023-04-05 05:21
I have also the same. Shaddow is too big and centre, and not not the icon. 
OsmAnd+ 4.4.6, veröffentlicht: 2023-03-31

**Comment by jf-simon** [comment] 2023-04-05 08:07
I hava a S10e with Android 12
This issue is also shown, using Andoid Auto.

**Comment by DaanLT** [comment] 2023-04-05 08:08
car head unit, UIS7862 based (ums512), android 10 (API/SDK 29), 
https://gadgetversus.com/processor/unisoc-uis7862-specs/

**Comment by pebogufi** [comment] 2023-04-05 08:59
Same shape with big shadow as @DaanLT with 
Samsung tab S5e, Android 10, OsmAnd~ 4.5.0#14292mqta, veröffentlicht: 2023-04-04.
BUT normal shape without shadow with 
Samsung S10, Android 12, OsmAnd~ same version 14292 !!

**Comment by pebogufi** [comment] 2023-04-05 09:01
@Zirochkabila   
Same shape with big shadow as @DaanLT with
Samsung tab S5e, Android 10, OsmAnd~ 4.5.0#14292mqta, veröffentlicht: 2023-04-04.
BUT normal shape without shadow with
Samsung S10, Android 12, OsmAnd~ same version 14292 !!

**Comment by scaidermern** [comment] 2023-04-05 09:14
Looks like only screens with a certain size are affected?

**Comment by jf-simon** [comment] 2023-04-05 09:37
seems so, on my other, bigger device, there is no shaddow.

**Comment by pebogufi** [comment] 2023-04-07 12:21
> seems so, on my other, bigger device, there is no shaddow.

For me NO, just the opposite.
Samsung tab S5e, Android 10, 10", big shaddow
Samsung S10, Android 12, 6.1", NO shaddow

**Comment by DaanLT** [comment] 2023-04-07 13:55
nighty OsmAnd~ 4.5.0#14304mqta, released 2023-04-07
better quality screenshot:
![Screenshot_2023-04-07_161208](https://user-images.githubusercontent.com/128729388/230620532-b272a306-2051-43be-97d0-d9d3a42c2fc6.jpg)

**Comment by franco999** [comment] 2023-04-07 14:42
Xiaomi Mi A2 Lite, Android 12.1

OsmAnd~ 4.5.0#14298mqta, released: 2023-04-06

![Screenshot_20230407-113857_OsmAnd~](https://user-images.githubusercontent.com/12088580/230627492-071d9d9b-f7ce-42a3-a7f6-ad9379c54da5.png)

**Comment by Zirochkabila** [comment] 2023-04-07 15:00
OsmAnd~ 4.5.0#35730m, Released: 2023-04-07

<img width="1220" alt="Screenshot 2023-04-07 at 17 59 19" src="https://user-images.githubusercontent.com/104760013/230630600-b31812da-f3c5-40dc-a16b-c4586564cf57.png">

**Comment by Bohuslavek** [comment] 2023-04-08 15:31
hello, the error of displaying the driving triangle when it is off the road appears on my CARPE ITER device which has ANDROID 9. Please fix the error for Android 9 as well.
thank you very much

**Comment by sonora** [comment] 2023-04-08 15:52
Potentially introduced here https://github.com/osmandapp/OsmAnd/commit/98a71e71c65ff18239e2458df838c36b03071b24, and recently published in our v4.4.6?

**Comment by Bohuslavek** [comment] 2023-04-18 13:45
Please, when will the error of the guidance triangle and its shadow be removed.

![20230418_153118](https://user-images.githubusercontent.com/130236543/232797043-0a156bf6-e199-48cd-9ef2-bc8af41b0866.jpg)

**Comment by Bohuslavek** [comment] 2023-04-18 13:52
version 4.4.7. the error is still the same.
![20230418_152704](https://user-images.githubusercontent.com/130236543/232798964-10d5e0c9-47d1-4836-93fd-59578e9d1b64.jpg)

**Comment by dmpr0** [comment] 2023-04-27 15:12
Should be fixed as part of task for replacing raster location images with VectorDrawable.
@Zirochkabila need to test.

**Comment by Bohuslavek** [comment] 2023-04-27 16:58
Hi, but when will the fix be done?  Now osmand+ without update.  Thanks

David Bohuslávek

☎️ +420 777 570 900
💻 ***@***.***

Odesláno z Galaxy S20

Dne čt 27. 4. 2023 17:12 uživatel Dmytro Prodchenko <
***@***.***> napsal:

**Comment by pebogufi** [comment] 2023-04-29 09:09
For me it is worse than before:
Samsung tab S5e tab 10" shows now shadows FOR nearly ALL smbols (except blue car). Before that change, i could use the marked symbol without shadow.
![Symbols Samsung Tab S5e 10](https://user-images.githubusercontent.com/18628183/235294347-6548413f-6c55-4cd2-8e93-3a30085e19d2.jpg)



Smartphone S10 6.1" which is perfect !!!

![Symbols S10 6 1](https://user-images.githubusercontent.com/18628183/235294653-460ab348-19d2-4be6-a8aa-0bab966c5f1f.jpg)

Both devices using 
OsmAnd~ 4.5.0#35864m, veröffentlicht: 2023-04-29

**Comment by Zirochkabila** [comment] 2023-04-29 09:22
Shadow that appeared on the other icons - is shown in the previous comment https://github.com/osmandapp/OsmAnd/issues/16787#issuecomment-1527677347
Confirmed.

**Comment by prallo** [comment] 2023-05-27 05:20
Shadow still there !
Android 13
Samsung Galaxy S23 Ultra
Osmand+ 4.5

**Comment by prallo** [comment] 2023-06-01 03:50
Osmand 4.5.1
Still not fixed !!!

**Comment by prallo** [comment] 2023-06-03 05:59
Where to follow ?

**Comment by vshcherb** [comment] 2023-06-03 11:01
Once the issue is closed you will receive notification on email

**Comment by prallo** [comment] 2023-06-18 04:17
Osmand Pro 4.5.2
Android 13
Samsung S23 Ultra

Problem still there !

**Comment by vshcherb** [comment] 2023-06-18 07:36
@prallo issue not closed! no need to spam

**Comment by HostedDinner** [comment] 2023-08-06 17:32
Same issue:
OsmAnd+ 4.5.9
Android 13
Samsung S22 Ultra

**Comment by dmpr0** [comment] 2023-08-15 09:33
Should

**Comment by dmpr0** [comment] 2023-08-18 08:48
Reopened because it still reproducible if Display size is set to minimum. 

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c1f05fbb-27eb-4ae1-8293-15f447d8778d"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8769a70a-a93c-420c-9f34-d49d03e97836"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/08b614cf-8913-41c6-a3cf-6ca5e4611129"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/17218621-7924-4628-afff-9cb31d91da27"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment] 2023-08-18 09:33
Now icon is centered so it's smaller issue now

**Comment by prallo** [comment] 2023-09-02 11:21
Osmand+ Pro 4.6.0, all good for me now.
Thanks a lot  !

**Comment by prallo** [comment] 2023-09-02 11:51
Osmand+ Pro 4.6.0, all good for me now.
Thanks a lot  !

**Comment by DaanLT** [comment] 2023-09-03 17:42
4.6.0 - no changes, the same dark shadow

**Comment by gaitjan** [comment] 2023-12-17 20:39
On a Google Pixel 7 Pro, Android 14, security update December 5, 2023, OsmAnd 4.5.10, there's an annoying non transparent shadow with the position icons.
On a Nokia XR20, Android 13, security update November 1, 2023, Osmand 4.5.10, there's no shadow with the position icons.

**Closed** 2024-01-03 23:24 UTC
Labels: and-bugs
