### ISSUE TITLE
Memory safety bug on 4.8.6, instant crash with MTE enabled

### ISSUE THREAD

**Issue by anoo2niem** [osmandapp/OsmAnd#21002] opened 2024-10-08 18:48 UTC
### Description

Hi,

I just updated through f-droid to 4.8.6.
I'm using grapheneos with MTE enabled.
The app crashes instantly after update.

### Steps to reproduce

Open version 4.8.6 with MTE enabled on grapheneos or regular pixel 8 or up with mte enabled in developer options.

### Actual result

Crash

### Expected result

No crash

### Your Environment (required)

```
type: crash
osVersion: google/caiman/caiman:14/AD1A.240905.004/2024092900:user/release-keys
uid: 10176 (u:r:untrusted_app:s0:c176,c256,c512,c768)
cmdline: net.osmand.plus
processUptime: 4s

signal: 11 (SIGSEGV), code 9 (SEGV_MTESERR), faultAddr d00c467c794a8a0
threadName: Worker (pooled)
MTE: enabled

backtrace:
    /data/app/~~ycVj5RzEuyS2wHLpyapcbQ==/net.osmand.plus-X4u5aRswlxWUKYjzp1du8Q==/lib/arm64/libQt5Core.so (ffcps_default_utf+208, pc 54f49c)
    <anonymous:c74a41201000> (pc fb58)
```

If there's any more data i could obtain which helps u in any way, please kindly guide me on how to obtain it.

**Comment by yuriiurshuliak** [comment] 2024-10-09 08:06
Duplicate of https://github.com/osmandapp/OsmAnd/issues/20951

**Closed** 2024-10-12 14:42 UTC
