### ISSUE TITLE
Ignoring Turn Lanes on straight motorways with exits (used to be mute turn announcements)

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#19065] opened 2024-02-09 19:54 UTC
### Description

The bug appears if you drive straight on a one-way road (turn lanes widget is absent):
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/32092837/a6f26108-b739-4b1e-aa7b-465f224bd4cd"  width="350" height="auto"/> </td>
  </tr>
</table>
But if you build a route not staright, but make an exit from the road, then in the same place the widget is displayed correctly on the screen:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/32092837/f1b31f0e-4ac8-46c5-80c4-944558f5947a"  width="350" height="auto"/> </td>
  </tr>
</table>

[https://www.openstreetmap.org/way/627781977](https://www.openstreetmap.org/way/627781977)
OSM data is correct (In older OsmAnd versions, the widget is displayed correctly. I guess the widget may be “broken” in one of the nightly builds).

On two-ways roads the widget displays correctly on the screen.

### Steps to reproduce

Build route (Car profile) from 53.8347027, 27.5402354 to 53.8352342, 27.535455

### Actual result

Turn lanes widget is absent

### Expected result

The widget should appear correctly on the screen.

### Your Environment (required)

OsmAnd Version: OsmAnd Nightly 4.7.0 1563m 2024-02-09
Android version: Android 11
Device model: Lenovo TB-8506X

**Comment by yuriiurshuliak** [comment] 2024-02-12 17:13
The bug has been reproduced. If you enable simulation of navigation on the above coordinates, the turn lanes widget is not displayed.

OsmAnd~ 4.7.0#1578m, released: 2024-02-12

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f7e49384-317d-4995-ba87-e46dc8cacd24"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/e66cb365-2217-4210-9ba4-d1107d37c268"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment] 2024-03-11 23:53
@yuriiurshuliak https://osmand.net/map/?start=53.834461,27.542199&finish=53.837044,27.534592&profile=car#16/53.8365/27.5329 your 2-nd screenshot is confusing. Please retest it.

For motorways / trunks with straight go ahead lanes are not dispalyed anymore cause it's not a significant information - https://osmand.net/map/?start=53.834461,27.542199&finish=53.835803,27.530258&profile=car#16/53.8365/27.5329 (to less disturb the driver.

https://github.com/osmandapp/OsmAnd/issues/18639

**Comment by Prusaker** [comment] 2024-03-12 05:56
>
> For motorways / trunks with straight go ahead lanes are not dispalyed anymore cause it's not a significant information - https://osmand.net/map/?start=53.834461,27.542199&finish=53.835803,27.530258&profile=car#16/53.8365/27.5329 (to less disturb the driver.

This is inconvenient when navigating. Is it possible to make this option customizable?

**Comment by yuriiurshuliak** [comment] 2024-03-13 14:50
Checked it again with live updates and no live updates. In the second screenshot, can see that the turn lane is not displayed.

OsmAnd~ 4.7.0#1818m, released: 2024-03-13

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5e9ade1c-c64b-48eb-8467-75727186d5b8"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/e1b06255-95bd-4a4c-a71a-accb7c65c0a9"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Galbar** [comment] 2024-03-31 21:14
I am having the same problem. I really loved how every now and then the app would reassure me about which lanes I should be on. Where I live there are a number of highways that seamlessly split into different ones and OsmAnd would tell me which lanes I should be on in advance. This was extremely useful. 

Now I either already know I where I should be or I have to deduce it by a combination of looking at the road OsmAnd thinks I am on (there are highways that overlap in some sections); looking ahead in the map, trying to discern which split I should be taking; and some amount of guess work.

This gets specially bad when I don't know the road. My wife and I have missed more than a few exits, some leading to long detours. This happened in a recent holiday trip we took. My wife, that generally prefers google maps, explicitly asked where were the lane indicators, because that's one of the features she learned to love when I "make" her use OsmAnd.

Honestly, I thought that it was a bug when they stopped appearing some time ago, I waited to see if it was fixed; then thought I may have messed up some setting and spent some time trying to get it to work; finally, today I decided to search the web and found this issue.

Please, bring them back. Maybe as a setting? :pleading_face:

**Comment by DmitryAlexei** [comment] 2024-04-01 12:58
@Galbar what is the version of your OsmAnd app? 
You can try beta from Google play, lanes widget should work

**Comment by vshcherb** [comment] 2024-04-01 13:50
Possible bug https://test.osmand.net/map/?start=52.282337,4.952173&finish=52.286098,4.945972&profile=car&params=car,prefer_unpaved#17/52.28475/4.94752 but here it's fine https://test.osmand.net/map/?start=52.282337,4.952173&finish=52.286918,4.950843&profile=car&params=car,prefer_unpaved#17/52.28475/4.94752

**Comment by Galbar** [comment] 2024-04-01 15:34
@DmitryAlexei I'm on OsmAnd+ 4.6.13 from PlayStore. How has the lanes widget's behaviour changed in the beta from the current implementation? is there an option that shows it always, as before?

**Comment by ivanPyrohivskyi** [comment] 2024-04-01 15:58
https://test.osmand.net/map/?start=52.282337,4.952173&finish=52.286098,4.945972&profile=car&params=car#17/52.28475/4.94752
Expected ```"KL:KL+|KR"``` (better, because both roads are _motorway_link_) or ```"[MUTE] C:C+|TSLR"``` (worse variant)

https://test.osmand.net/map/?start=52.282337,4.952173&finish=52.286918,4.950843&profile=car&params=car,prefer_unpaved#17/52.28475/4.94752
Expected ```"KR:KL|KR+"``` (similar as above)

From test 54
https://test.osmand.net/map/?start=43.717890,-79.508570&finish=43.715950,-79.525790&profile=car#16/43.7180/-79.5211
Expected ```"[MUTE] C:+C|+C|+C,TSLR|TSLR"``` (better variant, because we continue moving on motorway and have attached motorway_link)

From test 71
https://test.osmand.net/map/?start=48.771830,8.226070&finish=48.772407,8.224423&profile=car#19/48.77218/8.22436
Expected ```"[MUTE] C:+C,TL|+C|TSLR"``` or ```"C:+C,TL|+C|TSLR"``` (better variant, because we have 3 different ways on junction)

From test 68
https://test.osmand.net/map/?start=37.422236,-121.931419&finish=37.419493,-121.945286&profile=car#17/37.42078/-121.94060
Expected ```"[MUTE] C:+C|+C|+C,TSLR|TSLR"``` (better variant, because we continue moving on motorway and have attached motorway_link)

From test 49
https://test.osmand.net/map/?start=55.372941,10.443202&finish=55.371143,10.446684&profile=car#18/55.37226/10.44533
Expected ```"[MUTE] C:+C,TSLL|+C,TSLL"``` (better variant, because we continue moving on secondary and have attached secondary_link)

**Comment by DmitryAlexei** [comment] 2024-04-04 20:53
OsmAnd~ 4.7.0#1981m, released: 2024-04-04
The Lanes widget appears as expected only when you turn right. No turn lanes widget when going straight.


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/7ccda129-79e4-47c9-94b4-aa88b9902341"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/98e26380-4970-44bd-a128-f882c440a2ee"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment] 2024-04-04 21:01
@Galbar  Please make sure, that the Lanes widget is enabled in your driving profile. Go to Menu > Settings > Driving (or Cycling etc) > Configure screen > Top panel and see if Lanes widget is present. 

You can also try beta from Google Play.

**Comment by vshcherb** [comment] 2024-04-05 12:56
So many issues are fixed. The only thing we consider with this task to enable all turn lanes when OSM Editing plugin is on but that could be postponed for 4.8 which could start soon.

**Comment by Galbar** [comment] 2024-04-07 08:45
I just got the update for 4.7.6 (I entered the beta program). I tried the following road split: https://test.osmand.net/map/?start=41.558891,2.256682&end=41.554950,2.239451&profile=car#16/41.5566/2.2432 .

On the web it shows `Turn slightly left (+TSLL|+TSLL|TSLR|TSLR) onto C-33 and go 0.9 km`. But on the phone it does not show the lanes widget. I have triple checked that the lanes widget is enabled in the top panel and it is placed in the second row, name of the street being the first row.

This split is specially confusing, the road splits in half, there is no exit or anything.

**Comment by DmitryAlexei** [comment] 2024-04-11 17:14
@Galbar I have checked your route using OsmAnd~ 4.7.0#2041m, released: 2024-04-11 (alfa or nightly version of the app) and in the route detail (navigation > swipe to the top of the screen > Details > Turn - by - turn instructions) I see, that left turn is indicated. In realistic simulation of navigation left turn is also indicated. Please see screenshots. 
So your issue will be resolved in the future updates of the app.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/216b2482-5257-4aaf-a823-ad2d8575cd29"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/76b34b6e-7196-41d4-814a-653f7511971f"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Galbar** [comment] 2024-04-22 18:41
Hi, I just came back from a road trip this weekend. The turn lanes widget didn't show up (and there were multiple road splits). That was 4.7.6.
I just now got an update to 4.7.10, from Play Store and I tried (with the simulation option) to navigate the same spot as @DmitryAlexei shows in his screenshots.
I get the arrows to show in the detailed view but still no widget shown in the navigation view.

Is this a wrong configuration thing on my side or the fix has not yet been released? I just want to make sure I didn't mess some config up when trying things. 

Below you can find screenshots and a video.

|||
|---|---|
|![image](https://github.com/osmandapp/OsmAnd/assets/3595851/d4b97425-b376-46f9-95e2-3b88c37a154e)|![image](https://github.com/osmandapp/OsmAnd/assets/3595851/fe45dabe-39d2-4fce-b27a-f383c59b11be)|


https://github.com/osmandapp/OsmAnd/assets/3595851/85fccd27-02ab-4462-a27f-dcfda65fc1d4

**Comment by DmitryAlexei** [comment] 2024-04-22 21:27
@Galbar I've tried to reproduce your issue on the latest OsmAnd nightly and OsmAnd 4.7.9, released: 2024-04-15 and both times lanes widget was active from the very beginning of the route. I tried different simulation types (fast, realistic), deleted map markers widget from top panel, but the lanes widget displayed all the times.
So the problem might be in the configuration of your top widget panel.

In that case, I would propose you to reset to default the top widget panel and try realistic simulation of your route one more time (go to menu > configure screen > top panel > swipe to the bottom of the screen > reset to default)

**Comment by Galbar** [comment] 2024-04-23 08:58
@DmitryAlexei Thank you! That worked! 🎉 

I had no idea the reset to default button existed 🤯

**Comment by mikehgentry** [comment] 2024-04-23 13:10
Sounds similar to #18755

**Comment by vshcherb** [comment] 2024-06-28 18:44
Proposed to add setting to OSM editing to display turn lanes in all cases

**Comment by vshcherb** [comment] 2024-06-28 18:45
Anyway backend should provide a setting (constant) Routing Context / Configuration or somewhere to display them. In order to speed up development proposal to support attribute from routing.xml for now

**Comment by MarcMart** [comment] 2024-08-04 22:43
Just wanted to reinforce that adding a setting which enables constant lane assistance again would be great It has been been more than once a life-saver in unknown complex urban environments where straight go ahead lanes are sometimes absolutely not easy to identify. Please bring it back soon! :)

**Comment by vshcherb** [comment] 2024-08-30 13:11
We can add setting to "Turn lanes widget" - "Display on all intersections" ("Lanes will be displayed on all passing intersections regardless voice instructions")

**Comment by MarcMart** [comment] 2024-08-30 23:33
Hi Victor, that would be absolutely awesome!
 
Keep up the good work and by the way - I am almost mapping daily to make our map better and better (username Mar Mar) ;) So I do not only complain but also contribute ...
 
Marcos

**Closed** 2024-11-05 10:14 UTC
Labels: navigation, !, ^

**Comment by dmpr0** [comment] 2024-11-11 12:07
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/b35d2026-6dd4-4c31-899b-9c58907825f6"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/2c346390-393d-4798-a3f3-10a4e38f0b78"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/901ff7df-247a-4918-b270-a7553860260a"  width="300" height="auto"/> </td>
  </tr>
</table>
