### ISSUE TITLE
GPS still keeps using battery if turned off after using OSMAnd

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [osmandapp/Osmand#2528] opened 2016-05-08 10:20 UTC
Steps to reproduce:
- Open OSMAnd
- Turn on GPS (set to "Device only" mode)
- use OSMAnd for a while to check current location and checks surroundings
- exit OSMAnd and turn off GPS
-> Check battery usage and see that GPS still uses battery

After rebooting GPS is finally turned off. This does not happen with other GPS using apps like "mehr-tanken".

OS: Android 6.0.1 with Cyanogenmod 13.0-20160420-NIGHTLY
Phone: Nexus 6P
OSMAnd: 2.2.4

**Comment by vshcherb** [comment] 2016-05-08 21:38
Battery usage could be misleading especially after you mentioned "turn off GPS". It is possible that application battery usage reveals more historical data over time.

**Comment by scaidermern** [comment] 2016-05-09 07:03
I had the very same problem with my previous device on Android 4.4. The only solution was a reboot to prevent huge battery drain. It also happend only with OsmAnd and no other app. On my current device on Android 5.1.1 (also CM) I haven't encountered this issue so far.

**Comment by klawdhfzasjhaa** [comment] 2016-05-09 07:34
@vshcherb : It was not only in the "Battery overview" but also in "History details". There you can see, if cellular network, camera Wi-Fi or GPS is turned on. The strange this is, that GPS is show as "on" although I turned it off via quick settings after using OSMAnd.

**Comment by jkufner** [comment] 2016-05-09 07:50
I found it is better to keep GPS permanently enabled. It does not consume battery when unused, but it remembers satelites and gets fix faster next time. Also AGPS updates (online) are working when GPS is enabled, which means up-to-date satelite data and short GPS fix times.

When you turn GPS off using quick settings, it is possible the gpsd demon is stopped, but GPS receiver is not put into sleep correctly. If this is the case, then it is a bug in phone firmware.

**Comment by sonora** [comment] 2016-05-09 20:27
@klawdhfzasjhaa  : When you say: "•exit OSMAnd and turn off GPS -> Check battery usage and see that GPS still uses battery": Can you please provide a screenshot of how you conclude "GPS still uses battery". I know from my experience with many users that they misinterpret many of Android's systems messages and systems screens.

Also: I can confirm jkufner's statement: On all my test devices I strongly encourage users to not turn off GPS ever via the system settings or quick settings. GPS is disabled and will not use any battery unless you activate an app which  explicitly uses GPS, like OsmAnd or maybe your weather widget. OsmAnd will NOT use GPS when in the background or when the device is in sleep mode, unless you have a navigation active or use GPX trip logging, (both of which enable the GPS background service to perform the task, and this will be visible in the Android system notification at the top of the screen). Should you find any issue with this, please document this via screenshots here,

**Comment by scaidermern** [comment] 2016-05-10 17:51
I reproduced this with my old smartphone (Huawei Y300 with SlimKat on Android 4.4). As mentioned before, I've *never* encountered this issue with my new smartphone (Motorola Moto G 2014 with CyanogenMod 12 on Android 5.1.1) so far.

I've used OsmAnd with enabled GPS for a very short amount of time (a few minutes). Then I've switched back to the home screen and turned GPS of. This has been about an hour ago. Nevertheless battery history details show GPS being used all the time:
![screenshot_2016-05-10-18-59-32](https://cloud.githubusercontent.com/assets/1040784/15155412/a50e8e28-16e2-11e6-8246-81102d854993.png)

As you can see, the location service is definitely turned off:
![screenshot_2016-05-10-18-59-47](https://cloud.githubusercontent.com/assets/1040784/15155410/a50e615a-16e2-11e6-8213-0b08ae04f330.png)

According to the battery view, OsmAnd causes a huge battery drain:
![screenshot_2016-05-10-18-59-55](https://cloud.githubusercontent.com/assets/1040784/15155413/a510a0f0-16e2-11e6-9bb2-5e2479a45a0a.png)

The details show, that OsmAnd is supposedly causing GPS being used all the time:
![screenshot_2016-05-10-19-00-00](https://cloud.githubusercontent.com/assets/1040784/15155411/a50e6272-16e2-11e6-9be5-7ad874ca79f6.png)

You can also see that OsmAnd is obviously not running any more (the *Force stop* button is disabled). This can be confirmed by looking at the app *OS Monitor* which also doesn't list any OsmAnd process.

The only option to stop the battery drain is a reboot. I can also reproduce this effect with other apps, for example OSMTracker. Might also just be a firmware problem.

**Comment by klawdhfzasjhaa** [comment] 2016-05-10 18:35
Thanks @scaidermern for the screenshots. That's exactly my observation, I just didn't have the time to produce them.
Thanks also to @sonora for the detailed explanations. My issue is described perfectly with scaidermern's screenshots.

[Searching](https://jira.cyanogenmod.org/browse/CYAN-1121?jql=text%20~%20%22gps%20off%22) the CM issue tracker, it seems that this issue is present quite often..Do you think a should open an issue over there?

**Comment by sonora** [comment] 2016-05-11 08:10
@scaidermern Thank you for the screenshots, they bring clarity into this, and I a very convinced it is like this:

1. The green battery discharge curve clearly indicates that significant amounts of energy were only drawn during the first few minutes of the 1hour and 6min of device operation. After that you mention you had put OsmAnd in the background, and GPS was not used any more, the discharge curve is flat. (You should be able to verify that the GPS icon in the Android system notification disappears as soon as you put OsmAnd in the background e.g. by tapping the device's home key)

2. Misinterpretation(!): The screenshot showing OsmAnd to have consumed 59% of the power means to say 59% of the total power used since the last complete battery charge, i.e. 59% of the 7% (100%-93%) used at this point, which is roughly 4% (59% is the relative figure 4% the absolute). The screenshot summarizes the history, it does NOT indicate that OsmAnd is using any power any more!  So if you drained the battery with other apps now, OsmAnd's absolute share of power used would stay at 4%, and as other apps use power too, OsmAnd relative share would now gradually drop from the current 59% down to 4%.

3. The blue "GPS" bar seems to in deed indicate that GPS has remained on for almost the entire period of over 1 hour. But I do not see a GPS icon in the Android notification bar at the time you took the screenshots, so I think this is bogus. Very likely on that particular device the blue bar indicates that GPS is in some sort of standby mode, but not active. The discharge curve indicates that no significant power is used after the first few minutes, this would look VERY different if GPS was on all the time. Also the screenshot showing OsmAnd's consumption seems to suffer from the same bug of how things are displayed: It indicates that Osmand only used 2:25 minutes of CPU time (you mention that you closed it after a few minutes, so this makes sense), and the indication that it used GPS for 1hour and 3 min is bogus, this is impossible if OsmAnd was closed. I have heard that things like this are indicated by Android's battery consumption interface on some devices, but have never seen this on the test devices I use, which are mostly Samsung and htc.

Please understand how the power consumption is always reported summarized since the last full battery charge, and observe that neither OsmAnd nor GPS will consume any power while OsmAnd is not in the foreground. So there is no issue here other than your device reporting GPS being in some sort of standby state after OsmAnd was on once. Chances are, the same is reported on your device for other apps once they have used GPS once.

**Comment by klawdhfzasjhaa** [comment] 2016-05-16 14:56
Thanks for your analysis, sonora.

In scaidermern's screenshots there is only very little amount comsumed. Probably only while GPS was turned on. I agree, that there is no battery drain in this case. However, I have attached a screenshot where you can see the consumption of massive battery amounts by GPS (at least it looks like that to me) which corresponds to the GPS ON status. Also the subjective feeling was that battery was drained much faster than usually without any interaction. So I guess that GPS is not in some kind of standby mode.
![screenshot_20160514-185636](https://cloud.githubusercontent.com/assets/2808094/15293194/233e5172-1b87-11e6-8855-8b44671bf15b.png)


Moreover, I've tested mehr-tanken and Warnwetter apps with GPS and could not reproduce the results above. The Battery was stable.

**Comment by sonora** [comment] 2016-05-17 20:25
@klawdhfzasjhaa : Yes, I agree that your case looks much less clear, and that battery consumption in the interval between your 2 red lines was significant. So if I understand you correctly, you say that this was triggered by briefly starting up OsmAnd (marked by the left red line), but then you immediately closed it again (put it in the background or even force-closed it?), but battery consumption remained high all the way to the second red line?

Please note that the analysis is complicated in the case you document here due to the following interfering facts:
- You have many intervals in this screenshot where the battery drain is even steeper than the region between the red lines
- The region between the red lines is also the region of worst GSM reception (most yellow portion of the GSM bar), this also significantly contributes to battery drain.
- In the interval you marked, where GPS is reported as "on", there are also occasional reports of "screen=on", and it is the interval with heaviest CPU activity reported on your entire screenshot. I wonder what caused this, an idea? Or did you suspect OsmAnd?

All in all, if you want to explore this further, I suggest you single out OsmAnd as much as possible, by disabling GSM and WiFi, not using your phone (screen) during the test period but leave it alone, i.e. over night. In the middle of the test period (say midnight) briefly start up OsmAnd, close it again, and then leave the phone untouched again until morning. In this fashion you have the best chance to detect a change in the battery discharge rate (kink in the curve) when looking at it the next morning and comparing the intervals before and after midnight. You may then even re-boot the device, leave it untouched again for another half day, and see if this makes any difference.

Again, the screenshot you produced where the pone seems to have moved a lot and also have been used for many other purposes created too much interference for a good analysis.

I do in deed know of apps which, once started up, prevent the device's CPU from going back to sleep mode even after the app is force-closed and until the next device restart (I have e.g. seen this for some VoIP apps on Samsung devices). But this behavior is caused by faulty wake-locks and I have never seen OsmAnd behave like this on any of my test devices (though admit my experience with the very latest Android versions is still rather limited).

**Closed** 2016-06-15 16:05 UTC

**Comment by jpwfvandongen** [comment] 2016-08-21 15:11
I van verify that the issue is nog OsmAnd relatief because I have the exact same issue with Google Maps.

**Comment by FrankEular** [comment] 2016-08-24 03:16
A detailed battery stats could be obtained from
$ adb shell dumpsys
I catched a similar bug here: https://forum.cyanogenmod.org/topic/128425-battery-drain-gps-activated-after-alarm/

@sonora I don't understand your response on the "GPS on" part: when the GPS sensor is turned of manually from settings, why is it still shown on in the batterystats? I don't know anything about Android programming, and I cannot conceive any program setting +gps while the GPS is off in the setting menu.

**Comment by raindropsfromsky** [comment] 2016-08-25 10:39
I have OnePlus 2 with SnapDragon 810, which uses Qualcomm's IZat technology. This is supposed to consume less energy even when kept always on.

I usually keep it always on, but in "Device only" mode. This gives very satisfactory results with minimal battery consumption.

Do you have any comparable factors in your phone?

**Comment by sonora** [comment] 2016-08-26 14:48
@FrankEular: Battery stats in Android show accumulated history,  not momentary usage.

**Comment by mattok** [comment] 2016-08-31 18:42
I've got a OnePlus 1 running CyanogenOS 13.1.1, with OsmAnd+ 2.4.6. OsmAnd is the only app I use GPS with. I keep my GPS off by default. If I want to use OsmAnd for navigation (rather than planning of map updates, etc.) I turn it on, and when I have finished using it, I turn it off. When I am using it for navigation, this is always in the car and I always have my phone plugged in and charging. Therefore, under normal circumstances, I wouldn't expect the use of OsmAnd to have any effect on my phone's battery life when I'm not using it. However, that didn't appear to be the case. I've been doing some testing, and over the past couple of months it has become very clear that, for whatever reason, having used OsmAnd results in subsequent rapid draining of my phone battery. Hence I searched to see if anyone else had reported the same thing and found this thread.

For me, the following is reproducible:

If I reboot my phone, and don't use OsmAnd at all (I don't even open it once), then my phone will easily last a 3-4 days given the way I use it. I've just reconfirmed this.

However, if at any time, I use OsmAnd with GPS, even for a short while, my phone battery will subsequently barely last 1 day. This will continue until I reboot. This is confirmed too.

If I fully recharge my phone, then reboot it, and then use OsmAnd with GPS for a short while, and then close OsmAnd and switch off GPS, and then check Android's battery page many hours later, Android reports that OsmAnd has been using GPS for many hours since the last charge, when it definitely hasn't.

So, there is an issue, as reported. Whether or not
- OsmAnd itself is running down the battery even when it is apparently a cached/background process (i.e. by continuously and unnecessarily checking to see if it GPS is available, or some such) or;
- there is a bug in Android, or Cyanogen OS specifically,
I couldn't say.

I see that a new system update is available for my phone. I'll have to install it and then check to see whether this continues to be reproducible. I'll let you know, but it could take several weeks to reliably test.

**Comment by sonora** [comment] 2016-09-02 00:04
3 remarks here:

- When you say you "close" OsmAnd, please be aware that this is not performed by simply tapping the device's BACK button often enough, but can only be achieved by "swiping" the app from Android's "recent apps" list (ever since Android 4.4 or so, in prior Android versions swiping would just remove it from the recent apps list but not close it), or reliably via a task manager. But in any case, even if you do not close OsmAnd, battery usage should be zero (but see next bullet)

- When you say you "briefly use OsmAnd", are you sure you do not tap track recording  or start a navigation`? This would fire up OsmAnd's background service, needed to perform recording or navigation-related tasks even when you put your phone to sleep mode. But this would always be visible by an "O" icon in the Android notification bar, please check.

- If the above does not apply:  What you describe sounds like what is often referred to as a "wakelock" issue. I have seen this with multiple apps, always only on certain devices, e.g. with some VoIP apps on some Samsung phones. It seems related to and limited to certain device firmwares, so a Cyanogen Mod upgrade sounds like something to test. I have, however, never observed this being caused by OsmAnd on any device.

**Comment by mattok** [comment] 2016-09-03 06:43
Hi Sonora. Regarding the first point, my (very basic/simplistic) understanding is that pressing back to hide the app puts it into a state where it can still run, but is cached in RAM. If another open application needs the RAM though, it'll be killed automatically be the OS. Swiping the app on the recently used apps list is a manual way to kill the app and remove it from RAM. I have observed that once the battery drain has started, it persists even after swiping the OsmAnd app to remove it from the recent list.

When I say "briefly using OsmAnd", I do mean terminating any ongoing navigation afterwards.

In the past I have had battery drain problems caused by apps unnecessarily sending large numbers of keep awake requests when not in active use, which I have been able to deal with by disabling "keep awake" that for the app. (Is that what you mean by wakelock?) I don't think this is the issue with OsmAnd, and even if so, I wouldn't want to disable it to test because it's one of the few apps that I genuinely do want to be able to keep my phone awake while I'm using it (for navigation).

Until I have further evidence to the contrary, I am willing to believe that this is a GPS related OS problem rather than an OsmAnd one. It just so happens that OsmAnd is the only app that I switch GPS on for, which makes it look like an OsmAnd problem.

I'll let you know if I have any evidence to the contrary.

**Comment by sonora** [comment] 2016-09-03 07:27
Ok, very good, thank you!

Yes, you interpret my remarks on closing the app and wakelock  exactly loke I meant them.

A rather specific OS or hardware related issue seems likely here, or else I guess  I would see it in my testing, or we would have many more issue reports.

**Comment by FrankEular** [comment] 2016-09-12 21:19
@sonora I knew that it's about accumulated history. What I wanted to mean is that, after GPS is turned off, the "GPS" keeps shown green in the battery status. For example, I turned it off 8 hours ago, but the "GPS" is shown green in the interval (now - 8h ~ now).

**Comment by mattok** [comment] 2016-09-13 20:48
For me, the problem appears to have gone away with the latest system update, lending weight to this not being an Osmand problem. At least, using OsmAnd with GPS, and killing it afterwards by swiping it from the used/recent applications list doesn't end up having any detrimental effect on battery life, and reported usage of GPS by OsmAnd in the battery section was normal. I haven't yet tried not killing it after I've finished using it, but hopefully the result will be the same.

**Comment by mattok** [comment] 2016-09-20 20:57
Unexpectedly, it happened to me again today, in a manner consistent with that described by @FrankEuler.

Previously when I was having battery drainage problems, the OSM Editing plugin was enabled. I didn't think anything of it, but shortly before posting in this issue I disabled it because it was mentioned in relation to a map related crash bug that had since been fixed. Last weekend I used OsmAnd intensively for a long trip with no battery drainage problems.

Last night I fully charged my battery. Then, this morning I launched OsmAnd to report some map errors I had encountered on my trip. I enabled the OSM Editing plugin. I also reprogrammed a route I had taken. GPS was kept off on my phone the whole time. In fact it has been switched off the whole day (without having been activated even once). I identified the problematic map locations, and reported the issues. I then cancelled the route and exited OsmAnd. The whole process took less than 1/2 an hour.

Other than that, I hardly used my phone today. (Received a couple of text messages, created a couple of calendar events, and checked a single web page over wireless, once.) However, by the end of the day, my battery had fully run down. This is not normal.

Android reports that OsmAnd has been the 2nd largest user of battery, and that it has used GPS for more than 12 hours (whereas I used OsmAnd for less than 1/2 hour). Battery details show GPS to have been active throughout the day... but my GPS was switched off. No other app is reported as having used GPS.

So, I'm back to feeling that this is an OsmAnd issue, and not an OS issue. Specifically, I wonder whether:

- it could either be related to the OSM Editing plugin, or
- it could be related to having created a navigation route with GPS off and then having cancelled it. (Note that a background navigation service is launched. Maybe this isn't cancelled properly if a GPS connection was never established? It just keeps waiting and trying?)

Please could anyone else who has experienced this battery drainage issue report back if the problem has or has not occurred in similar circumstances?

Thank you.

**Comment by vshcherb** [comment] 2016-09-26 23:16
It could be issue of both OsmAnd and OS or even Phone Vendor, which I usually suspect the most. If it is pure OS or OsmAnd issue it will be consistently reproducible on other devices, people are testing the app for thousands hours and don't see this, it could be related to some reaction or some API doesn't stop correctly GPS lookup but it is impossible to find without reproducing the issue. 

I could suspect only OsMo plugin but not OSM Editing. And of course if you see that GPS icon is present when OsmAnd is not running on your screen, please investigate it immediately. I had such issues but OsmAnd was not a case.

**Comment by mattok** [comment] 2016-10-02 21:20
I can confirm that OSM Editing is not the issue. I've since disabled it, and still see the issue.

Regarding reproducibility, there are 5 (I think) separate people who have reported experiencing this issue in the thread above. They haven't all had the same phone, but it looks like they have all been running CyanogenOS/CynanogenMod. On my phone (running an up to date CyanogenOS) it's completely reproducible. The steps are as follows:

- Start with rebooted phone. GPS Off. Wireless On.
- Launch OsmAnd.
- Set up navigation from A to B. (e.g. Select location A from favourites. Select '...'. Choose "Directions from". Select B from favourites as destination. Select Go.)
- The following messages are briefly displayed before while the route is being calculated: "Position not yet known." "The background navigation provider requires a location provider to be turned on."
- An icon appears in the task bar, saying "OsmAnd+ Running in background (navigation). GPS wake-up interval: Continuous."
- Go to home screen, and select X to cancel navigation. See "Dismiss route: Are you sure you want to stop the navigation?" Select YES. The task bar icon disappears.
- Press Android back button a few times, until OsmAnd+ disappears.
- Don't turn OsmAnd back on. You can even swipe it from the history if you like. Don't turn GPS on.
- Notice that your battery is draining 3 to 4 times faster than normal. Go to settings, battery. Note that OsmAnd+ is listed as the largest consumer of battery by percent, despite it only having been used for a couple of minutes and without GPS. Select the battery usage graph to show the detailed view of resources. Note that, despite GPS being switched off, it is listed either as being continuously on, or on most of the time after OsmAnd was used (but never before).

I accept that this is a tricky one. You're going to be unlikely to want to spend time investigating and adjusting OsmAnd to account for something that might ultimately be a bug in CyanogenMod. I'll try to report it to CyanogenMod, and see what happens. In the meantime, if anyone can reproduce this with a non-Cyanogen flavour of Android, please say.

**Comment by mattok** [comment] 2016-10-02 22:36
This has now been [reported this on the CyanogenMod JIRA issue tracker](https://jira.cyanogenmod.org/browse/BACON-5164). We'll see what happens.

**Comment by FrankEular** [comment] 2016-10-15 18:39
@mattok I suggest you to get a log for battery via:
$ adb shell dumpsys batterystats > batterystats.txt
It's pretty more detailed. (you can search for "+gps" in the log file)

**Comment by marcimat** [comment] 2017-04-25 10:24
Hi! First of all, big thanks for this great application :)
I also have this problem I think : 

- I start OSMand+ (2.6.2) (and curves lines plugin) : all is fine I think (without GPS).
- I activate GPS : OSMand is happy to have it
- I desactivate GPS 
- I close OSMand (and close it with the recent's apps button)
- In my GPS config, I don't autorize any applications to use GPS 
- And… I see sometimes the GPS icon few moments later on top of the screen and the notification that OSMand wants the GPS (my phone is in french so I don't exactly known the english sentences). I don't know why this is not always the case also.

My power battery since runs out much faster as usual, although this app is close… but… I don't see OSMand as a big consumer in the power consumption screen. It's a little crazy :)

My phone is a Redmi4, uses Android 6.0.1 and MIUI 8.2.1.
Hope this can add another lighting on this subject :)

**Comment by sonora** [comment] 2017-04-25 11:35
OsmaAnd strictly only uses GPS in these scenarios:
- While the map screen is showing
- If you have trip logging enabled, as it needs to update your position for this (there are several ways to activate trip logging, either via the widget or via he trip logging settings)
- During a Navigation

If you are not in any of these 3 cases, OsmAnd should not (and to all my experience does not) use any kind of location service.

If you want to test "exiting" OsmAnd, please note hat on some ROMS swiping an app from the recent apps list does not necessarily exit the app. To be safer, you would have to go to an "Active apps" app and manually close it, or got to Android Settings / Apps, and force close it.

But again, from all my testing I do not see OsmAnd being the culprit here, I guess it is some other app starting it.

**Comment by marcimat** [comment] 2017-04-25 12:42
- In my tests I used the "navigation" menu to add a gpx trace (previously saved with OSMand+ after creating a route into this same navigation menu). I didn't find another location to add a trace to the map so I go there to do that. Althought it seems not load the GPS without I activate it manually.

- for the exiting : I think you're totally right ! In the "installed application" list, If I click OSMand+, the "force close" button si black / clicable, meaning that the application hasn't been close by removing it in the recent app menu or by simply "leaving" Osmand . If I click it, it tells me something like "this can cause instable operation". There is no other way to correctly close an application ? (My smartphone culture isn't really good !)

**Comment by sonora** [comment] 2017-04-25 18:56
- **Displaying** a track is not an issue. only **track recording** consumes battery power, because for recording your position has to be established for every track point to be saved.

- In contrast to most other operating systems, in Android there is no real concept of "exiting any app". The philosophy is to keep as many of the frequently used apps in background memory as possible ("empty memory is wasted memory"), so they do not have to be re-loaded when to be used. Hence Android normally never really closes apps unless more memory is needed for other purposes, and may even decide to load apps into memory in the background before you even launch them.

But as I say, there should be no impact on battery consumption by this behavior. Usually keeping apps in the background requires less battery than closing them and re-starting on demand.

**Comment by faramir** [comment] 2018-03-05 08:33
I have the same issue on Moto G3 (2015?) using Android 6.0.1 - battery meter shows that OsmAnd+ is using battery for the GPS. However, I have turned off GPS (using quick setup), closed OsmAnd (swapped out from drawer and "forcibly stopped") and don't run it for whole yesterday (and previous day evening).

At Saturday evening I have swapped out OsmAnd from drawer, charge battery to 100% battery (fully charged), and left for the whole night without use. In the Sunday morning Battery showed that OsmAnd was taking energy. Then I make sure that I have forcibly stopped application and then fully charged again. Today's morning, Battery showed that OsmAnd takes energy. Today I used adb to **dumpsys batterystats**.

___

# Location services are disabled:
![screenshot_20180304-070232](https://user-images.githubusercontent.com/567976/36963698-98b4104e-2054-11e8-836c-b1fce9949534.png)

---

# Sunday

#### Sunday's morning Battery info:
![screenshot_20180304-070127](https://user-images.githubusercontent.com/567976/36963695-981110ba-2054-11e8-87d7-acf0936ca167.png)

#### Sunday's morning details of Battery usage:
![screenshot_20180304-070325](https://user-images.githubusercontent.com/567976/36963700-98cdb896-2054-11e8-850d-74c964880002.png)

#### Sunday's morning usage by OsmAnd+:
![screenshot_20180304-070137](https://user-images.githubusercontent.com/567976/36963696-98309110-2054-11e8-8839-11926d901077.png)

---

# Today

#### Today's morning Battery info:
![screenshot_20180305-083306](https://user-images.githubusercontent.com/567976/36963701-98e6edd4-2054-11e8-8dbd-109c8f1b320b.png)
![screenshot_20180305-083310](https://user-images.githubusercontent.com/567976/36963702-9900784e-2054-11e8-838d-0a11b20a5466.png)

#### Today's morning details of Battery usage:
![screenshot_20180305-083316](https://user-images.githubusercontent.com/567976/36963691-97a543a8-2054-11e8-98f4-f064aebd0244.png)

#### Today's morning usage by OsmAnd+:
![screenshot_20180305-083325](https://user-images.githubusercontent.com/567976/36963692-97bf6314-2054-11e8-9a5b-4c2fe1896f33.png)

#### and the usage by OsmAnd+ after about 30 seconds (GPS usage increased by 6 seconds):
![screenshot_20180305-083401](https://user-images.githubusercontent.com/567976/36963694-97f74aea-2054-11e8-8aef-ea94376e612f.png)

---

The batterystats.txt get by using command: `$ adb shell dumpsys batterystats > batterystats.txt`
[batterystats.txt](https://github.com/osmandapp/Osmand/files/1780006/batterystats.txt)

**Comment by faramir** [comment] 2018-03-08 13:24
After a "quick" investigation it looks like, the OSMAnd crashed some time ago on my phone and left some services(? locks) that keep trying to get GPS location even when they were turned off and OsmAnd was also turned off.
