### ISSUE TITLE
Add support for multiple values

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#3844] opened 2017-05-28 17:18 UTC
Please add support for [multiple values](https://wiki.openstreetmap.org/wiki/Multiple_values) separated by [semicolon](https://wiki.openstreetmap.org/wiki/Multiple_values), in some cases they are really useful: some doctors have multiple specialities (example from the wiki: healthcare:speciality=radiology;radiotherapy), not mentioning amenity=clinic which covers dozens of specialities. I suggest to display them in OsmAnd in one line separated with coma and space "Health specialty: radiology, radiotherapy".

**Comment by vshcherb** [comment] 2017-06-02 07:57
The issue is not specific where exactly do we need that support, so it could be a pretty big refactoring.

**Comment by mchapliuk** [comment] 2017-06-02 19:57
+1
You can use car services separated by semicolon: service=tyres; repair; parts (it's from osm wiki)

**Comment by aceman444** [comment] 2018-01-23 22:33
It seems to me the 'cuisine' tag already shows multiple values properly. May this have been fixed with some other commit?

**Comment by vshcherb** [comment] 2018-01-23 23:01
Cuisine is a "text" tag, so it only could have UI issue of displaying it but the search might not support it yet. So 2 aspects
1. Double check UI Display i.e. correct translations
2. Search POI Filter functionality

**Comment by aceman444** [comment] 2018-01-27 14:19
I mean if you have cusine=burger;pizza, it is properly displayed in the details panel as "<translation of burger>, <translation of pizza>". So there seems to be some parsing going on an properly splitting the value on the semicolon an pulling translations of the individual words, and then concatenating with comma instead of semicolon. I assume that is what the reporter wants, but also for other tags.

**Comment by vshcherb** [comment] 2018-02-03 17:31
https://github.com/osmandapp/OsmAnd-resources/commit/f2406a4b9728f33b2eb4e6b53534c7f99e3a3fa2

**Comment by vshcherb** [comment] 2018-02-07 09:13
Fixed

**Closed by vshcherb** 2018-02-07 09:13 UTC
Labels: Nice to Have
