### ISSUE TITLE
The settings export is missing a file save dialog, it only allows to share the file with/to another app

### ISSUE THREAD

**Issue by puchu** [osmandapp/OsmAnd#19748] opened 2024-05-03 01:56 UTC
### Description

The option - Menu → Settings → Import/export → Export to file - is missing a file save dialog, it only allows to share the file with/to another app

### Steps to reproduce

Menu → Settings → Import/export → Export to file

### Actual result

The settings export only allows to share the file with/to another app

### Expected result

A file save dialog allows to select a folder and filename to save the file

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.10
Android/iOS version: 12
Device model: vayu
Crash-Logs: ?
```

**Comment by pebogufi** [comment] 2024-05-03 05:12
Use a file manager for the file sharing operation. This will save the file.

**Comment by scaidermern** [comment] 2024-05-03 06:39
Duplicate of #12264 I guess.

**Comment by puchu** [comment] 2024-05-04 01:56
> Use a file manager for the file sharing operation. This will save the file.

@pebogufi  there is no file manager to choose in the sharing dialog, although i have two installed

**Comment by pebogufi** [comment] 2024-05-04 04:50
On my device i see total cmd, Quick share, and messengers, email apps and more.
Android 12, samsung S10

**Comment by vshcherb** [comment] 2024-05-06 12:04
Duplicate of https://github.com/osmandapp/OsmAnd/issues/12264

**Closed by vshcherb** 2024-05-06 12:04 UTC
