### ISSUE TITLE
Animation freezing

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16966] opened 2023-04-13 13:59 UTC
### Description
When zooming quickly (with two fingers or buttons), the animation freezes at the previous zoom level and then draws out
[logcat (90).log](https://github.com/osmandapp/OsmAnd/files/11222827/logcat.90.log)
[Export_13-04-23.osf.zip](https://github.com/osmandapp/OsmAnd/files/11222830/Export_13-04-23.osf.zip) + 4gb maps

### Steps to reproduce

- Quickly zoom in on the map

### Actual result

<details><summary>4.5.0</summary>
<video src="https://user-images.githubusercontent.com/104760013/231781493-ba809370-06fa-4677-87c8-95f772cf8e9e.mp4"></video>
</details> 

### Expected result

<details><summary>4.4.7</summary>
<video src="https://user-images.githubusercontent.com/104760013/231781588-a2a7ff46-20a2-42cc-a2a0-4c53329aa39d.mp4"></video>
</details> 

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35770m, Released: 2023-04-13
Android/iOS version: Android 12
Device model: Poco x3

**Comment by vshcherb** [comment] 2023-04-15 12:38
Probably won't be fixed - as it's not an artefact from other improved behavior. Let's see if there are worse examples

**Comment by sonora** [comment] 2023-04-15 22:46
So which 'improvement' is causing this, maybe we can optimize the code?

**Comment by vshcherb** [comment] 2023-04-18 18:13
I can't reproduce. I suspect it after improvement that labels now don't disappear immediately. So while you keep slowly zooming in / out, labels will appear instantly without clearing screen as in 4.4 and then reappearing again.

**Comment by Zirochkabila** [comment] 2023-04-21 13:09
OsmAnd~ 4.5.0#35825m, Released: 2023-04-21
Still present


https://user-images.githubusercontent.com/104760013/233644113-51beb1c3-627d-4125-be18-ac1c866d71c0.mp4

**Comment by vshcherb** [comment] 2023-04-21 14:42
Not planned

**Closed by vshcherb** 2023-04-21 14:42 UTC
