### ISSUE TITLE
Offline Routing: destination anouncement 

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#2056] opened 2015-12-13 21:35 UTC
When there is a destination tag on a turn or on a roundabout without a streetname tag, Osmand says: "Turn left to (destination)". It is ok

When there is a destination tag on a turn or on a roundabout with a streetname tag, Osmand says: "Turn left on (streetname) (destination)".  I think osmand must say: "Turn left on (streetname) to (destination)"

What do you think?

**Comment by pl71** [comment] 2015-12-14 06:27
Slightly off topic: My voice is set to English, but local street names are not in English. Most of the time I hear: "Turn left on to" or "Turn right on to" which is strange. Probably English voice TTS can not pronounce street names in the local language. In that case voice prompt should be shortened to "Turn left" only.

**Comment by hakuchi** [comment] 2015-12-14 19:26
Osmand should be able to change separately if the TTS voice reads street names, ref or destination or all.

**Comment by OpenSourceForEver** [comment] 2016-01-09 00:24
What do you mean?

Osmand says: "Turn left on (streetname) (destination)". I think "to" is needed between (streetname) and (destination).

**Comment by sonora** [comment] 2016-01-13 00:34
Original issue fixed in nighlies. Please test, but I think the suggestion was justified.

As far as Pl71's the "off topic" post is concerned: I think that one is a duplicate of #1617.

**Closed by sonora** 2016-01-13 00:34 UTC
