### ISSUE TITLE
Transliteration bug

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7928] opened 2019-11-14 07:41 UTC
In the Germany maps, if the Transliteration is turned on, the city names with umlauts (ä ö ü) are missing. 

52.1617685,14.5653451

![image](https://user-images.githubusercontent.com/50198677/68836357-da0e1700-06c2-11ea-9bfd-100974327ee9.png)

**Comment by Discostu36** [comment] 2020-01-13 13:25
Duplicate of #5954

**Closed** 2020-01-15 14:44 UTC
Labels: Observed
