### ISSUE TITLE
Route planning should not require location services

### ISSUE THREAD

**Issue by smurfix** [osmandapp/Osmand#6579] opened 2019-02-24 20:00 UTC
Planning a route requires me to allow OsmAnd to access location services. That should not be necessary.

**Comment by scaidermern** [comment] 2019-02-25 07:29
Possible duplicate of #4845.

**Comment by vshcherb** [comment] 2019-02-27 16:14
Yes duplicate https://github.com/osmandapp/Osmand/issues/6579

**Closed by vshcherb** 2019-02-27 16:14 UTC
