### ISSUE TITLE
Change color of the button cancel

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1886] opened 2015-11-08 18:25 UTC
It happens that in the settings options, the "cancel" button appears in black. I would like to have the same color as the button "accept". Thanks!
Incorrect.
![screenshot_2015-11-08-14-51-03 01](https://cloud.githubusercontent.com/assets/12088580/11021814/77efe8d4-862c-11e5-811c-ad7d527a358e.png)
Correct.
![screenshot_2015-11-08-14-55-15 01](https://cloud.githubusercontent.com/assets/12088580/11021815/7a2bfe9e-862c-11e5-862e-7f0864873977.png)

**Comment by GaidamakUA** [comment] 2015-11-09 17:17
Excuse me, but can you give us more details like what build are you using, and your android version.

**Comment by franco999** [comment] 2015-11-10 17:10
@GaidamakUA  I'm using Android 5.0.2 (Moto E2 xt1527) and OsmAnd 2.3.0#14163M (2015-11-09). I do not know if it's Lollipop problem or application, because it appears in some popups well and sometimes not.

![5](https://cloud.githubusercontent.com/assets/12088580/11069219/dbf0cdc0-87b3-11e5-80ea-99352801ef37.png)
![3](https://cloud.githubusercontent.com/assets/12088580/11069220/dbf79ee8-87b3-11e5-9929-71e92aa05332.png)
![2](https://cloud.githubusercontent.com/assets/12088580/11069221/dc02bf4e-87b3-11e5-90ef-d2b88b60964b.png)
![4](https://cloud.githubusercontent.com/assets/12088580/11069222/dc63da2c-87b3-11e5-8ad3-6a9a1fedd3fc.png)
![1](https://cloud.githubusercontent.com/assets/12088580/11069223/dca55f92-87b3-11e5-8298-f33df38e61c1.png)

**Comment by GaidamakUA** [comment] 2015-11-11 10:44
We can't reproduce this bug. But we have replaced out dialogs with new version. Dialogs in settings are not affected, because there are no easy way to fix that. Dialogs that are not related to settings should be fixed.

**Comment by vshcherb** [comment] 2015-11-11 16:04
Everywhere except settings is  fixed. Please check it. The settings is difficult one and we can't reproduce it on our devices.

**Closed by vshcherb** 2015-11-11 16:04 UTC
