### ISSUE TITLE
wrong information about stop-sign

### ISSUE THREAD

**Issue by osmvermesser** [osmandapp/Osmand#4018] opened 2017-07-03 08:24 UTC
in current version of osmand the programm told you about a stop-sign when you come from a crossing into a stop street.

in wiki following definition can be found:

_Insert a highway=stop node on the approach way(s) that must stop, at the stopping point. Drivers may be required to give way (yield) whether or not a physical sign is present; but if you also want to capture the signs, you can use a traffic_sign=* tag as well. In all-way stop countries you could also add stop=minor to distinguish 2-way from 4-way stop signs. 

As this minor road highway=stop node is NOT at the intersection point, we know it just shows the stop line. The roadway approaches that do not stop will have no highway=stop nodes before the conflict point. Do NOT tag the conflict points -- the priority junction node(s)) -- with highway=stop, because not all the approaches will stop. 

Since the stop line on the approach applies to only one travel direction, that direction can usually be deduced by finding the shorter distance to the priority intersection. However, a few stop signs are on 2-way streets between closely-spaced junctions, making it necessary to identify the travel direction that stops. Where needed, this can be done using direction=forward or direction=backward, relating stop direction to OSM forward/backward of the way that contains the highway=stop node._ 

the addition tags diretction=forward or diretction=backward will not be used.

Jan

**Comment by sonora** [comment] 2017-07-03 11:02
I think this is a duplicate of what I have already documented as our TODO in #2885 ?

**Comment by osmvermesser** [comment] 2017-07-03 11:44
hi!
my english is not very well but it looks like the same.

in hope of fixing.

Jan

**Closed** 2017-09-20 19:25 UTC
