### ISSUE TITLE
Begining of gradient graph is obscured by labels

### ISSUE THREAD

**Issue by aSemy** [osmandapp/OsmAnd#18402] opened 2023-10-21 18:21 UTC
### Description

When I look at a gradient graph the left hand side is obscured by 3 labels. This makes it difficult to see what the full gradient profile is.

(To be honest, I'm not even sure what the labels are showing. I don't use them when I look at the graph, I'm not sure what the numbers mean.)

### Steps to reproduce

https://osmand.net/map?start=42.970379%2C142.752747&end=42.965530%2C142.666367&mode=bicycle#9/41.982523/142.710502

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/897017/e7b72db4-8f36-409f-a918-563eb26ae786"  width="300" height="auto"/> </td>
  </tr>
</table>

### Actual result

The graph is obscured by labels. 

### Expected result

The graph is not obscured by labels.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd+ 4.5.10, released: 2023-08-09

OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by mikehgentry** [comment] 2023-10-22 01:51
Duplicate of #18204

**Comment by DmitryAlexei** [comment] 2023-10-22 17:08
Not a full duplicate of #18204, but very similar issue.
That one is about elevation profile in Route details section (for more information see https://osmand.net/docs/user/navigation/setup/route-details), #18204 is about Elevation widget

**Comment by vshcherb** [comment] 2023-10-25 15:42
Merge to https://github.com/osmandapp/OsmAnd/issues/18204 cause we made a decision to redesign to solve that problem That issue has a long story moving from left to right and there is no obvious solution except make for labels separate space. Workaround is to scale up.

**Closed by vshcherb** 2023-10-25 15:42 UTC

**Comment by aSemy** [comment] 2023-10-25 18:16
@vshcherb to me it looks like #18204 describes a different problem. The mockups still show that the graph is partially obscured by labels that say '207 m' and '213 m'. Also, the issue doesn't mention the slope information, which is also rendered in the labels.

**Comment by mikehgentry** [comment] 2023-10-25 21:31
It's become a bit fragmented, but #16145 (which was folded in to #18204 ) describes a reasonable way to deal with the x origin problem.

I agree with you that it isn't at all clear what the slope bit means though.

**Comment by sonora** [comment] 2023-10-25 22:26
I had somwhere suggested to simply toggle (show/hide) these labels by tapping in the left hand side of the graph area (much like we toggle the movable position marker by tapping elsewhete in the graph).
