### ISSUE TITLE
.gpx Navigation - handling of missed waypoints

### ISSUE THREAD

**Issue by boldtrn** [osmandapp/Osmand#2994] opened 2016-08-23 13:15 UTC
When importing a .gpx file into Osmand I can navigate along the track/route.

However, if for some reason I did not reach a certain point of the track/route. Might be due to an issue of my gps, because of a construction site, or maybe I took the wrong turn. Now I check the route on the display and decide to join the route in a subsequent segment again. Osmand tries to route me through that point for several km. It would be nice if it would be possible to setup Osmand, that this time could be reduced. 

I like to plan my routes using an online route planner and import it into Osmand afterwards. However, it seems that from time to time my gps is inaccurate and therefore Osmand tries to force me to turn, which is really annoying. 

Let me know what you think.

**Comment by vshcherb** [comment] 2016-08-24 21:02
It is hard to say what is the preferred algorithm cause different users might expect different results. For some people returning to the same point could be preferrable, OsmAnd doesn't calculate many to many to find shortest path to the destination point, it tries to build a route to the closest point.

**Comment by boldtrn** [comment] 2016-08-25 05:49
> It is hard to say what is the preferred algorithm cause different users might expect different results

There is the `Pass along entire track` option. So I think, if one would want to follow exactly the track or wants to visit all waypoints along the route, than this option might be the best for him/her. Not setting this Option, I would assume that skipping parts of the route should be the desired option.

But still I would be fine with hiding this option somewhere in the settings for now.

Let me know what you think.

**Comment by vshcherb** [comment] 2016-08-28 21:37
```Pass along entire track``` is quite needed for cycle tracks. Though indeed it requires closer look from us.

**Comment by boldtrn** [comment] 2016-08-29 07:52
> Pass along entire track is quite needed for cycle tracks

I understand. Maybe a second option like `Allow passing by waypoints` could be build. This would allow Osmand to mark a waypoint as visited when coming closer than 1km to it or if the route is followed in a future segment.

**Comment by ymbus** [comment] 2018-02-01 08:54
Hello,
I'm sorry to post to this issue again, but i see in communities that the routing and waypoint behaviour is still a big deal for a lot of people.
I also noticed when not using "pass along entire track" that it takes a lot of time until osmand recognizes a missed waypoint. In a city this is very annoying.
When using the option "pass along entire track" which is needed for cycle tracks you have no chance to let a waypoint go. If I am driving on a road, where i just can't turn around and drive to the last waypoint, the navigation is useless from this point on.
So both options cause big problems.

Maybe it would be an option, that a user can skip a waypoint anytime he wants (even in both ways? skip one or go back to the last). 
How about a button "skip next waypoint". So the user can decide if he wants to let it go and travel to the next waypoint.
Binding this function to a hardware button like the volume buttons would be necessary for bikers (gloves).

**Comment by Zabuel** [comment] 2019-09-01 18:41
Ok with that ! (+1)
A "skip current checkpoint" button" would be a very useful option and often used. 

Very annoying when you have to go back to a missed check point. 

Please Do it ! ...otherwise gpx navigation only works halfway.

**Comment by YoBii** [comment] 2020-07-25 10:59
I think this is still relevant. 
I planned a route using existing tracks on komoot and exported that as .gpx file.
When imported into OsmAnd it kept rerouting me to the first point of the track (which is my home address) although I started navigation right there. 
Also if for whatever reason you have to detour from the gpx route and want to join on a later segment again, it will keep redirecting you to the missed point. In that case you have to stop your tour and rebuilt the route on the phone. Depending on the length of the route and number of waypoints this can be really annoying. Especially since you already planned out the entire route initially.

**Comment by vshcherb** [comment] 2020-07-27 12:48
Yes this issue was discovered in release 3.7 and already fixed in 3.8 nightly builds. Hopefully will be released to beta and public soon.

**Closed by vshcherb** 2020-07-27 12:48 UTC
Labels: Observed

**Comment by fvdnabee** [comment] 2021-02-23 10:17
Apologies to comment on a closed issue, but has this been fixed in 3.8? I noticed osmand 3.9.6 recalculating and sending me back to a missed waypoint (using Navigation with Follow track) more than once. In my impression it only skipped waypoints, once I continued my way back on the original track. Before I rejoin the track a bit further down the route of the missed waypoint, osmand kept re-routing me to the missed waypoint (instead of a waypoint further down the track). This isn't very useful when the track enters a closed street, and you'd like osmand to send you around the closed road instead of recalculating to the beginning of the closed road. I'm guessing this is intended behavior: e.g. only skip waypoints when the rider has rejoined the track?

I'm unsure whether a good solution exists in this case. Rerouting to the closest waypoint along the track after the missed waypoint might solve it, but it might break many other cases. Also if the next waypoint is 50 meters further down a closed street, it won't help either. Maybe the cost of navigating to a missed waypoint can be increased the further you are away from it, as this would make the remainder of the track a more desirable solution for the rerouting algorithm. Also, the current behavior of the app is not entirely clear to me. My impression is that if osmand would ignore a missed waypoint sooner, it would already help a lot. Is there any other input I can give to clarify the issue?
