### ISSUE TITLE
Router adds a short direct lines at the begining and the end of route after add an intermediate point

### ISSUE THREAD

**Issue by hamer13** [osmandapp/OsmAnd#19376] opened 2024-03-23 12:28 UTC
### Description

https://t.me/ruosmand/148280
profile: 
[Export_2024-03-23_car.osf.zip](https://github.com/osmandapp/OsmAnd/files/14731498/Export_2024-03-23_car.osf.zip)
just remove the ".zip" extension.

### Steps to reproduce

1. (optional) select a start point
2. select a final point
3. select an intermediate point

### Actual result

route from start to end via intermediate point with short direct lines at start and at end
screenshots:
incorrect route via bad road: 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/5617109/357ae801-81a0-44c7-8667-700578b64e38"  width="300" height="auto"/> </th>
  </tr>
</table>
added intermediate point: 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/5617109/7f4bf1ac-d6fd-44a9-aed0-218cee235d41"  width="300" height="auto"/> </th>
  </tr>
</table>
short line at the end: 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/5617109/8f7404fd-9fd4-465e-9f5f-ecca2b37926b"  width="300" height="auto"/> </th>
  </tr>
</table>
short line at the start: 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/5617109/f41ccdf6-7163-43c9-80d5-a85fbe7049f0"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

route from start to end via intermediate point
the correct route from 4.5.10:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/5617109/6e24400c-b9c7-421e-b8c4-4f3fe9160505"  width="300" height="auto"/> </th>
  </tr>
</table>

### Your Environment (required)

```
OsmAnd Version: 4.6.14 from f-droid
Android/iOS version: android 14
Device model:  Samsung Galaxy Z Fold 5
Crash-Logs: no
```

**Comment by hamer13** [comment] 2024-03-23 13:16
Installed "osmand free" from gplay, without any configuration except map style changed to"offroad" and maps location to "multiuser", no any import at all.
these maps:
```
q5q:/storage/emulated/0/Android/obb $ ls -l net.osmand/*.obf                                                                               
-rwxrwx--- 1 shell   ext_obb_rw 826395290 2024-03-23 16:05 net.osmand/Belarus_europe.obf
-rwxrwx--- 1 shell   ext_obb_rw 419487035 2024-03-23 16:05 net.osmand/World_basemap.obf
-rw-rw---- 1 u0_a313 ext_obb_rw  51127245 2024-03-23 16:04 net.osmand/World_basemap_mini.obf
```
OsmAnd 4.6.13,  2024-01-19
result: 
![Screenshot_20240323_160738_OsmAnd_4 6 13_clean](https://github.com/osmandapp/OsmAnd/assets/5617109/fe5413f7-eb71-4809-9856-63ffb2015ff6)
the short lines exist.

**Comment by hamer13** [comment] 2024-03-23 14:45
Also reproduced on old phone with android 8.
```
OsmAnd Version: 4.6.13 from google play
Android/iOS version: android 8
Device model:  Sony XZ1 compact
```

Steps:
1. install osmand free
2. first start, cancel maps downloading
3. chose "multiuser" storage
4. chose "offroad" style
5. copy maps from "plus" version
6. chose start point
7. chose end point
8. choise intermediate point

maps:
```
q5q:/storage/emulated/0/Android/obb/net.osmand $ ls -l *.obf
-rwxrwx--- 1 shell   ext_obb_rw 826395290 2024-03-23 16:05 Belarus_europe.obf
-rwxrwx--- 1 shell   ext_obb_rw 419487035 2024-03-23 16:05 World_basemap.obf
-rw-rw---- 1 u0_a313 ext_obb_rw  51127245 2024-03-23 16:04 World_basemap_mini.obf

q5q:/storage/emulated/0/Android/obb/net.osmand $ md5sum *.obf
1c0b2b4d9de8c296d2331b77b5bd4c51  Belarus_europe.obf
b04fe5e452815c17f1336fc70b237242  World_basemap.obf
c8a26a740dcd281a57b9383e1910fda3  World_basemap_mini.obf
```

**Comment by yuriiurshuliak** [comment] 2024-03-26 16:53
The bug was not reproduced. I selected the Multiuser storage 1 folder, then reset the car profile settings and set the map style to offroad. Subsequently, I examined the route without an intermediate point and then observed the constructed navigation with an intermediate point. No short straight lines were detected at the end or beginning of the route.

Here's the web version for comparison:
[Link to Web Version](https://test.osmand.net/map/?start=54.193240,27.119708&finish=54.187548,27.107735&via=54.189921,27.104014&profile=car#16/54.1916/27.1059)

OsmAnd~ 4.7.0#1924m, released: 2024-03-26

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f35eddff-5970-4e99-97b8-29f090d16b08"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/d5c5ba88-adaf-4db1-b060-06e9c227e42a"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by hamer13** [comment] 2024-03-26 20:20
Seems bug does not exist in nightly build but in release ones… Can this bug be fixed in current release?

**Comment by yuriiurshuliak** [comment] 2024-03-27 10:59
If the issue has already been addressed in the nightly version, it will be resolved in the release version as well. This is because the nightly version typically features quicker implementations of fixes.

**Comment by hamer13** [comment] 2024-03-27 14:34
I talk about current release 4.6 in f-droid and google market.

**Closed** 2024-05-15 14:49 UTC
