### ISSUE TITLE
Fixed map rotation

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/OsmAnd#17561] opened 2023-07-05 14:50 UTC
We have now 4 choices in Settings/Map rotation. The first ist "North is on top" and the 4. is "manual rotated", both announced with the word "fixed". But: when i use 2 fingers on the screen the map can rotate without me wanting it to. It would be nice, if the first item " north on top" would really fix the map: no rotation at all.

Spielmops

**Comment by vshcherb** [comment] 2023-07-05 15:12
This either duplicate of https://github.com/osmandapp/OsmAnd/issues/15660 or here is a fix for string https://github.com/osmandapp/OsmAnd/commit/3b6c995f1f8f384e98498b15f78a34b4f1cac9ad.

Probably related https://github.com/osmandapp/OsmAnd/issues/16989

**Comment by vshcherb** [comment] 2023-07-05 15:14
I think there was also an issue about a lock map orientation but I couldn't find it now

**Comment by sonora** [comment] 2023-07-06 07:05
#16751
#16836
#16785
#17086
#16893
#16989
https://github.com/osmandapp/Osmand/pull/17197
#15660
#17561
#16773
#16805

**Comment by mnalis** [comment] 2023-07-06 11:06
@Spielmops just to be clear, which OsmAnd version are you talking about exactly?

**Comment by Spielmops** [comment] 2023-07-06 11:17
Version 4.4.7, the previous version (4.3.8) had only 3 items to chose from. Now we have 4 and thus one could be fix.

Spielmops

**Comment by sonora** [comment] 2023-07-06 20:52
Essentially, in my perception, the sensitivity to cause accidental rotation has been (noticeably, I admit) decreased. Still occurs at times though, which is an issue if it goes unnotoiced on field trips   and for many  inexperienced users I saw if they are not aware how to reset.

**Comment by mnalis** [comment] 2023-07-07 02:39
>> I will not use beta-versions, I need a reliable navigation app

Nightly versions of OsmAnd can be installed alongside you main (non-beta) OsmAnd version, **just to test** how well it works for you, so you can provide your feedback if you find the fix acceptable or not. You don't have to use the betas/nightlies for your real navigations (you can even uninstall it after testing if you wish).

Of course, you can opt to wait for release instead, but if the result when that happens is not what you want, there will be another prolonged waiting period before there is a chance for another change - that's why I suggest trying it out and giving your feedback now.

>> It would be nice, if you write here, what the significant change regarding this issue is.

> Essentially, in my perception, the sensitivity to cause accidental rotation has been (noticeably, I admit) decreased

Also, as I understand it (but I might have gotten it wrong; see [all the tickets listed by sonora](https://github.com/osmandapp/OsmAnd/issues/17561#issuecomment-1623105410)!), if one starts zooming gesture, it cannot now be  accidentally changed to rotating action (which was one on main culprits in 4.4.x)

**Comment by sonora** [comment] 2023-07-07 08:28
> but what speaks against disabling the rotation with "North is on top"?

My thinking exactly. With perhaps an unmistakeably big initial rotation  threshold of like 30 or 45 degrees so that someone could **willingly** change from North up to Manual rotation without having to fiddle with the settings.

**Comment by mnalis** [comment] 2023-07-07 21:03
>  but what speaks against disabling the rotation with "North is on top"?

@Spielmops Even though I've read through most of those issues linked above, I'm not sure, but I can see few usability issues myself for that feature, depending on how it might be implemented (e.g. https://github.com/osmandapp/OsmAnd/discussions/16836#discussioncomment-6011264 and https://github.com/osmandapp/OsmAnd/pull/17197#issuecomment-1563312464). 

As far as I can tell, that is still one of the possible options on the table. When or if it will happen, and in what format, I cannot tell.

But it likely needs people trying out behaviour in 4.5.x, and reporting how well that works for them, and examples what doesn't work (Best screencast video, but just an explanation in words is much better then nothing). After all (judging by the issues opened), nobody ever complained about behaviour in for 4.3.x and previous versions, so that one was probably good enough. So people who are interested in this issue, should invest some time to try out new version and see how it works for them, and give feedback. 

So, I'd recommend to try a [latest nightly](https://www.osmand.net/docs/versions/nightly_versions), and if it still wrongly rotates when you don't want it,  you should give example of it / describe it. Otherwise, if the new behaviour is deemed good enough, it seems quite possible that there won't be further changes. And reporting behaviours of old (stable) versions which have already changed is not helpful; OsmAnd already had all those issues reported [before](https://github.com/osmandapp/OsmAnd/issues/17561#issuecomment-1623105410), and its behaviour changed several times already AFAICT.

> My thinking exactly. With perhaps an unmistakeably big initial rotation threshold of like 30 or 45 degrees so that someone could willingly change from North up to Manual rotation without having to fiddle with the settings.

Which is how it worked in 4.3.x and below, and what your PR #17197 tried to reestablish, right @sonora? It worked for me just fine, but there seems to be heavy [reluctance](https://github.com/osmandapp/OsmAnd/pull/17197#issuecomment-1567280186) to include it in that form. I've only have guesses I've outlined above in what manner 4.5.x tried to change the behaviour, if you know exact technical ways that current nightlies differ from 4.4.x, that information would be much appreciated.

**Comment by Spielmops** [comment] 2023-07-08 11:21
> After all (judging by the issues opened), nobody ever complained about behaviour in for 4.3.x and previous versions, so that one was probably good enough. 

I had problems with that old version, otherwise I would not have written this issue. But in the old version there were only 3 item to chose regarding rotation. So I tried version 4.4.7 and found 4 items. That is the reason I got the idea, that the first one could now be "fixed to north". 

Sorry that I did not try out every beta or nightly-version ...

**Comment by Dollarius** [comment] 2023-07-09 05:45
This has been reported tons of times: cannot we just add an option to FIX the North?

Even in the latest nightly (2023-07-08 OpenGL), I eventually end up rotating the North by mistake.
Many times, especially when the phone is in my pockets and I cannot notice the mistake.
I NEVER would want the North to rotate 😅

Thank you if you could consider this :)

**Comment by Nine-Tailed** [comment] 2023-07-09 20:48
> But it likely needs people trying out behaviour in 4.5.x, and reporting how well that works

Starting from version 4.4, gesture control is only annoying.  I wrote about it several times, but nothing fundamentally changed.  It became difficult to tilt the map at all, so also changed the direction of the gesture for tilting the map to the opposite.

**Comment by forfucsake** [comment] 2023-07-13 21:29
I found this by google.
Surprised to read the discussion about what I was sure is a bug.
The setting (in German) reads "north is up (fixed)" yet everytime I try to zoom the map is turned. 🙄

**Comment by Spielmops** [comment] 2023-07-17 07:36
I installed the nightly version 4.5.0 and tried the behaviour with "north on top": no real difference, the map rotates, if I zoom with 2fingers ...

**Comment by mkoncek** [comment] 2023-07-21 10:51
I am adding in a request for the user to be able to **disable** any rotation of the map.

**Comment by MikeHarding8** [comment] 2023-07-24 22:16
I noticed the word "Fixed" has been removed from the nightly build!?

A locked "North up" is virtually essential, I don't understand why there is even a debate about it.

**Comment by scaidermern** [comment] 2023-07-25 06:38
> I don't understand why there is even a debate about it.

Because obviously 11 tickets (#16751 #16836 #16785 #17086 #16893 #16989 #17197 #15660 #17561 #16773 #16805) aren't enough, that's why we need this 12th ticket to discuss the problem.

**Comment by GallusMax** [comment] 2023-08-09 06:24
> Also, as I understand it (but I might have gotten it wrong; see [all the tickets listed by sonora](https://github.com/osmandapp/OsmAnd/issues/17561#issuecomment-1623105410)!), if one starts zooming gesture, it cannot now be accidentally changed to rotating action (which was one on main culprits in 4.4.x)

Sorry, but: no! What if Osmand being used for navigation on a moving bike? You cannot be sure that first touch with two fingers will be "zoom" and not "rotate". 

Ceterum censeo: PLEASE bring back a map with reliable orientation! Best by dis-/enabling mode toggle in the settings (per profile), or by re-implementing a huge threshold against accidental rotating.

**Comment by vshcherb** [comment] 2023-08-10 12:20
It looks like the decision is moving towards a setting to disable rotation for certain profile, and as PR created for an earlier ticket this one is also merged to https://github.com/osmandapp/OsmAnd/issues/17086.

**Closed by vshcherb** 2023-08-10 12:20 UTC

**Comment by elf128** [comment] 2023-08-19 00:32
The issue still happening in 4.5.8 
It's not as bad as 4.4.x, but still happening.

**Comment by scaidermern** [comment] 2023-08-19 05:48
See #17086.
