### ISSUE TITLE
Search giving wrong town name

### ISSUE THREAD

**Issue by spaanse** [osmandapp/OsmAnd#17395] opened 2023-06-10 10:42 UTC
### Description
When you search for a place in the east of Leek (for example "De Dam 44", https://www.openstreetmap.org/node/1315477709) it says in the search results:
```
44
De Dam, Nietap
```
However, when you select that spot manually on the map it gives the description:
```
Nienoordkapel
Place of worship, De Dam 44, Leek
```
It seems that search uses the closest town centre instead of the place associated with the address.

### Steps to reproduce
1. Go to Leek, Groningen, The Netherlands
2. Search for "De Dam 44"
3. Observe the wrong town name (Nietap)
4. Deselect the place and select the cross (church symbol) on the map
5. Observe that in the place description it mentions the correct town name (Leek) 

### Actual result

```
44
De Dam, Nietap
```

### Expected result

```
44
De Dam, Leek
```

### Your Environment
OsmAnd Version: 4.5.1 / 4.4.7
Android/iOS version: Android 12 / ?
Device model:  EB2103

**Comment by Zirochkabila** [comment] 2023-06-13 15:09
[Map here](https://drive.google.com/file/d/19eIAHS8prnaWVRM8pyJ-fN13CEUlYfek/view?usp=sharing)

**Comment by zipav** [comment] 2023-06-13 18:10
### Steps to reproduce: 

- Open Netherlands Drenthe map\open coordinates
-  Search for "De Dam 44"
-  Deselect and select the cross POI on the map

Coordinates: 53.1618407, 6.3917903

OsmAnd Nightly 4.5.0#196m, released: 2023-06-13

![image](https://github.com/osmandapp/OsmAnd/assets/123936521/2988eccd-b543-4582-8278-dc683eb131ea)
![image](https://github.com/osmandapp/OsmAnd/assets/123936521/36f5e730-b919-4fb5-bef6-f85480534d24)

**Comment by spaanse** [comment] 2023-06-14 08:49
Some more points:
Red = Nietap
Green = Leek
Yellow line is approximate boundary between them
Black line connects the town markers

![Screenshot_2023-06-14-10-45-45-37_54166e5c6f8ad9491c65e2397c495c92](https://github.com/osmandapp/OsmAnd/assets/19549928/53a958e0-74d7-48d9-aa07-23852d3e9083)

**Comment by vshcherb** [comment] 2023-07-13 14:27
Leek - has the boundary https://www.openstreetmap.org/relation/1731316#map=16/53.1605/6.3915
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=1315477709&class=amenity
Nominatim works correctly

https://osmand.net/map#18/53.16150/6.39152 -where ami

Looks like the problem is the border so it needs to be precise here @xmd5a2

**Comment by xmd5a2** [comment] 2023-07-28 08:01
Will be fixed in august maps.
Test maps were generated locally. Here is output of "Where am I?" command in OsmAndMapCreator. Notice that De Dam street is in Leek city.
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/7ccdc71d-de43-4437-91fc-0e4e167ce3da)

**Closed by xmd5a2** 2023-07-28 08:01 UTC
Labels: search

**Comment by vshcherb** [comment] 2023-08-07 13:14
Tested on new maps - OK
