### ISSUE TITLE
Track stays visible after deleting it

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9778] opened 2020-09-10 06:04 UTC
Deleting a currently visible track makes the track stay visible on the map. The visibility can't be changed afterwards since the track isn't listed any more. Only restarting OsmAnd helps.

OsmAnd nightly.

**Comment by pebogufi** [comment] 2020-09-10 16:05
Open Configure Map / Tracks.
The deleted track is still visible here, you can uncheck to hide.
So the problem is, i suppose there are different internal lists of visible tracks, which should be merged.

**Comment by scaidermern** [comment] 2020-09-10 18:20
> Open Configure Map / Tracks.
> The deleted track is still visible here, you can uncheck to hide.

Yes, this works. However the track is no longer shown at My Places / Tracks / Visible.

Yes, synchronizing these views seems to be necessary. Alternatively deleted tracks should really be removed, i.e. not be rendered anymore.

**Comment by scaidermern** [comment] 2020-12-15 07:56
Problem still exists with OsmAnd 3.9.1. However now the workaround doesn't work any more, the track doesn't get listed under Configure Map / Tracks but still stays visible on the map. The only solution is to restart OsmAnd.

**Comment by androiddevkotlin** [comment] 2021-04-20 07:31
It seems already fixed on newer version.

**Closed** 2021-04-21 08:58 UTC

**Comment by scaidermern** [comment] 2021-04-21 09:05
> It seems already fixed on newer version.

Which version? I can still reproduce it with OsmAnd 3.9.10.
