### ISSUE TITLE
Wrong route recalculation 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5960] opened 2018-08-31 11:36 UTC
When you have a route with waypoints, and you deviate from it, it will try to recalculate, but waypoints already visited seem to become "un-visited" and a proper recalculation never happens.

**Comment by Olaf987** [comment] 2018-09-03 11:36
Dear all:

This bug was made after I experienced this and asked Osmand support what to do. I have been able to check the behaviour more rigorously now.

It seems this does not happen on short trips. I tried this yesterday and everything was fine. When this happened to me, the trip was very long (> 400km) with waypoints at the very beginning. When traffic forced me to deviate, the route recalculation could not happen on the fly when the car was moving rapidly so a proper start point could not be determined. The route was still not calculated after 15 minutes. I had to stop at a highway rest stop and delete the waypoints. This of course forces the entire route to be recalculated from scratch using a proper start point (I did mention I had to stop). The route could now be recalculated in a few minutes. The reason the very long routes work is very simple: when you go from one highway hotel to another, there is not much route to calculate.

Based on this, I would say the waypoints are not the problem. The length of the route combined with the moving car was. I therefore recommend to close this bug for now.

**Closed** 2018-09-09 15:00 UTC
Labels: Observed

**Comment by vshcherb** [comment] 2018-09-09 15:01
During navigation if the waypoint is past the waypoints should be deleted. Also we have "fast" calculation where only 1 segment (to the next waypoint should be recalculated). Let's see if we can get more feedback cause it is usually hard to reproduce those issues.

**Comment by Olaf987** [comment] 2018-09-09 20:42
What I remember is that when I opened the route after about 15 minutes of calculating with no results, all waypoints where still there. Should this be the case?
