### ISSUE TITLE
App crashes in new tracks menu

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16624] opened 2023-03-08 08:16 UTC
### Description
After entering the new tracks menu, the osmand shows the progress bar for a very long time and then crashes.

### Actual result
```
Version  OsmAnd~ 4.4.0#14224mqta
08.03.2023 11:06:55
Apk Version : 4.4.0#14224mqta 4400
Exception occured in thread Thread[AsyncTask #1,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 112 byte allocation with 3188176 free bytes and 3113KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.util.Calendar.createCalendar(Calendar.java:1684)
	at java.util.Calendar.getInstance(Calendar.java:1652)
	at java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:758)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:702)
	at net.osmand.gpx.GPXUtilities.getTimeFormatterTZ(GPXUtilities.java:1329)
	at net.osmand.gpx.GPXUtilities.parseTime(GPXUtilities.java:1302)
	at net.osmand.gpx.GPXUtilities.loadGPXFile(GPXUtilities.java:1641)
	at net.osmand.gpx.GPXUtilities.loadGPXFile(GPXUtilities.java:1349)
	at net.osmand.gpx.GPXUtilities.loadGPXFile(GPXUtilities.java:1342)
	at net.osmand.plus.configmap.tracks.TrackItemsLoaderTask.getGPXFile(TrackItemsLoaderTask.java:117)
	at net.osmand.plus.configmap.tracks.TrackItemsLoaderTask.loadGPXFolder(TrackItemsLoaderTask.java:83)
	at net.osmand.plus.configmap.tracks.TrackItemsLoaderTask.loadGPXFolder(TrackItemsLoaderTask.java:81)
	at net.osmand.plus.configmap.tracks.TrackItemsLoaderTask.doInBackground(TrackItemsLoaderTask.java:63)
	at net.osmand.plus.configmap.tracks.TrackItemsLoaderTask.doInBackground(TrackItemsLoaderTask.java:28)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
```

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14224mqta, Дата выпуска: 2023-03-08
Android version: 12
Device model: poco f3

**Comment by sonora** [comment] 2023-03-08 09:00
Another duplicate of https://github.com/osmandapp/OsmAnd/issues/14890#issuecomment-1455181175 and #16606, it seems?

**Closed** 2023-03-08 09:13 UTC
