### ISSUE TITLE
Wrong number of lanes. Sometimes...

### ISSUE THREAD

**Issue by RussianFox** [osmandapp/Osmand#7518] opened 2019-09-05 08:02 UTC
When driving, sometimes the osmand shows wrong lanes. When emulating routing at the same point, the number of lanes is correct. Another time when driving, the number of lanes is correct. There is no pattern.

I found that the number of lanes always twice as large. And this happens at high speed (140km/h)

I will try to make a video from the screen at this moment and record a track.

**Comment by RussianFox** [comment] 2019-09-05 08:17
I was able to reproduce the bug when emulating

![image](https://user-images.githubusercontent.com/11329995/64323601-7930d700-cfcd-11e9-8c6d-0aa32475c14d.png)
![image](https://user-images.githubusercontent.com/11329995/64323622-8221a880-cfcd-11e9-806b-7e18efe5ede1.png)
Point https://osmand.net/go?lat=60.07265117370175&lon=30.177768617215207&z=21

Line of road https://www.openstreetmap.org/way/721607097

**Comment by RussianFox** [comment] 2019-09-05 08:30
![image](https://user-images.githubusercontent.com/11329995/64324856-ca41ca80-cfcf-11e9-8558-5f18563f7795.png)
![image](https://user-images.githubusercontent.com/11329995/64324879-d2016f00-cfcf-11e9-9f4a-d180ed8e9e5e.png)
![image](https://user-images.githubusercontent.com/11329995/64324893-d88fe680-cfcf-11e9-8d6b-ef7e9f4d04b9.png)

Point start https://osmand.net/go?lat=60.07710116021404&lon=30.183764436629048&z=19
Point finish https://osmand.net/go?lat=60.05259187170085&lon=30.14729066951682&z=19

And this place with other start point 
![image](https://user-images.githubusercontent.com/11329995/64325317-93b87f80-cfd0-11e9-84f2-62fcc56d8b17.png)

**Comment by scaidermern** [comment] 2019-09-05 17:21
Duplicate of #7304 and #5003.

**Comment by vshcherb** [comment] 2019-09-06 07:40
Yes they are connected and related to OsmAnd Live

**Comment by RussianFox** [comment] 2019-09-11 12:19
When live-update is enabled, the folder "live" contains several *.obf files with changes. When routing with live-update is enabled, the number of lanes from all of these files for the line is summed.

**Comment by MadWasp79** [comment] 2019-09-25 06:38
@RussianFox  hello. Can you try to reproduce this bug now, with latest live updates? It's very elusive.

**Comment by noci2012** [comment] 2019-09-26 14:43
i observed it during last weeks in holland on a road  A27 Utrecht -> North, around the Hilversum ramps.
Suddenly 6 lanes.  Is this a software update or update on the maps.

**Comment by MadWasp79** [comment] 2019-09-30 11:40
Closed with https://github.com/osmandapp/OsmAnd-core/pull/91

**Closed by MadWasp79** 2019-09-30 11:40 UTC
