### ISSUE TITLE
Clarify that a name is on the current road with an icon (e.g. crosshair)

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2862] opened 2016-07-24 17:26 UTC
As the name of the recommended road in navigation is shown in the same place than the name of a current road in non-navigation (and potentially in a lost-route situation, see #2747), it would be helpful to have an icon in front of the name. 

The 'crosshair' icon should be universally understood as the current location, so it could symbolise the current road name I'm driving on.

Don't mind the colour in the mock-up below, b/w is fine as well:

![screenshot_crosshair-name](https://cloud.githubusercontent.com/assets/8266355/17085263/5861b6ae-51d4-11e6-82b9-7a572bfa7394.png)

**Comment by sonora** [comment] 2016-07-24 20:22
Yes, I like that!  :)

**Comment by sonora** [comment] 2016-07-24 23:33
PS: We can very simply use a `"\u2316"` prefix.

**Comment by polarbearing** [comment] 2016-07-25 06:25
\u2316 is called Position Indicator: ⌖, that would be fine.

**Comment by sonora** [comment] 2016-07-25 08:13
If we imply add add a character, this commit should fix it: https://github.com/osmandapp/Osmand/commit/6cf8e01563a5ec3568ee640686aa3297f87db808

This https://github.com/osmandapp/Osmand/commit/5ab723f0efb14ee407bff23e1873e38caed400a0 is a better version and also tests why nothing is displayed on some devices. Unfortunately, Android versions (I think this may only have been fixed in Android 6) are not very complete supporting all Unicode characters, and on my test devices the ⌖ does not show up (though the '+' added as a test does). So we may either have to chose a better-supported character, or an icon.

**Comment by polarbearing** [comment] 2016-07-25 09:55
As icons are used in this position anyway for navigation purposes, that might be the safer solution then.

**Comment by polarbearing** [comment] 2016-07-26 13:39
yeah I see just the + from the "\u2316+  " on my 4.1.2 android.

**Comment by vshcherb** [comment] 2016-07-27 21:40
Nope I think we should not hurry and make proper icon, we should not rely on user fonts. We have an icon and that will be an easy fix, I'm not sure if it comes to 2.4

**Comment by sonora** [comment] 2016-07-28 22:21
Something based on `map_my_location.png`, I guess.

**Comment by sonora** [comment] 2016-08-04 19:30
- We already mark **turns onto roads/refs** by pre-fixing the respective turn arrow before the text in the top bar.

- If we now also put a crosshair icon to mark if the name displayed marks **the street you are currently on**, I guess we should also at the same time

- denote when the text we display in the top bare actually is a **destination (towards)** instruction. This could perhaps be denoted by a signpost icon or similar.

**Comment by sonora** [comment] 2016-08-05 08:02
Follow up: I think the destination case (3rd bullet above) is better fixed by this commit: https://github.com/osmandapp/Osmand/commit/c928c89209a83fda06ab3da083ed1b474e74f426, which I also need for produce better navigation-description tag content in route GPX files.

So the issue is back to what was originally described: Crosshair icon for the "on road" case.

**Comment by polarbearing** [comment] 2016-08-05 09:38
Fully agree with the three bullets, and I claim [authorship](https://code.google.com/archive/p/osmand/issues/2506) for this idea :-) , though G\*\*gl\* has replaced the user names with funny animals.

**Comment by sonora** [comment] 2016-08-05 11:51
I see.  :)  I have injected a (localized) "toward" before any destination displayed, which should do the trick, because we may have mixtures of being **on "⌖ Highway XX towards San Francisco"**, so other than the crosshair icon at the beginning of the line the interim "toward" is better done via a string operation.

**Comment by vshcherb** [comment] 2016-08-07 19:25
I disagree with toward, it has too many characters and in some translation it could have up to 10 symbols. I definitely vote against this word and any word, it should be an icon and we will properly put it later

**Comment by polarbearing** [comment] 2016-08-07 19:30
Yes icon please, I was just about to complain as well, it moves important information out of the widget. Icon please.
![screenshot_2016-08-07-10-44_towards](https://cloud.githubusercontent.com/assets/8266355/17464711/183a5b72-5ce6-11e6-9e7e-b721c6120344.png)

**Comment by sonora** [comment] 2016-08-09 19:04
Fair enough. As long as we do not have icons, I have interim substituted where the crosshair ⌖ would be a `+`, and denoted the ᐅ (towards ) by `>`, so we can test if the logic works all right(https://github.com/osmandapp/Osmand/commit/91620a98ca525f2a07f3b1e179549017125518af).

**Comment by vshcherb** [comment] 2016-08-16 21:10
Fixed

**Closed by vshcherb** 2016-08-16 21:10 UTC

**Comment by polarbearing** [comment] 2016-08-16 21:58
In nb-2016-08-12 I used over the weekend, the "towards" was replaced with ">" only for the non-navigational street display; in navigation mode it was still the full word.

**Comment by sonora** [comment] 2016-08-17 07:13
@polarbearing : navigation case should be fixed, please re-test.

**Comment by polarbearing** [comment] 2016-08-17 14:17
Blue arrow works fine, direction symbol looks like a placeholder on my device, so an icon would be better as well.

Screenshot will follow

**Comment by vshcherb** [comment] 2016-08-17 20:51
That was a wrong symbol, please try latest build it should be better. This symbol is supported by Roboto and Droid.

**Comment by sonora** [comment] 2016-08-17 20:54
@vshcherb : We may have just overlapped, I tried to revert to using >>, which will definitely work. Victor, maybe you can re-commit to try yours first.
