### ISSUE TITLE
Change the color of the map context menu to light, when the map is in day mode.

### ISSUE THREAD

**Issue by enomat** [osmandapp/Osmand#1566] opened 2015-08-17 14:23 UTC
Currently the map context menu (the popup box that appears when you long tap the map) always has black background and white text, regardless of whether the map is in day mode or not.

![screenshot_2015-08-17-14-29-30](https://cloud.githubusercontent.com/assets/12612250/9305239/01b368d0-44f0-11e5-8904-28d6c88a41c2.png)

This context menu/box should have white background and black text when
 the map is in **day mode/view**.

It would improve the consistency of the UI. (As opposed to the current way, when I choose day map mode and everything become light, that box remains dark.)

**Comment by GabrielSebastianMoise** [comment] 2015-08-17 21:01
Seriously ? These guys has better things to do, to develop, repair, adjust, and less time to do a minor backgroud for such small thing. This is not an issue, like those for changing settings, routing, warning announcements, hazard tags implementation driver alerts, and so on.
IMHO  this request and some others, have a very small importance, that somethimes they sound so weird comapred with the ones with very high importance !

**Comment by jkufner** [comment] 2015-08-17 21:29
@GabrielSebastianMoise Devil is hidden in details. Yes, it is low priority stuff, but when someone is in mood for a few little fixes, it should be fixed/enhanced. Also bugs like this one are nice starting points for novice programmers.

@enomat It should respect light/dark UI mode in day mode and be always black in night mode.

**Comment by vshcherb** [comment] 2015-09-30 08:52
Yes, we know about that issue, most likely we will try to come up with a solution to change an application theme depending on Day/night mode view. The issue is that we can't really change Android Theme on the fly (Android doesn't properly support it and we didn't find workaround yet). But in our short plan is to consolidate context menu not with an app Theme, but with a Day/Night mode. We are changing context menu now, so that issue becomes irrelevant.

**Closed by vshcherb** 2015-09-30 08:52 UTC

**Comment by sonora** [comment] 2015-09-30 12:19
For now I suggest we use the dark theme as our default!  90% of the users will never change the theme anyway, and hence this will greatly contribute to avoiding this issue.

The dark theme is both more readable under man circumstances, does not have he glare issue, and on some devices also consumes less battery power. Many outdoor apps use dark themes by default, for exactly these reasons.

Best, Hardy

**Comment by vshcherb** [comment] 2015-10-02 15:50
I think we should use light by default as it looks better, but this issue will be fixed.
