### ISSUE TITLE
Self created search filter now in lowerkeys

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/OsmAnd#10130] opened 2020-11-04 08:44 UTC
I created own filters and stored them with a certain name. The name starts with a capital "A" followed by a space and then the search item. So a filter reads eg. "A Historische Ruine" and appeared with this name on top of the categories. With the Osmand-version 3.8.3 the names appear with a capital "A" and the rest of the line only lowercase-letters. If I create a new filter, then the same happens. 

What should happen? The filter-names should be untouched ...

Spielmops

**Comment by scaidermern** [comment] 2020-11-04 09:45
Duplicate of #9506. Looks like it has already been fixed.

**Comment by pebogufi** [comment] 2020-11-04 09:47
This is already reported jul 22 and fixed 17 days ago. Please wait for new version.
https://github.com/osmandapp/OsmAnd/issues/9506

**Closed** 2020-11-04 12:28 UTC

**Comment by Spielmops** [comment] 2020-11-30 11:52
New version 3.8.5 and still the same happens ...

Spielmops

**Comment by pebogufi** [comment] 2020-11-30 14:48
See my comment above. 
Ok in OsmAnd~  3.9.0#30985m.apk
Use nightly builds or wait for update to 3.9

**Comment by Spielmops** [comment] 2020-11-30 15:35
OK,thanks for the Info
