### ISSUE TITLE
Osmand switches back to standard-profile automatically?

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#13558] opened 2022-01-16 16:49 UTC
### Description
After finishing a route in a chosen profile (car, motorbike, …), Osmand always switches back to the “view map”-(standard-)profile and does not remain in the previous used profile. Though my routing is finished this moment, I want to continue driving in my chosen profile and don’t want to get back to the standard-profile.

### How to reproduce?
Drive and finish a route in the car or bike profile to its end. After confirming finishing it, profile is switched back to "view map".

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: 11
Device model: S20+

**Comment by EssBee59** [comment] 2022-01-19 19:59
I think, the switch to "view map" after finishing a tour is ok.

In the settings, you can activate/deactivate the profiles as you prefer/need:
If only "bike" is activated, it will be used by the next routing.
If you have several profiles activ, Osmand do not know, which of them have to be used in the next tour...
In thety case, several symbols appear and you have to select the one you want.

For my own, I prefer to activate only 1 profile at a time, this avoids forgotting to select among the availables profiles...

regards

**Comment by Rowin63** [comment] 2022-01-19 20:16
No, for me it is not.

Osmand does not need to know which profile I´m gonna use next, but it knows the one I just used for routing and I want to continue driving in this profile, though routing has finished. Riding on a motorbike, I can´t just switch back to the profile I´ve been in a second before. I need to stop, get my glove off and do something I wouldn´t need to.
And I dont want to activate and deactivate profiles all the time. Thats not the intention of using different profiles.

**Comment by scaidermern** [comment] 2022-01-21 07:49
Duplicate of #8640.

**Comment by Rowin63** [comment] 2022-01-21 07:59
Yes it is. Sorry, did not see this.

**Comment by vshcherb** [comment] 2022-01-21 14:06
Please note, If you select "Default profile" then switch won't be perform.

**Closed** 2022-01-21 14:05 UTC

**Comment by Rowin63** [comment] 2022-01-21 21:51
Yes I know, thank you.
But than means, before every ride in a specific profile I have to check first the main settings to see, which profile is set to standard. 
I don´t see the benefit of checking and changing the standard profile before every use.
But in my opinion it is comfortable remaining in the last used profile until I do choose conciously another profile.

**Comment by EssBee59** [comment] 2022-01-22 08:11
> I need to stop, get my glove off and do something I wouldn´t need to.

Hello Rowin63,
I understand your request, just a short remark:
The problem you mentioned using glove (for myself, without the right glasses to read symbols in the display!) is the reason why I prefer to activate only 1 profile for a gived day.
I set the profile home when I know which vehicle I will use (Fastbike, MTB, car or else .. I will use this day.
With gloves / withhout glasses the risc to change unintentionally the profile underway is too high for me.

This is the way I would recommend, but your request is ok... if you do not see or accept a risc !

**Comment by Rowin63** [comment] 2022-01-22 09:26
Beside the fact this issue is already closed: 
no, I dont want to take this or any other risk. But I have to, _because_ osmand switches automatically to another profile. The most simple solution: just stay in the profile you´re in, as long an the user does not conciously select another.
I still don´t get the benefit of automatically changing the profile.

**Comment by vshcherb** [comment] 2022-01-25 17:18
@Rowin63 benefit is very simple and it is in most of navigation + maps apps. Navigation mode is not the same as Browse Map mode. 
Effectively when you switch profile you enter Navigation mode i.e. you switch the map view what's convenient to drive, once you finish the drive you no longer need to have this mode and you get back to Browse Map mode.

**Comment by scaidermern** [comment] 2022-01-25 17:37
It would be nice if the user could decide when to leave navigation mode. With the current behaviour OsmAnd decides when to leave it. Re-entering navigation mode while driving is really unfortunate.

**Comment by Rowin63** [comment] 2022-01-25 17:51
> ... once you finish the drive you no longer need to have this mode...

Thanks for your opinion. 
But this is exactly my point: Finishing the guided route does not mean finishing my drive. In this point Osmands switching back it is very inconvenient, because I have to switch back again to the last used profile while still driving.

**Comment by vshcherb** [comment] 2022-01-25 20:32
We try to deal with with Finish Dialog, so if you don't click finish but tap to the map it should stay with profile active for driving. I would agree we better introduce another clear option "Keep driving".
