### ISSUE TITLE
The navigation "arrow"/symbol shows fake direction

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#21478] opened 2024-11-28 19:42 UTC
### Description

Maybe my assumption is wrong, but I guess that the arrow should point towards movement direction.
It seems to me, that now it shows expected direction if I were following the navigation route.
When stopped, then it can presume the correct position unless the speed is non-zero and position actually changes.

### Steps to reproduce

Use navigation.

### Actual result

The arrow points toward directions instead of actual movement.

### Expected result

The arrow should point were I am moving.

### Your Environment (required)

```
OsmAnd Version: 4.9.7
Android/iOS version: 14
Device model: Motorola Edge 40 Pro
Crash-Logs: ?
```

**Comment by scaidermern** [comment] 2024-11-29 05:41
Duplicate of #21428?

**Comment by vshcherb** [comment] 2024-11-30 15:04
If you use snap to road than direction is fake (based on route direction) unless you deviate from the route

**Comment by mdykierek** [comment] 2024-12-02 12:31
That is right. For me the issue can be closed.

**Closed** 2024-12-03 08:44 UTC
Labels: Observed
