### ISSUE TITLE
Shoreline still not conforming in Florida keys after update

### ISSUE THREAD

**Issue by Seaviator** [osmandapp/Osmand#7343] opened 2019-07-29 20:01 UTC
The latest update fixed some problems but also introduced some new ones. On key West itself the same problem persists, that being the land disappearing underneath the buildings. But I have encountered a new problem. The land seems to extend past the shoreline, into the water at some points.  

Here is a link to some images that might help explain:

https://imgur.com/a/GFxfvwE

**Comment by xmd5a2** [comment] 2019-09-06 07:28
Duplicate of https://github.com/osmandapp/Osmand/issues/6565

**Closed by xmd5a2** 2019-09-06 07:28 UTC
