### ISSUE TITLE
Opening_hours wrong interpreted

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#4934] opened 2018-01-23 07:59 UTC
Entering Opening_hours like example are wrong interpreted:
![wrong opening_hours](https://user-images.githubusercontent.com/18628183/35264112-bad2e4e2-001b-11e8-90a0-52d9decc6c90.png)

Mo-Fr 08:00-12:00
Mo 14:00-18:00 
Tu 16:00-18:00
Th 15:00-18:00
should be interpreted as 
Mo-Fr 08:00-12:00, Mo 14:00-18:00, Tu 16:00-18:00, Th 15:00-18:00
currently wrong is:
Mo-Fr 08:00-12:00; Mo 14:00-18:00; Tu 16:00-18:00; Th 15:00-18:00
that means instead of a semicolon a comma should be used.
Version 3.0.0#23477
Regards Peter

**Comment by vshcherb** [comment] 2018-01-23 08:30
Semicolon is fine in that case as well. I think it is duplicate of #3919

**Closed by vshcherb** 2018-01-23 08:30 UTC

**Comment by pebogufi** [comment] 2018-01-23 08:39
No, I think it is wrong. 
With semicolon it means that Mo 08:00-12:00, Tu 08:00-12:00 and Th 08:00-12:00 are interpreted as OFF.
With comma  it means that Mo 08:00-12:00, Tu 08:00-12:00 and Th 08:00-12:00 are interpreted as ON.

**Comment by vshcherb** [comment] 2018-01-23 08:42
Either
With semicolon it means that Mo 08:00-12:00, Tu 08:00-12:00 and Th 08:00-12:00 are interpreted as ON.
Either
There were some changes in the format that make it non backward compatible. As far as I know it was always ON since 2011

**Comment by pebogufi** [comment] 2018-01-23 08:55
Having a object with the opening_hours of example with semicolon osmand tells me this morning that next opening will be on We 08:00 (this is wrong). Currently (Tu 09:50) osmand shows me Opening_hours as red.
It should be green because it is in that range: Tu 08:00-12:00

**Comment by vshcherb** [comment] 2018-01-23 22:59
@pebogufi There was that issue in the nightly build but I guess it was just fixed yesterday. Anyway let's separate OSM Editing issue and functional issue (if it is still in the latest build please open a different bug).

**Comment by jandr** [comment] 2018-07-03 10:07
I disagree, @vshcherb .  The example shown by @pebogufi can be replicated on the stable OsmAnd version (3.0.4) at the time of writing.  Adding a common time to a set of days (e.g. Mo-Fr) and then other specific hours for each/some of those days would result in an incorrect opening_hours tag:

Reusing the example: 

Mo-Fr 08:00-12:00   -- From Monday to Friday, it opens every day from 08:00 to 12:00
Mo 14:00-18:00 -- Additionally, on Mondays it opens from 14:00 to 18:00
Tu 16:00-18:00 -- However, on Tuesdays it is only from 16:00 to 18:00
Th 15:00-18:00 -- Thursdays have a bit more time than Tuesdays, but less than Mondays (15:00-18:00)

Wednesdays and Fridays, the place is closed in the afternoon/evening.

OsmAnd separates each of this time-frames by semi-colon (;) instead of commas, but these time-frames should be inclusive.  The correct opening_hours for the above would be:

Mo-Fr 08:00-12:00**,** Mo 14:00-18:00**,** Tu 16:00-18:00**,** Th 15:00-18:00

OsmAnd is using semi-colons (;) instead of commas (,).  According to the specification, if a day is found in the expression after it has been previously defined, separated by a semicolon, the previous information will be cleared and only the new information is considered.  Thus, the opening hours will be considered as:

Monday - from 14:00 to 18:00 (not open in the morning, as the Mo-Fr time is cleared when reading the "Mo 14:00-18:00" after a semicolon)
Tuesday - from 16:00 to 18:00 (not open in the morning, see above)
Wednesday - from 08:00 to 12:00 (We does not appear by itself after the semicolon, so the first definition is applied)
Thursday - from 15:00 to 18:00
Friday - from 08:00 to 12:00

The above is obviously wrong.  The way to fix it would need the code to follow the definition properly, and use commas when needed (when days are repeated) when editing POIs, and also adhere to the definition when parsing opening_hours tags.

You can see the difference in the following links to the evaluation tool, which shows a graphical representation: 

OsmAnd (semicolon version):  http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2008%3A00-12%3A00%3B%20Mo%2014%3A00-18%3A00%3B%20Tu%2016%3A00-18%3A00%3B%20Th%2015%3A00-18%3A00&lat=48.7769&lon=9.1844&mode=0&DATE=1530611580000

Proposed (comma version): http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2008%3A00-12%3A00%2C%20Mo%2014%3A00-18%3A00%2C%20Tu%2016%3A00-18%3A00%2C%20Th%2015%3A00-18%3A00&lat=48.7769&lon=9.1844&mode=0&DATE=1530611580000

**Comment by jandr** [comment] 2018-07-03 10:10
For reference, just in case, I am providing links to the definition and the discussion on this in the opening_hours code: 

https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:additional_rule_separator

https://github.com/opening-hours/opening_hours.js/issues/53
