### ISSUE TITLE
addr:inclusion=estimate is ignored?

### ISSUE THREAD

**Issue by DonLiborio** [osmandapp/Osmand#5072] opened 2018-02-26 19:02 UTC
What version of OsmAnd are you using, on what device and Android/iOS version?
Osmand 2.9.3 on Blu Studio One (Android 5.1)

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline maps.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

In-app

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

Is addr:inclusion=estimate ignored? Osmand doesn't estimate an address between two nodes on a address numbering line.

**Example:** _Montevideo 2552, Rosario, Argentina_

The address is estimated correctly (about mid-block) at [openstreetmap.org](https://www.openstreetmap.org/search?query=montevideo%202552%2C%20rosario#map=19/-32.95253/-60.66047), but Osmand suggests _Montevideo 2502_

At least in Argentina, blocks have very predictable numberings in general and estimated addresses should work well (I think Google Maps does this). But I think Osmand is ignoring this tag (maybe it's too computationally intensive?). It'd be neat if the user didn't have to guess to which of the corners of the block she should drive, and the aproximate location of the destination within the block.

**Comment by vshcherb** [comment] 2018-03-09 09:21
I guess the issue is related to "addr:interpolation" probably it is not handled correctly.

**Comment by vshcherb** [comment] 2018-05-11 07:42
The issue was fixed with 3.0

**Closed by vshcherb** 2018-05-11 07:42 UTC
Labels: Nice to Have
