### ISSUE TITLE
Incorrect speed limit warning

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17065] opened 2023-04-26 16:06 UTC
### To Do

- [ ] Display 100 km/h speed limit warning

### Description
When navigating on the highway, a warning about the speed limit of 80 km/h is displayed. 
But, in [OSM data](https://www.openstreetmap.org/way/702395360#map=19/50.93788/5.93349), the maximum speed is 100 km/h.
[OsmAnd](https://osmand.net/map?start=50.937377%2C5.932971&end=50.944001%2C5.946543&mode=car#16/50.9420/5.9418)

### Steps to reproduce

- **Navigation from** `50.93751, 5.93279` to `50.94324, 5.94462`
- **Simulate navigation** > **Fixed speed 123 km/h**

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/234634284-7f8f3216-ec8e-43a6-849b-584f5f9d2b76.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
Speed limit warning shown 100 km/h

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35850m, Released: 2023-04-26
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by xmd5a2** [comment] 2023-05-26 06:20
Fixed. Duplicate of https://github.com/osmandapp/OsmAnd/issues/17017

**Closed by xmd5a2** 2023-05-26 06:20 UTC
Labels: routing

**Comment by Zirochkabila** [comment] 2023-05-26 13:17
New maps are required
