### ISSUE TITLE
Trip recording (plugin) - add "Stop and Save"

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2721] opened 2016-06-19 17:00 UTC
For the Trip recording (plugin), would it be possible to add an additional option "Stop GPS logging and save current track"? (I usually find myself first "stopping" and then "saving", i.e. extra taps.)

**Comment by homersimpsons** [comment] 2016-06-19 18:14
I think this is a duplicate of #2641

**Comment by bjohas** [comment] 2016-06-19 20:14
Ah yes - or at least a duplicate of one suggestion in https://github.com/osmandapp/Osmand/issues/2641.

**Closed** 2016-06-19 21:48 UTC
