### ISSUE TITLE
Reverse Direction Not Always Recalculating

### ISSUE THREAD

**Issue by seniorm0ment** [osmandapp/OsmAnd#16450] opened 2023-02-13 12:12 UTC
Most often than not, if I start heading in the opposite direction (say I can't get down a road, or there's a detour, or I accidentally take the wrong route) it wants me to do a uturn on that road and get back on the line. (To be clear it's not telling me to uturn, it just wants me to head back on the line)

It doesn't navigate me safely to other roads to get back onto the route like it should. This has happened so many times.
I have to stop routing, then restart it. Not safe while driving. 

I checked navigation settings, I have recalculate in cade of reverse direction enabled, and I have recalculate based off a certain distance disabled.

**Comment by bhankerson** [comment] 2023-02-13 19:06
I've noticed this issue too, while driving on gravel roads when routing wants to route me on a longer, paved route. After 1 mile it says "you've been off route for about 1 mile, recalculating...", then it recalculates. Have you tried driving at least a mile (or maybe a km) to see if it recalculates? I had "In case of reverse direction" disabled (I don't understand what it's supposed to do), I've enabled it now to see if it does the same thing.
It's probably related to #14466, but the problem is the opposite effect of no voice prompts.
Is this the right place to suggest that an option be created to disallow reverse route recalculation, and instead force recalculation of a route in the direction of travel?

**Comment by sonora** [comment] 2023-02-13 19:27
I  am not even sure we need an option or setting for this, because I would find it awkward to have to set it case by case (and would mostly forget).

Couldn't the user story be:
- [ ] The first route calculation results in the best route found, regardless of any movement the user may exhibit (user may even be at rest at the time, e.g. sitting in a parking lot)
- [ ] User starts driving, but in  a different, e.g. the oposite, direction than the route suggests.
- [ ] User will one time see an arrow indication and hear a message like "_Pleaee make a U-turn when possible_"
- [ ] If the user continues in the 'false' direction, all subsequent route recalculations will account for this by now calculating the route starting in the user's 'forward' direction.

**Comment by bhankerson** [comment] 2023-02-13 21:14
That'd be perfect, from my perspective.
Is this the right place to request multiple, alternate routes be shown at first calculation? :)

**Comment by vshcherb** [comment] 2023-02-16 22:52
@sonora i'm not sure how it's connected or not, I'm not convinced yet that we should change anything.  we always add penalty for wrong direction but we don't judge on navigation cause it could have flaws. 
It's not a constant but time to make constant to routing.xml probably - https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/router/BinaryRoutePlanner.java#L297. So if you drive different direction we assume that you could make a turn in 9 minutes (which probably not always true).

**Comment by sonora** [comment] 2023-02-17 00:42
Yes, you are right, I have also been re-thinking this. My thinking is now that this has actually worked well over the years, so I think priority is not to think about a new user story now,  but rather pinpoint what seems to have changed between apparently version 4.2.7 and 4.3.x.

I am currently a bit baffled by the fact that we hear so many voice prompts in the cases whee you do not follow the route in forward direction, almost like method `RoutingHelperUtils.checkWrongMovementDirection(currentLocation, prev, next)` does not work anymore as intended.

**Comment by Zirochkabila** [comment] 2023-02-19 08:59
OsmAnd~ 4.4.0#14188mqta, Released: 2023-02-19

[OsmAnd](https://osmand.net/map/?start=50.450154%2C30.502832&end=50.454240%2C30.498219&mode=car#17/50.45171/30.49918) 207 cost
[OsmAnd](https://osmand.net/map/?start=50.450202%2C30.502864&end=50.454240%2C30.498219&mode=car#17/50.45171/30.49918) 175 cost

Until then, the most alternative route (the route with the lower price) is a U-turn - the recalculation is made according to this principle. As soon as your position is in a place more suitable for recalculation (the route price is lower), the route will be built on a different road. You can see an example in the video


https://user-images.githubusercontent.com/104760013/219938666-d4e93a7c-a0de-43a5-ba7f-da1498d58953.mp4

**Comment by bhankerson** [comment] 2023-02-26 18:13
Yesterday I drove 7 miles in the "wrong" direction until it recalculated. It just kept extending a straight line (not snapping to any road) back to where it thought I should continue the original route. On the same navigation session, I again deviated from the route and it took 10 miles to recalculate. And when it did recalculate, it gave me some wacky route to get back to the parallel road that was on the original route (some 10 miles longer, and on a lesser road; I was on an interstate, and it wanted me to go on a 10-mile-longer county road route). Something funky is happening with the recalculation

**Comment by sonora** [comment] 2023-02-27 08:22
I have not tesred the following suspicion: Possibly this was broken by https://github.com/osmandapp/OsmAnd/commit/73d92c4b4f4909c7e389c7b15337246a9e430e4d, and could perhaps be fixed by https://github.com/osmandapp/OsmAnd/pull/16548.

**Comment by vshcherb** [comment] 2023-02-27 11:36
@sonora Great. Yes we came to same conclusion!

**Comment by vshcherb** [comment] 2023-02-27 11:37
Duplicate https://github.com/osmandapp/OsmAnd/issues/16277

**Closed by vshcherb** 2023-02-27 11:36 UTC
