### ISSUE TITLE
BT audio output does not work correctly after route recalculation

### ISSUE THREAD

**Issue by Gabor-B** [osmandapp/Osmand#2810] opened 2016-07-11 06:31 UTC
While testing the new feature in the nightly to pass BT audio via SCO ( #2590 ) I have encountered a bug
- Driving normally the feature works as expected
- When one deviates from the route and osmand has to recalculate the route a message starts to play, but the bluetooth channel is interrupted after 1second.
- After that the audio output is not working anymore.

Assumptions:
Sometimes there is some audio output over BT, for example when the audio message is long enough. Most of the message is truncated however and you only hear the last couple of seconds of it. I assume the message lenght from the interrupted route recalculation message is stil stuck in a handler, and when calculating the current output signal shorter messages can't anymore get through. Restart of route, app or BT does not help.

Remark: First time I have encountered this I tried to turn off BT and on again, but the BT slider on the phone got frozen (slider in on position, but disabled) After trying to restart the phone I got stuck in an optimize apps loop and had to wipe all data to get back into android UI.

**Comment by sonora** [comment] 2016-07-11 17:37
Strange, I always test-drive the voice router exactly with an arbitrary destination I am NOT going to (so exactly your scenario), and have done so for 300km over the weekend with no failure (build of 2016-07-08).

Can I please ask you to fill in the following gaps:
- Is this reproducible, or was this a one time occurrence?
- What is your exact setup: OsmAnd build and date(!), Android device, Android version, car stereo

I have checked that everything seems nullified ok upon route recalculation or navigation-restart. And  in any case, the BT connection is reliably reset, at the very latest after killing the OsmAnd app (via a task manager or so), no reboot should be required at all.

But I can add one more reset line of code later just to make sure we are not overlooking anything here. Will edit this post when done and tested.

**Comment by Gabor-B** [comment] 2016-07-11 21:51
Hello, this happened twice exactly the same way, after already driven for +100kms. I will test it again when I can (probably weekend).
Osmand-Nightly 2.4.0#17337M 2016-07-05
Voice: German-TTS
Oneplus Two OOS 3.0.2, Android 6.0.1
Car stereo: Sony MEX-N4100BT

**Comment by sonora** [comment] 2016-07-11 22:44
Ah yes, code of 2016-07-05 still had some issues, finalized 2016-07-09.

So I guess today's change I made may not have been needed, but does not harm either, I hope. Please test builds 2016-07-12 or later, I think I will work now.

Cut-off issue should also be solved. I see some slight cut-off in maybe 5% of cases. But the connection timing is unpredictable, so we probably cannot get much better than this. You can always get the current prompt re-played by tapping on the navigation arrow widget.

**Comment by Gabor-B** [comment] 2016-07-12 05:21
Ok, will test the newer version then

> You can always get the current prompt re-played by tapping on the navigation arrow widget.
I know of that, tried tapping the arrow for a couple of times. It resulted in no output most of the time, sometimes a more or less of truncated message was played.

**Comment by Gabor-B** [comment] 2016-07-14 10:00
I have tested it, now it withstood a couple of route recalculations without incident.
Sadly, the second problem arose again at some random route recalculation point, the bluetooth connection seems to got broken.
Route/App restart did not help, and when I tried to turn BT off/on again, it seemed like it was not reacting. Like the BT stack crashed or something.

![screenshot_20160714-115249](https://cloud.githubusercontent.com/assets/19547553/16835652/0330d498-49ba-11e6-964d-0aff6f6e43da.png)
Symptome:
1. Bluetooth off
2. I press on
3. Usually now the On position gets coloured with the accent colour, and the available and paired devices are listed. Now the slider stays grayed out in the On position and nothing happened. The same text as in the Off position is displayed instead. No connection is established.
Only a phone restart helped. I am puzzled on how to provide useful insight here??

**Comment by sonora** [comment] 2016-07-14 21:12
Let's take this one by one: Can you please describe as detailed as possible what the situation looks like when the issue is present:
- Once again please specify the build number and date, just to be on the safe side
- You are using a TTS voice, not a recorded voice, right?
- What are the exact symptoms: Sound is mute, right? When you change the sound output to "Media", does it work then (through the device speaker), or is it also mute? Does the car radio report a call still being connected or did it hang up properly? Does  the car radio still report the device as being connected, or not (can you dial a call, or play media music from the device)? Does the Android device report Bluetooth as being off, or did you turn it off manually?
- I would be interested in what the results are on your device for my test I describe in Issue 2816, both "normally", i.e. when it works, and after it started failing.

I need to understand as clearly as possible what the situation looks like, because I cannot reproduce this at all. I have now extensively tested devices with Android 4.0, 4.1 and 4.4 on my car stereo, and find they all work flawlessly. (I did discover one issue with recorded voices, but it seems totally unrelated to what you describe.)

**Comment by Gabor-B** [comment] 2016-07-15 20:11
Hi, just tested the same Build again (#17468, 2016/07/14), and the problem occured again, although I could not reproduce the BT stack crash now. Using de-tts. When I change to Notification, guidance is heard over Phone speakers. When I select "Like Media/Audio" and switch to the BT channel on the radio, no output. Car audio still reports phone as connected. When I start Play Music, the connection/output works. Phone connection works OK too. Switching back to SCO- still no output.
Your test: Yes, Yes, 1500, before and after the bug.
Resetting the BT connection helps however to get going again in this case.

When I can reproduce the BT stack crash, I'll report it. I think then the connection was gone for good.

**Comment by sonora** [comment] 2016-07-15 20:43
Thanks. One more detail which would be interesting to know is if, when it fails, simply switching the language to e.g. en-tts gets it going again.

**Comment by Gabor-B** [comment] 2016-07-16 01:04
Consistently when route recalculation begins. And always at the beginning of the prompt, you can only hear the beginning of the "R" in "Route recalculation". I can check the switch to en-tts, but I switched once while testing the SCO mode in the developer plugin, and that did not made it work again.
PS: On the way back today the bluetooth failed completely again, no chance to connect it again. Funny enough, the results of the test were Yes,Yes,1500. With no connection at all..

**Comment by sonora** [comment] 2016-07-16 06:29
I will look at the code again. From what I remember, when it is discovered that you left the route ( this should be some time before the "route recalculated" prompt) is the only point where we call a player "stop" i.e. the same command sent when e.g tapping the stop buton on your media player app. It somehow looks to me that your particular setup does not hanxle this very well during the SCO call.
 - Does the "phone call" for the "Route neu berechnet" call remain indicated as "connected" (call from Unkown or call from phone number) on the car stereo, or do you see the "call ended" being shown as normal?
 - I cannot reproduce this at all with my car and my Android devices. Do hou have a second Android device you could test this with?
 - Is there maybe a firmware update for your car stereo?

**Comment by sonora** [comment] 2016-07-21 19:11
Re-reading this thread one more time, maybe what you are experiencing is some unfortunate timing of events where starting and stopping the SCO connection overlap/interleave and your system setup does not cope with this very well. I have just added code to prevent interleaving - worth a shot,  I guess.

**Comment by sonora** [comment] 2016-07-25 11:49
After our code has now become much snappier processing the off-route situation, I can confirm that there seems an issue, likely exactly under the following conditions:
- An **ongoing** (and only that) voice prompt is interrupted by the player.stop(), which is triggered when the off-route is detected. TTS play over BT SCO then becomes silent for future prompts. The situation is recovered when manually stopping/re-starting the navigation (this re-inits the player). The situation is not well recovered by just tapping the next turn widget to manually trigger a prompt, this may produce partially audible prompts and something progressively gets out of sync.
- The equivalent issue occurs when playing the nav prompts not over BT SCO, but using the media output locally, i.e. via the device speaker. (Also play some music from the Android music player in the background for testing). There the phenomenon is not that future prompts become entirely silenced, but they from then on play on top of the music, i.e. the background music is not interrupted anymore.

This seems to indicate that there is an issue with our audio focus code, unrelated to BT SCO.

Will have to investigate. Always reinitializing the player after a stop could be an interim workaround, but does not eradicate the underlying root cause.

**Comment by Gabor-B** [comment] 2016-07-25 12:08
Hello, I am currently travelling a lot and not near my car, so I cannot test at the moment. I tried it briefly with a BMW car audio, in the short time I used it, it did not produced the bug.

Yuor questions:
   

>  Does the "phone call" for the "Route neu berechnet" call remain indicated as "connected" (call from Unkown or call from phone number) on the car stereo display, or do you see the regular "call ended"?
>     I cannot reproduce this at all with my car and my Android devices. Do hou have a second Android device you could test this with?
The call is disconnected.

>     Is there maybe a firmware update for your car stereo?
Apparently yes, but the changelog does not indicate bluetooth issues. I will test when I can.

> 
    You say it does not happen every time. Does this only happen when you are in the vicinity of your set destination, e.g. <20km?
No, sometimes +100km, sometimes -10km

>     When this occurs: If you simply keep on driving, does the situation recover by itself after 2-3 minutes (i.e. without changing anything)?
No

>     You say your BT stack sometimes crashes when trying to turn it on/off. Have you tried doing this before the issue occurs, is this really strictly limited to when seeing the issue?
Strictly limited to the issue, never seen it before.

**Comment by sonora** [comment] 2016-07-28 18:00
I managed to fix what I could reproduce. If the issue is gone for you, too, we can close this.

**Comment by vshcherb** [comment] 2016-08-03 15:56
Closing as no reaction yet.

**Closed by vshcherb** 2016-08-03 15:56 UTC

**Comment by Gabor-B** [comment] 2016-08-03 18:03
Hello, just arrived from holidays, could not test the issue beforehand. Can confirm that the fix is working with build 2.4.0#17796M. Good job finding the bug!
