### ISSUE TITLE
[Feature request] gpx altitude visualizer - maybe as plugin

### ISSUE THREAD

**Issue by PalatinateTom** [osmandapp/Osmand#3041] opened 2016-09-02 20:15 UTC
I'm using OsmAnd since many years and mostly outside the cities for hiking and biking.
For my use case and hopefully a lot of other users such a feature or  (payed) plugin would be really great.
- could show on a second screen the altitude flow of a stored gpx track
- potentially with color code to show the slope of the track
- if you navigate along such a gpx track it could show your position on that second screen
  (to see that there are only another 1300 m to climb)
- potentially also allows to send the gpx track to some service to correct altitude data
  (minor important)
- potentially also allow the calculated route to you destination to get the altitude profile
  and show it. 
  (As OSM is flat there can be surprises about the shortest way the routing choses)

**Comment by vshcherb** [comment] 2016-09-05 12:54
Thanks for feedback!

**Comment by chaosjug** [comment] 2016-09-09 08:18
It would be really great if the altitude could be locally calculated if the respective contour lines are available.

**Comment by sonora** [comment] 2016-11-24 16:33
Duplicate of #1795.

**Closed by sonora** 2016-11-24 16:33 UTC
Labels: Nice to Have
