### ISSUE TITLE
Disconnecting smartphone from Android Auto aborts navigation

### ISSUE THREAD

**Issue by lucidtanooki** [osmandapp/OsmAnd#18356] opened 2023-10-16 15:29 UTC
### Description

Hi there,
I just bought OsmAnd and noticed a very annoying bug (I don't think it is intended behavior).

When connecting my Android Smartphone (Android 12) to my car I can follow the navigation. But whenever I disconnect the phone (like when stopping the car at a petrol station, giving the phone to another passenger to look something up or answer a call, or just somebody pulling the plug unwated) the calculated route is gone. Especially when having a very long route re-calculating can take very long and I always have to stop the car again to redo this.

I bought the app since Android Auto didn't work with the open source variant OsmAnd~ - but this is a DealBreaker for me. I keep going back to Google Maps for that reason.

Best regards,
lucidtanooki

### Steps to reproduce

1. Calculate a route
2. start navigation
3. connect phone to android auto
4. disconnect phone from car

### Actual result

Route is gone. Navigation has stopped.

### Expected result

Navigation continues on the smartphone screen.

### Your Environment (required)

```
OsmAnd Version: OsmAnd+ 4.5.10
Android/iOS version: Android 12
Device model: XIaomi POCO F2 Pro
Crash-Logs: No crash
```

**Comment by DmitryAlexei** [comment] 2023-10-17 08:41
Duplicate of https://github.com/osmandapp/OsmAnd/issues/18122

**Closed** 2023-10-17 10:16 UTC
