### ISSUE TITLE
[bug] Can't save tracks/GPX anymore ("My Places")

### ISSUE THREAD

**Issue by BG2311** [osmandapp/Osmand#9256] opened 2020-06-16 17:23 UTC
Hi,
I usually enjoy Osmand+ while going on the mountains or before when I plan footpaths to hike. It's been a while since the last time I've planned something in the app, but I've mapped dozens of routes in the past months.
Some days ago I noticed I can't measure/create and save tracks/GPX anymore: I plan the route, then "saves as new GPX file" with "save as route points" -> the message says that it's saved in the storage but I don't find it anymore (not visible nor hide).
I've tried with 5/6 footpaths in different places but the result is the same.

Could you help me?
Thanks
Claudio

**Comment by njohnston** [comment] 2020-06-16 19:50
Duplicate of or related to #9238?

**Comment by BG2311** [comment] 2020-06-16 20:00
Related.
Sorry, I didn't search before opening the thread, you can even merge the two if it's handy, the issue is exactly the same.

**Comment by vshcherb** [comment] 2020-06-17 09:24
Merged to #9238

**Closed by vshcherb** 2020-06-17 09:24 UTC
