### ISSUE TITLE
Opening hours are not interpreted correctly when comment is included

### ISSUE THREAD

**Issue by momu** [osmandapp/Osmand#5250] opened 2018-04-18 08:14 UTC
> What version of OsmAnd are you using, on what device and Android/iOS version?

Android OsmAnd+ 2.93

> Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline map: Germany Berlin 1 April 2018

The node is: 
https://www.openstreetmap.org/node/4608665240

`opening_hours=Mo-We,Fr 09:00-12:00, Mo,Th 15:00-18:00, Tu 15:00-18:00 open "nach Vereinbarung", Th 09:00-12:00 open "Vorsorge"; PH off`

OsmAnd interpretes is at follows (comment "nach Vereinbarung" is always attached):
![screenshot_20180418-100635](https://user-images.githubusercontent.com/1451642/38919482-feff792e-42f0-11e8-82fb-fc80ea2aac2c.png)

Would it help to format it like this?
`opening_hours=Mo-We,Fr 09:00-12:00, Mo,Th 15:00-18:00, Tu 15:00-18:00 open "nach Vereinbarung", Th 09:00-12:00 open "Vorsorge"; PH off`
According [to the opening_hours evaluation tool](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo%2009%3A00-12%3A00%2C%2015%3A00-18%3A00%3B%20Tu%2009%3A00-12%3A00%20%7C%7C%20Tu%2015%3A00-18%3A00%20open%20%22nach%20Vereinbarung%22%3B%20We%2009%3A00-12%3A00%3B%20Fr%2009%3A00-12%3A00%3B%20Th%20%2009%3A00-12%3A00%20open%20%22Vorsorge%22%20%7C%7C%20Th%2015%3A00-18%3A00%3B%20PH%20off&lat=48.7769&lon=9.1844&mode=0&DATE=1523806740000&diff_value=Mo-We%2CFr%2009%3A00-12%3A00%2C%20Mo%2CTh%2015%3A00-18%3A00%2C%20Tu%2015%3A00-18%3A00%20open%20%22nach%20Vereinbarung%22%2C%20Th%2009%3A00-12%3A00%20open%20%22Vorsorge%22%3B%20PH%20off) it is equivalent.

**Comment by scaidermern** [comment] 2018-04-18 08:55
Duplicate of #5231

**Comment by vshcherb** [comment] 2018-04-25 22:19
Duplicate

**Closed by vshcherb** 2018-04-25 22:19 UTC
