### ISSUE TITLE
Osmand Live Android map update issue

### ISSUE THREAD

**Issue by caverdon** [osmandapp/OsmAnd#12282] opened 2021-07-28 11:25 UTC
### Description
Within the last 24 hours, map updates through an Osmand Live subscription in the Android app have stopped working.  

### How to reproduce?

Open the Osmand+ Android App
Go to Osmand Live feature
Notice your list of downloaded maps available and its date / timestamp
Pick a maps that is not current (example: an available map is that more than 1 month old)
Click on the map to do a manual update.
Click "Update Now"
Message appears: "No updates available"
Notice the date/timestamp on the map did not change -- still the old version
Open any desktop system and browse to OpenStreetMaps
Notice that there are map updates that appears in the desktop but do not appear in the app (map updates made after the date of the map in the app)

Another way to see the problem:
Open the Osmand+ Android App
Go to Osmand Live feature
Pick a map that is set for automatic live updates
Notice the maps timestamp IS updated with the latest map version
Click on the map to do a manual update anyway
Click "Update Now"
Message appears: "No updates available"
Check the map in the Osmand+ Android app.  While the map timestamp says the latest map is used, no recent map updates appear when you compare with OpenStreetMaps on a desktop

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: 11.0
Device model: Samsung Galaxy S20 Ultra 5G

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Tested with:
United States Georgia map (available for updating) - map timestamp is June 30 2021 12:00PM
United States Tennessee map (set for automatic live updating) - map timestamp is July 28 2021 4:10AM  (but does not contain map updates made on July 27)

**Comment by caverdon** [comment] 2021-07-28 11:28
I have verified the same issue happens with the Osmand+ Android app on a different device:

Galaxy Tab S6
Android Version 11.0

**Comment by scaidermern** [comment] 2021-07-28 11:30
Can confirm.

**Comment by vshcherb** [comment] 2021-07-28 18:16
Can't reproduce with 3.9.10, everything is updated fine up to 19:30 CET.

**Comment by scaidermern** [comment] 2021-07-28 18:25
For me it reports no updates available. After deleting all live data and restarting OsmAnd there are still no updates. Update size is now 0 kB. Saxony, Germany. 

OsmAnd 4.0.1.

**Comment by kevinp2** [comment] 2021-07-28 21:23
The same problem is occurring in the iOS app.  My US > Colorado map shows older data but claims to be up to date.

**Comment by thompehw** [comment] 2021-07-29 01:15
Live has also stopped working for me (last successful update was 21_07_25, but I only use "update now" every few days when I'm editing).

Android 10
Osmand+ 3.9.10
Map: England South East

**Comment by vshcherb** [comment] 2021-07-29 09:42
Problem shoudl be fixed now

**Closed by vshcherb** 2021-07-29 09:42 UTC

**Comment by pm4rcin** [comment] 2021-07-29 09:44
Confirm it works again.

**Comment by caverdon** [comment] 2021-07-29 10:41
I confirm it is now working
