### ISSUE TITLE
City choice in address search occasionally leaves address search and diverts to map

### ISSUE THREAD

**Issue by aknrdureegaesr** [osmandapp/Osmand#5967] opened 2018-09-02 08:47 UTC
## Sample user journey

(UI texts re-translated from German, may not be correct)

I am currently in town A and want to view an address in town B. (B may be close to A or quite far away.)

I go to "search by address" and notice "look for street in town C" (whatever a previous search had been).

So I understand I'm in the wrong town context and need to set the right town first. There is a UI element "choose town", so I hit that. I enter the first few letters of my town B. Soon, B appears on the list of places that is being displayed. I hit that list item.

Expectation: That town is now pre-selected (instead of the no-longer relevant C) and I can start typing the street. 

Actually seen: Sometimes it works that way, but sometimes, I'm being taken to the map and the town center is displayed. Rather annoying, not helpful, if it its a ~200000 people town with many more than two or three streets. I am not presently able to predict, let alone control, which of the two happens for which place.

When I'm thrown into the map, and I navigate back to the address search, it is still town C that's pre-selected. So, from my user experience point of view, my choice of town has been ignored.

## Specific example

For an example for B where things don't work well, load the map Europe / Germany / Nordrhein-Westfalen. I have the standard map as of 01.08.2018.  The town B = "Mülheim an der Ruhr" (there are several "Mülheims") is a town for which I have these problems. In case that helps, one of B's streets is called Sandstraße .

Oddly enough, using former West-German capital Bonn for town B works much as it should.

## OSMAnd version used

I'm using a Lineage OS (custom Android RAM) phone without any Google services installed (but I don't think that matters), and have OsmAnd~ 3.1.6 (from FDroid).

**Comment by aknrdureegaesr** [comment] 2018-09-02 08:58
I checked "Mülheim an der Ruhr" in OSM and found https://www.openstreetmap.org/relation/62385 , which does not look suspicious to me.

**Comment by vshcherb** [comment] 2018-09-29 23:06
Should be fixed now

**Closed by vshcherb** 2018-09-29 23:06 UTC

**Comment by bauxx** [comment] 2019-02-12 19:44
I have the same issue with address search in the OsmAnd+ app (version 3.2.7 installed via google play) under android 8.1. I am using offline maps, downloaded via the app.
If I go to search > select city first and choose a city (in my case Wien), instead of being able to search the street, OSM And directly shows the location of the city on the map. Thus, I am not able to search any particular street.

Seems to be some kind of bug in the app, maybe it is trivial but I haven't been able to find solution for it for some time already. This behavior comes when I try to look up addresses in any cities, which I get suggested as "nearby cities" (in my case Vienna and nearby cities). Curiously, I can't reproduce the bug on the same version of OsmAnd on other Smartphone device, although similar problems seem to have occured in the past.

I haven't tried reinstalling the app yet.

I will be thankful for any advice/tips!

**Comment by scaidermern** [comment] 2019-03-18 08:10
I just encountered this issue again with OsmAnd 3.3.6. Restarting OsmAnd resolved the problem.
