### ISSUE TITLE
OsmAnd Live still uses removed street

### ISSUE THREAD

**Issue by SchLois** [osmandapp/OsmAnd#9754] opened 2020-09-06 11:43 UTC
The best way to get help about an OsmAnd issue is to create a valid and detailed issue.
Please give us the following information so that we can try to **reproduce** your issue:

🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅-->

# 🐞 bug report

### Is this a regression?
I don't know, because I never had this use case before.

### Description

A few days ago I noticed that an up to that time existing street is being removed and can not be passed anymore. A new one will be built a hundred meters aside. I reported this ([https://www.openstreetmap.org/note/2328577](https://www.openstreetmap.org/note/2328577)) , a mapper fixed this very soon. The result is visible in this changeset [https://www.openstreetmap.org/changeset/90140820#map=19/48.17355/11.81851](https://www.openstreetmap.org/changeset/90140820#map=19/48.17355/11.81851).  

As I am using OsmAnd Live I expect to see this change on my device. But this is not the case. I’m not really a mapper, so I started the discussion  [https://groups.google.com/g/osmand/c/FiK-1HX_7hE](https://groups.google.com/g/osmand/c/FiK-1HX_7hE) to find out where the problem is. Friendly and knowing people came to the result, that the street had correctly been removed by applying the key _removed_ (https://wiki.openstreetmap.org/wiki/Key:removed), but OsmAnd Live does not interpret this right. 
Switching from _offline vector maps (with OsmAnd Live)_ to _OsmAnd  (online tiles)_ as source displays the change correctly (the street is removed) as a proof, that the the change is really correct. 

I dont' know, if the live map creation code or the code that displays the merged base and live diff maps has to be fixed. 

## 🔬 Minimal Reproduction
**Observed wrong result**
1. Select Offline vector maps  as source
2. Make a live update of Deutschland Bayern
3. Navigate to 48.17355/11.81851
4. You see the old version of the map
![LiveUpdate-still there_](https://user-images.githubusercontent.com/70842356/92324699-7cc5c680-f044-11ea-8732-cb44ef9959d1.png)

**Expected result**
1. Select OsmAnd (online tiles) as source
2. Navigate to 48.17355/11.81851
3. You see the correct map as this
![online_map-ok_removed](https://user-images.githubusercontent.com/70842356/92324703-84856b00-f044-11ea-9eae-65684507bd14.png)

## 🔥 Exception or Error
No exception is thrown, no error message, wrong data displayed.

## 🌍  Your Environment

**OsmAnd Version:**
<pre><code>

OsmAnd+ 3.7.4 (the latest available)
</code></pre>

**Device and Android/iOS version:**
<pre><code>
Samsung A5 2016 SM-A510F with Android 7.0 Patch Level 1. Juli 2019 (the latest available)
</code></pre>

**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download. 
  
The sample above is from Deutschland Bayern 01.08.2020 with OsmAnd Live 06.09.2020 00:38 
- [X] Online (tile / raster) maps 
  OsmAnd (online tiles) only to view the difference to Live version

**Anything else relevant?**
Another change initiated at the same time concerning a POI is visible in the live update, so the live update in general is working on my device.

**Comment by GoodClover** [comment] 2020-09-07 11:00
First of all check that you have line updates enabled, do this by going to the OSMAND Live menu and flipping the toggle.
![Screenshot_20200907-115752.png](https://user-images.githubusercontent.com/27222523/92380691-84977080-f101-11ea-8007-f413b6c1742d.png)

Then, if that dosen't work, try deleting the offline map entirely and re-downloading it, make sure Live Updates is enabled again.

Please note it may take an hour after enabling OSM Live for it to update.

**Comment by SchLois** [comment] 2020-09-07 16:31
The Live subscription is active, you can see a screenshot of the live map detail in the third post of the discussion in groups.google.com <https://groups.google.com/g/osmand/c/FiK-1HX_7hE> (direct link to screenshot <https://01027865525950270145.googlegroups.com/attach/505f0d5263e31/Screenshot_20200902-123307.png>). Another change of the same day (https://www.openstreetmap.org/note/2326726) is visible at my device. Live updates of the concerned map are working in general, only the removed street does not go away.

I have already deleted the live update files under /storage/0000-0000/Android/data/net.osmand.plus/live - the live update files were downloaded again, I have the newest version, but the removed street is still there.



Am 07.09.2020 um 13:00 schrieb GoodClover:

**Comment by homocomputeris** [comment] 2020-09-07 23:49
I can confirm this issue in OsmAnd~ 3.7.4

**Comment by Discostu36** [comment] 2020-09-08 10:06
**Can't reproduce** with Deutschland Bayern 01.08.2020 and Osmand Live Deutschland Bayern 08.09.2020 10:50

**Comment by vshcherb** [comment] 2020-09-08 13:48
Obviously with september maps this bug wont' be reproducible, month map https://download.osmand.net/aosmc/germany_bayern_europe/Germany_bayern_europe_20_08_00.obf.gz

**Comment by vshcherb** [comment] 2020-09-08 13:51
Both of the ways are present:
```
Way types [osmand_change-delete (371)] id 55257471235 osmid 431698994
Way types [osmand_change-delete (371)] id 21945506067 osmid 171449266
Way types [osmand_change-delete (371)] id 13702876039 osmid 107053719
Way types [osmand_change-delete (371)] id 13702876679 osmid 107053724
```

So I think after redownload live it won't be reproducible

**Comment by vshcherb** [comment] 2020-09-08 13:55
Probably the issue is that way wasn't removed but the tags were removed - https://www.openstreetmap.org/way/107053724
[Germany_bayern_europe_20_08_30.obf.gz](https://github.com/osmandapp/OsmAnd/files/5188744/Germany_bayern_europe_20_08_30.obf.gz)
The way wasn't present in 30 of August's file

**Comment by SchLois** [comment] 2020-09-08 14:55
With your link I could find the history of the street myself. On August 24 the then existing tag `highway=residential` was renamed to `**removed**:highway=residential` by _opendcc_. From the discussion mentioned above I learned, that this is made to avoid that mappers that use images as a base for their work can see, that the street they still can see on their outdated image had already been in osm and now it is removed and should not be added any more. 

This **removed** namespace is not handled right, either in creating the live files or when displaying it on the device. 

Because with live the street is still visible on mobile devices I independently reported the removed street and on August 30 _wurzelast_ additionally removed some tags like maxheight, maxspeed and so on completly.  

I think when the regular Germany_bayern_europe...-map for september is released, the street could be removed therein and the problem with live wont't be reproducible any more.

**Comment by vshcherb** [comment] 2020-09-11 11:27
I checked the special time and date and there was a glitch. We will double check that Tag renaming from "highway" to "removed:highway" will produce a correct diff.

**Comment by MadWasp79** [comment] 2020-09-23 08:32
fixed with https://github.com/osmandapp/OsmAnd/pull/9866

**Comment by vshcherb** [comment] 2020-09-24 08:47
Issue was not reproduced with separate testing, so tag renaming should work ok

**Closed by vshcherb** 2020-09-24 08:47 UTC

**Comment by SchLois** [comment] 2020-10-01 06:47
Maybe  I finally found the reason for this odd behavior: On my device I had installed only the road network for the whole country and the full maps for some states of it. Because I still had the problem and you could not reproduce it I decided to remove and reinstall the maps, not only the live versions. After deleting the road network for the whole country the map showed up correct in the remaining full map. Trying to reinstall the road network only map I noticed that the road network for the whole country is not available anymore. So I assume I had an outdated, no more maintained version of it on my device. As there is no new version, no update had been suggested and it seemed to be up to date. 
I installed the road network only maps for the remaining states one by one and everything is fine now.
Thank you for investigating my problem.
