### ISSUE TITLE
Add an alert for red light cameras

### ISSUE THREAD

**Issue by CarlosBrys** [osmandapp/OsmAnd#11187] opened 2021-03-18 12:02 UTC
In the same way that the app alerts when driving near a speed control photo camera, add an alert for red light control cameras at traffic lights.
Thank you

**Comment by scaidermern** [comment] 2021-03-18 13:15
Duplicate of #8339 (also reported by you).

**Closed** 2021-03-18 13:38 UTC

**Comment by CarlosBrys** [comment] 2021-03-18 13:39
Duplicate of #8339, that remains one year open.
