### ISSUE TITLE
Reset to default application mode after stop navigation

### ISSUE THREAD

**Issue by ehermann** [osmandapp/OsmAnd#9600] opened 2020-08-09 21:21 UTC
Hello,
Is there a reason to call `	osmandSettings.APPLICATION_MODE.set(osmandSettings.DEFAULT_APPLICATION_MODE.get());` on
OsmandApplication.stopNavigation, or it's a bug?
It's quite annoying to have the application mode reset to the default after every navigation stop instead of staying at the current mode.

**Comment by scaidermern** [comment] 2020-08-10 08:15
Duplicate of #9372.

**Comment by vshcherb** [comment] 2020-08-17 16:58
You can change default of course and we are collecting feedback for #9372 to make this optional

**Closed** 2020-08-17 16:57 UTC

**Comment by andrzej-gmt** [comment] 2020-09-04 09:53
I find changing profile after stop of navigation confusing and annoying. IMHO reasonable would be to reset navigation mode according to current profile.
