### ISSUE TITLE
Set departure time automatically to current time.

### ISSUE THREAD

**Issue by fwsmit** [osmandapp/OsmAnd#14054] opened 2022-04-10 20:42 UTC
Currently departure time is set to 0:00. This makes it so that many public transport options are very bad or unavailable, which results in a bad route. For completeness we need #9117, but it would already be a lot more useful if the departure time was set to the current time. This would be useful for people in travel, but also for better indications of travel duration.

I don't think this should be too hard to implement. If that's the case I'd be willing to implement it. It'd be nice if someone pointed me in the right direction then.

**Comment by vshcherb** [comment] 2022-04-11 12:50
I don't think it's implemented at all, so it's a kind of duplicate of 9117

**Closed by vshcherb** 2022-04-11 12:50 UTC
Labels: Nice to Have
