### ISSUE TITLE
Make text more contrast: Settings, Track Screen

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1257] opened 2015-05-22 06:27 UTC
With respect to this commit https://github.com/osmandapp/Osmand/commit/3d277761db953739b01a1909a1098c4f6d1c0e2f, which makes our light app theme the default now, I urgently suggest that we bring the contrast level for our screens to the standard other apps use, see my screenshots of OsmAnd vs. e.g. Firefox attached. OsmAnd's "Light gray on white" is simply not adequate for an outdoor app which sometimes needs to be operated in bright sunlight and other difficult conditions.
![firefox](https://cloud.githubusercontent.com/assets/845735/7765276/5d764f62-005c-11e5-9b2a-8e552ef8489e.png)
![osmand](https://cloud.githubusercontent.com/assets/845735/7765278/6203124a-005c-11e5-940a-45f4437fda54.png)

**Comment by vshcherb** [comment] 2015-05-22 11:32
This screen doesn't support proper theming color, and cause it overlaps with a flat list much, we think to merge it and deprecate this short list.

**Comment by sonora** [comment] 2015-05-25 10:39
This screen was an example only. The issue is present also on much more meaningful screens like  , the list for the POI search result hits, the pop-up GPX track selection list, the Configure map screen, etc.

Investigating our colors-xml a bit further, I think the issue is we are using a zoo of text colors, too many different constants (a few dozens!) for text colors which in a good and consistent UI should always be identical. We should simplify, this would also yield a more professionally styled interface:

We should have exactly to color patterns, for
- the light
- and dark app theme.
And each color pattern should essentially contain only
- the "highlight" color (our orange),
- the "normal text color" (maximum contrast, make it black and white, respectively),
- the standard background color (make as closely to white/black as possible, to maximize contrast).
- very few more for special cases (location-locked = blue, deactivated=grey.).
I doubt there is any need to have the intermediate "gray" text color used for e.g. additional text fields. If we need it, t should _not_ be used for functionally important text fields like the headers of POI or track categories, menu items, or search POI results(!), which are all things you need to be able to clearly read even under sub-standard lighting conditions.

**Comment by vshcherb** [comment] 2015-05-25 16:32
I disagree, we use only 2 colors actually they are standard in Android and we didn't redefine them.
?android:textColorPrimary
?android:textColorSecondary

Secondary is lighter, but it should be lighter by design. How much lighter is a different question. All other 3 colors https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values/styles.xml are needed for proper design.

**Comment by sonora** [comment] 2015-05-25 18:20
As it happens, I have taken a few hours today to systematically look through our app in both themes, and my impression, before reading your comment, was that I can only re-enforce my comments above: I think we have real issues both from a usability point of view, and from a consistency point of view. The issues spread across many screens, I suggest we publish a short styleguide  (see below) about which color must be applied for what. (I am mainly concerned about text color for now, but this can be expanded to icon color, and to some extent to text size.)

I will be very happy to work on such a concept systematically. But it sounds like I first have to apply some persuasion to convince you we do have room for improvement ...  :-)

Here are random examples, affecting consistency and/or usability:
(1) Search screen (Dark theme): History and Favorite screens show items in white (good readability), but for the Search POIs all result items (not search categories, though) are shown in gray (not optimally legible in sunlight)
(2) Configure map menu shows all entries in gray, why not white?
(3) Also on the Configure map screen, in the light theme, there is a very noticeable difference in font brightness between an item name (e.g. the label "Map magnifier") and the selected value shown (e.g. "150%") . In the dark theme, the difference seems much less, or none at all.
(4) On the My Place/My Tracks screen, the track category names (i.e. the folder names of the track folder's subfolders) are gray and not well readable (also very small) 
(5) On the Dashboard's "Search for" Card: In light theme, we use blue for the 3 icons, and we also use blue for the e.g. "SHOW ALL" tappable text labels in the headline. But in the dark theme we use gray for the 3 search type icons, and orange for the tappable headline text labels. (Certainly not a usability issue, but an inconsistent styleguide use here  :-) ). 

There are more examples, I think we simply should define the 3 prominent text colors for our style in each the Dark and Light scheme, then systematically apply them. It is not rocket science: the pattern could be:

Dark theme:
- Major text labels: White
- Minor text lables: Light gray
- Highlight color: OsmAnd's signature Orange

Light theme:
- Major text labels: Black
- Minor text labels: Dark Gray
- Highlight color: Could also be our OsmAnd signature orange.

(We could use the blue then in both schemes only for the position-related distances on the Dashboard cards).

**Comment by vshcherb** [comment] 2015-05-25 23:32
Short answer:
1, 2, (3?) - confirmed bug
4  - as designed, secondary color (discussible)
5 - tentatively agree, but that was designed like that. It should be orange icons as well.
6 - it is gray here.

Anyway I don't see to much inconsistence, but there are some issues.

**Comment by sonora** [comment] 2015-05-27 21:46
Looking at lines 4 to about 90 of our colors.xml, it becomes clear that we grossly over-customized this. Most of these 85 lines should collapse to only very few different colors, and introducing separate parameters for colors which should have identical values is exactly what opened the door for all the bugs I report above, and several more.

But moving forward, I think the way to go is now to leave all parameters in place and instead assign the standardized (and limited) colors we decide upon for an OsmAnd styleguide. I will gladly give it a shot when I have some time.

**Comment by sonora** [comment] 2015-05-27 22:12
PS: By "consistency" I mean the following: Our colors should not be widely picked (I cannot see any systematic pattern as we have it now), but they should rather correlate between the light and the dark app theme, as follows:
- something which is white in one theme should be black in the other
- something which is say 20% gray the dark scheme must be 100%-20%=80%gray in the light theme, and so on.

**Comment by vshcherb** [comment] 2015-05-27 22:56
I don't think this is the right approach to look at the problem. We have lots of constants but we have used lots of colors and doesn't mean inconsistent. 
Especially if that topic is about text color, only few constants there are about text (usually they contain text_).  To solve mentioned text problems, colors.xml is definitely not the solution. 
Actually the bugs should be fixed in UI xml by setting proper textColor which is missing in some layouts still (mostly these are non-refactored since 2.0 layouts).

**Comment by sonora** [comment] 2015-09-26 08:26
I would like to remind us of this issue, our settings and menu text is still hardy readable in outdoor light conditions, and I think in recent nghtlies we have made things rather worse than better. Again I attach
- The Settings screen of Firefox Mobile, which can serve as an example of good readability (compare to our light theme!)
- Our Settings screen in both light and dark theme (light theme sub-standard, dark theme very bad now)
- Our Track analysis screen, the font also hardly readable (particularly in dark theme)

We also use the same font color now on some more screens like for the track size info on the MyTracks screen, also hardly readable in dark theme.

![settings_firefox_light](https://cloud.githubusercontent.com/assets/845735/10116599/b2c16822-6438-11e5-8a94-64b80156ddd5.png)
![settings_light](https://cloud.githubusercontent.com/assets/845735/10116601/bbddac36-6438-11e5-83c2-1ae4cc29f5e3.png)
![settings_dark](https://cloud.githubusercontent.com/assets/845735/10116603/c8721b58-6438-11e5-98d6-59ad63587cd5.png)
![track-analysisi_dark](https://cloud.githubusercontent.com/assets/845735/10116604/d00025ea-6438-11e5-9506-a481a7d70b5e.png)

**Comment by sonora** [comment] 2015-11-13 08:42
Unfortunately, this issue was re-introduced on Nov. 11, at least for the dark theme. We should make sure we resolve before releasing!
Not quite sure yet which commit caused it, possibly this one: https://github.com/osmandapp/Osmand/commit/b3266d86aff848bbba007c8113d14c63310f776d

**Comment by sonora** [comment] 2015-11-13 20:51
Ok, main issue fixed again, thanks.

But still some minor issues, and I wonder if we really need 3 different text colors or can do with 2. Look at the attached screenshot (dark theme):
Color_1 =  white, OK
Color_2 = light gray = OK
Color_3 = dark gray = Hardly visible. Obsolete, can we use Color_2=
![3_colors](https://cloud.githubusercontent.com/assets/845735/11157219/a1285eca-8a50-11e5-9eb7-1ec833fdd8e0.png)
light gray instead?

**Comment by vshcherb** [comment] 2015-11-15 23:45
For me it looks good, 3 colors is ok.

**Closed** 2015-11-15 23:45 UTC
Labels: Investigating

**Comment by vshcherb** [comment] 2015-11-16 23:50
I would not use dark theme outdoors (in the night may be?). By default we have white theme which is more usable for these conditions. I will ask to look again and will double check myself.

**Comment by vshcherb** [comment] 2015-11-16 23:51
I think you almost convinced me :)

**Comment by vshcherb** [comment] 2015-11-20 11:20
Yes, I think we already changed @dmpr0 , correct me Dmitriy if I'm wrong.

**Comment by dmpr0** [comment] 2015-11-20 11:26
Yes, we make secondary text color in night theme more contrast.
