### ISSUE TITLE
German TTS: small bug with "St"

### ISSUE THREAD

**Issue by daganzdaanda** [osmandapp/Osmand#6618] opened 2019-03-05 11:17 UTC
Using Osmand 3.2.5, but have noticed the issue for a long time.
I don't know if this is in scope for Osmand, or if the TTS is something external.

The german TTS has some trouble with street refs that start with "St", like this 
https://www.openstreetmap.org/way/501115026#map=18/48.39204/10.70425

"St" is short for "Staats-Straße".  If it is pronounced, it should be "es te" (both letters seperately), but the TTS makes it sound like "asht", which may come from the fact that in many words the combination "st" will be pronunced "sht".
In real life, people usually don't use the abbreviation when talking about a "Staatsstraße". The full word is used -- though I'm not sure if that would be a good idea for Osmand...

Thanks for the great app!

**Comment by sonora** [comment] 2019-03-05 12:14
It is TTS-engine dependent, but yes, true, many engines mispronounce this.

We can try the solution of on-the-fly replacing "St " in the beginning of names by "S T " if your engine is set to German. This is tricky because "St " is the beginning of many point names globally, often e.g. abbreviating "Sant", "Saint", "Street", and more. The string replacement affects all these cases, but maybe that's no harm for lack of a better solution? Let's test it.

In principle thos would best be fixed in the TTS engines, but it looks like thay have no good strategy either ...

**Comment by daganzdaanda** [comment] 2019-03-05 12:23
> We can try the solution of on-the-fly replacing "St " in the beginning of names by "S T " if your engine is set to German.

That seems to be a good solution - I think even with St standing for "Saint" or similar, the abbreviation would never be pronounced "asht" in German. 
Of course, no human would use "S T " either, they all would be using the full word. But unless there's a "full_name" tag or similar, the correct full word can't be easily guessed by software.

**Comment by sonora** [comment] 2019-03-05 12:32
I have put the fix in our nightly build, and it will be in the next release I expect (unless we find a problem).

**Comment by jfburke3** [comment] 2019-03-06 01:23
Just wondering if OSM should be edited to replace the St abbreviation with Staatsstraße spelled out, to keep in line with the OSM policy against abbreviations....

**Comment by sonora** [comment] 2019-03-06 06:06
Very good point, I am not sure which rule applies here. On the other hand all German motorway (Autobahn) references seem also present as 'A 1234', primary roads (Bundesstraßen) as 'B 1234', hence the practixe of using St 1234 seems not unusually off?

**Comment by jfburke3** [comment] 2019-03-06 18:36
So...I actually *looked* at the example provided, and see that the issue is with the ref tag.  Yes, abbreviations are used in ref tags, so my previous comment can be disregarded.

This appears to be someone similar to #1279 with U.S. state highway refs.

**Comment by sonora** [comment] 2019-03-06 19:51
Yes, exactly, and for our English TTS I had to introduce a similar on-the-fly replacement years ago to make state routes sound 'S R' instead of 'Senior', how both google's and Samsung's engines pronounced it. :)

**Comment by sonora** [comment] 2019-03-06 19:53
I will close this but let's note any unwanted side effects here, I will monitor the thread.

**Closed by sonora** 2019-03-06 19:53 UTC

**Comment by daganzdaanda** [comment] 2019-03-07 16:48
Thanks a lot!
