### ISSUE TITLE
Enable export of multiple tracks

### ISSUE THREAD

**Issue by quazgar** [osmandapp/OsmAnd#13504] opened 2022-01-09 11:45 UTC
# 🚀 feature request

Exporting/sharing multiple tracks should be possible, similarly to OSM notes.

### Description

I would find it very convenient to export more than a single recorded track at once.

### Describe the solution you'd like

Exporting multiple OSM notes at once is possible already, the same should be possible for recorded tracks. Probably a lot of the OSM not exporting code can be reused. Also uploading to openstreetmap.org is possible for several tracks already.

### Describe alternatives you've considered

Direct access to the android file system works as an alternative, but may not be convenient for everyone.

**Comment by scaidermern** [comment] 2022-01-09 17:30
Duplicate of #5558 :(

**Comment by quazgar** [comment] 2022-01-09 18:01
Closing because it's a duplicate.

**Closed** 2022-01-09 18:01 UTC
