### ISSUE TITLE
Configure Map: add sunset / sunrise time to Map Mode

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#7244] opened 2019-07-12 18:26 UTC
This is the right place to indicate when switch will happen today and it is also useful for other purposes

**Comment by Dima-1** [comment] 2019-11-09 17:12
Are you mean like this?
![Screenshot_1](https://user-images.githubusercontent.com/31807095/68532341-15a88a00-032d-11ea-8de7-a0a1f1256380.png)

**Comment by sonora** [comment] 2019-11-09 18:40
Should be rather easy, it is in our dev plugin so we can just copy the code.

**Comment by Dima-1** [comment] 2019-11-09 19:19
It wasn't difficult, but I didn’t know that you have the code.

**Comment by sonora** [comment] 2019-11-09 19:21
https://github.com/osmandapp/Osmand/blob/b72a0e7c32f0736494d287b9f2412af4854f91a6/OsmAnd/src/net/osmand/plus/development/SettingsDevelopmentActivity.java#L210  ;)

**Comment by sonora** [comment] 2019-11-09 19:24
Let's maybe use the same date format `SimpleDateFormat("yyyy-MM-dd  HH:mm")` so we are consistent?

**Comment by Dima-1** [comment] 2019-11-09 19:32
What about local time settings with AM/PM ?If you don't use it anywhere I will change code.

**Comment by sonora** [comment] 2019-11-09 19:36
I just checked, I guess we can leave it for now. We use the ISO yyyy-MM-dd forma to e.g. create file name consistency and proper sorting (e.g. for recorded tracks), and also in the dev plugin (because that's for debugging, it does not matter). Elsewhere we use localized date format, so should be fine.

**Comment by Dima-1** [comment] 2019-11-09 19:46
I just checked, too. Came to the exactly same conclusion.

**Comment by sonora** [comment] 2019-11-09 20:12
Cool, I have merged it, thanks!

**Comment by vshcherb** [comment] 2019-11-13 15:39
2nd step to display it in the menu item (before the dialog item)

**Comment by vshcherb** [comment] 2019-11-13 15:40
Or could be "Day till 17:21" or "Night till 09:23"

**Comment by sonora** [comment] 2020-01-05 08:46
While we are at it: Looks like a layout change was recently introduced for the screenshot posted by Dima-1 above: In recent builds the second line of the dialog option "Sunrise/sunset", indicating the actual sunrise/sunset time, is now half cut off (visible is only the upper half of the second text line). At least on some of my devices (possibly depends on the system font size selected, have not investigated).

**Comment by vshcherb** [comment] 2020-01-06 23:50
@sonora please share screenshot if possible, we should fix it

**Comment by sonora** [comment] 2020-01-14 22:34
Here it is (System Font style is Default, System Font size is Large):

![Untitled](https://user-images.githubusercontent.com/845735/72388436-3d014600-3726-11ea-91a5-501f88eee7dd.png)

I do not think I overlooked this when I first tested and merged the fix in November on this very device, so I think it must have been caused by a subsequent change to the dialog xml or similar.

**Comment by vshcherb** [comment] 2020-01-15 14:33
Anyway we consider to move out it from this dialog and put it as extra line on Configure Map screen.

**Comment by vshcherb** [comment] 2020-01-27 16:39
![image](https://user-images.githubusercontent.com/1042025/73194145-00711980-412c-11ea-9a6c-4caef8283261.png)
![image](https://user-images.githubusercontent.com/1042025/73194151-0404a080-412c-11ea-9649-1cc981a699a3.png)

**Closed** 2020-01-29 16:33 UTC
