### ISSUE TITLE
Some issues with our Germany map download names

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15273] opened 2022-09-11 19:02 UTC
1. **Berlin:**
It looks like we combine the German states "Berlin" and "Brandenburg" in one map download, which OsmAnd under "All downloads" correctly reflects as "Germany Brandenburg, Berlin".

2. But under Germany's Standard map we offer on the top level a separate "Berlin" map, so that when a user selects all maps we offer on the state level for Germany, Berlin would be covered twice?

3. **Bremen:**
For the German state of "Bremen" we offer no separate download. Seems like we combined "Bremen" into the download for "Lower Saxony". I guess we should rename that download to "Grrmany Bremen, Lower Saxony"?

**Comment by vshcherb** [comment] 2022-09-12 14:57
Bremen is broken and it should be fixed similar as we did with Berlin / Brandenburg.

![telegram-cloud-photo-size-4-5834608073006758285-y](https://user-images.githubusercontent.com/1042025/189687152-41164400-fdfa-4d44-bf99-dab5d666f6bf.jpg)

**Comment by sonora** [comment] 2022-09-12 17:24
Regarding "_No issue with Berlin covering twice_", it became quite difficult for a user to find out what needs and needs not downloading if you want a gapless coverage but no overlap. Examples:
- **Monaco** seems to be part of the _France - Provence-Alpes-Cote-d'Azur_ download
- **Gibraltar** seems part of the _Spain - Andalusia_ download

but
- **Andorra** requires separate downloads (Standard maps as well as contour lines, hilllshades etc.)
- also **San Marino** requires all separate downloads.

I guess we should probably name all combined downloads consistently to reflect the combination in the name, and in our UI under "All Downloads" _remove all entries which would actually have an overlap with a combined download_. Philosophy being that if you download different files from the same level (list) of the "All downloads" UI page, you would never download any overlap (I think that's what most people would expect).

**Comment by xmd5a2** [comment] 2022-09-13 09:07
Problem with Bremen is in fact that it is admin_level=4, same as Lower Saxony within which it is located geographically. There are 37 admin_level=6 regions is Lower Saxony. It is now is divided artificially by large cities surrounding territories. We can't combine Bremen translations with some subregion translations about that.
![Screenshot_2022-09-13_11-52-34](https://user-images.githubusercontent.com/5829014/189859058-139e374c-6bc5-4fd8-bac4-ed545eb79f3a.png)
May be we can redo it and add 37 subregions
![Lower_Saxony,_administrative_divisions_-_nds_-_colored svg](https://user-images.githubusercontent.com/5829014/189859331-a2f54f72-60ee-424c-bda4-973240dcacdb.png)

**Comment by xmd5a2** [comment] 2022-09-13 09:26
Germany in OsmAnd is already divided into there German political states. Issue is in lower level regions, especially in Lower Saxony. Upper level states are huge in size and hence we can't combine any of them.

**Comment by sonora** [comment] 2022-09-13 17:26
Well, repeating myself, on the Germany top level
- we combine Berlin with Brandenburg, but still offer a separate Berlin download on that top level.
- conversely, we do not combine Bremen into Lower Saxony, but do not offer a separate Bremen download either.

Just wanted to make sure we cover everything gaplessly, but without offering any overlapping downloads on one and the same list screen in our download UI.

**Comment by sgjf4g4** [comment] 2022-09-14 15:12
Maybe it would help if i try to clarify the issue here. I can confirm by 100% what @sonora is reporting. It seems like its not that clear for @xmd5a2 .
@xmd5a2 You wrote "Problem with Bremen is in fact that it is admin_level=4, same as Lower Saxony within which it is located geographically."
Bremen and Lower Saxony have both the same status in germany. Both are **different** states like @sonora tried to explain by posting the link to https://en.wikipedia.org/wiki/States_of_Germany
So yes, they have both same level.
That Bremen is located geographically inside of Lower Saxony does not change anything in at the State. A state in Germany dont loose its state-status only because its located inside an other State.

@xmd5a2 You wrote "Germany in OsmAnd is already divided into there German political states."
That is what it should be. Its not at the moment. Or if you think that its already, then why cant any user using OsmAnd download the **state Bremen**? It should be listed in the Regions section in Germany but its not there.

@xmd5a2 You wrote "Germany in OsmAnd is already **divided** into there German political states."
That is what it should be. Its not at the moment. The word **divided** include the meaning, that its not included into any other map. You say, that "Germany in OsmAnd is **already divided** ". What you write here is by fact wrong and the map download section in OsmAnd prove it wrong, because if what you write were correct, then there wont be "Brandenburg, Berlin". Providing one file with two states with a **","**  between the state is **not** division. Its a combination. This combination is wrong. Thats 50% of the reason why this bug is been opened by @sonora . 

Take a look at this (i searched for a map that is as clear as possible i hope):
https://www.deutschland-ferien.net/files/bundeslaender-deutschland.gif
You see Bremen, Hamburg and Berlin as different States.

And from an other wording perspective that include only one half of this bugreport:
Germany have 16 political states. @xmd5a2 You wrote "Germany in OsmAnd is already divided into there German political states." Why are there only 15 files listed for download in the Region section in OsmAnd? Please add the missing file.

**Comment by vshcherb** [comment] 2022-09-14 22:19
@xmd5a2 we had old solution for Bremen which clearly was not the best. I think we solved it better with Berlin. In that sense we should not include Bremen in Lower Saxony.
Here we have separate issue that Brandenburg is not split by region but Lower Saxony is.
So we could offer probably "Surrounds of Bremen and Bremen" as a subregion of Lower Saxony which will include Bremen as well, but we still need to offer Bremen as top level. In that case  "Lower Saxony" -> "Lower Saxony, Bremen"

**Comment by sonora** [comment] 2022-09-15 07:37
So it looks like there are 2 actionable improvements(?):

(1) Rename the current download "Lower Saxony" to "Lower Saxony, Bremen", **and include the Bremen area in it** (it currently has a hole!). The split on its child download screen, which offers a separate  "Free Hanseatic City of Bremen", can remain as is.

(2) We leave on the top level the already combined "Brandenburg, Berlin". But we move the currently also on the top level separate "Berlin" download to its (new) chlid level? And there for consistency we should also create a separate "Brandenburg" download which has the Berlin hole ?

**Comment by vshcherb** [comment] 2022-09-16 11:34
(2) we can't correctly create holes in the map and it's not convenient to use.

We shouldn't take any responsibility of having homogenous division, i.e. 1) we shouldn't intend to divide to same admin_level all regions (including Germany), we should split by approxim size 2) we could combine some neighboor states  and not combine other states, i.e. provide Berlin but not provide separate Brandenburg though provide "Brandenburg, Berlin".

Though we should **always give proper region names**, so for combined regions we should display both names  via "," .

**Comment by sgjf4g4** [comment] 2022-09-17 17:23
This is a technical explanation. This should not be used for reasoning why something is done some way.

OsmAnd should target regular users. And i think this is already the goal. They dont know anything about the issues that creating "holes" into a map is hard or any other things like that.
When a country is been split into its states, then this should be consistent. 16 single states = 16 single files.
Just like @xmd5a2 told "Germany in OsmAnd is already divided into there German political states." - this is how it should be. Its sadly not the case right now and because of that this bugreport have been opened by a person. There should be 16 files - each file containing a state. And just only this one state should be inside this file. Not some randomly created files containing some state-mixtures that can be only explained to technical people.

**Comment by vshcherb** [comment] 2022-09-18 14:02
In order to avoid any political discussions / decisions we think to move out from Naming states or territories so it will be possible to download certain area, so if you select that you would like to have Brandenburg downloaded you will have Berlin as well extra it will be purely technical. 

Names and number of files then will be hidden from user completely.

**Comment by sonora** [comment] 2022-09-18 15:56
But there needs to be a "real world" transparency to know which maps you have on your device. I can hardly think of anything better than to use political region names and  boundaries?

**Comment by vshcherb** [comment] 2022-09-18 20:44
@sonora that doesn't mean you wont have bigger files downloaded, so even if we display that you have Bremen downloaded physically it could be a bigger region

**Comment by sonora** [comment] 2022-09-18 20:49
That's fine, I think. I'm just just saying if users intend to travel to "Country X", or "Province Y of Country Z", it needs to be clear what you have to download so you do not end up with a gap or misssing map.

**Comment by ivanPyrohivskyi** [comment] 2022-10-28 12:21
Need to test after maps generation.

**Closed** 2022-11-08 11:47 UTC
Labels: map-data
