### ISSUE TITLE
Incomplete TTS routing announcements 

### ISSUE THREAD

**Issue by bonanza123** [osmandapp/Osmand#3162] opened 2016-10-09 17:02 UTC
I am using the fdroid version of osmand (which is 2.4.7 at the moment) and I'm noticing incomplete routing announcements. I tried to reproduce this and enabled the developer plugin and chose test sound 4.4 and captured the [this log](https://gist.github.com/bonanza123/ae1ab3e5cf77311dc7668a9b5a8e3997). 

The line

```
I/net.osmand(20470): AbstractPrologCommandPlayer Speak files [, then , and arrive at your destination , Town Hall]
```

shows exactly the words I can also hear, but the remaining parts of the announcement are lost. The same fragment I also hear e.g. for the german TTS.

**Comment by sonora** [comment] 2016-10-25 10:05
Just to clarify: Your are talking about line 132 of the log, right? The first half of the statement is in line 131. Are you saying you cannot hear that? I cannot reproduce this ...

**Comment by bonanza123** [comment] 2016-10-25 10:47
@sonora thanks for having a look at it. Yes, its line 132. I only hear ", then , and arrive at your destination , Town Hall" the remaining part is missing.

As you can't reproduce it, is there any way I can provide more information about it? E.g. by means of a debug version?

**Comment by sonora** [comment] 2016-10-25 11:10
I am a little at loss what could be wrong here ... Is prompt 4.4 the only one which fails, or are there other ones of the test buttons failing similarly?

What device are you using, what is its Android language (locale) setting (German?), and what voice guidance output setting in the OsmAnd General settings (Media output?).

Does it always fail, also on repeated attempts, or sporadically? Is there a pause as it if processes the first half o, but silently, or does the second half of he prompt start rather immediately?

Do you have another TTS engine on your device you could try? When you try the English recorded voice, how does that behave?  Thx - Hardy

**Comment by bonanza123** [comment] 2016-10-28 06:50
There are multiple which fail, but some are working fine others do not work at all.
For example these work fine: 1.1 1.2 1.3 1.4 2.1 2.2 2.3 2.4  5.1 6.4 7.1 7.5 7.6 7.7 8.1 8.2  8.3 8.4 8.5 9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 10.1 10.2  10.3 10.4 
Not at all working are (completely silent): 3.1 3.4 3.6 4.1 4.3 5.2 5.3 6.1 6.2 6.3  7.2 
Partly working in the brackets is only the part I hear: 3.2 (then bear right) 3.3 (then) 3.5 (then bear left) 4.2 (then) 4.4 (see above)  7.3 (arrive at your intermediate destination) 7.4 (arrive at your destination) 

My impression is that the part that is related to relative distances (e.g "do something in 100m") is not working.

My locale is German, but I tried EN and DE TTS with the same result. Audio output is set to "Like Media/Music".

The issues occur always and are 100% reproducible. My girlfriend has the same phone with same issues. There is no pause: I click and 4.4 and I immediately hear the part "then then ...".

I've tried also with [espeak](https://play.google.com/store/apps/details?id=com.reecedunn.espeak) and it has the same issues.

The recorded sounds seem to have another issue: The apps hangs (android asking for force close) when I click on any testing sounds. I don't hear anything.

**Comment by sonora** [comment] 2016-10-28 18:57
Ok, thanks. So what fails is exactly all commands or command portions which involve our
`private Term street(CommandPlayer p, String name)`.

Looks to me like somehow a peculiarity of your ROM... Also weird that recorded sounds do not play at all.

No good idea for now. I assume you are using a stock ROM developed for your hardware, and the latest updates available for it (and not some ported or 3rd party ROM ?)

**Comment by bonanza123** [comment] 2016-10-29 08:18
Thanks for the effort you put in this.
Most likely you are right and its a ROM-related issue. However, I would like to - if possible - investigate it further such that I can report it to the ROM devs. Is it possible to get a debug build for that purpose? I already tried to pull the code from the r2.4 branch and build it, but that failed.

I also noted that e.g. MAPS.ME works fine for me regarding TTS announcements but I really don't want to change to it.

**Comment by sonora** [comment] 2016-10-29 10:21
I think debuggable is set to true for all nightly builds you can download from our web site.

Let me copy @vshcherb on this, maybe he has another idea. It would be interesting to get to the root of this. Chances are your ROM has some issue with the media/Prolog command player implementations.

**Comment by bonanza123** [comment] 2016-10-30 16:12
I captured a new log from a nightly, please see [here](https://gist.github.com/bonanza123/8504e7bd6b3f3e8be851dfd01e251a1a)

There are several VFY warnings and errors but I'm not sure whether they are really the culprit here. Thanks a lot for your help in advance!

**Comment by vshcherb** [comment] 2016-10-30 16:39
@sonora 
This line indicates that somethings went really wrong in Prolog engine. 
```
[[turn(left,voice(['','Broadway',''],'')),turn(left)], then, [turn(right_keep,100.0,voice(['','',''],'')),turn(right_keep,100.0)], [and_arrive_destination('Town Hall'),and_arrive_destination]]
AbstractPrologCommandPlayer Speak files [dann , dann haben Sie Ihr Ziel , Town Hall, erreicht 
```
As you see only couple of words are spoken and no numbers at all.

**Comment by vshcherb** [comment] 2016-10-30 16:49
I just took as an example first line and I'm very confused how it was generated?
```
[turn(left,voice(['','Broadway',''],'')),turn(left)]
```
In our file we have 
```
turn(Turn, Dist, Street) -- ['after.ogg', D, M, ' '| Sgen] :- distance(Dist, dativ) -- D, turn(Turn, M), turn_street(Street, Sgen).
```
https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/de/ttsconfig.p#L257

Though array wouldn't match it. 
I guess same applies to
```
[and_arrive_destination('Town Hall'),and_arrive_destination]]
```
We should have only one instance I think.

**Comment by vshcherb** [comment] 2016-10-30 21:33
I was wrong this should be normally handled by https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/de/ttsconfig.p#L344, so why we don't see dann haben Sie Ihr Ziel I have no idea.

**Comment by sonora** [comment] 2016-10-31 11:01
My guess: We are looking at a ROM with a somehow flawed Prolog implementation.

Would closer investigate once we see more occurrences of this, but recommend we close the issue for now?

**Comment by bonanza123** [comment] 2016-10-31 11:24
[here](http://www.jenseitsderfenster.de/2014/03/23/osmand-lernt-deutsch/) is a post that mentions that error already two years ago on a nexus s phone (in german, see update 2)

**Comment by sonora** [comment] 2016-10-31 12:26
Something I don not understand, but it may be unrelated, is why your log file mostly shows two lines for each command added in the command builder, the second one witht the last argument being omitted. In the case of commands which fail for you, this last argument is always the `voice(...) `portion.
```
D/net.osmand(15322): CommandBuilder Adding command : route_new_calc [150.0, 230]
D/net.osmand(15322): CommandBuilder Adding command : route_new_calc [150.0]
D/net.osmand(15322): CommandBuilder Adding command : route_new_calc [1350.0, 3680]
D/net.osmand(15322): CommandBuilder Adding command : route_new_calc [1350.0]
D/net.osmand(15322): CommandBuilder Adding command : route_new_calc [3700.0, 7320]
D/net.osmand(15322): CommandBuilder Adding command : prepare_turn [left_sl, 1520.0, voice(['','',''],'')]
D/net.osmand(15322): CommandBuilder Adding command : prepare_turn [left_sl, 1520.0]
D/net.osmand(15322): CommandBuilder Adding command : turn [left_sh, 450.0, voice(['','Hauptstraße',''],'')]
D/net.osmand(15322): CommandBuilder Adding command : turn [left_sh, 450.0]

```

**Comment by sonora** [comment] 2016-10-31 13:05
@bonanza123  It really looks like maybe your system uses the second set of commands it often generates, i.e. the ones with the last argument missing. (And when this does not fit any pattern, silence would be produced.) When you play e.g. prompt 1.1, do you actually hear the full prompt including length and time ("The trip is 150 meters, time is 4 minutes")?

**Comment by bonanza123** [comment] 2016-10-31 13:35
@sonora yes, for sound 1.1 I hear "The trip is 150 meters, time is 4 minutes" completely

**Comment by bonanza123** [comment] 2016-10-31 13:51
I captured another log (this time for non-TTS / recorded sounds which do not work at all because when ever I trigger a test sound the app hangs and doesn't put any sound), please see [here.](https://gist.github.com/bonanza123/a668351caacb73a4057fde5aad02f828)

I'm just posting it here because I thought that both problems maybe have the same root. Here is an excerpt of it:
```
I/InputDispatcher( 9287): Application is not responding: Window{a65cbd78 u0 net.osmand.dev/net.osmand.plus.development.TestVoiceActivity}.  It has been 5006.3ms since event, 5006.0ms since wait started.  Reason: Waiting because the touched window has not finished processing the input events that were previously delivered to it.
I/WindowManager( 9287): Input event dispatching timed out sending to net.osmand.dev/net.osmand.plus.development.TestVoiceActivity.  Reason: Waiting because the touched window has not finished processing the input events that were previously delivered to it.
I/Process ( 9287): Sending signal. PID: 10807 SIG: 3
I/dalvikvm(10807): threadid=3: reacting to signal 3
I/dalvikvm(10807): JNI: CheckJNI is off
I/dalvikvm(10807): ; workarounds are off
I/dalvikvm(10807): ; pins=0
I/dalvikvm(10807): ; globals=367
I/dalvikvm(10807): 
I/dalvikvm(10807): 
I/dalvikvm(10807): DALVIK THREADS:
I/dalvikvm(10807): (mutexes: tll=0 tsl=0 tscl=0 ghl=0)
I/dalvikvm(10807): 
I/dalvikvm(10807): "main" prio=5 tid=1 SUSPENDED
I/dalvikvm(10807):   | group="main" sCount=1 dsCount=0 obj=0xa5a31ca8 self=0xb7c418d0
I/dalvikvm(10807):   | sysTid=10807 nice=0 sched=0/0 cgrp=[no-cpu-subsys] handle=-1224761004
I/dalvikvm(10807):   | state=S schedstat=( 26166639742 2254711996 9738 ) utm=2419 stm=197 core=1
I/dalvikvm(10807):   at alice.tuprolog.Struct.getTerm((null):~-1)
I/dalvikvm(10807):   at alice.tuprolog.Struct.resolveTerm((null):-1)
I/dalvikvm(10807):   at alice.tuprolog.Struct.resolveTerm((null):-1)
I/dalvikvm(10807):   at alice.tuprolog.Term.resolveTerm((null):-1)
I/dalvikvm(10807):   at alice.tuprolog.Term.unify((null):-1)
I/dalvikvm(10807):   at alice.tuprolog.Prolog.unify((null):-1)
I/dalvikvm(10807):   at alice.tuprolog.Library.unify((null):-1)
I/dalvikvm(10807):   at alice.tuprolog.lib.ISOLibrary.atom_chars_2((null):-1)
I/dalvikvm(10807):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(10807):   at java.lang.reflect.Method.invoke(Method.java:515)
I/dalvikvm(10807):   at alice.tuprolog.PrimitiveInfo.evalAsPredicate((null):-1)
I/dalvikvm(10807):   at alice.tuprolog.StateGoalEvaluation.doJob((null):-1)
I/dalvikvm(10807):   at alice.tuprolog.Engine.run((null):-1)
I/dalvikvm(10807):   at alice.tuprolog.EngineRunner.solve((null):-1)
I/dalvikvm(10807):   at alice.tuprolog.EngineManager.solve((null):-1)
I/dalvikvm(10807):   at alice.tuprolog.Prolog.solve((null):-1)
I/dalvikvm(10807):   at net.osmand.plus.voice.AbstractPrologCommandPlayer.execute(AbstractPrologCommandPlayer.java:218)
I/dalvikvm(10807):   at net.osmand.plus.voice.CommandBuilder.execute(CommandBuilder.java:263)
I/dalvikvm(10807):   at net.osmand.plus.voice.MediaCommandPlayerImpl.playCommands(MediaCommandPlayerImpl.java:80)
I/dalvikvm(10807):   at net.osmand.plus.voice.CommandBuilder.play(CommandBuilder.java:257)
I/dalvikvm(10807):   at net.osmand.plus.development.TestVoiceActivity$2.onClick(TestVoiceActivity.java:260)
I/dalvikvm(10807):   at android.view.View.performClick(View.java:4451)
I/dalvikvm(10807):   at android.view.View$PerformClick.run(View.java:18446)
I/dalvikvm(10807):   at android.os.Handler.handleCallback(Handler.java:733)
I/dalvikvm(10807):   at android.os.Handler.dispatchMessage(Handler.java:95)
I/dalvikvm(10807):   at android.os.Looper.loop(Looper.java:136)
I/dalvikvm(10807):   at android.app.ActivityThread.main(ActivityThread.java:5001)
I/dalvikvm(10807):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(10807):   at java.lang.reflect.Method.invoke(Method.java:515)
I/dalvikvm(10807):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
I/dalvikvm(10807):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:613)
I/dalvikvm(10807):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm(10807): 
```

**Comment by vshcherb** [comment] 2016-11-06 20:56
Looks like a bug in Prolog interpreter, though it works on other phones and first time we hear about it. May be it is one language? Does recorded voice works for you ?

**Comment by bonanza123** [comment] 2016-11-06 21:12
@vshcherb thanks for your response. No, recorded voice does not work (please see the log in my previous post which is from recorded voice)

**Comment by vshcherb** [comment] 2016-11-06 21:16
I seriously feel bad about that issue but it looks like it is not under our control. Even if we decide to change all Prolog languages it will take a lot of time. 
We need to investigate it internally, if one of our developer will get it in a reproducible way we can run experiments to replace prolog engine or debug it or do something with it, for now I'm afraid we a little bit stuck.

**Comment by sonora** [comment] 2016-11-24 16:47
Unclear what can be done here.

**Closed by sonora** 2016-11-24 16:47 UTC
Labels: Observed
