### ISSUE TITLE
Opening links via OsmAnd does not bring the location on map

### ISSUE THREAD

**Issue by psamim** [osmandapp/Osmand#4486] opened 2017-09-26 17:02 UTC
Hi,

I am using Osmand 2.7.5 on Android 8.0. I use offline maps, have `OSM Live` enabled, and use OsmAnd (offline) navigation service.

When there is a link like https://osmand.net/go?lat=32.627926&lon=51.664024&z=17 , Android asks for an app to open the link. When opening the link with OsmAnd it is expected to bring the location (like the Web) or navigate to it, but nothing happens and OsmAnd opens normally.

Thanks,
Samim

**Comment by FTABoy** [comment] 2017-09-26 17:51
i have same issue on android 6, when we share a location using share button and then "Send" result make this link : 
پارک تندرستی
Location: geo:35.71751,50.96721?z=16
https://osmand.net/go?lat=35.71751&lon=50.96721&z=16
when i click this link and open it using osmand+ , the share location wont show on osmand offline map. 
regards.
FTABoy

**Comment by FTABoy** [comment] 2017-10-01 09:04
duplicated as refrenced here: https://github.com/osmandapp/Osmand/issues/4297
the problem is with links starting with httpS , links with http works good.

**Comment by vshcherb** [comment] 2017-10-01 09:27
Fixed and going to be released in 2 weeks

**Closed by vshcherb** 2017-10-01 09:27 UTC
