### ISSUE TITLE
Enhance fullscreen mode

### ISSUE THREAD

**Issue by N2ZLC** [osmandapp/OsmAnd#13946] opened 2022-03-17 19:29 UTC
# 🚀 Enhance fullscreen mode

### Description

Ability for users to hide the Android status bar while using the app.

### Describe the solution you'd like

Although users can enable fullscreen mode via...

Menu -> Configure profile -> General settings -> Fullscreen mode.

...it does not hide the Android status bar—only OsmAnd map buttons.

Selecting Fullscreen mode should hide the Android status bar. The code would be something like...

```java
getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);
```

And to disable fullscreen mode...

```java
getWindow().addFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);
getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
```

**Comment by scaidermern** [comment] 2022-03-18 07:28
Duplicate of #2551?

**Closed** 2022-03-18 11:44 UTC
