### ISSUE TITLE
Multiplying lanes in "lane assist"

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#15120] opened 2022-08-19 22:16 UTC
Please review the following screen. The road does not have this many lanes.
Had it twice. Checked OSM and the lane count seems correct in both places.
Could not reproduce with simulation.
This may be related to #14613 and #15118 - note that the route takes a shortcut between two footpath bridges. Both errors are not easy to reproduce in simulation
The screenshot made in Helsinki. The start and end points of the route were:
Start: https://www.openstreetmap.org/#map=19/60.23087/25.07648
End: https://www.openstreetmap.org/#map=19/60.15116/24.91658
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/27214784/185714070-0f8ae8ec-db82-4030-999f-30f96ff8c410.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

OsmAnd 4.2.7 on Xiaomi Mi 9T Pro running Android 11.

**Comment by vshcherb** [comment] 2022-08-23 08:25
This issue is related to Osmand Live very likely, can you make backup of live files?

**Comment by mdykierek** [comment] 2022-08-23 09:18
I am not using OsmAnd Live abroad. Even in Poland, only where I live and make most edits in OpenStreetMap - Silesia.

**Comment by Zirochkabila** [comment] 2022-08-23 10:28
Tested on version 4.2.7 - could not reproduce. As you can see in the screenshot - is displayed three directions by lanes, as well as the route runs exclusively on the highway.
Yes, you wrote about what failed to play in the navigation simulator, but how to do it without the use of simulation navigation is not clear.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/186135798-f277c971-009d-4238-9cdf-3c46ca5ae21e.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by mdykierek** [comment] 2022-08-23 10:56
Navigation is a dynamic process. It is affected by GPS errors, deviations on route etc.
This causes re-calculation and one of the bugs mentioned above is only reproducible with live navigation.
Please notice my previous comment:
> This may be related to #15118 - note that the route takes a shortcut between two footpath bridges. Both errors are not easy to reproduce in simulation.
I don't know. Maybe a wrong float comparison makes it merge two lanes or nodes together, maybe it reads wrong number of records due to some wrong index calculation. Note that the directions are not a simple concatenation of real and fake lanes. Right turn is overwritten by straight. Maybe it will be enough to fix 15118 and this one will disappear.

**Comment by vshcherb** [comment] 2022-08-24 13:42
Do you have duplicate maps downloaded i.e. overlapping ?

**Comment by mdykierek** [comment] 2022-08-24 18:28
If you mean having both whole Finland and it's regions, then no. I had only regions (all of them).
If you mean, regions overlapping - I can't tell as I don't have insight what is in OBFs, but Helsinki and Katowice (where I had it) are not on edges of the maps.
I can also tell, that in Katowice I went the intersection several times and had it only once.

**Comment by pieleric** [comment] 2022-08-27 10:12
Hi, as an extra "data point", I think I have seen both issues recently (in the last month), with a dev build.
Especially, the "shortcut" issue has been happening quite a few times. I *think* it happens when doing route recomputation on the fly (sometimes triggered just due to losing GPS connection for a short while and getting a very unprecise position when getting back the GPS signal). You can trigger it more easily by adjusting the auto-route-recomputation to a very small distance (eg 10 m).

**Comment by pieleric** [comment] 2022-08-27 10:13
Hi, as an extra "data point", I think I have seen both issues recently (in the last month), with a dev build.
Especially, the "shortcut" issue has been happening quite a few times. I *think* it happens when doing route recomputation on the fly (sometimes triggered just due to losing GPS connection for a short while and getting a very unprecise position when getting back the GPS signal). You can trigger it more easily by adjusting the auto-route-recomputation to a very small distance (eg 10 m).

**Comment by Zirochkabila** [comment] 2022-08-30 13:25
>

When using the recalculate every 10m, still can not be reproduced - three lanes are displayed, and the route is built exclusively on the road

**Comment by mdykierek** [comment] 2022-08-30 13:39
And to be on the same page - using simulation or real navigation?

**Comment by vshcherb** [comment] 2022-08-30 17:18
On screenshot also another bug is visible that 1 segment is not going correctly on the road geometry.
@Zirochkabila do you use fixed speed simulation? realistic? 

Looks like the bug is related to route recalculation so you need to have "GPX with noise" . 
@mdykierek do you have recorded GPX?

**Comment by Zirochkabila** [comment] 2022-08-30 18:33
> 
A realistic speed simulation was used on the section of the road indicated in the issue.

However, testing on a similar road (under realistic conditions) with a route re-routing value of 10 km gave the same result.

**Comment by mdykierek** [comment] 2022-08-30 21:12
No I don't have a recorded GPX, but I have another route I can try daily. Actually, today I had the following wrong lanes and off-road segment.
This is with Live updates enabled. Tomorrow, I will try with Live updates cleared and disabled.
![1661893842923](https://user-images.githubusercontent.com/27214784/187543923-b3bf76a7-13d0-4599-82f0-6318908cdace.jpg)

**Comment by mdykierek** [comment] 2022-09-05 16:44
I have a couple of inputs.

1. The issue is unlikely to be related to "Live updates". It happened to me with all scenarios i.e. with Live updates enabled, disabled and cleared on the region level, and disabled entirely.
2. It is very likely to be associated with "shortcut" issue.
3. Although it is triggered by automatic route re-calculation, the short interval actually caused it to happen less frequently or was harder to spot. After returning to 100 meters, I had the following situation again.

First it went "off road" and then wrong lane assist appeared (September 2022 maps for Silesia, Poland - NO Live updates)
![1662396004210](https://user-images.githubusercontent.com/27214784/188490811-aeacccd7-ef5f-4fbc-becc-5b6ef3da70b0.jpg)
![1662396004206](https://user-images.githubusercontent.com/27214784/188490841-92c76701-d904-4ab7-9e77-be4a6ab93784.jpg)
![1662396004202](https://user-images.githubusercontent.com/27214784/188490848-f3edbf3a-1457-4bd5-8a3b-b67571f5323a.jpg)

**Comment by vshcherb** [comment] 2022-09-06 17:47
@mdykierek every trip osmand by default records a track, you can share it private via support email, so we can "simulate your real trip", otherwise we're simulating without real data and likely we will fail to reproduce

**Comment by mdykierek** [comment] 2022-09-06 20:08
Will do. Seems to be consistent.

**Comment by mdykierek** [comment] 2022-09-07 15:46
GPX and associated screens sent to support.

**Comment by Zirochkabila** [comment] 2022-09-08 10:45
Thank you, we received your GPX

In version 4.2.7 the following checks were made:
1. Navigation by GPX (without attaching to the road)
2. Navigation on GPX (with road attached)
3. Navigation on route without using GPX
4. Navigation with route recalculation after 10 meters
5. Navigation with route recalculation after 100m
Cannot reproduce - the lanes are displayed according to the actual data (checked in Street View and Mapillary), and the route is built along the road.

**Comment by vshcherb** [comment] 2022-09-08 15:55
We need to simulate location using Given GPX and start normal navigation as mentionned.

**Comment by Zirochkabila** [comment] 2022-09-09 08:23
Three scenarios were tested:
1. With simulation of the position without attaching to the road (120m recalculated)
2. With position simulation with attaching to the road (120m recalculated)
3. With position simulation with attaching to the road (10m recalculated

**Don't reproduce.**

**Comment by mdykierek** [comment] 2022-09-11 17:07
> With simulation of the position without attaching to the road (120m recalculated)

Please note, that once you change the default, it is not possible to set it back to 120. Once modified it can be set to 100 or 200 with the slider.

**Comment by vshcherb** [comment] 2022-09-20 14:27
Merged to https://github.com/osmandapp/OsmAnd/issues/15118

**Closed by vshcherb** 2022-09-20 14:27 UTC
