### ISSUE TITLE
Offline Routing generates not optimal route due to penalty_transition

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#1468] opened 2015-07-15 08:20 UTC
The generated route, in certain areas, regularly generates a wrong turn then a u-turn, even though on some occasions it routes correctly through the same area.
![screenshot_2015-07-01-06-27-03](https://cloud.githubusercontent.com/assets/13037960/8693923/bb1c06fc-2ad2-11e5-96e2-f90f0a964bbd.png)
![screenshot_2015-07-02-19-16-41](https://cloud.githubusercontent.com/assets/13037960/8693924/be8ba86a-2ad2-11e5-9676-b70fe02642b0.png)
![screenshot_2015-07-10-16-04-03](https://cloud.githubusercontent.com/assets/13037960/8693930/c38f9af6-2ad2-11e5-9254-2323f42b7028.png)
![screenshot_2015-06-28-13-06-39](https://cloud.githubusercontent.com/assets/13037960/8693933/c9753796-2ad2-11e5-89c4-a50aa0cb436b.png)

Moving choosing a start or finish that is only a bit further up the same road can give different results, but always the same results.

Try:

Start:
lat="54.5350864" lon="-1.56678"

Finishes:
lat="54.5466598" lon="-1.5560266" - bad
lat="54.544521" lon="-1.55987" - good
lat="54.5605546" lon="-1.5677008" - good
lat="54.549787" lon="-1.5478172" - good
lat="54.5455709" lon="-1.5586762" - bad

**Comment by Norbert80** [comment] 2015-07-16 21:48
@Goodign thanks for reporting. Could you please provide coordinates of that round about where the error occurs. Please also edit your comment above and enter notes to each finish if it leads to good or bad result.

**Comment by Goodingn** [comment] 2015-07-17 06:09
Thanks, updated with results.

R/bout is located: 54.53767, -1.55643

In this example the roundabout could be described as being in the middle of the route, but not sure on some of the other examples.  They were probably much closer to the destination- I just happened to catch them as I was being directed.

**Comment by Norbert80** [comment] 2015-07-19 09:32
@Goodingn: Please verify and correct you coordinates. The finish coordinates are identical with the first start coordinates.

**Comment by Norbert80** [comment] 2015-07-19 09:42
@vshcherb: I have visualized a bad route with last finish of @Goodingn 's list:

https://graphhopper.com/maps/?point=54.535086%2C-1.56678&point=54.53767%2C-1.55643&point=54.545571%2C-1.558676&locale=de&layer=Lyrk

Therefor I have forced GraphHopper to route over the round about. You can see that the round about is approximately in the middle of the route.

This indicates that this could be the "bidirectional meeting bug". If you agree, please set this one as duplicate of issue #1195.

**Comment by Norbert80** [comment] 2015-07-19 09:47
@Goodingn: Please...

- Enable OsmAnds Debug Plugin
- Go to the settings of the Debug plugin
- Please deactivate 2 phase routing (check the second check box)
- Try if this fixes the problem and report here

**Comment by Goodingn** [comment] 2015-07-19 12:24
Corrected co-ords- copy and paste error.  Start was ok, Fin1 was a duplicate of Start.

**Comment by Goodingn** [comment] 2015-07-19 12:33
Disabling complex/2 phase routing hasn't affected the problem- it still makes that diversion.

**Comment by Norbert80** [comment] 2015-07-19 13:14
@vshcherb your support is required here. Does disabling 2 phase routing require a restart to take  effect?

Could you please investigate further?

**Comment by Goodingn** [comment] 2015-07-19 13:39
I disabled 2 phase, exited, killed the osmand task, launched osmand anew, checked 2 phase was still disabled with a tick, entered the start and finish points and it still mis-routed.

**Comment by vshcherb** [comment] 2015-07-23 22:14
>> Does disabling 2 phase routing require a restart to take effect?
Should not.

I'm currently very busy with server issues downloads etc, unfortunately takes longer than I planned. I definitely will go through the list of all issue (actually will be good to provide some kind of sorting, to start with most prioritized), but I'm not sure it could happen next week either.


Looking in the screenshots it looks that something is really blocking some ways, so I suspect the problem in the data. Because the distance is short, I don't think 2 phase routing is used at all!

**Comment by Goodingn** [comment] 2015-07-24 05:39
Thanks. This is likely not a data issue, because moving the destination up and down on the same road affects whether this junction is routed correctly or not. If it was a data issue I'd expect it to always route incorrectly.

**Comment by vshcherb** [comment] 2015-07-24 06:48
I know that most likely won't happen, the only correct way to test is to use MapCreator http://download.osmand.net/latest-night-build/OsmAndMapCreator-main.zip, because it shows the split of  segments timing on each and the function it tries to minimize in the logs.

**Comment by xmd5a2** [comment] 2015-07-24 07:21
Here output from MapCreator with problematic roundabout:
'	<segment id="44752404" start="1" end="0" time = "2.4800456" rtime = "0.0" name = "Whessoe Road" distance = "31.00057" turn = "Turn right" turn_angle = "82.46377" start_bearing = "114.09443" end_bearing = "114.09443" description = "Turn right and go 49,05 meters" />
	<point  direction="clockwise" highway="mini_roundabout" direction="clockwise"/>
	<segment id="44752402" start="0" end="1" time = "1.4443002" rtime = "0.0" name = "Whessoe Road" distance = "18.053753" start_bearing = "86.7603" end_bearing = "86.7603" description = "" />'

**Comment by vshcherb** [comment] 2015-08-04 22:01
Now we could call it a known issue. It is actually related to https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L205 (if we lower these values to 260 or we comment the whole section, the issue will be gone).
So what happenned the optimatization of penalty_transition is not *compatible* with A* bidirectional algorithm.  If we change it to onedirectional https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L18 (=1), then issue will be gone as well.

Unfortunately, I don't see a solution yet, because this optimization is very important but it is not clear what to do in these cases.

**Comment by Goodingn** [comment] 2015-08-05 05:19
Thanks for looking into this. Just to make sure you're looking in the right area for this problem, have you appreciated the routing gives predictably differing results if the end (or start) position is moved by relatively small distances, up and down the same road, such that to a human the routing should involve no change in navigation steps?

**Comment by vshcherb** [comment] 2015-08-05 15:14
Yes, that's why it is an engine issue. Engine should output the same result all the time and it does ! with 1 directional A* algorithm (which is slower for long distances). With bidirectional A* algorithm, it evaluates from both ends and that penalty transition will be included if it is a backward search and excluded if it is not. 

The main issue is that routing time varies (!) if you do A* from the end point or you do A* from the start point, of course that conflict gives weird result. Why we don't see it very often, because for long distances there is no such issue and forward and backward meets somewhere in the middle on highway.

3rd,4th screenshot is a different issue, reported here as well, but it requires a different fix. So this is only about described coordinates.

**Comment by hakuchi** [comment] 2015-10-03 20:18
@Goodingn do you have set your routing region to GB,India;Australia?

**Comment by Goodingn** [comment] 2015-10-06 12:48
Yes, set to 'UK, India, Australia & Others'.

**Comment by Goodingn** [comment] 2016-02-24 12:00
Did this get given up on?  In a built-up area it's hard to rely on navigation because of this.

**Comment by vshcherb** [comment] 2016-02-29 00:06
Not given up we don't have enough resources to fix all the issues. That issue is still open.

**Comment by Goodingn** [comment] 2016-08-13 14:58
There must have three major releases since this was logged, each with sizeable new features developed. It makes me sad that a bug in the core function of the app - routing - doesn't get looked at, because there supposedly aren't enough resources.

**Comment by vshcherb** [comment] 2016-08-13 16:49
Fixed

**Closed by vshcherb** 2016-08-13 16:49 UTC
Labels: Offline Routing

**Comment by utack** [comment] 2016-08-13 16:51
Did it make it into 2.4 or will it be in a bugfix release?

**Comment by vshcherb** [comment] 2016-08-14 22:07
It will be 2.4.4 around next week
