### ISSUE TITLE
OsmAnd Online GPS Tracker flooding Telegram Chat

### ISSUE THREAD

**Issue by gbschenkel** [osmandapp/OsmAnd#20823] opened 2024-09-12 16:53 UTC
### Description

Since the last upgrade, the Tracker appears to loose information of the last message/map posted, and each time it is going to update it, it creates a new one.

When driving, the Tracker flood Telegram chat with map messages, I already changed the behavior to only send Map(no text) and still it send flood, appears it lost the reference to the message posted and send a new one, thinking the message is expired. Maybe the API communication has changed on Telegram side. I don't know if is related but few times I saw the `Status` in `My location` tab show as error.

After the second time the App is opened(force shutdown and open again) this error start showing
```
Error 400: Server name must be non-empty.
```
Already tried to disable Energy Management, but appears it didn't affected.

Until it is fixed or I can resolve it, I ain't able to continue using the App.

### Steps to reproduce

Install OSMAnd+ from F-Droid.
Install OSMAnd Online GPS Tracker from Google Play Store.
Optional: Install Telegram.

### Actual result

Flooding chat with many Geo Location Map posts while the time selected is not ended.

### Expected result

Only 1(one) post while the elapsed time is not ended.

### Your Environment (required)

```
OsmAnd Version: 4.8.5
OsmAnd GPS Tracker: 1.0 (17 Jul 2024)
Android/iOS version: 14.0 (05 Aug 2024)
Device model: OnePlus 10 Pro 5G (NE2213)
```

**Comment by yuriiurshuliak** [comment] 2024-09-13 14:28
This seems to be the expected behavior. Based on earlier observations, continuous movement on the map triggers frequent location change notifications.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/93bb1fdc-3a93-4fce-9006-390ccbb4e5c2"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment] 2024-11-18 16:21
Looks like bug was fixed on Telegram side

**Closed by vshcherb** 2024-11-18 16:21 UTC
