### ISSUE TITLE
Random double U-turns 

### ISSUE THREAD

**Issue by pordini** [osmandapp/OsmAnd#17026] opened 2023-04-23 14:13 UTC
Sometimes Osmand suggests double U-turns (or similar multiple turns to go straight) while it's just a straight road and route.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/12774050/233844542-2d607d2b-a545-49af-b7ef-83f449e74365.png"  width="300" height="auto"/> </th>
  </tr>
</table>  
(Sweden, Murjek, BD810)

It happens randomly, as far as I can tell. The double u-turn in the screenshot only appeared after recalculation, before that there was no instruction here, just going straight.

Using OsmAnd+ 4.4.7, released: 2023-04-10

**Comment by mikehgentry** [comment] 2023-04-23 15:43
You don't have multiple overlapping maps do you (e.g. a region, and a country that encompasses that region, or the same area but both full and roads only)?

If so, try disabling (or even deleting) the duplicates - there's been some suggestion that overlapping maps can cause glitchy navigation.

**Comment by pordini** [comment] 2023-04-23 15:50
No, sorry. I only have one map of Sweden. Or from any other country, for that matter. And I'm using the offline Car routing.

![Screenshot_20230423-174622](https://user-images.githubusercontent.com/12774050/233849965-ed8aae87-ebc7-4450-bd5c-a8d3ace444c4.png)

**Comment by mikehgentry** [comment] 2023-04-23 16:21
Do you have live updates? If so, try disabling that

**Comment by pordini** [comment] 2023-04-23 16:26
Live Updates were not active, I had bad experiences with those in the past.

**Comment by Zirochkabila** [comment] 2023-04-24 13:02
@pordini Not reproduced - try reinstalling the application (or download the night version at https://osmand.net/docs/versions/nightly_versions) and re-download the maps.
Just in case, make a local backup file

**Comment by vshcherb** [comment] 2023-06-04 16:52
Probably already fixed with GPX navigation

**Closed by vshcherb** 2023-06-04 16:52 UTC

**Comment by Zirochkabila** [comment] 2023-06-22 16:06
@pordini Please send the location coordinates

**Comment by pordini** [comment] 2023-06-22 16:11
Oh sorry I thought I had done.

49.04623° N, 22.17450° E

**Comment by Zirochkabila** [comment] 2023-06-23 08:59
@pordini I'm not able to reproduce it yet - we will monitor user requests to get more information.
However, I've seen a similar situation on iOS devices https://github.com/osmandapp/OsmAnd-iOS/issues/2953, so it's possible that the problem exists.

**Comment by pordini** [comment] 2023-06-25 10:30
I had another one today so I actually went back and drove the same bit again. Didn't happen the second time..
![Screenshot_20230625-105628](https://github.com/osmandapp/OsmAnd/assets/12774050/7956f29f-f27a-4de3-90da-d1741064a4ae)
![Screenshot_20230625-110351](https://github.com/osmandapp/OsmAnd/assets/12774050/f21a221f-8f64-401f-8b81-62a7dfb75120)

**Comment by pordini** [comment] 2023-06-25 10:33
Next time I see it (and it is safe to do so) I will trigger a route recalculation before I reach the u-turn instruction.
