### ISSUE TITLE
Japanese cities have their names shown in another language

### ISSUE THREAD

**Issue by asereze** [osmandapp/Osmand#3738] opened 2017-05-03 12:05 UTC
On the map that's what I see in Japan, even if I have "Local Names" in the settings. I guess that's Chinese, even if I'm not sure about that.

Device: Xiaomi Redmi Note 4x
OS: Lineage OS 14.1 - Android 7.1.1
Locale: Sardinian (sc)
Version: OsmAnd~ 2.6.3

![photo_2017-05-03_14-01-46](https://cloud.githubusercontent.com/assets/11271324/25659663/153da6e4-3009-11e7-9ed2-c647c5e11f8e.jpg)

![photo_2017-05-03_14-01-41](https://cloud.githubusercontent.com/assets/11271324/25659671/1e37a92a-3009-11e7-8acc-64b494a8625d.jpg)

**Comment by vshcherb** [comment] 2017-05-06 10:12
The city names are displayed with system language. If it is English, they are displayed in Eglish (if there is no english name then it tries to transliterate them).

**Comment by xmd5a2** [comment] 2017-05-09 14:37
Looks like these names are transliterated (mostly wrong)
http://dictionary.hantrainerpro.com/chinese-english/translation-dongjing_tokyo.htm

**Comment by asereze** [comment] 2017-05-09 17:32
Ah, ok, thank you for the explanation. I have a suggestion, then. Could the "name:ja_rm" values be used, instead? It would be more appropriate in the Japanese case.

**Comment by radry** [comment] 2017-05-11 15:15
I can confirm this bug. If using offline vector maps and the map language is set to anything except local names, japanese names will be translated as if they were chinese. EVEN THOUGH "transliteration" is turned OFF. This bug is extremly annoying.

**Comment by eindgebruiker** [comment] 2017-06-29 18:28
This is a duplicate of #1396

**Comment by vshcherb** [comment] 2019-12-19 16:15
Merged to #6292

**Closed by vshcherb** 2019-12-19 16:15 UTC
Labels: Observed
