### ISSUE TITLE
Roundabout shortcut ignored by OSMAND car navigator

### ISSUE THREAD

**Issue by Jevgenij** [osmandapp/Osmand#4585] opened 2017-10-14 12:13 UTC
OSMAND algorithm will always ignore a left turn shortcut of a roundabout if one exists.

Examples
lat 49.50 lon 5.95
![screenshot_2017-10-13-11-57-04](https://user-images.githubusercontent.com/2399026/31575495-beeff0b0-b0e8-11e7-8ab4-b33c68121e33.png)

The second
![screenshot_2017-10-13-18-01-04](https://user-images.githubusercontent.com/2399026/31575492-b253b472-b0e8-11e7-9e61-b8621c5adf6f.png)

and the third

https://osmand.net/go.html?lat=47.978947&lon=-4.124305&z=18

**Comment by klic** [comment] 2017-10-14 19:04
As I'm the source of the third example, here is the routing image: [https://lichtenwalder.name/roundabout.jpg] (as  seem to not being able to attach a picture, here's a link)

**Comment by scaidermern** [comment] 2017-10-15 09:27
The way ignored in the first example is a highway=unclassified (https://www.openstreetmap.org/way/188215407). I think this is the wrong class, they way should be tertiary instead (as the way it is coming from: https://www.openstreetmap.org/way/385080086). Here OsmAnd prefers tertiary + primary over unclassified, which is correct.

Not sure what the cause in the second example (https://www.openstreetmap.org/#map=19/49.25486/3.97142) is. Is there a penalty for `junction=roundabout`? If not this could be the problem.

For the third example the weighting of `trunk_link` (e.g. https://www.openstreetmap.org/way/4043185) could be the problem, i.e. the weighting it is too low. However I'm unsure if the tagging is correct and whether this way should be promoted to `trunk` instead.

**Comment by majkaz** [comment] 2017-10-16 09:18
Just a confirmation - the same problem is here https://www.openstreetmap.org/#map=17/48.99015/14.48377 - routing from any direction, where the "shortcut" is possible does ignore the links and routes on the roundabound. 
As a note - the secondary_links might be mislabeled and might be correctly primary_links, but it still should make difference only going from the southwest (E55 to I/157).

**Comment by PaulStets** [comment] 2018-01-11 15:37
@scaidermern I completely agree that the questionable tagging may be the reason for many of these issues. For example, here (second case) https://www.openstreetmap.org/way/138608513#map=18/49.25550/3.97086 the road has the maxspeed tag, while the neighboring link has no speed restriction, therefore OsmAnd chooses the roundabout. 
@majkaz This seems to be a real issue and needs further investigation.

**Comment by PaulStets** [comment] 2018-01-12 14:59
Fixed with https://github.com/osmandapp/OsmAnd-resources/pull/479

**Closed by PaulStets** 2018-01-12 14:59 UTC
