### ISSUE TITLE
only "Brows Map" profiles possible in local language in new OsmAnd 3.5.5 of 28-11-2019

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#8019] opened 2019-12-01 08:30 UTC
I'm using multile profiles. Yesterday the new 3.5.5 was rolled out to my phone. I'm using OsmAnd in the Dutch language.
I removed all profiles and created new ones.
Whatever I do upon creating a new profile, the "Base profile" is always a "Browse map" profile even if I select "Car" or another from the top spinner, which means that I can't set navigation settings. I can select the navigation profile "Car", but as the base profile only stays "Browse map", I can't slect navagation options.

Only when using the English language as "Display language" I can create other car profiles.

Combined with this: The app is now in English, but  if I rotate my phone, it is back in Dutch.
But now, in Dutch, having English set as my app language, I can create other profiles and the base profile stays on "car". 

I reported the "after rotation back to system language" error before (Some OsmAnd strings switch back from changed locale to default phone locale upon rotation in #6695), but now the combination does "weird" things with the app profiles.

**Edit:** The general "App profiles" screen stays in Dutch, but the sub-screens are in English. I assume the main screen does not look at the settings, but at the device locale.

**Comment by vshcherb** [comment] 2019-12-03 18:50
Probably we need to make this setting Global if can't make it working for Profile based logic

**Comment by hvdwolf** [comment] 2019-12-04 17:56
It is worse. I have a slightly adapted car profile and a more heavily adapted "car+caravan" profile.
The car profile has (should have) 125 km/hr max. speed, the car+caravan 90 km/hr.
This worked real fine in the 3.5.3.
However, now in 3.5.5 when saving the 90 km/hr for the caravan, the first car profile now has 90 km/hr as well.
When changing the car profile back to 125 km/hr, the caravan profile is changed to 125 km/hr as well.

So I took the routing.xml and made a mycar.xml and mycaravan.xml, where I only took the header data and the car profile where I limited the max. speed to 90 km/hr on beforehand in the mycaravan.xml.
Both on these profiles I created a "base profile: car" based on the mycar profile, and did the same for the caravan on the mycaravan.xml (using profile<routingProfile name="caravan" baseProfile="car" .....> ).
Still they only use one max. speed.

Then I opened the mycaravan.xml and changed the profile part to <routingProfile name="caravan" baseProfile="caravan" ...> (they were complete copies anyway).
However, my "<routingProfile name="caravan" baseProfile="caravan" ...>" is not in the list of base profiles to choose from (which is probably logicical as it is not in the original Routing.xml)
When I select Car again as base profile I can select my new caravan profile.
When setting max. speed to 90 km/hr, my car profile is also set back to 90 km/hr.

It is totally unusable right now (and not very well tested so it seems).
Fortunately my caravan holiday will not start before April 2020.

Next to this: I use a heuristic_coefficient of 1.3 for my "derived" profiles.
However, the real base profile from OsmAnd, who should use 1.0, is now using the same HC as my derived profile.

**Comment by vshcherb** [comment] 2019-12-16 18:09
Yes, we're just going to fix that issue and make all these settings independent from each other.

**Comment by hvdwolf** [comment] 2019-12-21 17:21
I have seen Chumva's commit. I tested the nightly build. All settings seem to be separate now.

Only one thing: If I have a "mycar.xml" in routing with a HC of 1.3. The main routing.xml also uses the 1.3. I have to delete the "mycar.xml" to make OsmAnd use the default HC of 1.0 again.

Second observation: I now created a mycar13.xml and a mycar15.xml, where the first uses uses an hc=1.3 and the second an hc=1.5 and copied those into routing (of the Nightly build).
I made a car profile based on the mycar13.xml with the hc=1.3, but NOT a profile for the hc=1.5 (I only left that file also in the routing folder).
All profiles use the hc=1.5. 
Are these files read alphabetically and is OsmAnd simply using the latest hc it reads?

For me this is not a big thing at all, as I normally only use hc=1.3, but it is not correct.

**Comment by Chumva** [comment] 2020-01-06 15:52
Issue #6695 should be fixed soon here https://github.com/osmandapp/Osmand/pull/8184. Could you add sample files mycar13.xml, mycar15.xml and tell where you check heuristic_coefficient?

**Comment by hvdwolf** [comment] 2020-01-06 18:38
I set the heuristic coefficient in the top of the file and in the profile itself.
See 4 samples: the small ones only containing the necessary changes, and the extended ones where I simply copied the entired car profile and modified the heuristic coefficient values.


[mycar-profiles.zip](https://github.com/osmandapp/Osmand/files/4027343/mycar-profiles.zip)

**Comment by hvdwolf** [comment] 2020-02-04 09:41
Is there any update on when this gets available in the next (bug fix) release?
In the mailing list we see more issues of users now finding out that using "the brand new" profiles "breaks" a lot of things. This also results in completely incorrect routings and ETAs as speeds are also mixed up between car, bicycle and pedestrian profiles.
The severity and thereby priority of this bug is increasing as more users discover the profiles.

**Comment by Chumva** [comment] 2020-02-04 15:29
Profiles speeds were fixed here - 32b3f24865dde701daa76b67f2d9b1de62bc36d2. Only "Browse Map" profiles possible in local language and bug with heuristic_coefficient weren't reproduced and probably needs further investigation.

**Comment by Chumva** [comment] 2020-02-04 15:42
Can you provide additional info on how it happens or route coordinates?

**Comment by vshcherb** [comment] 2020-02-04 15:43
@hvdwolf if you can still reproduce it please let us know. This bug supposed to be fixed this week if we have enough information. I hope to cooperate so we can fix it faster

**Comment by hvdwolf** [comment] 2020-02-06 19:18
@Chumva As mentioned a couple of posts higher up (21Dec), I confirmed that it works fine. Since then I downloaded 7~10 nightly builds and found no regressions.

@vshcherb 
Sorry. Took a bit longer to test and react. Two extremely busy days at work. 
Profiles work work fine now as far as I can see. I tested and tried many options, but I'm also sure I didn't touch the full 100% of options.
The heuristic_coefficient "bug" is still there (2020-02-06 nightly build) and some users use that. I'm afraid I'm the one who spread that around in the mailing group.
99.5% (or more?) of the users are not in this mailing group and will have no knowledge of it.

**Comment by Chumva** [comment] 2020-02-06 19:37
Can you please add test route, coordinates, or even video how it reproduced with your custom routing profiles?

**Comment by hvdwolf** [comment] 2020-02-07 10:39
To really see the difference I calculate from "Hoefslagmate, Zwolle" to  "SchwarzwassertalStraße 2, Riezlern, Österreich", a route of 816 km (my "approximate" home address to my wintersport Gästehaus").
I do this with nothing in the routing folder "/android/data/net.osmand.dev/files/routing" (equal for net.osmand.plus). 
The route calculation takes forever. After 2-3 minutes it is still far from ready.
Then I copy my  "mycar15.xml" (see attached and renamed as mycar15.xml.txt as I can't attach .xml files) into "/android/data/net.osmand.dev/files/routing". 
[mycar15.xml.txt](https://github.com/osmandapp/Osmand/files/4170267/mycar15.xml.txt)
I open Osmand nightly again and create an additional "mycar 1.5" profile having the exact same settings as the default car profile, apart from the heuristicCoefficient="1.5" value.
If I now calculate the same route it calculates it in 18-20 seconds, for both the standard CAR profile as well as my "mycar 1.5" profile. Stopping/starting OsmAnd and even rebooting doesn't change this. As long as the mycar15.xml is in the routing folder, it takes that heuristic_coefficient.


Additionally: There is an alphabetic ordering in reading this files. If I put in a "zycar20.xml" in there with a heuristicCoefficient="1.1" value (despite the name), it will now take the heuristicCoefficient="1.1" value for all profiles thereby now also overruling the mycar15.xml profile.

**Comment by pebogufi** [comment] 2020-02-07 10:45
@hvdwolf 
Please have a look on my test results about the "revert".
There is a mysterious bug.
https://github.com/osmandapp/Osmand/issues/8304

**Comment by vshcherb** [comment] 2020-02-10 17:10
The original bug is not reproducible though we've got what could be wrong with #8304

**Closed by vshcherb** 2020-02-10 17:10 UTC

**Comment by Chumva** [comment] 2020-02-17 14:14
@hvdwolf 
Custom and default routing should work fine after this request - 
https://github.com/osmandapp/Osmand/pull/8462  
Bug with heuristicCoefficient happened due to attribute set inside osmand_routing_config which changed the default value for the whole config.

Please test it :-)

**Comment by hvdwolf** [comment] 2020-02-19 15:07
There is a good separation now in the heuristic coefficients as well.
The standard car profile with hc=1.0 "takes forever" ;), especially with routes over 300 km.
My modified 1.3 and 1.5 profiles are indeed much faster, with 1.5 (logically) the fastest.
I could not find other mix-ups or regressions either.
As far as I'm concerned the ticket can be closed.
Thanks a lot!
(the nightly build already mentions it is a 3.6 version)

**Comment by hvdwolf** [comment] 2020-02-19 15:52
I know. That is also why I mentioned "version stamped" in quotes. But if you open the nightly build, the splash screen is already in 3.6 mode.
You can only create a new release inside github on the releases page. At that moment a certain commit is coupled to that created release version.  So you have to do some "tricks" just before a release and when you are ready for release, you build the apk on that "frozen" release/commit state.

**Comment by vshcherb** [comment] 2020-02-19 18:18
Tonight 3.6.0-beta should have it and builds as well
