### ISSUE TITLE
Search results data

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd#6363] opened 2018-12-15 13:36 UTC
When looking for a village, instead of showing the distance from the nearest city, which is not informative, it is better to show in what region the village is situated.
![image](https://user-images.githubusercontent.com/40493090/50043560-ff437100-007e-11e9-9450-d7d47431c8bd.png)
This is how it would be better.
![image](https://user-images.githubusercontent.com/40493090/50043561-079bac00-007f-11e9-8f18-4d58369338c5.png)

**Comment by jfburke3** [comment] 2018-12-16 00:40
Yes!  YES!

Promote this from "Nice to Have" to "REALLY REALLY HELPFUL AND NECESSARY!"

While the arrow and distance information provided is occasionally helpful, it is too often not enough.

When I am in Atlanta, Georgia, and searching for the place Ruskin in Florida, the first 6 or 8 or so results are other places called Ruskin, and I have to guess which one is the one I want.  It is always a hit-or-miss situation.

**Comment by littlehelper** [comment] 2019-01-30 22:20
Sounds similar to the proposal in #4174.

**Comment by scaidermern** [comment] 2022-03-30 08:23
Duplicate of #2993.

**Closed** 2022-04-02 12:35 UTC
Labels: Nice to Have
