### ISSUE TITLE
Number of lines does not match the OSM data

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7426] opened 2019-08-15 10:18 UTC
At this point: 44.995934,20.207544 OsmAnd displays 6 lines, while there are no more than only 3 of them.

**Comment by vshcherb** [comment] 2019-08-15 17:08
Is OsmAnd live enabled?

**Comment by BrackoNe** [comment] 2019-08-15 17:16
Yes of course!

**Comment by scaidermern** [comment] 2019-08-17 20:52
Duplicate of #7304 and #5003.

**Comment by xmd5a2** [comment] 2019-09-17 06:36
Duplicate of https://github.com/osmandapp/Osmand/issues/7518

**Closed by xmd5a2** 2019-09-17 06:36 UTC
