### ISSUE TITLE
App size not modified after maps storage modifications

### ISSUE THREAD

**Issue by belgianGeek** [osmandapp/OsmAnd#13040] opened 2021-10-22 17:15 UTC
### Description
I have some maps on my phone (~ 3GB) and I moved them long ago from the internal storage to my SD card to save some space. I noticed that the app size didn't decreased, staying at roughly 3.1GB.

As I was really running out of space on my phone's internal storage, I deleted all my user data and saw there that the app size decreased to ~187MB. When I downloaded my maps again, after selecting my SD card as default storage in the app introduction, I observed that the app size stayed the same.

TL;DR
The app size do not decrease when you modify your maps location from internal to external storage, whch could eventually cause storage issues to end users.

### How to reproduce?
1. Download some maps and import them on your internal storage
2. Modify your maps location with the built-in app menu to store them on an external storage
3. App size should decrease by the maps size but stays the same

### Your Environment
OsmAnd Version: 4.0.7
Android/iOS version: Android 9
Device model: Nokia 5 (TA-1024)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

1. Belgium (standard map) - 01/10/2021
2. France Ile-de-France (standard map) - 01/10/2021
3. France Normandy (standard map) - 01/10/2021

**Comment by scaidermern** [comment] 2022-11-05 18:06
Duplicate of #6590?

**Closed** 2022-11-07 15:15 UTC
Labels: Observed
