### ISSUE TITLE
Export / Import of favourites.gpx corruption

### ISSUE THREAD

**Issue by Boothy99** [osmandapp/OsmAnd#20805] opened 2024-09-10 14:16 UTC
### Description

Having two devices (Google Pixel 6 phone & Samsung Galaxy Tab S4) I frequently export my (phone) favourites & import to the tablet (after deleting all favourites & restarting there first).

Recently, I noticed that the favourites.gpx file size had become smaller than the last export(s), even though I'd added numerous POI'S / notes, and deleted nothing. All exports for this file have been incrementally larger (if I've added to the POI's etc) each time I've saved them as a backup (previously the last "largest" was 1.96 MB, but now is 1.58 MB).

In addition to this, I noticed that if I import the (recent "smaller") favourites.gpx to my tablet, the groups icons and colours have been corrupted. Icon group colours become generally yellow, and icons are either incorrect or a default (not what I'd previously set).

If I delete all favourites (from the tablet) then import an older (but larger file size), favourites.gpx backup, then all is good + icons and colours are correct.

I've mentioned this in a recent post (which I'll delete if this confuses matters), here
https://github.com/osmandapp/OsmAnd/issues/20799#issue-2515826223

As a test, I exported my favourites from the older android tablet, hoping it might be something to do with android 14 on my phone. However, the same issue occurs from my tablet export (android 10) - file size becomes "reduced" and importing this results in a corrupted set of Favourites again.

The "older / larger 1.96 MB" favourites.gpx that works correctly when imported was from **11-08-24**.

The "recent / oddly smaller 1.58 MB" favourites.gpx that appears corrupted was saved on **8-09-24**

### Steps to reproduce

* Open OsmAnd / My Places / My Favourites
* Using "Share" - save to folder (or email file)
* Import the favourites.gpx to 2nd device (having first deleted all favourites from the device & restarted OsmAnd).

### Actual result

Importing the favourites.gpx results in POI icons being changed to a default icon for each group, and their respective colours revert to yellow (in general).

### Expected result

Exporting then importing to a second device should result in identically matching POI groups / icons & colours.

### Your Environment (required)

**Google Pixel 6**
Device : oriole
Brand : google
Manufacturer : Google
Model : Pixel 6
Product : oriole
Build : AP2A.240905.003.F1
Version : 14
App Version : OsmAnd+
Apk Version : 4.9.0 4900

**Also occurs on Samsung Galaxy Tab S4 ...**
Device : gts4lwifi
Brand : samsung
Manufacturer : samsung
Model : SM-T830
Product : gts4lwifixx
Build : QP1A.190711.020.T830XXU5CVG2
Version : 10
App Version : OsmAnd+
Apk Version : 4.9.0 4900

**Comment by sonora** [comment] 2024-09-10 14:30
It sounds like this may be a result of the commit referenced in **(3b)** here https://github.com/osmandapp/OsmAnd/issues/19892#issuecomment-2317065794, in combination with several "_Favorite / Waypoint import not correctly applying group / category appearance_" issues reported.

I believed them all to be fixed, but maybe there is still a gap somewhere. Do you run the latest beta version (or nightly) on the device you are importing to? Fix would only be in 4.9beta and up, I think.

**Comment by Boothy99** [comment] 2024-09-10 16:04
![Uploading Screenshot_20240910-170214.png…]()

![Uploading Screenshot_20240910-170230.png…]()

**Comment by Boothy99** [comment] 2024-09-10 16:08
![IMG_20240910_170735](https://github.com/user-attachments/assets/d675bb48-cbe3-4031-bd48-8c4b2ab1d1ca)

![IMG_20240910_170753](https://github.com/user-attachments/assets/1ea62fe6-12d8-4c1a-ba04-9dc52e6a7b69)

**Comment by Boothy99** [comment] 2024-09-10 16:09
Hope that helps?

**Comment by sonora** [comment] 2024-09-10 16:15
Thanks @Boothy99 !

- I have briefly  tested "_opened with" OsmAnd / import as Favourites_ and that also reproduced the appearance correctly.

- Also, your file looks correct, it correctly contains the group appearance, it seems. 

- So now, the only difference between our 'experiments' seems that I have exported/deleted/re-imported to the same device (always killing/re-starting the app between steps), and you use a different device. I will fabricate a file with changed group names to test. Or if you want, you can post your gpx file and I can quickly try on my device, perhaps that would give the final hint what's wrong here ... ;)

**Comment by Boothy99** [comment] 2024-09-10 17:13
Well .... 🥺 (looking for a very embarrassed emoji) .... I honestly can't believe this 🤔

I got home ... deleted all favourites from the tablet: 
closed OsmAnd .... then .... 
added "clear cache" for OsmAnd app.

Imported via Favourites interface ... and all was well (apart from comment below) !! Colours & icons correct. So ... I deleted them again, and clicked the exported file as I normally do, and again ... all looked well. How embarrassed am I feelingly ... VERY. I can only **apologise enormously**, @sonora !!! Sorry for time wasted 😪

N'.B.
Only issue that remains is when I choose a Custom colour as mentioned here -
https://github.com/osmandapp/OsmAnd/issues/20799#issue-2515826223

Solid colours seem to save, just not custom colours .... but that's another issue 🤨 

Again .... many, many apologies.

**Comment by sonora** [comment] 2024-09-10 17:25
It's not a problem, please don't worry! :wink: I was busy with something which cause periodic waits, so testing this fell beautifully in the gaps there...  :wink:

So let's watch this a bit, to see if it re-appears. Perhaps it is something strange, like a timing thing: I understand that the app saves these appearance changes to backup files, which it will e.g. start creating soon after an import. If your POI collection is huge (I have just tested one of mine with~20,000 points), this can take a while. If I kill the app prematurely, it has the points in its database all right, but not their appearance in the incomplete files. It will silently recover from this, but use default appearance instead. (a goldish yellow for favorites).

Potentially also your other issue may be caused by this (so far this is only a suspicion). Please try to wait a minute or so for good measure before killing the app to restart, then check. Perhaps that fixes it...?

**Comment by sonora** [comment] 2024-09-10 17:29
Closing this, please add comments if it re-appears.

**Closed by sonora** 2024-09-10 17:29 UTC

**Comment by Boothy99** [comment] 2024-09-10 18:03
Thanks @sonora ... I appreciate your patience and understanding whilst I feel a right plonker (even though I'd reproduced it a number of times, previously 😕). 

I'll certainly keep in mind your reference to waiting a while after import before closing OsmAnd down, as my favourites do have a large collection of ~ 60 groups with gawd knows how many individual points & text notes.... a lot of data collected over many years use (if only there was a "Select All" for when I'm cleaning out 60+ groups on the tablet 😉).

I'll keep my eye on things too 👍 

Many thanks again and for closing this one 🥴
Dave.

**Comment by sonora** [comment] 2024-09-10 18:37
I have now opened an issue about the missing "Select all" on the My Favorites screen, something which is eating my life tine at tines, too... Thanks for reminding me! 😢

**Comment by Boothy99** [comment] 2024-09-10 21:57
> I have now opened an issue about the missing "Select all" on the My Favorites screen, something which is eating my life tine at tines, too... Thanks for reminding me! 😢

Yayyyyyyyyy  ..... that will save sooooo much of my (& everyone's) time. Woohooooo !!! Thanks and looking forward to that button appearing 😊
