### ISSUE TITLE
There are occasional gaps in navigation

### ISSUE THREAD

**Issue by petersohn** [osmandapp/Osmand#8433] opened 2020-02-10 21:41 UTC
Sometimes, while navigating, OsmAnd fails to show the next turn, but instead shows a later turn as the next. While this is happening, it also doesn't show the correct lanes to take where I should not turn. Everything else seems to work normally, there is no recalculation going on, distances are showed correctly, and the blue bar is also correct.

It happened to me two times recently. The first time everything worked normally while travelling on the motorway, then it started showing that the next turn to take is a roundabout abut 10 kilometers ahead, which is correct, but it failed to show the turn where I should leave the motorway. After I passed the correct exit, it recalculated the route and everything went fine afterwards. The second time, I was travelling on a different motorway with much longer distance to the destination, and it was showing the correct turns, then I took a rest stop, OsmAnd recalculated the route and it suddenly stopped showing several of the turns I would have to take. Again, I took a wrong turn once, but then got back to the correct route before OsmAnd could recalculate again, so it continued to work wrong. But after reaching that particular turn, everything worked again.

Unfortunately, I could not reproduce the bug. I tried to program the same route into the navigation, but now it worked correctly.

**Comment by sonora** [comment] 2020-02-11 06:25
Did it perhaps happen on highways which have a frontage road, ,so the device may sometimes falsely assume you are already off the highway?

**Comment by scaidermern** [comment] 2020-02-11 06:45
Another duplicate of #8164 I guess.

**Comment by vshcherb** [comment] 2020-02-11 17:43
Looks like it is fixed with #8164, the gaps appear after route is recalculated at least once

**Closed by vshcherb** 2020-02-11 17:43 UTC
