### ISSUE TITLE
3 letter locales (hsb, kab) still not working as display language

### ISSUE THREAD

**Issue by juliannyca** [osmandapp/Osmand#3145] opened 2016-10-05 20:42 UTC
Hello! Upper Sorbian now works as map language, thanks for that! Now I'm referring to the other question about having it as display language as well. Here (https://github.com/osmandapp/Osmand/issues/2714) it was said, that Android doesn't support three-letter language codes. In the linked discussions it seems as if this question was resolved by now (https://code.google.com/p/android/issues/detail?id=106574). Now I see, that it is possible in the new version to chose Upper Sorbian as display language in OsmAnd as well. The problem is, that everything stays in English after restarting, although there are about 40 % already translated. What's the problem there?

**Comment by sonora** [comment] 2016-10-25 10:10
Victor, from what I see, this was fixed in version 1.1.0-rc1 of the Gradle plugin. Looks like we may merely have to update, once tis is productive. Our folder structure should be fine already.

**Comment by vshcherb** [comment] 2016-10-30 16:03
Sounds good.

**Comment by sonora** [comment] 2017-07-05 22:49
Looks like we are already on `classpath 'com.android.tools.build:gradle:2.1.3`.

Can anybody test if this issue has been resolved?

**Comment by juliannyca** [comment] 2017-07-06 08:51
I still see English content only when switching to hsb.

**Comment by milupo** [comment] 2017-07-06 17:19
Hi, I'm not involved in Osmandapp.

I translated Firefox for Android into Upper Sorbian and Lower Sorbian. Firefox for Android contains a language switcher and it should be shown in Sorbian from Android 5.0 on. Maybe you can include such a locale switcher in Osmandapp.

**Comment by sonora** [comment] 2017-07-16 06:40
So you are saying that on the **same** device you can see Firefox menus now in Upper Sorbian but cannot achieve this in OsmAnd, right?

**Comment by milupo** [comment] 2017-07-16 13:56
No. I want to say Firefox for Android and Firefox Focus for Android (and for iOS as well) have a locale switching feature so you can use the Firefox language instead of the OS language, Unfortunately, there is no Upper Sorbian Android so it is not possible to use the OS language as app language. You must "force" the app to use its own locale. But, to do that, the app needs a locale switching feature. So it should be possible to use the Upper Sorbian Osmand app on a German or English Android. BTW, this issue exists for all operating systems because there are no Sorbian Windows, no Sorbian Linux, no Sorbian Mac OS, no Sorbian Android and no Sorbian iOS. but for all those operating systemst applications exist that can be used in Sorbian.

Unfortunately I cannot test neither Firefox nor Osmand on my smartphone. I have an old phone with an old Android 4.0 only. But. I think Julian could test.

**Comment by sonora** [comment] 2017-07-16 19:38
OsmAnd runs ok on Android 4, but I guess And 4 may not support 3 letter language codes. The "Locale switcher", as you call it,  is built into OsmAnd, it is the General setting "Display language" (and "Map language" for names on the map if they exist). Map language has been confirmed working already, but I did not want to close this issue before also OsmAnd's menus have been confirmed to display ok in those languages?

**Comment by sonora** [comment] 2017-07-16 19:50
I have just tried myself on an Android 6.01 device and this worked flawlessly. (It did and does not work on my Android 4.4.2, looks like Android added support for 3 letter display language codes only later).

**Closed by sonora** 2017-07-16 19:50 UTC
Labels: Observed

**Comment by milupo** [comment] 2017-07-16 20:43
Yes, the three letter support is from Android 5.0.

You closed the bug report? But Julian may have the issue yet. It is his bug report.

**Comment by sonora** [comment] 2017-07-17 09:33
Yes but had since implemented the necessary support in OsmAnd and have now verified this works. The original issue is from a time when we were missing that support.

If tgere is still an issue, please open a new thread with the specifics how to reproduce.

**Comment by milupo** [comment] 2017-07-17 10:03
Yes, but Julian had the issue 11 days ago yet. But, let's wait for him.

**Comment by juliannyca** [comment] 2017-07-17 14:22
That's because I'm using an old Android version on my device. Yesterday I had the opportunity to test OsmAnd on a newer device and it works – also in Sorbian. So the issue is solved now. Thanks!

**Comment by milupo** [comment] 2017-07-17 14:54
Fine. Another piece of Sorbian software now. :-)

**Comment by sonora** [comment] 2017-07-18 06:18
Sounds like someone owes me a beer ... or whatever you guys drink. :)

**Comment by milupo** [comment] 2017-07-18 14:35
I drink mineral water, beer without alcohol, or simply a coffee.
