### ISSUE TITLE
Issue / question to enforcements

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/Osmand#3536] opened 2017-03-01 10:40 UTC
Can someone have a look at these two enforcements?
I'm wondering why there is no notification in osmand.

Is the relation processed so that osmands "knows" to which direction the enforcement belongs to?

https://www.openstreetmap.org/edit#map=20/50.40578/6.56821

https://www.openstreetmap.org/edit#map=20/52.44079/7.07284

**Comment by hakuchi** [comment] 2017-03-05 19:56
these relations are wrong.     
here you can see a correct relation: https://www.openstreetmap.org/relation/5492475
and wiki link: http://wiki.openstreetmap.org/wiki/Relation:enforcement

this is not a issue in OsmAnd

**Comment by bitboy85** [comment] 2017-03-06 14:23
Can you please have a look at it again? I've added the properties to the Relations.
Is it possible somehow to test the "new" map in osmand?

**Comment by hakuchi** [comment] 2017-03-06 16:34
[Relation](https://www.openstreetmap.org/relation/6932559) looks good, but you can delete the `name` from this relation, also the keys from this [node](https://www.openstreetmap.org/node/754456348).     
On the node is enough if you use `note=Blitzer`.

[Relation](https://www.openstreetmap.org/relation/6932260) also looks good, but same as above, you can delete the `name`. I don't know if a "Rotlichtblitzer" check the maxspeed or only the red light of the traffic signal.

On this [relation](https://www.openstreetmap.org/relation/6932249) is something missing 😉

PS: You should close this, because this is not a bug from OsmAnd! thx

**Closed** 2017-03-06 17:24 UTC
