### ISSUE TITLE
Send Group / Category of Tracks

### ISSUE THREAD

**Issue by gubrist** [osmandapp/OsmAnd#15048] opened 2022-08-09 14:17 UTC
# 🚀 feature request

### Description

I use OsmAnd+ 4.2.7

You can send a Group / Category of **favourites**

![Favourites send 1](https://user-images.githubusercontent.com/22197180/183672145-88091830-4e39-49b0-a791-6109c879c45f.jpg)

![Favourites send 2](https://user-images.githubusercontent.com/22197180/183672178-e6d81a23-e39d-40dd-9a4b-b3f24a113866.jpg)

### Describe the solution you'd like

I request to send  a Group / Category of **tracks** the same way

![Tracks send](https://user-images.githubusercontent.com/22197180/183672346-1547d40c-255d-4183-85f3-5a83af25de5b.jpg)

### Describe alternatives you've considered

Searching the Android files directory, which shows to be hidden and/or complicated.

**Comment by scaidermern** [comment] 2022-08-09 14:36
Duplicate of #5558.

**Comment by vshcherb** [comment] 2022-08-09 15:21
Please Keep in mind as well that you can export as OSF package already which accepted by other OsmAnd instance

**Closed by vshcherb** 2022-08-09 15:21 UTC

**Comment by gubrist** [comment] 2022-08-09 16:18
What is an "OSF package"?

My expectation is a device-independent *.GPX File, or some files compressed in a *. ZIP File.

**Comment by scaidermern** [comment] 2022-08-09 16:51
Actually osf is a zip file. But I understand what you are trying to say.

**Comment by vshcherb** [comment] 2022-08-09 16:58
Sharing GPX as multiple files will overload the system in most of the cases, sending as a zip file technically exactly the same as doing manual backup OSF. which could be renamed to ZIP and unzipped.
