### ISSUE TITLE
et and uk ttsconfig.p are broken

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2971] opened 2016-08-17 19:08 UTC
Two ttsconfig.p scripts in resources/voice contain errors and gen_voice.sh does not produce voice files:

```
et:
ERROR: string/2: Undefined procedure: num_atom/2
   Exception: (10) num_atom(1, _G1365) ?
   Exception: (9) string(_G1364, _G1365) ?
^  Exception: (7) setup_call_catcher_cleanup('$bags':'$new_findall_bag', '$bags':findall_loop(string(_G1364, _G1365), user:string(_G1364, _G1365), _G1375, []), _G1427, '$bags':'$destroy_findall_bag') ?
ERROR: assert/1: No permission to modify static procedure `google_gen/0'
ERROR: Defined at /home/xmd5a/git/OsmAnd-resources/voice/work/g_config.p:518
   Exception: (3) gen('g_config.p', google) ?

uk:
ERROR: atom_concat/3: Arguments are not sufficiently instantiated
   Exception: (9) string(_G1364, _G1365) ?
^  Exception: (7) setup_call_catcher_cleanup('$bags':'$new_findall_bag', '$bags':findall_loop(string(_G1364, _G1365), user:string(_G1364, _G1365), _G1375, []), _G1421, '$bags':'$destroy_findall_bag') ?
ERROR: assert/1: No permission to modify static procedure `google_gen/0'
ERROR: Defined at /home/xmd5a/git/OsmAnd-resources/voice/work/g_config.p:417
   Exception: (3) gen('g_config.p', google) ? 
```

**Comment by sonora** [comment] 2016-08-17 22:10
Both files initialize ok in OsmAnd and produce prompts. Cannot currently pinpoint the issue.

**Comment by vshcherb** [comment] 2016-08-17 22:17
The issue is in the format, something makes these files incompatible with generator normal files. It is possible that some constructions work for TTS but couldn't work for normal voice. So it is a bad practice cause we can't keep voice & tts packages in sync

**Comment by vshcherb** [comment] 2016-08-17 22:25
For generation only string(_, _) predicates matter, so I suspect that line for uk-tts https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/uk/ttsconfig.p#L385

**Comment by vshcherb** [comment] 2016-08-17 22:31
For uk I suggest that change https://github.com/osmandapp/OsmAnd-resources/commit/5d3c4eff165377ee861514e98438664f800d5d68 (which need to be tested)

**Comment by vshcherb** [comment] 2016-08-17 22:34
For et, I suspect this block. https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/et/config.p#L469. But if commented it out (it is good to try though!), then generated voicepack will be incomplete and these (decline_string) won't be used. 

Because 'et' doesn't have any former recorded it is not clear should we generate it or not.

**Comment by sonora** [comment] 2016-08-17 22:36
Really hard for me ... Original code is from Yaroslav Fedevych, but he never returned to this after the initial work in May 2015. I subsequently maintained the file together with all others, updating to include the latest features and upgrading to v103, but never touched the grammar, of course.

Similarly for Estonian.

**Comment by sonora** [comment] 2016-08-17 22:38
I suggest we go with your uk change, and comment our the line in et. We will just have to wait for issue reports, I see no other choice here.

**Comment by xmd5a2** [comment] 2016-08-18 07:33
@vshcherb still no luck with uk
```
ERROR: atom_concat/3: Arguments are not sufficiently instantiated
   Exception: (9) string(_G1364, _G1365) ? 
^  Exception: (7) setup_call_catcher_cleanup('$bags':'$new_findall_bag', '$bags':findall_loop(string(_G1364, _G1365), user:string(_G1364, _G1365), _G1375, []), _G1421, '$bags':'$destroy_findall_bag') ? 
ERROR: assert/1: No permission to modify static procedure `google_gen/0'
ERROR: Defined at /home/xmd5a/git/OsmAnd-resources/voice/work/g_config.p:422
   Exception: (3) gen('g_config.p', google) ? 
```

**Comment by sonora** [comment] 2016-08-18 23:33
Not sure I understand: The config.p file seems to be created all right, because there is a neew one in the folder? So all we need is the .ogg files, can we not produce them manually on google  for 2 languages by uploading a manually created list?

**Comment by vshcherb** [comment] 2016-08-22 12:26
config.P is a copy of ttsconfig.P though we generate voice messages directly from ttsconfig.P and that code is broken. I will take a look into it cause I couldn't find anything strange in uk file yet.

**Comment by vshcherb** [comment] 2016-08-22 14:38
Fixed

**Closed by vshcherb** 2016-08-22 14:38 UTC
