### ISSUE TITLE
String output gets garbled by utf8 characters

### ISSUE THREAD

**Issue by grinapo** [osmandapp/Osmand#1259] opened 2015-05-22 07:51 UTC
See full detail rendering at Node: 3100167388, Coordinates: 47.9922004, 18.8891429
There are two relations, one with name contains latin2 ("normal"), the other contains a crazy character (somewhere from extended codesets in unicode). Where the output is "relation1" it's okay, where the output is "relation2; relation1" both contains boxes instead of the accented characters outside ASCII range.
I try to attach an image.
![screenshot_2015-05-22-09-45-13](https://cloud.githubusercontent.com/assets/1056054/7766288/0b84365e-0068-11e5-820b-6cf1533774bf.png)

**Comment by vshcherb** [comment] 2015-05-22 09:46
We know it and this is a duplicate of another critical issue. We are working on it

**Closed by vshcherb** 2015-05-22 09:46 UTC

**Comment by grinapo** [comment] 2015-06-08 23:15
(Next time if you include the duplicate issue number it's easier to find them. Thanks.)
