### ISSUE TITLE
Maps Indexing takes ages on Android 11.

### ISSUE THREAD

**Issue by Kivasya** [osmandapp/OsmAnd#10453] opened 2020-12-22 09:37 UTC
**Importnat Note**:
Issue is identified on all devices with OsmAnd maps installed on SDCard with Android 11 and it's not reproducible on Android 10.

No more need to post information about it. All operations related to maps will be slow: indexing maps on start, searching, map rendering, etc. The issue is related to new SDCard restrictions on Android 11.

---------------

The maps are on the phone memory (not on the SD card). There are a lot of maps that are updated every month. There are: 118 maps 84 contour lines 28 hillshades Indexing all maps after calling up the app took only a few seconds under Android 10. Now on Android 11, it takes about 60 minutes (1 hour!). Since all maps are re-indexed even after each individual map has been updated, it will practically no longer be possible to update all maps in the future.

**Comment by vshcherb** [comment] 2020-12-23 18:15
This is really a lot. We actually reindex 1 map at a time, all other map information is stored in indexes.cache file (in the same older with maps) which is read everytime on restart. I wonder what's size of that file 1KB, 1MB ? 
So all indexed information is stored in indexes.cache, probably it's broken (could be deleted) or probably it is not able to be created somehow

**Comment by nickw7coc** [comment] 2021-01-02 20:01
Mine never complete indexing, I have to reboot the phone (Huawei Mate P20 Pro) every time.

**Comment by vshcherb** [comment] 2021-01-03 01:24
@nickw7coc do you use sdcard maps?

**Comment by bmurray7** [comment] 2021-01-03 01:26
@vshcherb I've observed a similar issue on my Note 20. I've configured OsmAnd to store map data on an SD card.

**Comment by nickw7coc** [comment] 2021-01-03 07:16
> @nickw7coc do you use sdcard maps?

No, they're on the phone (it has 128GB of memory, if which about half is still free.

**Comment by pebogufi** [comment] 2021-01-03 11:24
-- Since all maps are re-indexed even after each individual map has been updated, it will practically no longer be possible to update all maps in the future.

Thats the same behavior in updating LIVE maps. I have currently 15 maps in live and it is not optimal at all to index files after dnl of each file.
@vshcherb Why it is not possible to do the indexing only after dnl of the *last* file ?

**Comment by vshcherb** [comment] 2021-01-03 14:38
@pebogufi it's not the same with live maps, there are more than 15 maps that need to be reindexed + each region could have 2-3 file of updates.

**Comment by AnastasiaTiutina** [comment] 2021-01-13 13:48
Samsung phone S20 -128GB-5G
Android 11
OSMAND+ 
map storage on micro sd card from Samsung
Problem:
- It takes 5 minutes to see the map on the screen. From the start of the app (online and offline)
- Maps update is too long

**Comment by AnastasiaTiutina** [comment] 2021-01-14 10:02
OsmAnd + 3.8.4
Last map update: Jan 2021

dev: SM-G988B
Android: 11 (R), API 30
Android build number: samsung / z3sxeea / z3s: 11 / RP1A.200720.012 / G988BXXS5CTL6: user / release-keys

After updating to Android 11, OsmAnd has a deterioration in the performance .
Sometimes the app hangs when it starts and the download of maps is greatly slowed down. In addition, the indexing of the inventory cards is slowed down.

**Comment by nickw7coc** [comment] 2021-01-17 17:50
I'll make an observation here... I'm not good at wording things, so hope you follow... 
I starting updating the downloaded maps at 13:27, and looking at the phone again at 15:46 the phone was showing it was still downloading, so I went to the 'updates' screen, which showed that it was only partially updated, and it proceeded to download the rest of the file without intervention, so I left it to it, and I looked at the phone again at 17:17 and it showed it was still indexing, until I navigated to the Local list of maps screen, when the phone stopped showing it was indexing. 

Huawei Mate P20 Pro, Android 10.1.0.329, Osmand 3.8.4 released 2020-10-29

**Comment by vshcherb** [comment] 2021-01-18 00:27
Please share Logcat buffer for initialization

**Comment by nickw7coc** [comment] 2021-01-18 07:31
I have just spent 10 minutes searching for  log or cat or logcat without success...? What am I looking for, and where should I find it?

**Comment by BellHouse** [comment] 2021-01-18 10:35
I also experience the very long indexing process, since my Samsung Note 10+ received the update to Android 11 some days ago. Before, this was no issue.

Samsung Galaxy Note 10+ (SM-N975F), Android 11 build RP1A.200720.012.N975FXXU6ETLL, OsmAnd+ 3.8.4

**Comment by vshcherb** [comment] 2021-01-18 18:05
Devlopment Plugin ->  Options -> LogCat -> (I* - Info, D* - Debug, W* - Warn) -> Share

**Comment by nickw7coc** [comment] 2021-01-18 19:49
Done just now...

**Comment by nickw7coc** [comment] 2021-01-18 19:54
Just done a maps/voice files update (yet again there were the two 0.1MB
English voice files awaiting update, like there has been for about a year...

**Comment by AnastasiaTiutina** [comment] 2021-01-20 12:49
OsmAnd Does not work
Device model: Samsung Galaxy S10 / SM-G973F/DS 
Android: 11 
Kernel-Version: 4.14.113-20606340 
Android-Patch-Level: 2021-01-01 
OsmAnd type/version: OsmAnd+ 3.8.4 / 2020-10-29 
The latest maps update: I think it was in Nov 2020 (the date of the cards is 2020-10-01)

**Comment by sonora** [comment] 2021-02-11 15:29
Confirmed on Samsung Galaxy S10 and Galaxy Tab after recent Samsung stock ROM ugrades to Android 11.

**Comment by GBellinghausen** [comment] 2021-02-11 18:45
The workaround is to move the maps from SD card to the phone's memory.

**Comment by nickw7coc** [comment] 2021-02-11 19:13
My phone doesn't have a card, everything is in the device's memory.
The only way I can stop the indexing notification is, go into the app, and
navigate to the Updates tab.

**Comment by bmurray7** [comment] 2021-02-25 06:31
I've encountered this issue on my Samsung Note 10 after upgrading to Android 11. I was able to reproduce the issue on a local build from 0125820d762.

The ADB logs indicate that indexing each file on the SD card is taking tens of seconds:
```2021-02-24 20:55:09.120 25212-25212/net.osmand I/SurfaceControl: nativeRelease nativeObject e[532963592224]
2021-02-24 20:55:09.120 25212-25212/net.osmand I/SurfaceControl: release : mNativeObject = 532963601552 - Surface(name=Surface(name=af3fb4e StatusBar)/@0x3199b3 - animation-leash)/@0xfe8cc75
2021-02-24 20:55:09.120 25212-25212/net.osmand I/SurfaceControl: nativeRelease nativeObject s[532963601552]
2021-02-24 20:55:09.120 25212-25212/net.osmand I/SurfaceControl: nativeRelease nativeObject e[532963601552]
2021-02-24 20:55:21.462 25212-25976/net.osmand D/net.osmand: CachedOsmandIndexes Initializing db /storage/6239-3165/Android/obb/net.osmand/Us_ohio_northamerica.obf 18807ms
2021-02-24 20:55:33.338 25212-25976/net.osmand D/net.osmand: CachedOsmandIndexes Initializing db /storage/6239-3165/Android/obb/net.osmand/Us_north-dakota_northamerica.obf 11810ms
2021-02-24 20:56:18.550 25212-25976/net.osmand D/net.osmand: CachedOsmandIndexes Initializing db /storage/6239-3165/Android/obb/net.osmand/Us_north-carolina_northamerica.obf 45114ms
2021-02-24 20:56:54.209 25212-25976/net.osmand D/net.osmand: CachedOsmandIndexes Initializing db /storage/6239-3165/Android/obb/net.osmand/Us_new-york_northamerica.obf 35588ms
2021-02-24 20:57:09.554 25212-25976/net.osmand D/net.osmand: CachedOsmandIndexes Initializing db /storage/6239-3165/Android/obb/net.osmand/Us_new-mexico_northamerica.obf 15249ms
2021-02-24 20:57:29.673 25212-25976/net.osmand D/net.osmand: CachedOsmandIndexes Initializing db /storage/6239-3165/Android/obb/net.osmand/Us_new-jersey_northamerica.obf 20019ms
2021-02-24 20:57:38.337 25212-25976/net.osmand D/net.osmand: CachedOsmandIndexes Initializing db /storage/6239-3165/Android/obb/net.osmand/Us_new-hampshire_northamerica.obf 8559ms
2021-02-24 20:57:49.338 25212-25976/net.osmand D/net.osmand: CachedOsmandIndexes Initializing db /storage/6239-3165/Android/obb/net.osmand/Us_nevada_northamerica.obf 10921ms
2021-02-24 20:58:02.797 25212-25976/net.osmand D/net.osmand: CachedOsmandIndexes Initializing db /storage/6239-3165/Android/obb/net.osmand/Us_nebraska_northamerica.obf 13369ms
```

I used the Android profiler to trace the Java method calls: 
![image](https://user-images.githubusercontent.com/3842049/109105786-748d4080-76e3-11eb-80d4-4ac288380fe5.png)

It appears that bulk of the time is spent waiting on `fstat()`. The methods in `com.google.protobuf.CodedInputStream` make numerous small seeks when processing a file.

I hypothesize the root cause is related to the storage changes in Android 11 (see [AOSP release notes](https://developer.android.com/about/versions/11/privacy/storage)). I've seen [reports](https://www.reddit.com/r/androiddev/comments/kpn68k/android_11_very_slow_file_access_performance/gizbd8t?utm_source=share&utm_medium=web2x&context=3) of similar performance degradation in other apps.

I tried to mitigate the issue by replacing `java.io.RandomAccessFile` with a buffered version similar to [the one used Cassandra](https://github.com/facebookarchive/cassandra/blob/master/src/org/apache/cassandra/io/BufferedRandomAccessFile.java). I saw modest performance improvements, but not enough to come close to resolving this issue.

**Comment by creeper82** [comment] 2021-03-08 14:45
One more thing, I know this isn't 100% related but for me on android 10 the indexing is being done the way it should be done, it takes barely some seconds to index the maps, but.. the notification is the problem. Once in 2-3 downloads the notification saying that the area that was last on download queue is indexing... (no matter if the app is on foreground on background) And it actually is already indexed. Notification progress bar stays at 0%. Even closing the app from background doesn't help. I can either force stop the app, or (i prefer that one) open and close Map downloads and OsmAnd Live screens. And for some reason when I open Map downloads screen for the 3rd/4th time the notification just disappears. Also it happens perfectly after the loading circle stops. This is not a problem at all, there are probably more things to focus on. I'm just curious if this is a known problem.

**Comment by vorname-nachname** [comment] 2021-03-22 21:01
195 / 5000
Übersetzungsergebnisse
Hi
I had a similar problem, Samsung M51, update to Android 11, map building took forever. have changed the storage location, from sd-card / android to sd-card / osmand. No more problems.

**Comment by marscher** [comment] 2021-04-29 18:05
It is SAF making every bodies life harder. I really wonder how such a BS could be released into the wild. It seems it cannot be disabled anymore in the released version of Android11, so we do not even have a workaround available. I think we should all start complaining at Google, so eventually they enable this workaround again (Window service pack style FTW :rofl:).

https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage/

Essentially it makes file access orders of magnitude slower. And claims to do so, by improving security (which ain't true). Congrats! :angry:

**Comment by vshcherb** [comment] 2021-04-30 17:45
This issue is going to be closed in favor of https://github.com/osmandapp/OsmAnd/issues/7045. In new release OsmAnd can't target to Android SDK 30 without SAF support. 

Actually the API looks quite miserable since Android 10 and it's probably leading that OsmAnd won't be able to use sdcard / external storage anymore.

**Closed by vshcherb** 2021-04-30 17:45 UTC
Labels: Observed

**Comment by aceman444** [comment] 2021-05-02 09:19
Sorry, but it is critital to be able to use SD cards with the size of the maps currently in use.

**Comment by vshcherb** [comment] 2021-05-02 12:37
Then only solution would be to not upgrade to Android 11. This change is not driven by us (Google Android 11) and also there is almost no choice if OsmAnd needs to be updated on Google Play in future.

**Comment by pebogufi** [comment] 2021-05-02 12:56
Not long ago there was a recommandation to install osmand on **root** of a Android 11 device.
Did anyone made further tests, whether this could be the solution ?

Since a few days Samsung asks me to update my tablet S5e from 10 to 11. 
Of course I will refuse that !!!

**Comment by lefou** [comment] 2021-05-02 12:57
I installed OsmAnd via FDroid on Samsung / Android 11 (because I didn't know of that limitation before - there is no way back) and switched to `<sdcard>/osmand` directory, to work around the slow access speed. That setup works reasonable. So, dropping this feature just because _one_ (ok, a really important one) app store won't support it.

IIUC, OsmAnd _is_ build in different flavors for different app stores, so dropping this feature is probably only related to Google Play? Could you please make it clear, if that would (not) also affect FDroid users?

**Comment by vshcherb** [comment] 2021-05-02 13:04
The question is still being investigated but it's unlikely we will maintain 2 codebase, we will need to changed targetSdkVersion to 30 (Android 11) soon and probably do some code changes related to it. So it's unclear who will maintain branch with targetSdkVersion = 29. 

Certainly once you've got Android 11, then it's probably it, you will either got non-working app or slow SDCard. If you have Android 9 or earlier (Android 10 is question still), we will try to maintain codebase to get sdcard working properly.

**Comment by pebogufi** [comment] 2021-05-02 13:18
With my Samsung tab S5e android 10 i have osmand installed on
<sdcard>/Android/obb/net.osmand.plus
Everything works fine. 
Update 9 -> 10 months ago without problems.

**Comment by sonora** [comment] 2021-05-02 13:28
I also can confirm that all our current builds work just fine on Android 10 on a very wide range of devices.

The issue I hope can be solved somehow is Android 11  and in particular the google mandate for targeting SDK 30, and the ralated Android restrictions then. I hope there will be a solution, it is a potentially existential thread to our and many other apps.

**Comment by lefou** [comment] 2021-05-02 16:02
From what I've seen, current OsmAnd releases can:

1. access `<sdcard>/android/...` dirs normally when on Adroid <= 10
2. access `<sdcard>/android/...` very slowly when on Android > 10
3. access other dirs on sdcard, e.g. `<sdcard>/osmand` without any issues on all Android versions

So, with current OsmAnd versions the only thing you loose on Android 11+ is the fast aceess to `<sdcard>/android` directory. But you can still access other dirs on sd-card. This is even not hard to select in the settings.

The third setup is needed anyways if you want to use external routing engines like brouter.

I personally would rather live with this features and a non-Google Play app store like FDroid than loosing any access to sd-cards just to keep conforming to Google Play store. As @aceman444 pointed out (https://github.com/osmandapp/OsmAnd/issues/10453#issuecomment-830777688) accessing sd-cards is rather essential considering the size of maps. (Also from an availability standpoint, e.g. your phone crashes on a tour, but you can still access your routes / recorded tracks.)

**Comment by uwemock** [comment] 2021-05-26 09:12
> From what I've seen, current OsmAnd releases can:
> 
> 3. access other dirs on sdcard, e.g. `<sdcard>/osmand` without any issues on all Android versions

Unfortunately, this does not work on my Android 11 device. OsmAnd complains about not being able to move map files. Even if I change the location without moving the current files, OsmAnd complains that maps can't be created in that location.

**Comment by EssBee59** [comment] 2021-06-18 13:42
I am using the brouter (with "nogo´s"): After migration to Android 11, brouter had not longer read access to the file "favourites.gpx" under  OSMAND installation type 1.
After moving OSMAND to installation type 3, every thing worked as for the migration!

Are  negativ side effects possible by installing OSMAND with type 3?
Else not not, it could become the recommandation?

**Comment by theraser** [comment] 2021-11-20 14:48
Sorry for pushing this old issue again: is there any other known workaround for this slow storage problem? Just upgraded my Fairphone 3 to Android 11/Lineageos 18.1 and now got the same problem. Moving all data to <sdcard>/osmand worked but it is still as slow as at <sdcard>/Android/..., moving it did not change anything in terms of speedup. Startup takes about a minute, reindexing after updates takes ~2-3 minutes :pensive:

**Comment by EssBee59** [comment] 2021-11-20 20:48
Hello,
I am also using the /osmand directory under Android 11.... without performance issues!

**Comment by explorer79** [comment] 2023-03-25 13:35
> The workaround is to move the maps from SD card to the phone's memory.

I don't use it on an SD card. I use it in internal memory. I have a Galaxy S10+ with 1 TB with LineageOS. I downloaded all of Europe and other regions as well. Updating is a pain. it initializes everything after one map has been updated. I think it would make much more sense to only initialize once after every map is updated. But initializing takes ages, and when everything is initialized again after every single file, it takes ages.

**Comment by pebogufi** [comment] 2023-03-25 15:26
@explorer79 on which directory is your installation ?
Is your LineageOS comparable with Android 11 or 12 ?

**Comment by explorer79** [comment] 2023-03-25 15:36
@pebogufi 
Android 11
I don't know the installation directory. I can only see the data directory:
/storage/emulated/0/Android/data/net.osmand.plus/files
This is definitely not on an external sd card.

But actually it seems the update today did not take as long as it used to.

**Comment by pebogufi** [comment] 2023-03-25 16:14
Try moving to
/storage/emulated/0/Android/**media**/net.osmand.plus/files
Use "manual" for setting path
On Android 12 with Samsung S10 it works fine.

**Comment by explorer79** [comment] 2023-03-25 16:36
the first try to move the directory resulted in a crash. Now I'm trying a 2nd time.

**Comment by pebogufi** [comment] 2023-03-25 17:02
Try moving to
/storage/emulated/0/Android/**media**/net.osmand.plus/files
Use "manual" for setting path
On Android 12 with Samsung S10 it works fine.

**Comment by pebogufi** [comment] 2023-03-25 17:10
"Moving" means the Migrate function with "manual" in OsmAnd.

**Comment by explorer79** [comment] 2023-03-25 17:12
yes, I'm using the function to move the directory within OsmAnd+ with "manual". But that's where it crashes after some time. It is now my 3rd try. currently 91 GB remaining

**Comment by Andyxz1c** [comment] 2023-06-21 07:13
Helo.I experience identical issue for maps downloading function on Lineage,XZ1C, Android12, where maps are on externalSD (ext4 - Sandisk pro 512G) - but platform looks to be irelevant, it looks to me to application logic.
Indexing all files after each downloaded piece is not practical.
If this idea is due to avoiding loss of sync with offline-downloaded maps, then  maybe we can maintain:
- separate index (updated,added/deleted record) after each maps down/deleted with indexing flag (done/missing);
- and at the end of download process  (or OsmAnd restart), it woukd check this DB if all is indexed.
- download process would be identified, when all downloads ends, as during recently running i can add several new into download queue.

**Comment by pebogufi** [comment] 2023-10-01 15:54
@explorer79 
Months later. ..

Did you find a solution ?
Which directory do you use now withAndroid 11

**Comment by explorer79** [comment] 2023-10-01 17:55
@pebogufi, to be honest I uninstalled osmand and reinstalled it. But I still find it unusable. I have many countries installed. It might work better if only one or two countries were installed.
Currently the setting is /storage/emulated/0/Android/media/net.osmand.plus/files.

I think the main problem is the index. after one map is updated the whole index is reindexed. This takes forever if you have more than one country installed, because the complete reindex is done after each map update. It would be much better, if the reindex happened only once after every country is updated.

But the first start takes too long also. So when you sit in the car, start osmand, it just takes too long until the app is ready.
Searching for an address hardly works. I just use Here WeGo maps or Organic Maps instead.

**Comment by sonora** [comment] 2023-10-05 15:29
Perhaps this is not even a matter of storage location, but just another manifestation of #18077. There seem occasions where some processes come to a standstill, for no known reason...

**Comment by weirdal3333** [comment] 2024-11-24 11:34
I'm surprised that the solution of offering a manual (or automatic) reindex button somewhere, and letting the user index all new files, hasn't been suggested yet. 
This is still an issue on Android 12, 13 and 14.
