### ISSUE TITLE
On a peninsula land is displayed as water but streets are shown

### ISSUE THREAD

**Issue by Sparky1976** [osmandapp/Osmand#7678] opened 2019-10-16 13:27 UTC

**Comment by Sparky1976** [comment] 2019-10-16 13:37
I work in a town on a peninsula and the streets appear on  Osmand+ but the land is displayed blue like the lake surrounding
please see attached...
Map = United States, Wisconsin  
Near 45.0464° N, 87.2971° W
<img width="199" alt="door county" src="https://user-images.githubusercontent.com/56640370/66924181-c4d49880-efef-11e9-9b92-4b9b1ba132eb.png">

**Comment by xmd5a2** [comment] 2019-10-17 12:57
Duplicate of https://github.com/osmandapp/Osmand/issues/6587

**Closed by xmd5a2** 2019-10-17 12:57 UTC
