### ISSUE TITLE
TTS directions combine road numbers to create an incorrect road name

### ISSUE THREAD

**Issue by bhankerson** [osmandapp/OsmAnd#16256] opened 2023-01-16 17:08 UTC
### Description
I don't think OsmAnd draws anything from OSM routes for spoken directions, am I right? So, I am speaking about way tags. Take a road that has, for example, `ref=CR 100`, `name=212th Street`. I'm turning right onto that road. TTS will say "turn right onto cee-ar one hundred thousand two hundred twelfth street".

### How to reproduce?
Have navigation turn you onto a road with a `ref` number and a street name starting with a number. It may require the street name to be in the hundreds? I'm not sure how a road with `ref=CR 100` and `name=12th Street` would be read.

### Your Environment
OsmAnd Version: 4.3.5
Android/iOS version: Android 10
Device model: Moto G7 Power

Thank you!

**Comment by sonora** [comment] 2023-01-16 23:50
Looks liket his is a glitch specific to the TTS engine or version used. I have just tried Samsung's and cannot reproduce.

Have you updated your engine to the latest available version?

For testing: There is an app called TTS Test which allows to type arbitrary text to see how it will be spoken. Both "_CR 100 22th Street_" and "_CR 100 100th Street_" are pronounced ok for me. (I think we use blank beteeen ref and name. Could use a comma, but that produces false intonation with a pause for most engines.)

**Comment by bhankerson** [comment] 2023-01-17 04:48
I have "Speech Services by Google", updated Nov 30, 2022, version googletts.google-speech-apk_20221111.00_p4.491700629
Appears to be the latest available version, is yours different? Is there a way to rollback updates without a 3rd party app?

**Comment by sonora** [comment] 2023-01-17 08:59
Yes could use a semicolon. But I am a litthe hesitatnt because apparently this would fix a very spurios issue of the Google engine, while it has a notable impact on all other never broken cases. Have you tried the difference between "_Turn right onto CR 100 Main Street_" and "_Turn right onto CR 100; Main Street_"? Using Samsung's rngine I have a notable pause in the latter case, which sounds a little wrong? Test a few cases. If you think the intonation sounds natural, I can put the semicolon in the code for broader feedback.

**Comment by bhankerson** [comment] 2023-01-18 17:42
Huh, ok. Do you have a Samsung-specific TTS engine? My Google TTS does have a perceptible pause in "Turn right onto CR 100; Main Street" compared to without a semi-colon, but it is very brief, I feel it helps distinguish the separate road names. I don't notice a change in intonation. Additionally, "CR 100 12th Street" sounds like CR 112th Street".
A possible change that would eliminate the need for a semi-colon and improve TTS directions: switch the order. Since the `name` (in the US, anyway) almost always ends with "Street/Avenue/Road/Boulevard/etc.", there won't be the danger of two numbers running together. And in the case of city streets, it's more important to hear the `name` first, the `ref` is often not even (or infrequently) signed.

p.s. really not important to the discussion, but it might affect the decision on OsmAnd's part to act: I suspect that this "spurious" issue of the Google TTS is not going to go away. "100 212" is a common way to print the number "one hundred thousand two hundred twelve", especially in statistical documents, so it could be that Google has introduced and intends to keep this method of interpreting the space between sets of 3 numbers

**Comment by sonora** [comment] 2023-01-19 08:47
I have a variety of Samsung phones, all are set to `system-language=American English`, and their TTS is set to `Use system language`. On all of them, when I go the Android's setting `(General management) > Text to speech`, I can tap on the first entry `Preferred engine`, and get a choice between `Samsung text to speech engine` and `Google text to speech engine`.


Funny thing is: On all phones I have tried so far, **I could not reproduce the issue**, neither with the Samsung nor with the Google engine. So it seems to depend on exact versioning or some other system setup parameter.

Nevertheless I trust that this is an issue under certain circumstances, and Iam willing to look into a fix. Current thinking is to not fix it in our 60 or so language specific TTS configuration files: Maybe a viable way is to in general add a separator character to the end of the `ref` fields before passing them to the configuration file. (and if they are succeeded by a street name) I have to think about possible side effects.

**Comment by sonora** [comment] 2023-01-19 19:45
I'm hesitant to swap the order, since today's order is a long lived practice which has drawn no complaint in any language, while swapping is a risk. Also, it may be more awkward in some countries or situations: Imagine a prompt like "_Turn left onto North Avenue of the Americas State Route 10_", I feel it is less crisp then placing the (mostly shorter) ref first.

I like a solution with a comma or semicolon better, will test when I find time.

**Comment by sonora** [comment] 2023-01-20 10:38
Ok, I am currently testing this PR #16293, which basically fixes the issue.

- I prefer a comma over a semicolon, some engines pronounce a semicolon more like a period.
- Side effect: Since in most language files we prefer speaking "to destination" over speaking the street name (if both are present), there are now occurreneces where we have "_Turn right onto State Route 50, toward Orlando._" with a comma (and associated pause) in the middle. That sounds acceptable in most languages I can judge, what do you think? (The inconsistency is that the comma after the ref will not be present in that same prompt if there is no street name.)

**Comment by bhankerson** [comment] 2023-01-23 16:16
Sounds good! You have a better overview of all the potential repercussions than I do. As long as TTS doesn't say something incorrect, I'm happy :) Thank you for taking the time!

**Comment by sonora** [comment] 2023-01-23 16:42
@bhankerson From my testing, I think it's fixed. You should the the update in our next release version. Thanks for taking the time to report this.

**Comment by Zirochkabila** [comment] 2023-02-07 14:32
OsmAnd~ 4.4.0#14157mqta, released: 2023-02-07
It sounds the same with a space ( ), and a comma (,), as well as with a semicolon (;) - English TTS, 7Feb 2023

`37.76697, -122.41333` - space
[OSM](https://www.openstreetmap.org/search?query=37.76697%2C%20-122.41333#map=18/37.76697/-122.41289)

https://user-images.githubusercontent.com/104760013/217271672-8a4a81ea-cfe4-4ef2-8535-5553ab1720d5.mp4

https://user-images.githubusercontent.com/104760013/217271692-9c1d2840-b8dd-4224-ac9a-a1880279064c.mp4

`28.553863, -81.339374` - comma, a semicolon
[OSM](https://www.openstreetmap.org/search?query=28.553863%2C%20-81.339374#map=18/28.55386/-81.33936)


https://user-images.githubusercontent.com/104760013/217272751-f8f15efe-35f0-4ac6-ae9a-f048bfa6cdaf.mp4

https://user-images.githubusercontent.com/104760013/217272741-8518011a-7d2c-4052-9535-2ae7a65e6336.mp4

**Comment by sonora** [comment] 2023-02-07 16:16
@Zirochkabila yeah, well, for one, it depends on the TTS engine and even it's version it seems. But mainly: You are not testing what the issue was all about, see post 1: This is about the false concatenation of 2 numbers if they happened to end up next to each other and only separated by a blank.

I am fairly confident it's fixed now. :wink:

**Comment by Zirochkabila** [comment] 2023-02-08 10:15
@sonora Please send the coordinates of the place where you can check the TTS operation, provided that the two numbers are side by side and separated by a space

**Comment by sonora** [comment] 2023-02-08 10:42
@Zirochkabila Anatolii, I actually never bothered to find real world occurrence since I could not reproduce the issue in the first place on any of my devices with the TTS engines they come with. (The issue was discovered by @bhankerson, not by me.)

But performing quick search on OSM I would guess that e.g. https://www.openstreetmap.org/way/25703125 could be a test case, because it is labeled with both `ref=NY 24` and `name=212th Street`.

**Comment by Zirochkabila** [comment] 2023-02-08 10:51
@sonora  The fact is that I tested on streets with similar names, but I couldn't reproduce it
Most likely, it's really the TTS engine
Thanks

**Comment by sonora** [comment] 2023-02-09 22:42
I have just checked and the issue is that the fix https://github.com/osmandapp/OsmAnd/commit/dee5b2f668e4ff141adc64c6d0388c087287e9d2 was not merged back to releases v4.3.x, so unless @vshcherb would still consider merging it back it would only appear in v4.4.

I inserted a comma plus a blank as a delimiter, would believe that is a good fix. Maybe anybody who can reproduce is able to check a nightly build, or rlse we can wait until the first release 4.4, and if it is not fixed we could try a semi-colon, ok?

**Comment by bhankerson** [comment] 2023-02-13 19:10
That's fine, I can wait for 4.4 :) Thanks!

**Comment by vshcherb** [comment] 2023-02-23 19:32
4.4 beta should be uploaded next week

**Comment by bhankerson** [comment] 2023-05-01 15:38
Hey guys, I'm afraid I'm still getting concatenation of ref/name numbers. Travel north out of Pemberton, Minnesota, I'm told to "keep right on cee-aitch fifty-three thousand six hundred and twenty-seventh avenue". Route to Alma City, MN, and I'm told to "turn right onto cee-ar ten thousand one hundred and sixty-fourth street". I do hear a pause when the street is "CH 53, Main Street", but the comma isn't preventing my TTS from thinking "CH 53, 627th Avenue" is one number in the thousands.

**Comment by vshcherb** [comment] 2023-05-11 17:02
Issue can't be reopen cause 4.4 is out

**Closed by vshcherb** 2023-05-11 17:02 UTC
Labels: navigation

**Comment by sonora** [comment] 2023-05-11 17:46
Ok. It was just a reminder for me to come back to this and check, and draw other people's attention to maybe assist with testing. (Hard to fix if you cannot reproduce...)

I believe we can leave it closed now, thinking my latest commit should have finally fixed it.

**Comment by bhankerson** [comment] 2023-05-11 20:12
Ok, great, thanks! Will that be in the next update, then?

**Comment by sonora** [comment] 2023-05-11 20:26
Yes, it's already in the nightly build, and will be in the v4.5 official release.
