### ISSUE TITLE
Disallow routing on access=emergency

### ISSUE THREAD

**Issue by twzkxkan** [osmandapp/Osmand#1790] opened 2015-10-08 22:07 UTC
motor_vehicle=emergency, etc.

Routing on ways specified for emergency vehicles can be illegal and/or dangerous.

**Comment by vshcherb** [comment] 2015-10-12 21:43
Could you please provide an OSM example and give a bit more information: is it forbidden for all modes (pedestrian, cycling...)

**Comment by twzkxkan** [comment] 2015-10-12 23:07
Yes it applies to all modes similar to access=destination, access=private, etc. In practice if tagged with access=emergency all traffic should be banned unless you want to make an "emergency" specific routing profile.

[See also](https://github.com/graphhopper/graphhopper/issues/539)

**Comment by RussNelson** [comment] 2015-11-14 18:10
US Interstates are separated lanes in each direction.  They have periodic crossovers between these lanes. They are marked "No U turn" because they're only for police and other emergency vehicles. OSMAND 2.1.1 tried to route me through one of these, this one to be specific: https://www.openstreetmap.org/way/5566165 . It had routed me south through Albany on I-87, but I wanted to take the NY-7 / I-787 shortcut. I turned off, and it tried to route me back to I-87, first using NY-9, and then using this crossover.

This shows the correct routing: https://www.openstreetmap.org/directions?engine=osrm_car&route=42.75892%2C-73.74671%3B42.75903%2C-73.74596#map=14/42.7498/-73.7211

Switching to the Mapzen engine shows the incorrect routing: https://www.openstreetmap.org/directions?engine=mapzen_car&route=42.7589%2C-73.7467%3B42.7590%2C-73.7460#map=17/42.75829/-73.74235

You can reproduce this in OSMAND easily. Zoom in to NY-7 near Michaelangelo Street until you can see separate directions on NY-7. Press and hold on the westbound lane. Click on the box. Click on "Set as destination". Then press and hold on the eastbound lane. Click on the box. Click on "Directions From". Routes you straight through the "access=emergency" crossover.

If I may speculate, it looks like the router is not respecting access=emergency. Maybe there needs to be a setting for "Vehicle attributes", so I could set my vehicle's height (avoid maxheight roads), or weight (avoid maxweight roads), or emergency status (allow access=emergency)?

Maxheight routing is a big deal: http://11foot8.com/

There are other crossings which are only accessible to emergency vehicles. Some of the closed intersections on the Taconic State Parkway which used to go straight through are now populated with signs and rubber push-down sticks, so that emergency vehicles can go through, but others are discouraged.

**Comment by sonora** [comment] 2015-11-15 10:06
Russ, thanks for reporting!

Victor, easy to fix at first sight. But I think it requires a bit ore thinking, as OsmAnd is increasingly used also by emergency crews on some occasions, so maybe we need a navigation setting "Use (avoid) emergency lanes" for this?

Best, Hardy

**Comment by twzkxkan** [comment] 2015-11-16 12:28
> so maybe we need a navigation setting
This is really no different than other restrictions such as oneway or turn restrictions. If there is to be a mode that ignores traffic laws, it should be very clearly marked and never the default.

**Comment by elumbella** [comment] 2015-11-20 12:21
Sonora, I would'nt add it as a navigation setting as most users will not be emergency crews and an option like this will only confuse people and/or encourage illegal driving. I'd rather put it somewhere in the settings. Or include it in an addon if there is more functionality that would be specifically for emergency crews.

**Comment by vshcherb** [comment] 2015-11-23 08:27
Fixed

**Closed by vshcherb** 2015-11-23 08:27 UTC
Labels: Offline Routing

**Comment by twzkxkan** [comment] 2015-11-23 13:17
:+1: thanks, @vshcherb

**Comment by RussNelson** [comment] 2015-11-23 17:00
How about this idea? Put it in the navigation settings and say "Use illegal routes". Have two checkboxes in that section, saying "I am driving an emergency vehicle" and "Ignore traffic laws". Only do emergency vehicle routing if both checkboxes are checked. That wording should be sufficiently alarming to people that they won't accidentally use it.

**Comment by vshcherb** [comment] 2015-11-23 23:21
Quite bad idea, for professional usage, you need to customize routing.xml yourself. If it is always used by 90% of users, then we don't provide that option in the app itself, but extension point here is already existing.

**Comment by RussNelson** [comment] 2015-11-24 16:44
Okay, close this then?
