### ISSUE TITLE
Block streets according to navigation type

### ISSUE THREAD

**Issue by Vucumpra** [osmandapp/OsmAnd#18905] opened 2024-01-13 21:29 UTC
### Describe the idea (required)

Hello !
When traveling by bike, a multitude of routes are acceptable for the same destination.
But sometimes there are roads that I want to avoid because they are either dangerous or very uncomfortable.
But only by bike! By car, for example, these roads are ok and I wouldn't avoid them.

### Tell us about the expected behaviour (required)

So, is it possible to block streets according to navigation type ?
[Screenshot_20240113-220357](https://github.com/osmandapp/OsmAnd/assets/156325356/20d63a84-304a-4890-a8d1-7d04f4ee13a8)
When blocking street, show a pop-up with some categorie : foot, bike, car, ...
But it seems complicated to do :(

### Tell us about alternatives you've considered (required)

No idea

**Comment by mikehgentry** [comment] 2024-01-14 10:47
Not possible at the moment, but it has been requested.

#7396

**Comment by vshcherb** [comment] 2024-01-15 09:54
Yes it should be though the right solution wouldd be to block all roads in a certain directions to avoid using highways by pedestrian 

Duplicate of https://github.com/osmandapp/OsmAnd/issues/7396

**Closed by vshcherb** 2024-01-15 09:54 UTC
