### ISSUE TITLE
Adjust the distance granularity in voice alerts

### ISSUE THREAD

**Issue by travnick** [osmandapp/OsmAnd#9344] opened 2020-06-29 08:05 UTC
Context: car navigation

I'm using a voice alerts for a some time and I found out that voice alerts describing the distance to next turn or something like that is too detailed. Other popular gps apps are doing it better - the granularity matches the distance and speed so it's not strange/funny/irritating.
What's more, the accuracy of the gps (of the mobiles) is not so good to present the distance with such granularity.

In case of 359 meters, I really don't care about the 9 here.
With longer distance like 1234m the  34 meters are really nothing - I do not care about them at this point.

In my opinion the distance should be rounder to only two first digits, like on the examples:
```
4m -> 4m (no rounding at this lavel)
14m -> 14m
274m -> 270m
275m -> 280m
1234m -> 1200m
1282m -> 1300m
```
But I'm thinking if it would be better to round the distance to the halves:
```
4m -> 4m (no rounding at this lavel)
14m -> 15m
274m -> 250m
275m -> 300m
1234m -> 1000m
1282m -> 1500m
```

As always - it would be nice to have the configuration option for it, but with reasonable defaults

**Comment by sonora** [comment] 2020-07-22 23:21
Cannot reproduce. Which voice produces the issue?

**Comment by travnick** [comment] 2020-07-23 08:07
As far as I can see I'm using Polish recorded. I'm able to test how Polish synthetized or English act for me.

**Comment by travnick** [comment] 2020-08-27 10:39
I've tested Polish synthesized and there is no issue. So recorded voice is buggy

**Comment by sonora** [comment] 2020-08-28 17:47
In deed, I can confirm it now that our standard rounding ( which is **nearest meter for <17m, nearest 10m for <100m, nearest 50m for < 1000m, and nearest kilometer above that**) does not seem to be applied to recorded voices, I have just tested using recorded English.

I will investigate when I find time. In any case, the TTS voices are much more powerful, because they can e.g. also announce street names, so if you can, I recommend using TTS voices.

**Comment by sonora** [comment] 2020-08-28 19:57
I just investigated, and think I had fixed this very issue already months ago (https://github.com/osmandapp/OsmAnd-resources/commit/98799c4bfd125a93788af54c7a701fd020387010). But somehow I have a feeling that when in OsmAnd you download a recorded voice from our server you do not receive the latest version.

@vshcherb Maybe you could double-check, I think the issue is fixed in our code, but our downloads somehow have never been updated?

@travnick  To verify, you may on your device want to locate the file `pl_tts.js` in the folder `[SD-Card_or_InternalMemory]/Android/data/net.osmand(.plus)/files/voices/pl-tts`, and copy it to the `.../voice/pl` folder (overwriting the buggy version you have there). I believe that would fix the issue for you.

**Comment by vshcherb** [comment] 2020-09-02 13:12
@sonora your file will updated from release i.e. if you install new version all recorded files will be copied and overwrite existing recorded voice, cause release date of the apk is newer. It has been fixed in current ongoing release

**Comment by sonora** [comment] 2020-09-07 22:33
Yes, but if between releases users download a recorded or tts voice (even if none was present on their device before), is it intended they receive an outdated version?

**Comment by sonora** [comment] 2020-12-28 13:08
Closing this, should be fixed.

**Closed by sonora** 2020-12-28 13:08 UTC
Labels: Observed
