### ISSUE TITLE
Missing phone numbers

### ISSUE THREAD

**Issue by blackboxlogic** [osmandapp/OsmAnd#12344] opened 2021-08-01 22:45 UTC
### Description
POIs aren't showinh phone numbers. I recall seeing phone numbers before but they are gone now. 

### How to reproduce?
Download the Maine, USA map
Navigate to this element on the map https://www.openstreetmap.org/node/6557966132
Touch the POI to select it
Touch "details"
Get this:![Screenshot_20210801-183958.png](https://user-images.githubusercontent.com/31355456/127787388-cd35afa5-1e43-4c97-b47c-a116cbdbe1a4.png)
See that the element has a valid tag in OSM: phone=+1-207-856-9000
See that the phone number isn't visible in OsmAnd

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 11
Device model: Pixel 3

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

"United States Maine" published Jun 30, 2021

**Comment by scaidermern** [comment] 2021-08-02 11:15
Duplicate of #12209.

**Comment by vshcherb** [comment] 2021-08-02 11:45
Yes fixed. Should be next maps and 4.0.3 version available

**Closed by vshcherb** 2021-08-02 11:45 UTC
