### ISSUE TITLE
Elevation profile widget appears inconsistently when calculating a route

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#20630] opened 2024-08-17 21:08 UTC
### Description

Depending whether you wait for the route calculation to finish before dropping out of the Navigation menu, the Elevation Profile widget either appears or doesn't.

### Steps to reproduce

Be in a profile with the elevation profile widget active.

Long press somewhere far away on the map and choose 'Navigation'.

### Actual result

If you tap in the map while the route is calculating, the menu closes, and the route continues calculating. When it finishes, there is no Elevation Profile widget visible, and it isn't obvious how to make it appear (though actually starting the navigation works).

If instead you wait for the calculation to finish, then tap in the map, the menu closes and the widget is visible.

### Expected result

Presumably the widget is intended to appear when the calculation finishes, but doing things 'out of order' breaks this.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: +4.8.6
Android/iOS version: 11
Device model: XCover 4s
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment] 2024-08-23 09:05
The bug couldn't be reproduced. In my case, if the widget is active and you tap on the map during route calculation, then close the calculation menu, the widget doesn’t show up. Even if you wait for the calculation to finish without closing the menu, the widget still doesn’t appear.

This seems to be expected behavior since the Elevation Profile widget only appears once navigation starts, as demonstrated in the second video.

Steps to reproduce:

- Activate a profile with the Elevation Profile widget.
- Long-press on the map and select 'Navigation'.
- If you tap on the map before the route calculation finishes, the widget doesn’t appear afterward.
- Next, wait for the route calculation to finish, then tap on the map—the widget still doesn’t appear.

OsmAnd~ 4.9.0#3059m, released: 2024-08-22

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/8a4c9369-bd8e-4b60-8965-50808abdd688"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/e5704442-fbb1-4f3b-a81b-d18420b11303"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by mikehgentry** [comment] 2024-08-29 09:25
Upon further testing it seems to be limited to my contour based profiles.

Feel free to close if you can't reproduce it, I'll make a fresh profile using the same settings at some point and see if it behaves the same - I've been using these for quite a while so it doesn't surprise me if they've accumulated some cruft / oddness.

[Contour.zip](https://github.com/user-attachments/files/16393406/Contour.zip)

**Closed** 2024-09-14 16:26 UTC
