### ISSUE TITLE
No maps displayed after update

### ISSUE THREAD

**Issue by ericglam** [osmandapp/OsmAnd#11017] opened 2021-02-26 15:57 UTC
### Description
OsmAnd updated to version 3.9.9. and the rendering of maps is really slow to non-existent.   You start OsmAnd and no map is displayed until after about 2 minutes or so. The controls will display but not the map. Makes no difference if you are online or using offline maps. 
Downloading offline maps is now excruciatingly slow too with 10 minutes being taken up indexing each map once it has downloaded.
I read about replacing the default.render.xml file being zero bytes as being a fix, but this phone is unrooted so I have no access to replace these files.

### How to reproduce?
Open up the program after the update.

### Your Environment
OsmAnd Version: 3.9.9
Android/iOS version:11
Device model: Galaxy S10+

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by njohnston** [comment] 2021-02-26 20:14
Duplicate of #10453?

**Comment by vshcherb** [comment] 2021-02-28 20:43
I think it's duplicate to #10453 and actually most likely you've updated android first (last week ago was update to android 11).

**Closed by vshcherb** 2021-02-28 20:43 UTC
