### ISSUE TITLE
"Native library not supported on this device" error on Pixel 6 Pro

### ISSUE THREAD

**Issue by andrey-tsykunov** [osmandapp/OsmAnd#15157] opened 2022-08-26 00:51 UTC
I've just purchased a new phone (Pixel 6 Pro) and installed Osmand 4.2.7.

But maps do not work, I get "native library not supported on this device" and then "could not draw chosen area".

Changing "Use OpenGL Rendering" setting did not make a difference.

**Comment by vshcherb** [comment] 2022-08-29 15:30
I think it's duplicate of https://github.com/osmandapp/OsmAnd/issues/14947.

Please test https://download.osmand.net/latest-night-build/OsmAnd-opengl-arm64-nightly.apk

**Closed by vshcherb** 2022-08-29 15:30 UTC
