### ISSUE TITLE
Offline vector maps don't show information when long pressing on a POI in v3.8.3 and 3.8.5 

### ISSUE THREAD

**Issue by bege10** [osmandapp/OsmAnd#10270] opened 2020-11-24 18:45 UTC
### Description
When I long press on a POI in a offline vector map I only get the address, no information about the POI.
I didn't use that feature for quite some time, so I didn't notice it until now.

### How to reproduce?
Just long press any POI in the named versions. By chance I noticed that it works once if I place a POI under the mark in the center of the screen, close the app, reopen it and then long press that POI. If I long press the same POI again or any other POI it doesn't work any more until I repeat the procedure.
I restored v3.7.4 and it works. Restored v3.8.3, doesn't work, v3.8.5 neither.

### Your Environment
OsmAnd Version: 3.8.3, 3.8.5
Android/iOS version: LineageOS for microG 16 (Android 9)
Device model: Samsung Galaxy S5 Plus (SM-G901F)

**Maps used (online or offline):**   
Any offline vector map from German federal states (Bavaria, Lower Saxony ...)

**Comment by sonora** [comment] 2020-11-24 18:54
I guess this is a duplicate of #10030, please see my comment there?

**Comment by bege10** [comment] 2020-11-24 19:05
In fact this is a duplicate of https://github.com/osmandapp/OsmAnd/issues/10030
But the solution there does not work here. When I don't long press but only tap the POI I get the flash notification "Ziel ist nicht festgelegt" (aim is not determined).

**Comment by sonora** [comment] 2020-11-24 21:06
Sounds like you have the Accessibility plugin enabled?

**Comment by bege10** [comment] 2020-11-25 17:17
@sonora 
Amazing, yes, thank you very much! Obviously I don't understand the functionality of that plugin. If disabled it works as it shall do.

**Closed** 2020-11-25 17:18 UTC
