### ISSUE TITLE
Roads partially cut (12-14 zoom)

### ISSUE THREAD

**Issue by awikatchikaen** [osmandapp/OsmAnd#1248] opened 2015-05-18 12:10 UTC
On Osmand and on low zoom, I have roads which are partialy rendered, some parts are missing.

**Comment by vshcherb** [comment] 2015-05-18 14:07
The screenshots will be good

**Comment by sonora** [comment] 2015-05-18 20:13
I assume this issue refers to how some road segments are missing on our World_basemap.

**Comment by awikatchikaen** [comment] 2015-05-19 07:12
Sorry, here's a screenshot of Toulouse, France
![screenshot_2015-05-19-09-04-27 1](https://cloud.githubusercontent.com/assets/552126/7697360/37cd7e54-fe07-11e4-970d-67ea138e80c5.png)

**Comment by awikatchikaen** [comment] 2015-05-26 14:17
Not sure that tag "nice to have" is relevant. It's more a bug for me ....

**Comment by Norbert80** [comment] 2015-05-29 04:17
Could you please mark in the screen shot what exactly you mean?

**Comment by Norbert80** [comment] 2015-05-29 05:28
Confirmed with 2.1.0#7403D on Germany map around Munich.

Screenshots will follow. Will check for regression later.

@vshcherb any chance to raise prio? Extremely ugly that thing...

**Comment by vshcherb** [comment] 2015-05-29 08:58
Map bugs/issues can't be confirmed around the different area, they could be observed. Even though they could look the source of the same issue, they might not be the same. 
My observation this is zoom 12 and the detailed map is used. We use some lines simplification that might be too much. I agree it doesn't look nice, but it is not critical (zoom 13 displays much better picture and on that zoom the roads refs are still visible). I don't see reason to increase priority comparing to other issues we have. Zoom 12 never used for navigation.

**Comment by Norbert80** [comment] 2015-06-11 20:08
@vshcherb I provided some more screen shots. Although there may be some bigger problems I would appreciate if you remove "Nice to Have" label.

![screenshot_2015-05-29-07-19-39](https://cloud.githubusercontent.com/assets/6921696/8117095/1967e54e-1086-11e5-8b09-930fe58bf4c9.png)
![screenshot_2015-05-29-07-23-58](https://cloud.githubusercontent.com/assets/6921696/8117096/197aea5e-1086-11e5-8115-081319356a70.png)

**Comment by Norbert80** [comment] 2015-06-15 21:20
@vshcherb this issue is extremely annoying when viewing map intensively. IMHO users expect proper map rendering from a map app. :-)

Can I support to fix this issue by tuning some parameters in a config file?

**Comment by vshcherb** [comment] 2015-06-15 21:42
The maps are global, it requires different algorithms of road simplifications.

**Comment by sonora** [comment] 2015-06-15 22:51
Unless I am very mistaken, the issue only affects the world basemap? So a
possible fix could be we let our detailed regional maps (where
downloaded) take precedence over the basemap, down to very low zooms, like
we used to have it at some point?

**Comment by vshcherb** [comment] 2015-06-16 08:19
I would say other way around, basemap algorithms are different and in my opinion better. So the problematic zoom is only one 12, 13-14 are less problematic though.

**Comment by Norbert80** [comment] 2015-06-16 09:21
@vshcherb for me it looks like there are connections that stay unconnected over two zoom levels. Btw. how do you reference the zoom levels with numbers like 12, 13, 14, ...?

**Comment by Norbert80** [comment] 2015-06-16 09:23
@vshcherb If I long click the + or - button a selection comes up. There always 100 % is selected independent of the actual zoom level. Is this another bug?

**Comment by sonora** [comment] 2015-06-16 10:17
Let us not mix up here the "map magnifier", which is the percentage value
and acts just like a magnifier lens on what is displayed, with the map zoom
level, which is actually the "scale" equivalent on conventional paper maps,
see http://wiki.openstreetmap.org/wiki/Zoom_levels.

Unfortunately we have somehow messed up our zoom level indication, on some
devices you can briefly see 2 digits above our menu button (where the use
profile is normally indicates) when pressing the + or - zoom buttons, on
other devices the display disappears so fast it cannot be seen.

Zoom leve 12 is the first one where you see significantly more detail, we
use the regional maps then, while on zooms 11 and smaller we use the world
map, which has a lot less detail. It would be interesting what your issue
is in the first place, from my understanding it would have been at large
scales=small zoom levels <=11, but maybe I misunderstood.

Workaround to determine the zoom level could be to zoom in to where OsmAnd
says "max zoom" when trying to zoom further, last one displayed is 22, then
counting down with each tap of the zoom- button.

**Comment by sonora** [comment] 2015-06-16 10:37
PS: I just analyzed your screenshots above (they were too big to register
... :-) ) and they are Maps Style: OsmAnd (default), zoom level 10.

Our maps at 12 and higher look pretty flawless if you ask me, the
"disconnect" issue results from, in a way, oversimplifying the world
basemap display at zooms 11 and down.

**Comment by Norbert80** [comment] 2015-06-16 11:48
@sonora thanks for clarification zoom level indication.

I notice disconnected roads in zoom levels 11, 12 and 13. Do you need additional screen shots?

**Comment by Norbert80** [comment] 2015-06-16 13:19
Zoom levels 9, 10, 11, 12 and 13 are bad. I will provide scree shots later.

**Comment by Norbert80** [comment] 2015-06-16 20:41
![roads partially cut osmandf 2 1 0 7792d](https://cloud.githubusercontent.com/assets/6921696/8193702/01c5c5b0-1477-11e5-8ba0-7ec70e1ee632.png)

@sonora  @vshcherb please have a look at my comparison. (OsmAndF~2.1.0#7792D)

**Comment by Norbert80** [comment] 2015-06-17 09:16
@vshcherb: Have these "line simplifications" you are talking about been introduced in release 2.0?

**Comment by Norbert80** [comment] 2015-06-20 14:14
@vshcherb, @sonora  any change that this issue gets a bit more attention? Detailed map rendering is normally a strength of OsmAnd compared to conventional navigation systems. But that's broken by this bug. :-(

**Comment by vshcherb** [comment] 2015-06-20 20:20
This issue exist since 1st OsmAnd release and it is not a "bug", because we did what we could for now.

I'm afraid here we definitely want to talk about 12-14 zoom and leave 11st zoom for world basemap. We have plans to search for a better algorithm 12-14 zoom in a midterm timeframe, but below < 11 is definitely not planned any time soon.

**Comment by Norbert80** [comment] 2015-06-20 22:08
@vshcherb thanks for the information. This sounds like a wise decision.

**Comment by Norbert80** [comment] 2015-06-21 20:01
@vshcherb you have written:
>  I don't see reason to increase priority comparing to other issues we have. Zoom 12 never used for
> navigation.

The screen shot below has been taken during car navigation without manual zooming. Please note that the road above the round about is displayed cut! Please reconsider priority since this bug does effect normal navigation usage.

![screenshot_2015-06-21-18-32-47](https://cloud.githubusercontent.com/assets/6921696/8273154/9ebf2054-1860-11e5-91d5-5d885800ce88.png)

**Comment by vshcherb** [comment] 2015-06-21 21:12
This is completely different issue and yes we fixed it, thanks for reporting (main reason was overlapping 2 maps austria & germany), we fixed in the rendering style though. 
P.S. That's why it is better not to mix different issues. I keep that issue open keeping in mind about 12-14 zoom improvement.

**Comment by Norbert80** [comment] 2015-06-22 13:29
@vshcherb let's say fixing zoom level 12 - 15. :-) I'm not sure if the screen shot is 15. But that area in my latest screen shot is also truncated with 15.

**Comment by vshcherb** [comment] 2015-06-22 15:15
Nope, we should change description. Exactly 12-14. 15 is completely different issue, on screenshot it was 15 and it was fixed, but it has nothing to do with reported issue.

**Comment by Norbert80** [comment] 2015-06-22 21:31
@vshcherb shall I file separate issues for each zoom level?  I have a screen shot where road is not connected with round about at zoom level 16.

**Comment by vshcherb** [comment] 2015-06-23 10:09
@vshcherb shall I file separate issues for each zoom level? I have a screen shot where road is not connected with round about at zoom level 16.
Yes, if you have it reproducible with latest build.

**Comment by Norbert80** [comment] 2015-06-23 20:35
@vshcherb zoom levels 15 and 16 are still unacceptable bad. I have filed issue #1385 therefore.

**Comment by morray** [comment] 2016-05-17 00:31
Is there any fix for this bug in sight? It considerably harms orientation, when one tries to get an overview of the area.

**Comment by obifur** [comment] 2017-02-05 12:38
I'm not sure if this is the same bug because I can't remember facing it before. Please see the following screenshots.
S4mini, cm13 / Osmand nightly 2.6.0#20263M

![screenshot_20170204-103538](https://cloud.githubusercontent.com/assets/6723991/22626160/e59d8864-eba7-11e6-9ebb-8fa05608b79c.png)
![screenshot_20170204-103545](https://cloud.githubusercontent.com/assets/6723991/22626161/e92eb3fe-eba7-11e6-8128-25770e007f5f.png)
![screenshot_20170204-103557](https://cloud.githubusercontent.com/assets/6723991/22626167/f1f46aba-eba7-11e6-8827-56b7df58a32f.png)
![screenshot_20170204-103606](https://cloud.githubusercontent.com/assets/6723991/22626169/f47cca98-eba7-11e6-969e-2770b6bf986f.png)

**Comment by vshcherb** [comment] 2017-02-26 15:02
It could be OSM Live issue, we have it already opened.

**Comment by Discostu36** [comment] 2020-09-16 12:28
Now zoom levels 12-14 don't show streets at all on world map. So I guess this issue is outdated?

**Closed** 2020-09-16 17:38 UTC
Labels: Nice to Have
