### ISSUE TITLE
Map looks 'flooded' at zoom level 13

### ISSUE THREAD

**Issue by bambamal** [osmandapp/Osmand#4894] opened 2018-01-02 21:45 UTC
For some reason Bangkok, Thailand, looks flooded at zoom level 13. I haven't noticed this behaviour in any other place. Here are screenshots at zoom levels 12, 13 and 14:

![grafik](https://user-images.githubusercontent.com/33735248/34501243-5194433a-f00e-11e7-95e2-857f67b674cc.png)
![grafik](https://user-images.githubusercontent.com/33735248/34501248-57d4efec-f00e-11e7-9021-79880d506556.png)
![grafik](https://user-images.githubusercontent.com/33735248/34501256-5f146292-f00e-11e7-8114-054b61cdead8.png)

Im using the newest nightly 2018-01-02

**Comment by vshcherb** [comment] 2018-01-13 11:27
The problem is located here http://www.openstreetmap.org/#map=18/13.767649/100.518326. And there was coastline present at that location. Unfortunately I can't find it currently on the map possibly that was a data error which is already fixed

**Comment by PaulStets** [comment] 2018-01-14 08:56
The flooding was caused by the incorrect tagging on this pond: https://www.openstreetmap.org/way/531407311. Someone added it as a coastline. I have corrected it in JOSM and the generated map did not contain this error, so I also edited the OSM. The issue will be fixed with the next map update.

**Closed by PaulStets** 2018-01-14 08:56 UTC
