### ISSUE TITLE
The space is not cleared after the map update

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5084] opened 2018-02-28 16:41 UTC
Steps to reproduce:

1) Check how much free space you have ob the device.
2) Start updating any map in OsmAnd.
3) The free space will be decreasing during the download but will not go back after the map is updated.
4) Force-stop OsmAnd after the successful update and the space will be released.

**Comment by scaidermern** [comment] 2018-03-01 08:45
Duplicate of #3108?

**Comment by vshcherb** [comment] 2018-03-08 06:48
Yes it is duplicate

**Closed by vshcherb** 2018-03-08 06:48 UTC
