### ISSUE TITLE
POI description shows "Internet access" as POI category instead of the actual category

### ISSUE THREAD

**Issue by Erlendur22** [osmandapp/OsmAnd#17335] opened 2023-06-02 13:54 UTC
I am currently in Hamburg visiting the city. Some POI's like cafes or tourist attractions which have internet access as a tag, get displayed with the wrong category shown as the description. The node icon is correct but the description does not say _Tourist attraction_ or _Cafe_ but instead _Internet access_. This is frustrating, for the Osmand feature of "show nearby POI" will show nearby Internet Access POIs instead of cafes or tourist attractions. 

As a trial I deleted some of those nodes and reentered them as complete new nodes with JOSM. But problem persists. In the past there a was another bug report about the same problem. See here:

https://github.com/osmandapp/OsmAnd-iOS/issues/958

But it got closed and the problem persists. 

### Actual result

Wrong category is shown at POIs with Internet access tag. 

### Expected result

Right category of POI should be shown and Internet access just as a subtag. 

### Your Environment
OsmAnd Version: 4.3.5
Android/iOS version: Android 9
Device model: Samsung Galaxy S8

<details>
<summary> Screenshots</summary>

![Cafe](https://github.com/osmandapp/OsmAnd/assets/104724692/a7cd480b-a9e3-44d8-9bfd-acd8115ccf23)
![Miniatur Wunderland](https://github.com/osmandapp/OsmAnd/assets/104724692/0ad7dca8-308c-4244-8cc2-14802ccf598d)
![Miniatur Wunderland 2](https://github.com/osmandapp/OsmAnd/assets/104724692/e0f9746a-2cab-49ef-ac02-c5956448e786)

<details>

**Comment by scaidermern** [comment] 2023-06-02 20:59
I noticed such behavior before in combination with live updates. Have these POIs been edited recently?

**Comment by Erlendur22** [comment] 2023-06-03 10:01
Hi Alex,

to be honest, I don't know if they have been edited recently. The 
history is gone. My bad, because in order to find out the cause of that 
behavior, I first deleted the Internet access tags, waited, updated, 
verified, that the Internet access tag was gone and the original POI 
category showed. Then I added the tag again and for some reason the 
Internet access tag overrides the POI category. Then I deleted the node 
of the cafe and the Miniatur Wunderland completely, waited, checked with 
live updates to make sure, they were gone from the map, then I added 
them again with JOSM. But same behavior. The data in OSM is correct. The 
only fix I see is to delete the tag Internet access. So strange. But I 
think it is not a good fix to delete the Internet access tag, it is part 
of the tags of a node so it should stay in the database, especially 
other apps might use the tags and don't have problems.

Let's see. I have little hope, that this gets fixed, for two years ago, 
as mentioned, same thing occurred already.

Greetings Andre



Am 03.06.2023 09:00 schrieb Alexander Heinlein:

**Comment by scaidermern** [comment] 2023-06-03 10:37
You should never delete valid data (or valid tags) from OSM. If a specific software (like in this case OsmAnd) has a problem then this problem must be fixed in the software. Not in the data, if the data is valid!

**Comment by vshcherb** [comment] 2023-06-03 11:54
Technically it's better to provide links to OSM objects to be check by team and validate whether data needs to be changed or not. In that case it's a bug.

In OsmAnd we separate 1 entity to 2 POIs with different categories, cause there is no obvious order between POI categories it happens that POI category chosen randomly.  So we need to double check how it's present in the data first and then hand over to Android team to fix it.

**Comment by scaidermern** [comment] 2023-06-05 09:21
Looks like the affected POIs were these:
* https://www.openstreetmap.org/node/2398673087/history
* https://www.openstreetmap.org/node/5665900108/history

> to be honest, I don't know if they have been edited recently

Well, for the two POIs above, *you* added the `internet_access` tag a few days ago (before deleting the POI).

So I think this is the same behavior I experienced myself for similar POIs. The steps to reproduce should be the following:
* Add the `internet_access` tag to a POI
* Fetch update via OsmAnd live
* OsmAnd will display "Internet access: yes" as POI category instead of the original POI category (cafe, restaurant, whatever...).

With the next monthly map update the problem will be gone.

**Comment by Erlendur22** [comment] 2023-06-06 11:12
Hi Alex.

Yes, I did add the Internet_access tag, but only after I deleted it for test purposes. The Miniatur Wunderland node showed the same behavior BEFORE I changed anything. That's why I noticed this in the first place. After that I saw it on other nodes like the cafe too. 
I don't know myself if this particular node had been edited just before I saw it. If this bug in Osmand will be gone with the next monthly map update, then it's fine. Let's see. I will keep it in mind.

**Comment by xmd5a2** [comment] 2023-06-09 11:56
@scaidermern Hi. I've tried to reproduce this using your guide step-by-step but failed. I edited this node:
https://www.openstreetmap.org/node/1836595805

**Comment by xmd5a2** [comment] 2023-06-09 12:01
Finally I've reproduced this with [this node](https://www.openstreetmap.org/node/1272294270).
![Screenshot_2023-06-09-14-59-15-892_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/6da923b2-c93e-4658-bb3a-4944339aa5e9)
(POI description displays info about internet access but icon is from hotel POI)

**Comment by vshcherb** [comment] 2023-06-13 13:56
Also POI search by name is broken 

![telegram-cloud-photo-size-4-5780556699860582116-y](https://github.com/osmandapp/OsmAnd/assets/1042025/b1fa6c31-485c-4839-92c3-d287a7cb7040)

**Comment by vshcherb** [comment] 2023-06-20 10:59
Should we have different order to sort POI's or hard code some POI types in POI Search / POI on the map / Context menu

**Comment by Erlendur22** [comment] 2023-06-20 15:01
Thanks to all OSMand developers for taking this/mine issue serious. I appreciate it. 
Meanwhile I am in Italy and observe the same behavior there on restaurant/cafe nodes which have Internet access = yes. 
(Kinda obvious, for it's not a OSM data problem but a Osmand app one).

Strange is, that only the Internet tag causes such behaviour, no other tag shows same dominant behavior. And it's not limited to restaurants and cafes, as my initial post showed with the "Miniatur Wunderland" tourist attraction in Hamburg.

I follow the post interested and hope a solution can be found. Thanks.

**Comment by vshcherb** [comment] 2023-06-20 17:34
All POI that come from 1 point has that bug but you might only notice on A) Building B) Internet access C) Toilets

**Comment by ivanPyrohivskyi** [comment] 2023-07-14 11:14
McDonald's New-York, Manhattan.
Before/after:
<img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/e4b40676-44a7-4a0f-8290-aa90ecfbd166" /> <img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/66608b59-1af0-4466-8a17-5eeaa19de2cb" />

**Comment by ivanPyrohivskyi** [comment] 2023-07-14 11:30
Will fix in new maps after 01/08/2023
[Map for test](https://drive.google.com/file/d/1uaxK8ObiNg9PKUR_q4pXZ0EnASdRPoqM/view?usp=sharing) (New-York, Manhattan)

**Comment by scaidermern** [comment] 2023-08-06 06:06
Can still be reproduced:

![IMG_20230806_080558](https://github.com/osmandapp/OsmAnd/assets/1040784/52363818-d669-4bf9-93b1-594be0637df7)

https://www.openstreetmap.org/node/4431452831

OsmAnd 4.5.9

**Comment by DmitryAlexei** [comment] 2023-08-07 08:51
OsmAnd~ 4.6.0#571m, released: 2023-08-07 + fresh France Grand Est Bas-Rhin map 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/4ecbb4a8-ab10-4bcf-873e-19168299969a"  width="300" height="auto"/> </td>
  </tr>
</table>

@scaidermern You may need to update your maps to the latest version

**Comment by scaidermern** [comment] 2023-08-07 09:06
> @scaidermern You may need to update your maps to the latest version

Maps are from August.

**Comment by scaidermern** [comment] 2023-08-07 15:20
I've deleted live updates and downloaded them again. The problem persists.

The base map is France_great-east_bas-rhin_europe.obf

**Comment by vshcherb** [comment] 2023-08-07 17:54
Do you have other maps? https://download.osmand.net/download?standard=yes&file=France_great-east_europe_2.obf.zip delete it

**Comment by pebogufi** [comment] 2023-08-07 18:05
I have also the same situation since a very long time (i suppose months). I am shure not to have duplicate maps of the same region. I use osmand since version 0.73, I am aware of the problems of duplicate maps of same region.
Also have it on two devices.

**Comment by vshcherb** [comment] 2023-08-07 18:11
It's strange, and POI if you Show On Map by Name - tested with new maps and McDonald's

**Comment by pebogufi** [comment] 2023-08-07 18:16
After testing some pois i see the problem only if
internet_access:fee is also set.

**Comment by scaidermern** [comment] 2023-08-07 18:43
> After testing some pois i see the problem only if internet_access:fee is also set.

Maybe 🤔

@vshcherb Maybe it also depends on the POI type. @pebogufi and I encountered this bug with a tourism POI. You tested a fast food place instead 🤷‍♂️

**Comment by pebogufi** [comment] 2023-08-07 18:54
... and it is a differenc whether i select a poi from a select result list (no problem) or from the map (problem)

**Comment by Erlendur22** [comment] 2023-08-07 19:04
Hey there, 

the guy who opened that thread ;-)

I checked the two POIs I used as the initial example of that issue (and a few more POIs) and I have to say, the _tourism_ POI as well as the _cafe_ and the _pub_ POIs, all with Internet_access - They all got fixed. It now shows the correct category, in the search list as well as after selecting it on the map. 

But as I read now in the comments, the problem persists with other POIs and in other maps. Damn, that makes no sense and it makes it so difficult for you programmers, such an inconsistent bug :-( 

Logically I would also say, it has something to do with old maps other people have. But it got mentioned so often, that I think, whoever posts something here, knows about the simple step of using up-to-date maps. 

Cross fingers, that this bug gets fixed for ALL POIs.

**Comment by scaidermern** [comment] 2023-08-07 19:14
@Erlendur22 This bug only seems to happen with OsmAnd live. The newly mentioned POIs will be fixed after new basemaps for September are generated. That's why your examples also have been fixed meanwhile.

**Closed** 2023-08-18 10:05 UTC
Labels: search, !

**Comment by DmitryAlexei** [comment] 2023-08-31 06:50
The issue is still present with live updates
- OsmAnd~ 4.6.0#698m, released: 2023-08-30 
- Coordinates 48.58913° N, 7.73874° E 
- France Grand est map

<table style="width:100%">
  <tr>
    <th>With live updates</th>
    <th>Without live updates</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/e91e7b31-2798-4b79-bc21-1f6bddf49ff9"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/854ba8c0-5277-49f1-a8eb-f28a2520f75f"  width="300" height="auto"/> </td>
  </tr>
</table>
