### ISSUE TITLE
Be more considerate of user feedback

### ISSUE THREAD

**Issue by keunes** [osmandapp/Osmand#2730] opened 2016-06-20 15:33 UTC
I understand there's limited time and there might be other rationales to keep the list of issues limited to a certain degree. But how @vshcherb often closes issues immediately after giving a non-response (i.e. replying without addressing the OP's actual arguments) and thereby shutting off any (perceived) chance for community members to exchange thoughts with the developers, I find really frustrating.

If you gave a reply, at least give the OP the opportunity to give a response to that. In my cases (I'm talking #2166, #2539, #2692 and #2691) this was not the case, giving me the impression that different viewpoints are not appreciated & disregarded, which is really off-putting to me in any case. _Especially_ when you _explicitly express_ the hope to be able to exchange thoughts.

I sincerely hope active project members @alexey-pelykh, @GaidamakUA, @sonora, @vshcherb, @yvecai) can discuss how they deal with non-code contributions (viewpoints, experiences etc of users) here on github.

**Comment by vshcherb** [comment] 2016-06-22 23:34
User feedback is very important, though Github for us is a working bug-tracker system. "Closed" usually means that there will be no immediate action or it will be taken into account in new design, basically it means it is not a bug.

Cause mostly I'm acting as a product owner, it is my responsibility to maintain github issues which for us is very important. Because it gives a possibility to display open development and display the issues which will be focused on very soon. We did in the past (closing github issues) and I don't want get back to it again, but the time we can dedicate to Github is very limited. 

All you replies to the issue are  sent out to everyone even if it is closed and everyone could reply not only me.

**Closed by vshcherb** 2016-06-22 23:34 UTC
