### ISSUE TITLE
Map rendering stops while using a gpx track 

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4379] opened 2017-09-01 10:44 UTC
When setting a gpx track to be visible on the map and selecting 'Analyse on map' the loading track will not display and the map will not update. Zooming in and out results in blank space around the small portion of the pre-rendered map tile. 
Zooming in and out seems to work fine if a track isn't loaded.

Reinstallation doesn't help. 

Device: Samsung Galaxy S6 running Android 7.0

Example track: https://goo.gl/yVaZxJ

Screenshots:
![screenshot_20170830-213812](https://user-images.githubusercontent.com/20681525/29966621-672e4de8-8f1b-11e7-988a-466986c59de8.png)
![screenshot_20170830-213822](https://user-images.githubusercontent.com/20681525/29966622-672eb562-8f1b-11e7-8384-dfa86f41c30a.png)

**Comment by sonora** [comment] 2017-09-02 07:13
This seems an exact duplicate of what I have reported in #4181.

Subsequent research seemed to indicate that this is a phenomenen somehow during the upgrade of the GPX database. Strangely, when using any other method of displaying GPX tracks on the map, everything works fine from the start.

But when going via Analyze on map, I find this issue on pretty much all devices recently upgraded to our new OsmAnd versions. 

Looks like leaving OsmAnd on with the map screen running for something like 30 min to several hours eventually fixes this (time needed may depend on how many files are in your tracks folder, not sure). But this can only be a workaround  It is also unclear, which future events may cause the issue again, like e.g. bulk adding more tracks to your device, or future OsmAnd updates.

Root cause why this affects the map rendering when and only when going via the Analyze on map button is certainly needed here.

From what I know, dozens of users experience this but cannot pinpoint exactly why - most suspect they sonehow lost map files or OsmAnd got corrupted.

**Comment by vshcherb** [comment] 2017-09-20 19:15
@sonora  thanks for comment. Looks like we need to have a progress displayed for GPX database to be updated.

**Closed by vshcherb** 2017-09-20 19:15 UTC
