### ISSUE TITLE
4.7.8 it crashes systematically on launch

### ISSUE THREAD

**Issue by cricri-du-lauragais** [osmandapp/OsmAnd#19568] opened 2024-04-15 16:48 UTC
### Description

since upgrading my version + to 4.7.8 it crashes systematically on launch, I've cleared the cache and rebooted the phone (android samsung) and still the same, I can't access anything

### Steps to reproduce

can't access anything

### Actual result

can't access anything

### Expected result

with the prior version i have no problem ;)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.8
Android/iOS version: 14
Device model: samsung A33
Crash-Logs: ?
```
Version  OsmAnd 4.7.8
15.04.2024 6:38:57
Apk Version : 4.7.8 4708
Exception occurred in thread Thread[AsyncTask #2,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.database.sqlite.SQLiteException: no such column: totalDistance (code 1 SQLITE_ERROR[1]): , while compiling: UPDATE gpxDirTable SET fileName = ?, fileDir = ?, totalDistance = ?, totalTracks = ?, startTime = ?, endTime = ?, timeSpan = ?, expectedRouteDuration = ?, timeMoving = ?, totalDistanceMoving = ?, diffElevationUp = ?, diffElevationDown = ?, avgElevation = ?, minElevation = ?, maxElevation = ?, minSpeed = ?, maxSpeed = ?, avgSpeed = ?, points = ?, wptPoints = ?, color = ?, fileLastModifiedTime = ?, fileLastUploadedTime = ?, fileCreationTime = ?, splitType = ?, splitInterval = ?, apiImported = ?, wptCategoryNames = ?, showAsMarkers = ?, joinSegments = ?, showArrows = ?, showStartFinish = ?, use3dTrackVisualization = ?, width = ?, gradientScaleType = ?, smoothingThreshold = ?, minFilterSpeed = ?, maxFilterSpeed = ?, minFilterAltitude = ?, maxFilterAltitude = ?, maxFilterHdop = ?, startLat = ?, startLon = ?, nearestCityName = ?, maxSensorTemperature = ?, avgSensorTemperature = ?, maxSensorSpeed = ?, avgSensorSpeed = ?, maxSensorPower = ?, avgSensorPower = ?, maxSensorCadence = ?, avgSensorCadence = ?, maxSensorHr = ?, avgSensorHr = ?, dataVersion = ? WHERE fileName = ? AND fileDir = ?
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1540)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:975)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2652)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2630)
	at net.osmand.plus.api.SQLiteAPIImpl$SQLiteDatabaseWrapper.execSQL(SQLiteAPIImpl.java:133)
	at net.osmand.plus.track.helpers.GPXDatabase.updateGpxParameters(GPXDatabase.java:132)
	at net.osmand.plus.track.helpers.GPXDatabase.updateGpxParameters(GPXDatabase.java:118)
	at net.osmand.plus.track.helpers.GPXDatabase.updateDataItem(GPXDatabase.java:110)
	at net.osmand.plus.track.helpers.GpxDbHelper.updateDataItem(GpxDbHelper.java:142)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:94)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:38)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

**Comment by scaidermern** [comment] 2024-04-15 16:55
Duplicate of #19535?

**Comment by yuriiurshuliak** [comment] 2024-04-16 07:28
Could you please test our nightly version to see if this issue persists? You can download it from this link: [nightly builds](https://osmand.net/docs/versions/nightly_versions#nightly-builds).

**Comment by cricri-du-lauragais** [comment] 2024-04-16 10:09
> Could you please test our nightly version to see if this issue persists? You can download it from this link: [nightly builds](https://osmand.net/docs/versions/nightly_versions#nightly-builds).

Hello, the nightly version works, the only strange thing unrelated to the crash is the behavior of the plus and minus zoom buttons on the map, which always return in 2.5D, forcing you to press the 2D/3D button to return to the top view.
Thank you for your work and your responsiveness.

**Comment by DmitryAlexei** [comment] 2024-04-16 10:26
@cricri-du-lauragais thanks for your feedback.
Strange behavior of +- buttons will be fixed in this issue https://github.com/osmandapp/OsmAnd/issues/16027

**Comment by vshcherb** [comment] 2024-04-16 15:28
4.7.9 just released

**Closed** 2024-04-16 15:27 UTC
