### ISSUE TITLE
Missing information in details of POI 

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#6825] opened 2019-04-14 11:06 UTC
for tourism=museum there are important information not shown, which are in the database since more than a year:
opening_hours, website, email.

osmand 3.3.0#27129 (2019-04-04)
map germany badem-wuerttemberg 2019-04-01
![Screenshot_20190414-124515_OsmAnd~](https://user-images.githubusercontent.com/18628183/56091947-0310c400-5eb6-11e9-9df7-b37968b830bd.jpg)
![Screenshot_20190414-124531_Firefox~01](https://user-images.githubusercontent.com/18628183/56091951-0b68ff00-5eb6-11e9-99d0-77a09632f3d8.jpg)

**Comment by pebogufi** [comment] 2019-04-14 14:55
This only happens when I make a long tap on the poi symbol of the museum.
If I select the result line of the search, then all information is available.

**Comment by xmd5a2** [comment] 2019-04-15 14:14
Duplicate of https://github.com/osmandapp/Osmand/issues/6497

**Closed by xmd5a2** 2019-04-15 14:14 UTC
