### ISSUE TITLE
Multi-polygon relations IDs link to non-existent OSM objects

### ISSUE THREAD

**Issue by ricloy** [osmandapp/OsmAnd#15907] opened 2022-12-07 09:05 UTC
### Description
This problem was already reported in this closed issue: #13686.

On OpenStreetMap, sometimes, shops or amenities are mapped as multi-polygon relations. For this kind of POIs, when looking in the detail info, OsmAnd will provide a link to an OSM object which doesn't exist.

### How to reproduce?

On OsmAnd, search for a POI which has been mapped as a multi-polygon relation on OSM, tap on "Details" and then tap on the OSM link. Some examples can be found with the following Overpass-Turbo query: https://overpass-turbo.eu/s/1oLq

#### Examples:

1. Florence in Tuscany (Italy)
Name: "Maxismall Tecno Sport"
**POI type:** shop
**OSM relation ID:** https://www.openstreetmap.org/relation/6839682
**OsmAnd relation ID:** https://www.openstreetmap.org/relation/2203879606272

2. Milan in Lombardia (Italy)
**Name:** "Mondo Convenienza"
**POI type:** shop
**OSM relation ID:** https://www.openstreetmap.org/relation/6453804
**OsmAnd relation ID:** https://www.openstreetmap.org/relation/2203484467200

3. Bastia in Corsica (France)
**Name:** Crédit Agricole"
**POI type:** bank
**OSM relation ID:** https://www.openstreetmap.org/relation/1673474
**OsmAnd relation ID:** https://www.openstreetmap.org/relation/2200736892928

### Your Environment
**OsmAnd Version:** OsmAnd+ 4.2.7 2022-07-13
**Android/iOS version:** Android 11
**Device model:** Redmi Note 9 Pro

**Comment by Zirochkabila** [comment] 2022-12-07 15:56
OsmAnd~ 4.4.0#14003mqta, released: 2022-12-07
Not reproduced 
Polygon identifiers refer to existing OSM objects
Perhaps this is due to [15709](https://github.com/osmandapp/OsmAnd/issues/15709)


https://user-images.githubusercontent.com/104760013/206227064-359d1ebc-6316-4dbe-967e-e794bd9d8e0e.mp4

**Comment by vshcherb** [comment] 2022-12-07 17:42
Fixed in 4.3 likely

**Closed by vshcherb** 2022-12-07 17:42 UTC

**Comment by ricloy** [comment] 2022-12-13 09:12
I confirm that this issue is fixed in OsmAnd+ 4.3.2 (2022-12-08). Thank you!
