### ISSUE TITLE
Single-click quick action button without a secondary action

### ISSUE THREAD

**Issue by NunoAlvesEnduro** [osmandapp/OsmAnd#18530] opened 2023-11-09 11:50 UTC
### Describe the idea (required)

To have the ability to use the quick action button with only a single action

### Tell us about the expected behaviour (required)

I hope that when I place the quick action button, clicking on it will not open a second window to choose again which action I want. I want a single click to execute the only action defined, without a second action.

### Tell us about alternatives you've considered (required)

I didn't find an alternative, so I did the following: I activated the quick action button, chose the "add map marker" option, then on the main screen, I click once on the quick action button and have to click again on the action I want to do (in this window, the action I previously chose appears, plus the window with "+" to choose more options).

**Comment by DmitryAlexei** [comment] 2023-11-09 16:00
Duplicate of https://github.com/osmandapp/OsmAnd/issues/10197

**Comment by NunoAlvesEnduro** [comment] 2023-11-09 16:50
Good afternoon, when configuring the quick action button, I delete everything and then add only one quick action. However, the "+" for other options appears again, even though I have deleted everything. When going to the main screen and clicking on the quick action button, the menu with more than one choice appears again. Am I configuring it in a wrong way? Thank you for your help.
![WhatsApp Image 2023-11-09 at 16 41 45 (1)](https://github.com/osmandapp/OsmAnd/assets/150346280/d65c21e5-5925-4058-ba8a-6371595bf2d6)
![WhatsApp Image 2023-11-09 at 16 41 45](https://github.com/osmandapp/OsmAnd/assets/150346280/4f89a4ff-af30-4eab-8cd2-6c5112c6e0c6)

**Comment by DmitryAlexei** [comment] 2023-11-09 16:57
@NunoAlvesEnduro as of now, this is the expected behavior

**Comment by NunoAlvesEnduro** [comment] 2023-11-09 17:05
Thanks i made a observation on the #10197

**Closed** 2023-11-17 16:04 UTC
