### ISSUE TITLE
Rendering issues (The Netherlands)

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6239] opened 2018-10-31 13:52 UTC
Land is rendered as water at certain zoom levels. 
![image](https://user-images.githubusercontent.com/40493090/47792531-e2e4b280-dd24-11e8-946b-2c20aef39fe5.png)
![image](https://user-images.githubusercontent.com/40493090/47792545-eaa45700-dd24-11e8-88b2-7fc9c3373210.png)

**Comment by pangoSE** [comment] 2018-11-04 13:28
I have the same issue in Härnön, Västernorrland, Sweden

**Comment by pangoSE** [comment] 2018-11-04 13:33
This is a duplicate of #6203

**Closed** 2020-06-08 13:56 UTC
