### ISSUE TITLE
ETA much higher when using imported gpx to navigate

### ISSUE THREAD

**Issue by NimdaBE** [osmandapp/OsmAnd#9625] opened 2020-08-13 11:33 UTC
OSMAND+ 3.7.4

When i navigate from point A to B i get a realistic ETA/duration. When i create a gpx file (with for example maps.openrouteservice.org) with the route from A to B the ETA/duration is much higher (about double or more). How come? Because the distance is the same... Does it not properly calculate the route when driving along a gpx, or does it use other default (slower) speed settings so it estimates longer driving times?

For example: i got a route of 14km and OSMAND gives me an estimate of 48 minutes (which is realistic). When importing a gpx with the same route of 14km, it gives me a duration of 1h23 minutes... When you receive gpx-files from friends it would be handy to get a realistic eta as well...

It would be usefull to have a recalculation (or the choice to do so) of the route with the underlying map data when using an imported gpx to get a realistic eta/arrival time...

**Comment by scaidermern** [comment] 2020-08-13 11:47
This is caused by #3908. Currently for external GPX files OsmAnd assumes an average speed and doesn't match it against the actual road data. Therefore the ETA is typically wrong and various features (speed limits, lane guidance, announcement of road names) don't work as expected.

**Comment by vshcherb** [comment] 2020-08-14 14:45
Merged to #3908

**Closed** 2020-08-14 14:45 UTC
