### ISSUE TITLE
OsmAnd Live Update now bugs

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#6038] opened 2018-09-13 15:28 UTC
1. After you click Update now timestamp in the list is not updated (even though in dialog it is updated)
2. There is no indication whether new files are going to be downloaded or not and it is not clear if there is any error or not.

**Comment by AlexSyt** [comment] 2018-09-14 07:51
Duplicate of #5808 ?

**Closed** 2018-09-17 11:16 UTC
