### ISSUE TITLE
Smaller display setting in Android makes UI partially bigger

### ISSUE THREAD

**Issue by seekingmeanings** [osmandapp/OsmAnd#15704] opened 2022-11-12 19:37 UTC
### Description
I used my phone for some time with default Screen size settings. I changed it small to see more things on the screen but now the UI is extremely large. All the menus shrank and are normal, except the driving UI

### How to reproduce?
Change "Display Size" in the Android settings to "Small"

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: 11
Device model: Fairphone 4

**Comment by vshcherb** [comment] 2022-11-13 14:34
Please provide screenshots

**Comment by seekingmeanings** [comment] 2022-11-14 08:25
With the following default setting of the display size:
![Screenshot_20221114-091537.png](https://user-images.githubusercontent.com/84940126/201610746-b12f75bd-8c4d-4ffd-9696-a525d47a7ef8.png)
![Screenshot_20221114-091541.png](https://user-images.githubusercontent.com/84940126/201610786-6a510ee4-3167-4389-bc00-8f77e55aebd0.png)![Screenshot_20221114-091547.png](https://user-images.githubusercontent.com/84940126/201610791-02bec912-a224-4a7f-afb7-f5284e15b846.png)

But if I change it know to "Small":
![Screenshot_20221114-091529.png](https://user-images.githubusercontent.com/84940126/201610925-6897c08c-54a5-4198-98dc-7835961e09ab.png)![Screenshot_20221114-091454.png](https://user-images.githubusercontent.com/84940126/201610947-91027cac-25b3-4757-8f52-0f033a9cd8f7.png)![Screenshot_20221114-091448.png](https://user-images.githubusercontent.com/84940126/201610957-fa05fa1c-f0f1-4b5a-8016-420c232da102.png)
Notable is here that that most of the UI shrinks normal.

**Comment by joshuabach** [comment] 2023-02-09 18:57
I am experiencing the exact same issue on a fresh phone with LineageOS and freshly installed OsmAnd+ (from F-Droid)

Android Version: 13
LineageOS Version: 20-20230126-microG-lemonadep
OsmAnd Version:  OsmAnd~ 4.3.5

**Comment by seekingmeanings** [comment] 2023-02-09 20:54
noticed recently that the bug is not occurring in landscape mode

**Comment by joshuabach** [comment] 2024-03-29 07:36
At some point, this issue wen't away for me, without me changing the display settings. I can't recall when the UI size went "normal" again or if I did anything to fix it. To be honest, I totally forgot about the issue.

Today, I upgraded to Android 14 (LineageOS 21) and now the issue is back. Very confusing to me, but maybe this information helps.

I can also confirm that the issue is not present in landscape mode.

**Comment by vshcherb** [comment] 2024-04-02 11:12
We're going to fix it in 4.8 but before we need to make size customizable cause we want to let Tablet users to have bigger buttons.

**Comment by an-dr-eas-k** [comment] 2024-07-27 16:03
My setting on pixel 8 is the following:
![Screenshot_20240727-175526](https://github.com/user-attachments/assets/d1eed205-39cc-4364-8845-bf5209616e60)

And osmand shows way too large buttons, see 
![Screenshot_20240727-175807](https://github.com/user-attachments/assets/63a632ee-9a0f-4f2b-ae4a-c2e52e264256)

My workaround is really to change display setting whenever I do a day of osmand-navigating. I feel embarrassed when my folks look at my screen, with these enormous buttons. Please don't let 4.8 pass without the fix.

**Comment by DmitryAlexei** [comment] 2024-08-01 13:11
Duplicate of https://github.com/osmandapp/OsmAnd/issues/18357
will be fixed in 4.9

**Closed** 2024-08-01 14:11 UTC
Labels: Observed
