### ISSUE TITLE
+4.7.1 seems to corrupt existing favorites files when adding favorites

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19179] opened 2024-02-24 12:17 UTC
### Description

Recently I have created a new favorite group/file, growing to about 240 favorites for my next trip. The last changes I did on Feb 5th, then it worked fine (4.7.1 was released Feb 6th).
Today I added some more spots, maybe 7 or 8 (selecting in the map, add to favorite, set color and symbol).
But at the next start of the app this group of favorites was not listed/displayed anymore in the "my places" (though the file exists in osmands favorite folder!).

This happens in +4.7.1
Doing the same in +4.7.0 works fine (and this file can be copied to a +4.7.1 and work there too)

### Steps to reproduce

add favorites

### Actual result

the file seems somehow to get corrupted, anyway it is not displayed/accessable anymore.

### Expected result

not doing so :-)
See the attached file. 
This file is not displayed anymore in the "my places". Before adding the last spots is was working fine.
Please solve, thanks.

(had to rename it from .gpx to .txt for uploading)

[favorites-_Georgien 24 to see.txt](https://github.com/osmandapp/OsmAnd/files/14392776/favorites-_Georgien.24.to.see.txt)

### Your Environment (required)

+4.7.1 Android

**Comment by tch123** [comment] 2024-02-25 09:42
I also encountered the same problem on Android. Happened when I added favorites using Tasker+API.
After this happens,  can only use the backup to restore your previous favorites.

**Comment by Rowin63** [comment] 2024-02-25 10:08
Hm. I don´t really understand what is going wrong here.
When adding a favorite to an existing group/file, never before an additional NEW favorites-file was created. 
But now ths happens, see the pic. 
And only one of this two files is displayed in "my places". 
This probably was yesterday´s reason, why after deleting the second one, Osmand didn´t show the other one anymore.

![Favorites after Android Update](https://github.com/osmandapp/OsmAnd/assets/95540936/05ba6246-e6eb-44e8-a302-59ddb58516ca)

Tried it on three devices and it happens only on one device - on the one that had an Android-Update a few days ago (running +4.7.1 on it). The two other devices behave as usual: adding favorites to a folder > folder gets updated, and does not create a new one.

Must be an Android-Issue, somehow...
I also don´t have access to Osmands Data Folder anymore via file commander on the phone. Only connected to a PC I can access Osmands Data Folder.

Strange thing, making my data handling/sharing difficult.

**Comment by Rowin63** [comment] 2024-02-25 10:52
Anyway, Osmand´s behavior with Favorites is a bit "strange". 
I´m editing the "favorite-XY-file" in one device, copy this file to another device, but the changes (deleting some favorites) don´t show up. Still 255 favorites exist instead of 250 (I deleted some).
Even after deleting the FILE from Osmand´s data directory all this favorites remain still on display... I have to delete this data directly in Osmand in the "my places" menu...

**Comment by pebogufi** [comment] 2024-02-25 14:56
> Deleting in the app >>> deletes the file.gpx
> Deleteing the file.gpx (via manager) >>> does not delete the favorites in the app (not even after a restart)...

Yes, your are right. The management of favorites happens in a internal database, the files "favorite-XY-file" in directory favorites are just copies, which can be used by the user for other purposes.
So when sharing such a file to a other device when single items have been deleted, then delete the fav-group in 2nd device inside of osmand before importing the shared file.

**Comment by Rowin63** [comment] 2024-02-25 17:15
What a sh.t...
I thought I can handle the situation.
Was adding a bunch of favorites to my tour plan and... after this Osmand does not read this favorite file anymore.

**Comment by Rowin63** [comment] 2024-02-25 18:04
Sorry for being that busy here, but that drives me crazy a little bit...

After a phone restart Osmand does accept the "previous" backup file again also on device "A".

**Comment by Rowin63** [comment] 2024-02-25 20:51
Compared both files in an editor (the previous working one, containing 253 favorites, and the other non working one with 16 new favorites added in the app) (marking in the map > save as favorite > selecting the group, symbol and color)

After deleting the 16 changes in the non working file and copy it in Osmand´s favorite-folder, the file was accepted and the favorites shown again.

So the problem has to be somewhere in this 16 differences, but I didn´t find it yet.
Here´s the differences (renamed .gpx to .txt for uploading):

[Diff.txt](https://github.com/osmandapp/OsmAnd/files/14397794/Diff.txt)

**Comment by Rowin63** [comment] 2024-02-25 22:48
Startet over from the beginning with a working favorite-file, but this time on device "B" (the one without latest Android Update).
Set again all the new favorites one by one and at the end it worked.
Finally I copied this updated file to device "A" and it worked too.

So it seems (the basic favorites-file was the same on both devices): 
adding favorites on device "A" corrupts the file.
adding the same favorites on device "B" works fine.


Device "A": S20+5G, latest Android SW-Update installed; Osmand +4.7.1 
Device "B": S20+, latest Android SW-Update NOT installed yet; Osmand +4.7.1

**Comment by yuriiurshuliak** [comment] 2024-02-26 13:46
Please specify are you manually copying favorites or using the export option within the OsmAnd app? Does the problem persist if you use the export option through the app instead of manual copying?
Also have you tried starting with a working favorite file on the device with the latest update, adding favorites, and checking if the issue persists?

**Comment by Rowin63** [comment] 2024-02-26 13:55
Yes, the working favorite file did work on the device with the update. But (as it seems to me) since the update, when I add favorites to a group/file (I do this inside osmand app, making a spot on the map and tap the favorite icon!), then the file gets somehow corrupted. It still is in Osmands favorite folder, but after a app restart it's not shown in Osmands "my places" anymore. I can add favorites one by one, like always. But then you close osmand and at the next start this group is not visible in "my places" anymore (but via PC I see, it still exists there).

**Comment by Rowin63** [comment] 2024-02-26 13:58
Before the update I always was copying the favorite files to the other device. This never was a problem.
Since the last Android update I don't have access anymore with my file manager to osmands data, so since now I do export the favorite groups.

**Comment by Rowin63** [comment] 2024-02-26 14:49
>... Also have you tried starting with a working favorite file on the device with the latest update, adding favorites, and checking if the issue persists?

This is exactly how the problem began. Adding new favorites to an existing group on the device with the latest update (a few days ago)

**Comment by vshcherb** [comment] 2024-02-26 16:02
I didn't reproduce the issue with file duplicate, so when you add the favorites. The whole file is resaved.

And 2nd topic that when you import a new file with less favorites, it won't work cause importing files doesn't delete favorites and only add or update.

**Comment by vshcherb** [comment] 2024-02-26 17:53
Don't know, didn't reproduce it.

**Comment by Rowin63** [comment] 2024-02-26 19:35
You didn´t or you couldn´t?

I gave it another try and I think I got one step closer. 
Probably it has nothing to do with Androids update, but with the content/code of the files.

Device "A":
Created a new group "A01" and added 1 favorite in it. Group is displayed in "my places".
It´s this one (as usual, renamed .gpx to .txt for uploading).

Then I created another new group "A16" and added 1 favorite in it. Then I took this file and added those 15 favorites from yesterday that caused the problem (this are not favorites from somewhere else, but they all are created in Osmand. So the code is what Osmand creates. It´s this two:

[favorites-_Test A01.txt](https://github.com/osmandapp/OsmAnd/files/14409802/favorites-_Test.A01.txt)
[favorites-_Test A16.txt](https://github.com/osmandapp/OsmAnd/files/14409824/favorites-_Test.A16.txt)


Device "B":
Same procedure as above. Creating "B01" and "B16" with the same content as "A01" and "A16".
It´s this two:

[favorites-_Test B01.txt](https://github.com/osmandapp/OsmAnd/files/14409836/favorites-_Test.B01.txt)
[favorites-_Test B16.txt](https://github.com/osmandapp/OsmAnd/files/14409843/favorites-_Test.B16.txt)


And again: 
the files with the additional 15 favorites that caused the problem yesterday do the same today. 
Both "X16" files are not recognized in Osmand. They are in Osmand´s favorites folder, but they are not displayed in "my places".

![Screenshot_20240226_201939_Solid Explorer](https://github.com/osmandapp/OsmAnd/assets/95540936/da7ad258-d52e-4861-b2b2-2650b51e5340)

![Screenshot_20240226_201924_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/19a4571d-a494-4c39-86a9-09c9da1721f5)

The problem mus be hidden somewhere in the files.
But what and why?

**Comment by Rowin63** [comment] 2024-02-27 08:45
I gave it another try and I think I got one step closer.
Probably it has nothing to do with Androids update, but with the content/code of the files.

Device "A":
Created a new group "A01" and added 1 favorite in it. Group is displayed in "my places".

Then I created another new group "A16" and added 1 favorite in it. Then I took this file and added those 15 favorites from yesterday that caused the problem (this are not favorites from somewhere else, but they all have been created in Osmand. So the code is what Osmand creates. 
It´s this two (renamed .gpx to .txt for uploading):

[favorites-_Test A01.txt](https://github.com/osmandapp/OsmAnd/files/14409802/favorites-_Test.A01.txt)
[favorites-_Test A16.txt](https://github.com/osmandapp/OsmAnd/files/14416691/favorites-_Test.A16.txt)


Device "B":
Same procedure as above. Creating "B01" and "B16" with the same content as "A01" and "A16".
It´s this two:

[favorites-_Test B01.txt](https://github.com/osmandapp/OsmAnd/files/14409836/favorites-_Test.B01.txt)
[favorites-_Test B16.txt](https://github.com/osmandapp/OsmAnd/files/14416702/favorites-_Test.B16.txt)

And again:
the files with the additional 15 favorites that caused the problem yesterday do the same today.
Both "16" files are not recognized in Osmand. They are in Osmand´s favorites folder, but they are not displayed in "my places".

![Screenshot_20240226_201939_Solid Explorer](https://github.com/osmandapp/OsmAnd/assets/95540936/98085315-3871-4368-bc0d-2dbda3451204)

![Screenshot_20240226_201924_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/cfb5c5ca-2d68-431b-bc2f-8b4b4097a0a8)


The problem mus be hidden somewhere in the files.
But what and why?

**Comment by pebogufi** [comment] 2024-02-27 12:51
Yes the problem is in this file:
[favorites-_Test.A16_ERROR.gpx.txt](https://github.com/osmandapp/OsmAnd/files/14419630/favorites-_Test.A16_ERROR.gpx.txt)
I made test with RouteConverter, this file causes an error when i try to open it with RouteConverter, may be this can help.
The line with text "ERROR_IN_THIS_LINE" causes the bug.

**Comment by Rowin63** [comment] 2024-02-27 12:54
> Yes the problem is in this file: [favorites-_Test.A16_ERROR.gpx.txt](https://github.com/osmandapp/OsmAnd/files/14419630/favorites-_Test.A16_ERROR.gpx.txt) I made test with RouteConverter, this file causes an error when i try to open it with RouteConverter, may be this can help. The line with text "ERROR_IN_THIS_LINE" causes the bug.

Dear pebogufi,
Thank you so much for helping!!!

**Comment by pebogufi** [comment] 2024-02-27 12:55
Looks like that there are tags used which are not declared, may be more than i detected.

**Comment by Rowin63** [comment] 2024-02-27 12:58
anyway, you veryfied that issue, which almost drove me crazy the last days...

**Comment by Rowin63** [comment] 2024-02-27 13:08
But thats not all...

The same favorite is in this file, contains the same tag and here it works... (line 460-482)
[favorites-_Georgien 24 to see v3.txt](https://github.com/osmandapp/OsmAnd/files/14419879/favorites-_Georgien.24.to.see.v3.txt)

But unfortunately don´t remember on which device I created this file.

**Comment by yuriiurshuliak** [comment] 2024-03-22 10:39
Could you please confirm if this issue has been resolved and can now be closed?

**Comment by Rowin63** [comment] 2024-03-22 11:20
Hi!

The issue "osmand corrupts favorite files" is dolved, because the reason (one corrupt favorite) was found.

What remains is the fact, that adding a certain point on the map as a favorite causes this problem.

So is it an Osmand issue or not? I don't know...
From my side it can be closed. We found the trigger of this issue.

**Comment by pebogufi** [comment] 2024-03-22 11:38
I have one more problem with the two example files.

favorites-_Test.A01.gpx
favorites-_Test.A16.gpx

I can't delete the favorite group any more.
Neither with 3dots, then delete nor using delete icon in bottom line then mark the groups then delete.
After closing the app, clear cache and opening again they are back.
If i rename it (removing the underscore) then after closing the app, clear cache and opening again the renamed file and the old one exists.
I suppose, the underscore at beginning might be the problem ?
Any ideas ?

**Comment by Rowin63** [comment] 2024-03-22 11:48
I use the underscore on every group I temporarily want to be listet on top, never had and have an issue with it.

**Comment by yuriiurshuliak** [comment] 2024-03-27 11:38
@pebogufi @Rowin63 If the issue is no longer reproduced on your end, could we consider closing this bug? Or should we explore whether there are lingering unresolved issues or questions that require further investigation?

**Comment by pebogufi** [comment] 2024-03-27 12:07
For me it is to close, thanks a lot.

**Comment by Rowin63** [comment] 2024-03-27 13:04
Yes, here too. Thank you!

**Closed** 2024-03-28 21:28 UTC
