### ISSUE TITLE
OsmAnd+ 2.4 regression: OsmAnd wants to drive "a complete round" in roundabouts

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#2920] opened 2016-08-07 15:40 UTC
Since OsmAnd+ 2.4 release, OsmAnd wants the driver to exit at the fifth instead of the first exit of roundabouts. When taking the first exit, the route is re-calculated. (It looks like in general that this release re-caclulates very often).
![screenshot_2016-08-06-21-04-07](https://cloud.githubusercontent.com/assets/6921696/17463445/e0a9f480-5cc5-11e6-89ee-66fa85861d0d.png)

**Comment by vshcherb** [comment] 2016-08-07 18:52
This is a duplicate of https://github.com/osmandapp/Osmand/issues/2574

**Closed by vshcherb** 2016-08-07 18:52 UTC

**Comment by Norbert80** [comment] 2016-08-09 17:35
Fixed in OsmAnd+ 2.4.2. Thanks!
