### ISSUE TITLE
[Feature request] exit numbers in voice guidance

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7063] opened 2019-06-20 08:08 UTC
The exit numbers are not included in the instructions. For example, when exiting the M6 the instruction says “keep left on M6”. “Take the exit” or “Exit left” may be more precise.

**Comment by scaidermern** [comment] 2019-06-20 09:42
Duplicate of #1347

**Closed** 2019-06-23 17:22 UTC
