### ISSUE TITLE
[Feature request] add online tile

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#8388] opened 2020-02-05 07:11 UTC
Since the OSM community in Spain agreed to use the aerial images from PNOA (Plan Nacional de Ortofotografía Aérea, del CNIG-IGN) to edit OSM in Spain, it may be added to the list of available online tiles.

The parameters are: 
URL: http://www.ign.es/wmts/pnoa-ma?request=GetTile&service=WMTS&VERSION=1.0.0&Layer=OI.OrthoimageCoverage&Style=default&Format=image/png&TileMatrixSet=GoogleMapsCompatible&TileMatrix={0}&TileRow={2}&TileCol={1} (http://www.ign.es/wmts/pnoa-ma?request=GetTile&service=WMTS&VERSION=1.0.0&Layer=OI.OrthoimageCoverage&Style=default&Format=image/png&TileMatrixSet=GoogleMapsCompatible&TileMatrix=%7Bz%7D&TileRow=%7By%7D&TileCol=%7Bx%7D) 
Minimum zoom: 1 
Maximum zoom: 20

**Comment by scaidermern** [comment] 2023-04-12 10:29
Duplicate of #8373?

**Closed** 2023-04-12 13:21 UTC
Labels: Nice to Have
