### ISSUE TITLE
Slow route (re) calculation

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/OsmAnd#3683] opened 2017-04-19 15:32 UTC
On long distances the route calculation is slow. This wouldn't be a problem but if a road is closed it seems to take the same amount of time to recalculate the route. In my case this was about 10 minutes. Maybe you miss the next possible route because of this.

Maybe both issues can be fixed if you assume that you usually use motorways on long distances so keeping the route after the motorway link and just recalculate the route to the link.
On first calculation it might be possible to start navigation after finding a route to the next motorway link. the rest of the route could be calculated in background.

**Comment by scaidermern** [comment] 2017-04-19 18:55
I noticed the same issue. A small deviation from the route results in a complete re-calculation which shouldn't be necessary. I don't know the current routing algorithm implementation. But I imagine a recalculation should be able to keep the previous route in mind while calculating a new one. At some point the new route might lead onto the old route, resulting in a combination of both routes and the recalculation process can be stopped early. Not sure if this is possible with the current implementation, though.

**Comment by vshcherb** [comment] 2017-04-27 10:01
Current routing algorithm tries to use previous route for 3 times before running full recalculation. It has a threshold of 20km, so first 20km are always recalculated

**Comment by bumbaras** [comment] 2018-01-31 08:03
I have the same issues with 2.8.2 and many earlier versions. Yesterday I have checked 250km distance and after 11 minutes the navigation was still calculating the route. It is unbearable and make this app totally useless now. And it wasn't so bad at the end of 2015 year (one, two minutes and route has been calculated). That is i have trashed 2.8.2, and will try to do some tests on versions 2.2 and 2.3 sideloaded. If it won't help, i will trash the app completely. Current online navigation mechanisms binded with OsmAnd are not acceptable as well because they are not respecting any navigation settings made in app.

Of course, official statement of developer is that my device is just too slow. I am aware that Android 4.1.2, qct msm8627 mtp and 1GB Ram are not attributes of speed demon, but well, I think that my old Lark and Mio485 have worse hardware but works much, much better (i know, they are dedicated devices and not on Android).

**Comment by bitboy85** [comment] 2018-01-31 14:43
i don't think it is a hardware related issue. This happens also on my cars head unit which has an octa core and 2gb ram.
Another thing where an unexpected long recalculation takes place is when you visit a rest area next to the motorway. Sometimes it takes minutes.

**Comment by bumbaras** [comment] 2018-01-31 23:34
2.3.5 - the same map data as 2.8.2, the same destination, the same source point. Default settings. Route calculated in about 4-5 minutes. 2.8.2 couldn't finish it in 12 minutes. I got to home from work so i didn't wait anymore over that 12 minutes. Still too long as You ask me, but much better.

**Comment by sonora** [comment] 2018-02-18 08:51
Possibly similar to #5030? Can you check if you also observe an order of magnitude faster pedestrian than car routing these days?

**Comment by bumbaras** [comment] 2018-02-19 00:38
Don't think so that this is the same issue. On short routes, for example 30-50kms the calculation is quite fast, as far as i remember. I would need to check this again because it was quite long ago (yes, versions 2.2 and 2.3).
Besides, i didn't put any results from my latest tests which might put support in wrong here. Returning to my previous post, I was happy that older 2.3.5 was able to calculate 250-300km distance in about 5 minutes, much short than 2.8.2. But the navigation is still unusable - older version may calculate route faster but if i choose the other way than navigation proposed, OsmAnd starts to recalculating route again and it takes next 4-5 minutes. And when calculation is over then it appears that new route still differs from my route and then calculation start again for next 4-5 minutes. So I am in fact driving without any navigation.
I have gave up with OsmAnd for now. I will try other application, AutoMapa, which is alternative (not free) to check how it will work on Sony Xperia M.

**Comment by cgogolin** [comment] 2018-09-16 12:51
I am currently using OSMAND on a long trip through Europe and route calculation over several hundred kilometers is painful slow to the extent that that is almost unusable, even on quite fast/recent hardware. I mostly use OSMAND for pedestrian navigation and always love it, but this is a problem that is rather seriously limiting its usefulness for longer trips.

Can long distance calculations not be done on a much simplified graph of just motorways and their rough intersections? Other navigation apps take only a split second for the same route for which OSMAND takes >10min :-(

**Comment by bumbaras** [comment] 2018-09-19 10:27
You have to compare other offline product.
Of course, if You take some offline mio product and compare it, the mio will be the speed beast in calculating routes even if the hardware is much worse than what You have in Your android device. The algorithm in the Osmand is probably to complex now and use too much details from maps and this is the result.
The most painful thing is not that it takes so much time to calculate route but when You take the other road Osmand had proposed then the calculation starts from the beginning and takes another 10 (or longer) minutes - in this time You are still driving/moving so i don't have to say what will be the result of this calculation? Osmand doesn't have own online mechanism, and these online what have been implemented are really useless - for example the most useful online one in Osmand advices You to turn left or right on elevated highway (because highway is crossing some local road which runs below, and there is no direct connection).

**Comment by pss34** [comment] 2018-10-09 12:50
As I can see, route calculated on one core of my 8. It makes osmand be equally slow on all devices. Is it algorithm flaw?

**Comment by naoliv** [comment] 2018-10-09 13:01
I am seeing this problem even with short routes (from one side of the city to the other one): if I miss a street, it starts to recalculate the route.

But then it gives a solution/instruction to turn on a street which I just passed (since it took some time to calculate); and again, it starts a new route recalculation with the same type of problem, always giving a solution to a street which is now behind me.

It's just not fast enough to properly calculate a route for an approaching exit/street.

**Comment by scaidermern** [comment] 2018-10-09 13:28
> But then it gives a solution/instruction to turn on a street which I just passed (since it took some time to calculate); and again, it starts a new route recalculation with the same type of problem, always giving a solution to a street which is now behind me.

I think this is a more generic problem faced by all routers if you don't already drive on the route towards your destination.

Maybe if OsmAnd detects that you are moving it should not start calculating a route from your current position but instead from a position a few hundred meters ahead? How do other routers handle this problem?

**Comment by bitboy85** [comment] 2018-10-09 17:09
From what i've seen on other routers the recalculation time is much smaller (only few seconds) so getting a solution you just passed cannot happen or it is very rare.
Of course the algo should use multithreading to be much faster on multicore devices.

**Comment by TheCapsLock** [comment] 2018-12-01 11:43
> You have to compare other offline product.

I tried another offline product (but proprietary) : Sygic : Sygic gets your way in a few seconds, blazing fast compared to osmand.

Today, it is difficult to me to convince people to use osmand because of this and also because of extremely slow and irrelevant search results compared to other products.

**Comment by wehkah** [comment] 2019-04-28 17:13
> Can long distance calculations not be done on a much simplified graph of just motorways and their rough intersections? 

I am a driver who has passed a certain age, and I can tell you, this is exactly the way how long distance trips were "calculated" back in "the good old days", when maps were made out of paper and electronic guidance was something that only the army used in their tanks and rockets. ;)

In those "pre-electronic age", when you had to make a trip from A to B, you took a look at a large scaled map, you mentally connected the places by a straight line, and you simply looked for the **most convenient** and **fastest** roads that were the closest to this line. Then you memorized all the places along that road that you had to parse by or drive through, and then your trip started! Once on the road, you just followed the signs that told you how to drive from one way stop to the next. And just before you left or passed the last way stop, you took a look at a detailed city map and only then you would have looked up the proper way to your destination. 

No one in those days would have started a trip of more than 200km by writing down each and every single street and little dirt road, that would have summed up to the shortest way, taking 5 hours to calculate that route. 

Osmand is unbeatable when it comes to finding addresses and guiding you through a city that is not your home town. And I highly appreciate that and all the work that is being put into this project! I really love it! :)

But on the other hand: do you really need a navigation software, Osmand or other, to calculate a trip that consists of 490km on a highway and 10 km city traffic? I'd say: no! And, no offence meant, but any one who can't drive from edge of a country to the other without the use of a navigation software, should ask themselves, if taking a train wouldn't be the better solution...

Maybe this old-school routing mechanism, that _cgogolin_ mentioned and that I described above, could be a solution for Osmand's "long distance problem": connect the starting point and the destination by a straight line, then look for the best paved roads and fastest lanes along side this line, and off you go! And once you're within 50km of the final destination, Osmand can calculate the exact route.

**Comment by bumbaras** [comment] 2019-07-18 11:45
Well, the long time calculation for start is lesser problem than the fact that after changing on fly the route (for example route is closed due to accident) osmand start calculating it the same way which took the same time again. I can understand that google maps do this in blink of eye because it has strong servers behind. But why some offline Mio Spirit from 2012 is doing the same in few seconds? Its hardware is much behind current tablets. And Mio also can point You exact street and exact number.
Maybe datas which Osmand is using as a basis to calculating routes is just too much complex or code is too much not optimized?

**Comment by jkufner** [comment] 2019-08-16 00:41
I wonder why long-distance trips are so slow to calculate. When traveling long distances we always use highways (or similar fast roads`*`). Therefore, there is no need for Osmand to bother with low-grade roads and paths. The highway network is much less dense and navigation should take a second. Just find all nearby highways around current location and the destination, then plan route from the set of source highway points to a set of the destination highway points. Once such a route is computed, just connect the three fragments of the route — from current position to the source highway point, then the highway portion, and finally from the destination highway point to the destination.

Because the roads are (mostly) planar, the each set of highway points should form a polygon around the source/destination location. The highway routing needs to support multiple starting and ending points, but we can do that for any routing algorithm by replacing the path between source/destination position to a given highway point with a single edge.

`*` By "highway" here I mean various main roads: highways, motorways, 1st class roads, etc. Those roads that stay visible when you zoom out a little.

**Comment by wehkah** [comment] 2019-08-16 16:00
That's exactly what I meant in my posting. There should be an option in Osmand, to always take the most convenient / the best build / the road with the highest speed limit / the most sophisticated road, or whatever you call it, as long as possible, and use city road only, if absolutely necessary. That is, for example, the last few kilometres when you need to go to an address within the city. 

It really doesn't make sense to always use the shortest way, when the shortest way leads you through dozens of towns and cities, with a million traffic lights and very sloooooow traffic, while most likely there's a bypass road, a highway, a motorway or an autobahn nearby available, which elongates your trip just a couple of km, but safes you from getting mad because of urban traffic.

**Comment by scaidermern** [comment] 2019-08-16 16:45
> That's exactly what I meant in my posting. There should be an option in Osmand, to always take the most convenient / the best build / the road with the highest speed limit / the most sophisticated road, or whatever you call it, as long as possible, and use city road only, if absolutely necessary.

This is already the default. Unless you selected to take the shortest route, not the fastest.

**Comment by jkufner** [comment] 2019-08-16 16:54
@scaidermern The question is how it is implemented. Investigates the routing algorithm all roads or the highways only? The routing speed sugests it investigates all routes and rejects them as too slow. There should be a very effective optimization available.

**Comment by wehkah** [comment] 2019-08-16 16:55
Yes, you're right. But in many cases I have not seen a great difference in routing according to this setting. There are differences, yes, but still the option "fastest route" does not use all possible resources of bypass roads. I can not give you an  adhoc example right now, but my experience is that Osmand prefers to go straight through a city instead of driving around it.

**Comment by pebogufi** [comment] 2019-08-16 17:01
If you think route calculation is slow, read the discussion about changed heuristic coefficient (search for "heuristic" in forum) and test the recommandation of Harry van der Wolf.
I like it, it is fast !

**Comment by scaidermern** [comment] 2019-08-16 18:53
> The question is how it is implemented. Investigates the routing algorithm all roads or the highways only? The routing speed sugests it investigates all routes and rejects them as too slow. There should be a very effective optimization available.

You have to consider all roads for finding the optimal route. Some locations are very far away from large roads. And sometimes you have to leave the motorway and enter it again at a later point in time to take the fastest route.

Approaches like contraction hierarchies would be an option but makes routing less flexible because it doesn't support configurable routing parameters. Howerever they could still be an option, for example by supporting the three most common routing parameter combinations.

**Comment by bitboy85** [comment] 2019-08-16 19:48
I'm still wondering how very old devices could calculate a route quite fast.
Without knowledge of how its implemented right now its hard to say what could be optimised.
Maybe there are some unessessary checks. I guess we could assume that highways have best available surface and highest speed limit so there is no need to check this on every single piece of it.

As i said in the first post, main problem is not that it takes initially long to calculate. It just annoying it takes so long if something unforseen happend like a closed route and as also mentioned before, it happened to me if i visited an rest area next to the main road. I cannot understand why it takes minutes just to get back to the main road from the rest area even its the only possible way.

**Comment by jkufner** [comment] 2019-08-16 19:59
> You have to consider all roads for finding the optimal route.

Theoretically, yes. Practically, not really. When traveling across Europe there is no point in checking every possible road. Just get on highway and next few hundred km is planned. There may be a shortcut we miss ([example](https://en.mapy.cz/zakladni?planovani-trasy&x=14.4460332&y=53.2792725&z=13&rc=9g.YhxmOC99hNrhxmCBi&rs=osm&rs=osm&ri=106003376&ri=15701&mrp=%7B%22c%22%3A111%7D&rt=&rt=&xc=%5B%5D) – the bridge may get ignored), but if the length of a suboptimal route is similar to straight distance, it does not matter. If the found route is suspiciously longer, we may want to check for shortcuts and consider lower-grade roads.

> Some locations are very far away from large roads.

The distance does not matter. If we can construct a polygon made of highways around the destination, we can ignore low-grade roads when searching a route to the polygon. Once we get inside, we need to consider the low-grade roads again.

> And sometimes you have to leave the motorway and enter it again at a later point in time to take the fastest route.

By "highway" I mean various main roads. Zoom out on a map and those main roads stay visible when highways are visible. The point is that these roads form a network dense enough to find a reasonable route, but sparse enough to calculate the route in few seconds.

**Comment by wehkah** [comment] 2019-08-17 07:37
> I'm still wondering how very old devices could calculate a route quite fast.
> Without knowledge of how its implemented right now its hard to say what could be optimised.

I am no expert neither, but I my guess would be that pure navigation devices, even "old" ones, are optimized hardware that doesn't do any thing else but calculating routes. Those devices don't have to deal with things like operating systems, hardware drivers to be loaded, sharing the memory with other applications, and all those things that smart phones and tablets do.

**Comment by bitboy85** [comment] 2019-08-18 12:05
i own a very old navigon / transonic with ARM chip. Its just a device having winCE 5(?)  and the software installed, so no, i don't think theres something special built into it to do route calculation.

**Comment by wehkah** [comment] 2019-08-18 13:03
Interesting... I'm curious: is there any way you can get information out of that system, like memory usage, CPU usage, etc? 

Two ideas crossed my mind: 

1. Leaving a route because of traffic jam, accidents or construction sites is something that really needs to be taken care of in Osmand. I think one good solution to this problem would be a button on the screen, that makes Osmand stop calculating a new route and keep the already calculated route. Once you're done with following the diversion signs and you're back to your original road, Osmand can reuse the old route without having to recalculate it. 

2. 

> The distance does not matter. If we can construct a polygon made of highways around the destination, we can ignore low-grade roads when searching a route to the polygon. Once we get inside, we need to consider the low-grade roads again.

I'd call that a really good idea! But is that really necessary? I am not familiar with programming, and I have no idea about Osmand and  its techniques. But wouldn't it be enough to give the user a new option to give much more priority to fast roads and to low rate (thus ignoring) roads that lead through towns or country side roads?

**Comment by naoliv** [comment] 2019-08-18 14:47
Wasn't `Smart route recalculation` supposed to mitigate this problem?
![](https://user-images.githubusercontent.com/982338/63226218-d47d5f80-c1ad-11e9-8d33-9e3575df426b.png)

Maybe the code should be profiled to spot the slow paths and then find some possible optimizations.

**Comment by jkufner** [comment] 2019-08-18 22:18
@wehkah Ignoring lower-grade roads when routing to the polygon is not something user will see. It is under-the-hood optimization.

The whole point is, that there is a lot of low-grade roads, but relatively small number of highways (and other main roads). If there are like 10 low-grade roads for each highway, then if we consider 1 000 highways when routing, we can ignore 10 000 low-grade roads. That is approx. 90% faster calculation.

**Comment by jkufner** [comment] 2019-08-18 22:20
> Leaving a route because of traffic jam, accidents or construction sites is something that really needs to be taken care of in Osmand. I think one good solution to this problem would be a button on the screen, that makes Osmand stop calculating a new route and keep the already calculated route. 

User should not be bothered with such thing. Osmand should keep partial routing results cached and reuse them when calculating a new route. Then the recalculation should take less than a second, when we take a wrong turn and next street leads back to the original route.

**Comment by wehkah** [comment] 2019-08-19 09:09
That would be the ideal case. But how should Osmand decide whether you are leaving the calculated route on purpose, e.g. because you want to have lunch, or if you are forced to leave the route because of road works, or if you simply missed the right exit? And how should Osmand decide if its supposed to calculate a new route or not?

Even if Osmand keeps the original route cached, which would be a very good thing to do indeed, how do you keep it from starting to calculate a new route, as soon as you leave this route, just because you want to have dinner or you need to fill up your car? This automatic re-calculating of a new route simply takes too long, and if you're moving and taking turns while the calculating takes place, this procedure takes even longer, because the device always tries to re-re-re-calculate a new route, taking into account all the turns that you took or that you did not take since you left the original route. 

I don't think that this is something that can be taken care of automatically, as long as calculating a route takes longer than reaching the next turn or exit.

**Comment by jkufner** [comment] 2019-08-19 09:59
It does not matter whether you leave the route on purpose or not. The task is the same — calculate route to the destination.

Thing about routing and path-finding in general is, that you don't really calculate the route. The road map is a graph of nodes and edges and the algorithm checks a subset of hopefully relevant nodes and edges whether they lead in the right direction. The algorithm also calculates partial distances between start and the currently investigated node (or distance from the destination if run backwards). So when the algorithm finishes, you get a data structure which contains distances from the start to the each point on the route and also to many other suboptimal partially computed routes around the found route. If you take a wrong turn (on purpose or not), there is a pretty good chance that the new route is already calculated, all you need to do is to collect the data and render it.

The trick is that we must not stop the algorithm (and discard the temporary data structures) once the route is found. We must pause the algorithm in the current state and restart it when the current location leaves the calculated area. Then we get instant route recalculation for free.

Another trick is to calculate the route backwards. When the algorithm calculates distance from the start and the start moves, the calculated data become obsolete. But the destination does not move. So we can calculate route from the destination to the current position, and if the current position moves, the algorithm will simply run a little bit longer to check few extra nodes in the end. It is the same case as when recalculating route after taking a wrong turn.

**Comment by wehkah** [comment] 2019-08-23 17:17
> It does not matter whether you leave the route on purpose or not. The task is the same — calculate route to the destination.
> 

And I think that this is the problem: if Osmand could be kept from calculating a new route as soon as you leave the actual route, it could react much faster, once you finished following a detour, eg because of road works. While you're following such a detour, there is no need to recalculate a new route, because the detour will eventually return you to your previous road.

That's why I would welcome a possibility to manually stop Osmand from recalculating a new route.


> 
> Another trick is to calculate the route backwards. 

> When the algorithm calculates distance from the start and the start moves, the calculated data become obsolete.

Yes, that is sooo true: often it takes less time to reach and pass the next exit or turn, than it takes Osmand to finish the routing and telling you should have taken that exit. :(

**Comment by jkufner** [comment] 2019-08-23 20:29
I took a brief look into Osmand's source code and I think that Osmand calculates the route, stores it and then navigates. To make recalculations fast, I think it would be better another aproach. Let the routing algorithm run in the background and let it update the route as the current position changes. The difference is in preserving all the temporary data generated during the calculation, because the routing algorithm is running the whole time (but not using CPU all the time, of course).

**Comment by wehkah** [comment] 2019-08-23 21:05
Hm, I understand what you're telling, but I am still not 100% convinced. I know it's impossible, but the best solution I can think of would be to make Osmand "know" if a previous calculated route has been left because you missed the right turn, or if you were forced to leave it because of road works, to make it "know" if I want the route to be recalculated or if I don't want it, because I will return to the right track soon. In fact, it can be very disturbing if you start following an officially signposted diversion and Osmand tells you to "turn left" or "turn right" or "turn around" every few seconds. 

Unnecessary navigation commands can be avoided easily, the muting button is you friend there. :)
But the ongoing recalculation can be a very tough job for some hardware!

**Comment by jnr57** [comment] 2019-08-24 14:10
Hello all,
I was using occasionally 0smand using gpx tracks and some times for route navigation. Since the las update (3.4.8). I guess,  its almost impossible to use the app for route calculation for 100 to 300 km long. Seems to work fine for short distances <50 km. For the same trip it takes 0.1 s with Googlemaps! and 3 s with MAPS.ME. So how Osmand is calculating the route ? As previous comments, I will stop using this app if this problem is not fixed. Thanks for any uddapte.

**Comment by bumbaras** [comment] 2019-09-17 19:48
I have returned to OsmAnd since quite long break with Huawei P10 and it seems that calculation is done much faster now, it is probably due to more powerful smartphone. It still took about two minutes when i changed route, but strangely OsmAnd didn't seem to calculate new route - just showed i am out of route.
It was 350km distance.
Two things i couldn't find in current version - OsmAnd engine choice and Poland map only in autoroute version, not detailed one.

**Comment by scaidermern** [comment] 2019-09-18 06:27
> Two things i couldn't find in current version - OsmAnd engine choice and Poland map only in autoroute version, not detailed one.

Poland map has been split into several regions due to its size. Offtopic for this issue, though.

**Comment by bitboy85** [comment] 2022-05-04 11:37
Anyone else who thinks it got even worse? I tried to get a routing for about 200km and after 40 minutes(!!) it says it wasn't possible.
Tried reinstalling and using street-only maps instead of full featured maps. But it didn't help.

Its unusable in this state :(

**Comment by vshcherb** [comment] 2022-05-04 11:42
>  I tried to get a routing for about 200km and after 40 minutes(

That's too long even for current routing engine. Please share coordinates and try to increase routing memory up to 256-512 MB.

**Closed by vshcherb** 2022-05-04 11:42 UTC
Labels: Observed

**Comment by scaidermern** [comment] 2022-05-04 11:54
> > I tried to get a routing for about 200km and after 40 minutes(
> 
> That's too long even for current routing engine. Please share coordinates and try to increase routing memory up to 256-512 MB.

Why is that, from a technical point of view? There are other offline routing engines, like brouter, which don't have this problem. Do they have a better data format? Or are more aggressive when cutting branches during routing graph calculation? Or do they user some other approximation to reduce the computational effort? Smartphones have become really powerful in recent years and should be able to handle this, if I'm not completely mistaken.

**Comment by vshcherb** [comment] 2022-05-04 12:45
It really depends a lot on configuration, I think B-Router is also A* algorithm, so the end result should be comparable to OsmAnd (if routing configuration similar) i.e. B-Router could be 2 times faster due to optimized storage but unlikely 10 times faster.

**Comment by cgogolin** [comment] 2022-05-05 18:03
In many cases B-router feels more like 20x faster. This is on a Galaxy S10e.
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by bitboy85** [comment] 2022-05-06 07:10
How can i increase the memory?
Are there other options or configurations that could be tweaked?

Coordinates was from Bitburg, Germany to Dortmund, Germany

**Comment by bitboy85** [comment] 2022-05-10 09:08
Please reopen.

Meanwhile osmand version is 4.0.8; Kernel 3.4.39
Android 5.1.1 without any chance to upgrade.

During route calculation RAM usage from osmand is about 350-400MB while having an additional 1GB free.

It was able to finish the same route today after about 50 minutes....

**Comment by vshcherb** [comment] 2022-05-10 12:14
Bitburg - Dortmund on my device (4.2 OsmAnd Android 11) takes 10-15 seconds and 230 km route.

**Comment by vshcherb** [comment] 2022-05-10 17:15
It's not available in 4.0.8. Sorry 4.0 is outdated and no longer under support

**Comment by bitboy85** [comment] 2022-05-11 06:11
And i can't install a newer one because of the android version

**Comment by bumbaras** [comment] 2022-05-13 08:47
I am not sure why this matter is still discussed. I reported similar issue few years ago and only solution was to stop using this app. Because offline calculation is too much for average smartphone. Not sure how to interpret this because i was using some mio navigation device which calculation power were no more than 1/10 of my smartphone so i just stopped using osmand plus and went to google maps. The most annoying thing in this long time calculation was long time calculation after changed road.

**Comment by bumbaras** [comment] 2022-06-07 10:53
> Any chance to get the current version backported to android 5? I tried maps.me and it calculates a route within 2 minutes but it is lacking other features...

Huh? You want the maps.me be ported to old android? Is this somehow related to Osmand app? Android 5 is currently like Windows XP in modern times. Wouldn't expect anyone be interested to play with it. Beside 2 minutes suggests maps.me can be using online calculation.

**Comment by bitboy85** [comment] 2022-06-10 04:57
> Bitburg - Dortmund on my device (4.2 OsmAnd Android 11) takes 10-15 seconds and 230 km route.

sounds like it is working in newer versions. Maybe increasing the memory helps.

**Comment by H-Sachse** [comment] 2022-09-13 17:42
I thought about a solution for reducing the number of roads for the routing algorithm to take into account, and I think the following may work:
If the routing algorithm is further away than say 50 km from the starting point and the destination and any intermediate destinations, ignore roads of lower levels. Meaning only use Autobahn/Bundesstraße/Staatsstraße for Germany, Interstate/Highway/State Roads for USA and so on. This would cut out all the little roads in between. They would not lead to a usable route anyway.
The cutoff distance could be a tunable parameter, maybe even part of the map data, depending on how dense the higher level road network is.

I also think this would not be too hard to implement into the current algorithm. It would "just" have to check the distance to the start and destination(s), check the road type and drop this path if the road type is too low.

I just tried to calculate a Route from Füssen to Hamburg in Germany with Osmand+ (F-Droid) 4.2.6 and it couldn't do it, stating it didn't find a solution, although there's the A7 going from Füssen to Hamburg.

**Comment by scaidermern** [comment] 2022-09-13 18:00
Not sure if ignoring these minor roads completely is a good idea since they could be necessary in some edge cases. There could be a solution somewhere in between, for example by significantly raising the priority of major roads during route calculation.
Other apps manage to calculate long offline routes without such problems (see for example brouter). So it can't be impossible to finally "fix" this major(!) downside of OsmAnd.

**Comment by H-Sachse** [comment] 2022-10-08 20:07
Interesting observation: uNav + OSM scout server on Ubuntu Touch on a Lenovo TB-X605L can calculate a route clear across germany (from near lake constance to Hamburg) in about 10 seconds, where OSMamd takes forever if it can calculate a route at all on my FP3. To make sure everything is done offline I actually switched off network connectivity.
Both devices have similar HW specs.
Might be good to check out what the scout server does for routing to see why it is so much faster.

**Comment by mwerle** [comment] 2023-12-13 01:26
Just to add my 2c; I've now several times gotten completely lost in Tokyo after taking a wrong turn on one of the inner-city highways because OsmAnd failed to calculate -at all- the final 10km to my destination.  In both cases I eventually had to turn off the highway (there are no verges) in order to be able pull over and get it to recalculate, which costs a lot of money (the highways are all toll-roads, and you pay every time you leave and re-enter).

I have no idea what OsmAnd is trying to do under the hood, but it appears to have been trying to recalculate the entire route from my original starting point (a few hundred km away) to my destination (<10km away), instead of from my current position. Or it starts recalculating every time my position changes (obviously it's impossible for me to stop).

After pulling over, cancelling the current route (it still fails to recalculate after stopping), and calculating a new route to my destination it only takes a few seconds, so it's not an intrinsic issue with the routing in this area, just the way in which recalculation is working.

FWIW, I'm on a motorbike, so fiddling with the routing and/or asking a passenger to do it for me while driving is not an option.

Conversely my ancient Garmin Zumo 660 has no problems recalculating routes in a "sane" amount of time and I used it for routes covering 1000+km in Europe..

Perhaps a way to improve matters is for routes to have virtual waypoints (every X kilometers, or at major intersections, etc); if a user leaves a route, only a sub-route from the current location to the next waypoint needs to be calculated to get back on the original route. This would not require recalculating everything.

**Comment by sonora** [comment] 2023-12-13 07:17
Perhaps worth opening a new issue about this, and also state app version and map version fir reproducability.

I personally recently had _sporadically_ the following, using v4.6.5: I was using car routing, but just displaying the route, i.e. not in turn-by-turn modus. On some occasions I noticed that the route line now extenden not only in front of me, but my position was somehow displayed "in the middle" of the route line. Apparently, at some point OsmAnd had failed to recognize that I had progressed along the route,and still displayed the route starting from some point behind me (actually some turn, if I remember correctly). I had left that situation for a while, but it did not resolve itselfef, so eventually that 'stuck' starting point would have been far behind me (though not the original starting point of the route). Canceling the route and re-starting it resolved the situation in seconds. It is hard to reproduce, but happened to me 2-3 times in a week of extensive driving.

**Comment by vshcherb** [comment] 2023-12-14 14:45
We have already new routing for car & bicycle (Development settings -> Special routing) it's early stage alpha and still not in C++ (Java) but it's promisingly fast and fast recalculations

**Comment by naoliv** [comment] 2023-12-14 15:46
> We have already new routing for car & bicycle (Development settings -> Special routing) it's early stage alpha and still not in C++ (Java) but it's promisingly fast and fast recalculations

Is this the HH route planner? (#18378)

**Comment by vshcherb** [comment] 2023-12-18 09:19
yes
