### ISSUE TITLE
Gaps in gpx record

### ISSUE THREAD

**Issue by iseldonz** [osmandapp/OsmAnd#18917] opened 2024-01-16 00:16 UTC
### Description

Sometimes large gaps (over an hour) from one trackpoint to the next. App has not crashed as sometimes there are multiple gaps in one file.

### Steps to reproduce

Start recording a walk. Let OsmAnd run in the background (whether accessing other apps causes the problem is not known). Note large gaps in the recording.

### Actual result

GPX file has large gaps.

### Expected result

There should be no gaps.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:4.6.11 and the previous one
Android/iOS version:Android v.10
Device model:LG LM-K300TM
Crash-Logs: ?Attached. The text file has been edited to show only the header and some of the problem areas
```
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/14339975/eea620ae-0827-46a6-a408-e85a51cff0bf"  width="300" height="auto"/> </th>
  </tr>
</table>

[trek problem GPX.txt](https://github.com/osmandapp/OsmAnd/files/13943966/trek.problem.GPX.txt)

**Comment by iseldonz** [comment] 2024-01-16 00:19
Been using OsmAnd for several years. Earlier versions (don't recall which)) did not have the problem.

**Comment by yuriiurshuliak** [comment] 2024-01-17 11:32
Could your issue be a duplicate of this issue #18165?
Please read the possible solutions in the comments to this bug and check if they help you.

Also we recommend that you check if your device has any power optimization settings that may be affecting the app's performance. You can refer to this website https://dontkillmyapp.com/. Also, please refer to this article for troubleshooting steps: https://osmand.net/docs/user/troubleshooting/track-recording-issues

**Comment by scaidermern** [comment] 2024-01-17 12:40
Try to disable the battery optimization for OsmAnd in your Android settings.

**Closed** 2024-01-18 14:49 UTC
