### ISSUE TITLE
Creation of a Wheelchair routing profile

### ISSUE THREAD

**Issue by LorenzoStucchi** [osmandapp/OsmAnd#9768] opened 2020-09-08 11:41 UTC
# 🚀 feature request: Insertion of a routing profile for wheelchair

### Description
The application provides different types of routing (car, pedestrian, byke, ...) and it is missing a specific one dedicated to people with motor disability. 

### Describe the solution you'd like
The routing system of OsmAnd is one of the most efficient and it is one of the best one to consider also to avoid nodes. I was able to create a custom profile that considers the last version of the mapping schema for the wheelchair, the [code](https://github.com/LorenzoStucchi/Wheelchair-OsmAnd). 

### Describe alternatives you've considered
I tried to use the pedestrian profile but some elements as kerb are not already in the map.

**Comment by scaidermern** [comment] 2020-09-08 12:21
Duplicate of #9415.

**Comment by LorenzoStucchi** [comment] 2020-09-08 12:24
Thanks @scaidermern for pointing to the issue, If you want I created already the routing profile

**Closed** 2020-09-09 12:00 UTC
