### ISSUE TITLE
Frozen UI in Android 7.0 splitscreen

### ISSUE THREAD

**Issue by dragonchaser** [osmandapp/Osmand#3730] opened 2017-05-02 06:57 UTC
**Behaviour:**

Osmand UI freezes when using it in splitscreen mode on Android 7.0 (Moto G5 plus) when using the other app.

**Expected Behaviour:**

UI working as intended when using the app running in the other splitscreen half.

** How to reproduce:**

- Start osmand alongside any app (e.g. music player) in splitscreen, start navigation
- Use other app (e.g. switch to next track in music player)
- **Result:** Osmand UI will freeze within 10-30 seconds (but can be reactivated by touchevent somewhere in the osmand app)

**Comment by njohnston** [comment] 2017-05-02 07:35
Related to / possible duplicate of #3489.

**Comment by dragonchaser** [comment] 2017-05-02 11:48
@njohnston does not sound like a duplicate to me, but I think its basically the same problem.
So fixing the one should automatically fix the other.

**Closed** 2017-05-25 09:40 UTC
