### ISSUE TITLE
Location from NLP not used

### ISSUE THREAD

**Issue by y0va** [osmandapp/OsmAnd#13177] opened 2021-11-15 11:05 UTC
### Description
OsmAnd does not fetch location info provided by ichnaea unlp backend.

### How to reproduce?
Fresh lineageos installation with unified nlp package from https://gitlab.com/FriendlyNeighborhoodShane/minmicrog

[Mylocation](https://f-droid.org/en/packages/com.mirfatif.mylocation/) shows location from [Mozilla backend](https://f-droid.org/en/packages/org.microg.nlp.backend.ichnaea/) but when clicked on the crosshair icon in osmand, adb shows the following error repeatedly:

```
11-15 11:22:26.001  5648  5648 D StrictMode: StrictMode policy violation; ~duration=1 ms: android.os.strictmode.DiskWriteViolation
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1552)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at libcore.io.BlockGuardOs.remove(BlockGuardOs.java:340)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at libcore.io.ForwardingOs.remove(ForwardingOs.java:185)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.app.ActivityThread$AndroidOs.remove(ActivityThread.java:7582)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at java.io.UnixFileSystem.delete(UnixFileSystem.java:331)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at java.io.File.delete(File.java:1037)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:833)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.app.SharedPreferencesImpl.access$900(SharedPreferencesImpl.java:59)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:672)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.app.SharedPreferencesImpl.enqueueDiskWrite(SharedPreferencesImpl.java:691)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.app.SharedPreferencesImpl.access$100(SharedPreferencesImpl.java:59)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:604)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at net.osmand.plus.api.SettingsAPIImpl$1.commit(SettingsAPIImpl.java:70)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at net.osmand.plus.settings.backend.LongPreference.setValue(LongPreference.java:17)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at net.osmand.plus.settings.backend.LongPreference.setValue(LongPreference.java:3)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at net.osmand.plus.settings.backend.CommonPreference.set(CommonPreference.java:216)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at net.osmand.plus.OsmAndLocationProvider.redownloadAGPS(OsmAndLocationProvider.java:288)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at net.osmand.plus.base.MapViewTrackingUtilities.backToLocationImpl(MapViewTrackingUtilities.java:394)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at net.osmand.plus.base.MapViewTrackingUtilities.backToLocationImpl(MapViewTrackingUtilities.java:366)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at net.osmand.plus.views.layers.MapControlsLayer.onBackToLocation(MapControlsLayer.java:421)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at net.osmand.plus.views.layers.MapControlsLayer.access$800(MapControlsLayer.java:91)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at net.osmand.plus.views.layers.MapControlsLayer$6.onClick(MapControlsLayer.java:397)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.view.View.performClick(View.java:7448)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.view.View.performClickInternal(View.java:7425)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.view.View.access$3600(View.java:810)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.view.View$PerformClick.run(View.java:28305)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.os.Handler.handleCallback(Handler.java:938)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.os.Looper.loop(Looper.java:223)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-15 11:22:26.001  5648  5648 D StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Your Environment
OsmAnd Version: latest from fdroid
Android/iOS version: lineageos 18.1
Device model: d855

### related:
- https://github.com/osmandapp/OsmAnd/issues/2683
- https://github.com/osmandapp/OsmAnd/issues/3833

**Comment by vshcherb** [comment] 2021-11-20 14:43
So it looks like a duplicate of https://github.com/osmandapp/OsmAnd/issues/2683.

**Closed by vshcherb** 2021-11-20 14:43 UTC
Labels: Observed

**Comment by y0va** [comment] 2022-01-13 11:21
I don't think this is a duplicate, because NLP location data is not used in non-navigation mode neither.

**Comment by y0va** [comment] 2022-01-13 12:03
Ok, can't reproduce this anymore. Works for me.

**Comment by khimaros** [comment] 2023-01-19 01:37
I suspect this is working as intended, because the FDroid release does not use Google Location Services, which means the request never reaches microG or its UnifiedNlp backends. see also: https://www.reddit.com/r/OsmAnd/comments/wpqfz4/network_location_not_showing_on_the_fdroid_version/

**Comment by sonora** [comment] 2023-01-19 07:44
I believe that the F-Droid compilations may not have this, but our new (also nightly) releases have a setting `OsmAnd settings > Location source` (located between settings `Dialog and notifications` and `Auto-backup`) which you can set to either "Google Location Services" or "Android API". Since microg emulates google, it is possible that the setting would need to be set to that, but the F-Droud compilation omits the setting and uses always uses "Android API"?

**Comment by khimaros** [comment] 2023-01-19 07:52
does the "Android API" setting make use of the UnifiedNlp backends or does it use only GPS?

**Comment by khimaros** [comment] 2023-01-19 10:40
I think we need something like this: https://github.com/mirfatif/MyLocation/blob/master/app/src/main/java/com/mirfatif/mylocation/NlpBackend.java
