### ISSUE TITLE
OsmAnd voice announces a phantom destination (sporadic)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#2731] opened 2016-06-20 19:48 UTC
It happens sporadically. I experienced it - I think - 3 times.

The german voice says "dann haben Sie Ihr Ziel erreicht" several minutes or hours any many maneuvers before approaching the destination.  (I am not sure if it only happens if there has been an intermediate destination deleted before.)

Builds: OsmAnd+ 2.3.5 and older
Devices: Samsung Galaxy Note 4 and Huawei Y625

**Comment by Norbert80** [comment] 2016-06-22 01:39
Additional info:

After the bad target announcement voice guidance is continued normal until the real destination has been reached.

**Comment by sonora** [comment] 2016-06-23 07:53
@Norbert80  I had applied a fix for this in September 2015, but I assume when you reference "OsmAnd 2.3.5 and older builds" you are not saying it only happens with so old builds, right?

I cannot reproduce and hence it sounds like it is related to some functionality I do not regularly use, like maybe deleting intermediate destinations, as you say. I will sift through the code but chances are we can only really identify this if you collect more evidence about the circumstances when you observe this, ok? Things to watch are also: GPS reception just lost or just recovered at that point? Route recalculated shortly before? etc.

Thx - Hardy

**Comment by Norbert80** [comment] 2016-06-23 07:59
@sonora: Thanks. Yes, we definitely saw (or should I say heard) this bug with build 2.3.5.

**Comment by sonora** [comment] 2016-06-23 22:00
I made a lot of TTS voice fixes in early v2.4, which is still not released to the Play Store, and it could well be I have actually fixed this. Unless we can find out how to reliably reproduce, I guess we should either wait for our 2.4 release, or you could try our nightly builds and see if you can still reproduce it.

**Comment by vshcherb** [comment] 2016-08-14 21:05
Waiting for feedback about 2.4

**Closed** 2016-08-14 21:04 UTC
