### ISSUE TITLE
Route duration displayed in seconds

### ISSUE THREAD

**Issue by breversa** [osmandapp/OsmAnd#14888] opened 2022-07-18 15:24 UTC
### Description
When calculating a route, the toast that briefly appears at the bottom of the screen displays the route's duration in seconds, which is very inconvenient (borderline useless unless you're a maths genius).

### How to reproduce?
Set a destination
Tap "navigate"
Let OsmAnd calculate the route
See that the toast displays the duration in seconds:
![Screenshot_20220718-171514_OsmAnd~](https://user-images.githubusercontent.com/2071276/179545890-eb114869-2d44-4898-99b6-9b969a39db4b.png)

### Your Environment
OsmAnd Version: 4.2.6 from F-Droid
Android/iOS version: Android 10 (/e/OS 1.1)
Device model: Samsung Galaxy S9 (SM-G960F)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
France Grand Est Bas-Rhin (2022-07-01)

**Comment by scaidermern** [comment] 2022-07-19 05:19
Duplicate of #13501.

**Closed** 2022-07-19 07:06 UTC
