### ISSUE TITLE
Wrong map rendering near Brooking near ocean

### ISSUE THREAD

**Issue by programmin1** [osmandapp/Osmand#5972] opened 2018-09-02 21:32 UTC
I have noticed that for months there has been wrong rendering near Brookings, it's not due to old local maps, it has been this way for awhile....
Compare the actual map at
https://www.openstreetmap.org/node/357320171#map=15/42.0451/-124.2678
to what is shown in Osmand, in Osmand the RV park and Best Western don't show, the inlet doesn't even go to the ocean.

**Comment by scaidermern** [comment] 2018-09-03 07:52
Can you attach a screenshot of the area?

**Comment by programmin1** [comment] 2018-09-04 05:13
Yes:

![screenshot_2018-09-02-14-19-14](https://user-images.githubusercontent.com/1295242/45011275-900da980-afc6-11e8-910b-045fb760c897.png)

**Comment by xmd5a2** [comment] 2019-10-09 07:41
Duplicate of https://github.com/osmandapp/Osmand/issues/6565

**Closed by xmd5a2** 2019-10-09 07:41 UTC
