### ISSUE TITLE
"Rec" folder collapses after renaming a track

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd#6290] opened 2018-11-19 13:36 UTC
Ways to reproduce: 
Menu - My places - Tracks 
Expand "Rec" 
Have enough tracks so that they don't fit on the screen. 
Click on "three dots" to open track's menu. 
Choose rename. 
Append some words to the end so it doesn't affect sorting. 
Click Save. 
Now "Rec" is collapsed and you have to scroll to find your track again.

Desired behavior: 
Tracks list keeps scroll position upon renaming.

**Comment by njohnston** [comment] 2018-11-20 14:33
Possible duplicate of #6187.

**Comment by sonora** [comment] 2019-03-20 15:18
6187 was caused by the GPX folder list sometimes including group 'Visible' and sometimes not. This here seems different as the folder list does not change by renaming a file. Let me re-open, I think it requires a separate analysis.

**Comment by dmpr0** [comment] 2024-07-19 11:03
Tracks UI was updated, issue no relevant now.

**Closed by dmpr0** 2024-07-19 11:03 UTC
Labels: Observed
