### ISSUE TITLE
Transport Stops not always functioning

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#2932] opened 2016-08-11 08:53 UTC
Osmand+ 2.4 Beta Google Play 11 August 2016
(It says OsmAnd+, released 2016-07-31, but I already received another version after this date as well. Is this also a bug or is it "by design"?)

When displaying transport stops on the map (Configure Screen -> Public Transports -> Transport Stops), they are not always visible.
Sometimes 
- when panning the map they suddenly disappear, 
- when zooming out/in they sometimes disappear, 
- sometimes not all are visible, just a few (also after panning/zooming)

Edit: note that the POI icons remain visisble, just not the "overlayed" square transport stop icons.

**Comment by awojtas** [comment] 2016-08-11 09:21
Same issue here on 2.4 beta. Device is Sony Xperia Z3C with Android MM 6.0.

**Comment by vshcherb** [comment] 2016-08-11 14:40
I think that issue was fixed in 2.4.3 release though it is available only for 10%, soon it will be available more. Though I'm not sure we can release a new beta.

**Closed by vshcherb** 2016-08-11 14:40 UTC

**Comment by awojtas** [comment] 2016-08-11 22:03
Unfortunately even with 2.4.3 this always breaks for me after doing a
Search and selecting a recent place I searched for in another city on the
opposite side of the world.

To reproduce:
My home is Wellington, New Zealand. I can select transport stops and then
select the transport line and see the train route highlighted. Great.
1. Then I click Search icon and select "villa Richter restaurant", which is
a place I've previously searched for, in Prague, Czech Republic.
2. I zoom in and none of the stops are showing.
3. I click the "gps centre" button to move the map back to Wellington. The
transport stops are gone now.

Happy to send screenshots if that would help

**Comment by hvdwolf** [comment] 2016-08-12 08:16
Confirmed.
I don't see a difference either.

**Comment by vshcherb** [comment] 2016-08-12 20:28
Please send screenshots

**Comment by vshcherb** [comment] 2016-08-12 20:41
The issue is possible to partially reproduce when new toolbar appears, but previous route is still selected. Though after you close toolbar, then toolbar with route will show up and it will be possible to dismiss it.

**Comment by hvdwolf** [comment] 2016-08-13 08:28
This morning I wanted to reproduce "some things".
Atnight I have my phone switched off, so I switch it on and go into OsmAnd. Even thoughthe transport stops are selected for display, they are not visible. And I have done nothing yet.
I canof course senda screenshot, but it is the default map around my location which you get when you start OsmAnd. However, wthout transport stops.
So I switch them off and back on: still nothing.
I close the app completely and restart: still nothing.

I really think this new functionality is absolutely fabulous!! But it needs some bugfixing.

**Comment by hvdwolf** [comment] 2016-08-15 09:24
I completely uninstalled OsmAnd incl. data and settings and reinstalled it. That doesn't make a difference either. For me the transport routes don't work at all anymore.

**Comment by vshcherb** [comment] 2016-08-15 22:22
Please specify area... I just tested latest Netherlands Noord holland and it works as expected

**Comment by awojtas** [comment] 2016-08-15 23:52
I'm in Hong Kong, transport stops working fine.
Then I search for Villa Richter in Prague, Czech Republic, and transport
stops are missing.
Again I search for Wellington, New Zealand, and the transport stops are
gone.

It is like the transport stops only show for the city that GPS says you are
in.
Transport stops were showing fine in Wellington when I was there last week.
Now I'm in Hong Kong they're gone.

Screenshots attached

**Comment by hvdwolf** [comment] 2016-08-16 08:23
I am using the full Netherlands map. I live in Zwolle, (province Overijssel), Netherlands and I am currently in Zwolle. For me it is the other way round. I tested in Zwolle and nothing worked and still doesn't.
So I tested Raalte (20 km from Zwolle), also in province Overijssel. That doesn't work either.

Then I tested Den Haag in province Zuid-Holland. Den Haag works fine.
Leeuwarden, province Friesland also works fine.
(Another strange issue is that I have 2x Nederland in my search country options while I only have one map installed).
I removed the full Netherlands map (1 Aug), stopped OsmAnd, deleted ind.cache, started OsmAnd and downloaded full Netherlands again. 
And now the transport stops work: everywhere

(but again I have 2x Nederland as country option in my initial Search screen: weird. Does this have something to do with the merging of the regional maps?
And another weird thing is that I now have the world map and POI maps as searchable maps in my search screen. Should I file another bug?)

**Comment by vshcherb** [comment] 2016-08-16 21:50
About transport the places I'm checking I could not reproduce the issue.
https://goo.gl/photos/MK1qY7stdecb1S7F7 (Zwolle). Please keep in mind that not all stops are displayed, there are only stops which have proper transport relation routes.

Search screen is going to be deprecated, yes that's a minor issue.

**Comment by hvdwolf** [comment] 2016-08-17 09:57
As mentioned: After the reinstall of the Netherlands map it works fine.

**Comment by vshcherb** [comment] 2016-08-17 10:26
Yes, to show routes new maps are needed. That's not a problem of the app, it is just missing data in the old maps

**Comment by sonora** [comment] 2016-08-17 11:08
Similar to #2954. I will at least add a reminder to update maps on our web site.

**Comment by hvdwolf** [comment] 2016-08-17 11:09
That's not what I meant and described above. I had the 01 August map and I downloaded the 01 August map again.

**Comment by awojtas** [comment] 2016-08-17 13:42
No, it doesn't matters the map version. I was in Hong Kong yesterday and
the transport stops were working fine.

Now I'm in Prague and the transport stops in Hong Kong have disappeared.

Screenshots for both situations attached. The file name has the date. The
one with no transport stops was taking just now, from Prague.

The one with transport stops was when I was in Hong Kong.

If the map version was wrong then the transport stops would never have
worked in the first place.
