### ISSUE TITLE
Add favourites: make "name" field selected again

### ISSUE THREAD

**Issue by dafadllyn** [osmandapp/OsmAnd#19380] opened 2024-03-23 20:19 UTC
### Describe the idea (required)

Since a recent update, when adding a favourite, the text in the name field is no longer selected. Instead the cursor is placed after the last character in the name field (see screenshot below). As a result, when you want to give the favourite an individual name, you first have to select and delete the suggested name. This may not seem like a big deal, but when using OsmAnd to quickly take notes (as favourites) on the go to improve OSM later at home, it takes much more time.

### Tell us about the expected behaviour (required)

Please restore the previous behaviour, where the name field is selected by default when adding a favourite.

### Tell us about alternatives you've considered (required)

See above (you have to select and delete the suggested name, which takesmore time).

### Context (optional)

OsmAnd+ version: 4.6.13
Device: Google Pixel 6a
Android version: 14

<img src="https://github.com/osmandapp/OsmAnd/assets/79018751/f38d82d4-e971-49db-b2b6-5d0ff55404b2" alt="Screenshot_20240323-185627" width="300">

**Comment by pebogufi** [comment] 2024-03-24 09:39
In latest versions is now a delete button in the very right end of the text field which deletes the text.

**Comment by scaidermern** [comment] 2024-03-24 15:05
Duplicate of #18258

**Comment by vshcherb** [comment] 2024-04-01 22:58
I don't think it's OsmAnd update, I suspect Android release doesn't allow any more to select whole text - because nothing was changing in the code as I know

**Comment by scaidermern** [comment] 2024-04-02 06:55
> I don't think it's OsmAnd update, I suspect Android release doesn't allow any more to select whole text - because nothing was changing in the code as I know

I don't think so. I'm on Android 10 and for me the behavior is the same. The cursor is placed at the end of the text.
And the code definitely _did_ change, this was already discussed. See #18258.

**Comment by vshcherb** [comment] 2024-04-02 12:50
Selection stopped working between 2023-08-28 and 2023-09-20 - dont't see any changes yet (full selection)....

**Comment by vshcherb** [comment] 2024-04-02 18:43
We narrow down and search and found https://github.com/osmandapp/OsmAnd/commit/aef517594adc7515f16b11cbc02aa651e8c61bab#diff-f50a685ff2411ce64b328b93bbe8537cbcf826612489535ba20bdbc682f24312L360-R361 (still unlikely we can fix it cause it needs to be something in material lib )

**Comment by dafadllyn** [comment] 2024-04-02 20:12
> In latest versions is now a delete button in the very right end of the text field which deletes the text.

Prerelase? I use the latest version availabe in the Google Play Store, which is version 4.6.13, and there isn't such a button (see screenshot in first post above).

**Comment by scaidermern** [comment] 2024-04-03 11:29
> It's beta program Google Play

Nope. The current OsmAnd beta 4.7.4 doesn't have a delete button at the end of the text field for me. Probably only exists in the nightly?

**Closed** 2024-04-03 17:15 UTC
Labels: Observed

**Comment by vshcherb** [comment] 2024-04-03 21:09
4.7.5 was not released issues with Android Auto, hopefully this week will be in public beta

**Comment by DmitryAlexei** [comment] 2024-04-11 14:01
OsmAnd~ 4.7.0#2035m, released: 2024-04-10
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/be8dcf79-cf95-4628-9f6b-d639d6ee931b"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dafadllyn** [comment] 2024-04-16 19:10
@Chumva: Thanks a lot! (Now using version 4.7.9.)
