### ISSUE TITLE
feature request: marker's altitude

### ISSUE THREAD

**Issue by dtcgb** [osmandapp/Osmand#3183] opened 2016-10-18 22:37 UTC
When tapped, a marker will reveal its info: name if any and coordinates.
It'd be really nice to also be able to show the current altitude, completely offline.
You can roughly work it out by activating the contour lines layer but a real feature would be ideal.
Hikers from everywhere say thanks!

**Comment by littlehelper** [comment] 2016-10-19 04:56
Yes, that would be great.
(similar to #2487)

**Comment by vshcherb** [comment] 2016-10-19 17:41
We don't have "raw" SRTM data on the phone so it is quite impossible to do now.

**Comment by dtcgb** [comment] 2016-10-23 15:54
Mmmh. 
And how about an approximate reading, from the contour lines data, with a 10m margin of error (which is the smallest distance available between two lines)?
The data is out there already, and "offlineable".

Is it still technically unfeasible?

**Comment by sonora** [comment] 2016-11-24 16:53
Duplicate of #2487, I guess.

**Closed by sonora** 2016-11-24 16:53 UTC
Labels: Nice to Have
