### ISSUE TITLE
The coast line on the map changes with the zoom

### ISSUE THREAD

**Issue by Rpnpif** [osmandapp/Osmand#7366] opened 2019-08-03 19:00 UTC
To reproduce :
1. Load the map of France Bretagne.
2. Display the place on 48.35924° N, 4.26437° Ẅ.
3. Set the zoom to 17 and observe.
4. Set the zoom to 16: The car park is under the water.

The car Park should not be blue color (in the water).

**Comment by Rpnpif** [comment] 2019-08-03 19:05
Zoom 16
![Screenshot_20190803-204824](https://user-images.githubusercontent.com/3252332/62415924-3c6e6a80-b632-11e9-8d31-df1f626c400f.jpg)

Zoom 17
![Screenshot_20190803-204837](https://user-images.githubusercontent.com/3252332/62415935-5e67ed00-b632-11e9-9f7c-826076f8ebea.jpg)

**Comment by xmd5a2** [comment] 2019-08-05 17:29
Duplicate of https://github.com/osmandapp/Osmand/issues/6565

**Closed by xmd5a2** 2019-08-05 17:29 UTC
