### ISSUE TITLE
GPS issues on OnePlus 6T

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6410] opened 2018-12-30 14:28 UTC
Normally opening OsmAnd+ is fine, but it seems if it is 6+ hours since the last opening, it gets a GPS issue. OsmAnd+ shows 0/0 for the satellites. 
Just before opening OsmAnd+, I have tried at times opening other GPS using apps like Google Maps, Waze, OS Maps, TomTom Go, CamerAlert, GPSTest, they all get GPS location fine. I can then close them down and open OsmAnd+ and (if 6 hours have passed since I last opened it) I at times get the 0/0 for the satellites, after a little while it can then show 0/x, x being something like 1,3,5, 8. 
If I then open GPS Test, I can see some satellites (Only the USA ones) but none locked, and yet just before opening OsmAnd+ it would be showing something like 22 of 31 locked.
Do you think there could be a compatibility issue with OsmAnd+ and the Oneplus 6t?

**Comment by erikrr** [comment] 2019-01-11 17:05
I have the same problem since today after giving my OnePlus 5 an update from 9.0.1 to 9.0.2
Never had this problem before.

I was in a city and couldn't get a fix, it showed 0/7 satellites. It keeped showing that for minutes normally I get a fix max 5 seconds and also double the satellites.

I tried another time somewhere else same problem.

Then I tried what you said, I put the phone to the window for 15 minutes so it could see satellites and build up the database.
It seemed indeed a cold fix after that 15 minutes it showed 7/17 satellites.

So I hope it remembered because I don't want to load 15 minutes before I can find my way each time or day.

**Comment by sonora** [comment] 2019-01-13 09:52
Yes, it sounds like a 'cold start' of the GPS, however that should be a system-wide thing, I currently would not know how only OsmAnd could be affected.

In order to debug, can I suggest  2 experiments: 

- Test 1: Temporarily disable all Power Savings features for your device in its Android settings. Check for a few days if that changes this behavior in any fashion.

- Test2: In OsmAnd, could you temporarily enable the Development Plugin. With that, you would see an OsmAnd setting Settings/OsmAnd development/A-GPS settings. I had once implemented this, tap it to force an A-GPS download when the issue occurs (need to be briefly online for that). I would be interested if that speeds up the 'recovery' of the GPS in OsmAnd. (Which would in deed indicate something like a cold start issue.)

For all tests, it may be wise to set the Android 'Location' setting to 'GPS only', just to make sure you investigate the GPS isolated, and not mixed up with other Location modes and how different apps behave with such mixture.

**Comment by erikrr** [comment] 2019-01-13 15:14
Today I had again no gps. GPS test didn't see any satellites either.
Ok it sees them but no fix/lock

However Google maps has no problem it works. But Google maps always had more ways to get location data.

I tried the a-gps dload from the osmand setting menu with the plug-in but that didn't help.

So it seems it does a cold fix when you haven't used your GPS for x hours. Or how I see it it forgets it's data/almanak after x hours.
A big problem for me.

I already had battery optimalisation put to off.

Will test some more.

**Comment by erikrr** [comment] 2019-01-14 13:21
No I am afraid that the problem lies with OnePlus this time but I already made bug report at OnePlus.
Let's see what happens.

**Comment by erikrr** [comment] 2019-01-24 11:48
Still testing a workaround that get a quicker way to find that sats.
I made some progress still I am not 100 procent sure that there isn't a problem with osmand that handicap other GPS apps.
When I am ready testing the workaround in look into it.
I see the last days a crash late night or in the morning sometimes without even starting OSMAND.
Maybe that mess some thing up.
Unfortunately I didn't save the crash logs because I didn't connect the dots then.

Also 903 is available maybe that solves the problem.

**Comment by erikrr** [comment] 2019-01-24 11:54
If i do nothing then I see 0 of 7 sats so no fix for 10 to 17 minutes waiting to build up the sat almanac.

Btw why dont newer sats like Galileo speed up this process with pushing more and faster data to the receiver?? There must be a quicker way.

And after the cold fix it sees 25 to 30 sats with a fix with 10 of them a big difference.


Another question do GPS apps share the almanac or does each app has its own almanac copy?

**Comment by sonora** [comment] 2019-01-25 06:40
From what I remember, Android handles GPS system-wide and not on an app level, meaning that e.g. for downloaded A-GPS data it makes no difference if you downloaded it in OsmAnd (where it happens automatically, but you can also force it, see above), or e.g. in the GPS Status & Toolbox app (where it also by default automatically happens if older than 6 hours, and you can also manually force it.) The latest almanac data is always used everywhere, system-wide.

At the time I implemented (and likely still today), there was no way to read the time stamp of the system's last A-GPS download. Workaround is to track it in the app where you perform a download .This is why e.g. OsmAnd and GPS Status will report different download dates (each when they themselves performed a download), but only the newer of the 2 would be correct, or both could be outdated if a later update was performed by a 3rd app. But all apps would always use the latesd version, as the system GPS service only stores one.

**Comment by erikrr** [comment] 2019-01-29 11:20
Hi what helps for me is this maybe other people has something on this information.

Like I promised I tested or the workaound work every time. It changed a lot of thing background settings etc so when it worked I didn't know what did the trick and have to switch off one setting at a time wait a day to test etc.

It's very simple. What I do each morning switch gps on for the window, switch my gpsapp on and when I see less then 20 sats. I know it lost the almanac and i have to wait 8 to more likely 15 minutes.
But if you quickly reboot the phone in less then 10 seconds. After it rebooted it says 21 to 30 sats and has a fix in a few seconds.
Somehow when quickly rebooting it finds access to the lost almanac again.

But if you wait to long with rebooting then the almanac is really lost and you have to wait the 15 minutes to cold fix. I think it the old almanac gets written over.

The new update to 903 didn't do anything.

Normally I see at least 21 but sometimes 30 sats so when I see only 7 or 13 I know it's lost the almanac.

**Comment by erikrr** [comment] 2019-01-29 11:33
Tried that already but that didn't help in this case 
Even with updated agps data from gps data and status it made no difference. Not in OSMAND and not in toolbox. At least not in my case it could help for others

**Comment by sonora** [comment] 2019-01-30 09:01
In any case, as I explained somewhere above, OsmAnd performs an almanac update itself once a day (if online), and using the development plugin you can even verify when that happened last, or trigger it anytime. So the presenence of the almanac does not seem to be your issue here.

Unless you have some other background process, faulty app, or faulty system process, deleting the almanac without refreshing it or in some other fashion keeping it from being used. To rule out installed apps, maybe go through your list of apps, check which ones have location permission, and see if these are all well trusted mainstream apps or if one could cause the GPS loss. If it is not installed apps, it really sounds like a system or device issue and should be addressed to the vendor or manufacturer.

**Comment by erikrr** [comment] 2019-01-30 10:05
True I didn't mention it, sorry about that I forgot. The problem is not osmand but in Oreo, somehow blocking access to the almanac.

**Comment by erikrr** [comment] 2019-02-04 11:09
Yesterday I discovered something weird.
I started GPS Test first in the morning and it saw a lot of sats and had a
quick fix.
Ok must be a coincidence that's possible.

I closed GPS test and started OSMAND and expected the same behavior. But
OSMAND said only a few sats in view and no fix the first 30 40 secs.

Then I closed osmand and started gps test again to my surprise it didn't
see all the sats that it saw a few minutes before before. Only few visible
and no fix anymore.

Now that also could be a coincidence so tried again this morning and had
the same result as yesterday.

It's if the almanac get deleted/blocked once osmand starts. But that
doesn't seem possible. Will do some more testing the next mornings.
Maybe a combination between osmand and OnePlus Android 902 biting each
other somehow.

Luckily the reboot trick still works





Op wo 30 jan. 2019 10:01 schreef Hardy <notifications@github.com:

**Comment by erikrr** [comment] 2019-02-04 11:20
Anyway I switched of the wifi use of location and installed the developer plugin again.
I noticed the is a lot slower to get. But how do I force a agps dload?
Can't find the setting anywhere

**Comment by scaidermern** [comment] 2019-02-04 11:36
> Yesterday I discovered something weird. I started GPS Test first in the morning and it saw a lot of sats and had a quick fix. Ok must be a coincidence that's possible. I closed GPS test and started OSMAND and expected the same behavior. But OSMAND said only a few sats in view and no fix the first 30 40 secs. Then I closed osmand and started gps test again to my surprise it didn't see all the sats that it saw a few minutes before before. Only few visible and no fix anymore.

This is odd. It sounds like OsmAnd downloads a GPS almanac of lower quality or an outdated one.

**Comment by erikrr** [comment] 2019-02-07 11:15
Did the same test again but now with GPS toolbox status.
Same result toolbox sees all the sats and get a fix immediately. Then I close toolbox and start osmand the last sees almost no sats so I close osmand and start status again and now status thinks the last agps update is 22 hours old and see almost no sats anymore.
Dload new agps doesn't help it says 0 hours old but still doesn't see the sats.
Rebooting doesnt help either.

**Comment by sonora** [comment] 2019-02-28 07:59
Weird. When I had last researched this years ago, there was only one systen-wide almanac, and it had no accessible time stamp as far as I know, hence the only way to produce a time stamp was 'remember' in the very app which performed the download. (Meaning that a time stamp app A remembers from its download may actually be too old if app B performed a newer download, but in any case there is only one almanac.)

Forcing almanac download in OsmAnd: Simply tap on the line item in the dev plugin. Must of course have an Internet connection at the time, for the download to succeed. If not, the old almanac and timestamp should simply remain in place.

Should we really find out there is an issue with when/how OsmAnd performs its almanac download with latest devices or Android v9, we may have to re-visit that, or as an interim measure maybe add a checkbox to that dev menu facilitating disabling the automatic download. For now, if I remember correctly, my code performs an auto-update of the almanac if it believes it to be older than 24 hours and if it has an Internet connection ('and', not 'or').  Or you can trigger it manually, as described. I think this code has been unchanged for many years.

**Comment by sonora** [comment] 2019-02-28 08:26
Code ref: https://github.com/osmandapp/Osmand/blob/ac573d39018657ab864fdf120fb16a7abc90199e/OsmAnd/src/net/osmand/plus/OsmAndLocationProvider.java#L282

**Comment by erikrr** [comment] 2019-02-28 10:39
I also send a bugreport to Oneplus, one of them asked me for more details and to make logfiles for them to to research what happened.

First i send a log and they come back with:
Did you use "cold start "?
We checked the log and the XTRA data was deleted.
It will cause GPS issue if you use "cold start".

(of course i didnt do a cold start)

Then they asked for more logs:
We think the XTRA data was deleted when you used OSMAND app and it will take more time to locate when XTRA data is deleted.

Sorry, please follow these new steps to collect the logs.
Please help collect GPS log in big open space where you can see the sky like in roof/ square (outdoors).
Please upload log to google driver or transfer to computer after you collect every log. Otherwise the old log will be deleted when you collect new log.

Log1:
1. Input the command *#800# in dial-up interface, click "oneplus Logkit"
2. Click “move log path to built-in SD card”
3. Go back and click “Get Wireless Log” and then click “Delete history logs”
4. Click “Get GPS Log” to start capturing. When it informs you whether to reboot, please click “cancel”
5. Please don't activate OSMAND app. Start the other map apps and take screenshot. and Use the app to navigate for 5-10 minutes.
6. Return to the log interface and click “Stop logging”, then click “move log path to built-in SD card” again to stop it.
7. Enter file manager, choose storage, find the oem log file and long press and click right upper corner three dots to compress it and send it to: 

Log 2:
1. Input the command *#800# in dial-up interface, click "oneplus Logkit"
2. Click “move log path to built-in SD card”
3. Go back and click “Get Wireless Log” and then click “Delete history logs”
4. Click “Get GPS Log” to start capturing. When it informs you whether to reboot, please click “cancel”
5. Activate OSMAND app and take screenshot. Use OSMAND app to navigate for 5-10 minutes.
6. Return to the log interface and click “Stop logging”, then click “move log path to built-in SD card” again to stop it.
7. Enter file manager, choose storage, find the oem log file and long press and click right upper corner three dots to compress it and send it to: 


After that i got their feedback

We checked both logs. 
GPS request and return were fast and normal in log 1.
GPS request is normal,but return was slow because the XTRA data was deleted in log 2.
So we believe it is OSMAND app peoblem. Please try to feedback the problem to OSMAND app.

High regards
OnePlus Bug Hunters

**Comment by tadeasbucha** [comment] 2019-02-28 20:24
Wow, this thread is literally my life over past 2 months with regards to OSMAnd. I experience the same issue as previously stated. If I may be of any help, please let me know.

**Comment by sonora** [comment] 2019-03-01 00:55
I found this thread https://stackoverflow.com/questions/4961514/problems-with-sendextracommand-and-force-xtra-injection, the first answer to it indicates that the app GPS Status uses similar code than I do in OsmAnd. So it would be interesting to know if it causes the same issue (either just by starting it, or by performing an A-GPS download with it.)

Other things I am struggling with:
- Does the issue really only come up after 6 hours of not having used OsmAnd?
- Is the issue reproducible, or sporadic?
- You sound quite confident the issue only appeared after the Android 9.0.2 upgrade?

I am beginning to think if it really is something in OsmAnd, it may not be the A-GPS download (as it happens only every 16 hours unless triggered manually), it may be something in how we use the LocationProvider, which became incompatible with Android 9.02+.  Are you actually using OxygenOS 9.0.2, right? I found some changelogs for it, but nothing too specific indicating changes to GPS behavior ...

**Comment by sonora** [comment] 2019-03-01 01:51
Working from the theory that maybe force XTRA injection no longer works on affected devices, I have made a small change not forcing a cold start before trying to inject A-GPS data. Could anybody please try the latest nightly to see if the issue is gone?

**Comment by erikrr** [comment] 2019-03-01 02:00
Can you send me the nightly /APK or how it is called
Or tell me where to find it

Op vr 1 mrt. 2019 02:51 schreef Hardy <notifications@github.com>:

**Comment by sonora** [comment] 2019-03-01 02:25
Nightly of the free version is here: http://download.osmand.net/latest-night-build/OsmAnd-default.apk

It should install in parallel to the paid version, I think, also using a separate data (map) folder.

**Comment by erikrr** [comment] 2019-03-01 11:59
Installed it, it can take a while before i can give feedback think at last
a week or so before i can say something.
If the fix doesnt work i know immediately but if it works not becuase the
last 2 weeks some days it found the sats the next morning. Before that each
day at 11 in the morning they were 100% gone. So testing can take a while.

I made a back up to be sure not to loose anything. However they start
separately but i cant find the map of the nighlty to put my favorites and
user settings from the paid version in. Is that possible? its not a big
problem if it doesnt
.


Op vr 1 mrt. 2019 om 03:25 schreef Hardy <notifications@github.com>:

**Comment by sonora** [comment] 2019-03-01 15:39
Ok, thanks! I would be interested to know if,  in the 'old' and on the 'new' version, when you tap the A-GPS menu item in the development settings, the download timestamp changes to the current time for you. If it does only for the new version, it would be an indication that we are on the right track.

Regarding your questions of transferring settings: I am afraid you will have to do that manually as needed, we have no export/import for that.

The free version of OsmAnd stores its data under (storage)/Android/data/net.osmand/files, while the paid version uses  (storage)/Android/data/net.osmand.plus/files. You can manually copy map files and the favorites.gpx between the 2 folders. To import favorites, locate the favourites.gpx file in the (old) data folder, tap it, then in the pop-up menu select OsmAnd to open it, and then select 'import'.

Our FAQ page at http://osmand.net/help-online/faq has some more useful information, in particular how you can temporarily uninstall one version without losing your data. Also, if you cannot find the data folder, maybe it is in internal storage and you must change it to external storage in order to see it, as explained in http://osmand.net/help-online/faq#change_maps_dir.

**Comment by erikrr** [comment] 2019-03-01 16:15
I finally found the right agps setting in developer options. I was always
tapping the 0/13 sats line on the main screen then it asked which program I
want to use 'GPS test' and then waited a few minutes and nothing useful
happened :-)

I tried both, old first and then new tapping the line in Dev options.
Both had an old time line 12:26 after tapping it was 16:56 or so.
But after the agps dload the fix I had before agps was gone and fewer sats.
It was like it did a full reset, thrown away all known data/locations
instead using new data to complement the old data. I don't know if that is
suppose to happen.

Then I tried the new version but he didnt get a quick fix anymore also
after agps again the time line changed but also the same reset result. I
had better tested the new version first.




Op vr 1 mrt. 2019 16:39 schreef Hardy <notifications@github.com>:

**Comment by sonora** [comment] 2019-03-01 17:12
Ok, thanks,! Let's watch it for a few days.

The difference between the old and the new version is that in the old version we reset the A-GPS data before downloading the updated information, the new version only downloads the updated info without performing a reset. I had never observed any issues, but perhaps the reset causes a cold start of the GPS chipset on your device after updating to 9.0.2.

**Comment by erikrr** [comment] 2019-03-02 09:21
First test today and it went well.

First the app 'gps test' it worked. Lot of sats.

Second the nightly it worked too. Quick fix and lot sats!

Then the old version and all sats and sat fix were gone :-(

Nightly again also no sats anymore.

So my first impression seems to be that your fix in the nightly works. Will
do some more testing but I think you found the solution for this problem


Op vr 1 mrt. 2019 18:12 schreef Hardy <notifications@github.com>:

**Comment by erikrr** [comment] 2019-03-03 19:02
Second day old and new had no problem both did see the sats and had a fix.
But osmamd got updated to 3.3.2 when i started. Could it be the updated
3.3.2 version has your fix too?

Op za 2 mrt. 2019 om 10:21 schreef Wow <worldorder2000@gmail.com>:

**Comment by sonora** [comment] 2019-03-03 22:22
@vshcherb I think so, right, Victor? (https://github.com/osmandapp/Osmand/commit/c1e5307e926b73e331fe775153cc5cb600433248)

**Comment by vshcherb** [comment] 2019-03-04 09:17
@sonora  looks good

**Comment by sonora** [comment] 2019-03-04 09:23
@vshcherb  Couldn't determine if the fix is in release 3.3.2. But I think you built straight from master, so it is?

**Comment by erikrr** [comment] 2019-03-05 08:37
Today and yesterday both versions had a quick fix and instant 30 sats


Op ma 4 mrt. 2019 10:23 schreef Hardy <notifications@github.com>:

**Comment by erikrr** [comment] 2019-03-10 23:08
After a week of testing I can say it works much much better. 

However sometimes I still took a few minutes instead of seconds
I goes something like this:
0/15
0/16
0/17
0/18
.....
0/25
After a 1 or 2 minutes it goes to
0/0
0/1
0/2
Etc
And then in one minute it will have a fix soon.
No idea why it goes from 25 sats in view, but not fix yet, to 0 SATs and start seeking again from zero.

It's not a 17 minutes cold fix but also not a 5 second hot fix but something in between.

But most of the time it were hot fixes and lot of sats

So I am happy with the fix, thnx.

**Comment by sonora** [comment] 2019-03-14 00:05
Ok, thanks for the feedback. I think that is all that can be done in OsmAnd. Whatverer is left is likely a peculiarity of your device's GPS chipset and drivers. And actually I see that in a number of devices, while in others not.

Yes, the fix is in the latest release, thx for testing the nightly, can probably uninstall now.

**Closed by sonora** 2019-03-14 00:05 UTC
Labels: Observed

**Comment by djselbeck** [comment] 2019-03-19 07:54
Just want to say thanks to all involved here, this also fixed problems on Sonys AOSP for the XZ1c

**Comment by erikrr** [comment] 2019-03-25 14:24
Unfortunately, i think 10 days ago i got some new problems not encounted
before while testing. Maybe because a new update from Oneplus to 9.04
around the same time. I think i never update again anymore.
What happens is that 50% when i switch Navigation on, it works or it shows
a blue dot where i am on the map but says 0/34 sat. How can that be
possible if it shows the dot on the map he must have a gps fix.

However the blue location dot shows where i am on that moment on the map
but it doesn't transform  to the blue arrow.
When navigating thats horrible at last Saturday i was was in Germany.
Saturday i had no problem on Sunday a big problem no navigation possible.
There i stood no way to show me the quickest route to the station and i was
already late for that train..

The thing is that i can on a bad days start with "gps test" get a fix,
switch osmand (nightly or newest build)  get a blue dot and 0/34 sats, then
go bakc to "gps test"again and he has no sats anymore.

Maybe you have an another idea where this problem can come from? And how to
fix it. It would be great because i dont want to buy a new mobile but if
not fixable i see no other option because i need something i can 100% count
on.






Op di 19 mrt. 2019 om 08:54 schreef Hendrik Borghorst <
notifications@github.com>:

**Comment by erikrr** [comment] 2019-04-01 11:08
To be honest I did a test for six or seven days at a row.
And all days I had a quick fix only one day when I went from Holland to Belgium the next day I had no fix but after a reboot he got it.
So the problem isn't so bad that I had to buy a new phone 
I try to work with this one for now and test it some more. had to learn a few workarounds. If it keeps working 6 from 7 times it is good enough.
I don't want to miss osmand tried other programs but they don't feel right.
