### ISSUE TITLE
dotted line to indicate toll road dependent from too many facts

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#19087] opened 2024-02-12 14:51 UTC
### Description

The display of the dotted line of toll roads on streets depends on zoom level (ok), 
map style (bug?), 
presence of world overview map (NOT mini) (bug)

### Steps to reproduce

dotted line is visible if
zoom level >   ~**10**  AND
map style is in (OsmAnd, Mapnik, Desert)  AND
world overview map (NOT mini) **DE**activated

if different map style (touringview, ?)
OR world overview map activated 
then
dotted line is visible if
zoom level >  ~**12**

For planing a longer trip it is better to see dotted line on lower zoom levels like 10. So for planning i have to **de**activate world overview map to get more overview 

### Actual result

See above

### Expected result

See above

### Your Environment (required)

OsmAnd Version: OsmAnd~ 4.7.0#1572m, veröffentlicht: 2024-02-12
Android version: 10
Device model: samsung tab S5e
Crash-Logs: no

**Comment by yuriiurshuliak** [comment] 2024-02-19 16:41
I attempted  to reproduce  the issue by comparing the two map styles, OsmAnd and Touringview. At a zoom level of 10, the dashed Access Toll line appears in both styles. However, at a zoom level of 12, the Access Toll is represented as a dashed line solely in the OsmAnd map style, while in Touringview, it is depicted as highlighted orange-yellow lines.

It's worth noting that diverse map styles cater to different requirements, and the variation observed might be influenced by the specific characteristics of each style.

OsmAnd~ 4.7.0#1627m, released: 2024-02-19

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/261dd1de-e058-4e2b-ba64-17b7abce3542"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/b0ef4467-6c44-464a-a501-c85f25b64cf8"  width="300" height="auto"/> </th>
  </tr>
</table>

<table style="width:100%">
  <tr>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/62049c7a-de89-433e-9994-54a815480515"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/302febad-1830-4063-8b2d-1f9d9ded7e17"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by pebogufi** [comment] 2024-02-19 18:14
I understand that different map styles show different objects, that is no problem for me. 
But i don't understand that the presence (visibility) of world overview map inhibits the dotted line for some map styles for zoom level 11 and 12.
Is it possible that world overview map overwrites regional map (dotted line) at theese two zoom levels with the motorway line red/yellow/red ?

**Comment by sonora** [comment] 2024-02-19 19:12
Hm, not sure I can reproduce the issue, I just looked at Rome and it seems the toll roads around Rome are correctly shown using the Touring View map style: I also cannot find any dependency of this on the presence ot not of any other maps, like the any world overview maps...

![Screenshot_20240219-200804_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/8a697a6d-7d40-450b-9ec2-cc94691c7d5e)

**Comment by pebogufi** [comment] 2024-02-20 06:46
Yes, touring view has the problen to see dotted line only with zoom level > ~12, see my first statement. 
Please try with map style in (OsmAnd, Mapnik, Desert) AND then 
world overview map (NOT mini) DEactivated
Or activated.

- DEactivated - dotted line visible when zoom level > ~10 
 
- activated  - dotted line visible when zoom level > ~12

**Comment by pebogufi** [comment] 2024-02-20 10:00
@sonora 
Looks like you use rendering engine 1, I can confirm that it shows dotted line wth Touring View from zoom 10, thats ok, i love it !
But with rendering engine 2 it shows dotted line with Touring View  only from zoom level 12.

**Comment by pebogufi** [comment] 2024-02-20 10:11
... and i confirm that dependency of the presence of any other maps, like the any world overview maps is only a problem with new rendering engine 2, no problem with r.e. 1.
Sorry since some months I use only the new r.e. 2, i did not report that or check it before.

**Comment by sonora** [comment] 2024-02-20 18:52
@pebogufi Ah, ok, yes, in deed I was testing with v1.

I noticed that there had been some small changes to the files some months ago trying to fix some Touring View behavior with the v2 engine, which had elapsed me. I have now made an obvious correction which may fix the issue :https://github.com/osmandapp/OsmAnd-resources/commit/3406f45dba1cf04637390a54d866740252acb5b3. Does that solve it?

**Comment by sonora** [comment] 2024-02-21 22:09
Right, so it sounds the Touring View specific peculiarity has been resolved  and now it needs to be checked why with the v2 engine the world map supresses the toll road display for zoom 10 and 11...

**Comment by vshcherb** [comment] 2024-02-27 17:35
Would need some investigation from @xmd5a2 to understnad whether it map data issue or rendering engine

**Comment by xmd5a2** [comment] 2024-03-21 06:15
Dev notes: looks like Basemap_SimplifyRoads job is broken.

**Comment by xmd5a2** [comment] 2024-03-26 13:19
Basemap was fixed and updated. Please retest this:

> Right, so it sounds the Touring View specific peculiarity has been resolved and now it needs to be checked why with the v2 engine the world map supresses the toll road display for zoom 10 and 11...

1.Turn on "Show toll restrictions" in Configure map - Details
2.Download full basemap
3.Download Russia_moskovskaya-oblast_asia map
4.Go to https://www.openstreetmap.org/way/870545810 and see that it has dots on it at zoom 10-11
Zoom 10:
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/5057971e-e820-4ad6-8b7e-1edb03f89874)

Zoom 11:
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/de88b64b-9431-4587-a59c-1e8f4d0ea2e9)

**Comment by pebogufi** [comment] 2024-03-26 14:30
Confirm fixed, now I like it so much 😃
Thanks a lot, Peter

**Comment by pebogufi** [comment] 2024-03-27 07:17
> @pebogufi Ah, ok, yes, in deed I was testing with v1.
> 
> I noticed that there had been some small changes to the file some months ago obviously trying to fix some Touring View behavior with the v2 engine, which had elapsed me. I have now made an obvious correction which may fix the issue: [osmandapp/OsmAnd-resources@3406f45](https://github.com/osmandapp/OsmAnd-resources/commit/3406f45dba1cf04637390a54d866740252acb5b3). Does that solve it?

@sonora 
Due to your fix I know where the zoom factor can be set. Thanks a lot. Currently I set it after every update to 8 which is fantastic for planing long travel. Could you set it to 8 in the resources ?
This would be really great 🌞

**Comment by sonora** [comment] 2024-03-28 20:06
Ok, let's try! ;) Untested, so please let me know if its really worth it and does not provide more clutter than benefit!

**Comment by pebogufi** [comment] 2024-03-29 11:26
@xmd5a2 
NEW BUG in new version of new created "world overview map".
In France a part of a motorway is now tagged as "with toll" which is wrong, see detail local maps.
E11 (A 75) south of Clemont-Ferrand
Wrong part starting *near* Brioude 45.29450 N, 3.24316 E
to south
Beziers 43.33950 N, 3.29621 E
Between theese two points is only a smal part WITH TOLL, the bridge in the west of Millau "Viaduc de Millau" 44.07866 N, 3.02333 E.

**Comment by sonora** [comment] 2024-03-29 16:04
Perhaps it's not such a good idea to use minzoom=8 for the toll road display? Because that takes the data off the overview map, and I am not sure it's valid rhere and detailed enough... pls let me know.

**Comment by pebogufi** [comment] 2024-03-29 17:36
I use "8" since your change at Feb 20, just setting it by hand after every app update in Touring-view_(more-contrast-and-details).render.xml
line 1321 and I am absolutely happy with it.
I am traveling through south of france since 3 weeks.
It is perfect for planing over some distance.

**Comment by pebogufi** [comment] 2024-03-30 07:01
One more hint.
The option "show access restriction" was divided into
-  "show *access* restriction"
and
-  "show *toll* restriction"

In Touring-view_(more-contrast-and-details).render.xml this change was NOT made,
toll works with   "show *access* restriction" until now.

**Comment by sonora** [comment] 2024-03-30 07:55
Regarding the new separation between access restriction and toll: Yes, there's more and more diversification and detailing happening, which increases not only the complexity and effort for code maintenance (and opens new occasions for bugs to occur and performance to slow), but in the end also demands more time from users to configure everything to their liking and usability. :( Oh well, I can take the time to look at it...

**Comment by vshcherb** [comment] 2024-04-01 22:31
If basemap generated please close it @xmd5a2

**Comment by xmd5a2** [comment] 2024-04-02 11:52
@pebogufi  Please create a different issue for this (https://github.com/osmandapp/OsmAnd/issues/19087#issuecomment-2027104671)

**Comment by xmd5a2** [comment] 2024-04-02 11:53
How to test: https://github.com/osmandapp/OsmAnd/issues/19087#issuecomment-2020413064

**Comment by dmpr0** [comment] 2024-04-11 15:09
# Review
- [ ] Proper instructions is required

**Comment by vshcherb** [comment] 2024-04-12 10:36
Reverted to combined option of toll//access

**Closed by vshcherb** 2024-04-12 10:36 UTC
Labels: rendering, ~
