### ISSUE TITLE
When updating maps (OsmAnd+ version) the previous file remains open

### ISSUE THREAD

**Issue by iosabi** [osmandapp/Osmand#5940] opened 2018-08-25 20:51 UTC
When downloading offline maps, the files are replaced and the previous files are erased. However, the old files are kept open (the app holds a file descriptor open to it). This causes the filesystem to keep the files around until the last fd is closed, even if they are not reachable anymore in the /sdcard/osmand/ directory.

This will cause the device to run out of space if the free space is not enough to download all the pending maps while keeping the previous ones (not just the space needed for the incremental size). A workaround is to close the app and re-open it, so the old files are released when the process ends and the filesystem can free that space.

To reproduce this issue follow these steps:
1. open a shell, check the free space on the device (df /sdcard). Note the free size.
2. Open OsmAnd
3. "Download Maps" -> "Updates", update a few maps, note the download size.
4. go back to the shell and type "df /sdcard". The free space went down by the download size (more actually).
5. Close OsmAnd (simply swipe it away).
6. go back to the shell again and type "df /sdcard", you see the space of the old files back as free space.

**Comment by scaidermern** [comment] 2018-08-26 06:04
Duplicate of #3108?

**Comment by vshcherb** [comment] 2018-08-26 12:43
Yes it is duplicate of #3108

**Closed by vshcherb** 2018-08-26 12:43 UTC
