### ISSUE TITLE
Public Transport (train, railroad) unexpected or unsafe walking routes at start and end

### ISSUE THREAD

**Issue by lunkhub** [osmandapp/OsmAnd#13694] opened 2022-02-05 12:54 UTC
# 🐞 routing report
Description

Using Public Transport (train, railroad) beta navigation to estimate time between stations, the route included, unexpected, some minutes of walking route near start and finish of rail route. One walking route crossed several tracks (unsafe). Both walking routes went to "random" destinations. See screenshots of start and finish locations with walking routes shown.

Expected behavior: Show only rail route, **without additional walking route** (?). Or show more sensible, safe walking route to a location on the train station platform (?).

Note: I understand defining the station platform locations may be difficult because of multiple platforms and station buildings, and this may be a map issue. Having public transport data in the maps is awesome!

### Routing engine

- [X] OsmAnd's in-app offline routing

### Routing Profile

Public Transport. Defaults IIRC.

### Start and end points

How to reproduce?

Choose train station destination, choose train station start location. These locations are at or very near actual train stopping locations (on or within meters of the rails). Navigate. See minutes of walking in route details, or zoom in on map to see walking route near start and finish locations.

Example destination: High Point NC Amtrak, 35.95753, -080.00594
Example start: Greensboro NC Amtrak, 36.06880, -079.78658

### Actual and expected routes

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/66975721/152642954-1a83b3a3-d901-47ff-b171-fd7c257d7858.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/66975721/152642959-711b2098-3d21-4c23-9a25-43a9d3b43a58.png"  width="300" height="auto"/> </th>
  </tr>
</table>

### Is this a regression?

Not to my knowledge.

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd~ 4.1.11 from F-Droid, Jan. 2, 2022
</code></pre>

**Device and Android/iOS version:**
Android/iOS version: Android 11, DivestOS 18.1, Jan. 2022
Device model: Nexus 6
**Maps used (online or offline):**
Offline Maps, North Carolina USA, Jan 1, 2022

- [X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by OpenSourceForEver** [comment] 2022-07-10 17:35
Relationed with https://github.com/osmandapp/OsmAnd/issues/6744

The problem is not only when start and end points are a rail station, but also when changing and with other means of public transport (buses...).

**Comment by ivanPyrohivskyi** [comment] 2023-06-20 15:13
Need to find more places

**Comment by lunkhub** [comment] 2023-06-22 04:42
Updated to OsmAnd~ 4.4.7 from F-Droid. Offline maps 1 June, 2023.

I think the problem is partly map data. Most USA Amtrak stations and platforms I look at do not have walking routes defined inside or around station buildings and platforms. The second problem is OsmAnd does not end route where it does not have a good walking route pathway or sidewalk, or it goes too far.

Two more locations:

Petersburg Amtrak Station (37.24174, -77.42884) to Richmond Staples Mill Station (37.6178, -77.49651), Virginia, USA. At Petersburg, from the station building, it wants a 1 mile walk far around the station. From the platform it wants a walk across tracks to Laurel Road, then back across tracks. At Richmond it wants a very short walk, ~100 meters, but it goes around the station building passing a block, not through the station building where people  go.

Alexandria Amtrak Station (38.80643, -77.06223) to Washington Union Station (38.90003, -77.00501), DC. It wants 6 minute walk around Alexandria Amtrak Station, and 9 minute, 0.45 mile walk around Washington Union Station. A walk along the platform is required, but nothing like what it says beyond that.

Let me know If you want more. Thanks for a great app.

**Comment by lunkhub** [comment] 2023-06-22 04:48
Another comment. It always jumps straight to routing, before both Start and Finish are final. So effort is wasted until both are defined. If there is an option to delay routing start until both are defined, please tell me.

**Comment by xmd5a2** [comment] 2023-06-23 06:32
99% of railway station doesn't have footways connected to railways and this is right from OSM point of view because they are not physically connected. In best mapped cases we have footways connected to platform (way) or edge of platform (area). So in most cases even routing via platforms is not possible.

**Comment by OpenSourceForEver** [comment] 2023-07-03 15:52
Osmand should route to the platforms, since objectively it is the place where people go to take public transport.
Although there are no pedestrian paths that link the platforms with other paths, this would be better than the current routing, since now stop_position is routed with any other path, although logically, this point has no connection with other paths in the map.
This should also be the case on bus platforms.

**Comment by vshcherb** [comment] 2023-07-17 11:04
We have platforms routable https://www.openstreetmap.org/way/514385159 though we don't support free form of navigation by pedestrian:area / platform, so for now we only support when platform is connected with pedestrian route by a common node.

**Comment by vshcherb** [comment] 2023-07-17 11:53
This issue is solely related to pedestrian navigation which could be improved with area routing. So this issue is merged to https://github.com/osmandapp/OsmAnd/issues/2586

**Closed by vshcherb** 2023-07-17 11:53 UTC
Labels: routing
