### ISSUE TITLE
Investigate when "toll booth" should be announced

### ISSUE THREAD

**Issue by jirislaby** [osmandapp/Osmand#3293] opened 2016-11-24 08:10 UTC
Sometimes, osmand reports that I drive over speed limit. Most of the time I see the actual limit in the bottom left corner in the traffic sign as "50" or "90". But sometimes, I see just the dollar sign "$" in the traffic sign. Is it on purpose?

**Comment by hakuchi** [comment] 2016-11-24 17:34
If you pass a toll both the dollar sing will be displayed.
do you have a screenshot or a example?
What version of OsmAnd you use? Latest map?

**Comment by sonora** [comment] 2016-11-25 00:22
($) in deed indicates a toll booth...

**Comment by jirislaby** [comment] 2016-11-25 07:42
Quite interestingly, this happens in Czech republic and Slovakia (from 1.11.2016), where we have no toll booths. What is the exact OSM tag?

**Comment by sonora** [comment] 2016-11-25 08:41
Then we might have some bug and need to investigate. Can you provide some places where this happens?

The tag should be barrier=toll_both, unless I am mistaken.

**Comment by jirislaby** [comment] 2016-11-25 12:55
Ok, I cannot tell the places out of the top of my head. It happens quite often, so I will monitor it and will report on places thereafter.

**Comment by jirislaby** [comment] 2016-11-25 13:12
Ok, despite we do not have toll booths, we have toll bridges as described on the [osm wiki](http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dtoll_booth#Toll_bridges). So for example [a bridge](https://www.openstreetmap.org/node/1528574972) on the map triggers the traffic sign with dollar sign to be displayed.

There is no way to distinguish those two, so there is no way to fix this, I think.

**Comment by jirislaby** [comment] 2016-11-25 13:15
The only thing I miss is documentation. Are the symbols on the map documented somewhere. I only found map legend for the rendered map proper (roads, footways, rails etc.)

**Comment by polarbearing** [comment] 2016-11-25 14:05
If passing the toll bridge means that your payment is collected this moment, then they are correctly tagged as barrier=toll_both, interestingly the type of the station is not tagged yet.

The standard map style is maintained in the [Carto group](/gravitystorm/openstreetmap-carto), it seems that the toll barrier tags are currently [not rendered](/gravitystorm/openstreetmap-carto/issues/958), also toll on road is not rendered.

**Comment by hakuchi** [comment] 2016-11-25 22:13
@jirislaby: 
TTS says: Attention toll both
And the normal voice: Attention

This toll booths are not for car/motorcycle and so they should not be mapped as barrier=toll_booth.
If you add the hgv toll booths to OSM you should use enforcement relation, because you have to buy some device to pay the toll. But this you should discuss with community from Czech republic, Slovakia and/or other.

@ OsmAnd: 
We not should add these toll booths to the map in country's with vignettes, because if there is a toll booth on the motorway these ar not for car/motorcycles.

Is there a way to add a code to the map creator that delete only the toll booth from motorway?

**Comment by polarbearing** [comment] 2016-11-26 01:49
@hakuchi - you are mixing the method of collecting the toll with the affected vehicles. 

If passing the bridge triggers the payment, e.g. because you have an RFID transponder installed, the tagging barrier=toll_booth is correct. You might introduce a qualifier for which vehicle class the toll is valid, and come back here to have it implemented. 

To my knowledge, Germany is/was the only country so far that had that overly complicated system that the HGV driver books his route in advance in a special station, and is monitored via camera bridges and GPS tracking to comply with it. In this case, the bridge is an enforcement device, and the highway carries a toll-tag restricted to these vehicles. 

Finally, if the toll alerts bother somebody, maybe we could get a switch in the alerts settings.

**Comment by hakuchi** [comment] 2016-11-26 20:09
but this toll booths are only for vehicles over 3.5t, and so the warning about this points should not be given for car and motorcycle navigation.

- ___Austria___ have vignettes for vehicle up to 3.5t and for vehicle above 3.5t you have to rent a _Go-Box_ device.
- ___Czech Republic___ have vignettes for vehicle up to 3.5t and for vehicle above 3.5t you have to rent a _PREMID_ device.
- ___Slovakia___ have vignettes for vehicle up to 3.5t and for vehicle above 3.5t you have to rent a _MYTO_ device.
- ___Switzerland___ have vignettes for vehicle up to 3.5t and for vehicle above 3.5t you have to rent a _Tripon_ device.
- ___Germany___ not have toll for vehicles up to 7.5t and buses(for now), but for trucks above 7.5t yo have to rent a _RFID_ device.
- there are other countries with similar system(_GPS_ based or _microwave_ based) for truck toll.

In Italy is 1 motorway with toll bridges they make a photo from your license plate and if you not pay the passed distance in 15 days you will receive a penalty notice. When you enter the motorway, you see large street sings they give you the information about the _new_ toll system. This motorway is for me the only correct example to use `barrier=toll_booth` on a motorway, because a message during navigation will remember you to pay toll.

So for car/motorcycle navigation in Czech Republic the `barrier=toll_booth` should not be displayed, because this toll bridge not have any effect for car/motorcycle. For truck navigation this toll booths can be displayed, but I think this is not needed.

I don't know if enforcement relation for toll is supported in OsmAnd.
If I am a truck driver, I will have a navigation that avoid bridges or tunnels they i can not pass or streets they are closed for trucks. Toll for truck is something special and as truck driver I have to know in what country and what type of street need some special box/payment.

**Comment by vshcherb** [comment] 2016-12-08 22:24
I don't think we could support variety of toll booth especially conditionally based. IMHO we should say attention all the time cause it should not be that annoying and people should read road signs which definitely will be always more instructive. 

The biggest issue for me of course when we don't say "Attention payment", for example, payment is needed for the whole territory like Czech or some cities in Germany. I would love to support that feature cause "payments for non-local people" are always very confusing. If we could have a tag where the area begin and at least a small description, that would be great.

**Comment by jirislaby** [comment] 2016-12-10 07:19
On 12/08/2016, 11:24 PM, vshcherb wrote:
> The biggest issue for me of course when we don't say "Attention
> payment", for example, payment is needed for the whole territory like
> Czech or some cities in Germany. I would love to support that feature
> cause "payments for non-local people" are always very confusing. If we
> could have a tag where the area begin and at least a small description,
> that would be great.

In the Czech republic, all paid roads/highways are tagged as toll=yes.
And it indeed works with e.g. "avoid paid roads" (whatever the option is
called in english version of osmand). So this should be sufficient
condition in here to inform the drivers that they are about to use paid
highway. toll:booth makes actually no sense here.

Furthermore, showing the $ traffic sign is annoying for me given I
suspend the phone on highways for long trips. The phone gets resumed on
every toll bridge (every highway entry I pass by) showing me $ for no
reason.

-- 
js

**Comment by hakuchi** [comment] 2016-12-10 13:58
@jirislaby do you have reported this on [OSM](https://www.openstreetmap.org/note/new#map=19/49.31264/17.39668&layers=N), or discussed in the [Forum](https://forum.openstreetmap.org/viewforum.php?id=47)?
I think Czech OSM Community have to solve(delete) this, for that what I have scribed in [above comment](https://github.com/osmandapp/Osmand/issues/3293#issuecomment-263083064), because **toll bridges** should not be mapped as `toll_booth`.

There are 192 `toll bridges`(3-4 ears old) mapped in Czech Republic and they are only for vehicles over 3,5t. Other country's with vignettes not have any `toll bridge` mapped as `toll_booth`.
Example Czech Republic:
OSM [link](http://www.openstreetmap.org/node/1773372697/history)
Mapillary [link](https://d1cuyjsrcm0gby.cloudfront.net/axuWXMySJs43vt215m0NUQ/thumb-2048.jpg)

Example Austria:
OSM [link](https://www.openstreetmap.org/way/189679096)
Mapillary [link](https://d1cuyjsrcm0gby.cloudfront.net/VLnROZQXqLESGpkBNNBEHQ/thumb-2048.jpg)

**Comment by jirislaby** [comment] 2016-12-15 12:41
@hakuchi 
> because toll bridges should not be mapped as toll_booth.

I don't think you are right here. See:
http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dtoll_booth#Toll_bridges

It says:
>As the tag is defined for both, manual and automatic toll collection, it should also be applied for "toll bridges" that trigger the automatic collection, often with free traffic flow.

**Comment by polarbearing** [comment] 2016-12-15 13:57
@hakuchi 
> Germany ... for trucks above 7.5t yo have to rent a RFID device.

I am not familiar with the brand names of the systems you cite for the other countries, and you do not give a source for your statements. 

I know for sure however that the brand name for the German system is [Toll Collect](https://de.wikipedia.org/wiki/Toll_Collect), and it is ***not*** [RFID](https://en.wikipedia.org/wiki/Radio-frequency_identification) based. Thus in Germany, tagging monitoring bridges as toll_booth would be incorrect.

In many other countries, the [collection](https://en.wikipedia.org/wiki/Electronic_toll_collection) however ***is*** based on transponders, i.e. a form of RFID, thus the collection happens in the moment you pass this bridge, so tagging such bridges as toll_booth would be correct, and you might need to introduce the traffic classes they are intended for.

**Comment by hakuchi** [comment] 2016-12-15 20:32
@jirislaby I know what is scribed in the Wiki, an for me this is wrong.
For me a `toll bridge`(no stop, no lift gate) and a `toll booth`(stop and lift gate) are two complete different things. 
This is only what I think, and the community from a country can decide to not use barrier=toll_booth for toll bridge(like Germany).     
If you discuss this with the community from your country this can be written in the Wiki in the same way as the German community done.

@polarbearing 
German name of device was my error. fixed. 
Names of devices from other country's you can find easy with Google.    

In Germany you can register your route on the Toll Collect website/terminal and the toll bridges check your license plate if you paid the toll. Similar system as the "Videomaut" in Austria.

The RFID, DSRC and microwave based devices sand a signal to the toll bridge and so can be calculated the drived distance(for later bill). In the moment you pass the `toll bridge`, no payment is made(not in Germany and not in other country's). All devices have the advantage that you do not have to pay immediately. But if you pass a `tool_booth` you have to pay in exact this moment.


**And for thus I say:** toll bridges should not be mapped as `toll_booth`, because they are **only** for `over 3,5t/over 7,5t/RFID/DSRC/microwave/etc.`

**Comment by polarbearing** [comment] 2016-12-16 21:58
> In the moment you pass the toll bridge, no payment is made(not in Germany and not in other country's)

@hakuchi - please stop making such statements without proof. Claiming something is not done somewhere is always dangerous as none of us is omniscient. 

Making a payment when passing a particular point is particulary popular for tolls on bridges or tunnels. I have seen them implemented a lot in the US, and another such implementation is the [eToll](https://en.wikipedia.org/wiki/EToll) system in Ireland. Thus they can be used, for distance or spot payment. 

As described [here](https://en.wikipedia.org/wiki/Video_tolling), the Austrian Videomaut is a spot-payment system. It differs significantly from the German TollCollect. 

> toll bridges should not be mapped as toll_booth

Toll bridges are toll bridges and therefore they should be mapped as ```toll_booth```. As said, if they only apply for a particular traffic class, that can be added.

**Comment by polarbearing** [comment] 2016-12-16 22:06
As for the OsmAnd issue, we have a setting to avoid toll roads, and we have a setting which alerts are shown. Maybe we can add a separate option here to switch off toll warnings.

Thus if I am in a country where the toll booths don't apply for me, i can switch them off.

**Comment by hakuchi** [comment] 2016-12-17 22:35
I used some devices to pay the toll and always the complete payment was made at the end of the month(distance + rental costs) from my bank account or card.
I never made a payment in the second I passed the toll bridge. And if I have a account I can check daily costs and distance.

> eToll system in Ireland.

http://www.etoll.ie/getting-a-tag/account-types/
you can register a device and a account where you can pay the toll each month easy from your bank or card. In Ireland the toll bridges are for all vehicles what passing, not how in Germany, Austria, Czech Republic, etc. they are only for hgv.
In Ireland you don't have to pay the toll in exact the second you pass the toll bridge. Toll in Ireland offer a next day 8PM payment, if you don't have a device.

If you pass a toll bridge in Ireland(or A36 in Italy) without device, the toll bridge make a photo from your license plate and if you not pay in the next day(s), you receive a letter with a fine.
You can pay toll in [Ireland](https://www.eflow.ie/i-want-to/pay-a-toll/)/[A36-Italy](https://apl.pedemontana.com/pagamento-rapido) on different service stores, rest areas or online.

If you pass the toll bridge in Czech Republic, Austria, Slovakia, Switzerland, etc. with a car without device/vignette the toll bridge no make nothing. These country's have vignettes, and so the toll bridges are only for hgv(there are other systems to check if you have vignette).

> Videomaut is a spot-payment system. It differs significantly from the German TollCollect.

It differs only that way, that Videomaut is for up to 3,5t(no motorcycle) and TollCollect is for over 7,5t

For Videomaut you have to pay before passing on there homepage(also you can pay a account for 1 year). If you not have paid the toll before arriving toll station, you have to use the normal toll booth.
For Toll Collect(over 7,5t only) you can use the terminal or website to register your tour(or you have DSRC device). If you pass a toll bridge without registered route, wrong route or without DSRC, you receive a letter with a fine.
Videomaut is similar(ähnlich), not the same(gleich) system as Toll Collect, because if you have paid the toll online/terminal the operator check your license plate. So you don't have to stop in Austria on a normal toll booth and in Germany you don't receive a fine.
This info you can find on the TollCollect website and the Asfinag website.

>>toll bridges should not be mapped as toll_booth

>Toll bridges are toll bridges and therefore they should be mapped as toll_booth.

I have already described above why I think, that this are two different things: [here](https://github.com/osmandapp/Osmand/issues/3293#issuecomment-263083064), [here](https://github.com/osmandapp/Osmand/issues/3293#issuecomment-266210423) and [here](https://github.com/osmandapp/Osmand/issues/3293#issuecomment-267436096)
A bridge(Brücke) and a booth(Stand,Kabine,Bude,Hütte) are two different words and so also tool booth and toll bridge are two different things, or are you using a language where bridge and booth describe the same thing.

**Back to topic:**
The solution [above](https://github.com/osmandapp/Osmand/issues/3293#issuecomment-267707428) from polarbearing sounds good for me, but in Czech Republic the toll bridges on motorways are for over 3,5t and so they not should displayed ad any time in car/motorcycle navigation.

**Comment by hakuchi** [comment] 2019-07-15 17:17
9 months ago all the `toll_booth` was transferred to `barrier=toll_gantry`
https://www.openstreetmap.org/changeset/63228503

This issue is no longer reproducible in OsmAnd

**Closed** 2019-08-06 17:01 UTC
Labels: Observed
