### ISSUE TITLE
Offline Routing: destination anouncement

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#2151] opened 2016-01-14 23:56 UTC
https://github.com/osmandapp/Osmand/issues/2056  Fixed, but now there is another problem: 

When there is a destination tag on a turn or on a roundabout without a streetname tag, Osmand says: "Turn left to to (destination)". There are two "to". In other cases the issue is fixed.

**Comment by sonora** [comment] 2016-01-15 08:49
Leonid, I just see Victor has assigned you to this. I think the fix should be adding this line
cut_part_street(voice(['', '', Dest], _), [' ', Dest]).
between the 2 existing cut_part_street lines in all v104 tts files.
Best, Hardy

**Comment by sonora** [comment] 2016-01-15 09:30
Or, more directly: Replace
- turn_street(Street, ['toward.ogg', SName]) :- tts, Street = voice(['', '', D], _), cut_part_street(Street, SName).

by
 - turn_street(voice(['', '', D], ['toward.ogg', ' ', D]) :- tts.

**Comment by sonora** [comment] 2016-01-15 11:54
Some specialties in some languages, I have committed the fix here https://github.com/osmandapp/OsmAnd-resources/commit/3cffc48c78233cbe11c93fef6191386d6f02e426, so we can test now.

**Comment by sonora** [comment] 2016-01-15 12:44
Think this works.

**Closed by sonora** 2016-01-15 12:44 UTC

**Comment by Barrocas** [comment] 2016-01-29 09:33
Yesterday I notice the announcement was reading something like 'Take the first exit in direction to (ref) in direction to (destination)'
So now it's saying 'in direcion to' twice?

**Comment by sonora** [comment] 2016-02-02 20:11
Barrocas, I cannot reproduce this, could you maybe specify some more details like what tts-language you are using, what nightly OsmAnd build, maybe specify an OSM location where this occurs, and if possible also double-check with older OsmAnd builds if tis is a newly introduced issue or has always been present?

Thanks - Hardy

**Comment by sonora** [comment] 2016-02-02 20:28
@Barrocas: I think I have found the issue, I believe you are talking about Portuguese, correct?

Issue is as follows: Both the English "onto", used when you are supposed to turn onto a new street or ref, and the English "towards", used when you are supposed to turn towards a destination, are in the Portuguese language file translated as "em direção a ".

So in cases where the English tts voice would e.g. say "Turn right onto A3 towards Rome", in Portuguese you would hear "... em direção a A3 em direção a Rome".

The solution is likely to find another (better) translation for either the English "onto" or "towards", which would remove the duplication of "em direção a". Maybe "para" can be used for one of the 2 cases?

**Comment by Barrocas** [comment] 2016-02-02 23:18
@Sonora: Thanks for taking the time to help on this :)

Yes, I use the PT-TTS, sorry for not having pointed that out before.

Yes, the 'onto' could be (and I think it used to be) translated as 'para', and the 'towards' is fine as 'em direção a'.

**Comment by sonora** [comment] 2016-02-03 16:10
Ok, I have made the change for both pt and pt-BR (Brazil). Could you please test, but it should be ok now.

Both "onto" and "towards" had actually always been specified as 'em direção a ' in both language files, but the duplication in Portuguese only became apparent after Issue #2056 was solved, which explicitly asked for an extra insertion of "towards" in some prompts where it was linguistically appropriate.

Best, Hardy

**Comment by Barrocas** [comment] 2016-02-05 09:38
Now it's workink fine, thanks! :)

**Comment by Barrocas** [comment] 2016-02-05 09:42
Going off-topic, but could I just ask for another small change on the TTS-PT file?

Replace the 'toll' warning that is now translated as 'pedagio' (maybe it's ok in PT-BR, but it's not adequate in PT-PT), to 'portagem', as this is the common word used here for a toll.

**Comment by sonora** [comment] 2016-02-07 08:43
Done.

**Comment by Barrocas** [comment] 2016-02-07 09:53
Thanks! :)
