### ISSUE TITLE
Part of the river is not displayed

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5209] opened 2018-04-05 11:14 UTC
Location: https://www.openstreetmap.org/query?lat=49.9832&lon=7.8647#map=15/49.9866/7.8702

Screenshot: 
![image](https://user-images.githubusercontent.com/20681525/38363023-a9ce0e76-38db-11e8-9fa4-2e888c7af3ff.png)

**Comment by Heiner-Sch** [comment] 2018-04-05 15:53
The landuse data of the map is missed inside the borders of the "UNESCO World Heritage Upper Middlerhine Valley".

In the OSM data it's a border to a protected area.
name: UNESCO Welterbe Kulturlandschaft Oberes Mittelrheintal
int_name: UNESCO World Heritage Upper Middle Rhine Valley

It's possible that it's a problem with the map data.
Any idea?

**Comment by xmd5a2** [comment] 2018-04-06 07:25
We need to know what maps are in use. I can't reproduce issue using latest Germany_rheinland-pfalz_europe_2.obf or Germany_hessen_europe_2.obf

**Comment by Heiner-Sch** [comment] 2018-04-06 07:40
You see this only if you zoom in. The zoom level in the screen shot is the first were I see this.

The map: Germany_rheinland-pfalz_europe.obf from 1th of March 2018
and Germany_hessen_europe.obf  also from the 1th of March.

I see this on two phones and a tablet, all with the same map and OSMand version.

**Comment by xmd5a2** [comment] 2018-04-06 08:12
Try to remove osmand/rendering/default.render.xml and try again. And/or try "Topo" rendering style.

**Comment by xmd5a2** [comment] 2018-04-06 08:18
![screenshot_2018-04-06-11-12-02](https://user-images.githubusercontent.com/5829014/38410005-2b4bd9fa-398c-11e8-8df1-fba215ed40ac.png)

**Comment by Heiner-Sch** [comment] 2018-04-06 08:26
If I switch to "Topo" it's OK.
But if I switch to "Touring" I see everything inside the border of the restricted area with the same background colour.
But not as an overlayer, like in your screen shot. It's the only colour remaining.

**Comment by Heiner-Sch** [comment] 2018-04-06 08:32
Removing default.render.xml doesn't help.
After restart OSMand the file is rebuilt with the same size, and the same problem.

**Comment by xmd5a2** [comment] 2018-04-06 08:33
What OsmAnd version are you using?

**Comment by Heiner-Sch** [comment] 2018-04-06 08:33
OSMand+ 2.9.3 from the Google PlayStore

**Comment by xmd5a2** [comment] 2018-04-06 09:14
Issue was fixed by this commit https://github.com/osmandapp/OsmAnd-resources/commit/0fa4d03be99cfa34bef7666a9a78f7bca1a59599

**Closed by xmd5a2** 2018-04-06 09:14 UTC
