### ISSUE TITLE
Wrong public transport stop is selected

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#9807] opened 2020-09-14 16:20 UTC
Tapping on public transport selects wrong public transport stop:
Actually this is a bus stop is for 300, 55 but tram stop is selected which is further way on railways. So it looks like the priority is not correct and wrong stop was selected. Location is https://www.openstreetmap.org/node/7032915108

![image](https://user-images.githubusercontent.com/1042025/93111172-8c818280-f6b6-11ea-8ad9-156949b0739b.png)

**Comment by sonora** [comment] 2020-09-14 17:40
Looks like this is not a universal issue, though, I've just checked in some areas I know well and things now work as expected (latest nightly, September map).

Still have to find a single point where I could reproduce. (Could quite possible have been the root cause for #9803, though, when I could still observe it.)

**Comment by sonora** [comment] 2020-09-14 22:12
Finally found an oddity which could be related: OsmAnd 3.8 beta, map-obf Bavaria, published mid September 2020, OSM-data last changed Aug 15, so presumably the latest data should already be in our September map(?):

When in OsmAnd I tap on any of these nodes:
https://www.openstreetmap.org/node/7723596239
https://www.openstreetmap.org/node/7723596240
I always get the data (context menu) displayed for this neighboring node:
https://www.openstreetmap.org/node/7723596241

OsmAnd also displays extra bus stop icons not present in the OSM data.

**Closed** 2020-09-18 10:37 UTC
