### ISSUE TITLE
Not showing detailed map after map updating

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#16119] opened 2023-01-02 13:33 UTC
### Description

After the map update on 1 January, I need to restart OsmAnd for showing the detailed map.

### How to reproduce?

1. Update Czechia Northeast map on 1 January
2. We see the green map area (it means that this map is actual)
3. But when we zoom the map we don't see the full map (only World overview map)

We need to restart OsmAnd for  starting to see the updated map

### Your Environment
OsmAnd Version:  OsmAnd~ 4.4.0#14068 (2023-01-02)
Android/iOS version: 12
Device model: Samsung 10S

**Maps used (online or offline):**   
Czechia Northeast 1 January, 
Tasmania (Australia) 1 January.

**Comment by scaidermern** [comment] 2023-01-02 13:36
Do you use map rendering engine v2 (OpenGL)? Then this is likely a duplicate of #15029.

**Comment by EugeneZmeuk** [comment] 2023-01-02 13:42
OpenGL rendering. But it's the first time for me. I used OpenGL earlier and I didn't have this issue with showing maps after updates.

**Comment by scaidermern** [comment] 2023-01-02 13:47
Strange. I had this every month since August.

**Comment by alex-osm** [comment] 2023-01-05 18:29
https://github.com/osmandapp/OsmAnd-core/commit/1582fc1d118773ce6e10cf303e58633ae44b52e8

**Comment by Zirochkabila** [comment] 2023-01-09 13:09
OsmAnd~ 4.4.0#14082mqta, released: 2023-01-09
Done
OpenGL and Legacy too

**Comment by vshcherb** [comment] 2023-01-16 11:05
https://github.com/osmandapp/OsmAnd/pull/16252/files - doesn't look generic and not in generic place.

**Closed** 2023-01-19 14:32 UTC
Labels: and-bugs
