### ISSUE TITLE
The track being recorded is not displayed when zooming in

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#21597] opened 2024-12-20 15:54 UTC
### Description

The problem is only with the rendering engine v1.
The problem came to F-Droid in version 4.9.6 and also 4.9.7.

Version 4.8.6 works fine.

Press the track record (show on the map). Change the scale with the "+-" buttons when approaching the track disappears from the map, when deleting the track appears on the map.

### Steps to reproduce

Description

### Actual result

Description

### Expected result

The track should be displayed on the map at any scale.

### Your Environment (required)

OsmAnd Version: F-Droid: 4.9.6 & 4.9.7
Android
```

**Comment by yuriiurshuliak** [comment] 2024-12-21 09:09
Duplicate of #21193

**Closed** 2024-12-28 19:12 UTC
Labels: duplicate
