### ISSUE TITLE
French voice prompts pronunciation

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6274] opened 2018-11-12 13:24 UTC
All words beginning with `l are pronounced in two words. " l' itinéraire " is pronounced L + itinéraire, not liténéraire.

**Comment by Rpnpif** [comment] 2018-11-15 09:50
It is the same issue as #6159 report that it should be fixed in github.

**Comment by Rpnpif** [comment] 2018-11-21 11:01
This issue is not fixed in OsmAnd 3.2.5.

Waiting this issue is fixed, you can replace the Android/data/net.osmand.plus/files/voice/fr-tts/fr_tts.js with the attached file here fr_tts.js.txt, renaming it fr_tts.js.

[fr_tts.js.txt](https://github.com/osmandapp/Osmand/files/2603940/fr_tts.js.txt)

**Comment by Rpnpif** [comment] 2018-11-21 11:17
@vshcherb: Please, where I find fr_jjs.js in the sources of Github ?

**Comment by Rpnpif** [comment] 2018-11-22 10:11
Thank you, @sonora. I searched in a wrong repository.
All work fine.
We are waiting for the next release of OsmAnd.

**Comment by sonora** [comment] 2018-11-22 23:40
@vshcherb Let's make sure we include my improved fr tts file in a new release, looks like in 3.2.6 we may have missed it (?)

**Comment by alyonapinchuk** [comment] 2018-12-03 20:12
Voice outputs are overlapping or missing when entering roundabouts. Example: 
Right: "Entrez dans le rond-point et prenez la deuxième sortie" (enter the roundabout and take the second exit) 
What I hear: "Entrez dans le rond-point et prenez --- et prenez la --- ième sortie"

**Comment by Rpnpif** [comment] 2018-12-04 10:20
> What I hear: "Entrez dans le rond-point et prenez --- et prenez la --- ième sortie"

@alyonapinchuk: This bug was yet fixed in code sources by Sonora. See  #6159 report.
In the meantime, you can applied my workaround from https://github.com/osmandapp/Osmand/issues/6274#issuecomment-440623938.

**Comment by breversa** [comment] 2019-03-27 10:55
As of v3.3.6, the french pronunciation is totally borked, nearly unusable, as not only are the aformentionned bugs still there ("l'itinéraire" pronounced as "L itinéraire"), but now, all numbers are pronounced as single digits :

- "Dans 250m" is pronounced as "Dans 2-5-0m"
- "Limite de vitesse : 110" is pronounced as "Limite de vitesse : 1-1-0"
- "Prenez la D224" is pronounced as "Prenez la D-2-2-4"

**Comment by sonora** [comment] 2019-03-28 09:06
Very strange, would not even know what can cause such a behavior other than an issue of the TTS engine you use. There has been no change to the file since my fix some 5 months ago. I have just tested and cannot reproduce any such issue.Think you may have to look in your device's TTS settings and check your setup there?

**Comment by breversa** [comment] 2019-03-28 09:27
Now that you talk about it, I actually updated OsmAnd at the same time I went from LineageOS 14.1 to 15.1. Guess it's time for more testing !

**Comment by Rpnpif** [comment] 2019-03-28 16:34
@breversa, I have not this issue.on Android 8.0.0.

**Comment by sonora** [comment] 2019-03-28 20:05
Let me close this, I think it is not an OsmAnd issue any more. Should there stiil be issues, please open a new thread.

**Closed by sonora** 2019-03-28 20:05 UTC
Labels: Observed
