### ISSUE TITLE
"Display position always im center" does not work anymore

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#3594] opened 2017-03-28 07:03 UTC
The option configure screen / "Display position always im center" does not work anymore.
Independent of the switch it is +always+ in center, that means, I can not switch it to lower position.
Version 2.6.0#20911

Regards Peter

**Comment by sonora** [comment] 2017-03-28 15:58
Peter, it may be a leftover that the setting is still acessible there in the first place. From what I see, having the position marker near the bottom of the screen only really makes sense if your map orientation is set to "Direction of motion", the idea being that you have "more screen in front of you". For all other map orienration settings this would be rather awkward. Hence I think we have automated it in that way (coupled it to the map orientation), to remove complexity and declutter the interface. Can gou agree?

Hence I would conlude here the action is simply to hide this setting in the menu.

**Comment by pebogufi** [comment] 2017-03-28 17:50
Hardy, I would agree, if it would work like you described.
But if I navigate and map orientation is set to "Direction of motion", and the switch is off, that means I expect it near bottom,  it is actually in center.
Just tested only in simulation mode, but last weekend same behaviour.
Peter

**Comment by sonora** [comment] 2017-03-28 18:39
Ok, you are right, we need to investigate. Just played around with it a bit and it sometimes seems to work ok, sometimes not. Found no good relation yet to the navigation or just map viewing case, or other parameters.

Looks like we agree, though, that the setting should be hidden in the UI, and the non-center position be automaticallu used exactly and exclusivly when the map is in "according to direction of mottion" mode.

**Comment by pebogufi** [comment] 2017-03-28 18:56
Yes, agree.
Peter

**Comment by crimean** [comment] 2017-03-29 16:52
Peter, please check if you have this setting OFF in profile you are using during navigation. This setting is profile (browse, car, bicycle, ped) depended.

**Comment by pebogufi** [comment] 2017-03-29 17:22
Yes I confirm, that it is just this profile. I tested it carefully before reporting, and now again.
Peter

**Comment by sonora** [comment] 2017-03-29 18:16
Alexey, Fix should be to
- Hide the setting in the UI entirely
- Check all places in our code where we change the map orientation and strictly (and exclusively) couple the off-center position to the "according to direction of motion" parameter.

**Comment by vshcherb** [comment] 2017-03-29 20:18
@sonora we need to understand the issue first. I might be dragged by mistake to 2.6 thinking it is a regression if it is not a regression, we need to think carefully about solution (so it should be assigned to me)

**Comment by vshcherb** [comment] 2017-03-29 20:30
I also tested it and I couldn't understand the issue:
1) Show position in center (true) is only related to the "compass" direction to moving. 
2) If you change profile, the setting should change according to profile stored.

**Comment by sonora** [comment] 2017-03-29 20:46
Issue is: Sometimes the position change works ok when changing between profiles with and without map orientation according to motion, and sometimes it does not.I had both working and not working occurrences for manual profile changes or changes induced by a start oc a navigation/Follow. Looks like a definite regression, will try to find what may have caused it.

**Comment by sonora** [comment] 2017-03-29 21:31
I think here is the confusion: The setting "always in center" is only considered at all if map orientation by motion is selected. It is disregarded (though visible and changeable) in all other map orientations. That's why I think we should either hide it entirely, or at least hide it when the map orientation for the profile in quedtion is not "by motion". Probably easier and sufficient to hide entirely and simply marry rigidly with whether or not "orientation by motion") is selected. 

Yesterday I was certain there is some additional refresh issue hidden somewhere to the effect that the map position does sometimes not change correctly after a profile change, but cannot reproduce just now.)

**Comment by vshcherb** [comment] 2017-03-29 21:43
Hiding option a bad UI strategy, it could confuse people even more (I need to send once investigation about UX pattern). Integrating it with "direction" will lead to 4 states (direction & position in center , direction & position on bottom). 
If it is a regression it would be great to know how to reproduce it, otherwise it is not fixable right now and not sure how important it is .

In my opinion I was never a big supporter of that setting and I would like to delete it though we need to think carefully about it if we want to introduce 4 states.

**Comment by sonora** [comment] 2017-03-29 22:08
You misunderstand: I want to reduce to the following 3 states:
- No rotation (north is up): This automatically means center-position.
- Rotation to compass: This also automatically means center-position.
- Rotation according to direction of motion: This automatically switches to bottom position.

Since in this model there is NO user choice of center- or bottom-position at all, I suggest we delete the center/bottom setting from the UI.

**Comment by pebogufi** [comment] 2017-03-30 05:22
I fully agree to the argumentation of sonora.
Peter

**Comment by vshcherb** [comment] 2017-03-30 09:56
> Rotation according to direction of motion: This automatically switches to bottom position.

I don't understand where is the state 
> Rotation according to direction of motion in the center position.

This is not my request but I know it is quite popular and it's been since OsmAnd 0.2 version

**Comment by sonora** [comment] 2017-03-30 14:15
Ok, then I'd say let us split this: Whether the mode 4 "Rotation according to direction of motion with center-position" has a reasonable use case or is obsolete can be a simplification request and discussion in a seperate issue.

Let us focus on reproducing Peter's original issue here that he sometimes (or always) cannot get to mode 3 "Rotation according to direction of motion with bottom-position". I had yesterday backed up my data folder then re-installed OsmAnd to test something else and have to say that I have not been able to reproduce it since. Am currently traveling and only have one other device with me, that one has never shown the issue. So while before I could not systematically reproduce, for now I cannot seem to reproduce at all ... 

Peter, on the device where you see it, you would have to work out step-by-step instructions how to reproduce or it cannot be debugged, together with a report on what the settings are and maybe a screenshot.

**Comment by pebogufi** [comment] 2017-03-30 16:02
Ok, I will make more test. Yesterday in two tests it was ok, so I will need some time to find out which situation causes the problem.

**Closed** 2017-09-20 19:34 UTC

**Comment by tubemeister** [comment] 2021-09-13 20:01
Any progress on this? Osmand still puts me in the center of the screen in 3D mode, no matter the position of that "always in center" toggle, which is still there in the interface.

Osmand 4.0.6 on an iphone

**Comment by vshcherb** [comment] 2021-09-14 16:12
Issue was fixed 3 years ago and probably is not related to ios version. https://github.com/osmandapp/OsmAnd-iOS/issues
