### ISSUE TITLE
OSM live via OAuth

### ISSUE THREAD

**Issue by Matthias84** [osmandapp/Osmand#4487] opened 2017-09-26 19:03 UTC
When you signup to OSM live, you currently need to enter the OSM account and credentials. This is bad, as it leaks the information at OSMand servers (and e.g. stolen by a third party) and doesn't allow to revoke / restrict access.

[OSM supports OAuth](https://wiki.openstreetmap.org/wiki/OAuth), which is already used by a lot of tools, that need access to your OSM profile. It would be great, if this tech could be used for signup to OSM live.

**Comment by vshcherb** [comment] 2017-09-28 07:26
I guess it is a duplicate but let's keep it. We will be glad to have it.
*Note: signup for accepting donation (not for contribution).

**Comment by HolgerJeromin** [comment] 2017-09-29 07:59
This is a duplicate of the issue https://github.com/osmandapp/osmandapp.github.io/issues/37 for the website.

**Comment by vshcherb** [comment] 2017-10-01 09:32
Moved to  osmandapp/osmandapp.github.io#37

**Closed by vshcherb** 2017-10-01 09:32 UTC
Labels: Nice to Have
