### ISSUE TITLE
Public transport routing doesn't work in OpenGL rendering

### ISSUE THREAD

**Issue by HamousOnWheels** [osmandapp/OsmAnd#20784] opened 2024-09-08 16:31 UTC
### Description

If rendering engine v2 is enabled, public transport routing consistently doesn't work. Switching back to v1 and restarting the app makes it work again. Only realized recently since i didn't need it often lately, but i believe it's been broken every time i've tried it this year. Maybe my phone or android version is too old to support the opengl engine?

### Steps to reproduce

- Enable map rendering engine version 2 in settings (enabled by default since some time afaik)
- try public transport navigation to any point regardless of distance

### Actual result

"Unfortunately, Osmand could not find a route suitable for your settings."

Changing any routing settings such as "number of changes" does nothing. The only thing that restores routing is changing the rendering engine back to version 1 and force quitting the app.

### Expected result

Routing works as it always has

### Your Environment (required)

```
OsmAnd Version: osmand~ 4.8.6
Android version: 11
Device model: motorola moto g8 power
Crash-Logs: no crashes
```

**Comment by yuriiurshuliak** [comment] 2024-09-09 13:46
The bug was not reproduced. To test, select OpenGL rendering and a public transport profile, then try to build point-to-point navigation.

The navigation will be built correctly, showing options with walking times and public transport routes, including route information such as time, distance, transfers, and public routes.

For more detailed information, you can refer to our documentation: [Public Transport Navigation](https://osmand.net/docs/user/navigation/routing/public-transport-navigation/)

OsmAnd~ 4.9.0#3148m, released: 2024-09-09


https://github.com/user-attachments/assets/853d7abf-0ec9-49fe-9133-d8d1e68ad21c

**Comment by DmitryAlexei** [comment] 2024-09-12 13:41
@HamousOnWheels 
Please try to increase the number of intersections in the Public transport navigation settings
Moreover, make sure that transport routes in your location are mapped with Public Transport Version 2 (PTv2) scheme

If this doesn't work, please provide the start and end points of your routes. We will try to reproduce your issue

**Comment by HamousOnWheels** [comment] 2024-09-16 01:14
Increasing the number of intersections doesn't help. Here are my navigation settings: 

![image](https://github.com/user-attachments/assets/992d289a-3607-4342-8884-eb616dc3acab)

I don't know how to check the public transport version. The area is Belgrade, Serbia. A route for example could be [here](https://osmand.net/map/?pin=44.82549,20.40901#15/44.82549/20.40901) to [here](https://osmand.net/map/?pin=44.74171,20.45320#17/44.74171/20.45320) (apologies if this isn't the proper way to share routes)

Other things i've tried:
- tested with a few other European cities (Prague, Berlin, Riga)
- disabling all plugins. The plugins i have enabled are online maps and OSM editing, if it matters.
- wiping and reinstalling 4.8.6
- installing 4.9.0 beta

I need to repeat it's crucial to force stop the app between changing rendering modes, since immediately after change navigation will still work, until the point the os itself kills the app.

**Comment by HamousOnWheels** [comment] 2024-09-16 01:21
Update: after some more testing, i got it to work under following steps:
1. start the app in opengl mode, under public transport profile by default. Try to calculate a route. Navigation doesn't work.
2. switch to a driving or cycling profile. Route is calculated normally.
3. switch back to public transport. Route is calculated as expected.
4. after these steps, every subseqent public transport route calculation works normally.
5. after the app is restarted, public transport is back to not working until the profile shuffle is done again.

Confusing to say the least! This is still version 4.8.6 to be clear.

**Comment by contrapunctus-1** [comment] 2024-09-16 04:43
A number of India users have also faced this issue.  I haven't tried the rendering engine workaround, but I've often (successfully) used the switching-navigation-profile workaround.

To add another example, try navigating by bus from Vijaylakshmi Apartment
geo:28.62896,77.30901?z=21
to Mandi House 
geo:28.62550,77.23391?z=20

**Comment by TobiPeterG** [comment] 2024-09-26 23:05
I thought I had this issue, but increasing the number of maximum changes fixed it for me.
I don't need to switch profiles etc., I live in Germany.

Why does the setting for maximum changes even exist?

**Comment by vshcherb** [comment] 2024-10-28 15:24
As it's very slow route calculation to be honest, so in many cases 2 is maximum for reasonable waiting time

**Comment by HamousOnWheels** [comment] 2024-11-22 17:52
Why was this closed? This is still an issue as of 4.9.6. As I said before, increasing the number of maximum changes doesn't help.

**Comment by vshcherb** [comment] 2024-11-27 21:22
It was closed as we didn't reproduce the issue, we will try once again

**Comment by yuriiurshuliak** [comment] 2024-12-03 17:52
The bug has been reproduced under the following conditions:  
- When attempting to calculate routes directly using the **Public Transport profile**, regardless of the **number of changes** or the **country of use** (e.g., Berlin), the error message *"Unfortunately, OsmAnd could not find a route suitable for your settings"* appears, with **Public transport routes calculated: 0** displayed.  
- Interestingly, if a route is first calculated using the **Car profile** and then recalculated with the **Public Transport profile**, it works as expected.  

This confirms the issue is reproducible and related to direct public transport routing. 

OsmAnd~ 5.0.0#3870m, released: 2024-12-03

https://github.com/user-attachments/assets/42f041f4-06d1-4cc9-999f-d5fb088afefb

**Comment by HamousOnWheels** [comment] 2024-12-03 20:28
Exactly as reported. Thanks for looking into this.

**Comment by DmitryAlexei** [comment] 2024-12-05 09:25
OsmAnd~ 5.0.0#3884m, released: 2024-12-05
I downloaded the Berlin map, then updated the Nightly to the latest version > switched to public transport profile > start and end points are set on 11th zoom level through Map context menu (pick up a point on the map > in context menu choose actions > Directions from) result is in the video
https://github.com/user-attachments/assets/c836e5f7-37d9-43d6-8e66-3bd5473da257
[logcat (2).log](https://github.com/user-attachments/files/18020585/logcat.2.log)


After the first attempt, I switched to the driving profile and the route between points was successfully calculated. Right after that, public transport route can also be calculated.
https://github.com/user-attachments/assets/d2e50e2b-4535-4a68-9c20-055ef3db967a


[logcat (3).log](https://github.com/user-attachments/files/18020637/logcat.3.log)

**Comment by RZR-UA** [comment] 2024-12-09 13:25
@DmitryAlexei, To Do:

- [ ] test fix using OsmAnd nightly
- [ ] back Issue to fixing (backport to r4.9)

**Comment by Zirochkabila** [comment] 2024-12-09 17:05
# Testing 1

`OsmAnd~ 5.0.0#3911m, Released: 2024-12-09` - **Done**
`4.9.0.14` - **Canʼt testing (OsmAnd crashes)**
`iOS release version` - **Still present**


https://github.com/user-attachments/assets/7cca1a75-ee7c-440a-81e8-86bfefb70265

**Closed** 2024-12-12 08:10 UTC
Labels: navigation

**Comment by Zirochkabila** [comment] 2024-12-12 18:24
# Testing 2

`4.9.0.18` - Fixing
