### ISSUE TITLE
Koshi town streets flooded

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#6987] opened 2019-05-28 08:19 UTC
Eastern coast of Koshi town is flooded in OsmAnd:
Lat 9.95780 Lon 76.25795
![image](https://user-images.githubusercontent.com/50198677/58462378-6f7c1580-813a-11e9-8ee1-f5c3127fa51b.png)

OpenStreetMap displays the coast accurately:
https://www.openstreetmap.org/node/1998361311#map=17/9.96040/76.25980
9.9625, 76.25828
Bazar Road, Kumbaramukku Junction, Mattanchery, Kochi, Ernakulam, 
Kerala, 628002, India

**Comment by davidzx** [comment] 2019-06-04 12:42
Happens in Stockholm, sweden as well, whole islands disappear when zooming out while the roads stay visible.

**Comment by xmd5a2** [comment] 2019-06-05 12:25
Duplicate of https://github.com/osmandapp/Osmand/issues/6565

**Closed** 2019-06-08 09:22 UTC
