### ISSUE TITLE
OsmAnd nigtly in app instalation not working

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/OsmAnd#19374] opened 2024-03-23 10:55 UTC
### Description

The in app download and installation of the new OsmAnd build is no longer working.

Download works fine but installation is not starting.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/9936160/9e874745-d594-49d4-834b-2986989dcf4d"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Deinstall old OsmAnd nightly.
Download OsmAnd nightly from website and after some day download new build in app. 

### Actual result

Download works fine and make complete download, but installation is not starting.
Also the option to allow OsmAnd to install unknown apk is missing in the settings.

### Expected result

Automatic start of installation of the downloaded apk after finished download without open extern file explorer.

### Your Environment (required)

Tested with:     
OsmAnd Nightly 4.7.0#1875m 
fron 03.20.24
Android 10

**Comment by DmitryAlexei** [comment] 2024-03-23 22:27
@hakuchi is it duplicate of https://github.com/osmandapp/OsmAnd/issues/19262 ?

**Comment by yuriiurshuliak** [comment] 2024-03-25 14:20
Perhaps this update mechanism is not functioning. To continue receiving the latest updates, you will need to manually remove the existing nightly version and install the new one. This action will restore the updating process. https://osmand.net/docs/versions/nightly_versions#nightly-builds

**Closed** 2024-03-26 12:33 UTC

**Comment by hakuchi** [comment] 2024-03-28 08:14
@vshcherb 
The in app update mechanism still not working.
OsmAnd nightly have no option to allow installing apps.

OsmAnd missing option:
![Osmand](https://github.com/osmandapp/OsmAnd/assets/9936160/01065514-8c34-4b97-8aa0-ca28f3999da2)

Explorer wiht option and permission:
![Explorer](https://github.com/osmandapp/OsmAnd/assets/9936160/3a4ccc93-dfc0-4aa7-b9da-0ed37dee4813)

**Comment by DmitryAlexei** [comment] 2024-03-28 21:39
Can you grant permission to install unknown apps to OsmAnd nightly in Android settings?

**Comment by hakuchi** [comment] 2024-03-29 07:40
No. There is no option in the android settings.

Also after a clean new installation no pop up is showing after download.     
I can only install update with file explorer by accessing android/data/net.odmand.dev/files 

This is not the "update error" from the 19262.    
I can update OsmAnd but not in OsmAnd as some time ago
