### ISSUE TITLE
wrong direction arrow highlighted (turn ambiguity) - improved tagging needed

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#8997] opened 2020-05-18 23:02 UTC
Is this a separate issue or a dup of #8807?

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=59.95513%2C30.40694%3B59.95954%2C30.40735

![image](https://user-images.githubusercontent.com/14617699/82267351-bf1fa680-9974-11ea-99b5-a59ebfc77aef.png)

**Comment by blackboxlogic** [comment] 2020-05-23 12:57
This may be working as designed to mean "For now, stay straight. After, turn right."
Note the different distances under the different arrows.
It may also be a data issue. I see there are two dedicated right turn lanes, and OsmAnd might be assuming that both of those will lead you down that first right turn, which isn't your route.

**Comment by vshcherb** [comment] 2020-05-24 11:27
I'm afraid this issue can't be fixed cause there is turn ambiguity. 2 turn-lanes to right are assigned to https://www.openstreetmap.org/way/45370997#map=17/59.95742/30.40774. 

Probably the corrected map could have the most right lane to have 2 right turns assigned.

Or probably we need to wait for more clarification in tagging scheme. Simply saying we need to have extra taggging scheme:
turn:lanes=C|C|C|TR|TR...
turn:lanes:way=C|C|C|C|C;R

**Comment by 532910** [comment] 2020-05-25 20:15
> 2 turn-lanes to right are assigned to [way/45370997](https://www.openstreetmap.org/way/45370997)

2 turn-lanes to right are assigned to [way/207505876](https://www.openstreetmap.org/way/207505876) and 45370997 goes after 207505876, aren't they?

**Comment by vshcherb** [comment] 2020-06-04 16:06
Yes it is strange, it should be no lanes at all up to 142 m

**Comment by vshcherb** [comment] 2020-06-04 16:18
![image](https://user-images.githubusercontent.com/1042025/83782184-c0004a00-a68f-11ea-9f61-25c0a6a9a480.png)
Looks like fixed already

**Closed by vshcherb** 2020-06-04 16:18 UTC
Labels: Observed
