### ISSUE TITLE
Umlaut transliteration

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6019] opened 2018-09-10 12:04 UTC
OsmAnd~ 3.1.6, UI language German, map language German, and the setting "transliterate if not available in German" active. Then, e.g., "Krückenweg" in Dortmund is transliterated to "Kruckenweg," even though umlauts are part of German. 

Transliteration disabled
![image](https://user-images.githubusercontent.com/40493090/45296452-bbcee900-b50a-11e8-9223-54f54aafa5a4.png)
Transliteration enabled
![image](https://user-images.githubusercontent.com/40493090/45296467-c7baab00-b50a-11e8-9189-aad7cd29da54.png)

**Comment by Discostu36** [comment] 2020-01-13 13:24
Duplicate of #5954

**Closed** 2020-01-13 14:58 UTC
Labels: Nice to Have
