### ISSUE TITLE
Verify Search concept

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4829] opened 2017-12-05 07:47 UTC
When looking at other apps which perform search operations in huge indexes (i.e. scientific libraries or dictionaries) I find that they are still **instantaneous** in suggesting search results even while you type, while the performance of our offline text search seems **much** inferior with us looking the a spinner and an empty list of search hits for a long time.

I suggest we take a second look at our search mechanism and figure out why this is, and if it can be improved. I am currently not sure where we lose all that time, is it actually finding the hits in the index (that should be rather quick if it is sorted correctly?), or is it sorting them by distance (maybe that should be done later, after already suggesting/displaying them?), or is it a some sub-optimum search algorithm trying to unnecessarily scan the index by successively increasing the search radius, rather than just doing a much quicker total list lookup?

**Comment by vshcherb** [comment] 2017-12-05 08:23
Well, here I don't see much to improve at all. First of all it is not that slow on devices I have, second it hugely depends on the number of maps you have installed. Basically if you have 1 map, 1 search by 1 criteria could be 100-200 ms, if you have 10 maps it is 10*100 ms.

The only thing to look at & double check when the search algorithm starts. So to me it is a duplicate of #4812.

**Closed by vshcherb** 2017-12-05 08:23 UTC

**Comment by sonora** [comment] 2017-12-05 22:05
@vshcherb Just for reference, this is my performance on most devices: With about 40 obf files present, searching for something random which does not exist (like dhvddrghd) takes about 1 minute and 40 seconds before finally displaying that there is no search hit. That is quite a long time of staring at an empty screen...? Shouldn't any reasonable algorithn be able to confirm much quicker that something is not contained in the index?

**Comment by sonora** [comment] 2017-12-06 00:28
PS: I am wondering what our performance drop is here between our debug and the release builds ...

Looks like my credentials for the osm-releases folder have expired years ago, can you re-send, so I can do some testing?

**Comment by scaidermern** [comment] 2017-12-06 11:28
> With about 40 obf files present, searching for something random which does not exist (like dhvddrghd) takes about 1 minute and 40 seconds before finally displaying that there is no search hit.

This is pretty slow. I have a low- to mid-end device (Moto G4) and two enabled maps. Searching for something nonexisting takes 3-4 seconds. With four enabled maps (one of them is pretty large) it takes around 7 seconds.

**Comment by JonnyTech** [comment] 2017-12-06 12:27
Could this be a build issue? My phone searches very slowly - GApps free and uses the F-droid build. A friends similar phone with the Play Store build seems to be very much faster.

**Comment by sonora** [comment] 2017-12-07 03:48
I have now tested a non-debuggable build, same conditions as above. The "random" search test now improved to about 1 minute 10 sec, searching for "existing" values is also faster. So there is some impact and we must not test stuff like that woth debuggable dev builds.

**But it seems the major impact here is the number of obfs present**, searching with only 1 (0.9 GB) map file active decreases the "random search - nothing found" time to about 7 seconds!

**Comment by vshcherb** [comment] 2018-02-03 20:57
Merged into #4812
