### ISSUE TITLE
Flooded area Nicaragua

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6818] opened 2019-04-12 10:50 UTC
https://www.openstreetmap.org/search?query=11.5656967%2C-85.5786972#map=11/11.5026/-85.5941
![image](https://user-images.githubusercontent.com/40493090/56032086-e0ea3b00-5d29-11e9-8f72-dd24d27be125.png)

**Comment by xmd5a2** [comment] 2019-06-14 08:44
Duplicate of https://github.com/osmandapp/Osmand/issues/6587

**Closed by xmd5a2** 2019-06-14 08:44 UTC
