### ISSUE TITLE
Gaps in GPX track during recording

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#1903] opened 2015-11-12 13:14 UTC
While recording of GPX track is active, there are gaps in the track. However, if you view the track after the recording, it looks fine. The phone was turned on and off during recording.

Galaxy S4, Android 5.01, OsmAnd+ 2.1.1
![pict_1_during_track_recording](https://cloud.githubusercontent.com/assets/12711814/11119142/1de5c404-8950-11e5-8e53-b69536d66e18.jpg)
![pict_2_after_storage_and_indication](https://cloud.githubusercontent.com/assets/12711814/11119141/1de26eb2-8950-11e5-920b-7e84e4bdf0c0.jpg)

**Comment by therob84** [comment] 2016-02-07 21:30
I can confirm gaps in the recorded GPX track (3 times in 1h recording).
I often switched the phone on and off during the track recording. Sometimes I noticed, that OSMAnd did not seem to have a GPS-fix at the moment I switched the phone on (Satellites 0/26) and only re-connected within 2-3 sconds to continue the recording.
But at this moment I was not sure, if it was just a problem of displaying the satellite count it due to screen off-->lockscreen-->unlock-->OSMAnd precodure or if the connection really was lost.

I think for me the problem was not, that the recording made any fault. I think a disconnected GPS-reception was the cause. 
During all the time there was the notification and the symbol about the "OSMAnd background service is running" at the notification bar and both the "GPS wake-up intervall" and the "GPX recording interval" was set to "continous" and the terrain should have allowed for sure a good GPS coverage!

I used v2.5.2 with Android 5.1 at the Fairphone 2.
Any hints what the reason of this could be?

Btw, maybe in connection: Without recording, if I click at "GPS 12/26" [satellites] entry in the right upper corner and select any "GPS wake-up intervall", e.g. "5s" and "OK" and click it again, this value is not saved and it displays again "continous". 
What does this setting mean and why the value is not stored?

**Comment by sonora** [comment] 2016-02-08 11:44
The GPS wakeup interval is used by the OsmAnd background service. The service is by default activated if
- a navigation is running
- a track is being recorded.

The service facilitates GPS running (if the interval is "continuous"), or being activated at fixed intervals (if set to a time interval), so that necessary actions like navigation voice prompts or recording a track point can be performed.

For track recording, it should behave as follows: when you start a track or segment recording, you specify a track point interval.  If you record your track with <30 sec nterval, the GPS wakeup interval is be default set to continuous, because it makes no sense to interrupt GPS for so short periods of time. For longer track recording intervals >=30sec, the wakeup interval is set accordingly, this saves battery power, as GPS is allowed to go to sleep in between point recordings..

I think what you are observing when you say "the wakeup interval is not saved" is exactly this behavior, the interval is chosen as needed when you _begin_ to record a new track segment. You would have to change it _after_ the track recording is already running, if you really want this. (It does not really make a lot of sense in most situations, probably better to re-adjust your track recording interval instead.)

Regarding the original issue reported here on the top: Are you saying, it is a display issue only while recording, but the track itself is fine, right? It looks to me the issue is in a built-up area (town), and there are rather few points, about 1 every 200m. Can you check the track if some of them are "missing"? Chances are we may have a live display issue for missing points (not sure, actually), but it only becomes visible for such long recording intervals ..

**Comment by xmd5a2** [comment] 2016-02-14 20:02
I also noticed these gaps in currently recording track if OsmAnd loses GPS fix. I believe that this behavior is better than if the track segments would be connected by a straight line.

**Closed by xmd5a2** 2016-02-14 20:02 UTC
