### ISSUE TITLE
address search now uses unfamiliar English names and doesn't use countries of regions

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#1323] opened 2015-06-06 10:25 UTC
In the current version (2.0.4), goig to the address search and tapping "Region" brings up the list of all supported regions, as expected.  There are two problems with this, first of all where a country is split up into regions the country name is not prepended to the region, as if I remember correctly was the case in older versions.  For example, I have the full set of France mainland map files installed;  formerly starting to type 'f' 'r' would bring up all of her regions, such as "France alsace", "France aquitaine" etc. with just typically those two keystrokes followed by a scroll and tap needed to find the wanted one.

Now typing the same 'f' 'r' only searches the bare region names, so it only shows "Free County", "Ile-de-France" and "Free and Hanseatic City of Bremen".  It isn't possible, therefore, to pick a country and then browse its regions.

The second issue is that this search always seems to use the English names of the regions;  it took me a long time to work out that the "Free County" above was actually Franche-Comté.  Nobody, not even an English visitor travelling in France, would know it by the English name, and it would not be shown on any signpost or any other documentation - therefore it is pointless using the translated name.

There used to be a setting "Use English names on maps" which seems to have disappeared; to my recollection I have never had this option turned on.  Setting the "Map language" (I have tried "Local names", "English" and "French") does not affect the search.

Suggest that the searcher should revert to showing the country plus region when appropriate (in some distinguishing format, e.g. "France - Alsace" if necessary), and either always use local names or honour the map language setting.

**Comment by aceman444** [comment] 2015-06-08 19:47
Try to set the Display Language to French (not system default) and restart OsmAnd (also from Recent tasks in Android).

**Comment by vshcherb** [comment] 2015-06-08 22:05
Let's keep it open and thinkg if we want Display Language be System default by default. And still it is a bug in the sense that by default we should use "Local names" though it is hard to define what is name. Also same issue applicable to Download List. For now the good solution is not clear

**Comment by martenjj** [comment] 2015-06-09 09:28
Tried with Osmand application language set to French (which correctly changes the app language) and tablet restarted to make sure.  Typing 'f' 'r' now brings up only "Free County" and "Ile-de-France"; strangely the English "... Bremen" shown previously now is not there, it is named "Brême" (never heard of that before) in the full list.

With the tablet system language set to French (previously it was English UK) and Osmand language still set to French, the results are the same as above ("Free County" and "Ile-de-France").

With system language set to French and Osmand language set to System, the results are the same as in the first comment ("Free County", "Ile-de-France" and "Free and Hanseatic City of Bremen") although the GUI is correctly in French.

**Comment by martenjj** [comment] 2015-06-09 09:44
The anomaly of this only happening for certain places can be explained by the OSM data not being consistent.  Franche-Comté has (irrelevant languages not shown):

name	Franche-Comté
name:en	Free County
(no name:fr)

Alsace (which is shown and searched correctly in Osmand) has:

name	Alsace
name:fr	Alsace
(no name:en)

**Comment by aceman444** [comment] 2015-06-09 20:17
Yes, the ideal state would be if OsmAnd lang is set to "system default" and everything should work.
Victor, the bug here is this:
- Assume system language is set to X (not English)
1. Set OsmAnd language to language X
- OsmAnd UI is in language X and list of countries to download is in language X (fine).
2. Set OsmAnd language to "system default"
- OsmAnd UI is in language X. But the list of countries to download is in English (=>bug).

This should be easy to fix to use the same language at both places.

**Comment by martenjj** [comment] 2015-06-09 20:58
aceman444, that is indeed one bug.  But even if it were fixed, there would still be the problem where, if the system language "X" were set to (e.g.) English, then the country/region list would be displayed in English which is still not what is wanted.

I think the original "Use English names in maps" setting - still referenced at http://osmand.net/help/HowToArticles.html but not present in the current version - needs to be reinstated.  It could be made non-language specific by being presented in the inverted sense as "Use local names", with the default being on.  So having this option set on would use only the OSM "name" tags for all display and searching.  Having it set off would use the "name:XX" tag if it were present, otherwise "name", where "XX" is the OsmAnd configured GUI language or the system language if the app is set to use the system default.

**Comment by aceman444** [comment] 2015-06-09 21:08
There is still the setting for map language using the name:xx tags. But it moved to the map settings (the 3 layer icon), it is no longer in OsmAnd settings.

**Comment by vshcherb** [comment] 2015-06-10 14:19
The issue is fixed in such a way. 
- The region name is searchable by 2 keys, displayed name and file name.
- The region name is consistently displayed as translation to Settings - Localization - Application Language. So if your Android System Language is french you will see it in french. That fixes the problem you can read the name.
- It is consistent with file information in Download Maps.
- That's not possible to display file names any more, because they are not geographically correct!

In the end this name should be aligned with Configure Map - Map Language and combined through all searches and map view (map should display exactly what you search and of course the search should help with different spelling of the same map object), this is the goal but it will be achieved once search becomes combined.

**Closed by vshcherb** 2015-06-10 14:19 UTC
Labels: Investigating
