### ISSUE TITLE
Track split interval lost when editing track points

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#7150] opened 2019-07-04 07:18 UTC
The split interval setting is lost when adding or removing points from the track. The track color **doesn't** get lost.

**Comment by vshcherb** [comment] 2019-07-05 16:27
Can't reproduce, I still see that option after adding a point, probably track needs to reopened or refreshed.

Please attach screenshots

**Comment by scaidermern** [comment] 2019-07-07 05:50
You can see the split marker vanishing after deleting a track point: https://imgur.com/a/pMCKRR5

**Comment by vshcherb** [comment] 2019-09-06 20:57
Merged into #7501

**Closed by vshcherb** 2019-09-06 20:57 UTC
Labels: Observed
