### ISSUE TITLE
Graphic glitch: orthogonal dent and duplicate road appear beyond some zoom level

### ISSUE THREAD

**Issue by vmicho** [osmandapp/OsmAnd#16651] opened 2023-03-09 19:59 UTC
### Description
1. I see a small horizontal dent (1st screenshot, on the right side, on the main road, just between N20 and Löven...)
2. After zooming in, at some zoom level and beyond, a duplicate road appears, completely unrelated.

Example coords: 46.9373 N, 7.1385 E
Map used: CH, 2023-03 + CH hillshades, deleted live updates

The dents (1.) - I've seen that on multiple locations randomly since the opengl renderer update. E.g. I've just zoomed to 47.1492 N, 7.6959 E and see same thing, but vertical this time. Another random zoom to 47.1291 N, 10.0527 E (map AT 2023-02, screenshot 3, after updating to 2023-03 I see same thing)
Does not depend on phone orientation (see it in vertical or horizontal layout).
The duplicate road (2.) - I see that 1st time.

### Actual result
![Screenshot_20230309-201904_OsmAnd+](https://user-images.githubusercontent.com/66125746/224134061-19f4dc12-859c-42f3-87e0-e5746f0b5c67.png)

![Screenshot_20230309-201922_OsmAnd+](https://user-images.githubusercontent.com/66125746/224134114-1686761e-fa71-42f0-9d28-60af10a9d2f3.png)

![Screenshot_20230309-204311_OsmAnd+](https://user-images.githubusercontent.com/66125746/224137188-dff35aac-8ba9-4d16-a3f7-719debb697db.png)

### Your Environment
OsmAnd Version: 4.3.12
Android/iOS version: 11
Device model: Mi8

**Comment by Zirochkabila** [comment] 2023-03-13 11:28
OsmAnd~ 4.4.0#14234mqta, Released: 2023-03-13
Regarding the absence of a part of the road, this can be reproduced both with and without live updates (V2 rendering) - similar to what @scaidermern  wrote about
As for the display of the second road in the second screenshot, it cannot be reproduced - @vmicho please list all Swiss maps you use (and which maps you use live updates on)

46.9373 N, 7.1385 E
[Map](https://drive.google.com/file/d/1vGHdEX9tMcRR7lfA41Atlx7tWYJCqfM4/view?usp=sharing)

https://user-images.githubusercontent.com/104760013/224688538-39888b76-8ade-43fc-9f63-303a49567a96.mp4


------

47.1492 N, 7.6959 E
[Map](https://drive.google.com/file/d/1Auz3pDeVsvv8gQZ0Q_Ob8ZN1Va2weKbW/view?usp=sharing)

https://user-images.githubusercontent.com/104760013/224688969-8f8cc2c2-49c5-4f3a-9843-3a324190a0ac.mp4

**Comment by vshcherb** [comment] 2023-03-13 16:41
Looks like it's fully duplicate of https://github.com/osmandapp/OsmAnd/issues/16135

**Closed by vshcherb** 2023-03-13 16:41 UTC

**Comment by vmicho** [comment] 2023-03-14 21:48
I have additionally World map + World map mini
Maybe one of these is causing problems
I notice the road orientation corresponds to the world map.
This is screenshot using only world map (CH map uninstalled):
![Screenshot_20230313-231747_OsmAnd+ world map only](https://user-images.githubusercontent.com/66125746/225147744-9f1f9fde-45a9-4dfe-902f-df42f05fc1f9.png)
