### ISSUE TITLE
Loaded maps do not appear on the map

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15045] opened 2022-08-09 12:22 UTC
### Description
Loaded maps are not displayed on the map. Although they are displayed in the Download maps.
The user tried both the internal storage of the phone as well as his external SD card and it won't make a difference
[logcat map.log.zip](https://github.com/osmandapp/OsmAnd/files/9290247/logcat.map.log.zip)

### Steps to reproduce
Download map of some country 

### Actual result
Loaded maps do not appear
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/183644922-2501027f-d218-4d22-a59a-ba9263c0cfe8.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/183644927-4deeab7b-6bf4-4f94-bf81-32a9621d0390.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
Loaded maps are displayed on the map

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 11
Device model: Redmi note 9 pro

**Comment by sonora** [comment] 2022-08-09 16:49
Have you tried zooming in further? The "far out" zoom levels are contained in the "World Overview map", but not included in any country or regional map. load both maps to see details at all zoom levels.

**Comment by vshcherb** [comment] 2022-08-09 16:56
I don't think we will reproduce it probably reinstall should help

**Comment by sonora** [comment] 2022-08-09 17:18
Looks to me like the map is simply zoomed out too far. 200km scale on screenshot 2 without World basemap loaded may only display you some forest area from the mini-basemap...

Screenshot 1 also implies it is zoomed out very far, while displaying selected Water/Camping POIs from the full country map ok.

**Comment by paulolaslo** [comment] 2022-08-10 08:46
> Have you tried zooming in further? The "far out" zoom levels are contained in the "World Overview map", but not included in any country or regional map. load both maps to see details at all zoom levels.

Zooming doesn't help, the map remains invisible

**Comment by paulolaslo** [comment] 2022-08-10 08:47
> I don't think we will reproduce it probably reinstall should help

I tried uninstalling and reinstalling many times but the same problem remains

**Comment by paulolaslo** [comment] 2022-08-10 08:50
![Screenshot_2022-08-10-10-49-14-550_net osmand](https://user-images.githubusercontent.com/110971402/183858392-504d4b7f-e7d3-42a8-afdd-7b743b1aff00.jpg)

Here's a screenshot of the map zoomed in. The interest points do display. I can create a

**Comment by paulolaslo** [comment] 2022-08-10 08:54
I just activated OpenGL before restarting the app and still nothing has changed

**Comment by pebogufi** [comment] 2022-08-10 13:35
I also had a problem with disappearimg maps. 
4.3.0 #34465
During a bicycle trip I made a stop to look for something on the map. Suddenly map was all white.
Closing and clear cache several times did not help.
Reinstalling older version helped.

**Comment by Antheii** [comment] 2022-08-10 15:42
Same issue, with me it started after installing on a new phone, using the standard Google migrate tool (previous phone Moto G7, Android 10, new phone Pixel 6 Pro, Android 12).

Uninstalled OsmAnd+, and reinstalled same version (Beta), still same issue. 
Uninstalled again, removed from Beta program, and installed the standard version. Issue solved, with the maps shown correctly again.
On request of the support team, removed the app again, joined the Beta program, and installed the latest Beta. This time I only forgot to check the "Keep xxx MB of app data" - so I lost all my POI's :-( , but I guess  I got  a clean install now, which might or might not explain why this time all maps returned!


![Screenshot_20220806-203058](https://user-images.githubusercontent.com/63048026/183943275-8897d74d-18d2-41c1-a530-4499c7b6b3c0.png)
![Screenshot_20220806-201952](https://user-images.githubusercontent.com/63048026/183944817-42629a00-f855-4171-9149-20fedc9f3899.png)

Device : raven
Brand : google
Model : Pixel 6 Pro
Product : raven
Build : SP2A.220305.013.A3
Version : 12
App Version : OsmAnd+
Apk Version : 4.2.7 4207

**Comment by vshcherb** [comment] 2022-08-10 16:37
I experienced similar issue with OpenGL enabled but then only reboot of the phone helped. Restart app was not helping somehow. Anyway it looks something specific to device is going on cause this behavior is consistent on Pixel phones where only OpenGL works

**Comment by paulolaslo** [comment] 2022-08-11 14:23
Problem fixed after I did the very last update of the MIUI (12.5.8). Still unclear why the maps suddenly stopped showing

**Comment by pebogufi** [comment] 2022-08-11 15:34
Same problem again with OsmAnd~ 4.3.0#34467m, 2022-08-09
Just looking something at the map, then i got a plain white map display. 
Restart did not help. 
But reinstall the same version solved it.

**Comment by tkoeller-max** [comment] 2022-08-11 20:31
Also having the same problem with Osmand 4.2.7 installed from Google Play Store. This is a fresh install to a pristine Google Pixel 6a device.

**Comment by tkoeller-max** [comment] 2022-08-12 11:19
Also having the same problem with Osmand 4.2.7 installed from Google Play Store. This is a fresh install to a pristine Google Pixel 6a device.

**Comment by vshcherb** [comment] 2022-08-12 15:35
Merged to https://github.com/osmandapp/OsmAnd/issues/14947

**Comment by franco999** [comment] 2022-08-17 02:18
The same thing happens to me with versions later than OsmAnd~ 4.3.0#13697mqta, (2022-08-08).

I have tried even the latest nightly and it still happens. 

On first startup, the maps load fine but when I close and reopen the application, they don't load anymore. I have to close the application to be able to see the maps and their data again.

**Comment by panicfarm** [comment] 2022-08-17 13:02
Installed from Play Store to new Pixel 6 Pro. Map is not rendered by default. In OsmAnd -> Plugins -> OsmAnd development -> Settings enabled Use OpenGL rendering. Restarted the app and the map started rendering. Should be enabled by default prob

**Comment by tkoeller-max** [comment] 2022-08-18 20:49
> Installed from Play Store to new Pixel 6 Pro. Map is not rendered by default. In OsmAnd -> Plugins -> OsmAnd development -> Settings enabled Use OpenGL rendering. Restarted the app and the map started rendering. Should be enabled by default prob

Works for me, too. However, map rendering is worse with this mode enabled. Coast lines are sometimes approximated coarsely by polygons.

**Comment by Zirochkabila** [comment] 2022-08-19 14:15
The user has a similar problem on Samsung S22, OsmAnd~ 4.3.0#13718mqta, released: 2022-08-17 - can be corrected by restarting the phone or disabling Open GL restarting the app, and activating Open GL again.

**Comment by vshcherb** [comment] 2022-08-19 15:12
Release 4.2.7 - MiUI 12, Android 11 (Ticket 40331)

**Comment by vshcherb** [comment] 2022-08-19 15:42
![image](https://user-images.githubusercontent.com/1042025/185656311-e8f9b49e-25dc-4a9b-9e63-f033f59447c9.png)
Pixel 6 - Android 13

**Comment by amirhomayoun** [comment] 2022-08-20 21:54
Had the same problem on new Google Pixel 6a. Android version 12, OsmAnd+ 4.2.7, released: 2022-07-13.

Turning on the OpenGL in the plugins fixed the issue on the phone. Android auto however, stays blank. I notice that overlay maps do show on the AA, but the map itself does not. So, I have the Google Traffic maps as an overlay, and AA does show it, but switching the map source from "offline vector maps" to "OsmAnd (online tiles)", or "Microsoft Earth", or any other source, won't work. The AA screen stays blank (if you don't have the overlay). You can use navigation, and it is functioning, you just cannot see anything on the map unless if you turn on the overlay. The open street plugin would work too, if you turn it on, you can see the red crosses on the blank black screen on the AA screen. Somehow map doesn't load on the Pixel 6a, the same version of OsmAnd, on the same car worked before (on Android 11, and a pixel 4). Turning OpenGL off won't make a difference.

**Comment by pebogufi** [comment] 2022-08-21 07:20
@amirhomayoun 
OT. Can you please send the link for Google Traffic maps as an overlay?
Thanks.

**Comment by amirhomayoun** [comment] 2022-08-21 14:13
Sure. If you want it without labels:

`https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i{0}!2i{1}!3i{2}!4i256!2m3!1e0!2sm!3i0!2m6!1e2!2straffic!4m2!1st!2s0!5i1!3m17!2sen-BE!3sUS!5e18!12m4!1e68!2m2!1sset!2sRoadmap!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2sp.v%3Aoff!4e0!5m1!5f1)`

And if you want it with labels:

`http://mts0.googleapis.com/vt/lyrs=traffic&x={1}&y={2}&z={0}&style=15`

The first one is what you see in my photo. If you use the other one, you will see the green/red traffic as well as some basic street/business names. I'd rather use the offline vector maps as map and just put the traffic overlay on top of that, so I use the first one.

**Comment by vshcherb** [comment] 2022-08-23 08:53
Android Auto is offtopic and it's a known limitation and it doesn't work now

**Comment by johann-petrak** [comment] 2022-08-24 13:18
I seem to have the same problem here: moved to a new phone Redmi Note 11 Pro+ 5G running MIUI 13.0.3 and Android 12 SP1A. I was using Google Sync to set up my apps from the old phone.

The symptoms were: 
* initially, offline map was not rendered, but location markers or things like cycle routes were rendered
* when moving/zooming the screen, the things that did get rendered ended up not to get properly repainted and produced a huge mess on screen
* online maps instead of the offline vector map did get rendered properly
* after some experimentation it turns out that map style "Osmand" was selected
* when changing the map style to "Topo", suddenly the offline map does get rendered properly
* support suggested to try enabling OpenGL which did not change anything
![Screenshot_2022-08-05-15-43-13-270_net osmand plus](https://user-images.githubusercontent.com/619106/186428559-24538819-13b5-454d-9494-2738a47f2be3.jpg)

**Comment by PvdBerg1998** [comment] 2022-08-27 11:35
Same problem after changing to LineageOS 18.1 on my Oneplus 8, rendering using OpenGL fixed it.

**Closed** 2022-11-15 16:32 UTC
Labels: Observed

**Comment by tkoeller-max** [comment] 2022-11-16 16:10
@Zirochkabila Problem still exists in 4.2.7

**Comment by alewando** [comment] 2022-11-17 21:01
#14947 says this is fixed in version 4.3.0 (three months ago), but that version is still not available in the app store

**Comment by Zirochkabila** [comment] 2022-11-23 08:44
@tkoeller-max Try to do as described in the article [No maps rendering for Google Pixel device](https://osmand.net/docs/user/troubleshooting/maps-data#no-maps-rendering-for-google-pixel-device)
