### ISSUE TITLE
Feature request: adjusting speed for time calculation

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5982] opened 2018-09-04 15:21 UTC
It would be a useful feature to adjust speed defaults for timing calculations, especially for bicycles. Speeds vary from person to person, and calculating it using the average speed is not trustworthy for many people.

**Comment by breversa** [comment] 2018-09-07 07:51
Agreed, but how would your proposed speed adjustment work ?

**Comment by vshcherb** [comment] 2018-09-09 15:30
I think it is a duplicate issue but couldn't find another one requested for Boat navigation I think.

**Comment by bege10** [comment] 2019-04-16 17:50
There must be an assumed speed already. But that is too high. This average speed should be adjustable. On a slightly upward route the assumed speed by OsmAnd was almost 20 km/h. Well, I am a slow biker due to disability and I ride on a plane route 12-15 km/h.

**Comment by bege10** [comment] 2019-04-16 17:53
duplicate of https://github.com/osmandapp/Osmand/issues/5622?

**Closed** 2019-04-17 10:12 UTC
Labels: Nice to Have

**Comment by hman2** [comment] 2020-07-30 14:48
Since this issue was closed, does this mean the default speed was changed? Why not make this user adjustable? Since Osmand does caluculate with different speeds for different road quality already, why not introduce a setting that simply gets multiplied with whatever Osmans calculates? So users with three speed bikes might make a setting of "0.9" for instance, while drivers of racing bikes might be able to set "1.2" ?

**Comment by vshcherb** [comment] 2020-07-30 16:51
Speeds are adjustable with routing.xml but you need to edit in the text editor, in future we plan allow few changes there but it is not clear when/how will be done
