### ISSUE TITLE
Route calculation +50% slow 

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#16941] opened 2023-04-10 14:03 UTC
Here''s a before and after:
![Screenshot_20230410-150628_OsmAnd~](https://user-images.githubusercontent.com/845735/230907551-4dbba962-9dfc-474d-9a56-301a820e16d9.jpg)
![Screenshot_20230410-150831_OsmAnd~](https://user-images.githubusercontent.com/845735/230907554-4282829b-6a22-4765-8c56-2d512524967d.jpg)

_Originally posted by @sonora in https://github.com/osmandapp/OsmAnd/issues/16173#issuecomment-1501801006_

**Comment by Zirochkabila** [comment] 2023-04-10 14:36
@sonora Please provide route coordinates and OsmAnd versions for comparison

**Comment by sonora** [comment] 2023-04-10 14:48
Can I ask the following, it would help me assist investigating:

The purpose of method` int[] filterDirectionTags(...) `is to return all `pointTypes` which apply independent of direction, plus the ones applying for the direction of travel, but minus the ones for the opposite direction, right? So why do we call `continue` in the second loop exactly for the ones where the `t/h/direction` tag _matches_ the travel direction?

What am I overlooking?

@Zirochkabila Those were random coordinates, just pick any. 50% was on the high side though. If you produce better statistics by averaging over enough repeated calculations of the same route, my experience is about a 10-20% penalty of the 2023-04-07 over the 2023-04-02 build.

**Comment by sonora** [comment] 2023-04-11 23:41
I've run a lot more tests with a lot more routes now, and the results are inconclusive  I believe we should park this, chances are it really is circumstantial, i.e. depending on actual tagging now processed.

This is substantiated by the fact that I find no reason why the new code should perform significantly slower, other than my question elsewhere on the change in logic.

**Comment by Dima-1** [comment] 2023-04-21 15:02
I tested 10 different routes in Bavaria from 204 to 478 km, some of them became slower(by 10%-20%), some became faster (by 10%-20%), the rest did not change at all

**Comment by sonora** [comment] 2023-04-21 17:58
@Dima-1 Dmitry, yes, I agree, I think it is by design because we now catch more tags where they are applicable (that's why it varies so much), so I think we should close the issue. I had re-ckecked the code and also find no obvious flaw.

**Closed** 2023-04-22 15:11 UTC
Labels: routing

**Comment by velle** [comment] 2023-05-22 02:07
@vshcherb I assume you took a screenshot from the app. But what did you do to make your app show those stats after calculating a route? On my device I haven't yet seen any info like this. When I ask it to calculate a route it simply switches to showing the route on the map and a voice telling me the distance of the route.
