### ISSUE TITLE
different date format in routes & tracks

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#15519] opened 2022-10-20 08:33 UTC
# 🚀 feature request

A recorded track has the date format "yyyy-mm-dd hh-mm Day" (perfect).
A planned route has the date format "Day dd Mon yyyy" (not possible to sort by date).

Can you make it all the same pattern please (like the tracks)?  
Thanks!

**Comment by scaidermern** [comment] 2022-10-20 10:41
Duplicate of #10838

**Closed** 2022-10-20 12:28 UTC
