### ISSUE TITLE
OSMand plugin Openplacereviews is broken

### ISSUE THREAD

**Issue by iiitomo** [osmandapp/OsmAnd#17966] opened 2023-08-19 00:16 UTC
It is not possible any more to do reviews via the OSMand plugin Openplacereviews .
Its website  (https://openplacereviews.org) indicates the project has been discontinued in June 2023, and the contributed data will be soon stop being available.
So OSMand should use an alternative for place reviews, for example Mangrove as suggested by the above page.

**Comment by scaidermern** [comment] 2023-08-19 05:47
Duplicate of #11111.
Also, this plugin is no longer part of OsmAnd. You should update your version.

**Comment by vshcherb** [comment] 2023-08-19 08:47
In

**Closed by vshcherb** 2023-08-19 08:47 UTC
