### ISSUE TITLE
Android: Fietsknooppunten (aka cycle nodes aka rcn_ref) no longer displayed in cycle routes

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#7535] opened 2019-09-09 18:10 UTC
Motorola 5Gplus, Android 8.1, OsmAnd 3.4.6, Netherlands full map of 1 August (but also July version).

In cycle mode it is possible to show the cycle routes on the map.
In the Netherlands we have the "fietsknooppunten" (cycle nodes). They are also partially in Belgium (Vlaanderen) and in the border areas in Germany where Germany and the Netherlands are lying adjacent.
These "knooppunten" are no longer visible.
So: showing cycle routes is no problem and works fine.
The attached image shows the cycle routes AND cycle nodes as they are displayed in Openstreetmap.org with the cycle layer. Location is around "de Lutte" in Overijssel in the Netherlands.

![cyclenodes](https://user-images.githubusercontent.com/4520361/64554714-3f006600-d33c-11e9-9b3f-7a4c8d346f85.jpg)

As far as I can check they still exist in the default_render.xml (lines 3091-3101). https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L3091

Also the rendering_types in obf_creation still contain the nodes (as far as I can check).

**Comment by scaidermern** [comment] 2019-09-09 19:12
Duplicate of #6963?

**Comment by hvdwolf** [comment] 2019-09-10 16:13
Yes. It is a duplicate of #6963 

I searched for cycle node and fietsknooppunt, not cycle route node. :(

**Closed** 2019-09-26 13:33 UTC
