### ISSUE TITLE
Voice sporadically muted permanently in high load / low memory situations (reboot required)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1351] opened 2015-06-15 15:24 UTC
Using OsmAndF~2.1.0#7464D and OsmAndF~2.1.0#7731D I noticed the following bug.

Parameters to reproduce
- Make sure map "Germany_baden-wuerttemberg_europe.obf" is installed
- Start point: 47.8297081, 8.9572001
- Destination: 47.683390040222264, 9.75730018119812
- Start navigation in car mode
- Against automated directions take the exit at: 47.68908333333333, 9.293333333333333

Result:
After the recalculation of the route OsmAnd does not speak anymore. (I have not muted OsmAnd and all volumes are at maximum.)

@vshcherb: Hope you can use these information to reproduce the bug by simulation. I use german sampled voice (no tts). You will receive a partial track log by E-Mail.

**Comment by vshcherb** [comment] 2015-06-15 15:32
Why the sound would be related to specific coordinates, I think it should be generic for all routes and I think it would make sense to test voice before/after with Development -> Settings -> Test Voice Prompts

**Comment by Norbert80** [comment] 2015-06-15 15:33
This happens always in this situation. Maybe a memory problem with rerouting.

**Comment by Norbert80** [comment] 2015-06-15 15:34
It is strange for me, too.

**Comment by Norbert80** [comment] 2015-06-15 15:41
@vshcherb my intention is to give you steps to reproduce the bug. Hope you can simulate,  reproduce and find out by debugging what exactly triggers the bug.
I think I have read in the group of other users having problems with voice becoming silent sporadically.

**Comment by Norbert80** [comment] 2015-06-15 15:51
@vshcherb: Clicking at the top-left direction icon also fails to generate a voice output while the bug is "active".

**Comment by Norbert80** [comment] 2015-06-15 17:11
@vshcherb additional information:

While driving these route part with OsmAndF~2.1.0#7464D I had the feeling that there might be still some problems introduced by fast re-calculation.

I remember from former discussion that you have increased the part to be rerouted from 20 km to ~35 km (?). While my built-in BMW navigation system has "accepted" the exit after a few kilometers, I remember that  OsmAndF~2.1.0#7464D did massive re-calculations where I had the feeling that it suggested "stupid slopes". Since the distance between the exit and the destination is about 43 to 45 km I ask myself if OsmAnd always wanted to force a route back to a point on the initial route.

But I would need more information in "fast re-routing" and time to finally investigate this.

**Comment by sonora** [comment] 2015-06-15 19:00
The recalculation issue has been resolved with OsmAnd builds after about
June 10, so it should not be an issue any more with more recent builds

**Comment by Norbert80** [comment] 2015-06-15 20:40
@sonora thanks for this information. This coincides with my observations since I didn't experience the "stupid slopes" with OsmAndF~2.1.0#7731D anymore. So I can confirm that "fast recalculation" should be already fixed.

But let's concentrate on the initial topic (voice not speaking) of this bug report. Although if not related to fast recalculation it may be still related to recalculation in general.

@vshcherb are you setting up a simulation? Do you need additional information?

**Comment by sonora** [comment] 2015-06-15 22:43
Norbert, would you have another device you can test this with? I am
wondering if it is maybe memory-related ... Or can you shorten your route
by picking a closer destination on the same route and see if this changes
anything?

**Comment by DrVanScott** [comment] 2015-06-18 20:24
i am still quite unfamiliar with OsmAnd. As it seems that i suffer from the same problem: Can i somehow simulate the routing reported by Norbert80?

**Comment by vshcherb** [comment] 2015-06-18 21:21
With Development plugin on, there is a special card at bottom to simulate voice and also there is a special activity to Test Voice

**Comment by Norbert80** [comment] 2015-06-18 21:29
@vshcherb for my understanding he wants to trigger the bug in a reproducible way before testing the voice. I also would like to know how to use track logs as fake GPS positions in order to simulate from track logs.

**Comment by Norbert80** [comment] 2015-06-19 21:20
@vshcherb today I tried this route with release 2.1.1.
The voice has permanently muted directly after the first recalculation (triggered by taking the exit). I have force closed OsmAnd and restarted it. Voice worked again.

I decided to drive the remaining part according to BMW's "economic" routing mode which has - as expected - forced further recalculations in OsmAnd which was set to "fastest" mode. Then OsmAnd has muted again permanently...

So this is reproducible always for me and it happens also on other route parts when forcing recalculations.

You should consider to raise priority and start investigation.

**Comment by vshcherb** [comment] 2015-06-20 22:41
I investigated it already, it is very critical issue, but very personal too. I did many test drives since it was open, of course I had recalculation and I didn't experience any error. 
On my previous device (very old) when I use TTS engine I was constantly getting noise while the routing, this was related to memory limitation. I didn't have another choice and switched to recorded voice.
It might help in your case as well.

If the issue is logical (it might be) and it is related to a specific route, it will be good if someone else could reproduce it on another device, then it requires special attention.

To not give false hopes, I will close that issue because there is no action planned, but keep following it in order to know the reasons deeper. If something obvious is discovered, the issue will be fixed immediately.

**Comment by Norbert80** [comment] 2015-06-21 08:18
@vshcherb thanks for these clear and illuminating words. In fact it is difficult to deal with such kind of problems. Maybe I will ask in the group for other users experience the same problem. This might lead to additional information...

> On my previous device (very old) when I use TTS engine I was constantly getting noise while the
> routing, this was related to memory limitation. I didn't have another choice and switched to
> recorded voice.
> It might help in your case as well.

I experience these problems with recorder voice.

**Comment by Norbert80** [comment] 2015-06-21 08:23
https://groups.google.com/forum/#!topic/osmand/Mt0P6um4etk

**Comment by Norbert80** [comment] 2015-06-21 13:04
@vshcherb we already have feedback in the bug hunting thread (link above). It also affects other users and newer devices like Nexus-5 running 4.4.4. So it is against you assumptions not specific to only one specific route.

What can we do now?

**Comment by Norbert80** [comment] 2015-06-21 16:29
@vshcherb please reopen this bug.

**Comment by DrVanScott** [comment] 2015-06-21 20:29
> What can we do now?

The next time, the problem appears, it would be interesting if the speech test of the dev plugin would still work. This might help the developers.

Is there a log file written by osmand?

**Comment by Norbert80** [comment] 2015-06-21 20:38
What is the technical difference between "speech test of the dev plugin" and  clicking on the top-left button that indicates the next action? This button also normally repeats the voice. But this button is silent after the bug is triggered.

**Comment by vshcherb** [comment] 2015-06-21 20:47
@Norbert80 Did you test at least any other voice package as I recommended?

**Comment by Norbert80** [comment] 2015-06-21 20:50
These reports where all with german recorded voice. I did not drive that route with another voice.

**Comment by vshcherb** [comment] 2015-06-21 21:06
1) Would you mind  to drive with german TTS. 2) Did you try to cancel route and start it over again (so is it just recalculation issue)?

**Comment by Norbert80** [comment] 2015-06-21 21:14
@vshcherb

1. I can try it on Thursday on my way home

2. I'm very sure that just restart navigation does not fix voice. I need to force close and restart OsmAnd.

**Comment by Norbert80** [comment] 2015-06-26 07:12
@vshcherb
I have driven the route yesterday evening with german tts voice. The voice has NOT muted!

OsmAnd+ 2.1.1 second release

(Additional difference compared to my last reproduction of the bug is that since yesterday I have map details enabled. But I can't imagine that this is related with the bug.)

Now we know that the bug only occurs with recorded voice. But we don't known if it only happens with the german recorded voice.

Due to my holiday I cannot try english recorded voice in the next two weeks.

@vshcherb could you setup a simulation with my track log and german recorded voice in order to try to reproduce the bug?

**Comment by damianszczepanik** [comment] 2015-07-06 20:28
@vshcherb @Norbert80 

Can you reopen this issue?

I have reproduced this with the newest version and can provide logcat which I've already collected.

**Comment by vshcherb** [comment] 2015-07-07 12:54
We will try to reproduce it.

**Comment by Norbert80** [comment] 2016-04-09 21:48
@vshcherb please re-open this issue. I just experienced this bug again with OsmAnd+ 2.3.3 on a different route also after several forced re-calculations.

**Comment by Norbert80** [comment] 2016-04-09 21:50
@damianszczepanik Did you send the logcat to @vshcherb?

**Comment by damianszczepanik** [comment] 2016-04-09 22:10
I don't have logs any more but I can reproduce the issue if you like. At least I can try

**Comment by Norbert80** [comment] 2016-04-09 22:37
I think it only makes sense if @vshcherb commits to investigate on this bug. It is not clear for me why he has closed it without any comment.

**Comment by vshcherb** [comment] 2016-04-13 22:08
Please attach a logcat here though we couldn't fix low memory issues using Log files

**Comment by damianszczepanik** [comment] 2016-04-21 20:14
I've ```grep osmand``` and attached results.

[1.txt](https://github.com/osmandapp/Osmand/files/230655/1.txt)
[2.txt](https://github.com/osmandapp/Osmand/files/230654/2.txt)

**Comment by Norbert80** [comment] 2016-06-23 20:59
I experienced this issue today again on another route. Is there any progress on the meantime?

**Comment by sonora** [comment] 2016-06-27 20:48
I have been doing a lot of TTS voice testing lately, and it seems that I do sporadically see the same or a similar issue, that the TTS voice remains silent for repeated navigations, even though it initially worked. 

It seems to happen primarily when there was a previous voice navigation going on, and the device went to sleep after navigation was finished or I had stopped it. Then (very rarely), upon waking up the device again and starting a new navigation may sometime result in the TTS voice remaining silent.

When this happens, it seems like nothing inside OsmAnd can get he voice to sound again, neither tapping OsmAnd's mute/unmute button, nor changing the TTS voice selected (both under route settings), nor going to the development plugins' voice test activity and trying different TTS voices there.

But what does reliably work is to go to Android's TTS engine setting and there tap "Listen to an example". This will produce the test sound, and then returning to OsmAnd will immediately produce the TTs voice in OsmAnd fully functional again.

This is e.g. on Android 4.4 devices, I do not think it is memory-related.

**Comment by Barrocas** [comment] 2016-06-27 22:33
I also have seen the TTS voice going silent after doing some
navigation, and stopping.
Then I go do something else, and when setting up a new route,
sometimes TTS is mute, as you described.
I usually just 'Force Close' Osmand, and when restarted it works again.

On Android 4.4.2

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment] 2016-06-28 20:53
I am not sure this is related, but I occasionally observe an NPE in connection with TTS voice prompts, see log attached. (Issue is with Pebble code, but I do not use Pebble.)
[exception.log.txt](https://github.com/osmandapp/Osmand/files/338028/exception.log.txt)

**Comment by sonora** [comment] 2016-07-01 19:03
Looks like mTtsContext in line 136 can be null there? Easy to mask there, but maybe needs another fix, could this issue be related?

**Comment by sonora** [comment] 2016-07-06 06:20
From my testing: When the "mute" situation occurs:
- TTS player is not null
- re-initializing the TTSCommandPlayer (e.g. with another language) does not help
- issue occurs only with TTS, not with MediaCommandPlayer
- even when starting off with (working) MediaCommandPlayer, then switching to TTS may still produce the issue
- Issue reproducibly "fixes" itself after about 1-2 minutes

**Comment by sonora** [comment] 2016-07-07 17:45
I think I knocked this one off. This commit https://github.com/osmandapp/Osmand/commit/4e05a1f52efacf54df816b7c501e39aaa02d5872 fixes all issues I had listed above, and also (hopefully) what was described way above as "Voice sporadically muted permanently ... (reboot required)".

My fix masks any play requests (and hence requestAudioFocus) until the TTS player reports successful initialization. This prevents the audio system from going into state "audio focus retrieved and prompts sent, but player not ready", and corrects all "side-effects" documented above.

What remains of this issue is that there are situations, described in **Observation 1** above, where the TTS player initialization takes much longer than usual. The sound will now (in a controlled fashion) remain silent, but automatically start as soon as the player is ready.

The period in question  seems to be during app initialization, round about when the map gets rendered for the first time), possibly because of some other parallel process with high load or priority. It remains to be seen what we can change in our AppInitializer to mitigate this.

**Comment by sonora** [comment] 2016-07-14 21:48
I think I have to re.open this, I have tsted voice navigation extensively in the last 2 weeks and finally made it to observe this.
- It seems to happen ONLY with recorded voices, so I think the issue may be in MediaCommandPlayerImpl
- This does of course not happen at specific coordinates, but it seems it only happens when you deviate from the route and the route is automatically re-calculated, when the player is stopped to prevent "old" commands from playing. (But sometimes, not always!)
- Issue is independent of what voice output is used.
- I observe this also on high-end devices, do not think this is memory related
- Stopping, then re-starting the navigation does **not** remediate the issue
- But going into "Test voice prompts" of the dev plugin **does** remediate the issue (I had recently added code there to always re-init any language, even the one was already initialized, which formerly failed)

Route-recalculation performs an initVoiceCommandPlayer, I think there may be an issue with how we handle that for recorded voices, while it works flawlessly with TTS voices (never seen this issue there.)

**Closed** 2016-07-15 08:21 UTC
Labels: Observed

**Comment by sonora** [comment] 2016-07-19 21:13
For the record:
- Looks like nullifying the Media player after a stop() as in  https://github.com/osmandapp/Osmand/commit/a2d4609a23b7507c73457eca34b8ce184c414172 reliably fixes the issue described here
- Nullifying the media player in this fashion causes many navigation prompts, especially after a "route recalculated prompt", to sound twice in a row.. Unclear why, it almost looks like 2 different instances of VoiceRouter may be triggered or even run overlapping each other.
- Chances are that that nullifying the TTS player after a stop() may fix #2810, but I cannot reproduce and hence cannot verify

In any case it seems overkill to nullify the player instead of just a stop(), so the root cause of this issue remains unknown,
