### ISSUE TITLE
Track overlay on / off switch in wrong state

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#18104] opened 2023-09-06 12:22 UTC
## Description

Immediately after selecting a track the switch is in the wrong state

### How to reproduce

Starting with no tracks visible. Go to

Menu -> Configure Map -> Tracks

Tick the box on a track, choose 'Apply'.

### Actual result

Returned to the menu with the On / Off switch set to 'Off'. Exiting the menu reveals that the track is visible. Re-entering the menu, the switch is correctly showing 'On'.

### Expected result

Switch matches actual state

**Environment**
OsmAnd Version: + 4.6.0
Android/iOS version: 11
Device model: XCover 4s

**Comment by yuriiurshuliak** [comment] 2023-09-07 15:21
The bug was reproduced under certain conditions. It happened when you had at least 10 tracks to reproduce. If you followed these steps: Menu -> Configure Map -> Tracks, with the slider in the disabled position, selected multiple tracks, checked the box, and clicked 'Apply,' the slider in Configure Map -> Tracks remained inactive. Interestingly, when you viewed the map, the tracks were visible on it. Even more intriguing, if you subsequently rechecked the Configure Map -> Tracks slider, it automatically became active.

OsmAnd~ 4.6.0#731m, released: 2023-09-07


https://github.com/osmandapp/OsmAnd/assets/127092082/279da523-ec74-4085-80a8-a725eb36c55e

**Comment by mikehgentry** [comment] 2023-09-07 23:37
I only need to select one track (from the 'Recently visible' list) to reproduce it here, though I have 41 tracks in the 'All' list.

If I get the chance I'll try to figure out what's specific about it.

**Comment by dmpr0** [comment] 2023-10-03 15:49
### Description

Tracks item is show as Disabled in Configure Map

### Steps to reproduce

* Open **Menu** – **Configure Map** – **Tracks**
* Switch to any folder, tap on track or **Select all**
* Tap **Apply**

### Actual result

<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/c25d9677-f599-4117-b367-cfac7758b6cb
"  width="300" height="auto"/> </td>
  </tr>
</table>   


### Expected result

* Track item will be shown as On

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by nazar-kutz** [comment] 2023-10-15 11:38
This issue is caused by an incorrect way of visually updating of the switch element and will be fixed with https://github.com/osmandapp/OsmAnd/pull/18334

**Comment by dmpr0** [comment] 2023-10-17 06:39
# Review 

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/cefe317e-6510-4c58-9b33-cbf3326d7f10"  width="300" height="auto"/> </td>
    <td><video src=""  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  




- [ ]  Visible lag to calculate 8 tracks visibility.

**Closed** 2023-10-17 11:13 UTC
Labels: and-bugs
