### ISSUE TITLE
Unable to hide track (4.1 ok) 

### ISSUE THREAD

**Issue by bytes101** [osmandapp/OsmAnd#14599] opened 2022-06-21 11:14 UTC
### Description

Unable to hide track in new stable version 
### How to reproduce?
Press the eye icon doesn't hide track/route as before see [scrrenshot]

### Your Environment
OsmAnd Version:
Android/iOS version: New Release 4.2 (android-4-2-released)
Device model:

Test Device- Doggee Pro S89, Cubot mini , Xcover 4 and 5
![Screenshot_2022 06 21_11 52 33 941](https://user-images.githubusercontent.com/95884760/174786499-0349b3dd-472f-4fb0-84a4-2e1b9924f186.png)
![Screenshot_2022 06 21_11 52 38 978](https://user-images.githubusercontent.com/95884760/174786508-bbd6151d-cae8-44a8-b57f-dcfc9b96767f.png)
![Screenshot_20220621-120052](https://user-images.githubusercontent.com/95884760/174786526-b0d7443a-f1cb-4b5e-a53d-3d3232987a53.jpg)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by pebogufi** [comment] 2022-06-21 15:08
Can confirm that since a few days of nightlys.
It looks like that state of button (eye vs. eye strike-though) is inverse to state of track (visible vs. not visible)

**Comment by pebogufi** [comment] 2022-06-21 15:13
... but I have just seen https://github.com/osmandapp/OsmAnd/issues/14192
it looks like there is a change in progress.
state -> action

**Comment by scaidermern** [comment] 2022-06-22 09:31
Yep, I can also confirm this issue. I think it is a regression between 4.2.2 and 4.4.4. I'm pretty sure this problem didn't exist in version 4.2.2.

**Comment by sonora** [comment] 2022-06-22 23:52
The button is sometimes out of sync now (sometimes shows action, sometimes shows state).

Workaround: Hiding track still works by tapping it multiple times (twice or 3 times, depending on state), then closing the dialog.

**Comment by pebogufi** [comment] 2022-07-06 11:13
There is a change in behavior.
see https://github.com/osmandapp/OsmAnd/issues/14599 comment of dmpr0 on 06/06/
Previous situation: eye / strike-through-eye
showed current state, 
now: it is action to be performed, which is just the opposite of state.

**Comment by Zirochkabila** [comment] 2022-08-11 13:58
The button displays the action, not the state

>

**Comment by vshcherb** [comment] 2022-10-14 13:23
Now when you disable track it displays with grey color only if it was solid color. 
- [ ] If track is displayed as Altitude for example (not solid), it fully disappears

As a extra note line could be displayed as a stroke.

**Comment by Chumva** [comment] 2022-10-25 12:03
https://github.com/osmandapp/OsmAnd/commit/927a24988594f0decae382eb45363823e65f2691

> * [x]   Hide direction arrows when the track is hidden
> * [x]  Add 50% transparency for disabled track color

**Closed by Chumva** 2022-10-25 12:03 UTC
Labels: and-bugs
