### ISSUE TITLE
Wrong elevation data on graph in route details

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#19142] opened 2024-02-19 18:55 UTC
### Description

A certain point on a road in Belgium displays about 50% slope in route details. Same point in the track context menu, in iOS or web displays different slope levels from 10 up to 20%

### Steps to reproduce

1. Download Belgium Wallonia map 
2. Download Belgium Terrain map (3D)
3. Go to 50.44366 4.55810 and build a route trough this point on a map
4. Go to route details and have a look at a graph (altitude / slope or only slope)

### Actual result

- you will see the peak on the graph, corresponding to slope of 50%
- in track context menu created from that route, slope is approximately 20%
- using [OsmAnd web](https://test.osmand.net/map/?start=50.442085,4.557652&finish=50.445850,4.557481&type=osmand&profile=bicycle#17/50.44331/4.55551) in route details slope is 10%
- in iOS the graph displays a maximum 12% slope

**iOS - route details Android - track context menu Android**

<table style="width:100%">
<tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/33c0acf9-af02-4e32-b05e-3047d02afd9e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/1adfd5fc-1ec6-4ca1-a1d1-9a5bfc415548"  width="300" height="auto"/> </td>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/20e93f7c-ffcf-4fb5-9f4f-f37a06ed337e"  width="300" height="auto"/> </td>
  </tr>
</table>

[2_5364006152285733036.gpx.txt](https://github.com/osmandapp/OsmAnd/files/14336003/2_5364006152285733036.gpx.txt)

### Expected result

- slope is calculated the same in route details and in the track context menu in Android 
- slope graphs look similar in Android, iOS and web

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.7.0#1623m, released: 2024-02-18 and TestFligt 4.7.1.9
Android/iOS version: Android 13, iOS 17.2.1
Device model:
Crash-Logs: ?
```

**Comment by vshcherb** [comment] 2024-02-22 19:19
Obviously it's a bug all data should be consolidated for Web / Android / iOS as we are using same source data across all platforms 
To do: make sure all numbers are the same.

Probably Android value is wrong though it needs to be double checked (50% looks very extreme)

**Comment by vshcherb** [comment] 2024-05-14 09:06
Is the issue fixed now?

**Comment by xmd5a2** [comment] 2024-05-14 09:18
No. April maps use old terrain data. I think graph algorithms should be fixed until it is reproducible.

**Comment by xmd5a2** [comment] 2024-05-17 08:22
Tested with new data:
| route details Android | track context menu Android |
|--------|--------|
| ![Screenshot_2024-05-17-11-09-57-296_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/3171bd3a-8497-443d-bd97-6955e3346cca) | ![Screenshot_2024-05-17-11-11-30-304_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/4b3d52a9-f244-4263-b5ce-6dc6e9da518c) |

Same track in QGIS (profile tool):
![Screenshot_2024-05-17_11-17-10](https://github.com/osmandapp/OsmAnd/assets/5829014/a23593a7-aa22-4102-a582-4c558f4b3878)

Obviously route details Android graph is calculated incorrectly

**Comment by DmitryAlexei** [comment] 2024-07-03 08:16
Todo (brief) 
- compare synthetic .gpx in iOS, Android and web app - if the graphics are the same
- compare elevation data after routing
- compare elevation data after approximation 
So we can find where the problem with the garphs is

**Comment by RZR-UA** [comment] 2024-07-05 11:03
| Header | Header | Header |
|--------|--------|--------|
| ![1](https://github.com/osmandapp/OsmAnd/assets/90444451/9ebaac04-39f3-4b5e-8f76-f3d1dc571231) | ![2](https://github.com/osmandapp/OsmAnd/assets/90444451/94630f95-8cae-40ba-b206-5bcdca00a7ba) | ![3](https://github.com/osmandapp/OsmAnd/assets/90444451/ce61d434-1ba3-4e63-a414-2e57692fbc26) |

**Comment by RZR-UA** [comment] 2024-07-08 17:26
The charts are broken because of no elevation data found in OBF for the bridge:

https://www.openstreetmap.org/way/53122270

Road 3399825309 osmid 53122270 bridge='yes' highway='unclassified' oneway='no' route_hiking_1='' route_hiking='' osmand_highway_integrity_brouting='0' name="Rue du Petit Try" route_hiking_1_colour="white-red" route_hiking_1_distance="306.9" route_hiking_1_name="GR 412 Sentier des Terrils" route_hiking_1_network="nwn" route_hiking_1_operator="SGR asbl" route_hiking_1_osmc_background="white_3" route_hiking_1_osmc_foreground="red_lower_3" route_hiking_1_osmc_stub_name="." route_hiking_1_osmc_text="412" route_hiking_1_osmc_textcolor="black" route_hiking_1_osmc_waycolor="red" route_hiking_1_ref="GR 412" route_hiking_1_relation_id="157373" route_hiking_1_website="https://grsentiers.org/topo-guides/33-gr-412-sentier-des-terrils-9782931078129.html"

**Comment by RZR-UA** [comment] 2024-07-08 17:38
```
	public static boolean isHeightDataNeeded(Way e) {
		if (e.getTag("highway") == null && e.getTag("cycleway") == null && e.getTag("footway") == null
				&& e.getTag("waterway") == null && e.getTag("piste:type") == null) {
			return false;
		}
		if (e.getTag("osmand_change") != null) {
			return false;
		}
		if (e.getTag("tunnel") != null || e.getTag("bridge") != null) {
			return false;
		}
		return true;
	}
```

**Comment by RZR-UA** [comment] 2024-07-08 18:10
OsmAnd IndexHeightData / isHeightDataNeeded() does not generate Elevation information (height data) for bridges/tunnels and as result we do not have height data in OBF-files sometimes.

In this particular case there is the long bridge over the overpass, without any height data available.

OsmAnd Web automatically detects missed height data and fill it out with SRTM request:

![web](https://github.com/osmandapp/OsmAnd/assets/90444451/ebec9b08-bccf-46db-885b-392bd6b0741c)

OsmAnd Android and OsmAnd iOS process the same situation differently (some kind of different algorithm for approximation height-missed segments):

Android:
![android](https://github.com/osmandapp/OsmAnd/assets/90444451/3a759eb3-143f-4997-aa6d-11797d404c41)

iOS:
![ios](https://github.com/osmandapp/OsmAnd/assets/90444451/d93b161f-422e-427e-8ef6-21526a1bfc14)

**The data is:**

```
95.1
96
96.5
97

the bridge (starts at 98, ends at 108 meters)

108
110
111.2
115.7
```

According to the data and the charts:

1. **OsmAnd Android approximates incorrectly and should be fixed (the chart shows one very short step up and then flat line to the end of the bridge).**

2. OsmAnd iOS chart is better but has several issues:

- incorrect scale (it's diffucult to differ the very beginning of the elevations)
- the strange slope graph which is inconsistent with the bridge 98-108 meters increase

Finally, iOS does correct elevation approximation 98-108 and calculates correct slope percentage.

**Comment by RZR-UA** [comment] 2024-07-08 18:11
TODO:

- [ ] fix Android empty-height approximation between segments
- [ ] verify Android Slope information (graph, percentage)
- [ ] compare Android and iOS finally

**Comment by vshcherb** [comment] 2024-07-09 06:42
To do:
- Android, iOS should have same information - on bridges, tunnels should have linear increase (no sudden jump) if information is missing on one of the segment or multiple (starts at 98, ends at 108 meters). 

That's correct
```
The charts are broken because of no elevation data found in OBF for the bridge:
https://www.openstreetmap.org/way/53122270
```

**Comment by RZR-UA** [comment] 2024-07-09 17:21
New interpolation for Android just implemented:

Current:
![1](https://github.com/osmandapp/OsmAnd/assets/90444451/b24a6a16-4139-4064-9218-56249aff12ca)

With interpolation:
![2](https://github.com/osmandapp/OsmAnd/assets/90444451/973141b8-777e-4676-bc25-81535bf38ee9)

(this is the bridge in Lisbon)

**Comment by RZR-UA** [comment] 2024-07-10 14:18
Web TODO:

- [ ] interpolate for /route
- [ ] interpolate for /updateRouteBetweenPoints or get-analysis

**Comment by RZR-UA** [comment] 2024-07-11 11:55
Sometimes OsmAnd iOS calculates wrong slope:

https://test.osmand.net/map/navigate/?start=53.822860,9.285870&end=50.385780,6.656350&profile=car#7/52.049/13.469

**iOS (bug):**
![ios](https://github.com/osmandapp/OsmAnd/assets/90444451/63d62f09-6553-43ca-9a45-58add93e9068)

**Android/Web are OK:**
![android](https://github.com/osmandapp/OsmAnd/assets/90444451/941e474e-08c3-4cfa-8089-e52cd01c6b3d)
![web](https://github.com/osmandapp/OsmAnd/assets/90444451/52486390-9be6-448f-87cd-c9a5125ce45d)

**Comment by vshcherb** [comment] 2024-07-11 14:35
@DmitryAlexei for iOS

**Closed by vshcherb** 2024-07-11 14:35 UTC
Labels: map-data

**Comment by DmitryAlexei** [comment] 2024-07-12 14:31
- tested Android OsmAnd~ 4.8.0#2725m, released: 2024-07-12 and OsmAnd web using

https://osmand.net/map/navigate/?start=53.822860,9.285870&end=50.385780,6.656350&profile=car#7/52.147/5.504

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e7e5a3ac-303d-4774-9f53-afdbca3e865d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/e3d77df3-9248-41ec-82e5-d20a5fe6ef98"  width="300" height="auto"/> </td>
  </tr>
</table>

- separate task for iOS created
