### ISSUE TITLE
Very slow maps under Android 8

### ISSUE THREAD

**Issue by amilopowers** [osmandapp/Osmand#4459] opened 2017-09-20 06:32 UTC
OSMand+, Version 2.7.5
Android 8.0.0 on a Nexus 6P (angler)

Since the update to Android 8 I can barely move the map. It has become very slow. The app works well in general.

Others have mentioned that in Play-Store reviews as well.

**Comment by rbovard** [comment] 2017-09-20 09:26
Duplicate of #4323

**Closed** 2017-09-20 19:12 UTC
