### ISSUE TITLE
[Contour lines plugin] Issue: too few or no altitude labels on the screen

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/Osmand#3938] opened 2017-06-18 12:42 UTC
Hi!

I used "Contour lines plugin" (that I bought recently) at my trekking trip and noticed that very often there are too few or no altitude labels on the whole screen. This definitely makes working with altitude data very inconvenient, because in order to find an altitude of some place I am forced to scroll back and force to find some altitude label along some contour line, and then calculate in my mind how many lines (and meters) is the point and line in question from the line with label. I attached a few screenshots that demostrate the situation. The solution is to increase the number of labels on contours lines, so the screen would contain at least 5..10 labels.

(Attached screenshots are from map of Spain, Catalonia. To reproduce the screen you can search for "tossal de torrent" for example.)

![screenshot_2017-06-11-12-45-39](https://user-images.githubusercontent.com/22505250/27260753-495fcbd8-5434-11e7-9afb-b78f5e9a22a8.png)
![screenshot_2017-06-11-12-45-53](https://user-images.githubusercontent.com/22505250/27260748-4958ccd4-5434-11e7-9995-443bd7c7f8e7.png)
![screenshot_2017-06-11-12-46-01](https://user-images.githubusercontent.com/22505250/27260749-495b9392-5434-11e7-8d12-f868762adf27.png)
![screenshot_2017-06-11-12-46-14](https://user-images.githubusercontent.com/22505250/27260751-495ceae4-5434-11e7-9069-6f087c9e0b1f.png)
![screenshot_2017-06-11-12-46-33](https://user-images.githubusercontent.com/22505250/27260752-495d2176-5434-11e7-8dda-a8937ee98e28.png)
![screenshot_2017-06-11-12-46-50](https://user-images.githubusercontent.com/22505250/27260750-495c5b38-5434-11e7-8f8b-833c0a89d01a.png)
![screenshot_2017-06-11-12-47-03](https://user-images.githubusercontent.com/22505250/27260754-4972c044-5434-11e7-9da8-6b0265b60ded.png)
![screenshot_2017-06-11-12-47-19](https://user-images.githubusercontent.com/22505250/27260755-497607fe-5434-11e7-8c47-ea09e48cdce2.png)

**Comment by njohnston** [comment] 2017-06-18 15:30
Duplicate of #3802.

**Comment by vshcherb** [comment] 2017-06-22 07:57
Fixed

**Closed by vshcherb** 2017-06-22 07:57 UTC
