### ISSUE TITLE
Incorrect free space determination when using SD card

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14508] opened 2022-06-09 12:44 UTC
### Description
The user sees the error when using External storage 2 and Multiuser storage 2 that there is not enough space on the card, although there is memory (samsung xcover 4s too)

### Steps to reproduce
Menu->Settings->OsmAnd settings->Data storage folder -> chose one

### Actual result
The system displays an error

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/172849457-6a81b17d-1ad0-454f-b188-3f1dc49252aa.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/172849463-231958ca-626b-4239-84b4-19ebe1f3b1df.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result

Selectable SD card

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version:  Android 11
Device model: Samsung S9

**Comment by ThaChillera** [comment] 2022-06-10 09:37
Same issue here, it says I cannot download because free space is a negative large number. When selecting storage locations, it doesn't specify the free space available for the sd card locations.

### Your Environment:

OsmAnd Version: 4.1.11
Android/iOS version: Android 11
Device model: Fairphone 3+

**Comment by wandhydrant** [comment] 2022-06-10 23:40
Sounds like a duplicate of #14165 and #13538 . The workaround proposed worked for me: choosing the path /storage/<uuid>/Android/media/net.osmand.plus/files .

The paths readily available in the app (with /data and /obb) wouldn't work, no matter if they already existed or if I deleted them first by uninstalling OsmAnd.

**Comment by vshcherb** [comment] 2022-06-11 11:22
Duplicate of https://github.com/osmandapp/OsmAnd/issues/14165

**Closed by vshcherb** 2022-06-11 11:22 UTC
