### ISSUE TITLE
Declutter UI, introduce a 'Settings' home screen

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#9047] opened 2020-05-22 11:47 UTC
Disappointed feedback for the 3.7 pre-release reveaIs that we work on creating lots of customization options with limited value-add, where users can spend their time on selecting colors or icons for gadgets, and hiding or sorting menu entries. But the app in its default state is still a logical and visual jungle (now worsened) of different places where to configure its basic setup,. There is no logical path with a decision tree to find a particular setting. Instead you have to essentially know which of the many separate  entry points which we now offer leads to the desired setting, like
- **Menu button**/Settings/Osmand settings etc.
- **Configure profile**/General settings etc.
- **Plugins**/(plugin)/Settings, 
- **Configure map**/Plugins settings/(plugin)
- **Configure screen**

This lack of discoverability, missing a linear or systematic way to step through or get an overview, decisively lowers OsmAnd's 'first impression' attractiveness to new users.

A way to improve is:
- [ ] Limit the main menu (drawer) to **functionality** line items, i.e.what users need to call up to perform the everyday core use like search, directions, trip planning.

- [ ] And offer only **one** line item (or just gear icon) as the single entry point to all Settings, as is customary for most apps.
  - _Remove all other duplicate menu items leading to settings of any kind, like Configure map, Configure screen, Plugins. And probably also Download maps, we prompt for missing maps anyway, all else belongs under Settings._
  - _I suggest to even remove 'Configure profile' from the top level. But that's debatable, maybe you insist on keeping this shortcut visible somehow to reflect our recently introduced app profile centricity._

 - [ ] Tapping Settings/gear must lead to **one unified 'Settings' home screen**. It must display and guide to all subsequent categories of settings we now have:
   - OsmAnd settings (affecting the entire app)
   - Map management, download maps
   - Profile management, and Configure profile
   - Plugins, and Plugin settings

_Note: Whoever needs to frequently/directly access a specific setting, should use/request a corresponding QuickAction button. The average user should not need this, or we have a flaw in our usability logic._

As a side effect, the drawer will become shorter and more likeable. You wouldn't believe how  many people I've met not realizing that it can be scrolled to see its off-screen line items.  ;)

**Comment by vshcherb** [comment] 2020-05-22 14:24
The driver for this release was mostly for advanced users and technical features, to allow customization first of all! Also the main driver is to let advanced users create *simplified Profiles* which they can share with other users.

On the other hand every feature is driving to complexity. Unfortunately 3.7 could not be a 1 year release so we can combine: customization & simplification. Simplification is yet to come. And in 3.8 it will mostly come as simplification of menus and moving features to Plugins. 
In 3.9 it will probably come with combining Configure Map / Configure Screen and may be Configure Profile.

As of today you have links from Configure Profile -> Map / Screen - so it is clear. Map should be a quick access button, so person can configure it on the fly. Configure Profile / Navigation / Screen doesn't necessary will be like that so it will be collapsed into Configure Profile.

*Plugins are not profile based*. Enabling plugin will enable for all profiles! But plugin options could be customized in each profile differently. So I think I explained our roadmap it is not perfectly aligned but I think it covers most of use cases mentionned.

**Comment by vshcherb** [comment] 2020-05-22 14:26
As a reply to last article:
- Maps management (More globally external resource management) - not settings, won't be merged. 
- Configure Map settings -settings but with quick access from Map. Discussible how it will be merged.
- Plugins - will be completely redesigned but won't be merged with Settings. They will be more like external or advanced pieces of functionality. 
- Other settings are united today under Configure Profile but there are shortcuts in Drawer, will be merged / redesigned.

**Comment by sonora** [comment] 2020-05-23 05:51
The proposal is simply to have ONE settings homescreen and fork from there to all types of app configuration.

It can contain the app overarching configuration (which plugins are visible, which profiles are visible, external data management, etc.), as well as link to the profile dependent configurations (including plugin settings) etc.

I simply feel the user would welcome such a single handle 'home base for all types of configurations', without having to remember in advance which config details belong where, or are settings or configs, or are profile vs.app global. Also if data management is at least reachable from such a home page it does not hurt.

**Comment by GuentherGredy** [comment] 2021-07-01 08:14
Hello Hardy, hello Victor,

as an (enthusiastic) user of OsmAnd I'm not entitled to review the application. Yet, I recently got an email from Hardy concerning this issue, and I have read it carefully. So please excuse me if I'm going to post some words in this context.

Having the rich feature set in mind, the fist thing I want to say is, that I am completely convinced about what you are offering to your customers. OsmAnd for me is not only an alternative to my Garmin device, even more, I am in the process of migrating from Garmin to OsmAnd in the field!

In the days when starting with OsmAnd I was completely lost due to what you are discussing within this issue; it took me a long time "hiking" down the learning curve, which from my personal point of view has been rather flat. Meanwhile all the single tesseras have become a reasonable picture, but I sometimes still stumble upon the UI.

Today I would sadly miss OsmAnd! Yet, concerning the UI I fully agree to what Hardy has commented at the beginning of this issue. As a retired software engineer and project manager I fully understand the problem of continuing with the structure of a given software on one hand, and thinking about refactoring on the other hand.

I do not know anything about your governance, your head count, your business model, your overall backlog, and what you are able to achieve within your organization, but I personally would very much appreciate UI refactoring in the sense of Hardy's statements.

Stay healthy and thanks for your attention

Guenther, a fan of OsmAnd

**Comment by snouup** [comment] 2021-07-21 13:28
I've been a user of osmand for many years almost since it's inception, yet still get confused sometimes.
For me, the main issues across the Ux are redundancy and poor discoverability.

Often there is more than one path towards a specific menu, more than one method to achieve the same task. For example, there is a profile switcher button on the map, and another profile switcher on the main menu bar. Why?

Users tend to have trouble building a memory of achieving even the most simple tasks if they happen to do them differently every time.

Lots of menus exist in more than form.
Often, it's to provide some "quick access" for the most commonly used setting, hiding the rest of the settings in another version of the menu elsewhere. For example, "Configure profile" has more options than the profile switcher on the map. The profile switcher never tells you there are more settings. Call me stupid but for the longest time, I failed to discover most settings (like app dark theme) at all.

Nothing inherently wrong here, in principle, dividing up settings into Basic/quick access and Advanced categories is a good strategy, _so long as_:
- The basic menu makes it obvious there _is_ an advanced menu, ideally provides a link to it
- Advanced menu does not duplicate contents or functions of the basic menu (see point about redundancy)

Maybe we don't need full redesign, cutting out redundancies may be enough. Menus will be less cluttered and easier to use almost automatically.

**Comment by eternaltyro** [comment] 2021-12-23 14:38
Are there mockups / wireframes for the current UI flows that I can refer?

**Comment by vshcherb** [comment] 2021-12-23 15:56
I believe the issue is 1.5 year and couple of things changed. Map / Data management is not part of this discussion cause it's not settings - it's data i.e. Personal (Tracks / Favorites / ... ) or Application (Maps / Caches)

1. Usability (every day) - now it's possible to change and customize main menu
2. Discoverability - nothing to make it specific all Settings are divided in 4 groups which are discoverable from main menu:
 - Configure Map [Profile]
 - Configure Screen [Profile]
 - Settings -> [Global + Profile Settings]
 - Plugins [Both]
3. Redundancy - as far as I know we have only 2 duplicate settings path
- Plugins -> Settings - same as - Settings -> Profile -> Scroll down Plugin Settings
- Configure Map / Configure Screen  - same as - Settings -> Profile -> Configure Map / Configure Screen
4. Consistency. Probably the most discussible point cause that's exactly why we don't want to merge all settings in one big list but keep as 4 groups:
- Configure Map - everything that interacts with maps i.e. layer on the map
- Configure Screen - everything that overlays with map but doesn't move with map i.e. HUD
- Settings - everything else with links to other screens
- Plugins - everything that's could be extended with either Internal Plugin or External. Please don't forget there are 3rd party plugins though since we don't have Marketplace it looks that are the settings. Nope Plugins are not Settings, it's a possibility to move functionality out of the base application. 

I don't see much sense to create 1 screen with 4-5 tabs cause having 4 menu items simplifies access and basically creates a learning path. Please keep in mind that OsmAnd has 100 settings and we can't compare with apps that could fit settings in few screens so we need to introduce the Structure with categories.

**Comment by sonora** [comment] 2022-01-05 09:05
In my mind, the issue is as valid as ever: We have a **"Settings"** option in the menu, where in other apps a user expects to simply find ALL items related to setting up the app and configuring it.  In OsmAnd, this is not the case because numerous configurations and setting options are scattered elsewhere.

**Comment by GuentherGredy** [comment] 2022-01-05 09:33
My recent experience with the latest software version concerns a **regressive issue** (pls. refer to #13465). I have the fear that you will be faced with regressive issues as long as you didn't declutter the UI. Regressive issues are annoying for the user and expensive for the development.
Happy New Year and stay healthy
Guenther

**Comment by sonora** [comment] 2022-01-05 10:49
Here's how I would top-structure the combined settings screen:

- Settings
  - **Profile selector**
  - Screen appearance (current profile)
  - Map appearance (current profile)
  - Other profile settings  (current profile)
  - **Global app settings**
  - **Download maps**
  - **Plugins**
  - **Backup and Restore**
  - **Purchases**

**Comment by vshcherb** [comment] 2022-01-14 17:24
Thanks @sonora . As I understand you would like to move from Main Menu to Settings Menu and Main Menu would win 4 items in that case. 

I would close the issue:
1.  Even though we still  plan to add Plugins to Settings (so it will be everything except Download Maps there)
2. Consolidate Map appearance / Screen appearance postponed for now
3. And most important, now you could customize Main Menu anyway.

**Comment by vshcherb** [comment] 2022-01-14 17:25
Right now only Download maps & Plugins are not accessible through Settings

**Closed by vshcherb** 2022-01-14 17:24 UTC
Labels: Observed

**Comment by GrzegorzWidla** [comment] 2022-01-27 17:15
> > For me, the main issues across the Ux are redundancy and poor discoverability.
> 
> Aren't those two inherently at odds with each other?

No. You could have single action appear in multiple unusual places one wouldn't expect it to be.

**Comment by HibGut** [comment] 2025-04-03 10:34
> Here's how I would top-structure the combined settings screen:
> 
>     * Settings
>       
>       * **Profile selector**
>       * Screen appearance (current profile)
>       * Map appearance (current profile)
>       * Other profile settings  (current profile)
>       * **Global app settings**
>       * **Download maps**
>       * **Plugins**
>       * **Backup and Restore**
>       * **Purchases**

You can add navigation settings to the list. 

I'm in a Telegram user group for OsmAnd and frequently people post about their frustration with the UI. Don't know settings exist, can't find settings they do know exist, can't replicate how they found settings last week, general sense of overload, ... This issue is as current as ever, I can't comprehend how it could be closed as "completed" in Jan 2022.

**Comment by GuentherGredy** [comment] 2025-04-04 12:17
I have tried to document the menu. Perhaps it helps argumenting. BR Guenther

[1_Osmand-Menu.pdf](https://github.com/user-attachments/files/19604189/1_Osmand-Menu.pdf)

**Comment by sonora** [comment] 2025-04-04 13:12
The main side bar mixes
- app **settings and configuration**
- with regular app **usage**

line items in a pretty arbitrary fashion, that's the feedback I get most often.

Could probanly most transparently be resolved by 
- moving all settings and configuration items behind a single, top level 'Settings' emtry
-  so that the remainder of items visible on this top level are all 'regular use cases', like Search, Navigation, My Places, Plan a trip.
