### ISSUE TITLE
unreproduceable routin error

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#6665] opened 2019-03-12 13:13 UTC
Sometimes I see routing errors, that I can reproduce later for limited time only or can not reproduce at all.

Example 1:
There is no left turn here:
https://www.openstreetmap.org/relation/7454212
The last modification was made over a year ago.

But about a week ago I got:
![Screenshot_20190228-220938_OsmAnd~](https://user-images.githubusercontent.com/14617699/54202451-16102d00-44e1-11e9-92fd-ec41bca287cf.png)

And was able to reproduce it with routing emulation several days after:
![Screenshot_20190228-220938_OsmAnd~](https://user-images.githubusercontent.com/14617699/54202474-2cb68400-44e1-11e9-818e-0241890c29cf.png)
![Screenshot_20190302-025422_OsmAnd~](https://user-images.githubusercontent.com/14617699/54202476-2d4f1a80-44e1-11e9-844a-a1c4b98bccf2.png)

But now it routes correctly.

Example 2:
![Screenshot_20190124-000500_OsmAnd~](https://user-images.githubusercontent.com/14617699/54202505-3e982700-44e1-11e9-8eb6-b07e62af229c.png)

Example 3:
![screenshot_20181102-051613_osmand](https://user-images.githubusercontent.com/14617699/47890115-7bcb1900-de5e-11e8-8959-f991c035986c.png)
 #6245  #6321

**Comment by hakuchi** [comment] 2019-04-16 21:08
@532910 you reported this errors just some months ago, and no other user can reproduce this errors.

Maybe in the OsmAnd data on your phone is something wrong, because of your "sometime it works correct and sometime not".
You should complete uninstall OsmAnd(uninstall+delete remaining OsmAnd data) and make a clean new installation.(favorites can be exported)

This helped to me to fix some strange things.

What version are you using? PlayStore or nightly? Updated or old?

**Comment by 532910** [comment] 2019-04-16 21:20
The latest from f-droid

**Comment by 532910** [comment] 2019-04-16 21:27
May `OsmAnd Live navigation` setting give such effect?

**Comment by hakuchi** [comment] 2019-04-16 22:35
> May `OsmAnd Live navigation` setting give such effect?
Maybe, but only if in this intersection are some newer changes.
You can also deactivate the Osmand live and test without this.

You should try clean installation and check again, because for me this is not reproducible and a clean installation may help. There can be some old or not correct updated data on your phone what making these routing errors.

**Comment by 532910** [comment] 2019-04-16 22:50
this is not reproducible even for me

**Comment by hakuchi** [comment] 2019-04-29 17:02
> this is not reproducible even for me

so you should close this issue

**Closed** 2019-04-29 20:49 UTC
Labels: Observed

**Comment by 532910** [comment] 2019-11-27 16:59
one more unreproduceable routing error
![image](https://user-images.githubusercontent.com/14617699/69743981-66ebb280-1150-11ea-8250-f0d5e2b2d5cb.png)
