### ISSUE TITLE
Osmand Live data option in navigation settings is not respected (wrong routing with live updates enabled)

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#18008] opened 2023-08-23 16:40 UTC
## Description
Vienna, coming from "Brigittenauer Brücke" to "Handelskai" (I took the wrong exit and had to go back to the other side of the Danube). Routing directed me this way, but this turn is not allowed and not even possible, the "shortcut"/turn would be against the driving direction.

### How to reproduce
Happened yesterday using online map and car profile.
Could not reproduce it on osmand online and neither on OSM online.
But it is reoroduceable using the online map: configure map / map source / (OsmAnd (online tiles) and also using the offline map

### Actual result
But you see on the screenshot, how the routing directed me.

### Expected result

**Environment**
OsmAnd Version: +4.5.10
Android/iOS version: 13
Device model: S20+

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/da42af66-b5b9-443b-bbae-29b7233006fe"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by sonora** [comment] 2023-08-23 17:18
Probabaly not an OsmAnd issue - looks like a missing turn restriction on the map and needs to be fixed there, from Handeslkai onto Brigittenauer Bruecke? Can anybody confirm? https://www.openstreetmap.org/#map=17/48.23596/16.39206

**Comment by Rowin63** [comment] 2023-08-23 17:54
Openstreetmap and Osmand online is correct:
![Osmand_online](https://github.com/osmandapp/OsmAnd/assets/95540936/7c4d9196-6872-4676-b2f0-204ade7ecf3f)
![Openstreetmap_online](https://github.com/osmandapp/OsmAnd/assets/95540936/a686a905-5cec-4d66-877a-c6cb0bb3f7f5)

**Comment by sonora** [comment] 2023-08-23 18:21
Yes, looks like a bug, because there is a turn restriction there: https://www.openstreetmap.org/relation/395318

**Comment by DmitryAlexei** [comment] 2023-08-24 15:17
- Tried to reproduce this issue on the [OsmAnd map](https://test.osmand.net/map/?start=48.241547,16.406917&end=48.241044,16.405613&type=osmand&profile=car#17/48.24062/16.40453) with no success.

Also didn't manage to reproduce it with OsmAnd~ 4.6.0#663m, released: 2023-08-24 and OsmAnd 4.5.10, released: 2023-08-09
- tried various variations of starting and ending points (start 48.24064° N, 16.40430° E, end 48.24178° N, 16.40838° E)
- with and without online maps as map source
Every time relation https://www.openstreetmap.org/relation/395318 was respected

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/7eb39c1b-3e16-4829-9531-40adb9924bb9"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f678c7a2-2cb4-4a7e-aa4c-6cc9b9363ca2"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment] 2023-08-24 15:23
> And in the App it´s like this:
> 
> <img alt="" width="300" height="auto" src="https://user-images.githubusercontent.com/95540936/262757909-0330fd99-d8ab-4ba8-8727-0cdd50aefa18.jpg">

@Rowin63 have you build your route in driving profile and after that changed profile to *Browse map*? 

Can you, please, provide:
- exact coordinates for starting point and destination 
- your profile settings (menu > settings > your driving profile > go to the bottom and chose *Export profile*

**Comment by sonora** [comment] 2023-08-24 18:09
I've tried also, could not reproduce the issue. Perhaps your profile is warped somehow:, Please note that turn restrictions are e.g. not observed for pedestrian routing, so maybe you use a custom profile basing on that?

Also note that when a route has been configured, and you subsequently change the profile via the top left icon on the map screen  this only affects the map view. It does **not** retroactively change the calculated route's transport mode. (To do that, you would have to use the profile buttons on top of the route config dialog.)

**Comment by Rowin63** [comment] 2023-08-24 18:44
Hello!

Starting point was around here (I took the wrong exit): 48.24130, 16.40031
Destination point was here: 48.24490, 16.41012

First time it happened, I was on the road in the Car Profile. No switching around.
For the screenshot I posted last, I created the route in the car profile, then switched to the viewing map profile,



The profile I use (had to rename the .osf to .txt for uploading)
[Auto.txt](https://github.com/osmandapp/OsmAnd/files/12432355/Auto.txt)

After this I did reset the car profile to it´s original settings, still the same routing: 

![Screenshot_20230824_203417_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/6e315a4f-e4c6-44d0-a4e7-12f2c9ca2778)

**Comment by sonora** [comment] 2023-08-24 21:10
Next thing it could be is a faulty map. My AT map rather old, 2022-09-01. Which one do you use?

**Comment by Rowin63** [comment] 2023-08-25 05:21
I just (right now) updated the map.
But I really don't want you to spend your time on this. It's a very minor thing. And everyone being there sees, that it's not even possible to turn left, up the bridge, there. So after some meters going straight anyway one gets a recalculated new route and is directed correctly again.
Please don't spend your time on this. I thought it's just a simple click to correct it and not a project 😉👍

**Comment by sonora** [comment] 2023-08-25 06:11
It looks like map is correct on OSM. So I felt sort of challenged how to reproduce it because neither @DmitryAlexei nor I can't.That's why I listed all the spurious possibilities about customized routing profiles or changing profiles on the fly.

Yes, probably not a very pressing issue. Still, I'd be interested to find out what's going on, maybe @DmitryAlexei can tell upon checking your Auto.osf config file.

**Comment by DmitryAlexei** [comment] 2023-08-25 09:05
OsmAnd 4.5.10, released: 2023-08-09
Tried to reproduce using provided driving profile and coordinates:
Starting point 48.24130, 16.40031
Destination point 48.24490, 16.41012
Austria Lower Austria map was downloaded
Not reproduced 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/37be374b-53e8-48c8-9ee5-15cf441f5bc5"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ba98260c-117d-403b-bcec-0ce70b5b97f2"  width="300" height="auto"/> </td>
  </tr>
</table>

But **Issue can be reproduced** if you turn on live updates for _Austria Lower Austria_ map and download them:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/4a463347-fd9b-449b-9440-f83a7df5e391"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/8f8cb54f-e88d-47e0-822a-33c491bfcea0"  width="300" height="auto"/> </td>
  </tr>
</table>

**Important**. In provided profile:
- development plugin was disabled
- and, accordingly, the *Osmand live data setting* was not available (https://osmand.net/docs/user/navigation/guidance/navigation-settings#development-settings)

**Issue can also be reproduced with OsmAnd~ 4.6.0#663m**, released: 2023-08-24 with live updates downloaded and *OsmAnd live data* disabled:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/45980b9d-d21e-46f7-801a-8e3e217558c2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/e87e4afd-dfe4-4875-8358-2c017069498f"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Rowin63** [comment] 2023-08-25 09:52
Thanks for investigating 👍

**Comment by sonora** [comment] 2023-08-25 10:46
Yes, "Live updates" makes sense, it seems that is often the culprit for phenomena like this... 😉 Just came here to suggest that, but @DmitryAlexei beat me to the finish line 😉 😉 😉  - Well done!!

**Comment by sonora** [comment] 2023-08-25 12:00
Are there 2 independent bugs then here?
- OsmAnd seems to somehow ignore, at least for routing, if OsmAnd live data is disabled
- OsmAnd ignores a valid turn restriction present in the OSM data and unaltered by any updates when it uses live data?

**Comment by okt-nikolaym** [comment] 2023-08-28 06:54
I see a trouble here with life updates: 40.3074, 44.365

intial changeset: https://www.openstreetmap.org/changeset/139877462

deleted ways:
https://www.openstreetmap.org/way/961493314
https://www.openstreetmap.org/way/961493311


correct vehicle routing: 
![image](https://github.com/osmandapp/OsmAnd/assets/109795339/cfc00b30-ad6c-4833-abc9-e8d9d5967607)

Osmand with Live updates rouging:
![image](https://github.com/osmandapp/OsmAnd/assets/109795339/42199897-f479-4cfb-9be3-7390780251b8)

View without live updates:
![image](https://github.com/osmandapp/OsmAnd/assets/109795339/97920253-6ed1-4d15-b507-ea9b37b599fa)

With live updates:
![image](https://github.com/osmandapp/OsmAnd/assets/109795339/95adf489-ed6c-4e0c-b40f-f487e4baac05)

Observed on versions:
OsmAnd+ 4.5.10 (gplay)
Osmand~ 4.6.0#670m (nigh build from 27 aug 2023)

**Comment by noktoborus** [comment] 2023-08-28 07:16
I see a trouble here with life updates: 40.3074, 44.365

intial changeset: https://www.openstreetmap.org/changeset/139877462

deleted ways:
https://www.openstreetmap.org/way/961493314
https://www.openstreetmap.org/way/961493311


correct vehicle routing: 
![image](https://github.com/osmandapp/OsmAnd/assets/109795339/cfc00b30-ad6c-4833-abc9-e8d9d5967607)

Osmand with Live updates rouging:
![image](https://github.com/osmandapp/OsmAnd/assets/109795339/42199897-f479-4cfb-9be3-7390780251b8)

View without live updates:
![image](https://github.com/osmandapp/OsmAnd/assets/109795339/97920253-6ed1-4d15-b507-ea9b37b599fa)

With live updates:
![image](https://github.com/osmandapp/OsmAnd/assets/109795339/95adf489-ed6c-4e0c-b40f-f487e4baac05)

Observed on versions:
OsmAnd+ 4.5.10 (gplay)
Osmand~ 4.6.0#670m (nigh build from 27 aug 2023)

**Comment by ivanPyrohivskyi** [comment] 2023-09-08 06:42
During August 2023 problem detected 3 times in live updates, last time - 25.08.2023.
Cause of problem - generation of obf (*_before.obf) file was corrupted, was not accepted some rules of convert tags from rendering_types.xml .
Do not close the issue, need monitoring during September. Place described in issue has good location with relation with many members, that can be change.

**Closed** 2023-09-08 09:56 UTC
Labels: live-updates
