### ISSUE TITLE
Nightly freezes frequently, but no crash

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#18355] opened 2023-10-16 10:03 UTC
### Description

The latest nightlies do freeze very frequent at app start, but not crash (no crash report is created).
This last freeze took almost 5 minutes, then something like a "internal restart" happened (app worked again and at that moment a new logcat was created => like a "restsart"?)
After this event the app runs fine again with a memory consumption between 180-200MB (tracks on display)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/5ccba477-ef13-4468-b0f8-8f7aa0740615"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

i dont know...

### Actual result

freeze

### Expected result

no freeze :-)

### Your Environment (required)

OsmAnd Version: 4.6.0#872m but also before
Android/iOS version: 13
Device model: S20+

**Comment by DmitryAlexei** [comment] 2023-10-16 12:06
Related with or duplicate of https://github.com/osmandapp/OsmAnd/issues/18302

**Comment by Rowin63** [comment] 2023-10-16 14:13
If you say so, then yes.
But to me it seems different - this is a 4.6.0.XXXX and my free 4.5.10 parallel on the same phone does not show this issue.

**Comment by DmitryAlexei** [comment] 2023-10-16 14:57
When do you experience freezes? When do you activate OsmAnd from background? Or when you launch the app using the icon?

**Comment by Rowin63** [comment] 2023-10-16 15:11
When I launch the app, at the first start, using the icon

**Comment by Rowin63** [comment] 2023-10-16 17:22
Here´s a logfile.
00:00 Osmand start. Blank screen for about 25sec. (only the osmand logo)
00:25 the first map appears
01:00 the first tracks appear, first freeze, but the app continues.

If now I get busy in the menues, osmand freezes and I cant get a logfile anymore.

[logcat.log](https://github.com/osmandapp/OsmAnd/files/12919715/logcat.log)

**Comment by Rowin63** [comment] 2023-10-16 17:45
Here´s the next, osmand still is busy and the "osmand does not response" appears frequently.

[logcat.log](https://github.com/osmandapp/OsmAnd/files/12919972/logcat.log)

**Comment by Rowin63** [comment] 2023-10-16 17:50
Here´s one more, this "no response" keeps popping up again and again.
I had to close the app now.

[logcat-1.log](https://github.com/osmandapp/OsmAnd/files/12920008/logcat-1.log)

**Closed** 2023-11-01 16:39 UTC
Labels: and-bugs
