### ISSUE TITLE
Address Search using zip code: House numbers not listed

### ISSUE THREAD

**Issue by MSenning** [osmandapp/Osmand#2284] opened 2016-02-27 10:51 UTC
## Malfunction of address search using zip code
Searching an address in a city using the corresponding zip code rather than the name of the city, no list of the house numbers is found:
E.g., searching the zip code _8001_ in Switzerland which is a zip code of a Zurich area, a list of streets in this area is (correctly) shown. Choosing _Bahnhofstrasse_ in this list yields the error message _No house numbers / houses found_. 
In contrast, if searching for the city name _Zurich_ rather than the zip code, the same list of streets is shown. But now, choosing _Bahnhofstrasse_ returns correctly all house numbers.

**Comment by rominf** [comment] 2016-06-14 14:07
@MSenning. Thank you for report. Closing this as duplicate of #1462. You should not catch this bug with July's maps.

**Closed by rominf** 2016-06-14 14:07 UTC
