### ISSUE TITLE
Wrong lane is selected

### ISSUE THREAD

**Issue by petersohn** [osmandapp/Osmand#6529] opened 2019-02-10 14:51 UTC
Wrong lane is selected when navigating the following intersection along the main street:

https://www.openstreetmap.org/#map=19/47.45902/9.64053

![screenshot_20190210-153751_osmand](https://user-images.githubusercontent.com/2822847/52535083-8133db80-2d4a-11e9-8d44-e80048f7f041.jpg)

In OpenStreetMap, the turn lanes are `left;through|right`. OsmAnd correctly finds the route, but it says that I have to take the left lane, although the correct one is the right lane. OpenStreetMap also has the `destination:ref:lanes` tag filled with the value `|L202` (L202 being the ref of the road I'm travelling), but OsmAnd doesn't seem to respect this tag.

Here is a relevant screenshot with satellite image:

![screenshot_20190210_155433](https://user-images.githubusercontent.com/2822847/52535259-59457780-2d4c-11e9-8161-43420d45c37e.png)

**OsmAnd version:** OsmAnd+ 3.2.7.

**Map version:** Austria 1 Jan 2019.

**Comment by InsertUser** [comment] 2019-02-12 00:06
I suspect that in the view of OSM (and OsmAnd) this is not considered a right turn as the main road appears to bend to the right and so continuing 'straight' is to continue around the bend.

**Comment by vshcherb** [comment] 2019-04-12 15:13
This is indeed a very tricky issue. Even that main road turns slightly right OsmAnd doesn't consider that crossroad as intersection, so it doesn't try to suggest anything but "Go Straight". Arrow highlighting simply highlights go straight here though it is not correct.

Probably the curve lane is too smooth. I'm not sure if changing geometry could help though somehow it should be triggered as a turn not as a straight road.

**Comment by vshcherb** [comment] 2020-06-08 15:24
Should be fixed, can't reproduce anymore

**Closed by vshcherb** 2020-06-08 15:24 UTC
