### ISSUE TITLE
[Feature request]: move labels on the right side of the altimetric plot:

### ISSUE THREAD

**Issue by malaerba** [osmandapp/OsmAnd#18741] opened 2023-12-15 07:48 UTC
### Describe the idea (required)

![Screenshot_20231212-174040_1](https://github.com/osmandapp/OsmAnd/assets/1038498/6f4b4a1e-fa42-4677-9d80-41903367f973)

Move the labels with altimetric datas on the right side of the altimetric plot. 

The picture shows how the altimetric plot is. 

### Tell us about the expected behaviour (required)

I travel by bike. If labels are on the right side I can read easily how much to climb in the next kilometers. 

### Tell us about alternatives you've considered (required)

The workaround is to zoom the plot to show the closer part of the track, but in not easy when riding.

**Comment by DmitryAlexei** [comment] 2023-12-15 08:41
It's a duplicate of https://github.com/osmandapp/OsmAnd/issues/18204
see comments in all related issues

**Comment by Max1234-Ita** [comment] 2023-12-15 08:45
In my opinion, moving the labels to the right side would just translate the problem to the final part of the travel.

I think a possible alternative would be moving the info labels on the top of the graph, so that they will never interfere anymore: i.e., see the mock-up picture below:

![image](https://github.com/osmandapp/OsmAnd/assets/15315381/74a6d33b-b68c-4bc8-a330-c8fec419397f)



Another alternative could be allowing the user to scroll the graph even when at maximum zoom-out factor, so that it will be fully visible on the side of the labels:

![image](https://github.com/osmandapp/OsmAnd/assets/15315381/3e58d1d3-8fa3-4a52-8bfe-d2c65d459b69)

**Closed** 2023-12-15 11:32 UTC
