### ISSUE TITLE
Map live updates don't provide elevation information

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#16657] opened 2023-03-10 17:19 UTC
Map live updates don't provide elevation information (incremental map updates) such as 
1. Grade on the updated / added ways
2. Uphill / downhill on the updated / added ways 

It's visible that route details graph has empty spots for elevation

**Comment by scaidermern** [comment] 2023-03-13 08:35
Duplicate of #13789 :)

**Comment by ivanPyrohivskyi** [comment] 2023-03-13 14:13
Data for test:
Changed relation: https://www.openstreetmap.org/relation/13811151

Live update file without elevation:
[Ukraine_transcarpathia_europe_23_03_10.obf.gz](https://github.com/osmandapp/OsmAnd/files/10958151/Ukraine_transcarpathia_europe_23_03_10.obf.gz)

Live updates with elevation:
[Ukraine_transcarpathia_europe_23_03_09.obf.gz](https://github.com/osmandapp/OsmAnd/files/10958203/Ukraine_transcarpathia_europe_23_03_09.obf.gz)

<img width="400" src="https://user-images.githubusercontent.com/1040293/224726769-2e3d92fa-4c3c-464e-8910-8db7b0749d99.png"/> <img width="400" src="https://user-images.githubusercontent.com/1040293/224726751-1ef73381-28e2-4fb4-a191-1e4c059feef3.png"/>
<img width="400" src="https://user-images.githubusercontent.com/1040293/224726782-3d274a43-bc4d-4178-831d-376e4969a80b.png"/> <img width="400" src="https://user-images.githubusercontent.com/1040293/224726784-69c984d7-09f1-4e74-8028-6dbc15ffbbc8.png" />

**Closed** 2023-03-30 14:47 UTC
Labels: live-updates
