### ISSUE TITLE
Loop GPX Track: finishes too quick as it starts

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11717] opened 2021-05-19 13:30 UTC
The problem is in planning a loop route. If you plane a route (or select follow by track) in a circle and the finish point is located immediately after the start point, then navigation will ignore all other points and plan the route only between the start and finish.

https://drive.google.com/file/d/1TS9iWhucSN3vUWt7SfXFkuynzUVqe2Lk/view.

The navigation by the loop is working only if you swipe the start and finish points.

**Comment by pebogufi** [comment] 2021-05-19 13:58
If you want to plan a "loop" route, add all intermediate points one after the other (in the correct order) with "add as subsequent destination", then final destination also with "add as subsequent destination", then start point. 
This works very easy.

**Comment by vshcherb** [comment] 2021-05-19 16:08
When navigating by GPX intermediate points don't work but the issue is that start point is too close to end point, so after start navigation it immmideately recognizes as finish point. Probably we can debug once we have simulate GPX track as well.

**Comment by vshcherb** [comment] 2021-05-19 16:16
[Zopp Verkennend.gpx.zip](https://github.com/osmandapp/OsmAnd/files/6510274/Zopp.Verkennend.gpx.zip)

**Comment by cepprice** [comment] 2021-11-05 16:56
Was fixed in 4.0

**Closed by cepprice** 2021-11-05 16:56 UTC
Labels: Observed
