### ISSUE TITLE
Weird motorway routing - Makes me take the opposite direction then reverse at the next exit

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#17772] opened 2023-07-31 13:22 UTC
# 🐞 routing report

### Routing engine
- [ X ] OsmAnd's in-app offline routing
- [   ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile
Car

### Start and end points

Start point: [Italy-Lombardy] Voghera, Corso Ventisette Marzo, 11 (https://www.openstreetmap.org/way/1079848536)
End point: [Italy-Lombardy] Busto Arsizio, Corso Sempione, 214 (https://www.openstreetmap.org/way/1130921150)

### Actual and expected routes
Expected route:
- From the starting point, go to Casei Gerola (https://www.openstreetmap.org/way/49208081)
- Take the A7 Motorway, North direction, to Milan
- Take the E35/A50 ("Tangenziale Ovest di Milano") to Terrazzano
- Take the A8 Motorway to Busto Arsizio

Actual route is initially calculated as expected:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/15315381/399afc7a-14b2-47a6-afb7-ecb0a4e16d3e"  width="300" height="auto"/> </td>
  </tr>
</table>

 However, as I come to the first toll barrier in Casei Gerola (https://www.openstreetmap.org/way/49208081), it changes:

**- Take the A7 Motorway, SOUTH direction, to Castelnuovo Scrivia (https://www.openstreetmap.org/way/32464090)
- Turn left and take the SP93 road (https://www.openstreetmap.org/way/49208029);
- Go straight for about 2.5 Km, until here: https://www.openstreetmap.org/node/364989081
- Do a U-turn (?!?)
- Go back to Castelnuovo Scrivia**
- Take the A7 Motorway, North direction, to Milan
- Take the E35/A50 ("Tangenziale Ovest di Milano") to Terrazzano
- Take the A8 Motorway to Busto Arsizio

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/15315381/c6464a6d-df32-422c-b757-8cba492de086"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/15315381/e2ab6740-1bbc-446a-aa77-5a5af99f06aa"  width="300" height="auto"/> </td>
  </tr>
</table>

### Is this a regression?
I saw this behaviour also on previous releases of OsmAnd 4.
Probably it wos properly working in OsmAnd 3

## 🌍 Your Environment

**OsmAnd Version:** 

<pre><code>
OsmAnd Plus v. 4.5.8

</code></pre>

**Device and Android/iOS version:**
Samsung Galaxy A50, with Android 11 (non-rooted)

**Maps used (online or offline):**
- [X ] Offline maps offered within the OsmAnd app for download.
**Anything else relevant?**

Behaviour observed with both Version 1 and Version 2 rendering (Version 2 used in the attached pictures)

### Additional info
Please follow the steps below in order to reproduce the behaviour more easily:

1. Close OsmAnd and remove it from the list of Recent Apps 
2. Launch OsmAnd
3. Search for the start point and show it on the map @ zoom  = 16 or 17
4. Set the start and destination points as described above.

If OsmAnd is not shut down before, there is some chance the route is calculated as expected: 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/15315381/9b12718a-cb59-4df7-bdcf-c26a724d4cf5"  width="300" height="auto"/> </td>
  </tr>
</table>

Thanks for you work,
Max

**Comment by vshcherb** [comment] 2023-07-31 16:45
I think we are talking about this route - https://test.osmand.net/map/?start=44.991950,9.003650&end=45.636880,8.827690&type=osmand&profile=car#17/45.01240/8.92830 - fresh calculations don't produce any errors. The error might be reproducing only during simulation

**Comment by Max1234-Ita** [comment] 2023-07-31 17:45
> I think we are talking about this route - [test.osmand.net/map/?start=44.991950,9.003650&end=45.636880,8.827690&type=osmand&profile=car#17/45.01240/8.92830](https://test.osmand.net/map/?start=44.991950,9.003650&end=45.636880,8.827690&type=osmand&profile=car#17/45.01240/8.92830) - fresh calculations don't produce any errors. The error might be reproducing only during simulation

I actually did that trip today, and it happened while I was driving...

**Comment by DmitryAlexei** [comment] 2023-08-01 06:50
To reproduce the situation correctly, add information about your navigation settings:
go to settings > your driving profile >swipe to the bottom of the page > choose *Export profile* and attach the file to this issue
or add screenshots: navigation > settings > navigation settings > route parameters

**Comment by Max1234-Ita** [comment] 2023-08-01 07:37
> To reproduce the situation correctly, add information about your navigation settings: go to settings > your driving profile >swipe to the bottom of the page > choose _Export profile_ and attach the file to this issue or add screenshots: navigation > settings > navigation settings > route parameters

Hi Dmitry, and thanks for your attention.

Please find attached the .obf coming from export of the profile I used for route calculation.
I didn't include the maps since they occupy more than 5 Gigabytes; please let me know if you need some more info.

Max

[Automobile.zip](https://github.com/osmandapp/OsmAnd/files/12225857/Automobile.zip)

**Comment by DmitryAlexei** [comment] 2023-08-17 13:59
[OsmAnd map](https://test.osmand.net/map/?start=44.992120,9.002970&end=45.636689,8.828396&type=osmand&profile=car#16/45.0135/8.9285)
[OSRM routing](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=44.99212%2C9.00296%3B45.63669%2C8.82840#map=16/45.0126/8.9324&layers=N)

For navigation on the device with OsmAnd~ 4.6.0#626m, released: 2023-08-17 :
Starting point [44.9921153, 9.0029606](https://www.openstreetmap.org/#map=18/44.9921153/9.0029606)
End point [45.6366886, 8.8283958](https://www.openstreetmap.org/#map=18/45.6366886/8.8283958)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/802e5dca-49b0-4f1c-9fb9-d126320718dc"  width="300" height="auto"/> </td>
  </tr>
</table>

1. Have tried to set up initial and end point with map markers, using search and selecting them on the map, every time the route is as it expected to be.

2. In realistic simulation with default driving profile (settings were reset to defaults via menu > settings > driving profile > reset to defaults) and your driving profile, I didn't manage to reproduce this issue. Also tried navigation with recorded GPX file from the message above and also no luck.
Every time, OsmAnd gave right instructions and didn't change initial route. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/2076a09d-18e2-49ee-a125-e5e4548bf633"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/23c68864-d8d7-4d32-a516-3f1e1e6419e1"  width="300" height="auto"/> </td>
  </tr>
</table>

@Max1234-Ita as I understand you have made

**Comment by DmitryAlexei** [comment] 2023-08-17 14:02
@Max1234-Ita Wrong navigation instruction are probably related with route recalculation due to gps signal loss.

**Comment by vshcherb** [comment] 2023-08-18 10:15
Closing as not reproduced

**Closed by vshcherb** 2023-08-18 10:15 UTC
