### ISSUE TITLE
[Feature request / correction] Dark themed splash screen

### ISSUE THREAD

**Issue by Atrate** [osmandapp/Osmand#7261] opened 2019-07-16 04:32 UTC
The last update gmhas brought a really nice visual change to the dark theme, I like it a lot, but there's a thing missing.

When the app is set to use the dark theme, the initial OSMAnd+ splash screen should also be dark themed, to not blind people at night.

Thank you.

**Comment by vshcherb** [comment] 2019-09-06 21:19
Well it is nice to have though we need to wait for Android 10, to properly implement it. Night theme had poor support from operation system, so we ended up to workaround with our own solution. The problem that settings are not initialized till the splash

**Comment by dmpr0** [comment] 2020-02-24 11:05
Duplicate of https://github.com/osmandapp/Osmand/issues/8040

**Closed by dmpr0** 2020-02-24 11:05 UTC
Labels: Nice to Have

**Comment by Atrate** [comment] 2020-02-24 12:50
Nice, an older issue being marked as a duplicate of a newer one
