### ISSUE TITLE
Incorrect route planning (not a routing issue)

### ISSUE THREAD

**Issue by Yogurt4** [osmandapp/OsmAnd#17649] opened 2023-07-17 11:23 UTC
## Description

The starting point seems to be ignored when feeding the routing engine.

### How to reproduce

Plan a walking route that has a starting point very far from your current location.

### Actual result

1. It takes ages for the routing engine - if it can route at all. It is due to the unnecessary routing between your current location and the desired starting point.
2. The result includes everything from your current location.

The attached picture shows a routing from Glen Nevis to Ben Nevis, while still being on the Isle of Skye.

![kép](https://github.com/osmandapp/OsmAnd/assets/13086031/d03d97f1-0e29-40c9-ba17-a22a18b898b3)

### Expected result

Route from the specified starting point.

**Environment**
OsmAnd Version: 4.4.7
Android/iOS version: 101.191014.001
Device model: Xiaomi Redmi 8

**Comment by mikehgentry** [comment] 2023-07-17 11:26
Duplicate of #17498

**Comment by Yogurt4** [comment] 2023-07-17 11:33
Yes, it seems to be the same issue. Continuing there.

**Closed** 2023-07-17 13:58 UTC
