### ISSUE TITLE
Proper favourite places importing from kmz files

### ISSUE THREAD

**Issue by krwow** [osmandapp/OsmAnd#19249] opened 2024-03-05 19:48 UTC
### Description

Favourite places import from kmz files is somewhat supported, but imported places are more like just points with location and name, they are not connected with POI data from OpenStreetMap - e.g. there's no opening hours in imported favourite places.

Please improve it, because migrating from apps like OrganicMaps or Maps.me, which can export favourite places to kmz file, requires at this moment actually adding all places to favourites from the start if we want to have them connected with data from POI.

### Steps to reproduce

Import some kmz file with favourite places by touching plus sign ("Add to Favourites") in "My Places" (kmz file can be exported from e.g. Organic Maps or Maps.me).

### Actual result

Imported favourite places have only location and name, other information from OpenStreetMap database are not visible - it seems to be just a point, not POI added to favourite places.

Favourite place imported from kmz file:
<img src="https://github.com/osmandapp/OsmAnd/assets/65966603/c69a939c-8734-498b-aea7-71ecbf64e897" alt="favourite_place_imported_from_kmz.png" width=25% height=25%>

### Expected result

Favourite places imported from kmz file should behave as POI from OsmAnd added to favourite places - they should have all information in themselves, including opening hours, POI type and dish type.

Example of POI added to favourite places in OsmAnd:
<img src="https://github.com/osmandapp/OsmAnd/assets/65966603/1d3c0f52-0a21-47a9-9c6f-c9e1cdb323f1" alt="favourite_place_from_osmand.png" width=25% height=25%>

**Comment by yuriiurshuliak** [comment] 2024-03-06 13:32
Duplicate of #11210

**Closed** 2024-03-11 22:36 UTC
