### ISSUE TITLE
route not shown on map - OsmAnd nightly

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/OsmAnd#15683] opened 2022-11-08 20:56 UTC
in latest nightly(#34887m) the calculated route is not shown on the map.
If I scroll the map fast, the route looks like as she is under the map.

![1](https://s20.directupload.net/images/user/221108/b6scjn7k.png)

![2](https://s20.directupload.net/images/user/221108/asa6hhvk.png)

**Comment by scaidermern** [comment] 2022-11-09 06:23
Duplicate of #15627?

**Comment by hakuchi** [comment] 2022-11-09 17:15
Looks similar, but the route is present, but not shown in the correct layer above the map.

According to the specifications of my Moto G7 (Android 10) I have OpenGL

**Comment by sonora** [comment] 2022-11-09 17:23
Sounds exactly like https://github.com/osmandapp/OsmAnd/issues/15627. Disable the Version 2 renderin setting (which seems to come on uncontrolled in some cases), then it should work.

**Comment by hakuchi** [comment] 2022-11-09 17:41
With the Version 1 it works, but sounds strange to me that the route is present under/behind the map.

**Comment by sonora** [comment] 2022-11-09 17:47
I know, but thta's the bug addressed in #15627.

**Closed** 2022-11-09 18:00 UTC
