### ISSUE TITLE
Support 3D buildings

### ISSUE THREAD

**Issue by TobiPeterG** [osmandapp/OsmAnd#20909] opened 2024-09-26 09:22 UTC
### Describe the idea

Hi there,

Apps like Google Maps, Magic Earth or Organic Maps support showing 3D buildings.
Is something like this possible for OSMAnd as well?

### Expected behaviour

3D buildings are shown on the map

### Alternatives you've considered

No 3D buildings, though not looking that nice

**Comment by scaidermern** [comment] 2024-09-26 09:37
Duplicate of #14864 (I've just improved title/content of this issue so that it can be found easier).

**Closed** 2024-09-26 11:01 UTC
