### ISSUE TITLE
Lane guidance broken in nightly build 2.7.0 #21903M

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#4010] opened 2017-07-02 06:14 UTC
What version of OsmAnd are you using, on what device and Android/iOS version?

Using nightly build 2.7.0 #21903M,released 2017-07-01 on Samsung Galaxy S4, Android 4.2.2

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Using my own US Georgia map built using osmandMapCreator and the June 30 download from Geofabrik, and your US Florida map dated May 31.

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

Using OsmAnd routing

What routing profile is choosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car profile

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also a permalink from openstreetmap.org can be helpful.

Trip from Atlanta area to a suburb of Tampa. To reproduce, you can just use the city nodes for those cities. 

I 75 lane guidance south of Atlanta is pretty complete all the way to the Florida border. Lane guidance in Florida is mostly incomplete except for a few exits in north Florida, until you get to the Tampa area. From the I 275 junction down to the Gibsonton exit, I 75 lane guidance is very good. 

The night builds from about a month ago gave proper lane guidance on the same trip. I will note that more recent night builds have given some odd lane guidance when driving in different areas, but i haven't had the time to work out how to report those. Now it appears to be completely broken. (Note: at the very end, after i had exited the freeway and was almost at my destination, it did give lane guidance on one of my final turns.)

** Edited to correct some typos.  I blame Otto Koreckt.

**Comment by jfburke3** [comment] 2017-07-02 06:24
And by lane guidance broken, i mean that the helpful little arrows that pop up to show you what lanes to be in do not helpfully pop up.

**Comment by sonora** [comment] 2017-07-03 11:07
May have the same root cause as #4011.

**Comment by vshcherb** [comment] 2017-07-03 15:43
I guess it doesn't happen in release version so we can find what's the issue quick.

**Comment by vshcherb** [comment] 2017-07-03 15:53
The issue discovered related to Core changes

**Comment by jfburke3** [comment] 2017-07-03 16:20
As far as I can tell, the last release version works fine.

**Comment by jfburke3** [comment] 2017-07-03 16:23
Let me know when it's available in a new nightly build, and I'll be happy to give it a thorough test.

**Comment by polarbearing** [comment] 2017-07-03 16:30
As said in 4011, I had the problem in 2.7.0#21876M/2017-06-28

**Comment by sonora** [comment] 2017-07-03 16:46
Introduced on 2016-06-27, I guess with this commit: https://github.com/osmandapp/OsmAnd-core/commit/fab567ef9236178902e4426194d94041dc3ce33b

**Comment by crimean** [comment] 2017-07-04 14:07
Fixed by https://github.com/osmandapp/OsmAnd-core/commit/48933fcb623fdbee5be23526b896bafde66af50a

**Closed by crimean** 2017-07-04 14:07 UTC

**Comment by jfburke3** [comment] 2017-07-05 06:09
Just to close the loop on this, I installed nightly build 2.7.0 #21943M, and both lane guidance and freeway exit directions appear to be working fine now.
