### ISSUE TITLE
OSM Notes Plugin: Offline edits not accessible.

### ISSUE THREAD

**Issue by 9662** [osmandapp/Osmand#1414] opened 2015-06-27 19:23 UTC
Using OsmAnd~ 2.1.0, if I create an OSM note while having "Offline editing" enabled, there is no way to subsequently upload the notes.

Clicking on "Locally saved OSM POIs/Notes" shows the "My Places" list with three "tabs": My Favourites, My Tracks, Notes.

Under Notes, I have some photos that I took from within OsmAnd, but no notes.

If I enable display of OSM bugs on map settings, my notes can be seen and I get the option to add comment / delete / etc., but no way to upload them. :(

**Comment by vshcherb** [comment] 2015-08-03 22:59
You should see another tab OSM Changes. Please scroll right, it might be hidden? Or restart the app.

**Comment by vshcherb** [comment] 2015-08-03 23:24
Actually managed to reproduce this issue, the workaround is only to restart the app. And the issue is fixed in nightlies.

**Closed by vshcherb** 2015-08-03 23:24 UTC
