### ISSUE TITLE
Crash when opening a photo in Mapillary

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16729] opened 2023-03-17 14:33 UTC
### Description
Crash when opening a photo in Mapillary
[exception (38).log](https://github.com/osmandapp/OsmAnd/files/11002364/exception.38.log)

### Steps to reproduce
Find this place `48.36582° N, 10.89973° E` (for example) > Open photo

### Actual result
Crash

https://user-images.githubusercontent.com/104760013/225933864-e9fa960e-5e5b-4985-ac2b-c8519403ca25.mp4

### Expected result
Mapillary photo is open

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14249mqta, Released: 2023-03-17
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Chumva** [comment] 2023-03-23 09:53
Duplicate of https://github.com/osmandapp/OsmAnd/issues/16763

**Closed by Chumva** 2023-03-23 09:53 UTC
Labels: and-bugs

**Comment by Zirochkabila** [comment] 2023-03-25 16:12
OsmAnd~ 4.5.0#14270mqta, Released: 2023-03-25
Done
