### ISSUE TITLE
Unreadable text with night mode

### ISSUE THREAD

**Issue by ciseur68** [osmandapp/OsmAnd#13151] opened 2021-11-11 10:38 UTC
### Description
Hello, the text describing the types of roads and surfaces for a route is black over a grey background when the night mode in active. It should be white in order to be readable.

### How to reproduce?
Turn on night mode, plan a route and check the types of route and surface.

### Your Environment
OsmAnd Version: fdroid 3.9.10
Android/iOS version: android 11 RKQ1.200826.002
Device model: Xaomi Mi 9 lite

**Comment by dmpr0** [comment] 2021-11-15 10:19
Hello! Thank you for the feedback. 
Please try to update OsmAnd to the latest version. 
If it doesn't help, please attach screenshots.

**Comment by vshcherb** [comment] 2021-11-15 18:26
This is a duplicate of another fixed issue. https://github.com/osmandapp/OsmAnd/issues/12228

**Closed by vshcherb** 2021-11-15 18:26 UTC
