### ISSUE TITLE
Problem with TTS voice

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/OsmAnd#3936] opened 2017-06-17 22:50 UTC
Osmand 2.7.0#17629D offline route And offline maps.
Sometimes TTS voice is distorted but I think there is not a problem on my phone because music sounds good. Anybody has the same problem?

**Comment by sonora** [comment] 2017-06-18 05:39
Almost all TTS engines have a "Listen to an example" button, in the Android (not OsmAnd) settings under Langusge and input / Text to speech options. So that is the first thing you should check to figure out so iif the issue is in OsmAnd or in your device's engine or setup, ok?

**Comment by naoliv** [comment] 2017-06-18 19:18
Sometimes I see this problem too, but from what I have observed, it happens when the phone is under heavy load (high memory and/or CPU usage).

**Comment by sonora** [comment] 2017-06-19 08:18
Perhaps a side effect of some power saving feature throttling CPU speed more than adequate?

**Comment by polarbearing** [comment] 2017-06-19 17:08
On my old, single-core device, I had kind of a stuttering effect (see [old ticket](https://code.google.com/archive/p/osmand/issues/2325)), since OsmAnd and the TTS engine were competing for CPU cycles.

**Comment by OpenSourceForEver** [comment] 2017-06-21 23:25
I do not found any bug on "listen to an example" (tts engine)

**Comment by sonora** [comment] 2020-11-08 07:55
@OpenSourceForEver  When you report 'Sonetimes TTS voice is distorted',  do you mean it changes from prompt to prompt during one navigation (which could indicate a load issue), or is it in some OsmAnd sessions and not in others (which could indicate initialization issues)? I have refined the way how the TTS engine is initiated (in recent nightly), which now solves the old problem that under some circumstances the pronunciation of the device TTS default language was used, which could cause a distortion issue if that language was different from the vioice prompt language selected in OsmAnd. Maybe test once more.

**Comment by OpenSourceForEver** [comment] 2020-11-08 10:31
I think it was a processor power problem, something like @polarbearing said at https://github.com/osmandapp/OsmAnd/issues/3936#issuecomment-309504673

My device had a MediaTek MT 6589T SOC
GPU: PowerVR SGX544 MP

On my current device there is no problem, I did not close this issue because other users had a similar problem

**Comment by sonora** [comment] 2020-11-24 07:10
It looks like there are no recent reports, so let me close this one.

'Distortion' in many cases may have been misinterpreted as when the engine used the wrong accent, e.g. if the system was set to German but OsmAnd set to use Dutch. That I think I fixed, now the OsmAnd setting will be observed if it differs from the system setting.

If there are cpu load issues, I would expect them to occur primarily while other stuff is going on like map rendering while driving and navigation, and not while using the Test voice prompt buttons, so that should be identifiable. Let's see if we get any new issue like that.

**Closed by sonora** 2020-11-24 07:10 UTC
Labels: Observed
