### ISSUE TITLE
Offset when adding POI and notes via quick action

### ISSUE THREAD

**Issue by rbovard** [osmandapp/Osmand#6624] opened 2019-03-06 13:20 UTC
I noticed that in my last modifications and notes, the location of the created points is shifted to the north (~10 m).

I'm currently running OsmAnd+ 3.3.2.

Did someone else noticed that? I can do more testing if needed.

**Comment by francois2metz** [comment] 2019-03-08 22:03
Same for me

**Comment by francois2metz** [comment] 2019-03-10 19:18
Duplicate of #6508

**Comment by rbovard** [comment] 2019-03-11 12:01
Thanks for pointing this out @francois2metz but it's more or less duplicate, since the issue you mentionned concerns favorites.

In fact, it seems that there is an issue with the quick action when adding bookmarks, notes and more seriously **OSM edits**.

**Comment by scaidermern** [comment] 2019-03-11 12:26
I can confirm. This is *not* a duplicate of #6508. OsmAnd shows the correct location when creating the POI/note but after creation the object is shifted roughly 10 meters to the north.

![video_2019-03-11_13-20-34](https://user-images.githubusercontent.com/1040784/54123818-01f4fe80-4401-11e9-9ab9-a9a6aeba35c0.gif)

At the beginning you can see a small circle north of the screen center. For the newly created POI / GPX waypoint OsmAnd shows an orange marker at the center of the intersection. However the POI / GPX waypoint don't get created at the orange marker but at the small circle seen at the beginning.

**Comment by rbovard** [comment] 2019-03-11 12:44
Thanks for your gif @scaidermern.

It seems it takes the center of the screen and not the location of the quick action.

**Closed** 2019-03-14 13:10 UTC
