### ISSUE TITLE
Finding a town takes ages

### ISSUE THREAD

**Issue by keunes** [osmandapp/Osmand#2693] opened 2016-06-13 14:51 UTC
Searching for Gees (NL) takes just under a minute, although it feels longer when you're waiting for the result. In contrast, finding it on osm.org takes miliseconds (forgive the unfair comparison).

On my dad's device this takes even longer, I'll test & report later on.

---
**App version:** 
**OS version**: FPOS 1.3.6 // Android 5.1
**Devide model**: FP2
Offline maps, downloaded The Netherlands as a region.

**Comment by sonora** [comment] 2016-06-13 17:56
Please specify which app version you report this for, because I think this has already been fixed, but not yet released.

**Comment by keunes** [comment] 2016-06-13 18:46
I'm sorry, forgot to add before posting ^^
App version 2.3.5, 2016-04-28

My dad's phone (for him nothing happens at all if you tap 'check villages; the button just disappears'):
Huawei ALE-L21
Android 5.0.1 (EMUI 3.1?)

**Comment by vshcherb** [comment] 2016-06-13 21:33
Just double checked the problem is fixed in latest builds

**Closed by vshcherb** 2016-06-13 21:33 UTC

**Comment by keunes** [comment] 2016-06-13 22:32
Grand, looking forward to the update then :)
Thanks!
