### ISSUE TITLE
OsmAnd Live reporting that there is no update available. Requiring to restart the app.

### ISSUE THREAD

**Issue by tuxayo** [osmandapp/Osmand#6201] opened 2018-10-20 20:24 UTC
Happens to me all the time on one device (haven't used Live since few months before)
I wasn't getting an update although I had made a change few hours before, and the [status timestamp](https://osmand.net/api/osmlive_status.php) was up to date.

It doesn't happen on another device. So now to reproduce I just try update the non-impacted device. If there is an update then I go to the impacted one and try to update, and it never works without a restart.

### Mitigation
- close the app by removing it from the recent apps
- launch it
- retry OsmAnd Live

#### Impacted device
- version 3.2.2
- Phone: Nexus 5
- Android 7.1.2 (LineageOS for microG 14.1)
#### Non-impacted device
- version 3.2.2
- Phone: Galaxy S5
- Android 7.1.2 (LineageOS for microG 14.1)

### Logs
[logcat-before-restart.txt](https://github.com/osmandapp/Osmand/files/2498507/logcat-before-restart.txt)
[logcat-after-restart.txt](https://github.com/osmandapp/Osmand/files/2498508/logcat-after-restart.txt)

**Comment by scaidermern** [comment] 2018-10-22 07:02
I had the same issue two times already. OsmAnd reported that there are no updates available although the last update was several hours ago and there definitely has been new data. Force-closing OsmAnd and restarting it solved the problem and new updates could be downloaded immediately.

So far I have also no idea how to reproduce this issue. Looks like this only happens after OsmAnd is running for a while. And maybe only after wifi became unavailable and later available again.

**Comment by scaidermern** [comment] 2018-10-22 09:47
I encountered the same issue two times. OsmAnd live reported no data available although there was new data. Force-closing OsmAnd and restarting it resolved the problem.

Not sure how to reproduce though. So far this only happend after OsmAnd was running for a while, with wifi becoming unavailable and available again.

**Comment by tuxayo** [comment] 2018-10-29 23:17
Indeed on my other device (Galaxy S5), disabling the Wi-Fi when I don't use it **seems** to help reproducing the issue.

On the Nexus 5, even if in range of the Wi-Fi I can reproduce it. Last example was in less than 1h30 (phone being used).

**Comment by prototype99** [comment] 2018-12-12 11:03
i've noticed this on google pixel 2 as well, next time it happens i'll try and take note of any other significant details; i have to restart my phone to fix it. stock android 9 in case that matters.

i have also noticed that sometimes it will say there's an update and i have to keep tapping update now for a while before it says none available, each update is slightly larger than the last so i get the impression it was doing them in chronological order for some reason, although that's just a guess.

**Comment by scaidermern** [comment] 2018-12-27 13:33
Is there anything we can do to provide more information about this bug? It is really annoying.

**Comment by MadWasp79** [comment] 2019-01-30 12:06
@tuxayo @prototype99 @scaidermern  
I made an attempt to fix this issue, but since I was unable to reproduce it, we will need more testing from you. Please try tomorrow's (as of Jan 31) night build and clarify if a bug is fixed or not.

**Comment by MadWasp79** [comment] 2019-01-31 08:39
Closed with https://github.com/osmandapp/Osmand/commit/c634526458346a5f63d6bbb9d45a692b1c5af702

**Comment by prototype99** [comment] 2019-01-31 12:14
i am somewhat unsure of how to safely load the nightly builds. but once the version with the patch (3.3?) comes out i'll be sure to take note if i get it again

**Comment by scaidermern** [comment] 2019-03-04 10:11
@MadWasp79 @vshcherb Is [c634526](https://github.com/osmandapp/Osmand/commit/c634526458346a5f63d6bbb9d45a692b1c5af702) contained in the latest build (aka the emergency release)? If so, the fix doesn't work. The problem persists with OsmAnd 3.3.2.

**Comment by vshcherb** [comment] 2019-03-07 10:26
The problem is still hard to reproduce and we didn't succeed, blind guesses wouldn't work efficiently. we will give a new attempt to get it reproduced.

**Comment by scaidermern** [comment] 2019-03-10 18:21
Maybe you can add some debug output for the nightly version to track down the problem.

**Comment by tuxayo** [comment] 2019-03-20 08:36
Hi, I'm trying with the nightly build.
Is OsmAnd-nightly.apk from https://download.osmand.net/latest-night-build/ the right one?

OsmAnd-default.apk is linked from the main website and actually has the app name containing "Nightly" but I don't have access to OSM Live from this one.

How does one find on which commit a nightly is based on? The short commit hash from in app version doesn't match the latest

**Comment by MadWasp79** [comment] 2019-03-21 08:34
@tuxayo to test OsmAnd live you need to use OsmAnd-nightly.apk. 
About which commit it is built upon - well, it rebuilds after each accepted commit/pull request to the master, but it takes some time, depending on server load.

**Comment by scaidermern** [comment] 2019-03-26 12:13
> Maybe you can add some debug output for the nightly version to track down the problem.

Any news regarding my suggestion? This issue is still present in OsmAnd 3.3.6.

**Comment by MadWasp79** [comment] 2019-03-26 13:51
We are still looking into the issue.

**Comment by MadWasp79** [comment] 2019-04-15 07:19
@scaidermern @tuxayo I added more logging to the code where this issue could originate from, so if it possible, please install nightly build and try to reproduce issue while connected to adb. We will need your logs.

**Comment by scaidermern** [comment] 2019-04-15 07:51
> please install nightly build and try to reproduce issue while connected to adb. We will need your logs.

Which build exactly? https://download.osmand.net/latest-night-build/OsmAnd-default.apk calls itself "OsmAnd Nightly" but has no support for OsmAnd Live. https://download.osmand.net/latest-night-build/OsmAnd-nightly.apk instead fails to install with "App not installed", unfortunately no specific error is mentioned.

**Comment by scaidermern** [comment] 2019-04-16 18:10
This is the output:
```
04-16 20:07:18.688 30499 30499 D net.osmand: PerformLiveUpdateAsyncTask onPreExecute
04-16 20:07:18.689 30499 30499 D net.osmand: PerformLiveUpdateAsyncTask Last update check for Germany_sachsen_europe.obf -> 1555438022917, current check time: 1555438038689
04-16 20:07:18.749 30499 14406 D net.osmand: PerformLiveUpdateAsyncTask doInBackground
04-16 20:07:18.880 30499 30499 D net.osmand: PerformLiveUpdateAsyncTask onPostExecute
```

OsmAnd says the last map change has been at 15:50 which is not true. The current time is 20:07.

**Comment by MadWasp79** [comment] 2019-04-17 11:00
@scaidermern thank you for provided logs. But we need more help from you. Please update osmand-nightly build and get new logs, we hope they will give us insight on the root of this issue.

**Comment by scaidermern** [comment] 2019-04-18 06:09
```
04-18 07:23:15.726 11057 11057 D net.osmand: PerformLiveUpdateAsyncTask onPreExecute
04-18 07:23:15.737 11057 12677 D net.osmand: PerformLiveUpdateAsyncTask doInBackground
04-18 07:23:15.737 11057 12677 D net.osmand: IncrementalChangesManager getIncrementalUpdates(): URL => https://osmand.net/check_live?aosmc=true&timestamp=1555563600000&file=Germany_sachsen_europe
04-18 07:23:15.811 11057 12677 D net.osmand: IncrementalChangesManager getIncrementalUpdates(): list size => 0
04-18 07:23:15.818 11057 11057 D net.osmand: PerformLiveUpdateAsyncTask onPostExecute
04-18 07:23:34.694 11057 11274 W OkHttpClient: A connection to https://osmand.net/ was leaked. Did you forget to close a response body?
04-18 07:23:51.044 11057 11461 W OkHttpClient: A connection to https://osmand.net/ was leaked. Did you forget to close a response body?
```

The requested URL definitely contains elements and is not empty. But looks like OsmAnd isn't able to download it correctly. Maybe the warnings at the end give a clue?

So far it seems like switching wifi off and on again (possibly at a later point in time) helps to reproduce this issue.

**Comment by vshcherb** [comment] 2019-04-18 15:09
Possible fix is ready to test

**Comment by tuxayo** [comment] 2019-05-06 12:13
@vshcherb I can still reproduce on version 3.3.8 from F-Droid. How can one check with release include a given commit?

nightly build: can't test, how does one tests OsmAnd live?

**Comment by scaidermern** [comment] 2019-05-07 16:51
Yes, looks like this bug still exists (3.3.8 from Google Playstore) :(

Can't say whether it occurs less often, though.

**Comment by vshcherb** [comment] 2019-05-08 15:43
@scaidermern do you have logs one more time?

**Comment by scaidermern** [comment] 2019-05-08 19:00
```
[05-08 20:58:15.047 13470:13470 D/net.osmand]
PerformLiveUpdateAsyncTask onPreExecute

[05-08 20:58:15.066 13470:17551 D/net.osmand]
PerformLiveUpdateAsyncTask doInBackground

[05-08 20:58:15.222 13470:17551 D/net.osmand]
IncrementalChangesManager Incremental updates: https://osmand.net/check_live?aosmc=true&timestamp=1557276600000&file=Germany_sachsen_europe, updates 1 (total 111)

[05-08 20:58:15.222 13470:13470 D/net.osmand]
PerformLiveUpdateAsyncTask onPostExecute
```

**Comment by tuxayo** [comment] 2019-05-09 12:09
> Can't say whether it occurs less often, though.

The first time i tried it seems to need more tries to trigger the bug but I'm not sure.
However, now I've found how to trigger the bug easily: Try to reupdate the map again. After a first manual update finishes.

**Comment by scaidermern** [comment] 2019-05-09 16:26
> However, now I've found how to trigger the bug easily: Try to reupdate the map again. After a first manual update finishes.

Yes, this seems to trigger it. Of course there is no new data available after just updating it. However even after hours OsmAnd still reports that there is no new data available.

I've just found out something else: this bug is map-specific! If the bug occurs for a map then trying to update a different map might work. Enabling live updates for other maps (for which live updates aren't enabled yet) also works and OsmAnd is able to download the diff files. Disabling live updates and reenabling them for a problematic map also resolves the bug, OsmAnd will download the newest diff files.

**Comment by tuxayo** [comment] 2019-05-10 11:59
> Disabling live updates and reenabling them for a problematic map also resolves the bug,

Great find!

details of what I just tried:
- have a "locked" map (and which has auto-updates disabled)
- enable auto-updates
- disable auto-updates (no need to wipe existing data)
- try to manually update => it works

No need to restart OsmAnd, thanks a lot @scaidermern :)

**Comment by vshcherb** [comment] 2019-07-01 13:31
@scaidermern we just added even more logging, can you please rerun your test and share your logs so we can see where exactly download is failing. Thanks

**Comment by scaidermern** [comment] 2019-07-03 13:22
I didn't manage to reproduce it with the current nightly so far. Currently I don't have much time to perform additional tests, maybe some other user can jump in.

**Comment by vshcherb** [comment] 2019-07-03 20:14
That's good enough! Thanks everybody, we put logs quite a lot, so in case it becomes again annoying issue I think logs will help us enough

**Comment by scaidermern** [comment] 2019-07-14 20:35
Occured again, OsmAnd 3.4.3.

```
[07-14 22:27:48.679 518:518 D/SurfaceFlinger]
duplicate layer name: changing net.osmand.plus/net.osmand.plus.liveupdates.OsmLiveActivity to net.osmand.plus/net.osmand.plus.liveupdates.OsmLiveActivity#1

[07-14 22:27:49.644 19861:19861 D/net.osmand]
PerformLiveUpdateAsyncTask onPreExecute

[07-14 22:27:49.662 19861:13338 D/net.osmand]
PerformLiveUpdateAsyncTask doInBackground

[07-14 22:27:49.838 19861:13338 D/net.osmand]
IncrementalChangesManager Incremental updates: https://osmand.net/check_live?aosmc=true&timestamp=1563093600000&file=Germany_sachsen_europe, updates 1 (total 113)

[07-14 22:27:49.838 19861:19861 D/net.osmand]
PerformLiveUpdateAsyncTask onPostExecute
```

**Comment by scaidermern** [comment] 2019-09-27 12:51
Bug still occurring with OsmAnd 3.4.8:

```
[09-27 14:48:53.143 519:519 D/SurfaceFlinger]
duplicate layer name: changing net.osmand.plus/net.osmand.plus.liveupdates.OsmLiveActivity to net.osmand.plus/net.osmand.plus.liveupdates.OsmLiveActivity#1

[09-27 14:48:53.931 18342:18342 D/net.osmand]
PerformLiveUpdateAsyncTask onPreExecute

[09-27 14:48:53.952 18342:23149 D/net.osmand]
PerformLiveUpdateAsyncTask doInBackground

[09-27 14:48:54.122 18342:23149 D/net.osmand]
IncrementalChangesManager Incremental updates: https://osmand.net/check_live?aosmc=true&timestamp=1569573300000&file=Germany_sachsen_europe, updates 1 (total 100)

[09-27 14:48:54.122 18342:18342 D/net.osmand]
PerformLiveUpdateAsyncTask onPostExecute
```

**Comment by scaidermern** [comment] 2019-11-05 14:58
Bug still occurring with OsmAnd 3.5.1:

```
[11-05 15:55:22.877 522:522 D/SurfaceFlinger]
duplicate layer name: changing net.osmand.plus/net.osmand.plus.liveupdates.OsmLiveActivity to net.osmand.plus/net.osmand.plus.liveupdates.OsmLiveActivity#1

[11-05 15:55:23.759 28794:28794 D/net.osmand]
PerformLiveUpdateAsyncTask onPreExecute

[11-05 15:55:23.783 28794:3270 D/net.osmand]
PerformLiveUpdateAsyncTask doInBackground

[11-05 15:55:23.835 28794:3270 D/net.osmand]
IncrementalChangesManager Incremental updates: https://osmand.net/check_live?aosmc=true&timestamp=1572941100000&file=Germany_sachsen_europe, updates 1 (total 101)

[11-05 15:55:23.835 28794:28794 D/net.osmand]
PerformLiveUpdateAsyncTask onPostExecute
```

Please reopen...

**Comment by vshcherb** [comment] 2020-01-21 19:21
@scaidermern can you please attach new log once it appears (added more info).
You can use Logcat button inside Development plugin to easy access without adb and other tools

**Comment by scaidermern** [comment] 2020-03-03 17:39
> @scaidermern can you please attach new log once it appears (added more info).
> You can use Logcat button inside Development plugin to easy access without adb and other tools

```
[03-03 18:32:36.750 532:532 D/SurfaceFlinger] duplicate layer name: changing net.osmand.plus/net.osmand.plus.liveupdates.OsmLiveActivity to net.osmand.plus/net.osmand.plus.liveupdates.OsmLiveActivity#1
[03-03 18:32:37.625 7486:7486 D/net.osmand] PerformLiveUpdateAsyncTask onPreExecute
[03-03 18:32:37.644 7486:21031 D/net.osmand] PerformLiveUpdateAsyncTask doInBackground
[03-03 18:32:37.747 7486:21031 D/net.osmand] IncrementalChangesManager Incremental updates: https://osmand.net/check_live?aosmc=true timestamp=1583218200000&file=France_new-aquitaine_europe, updates 1 (total 101)
[03-03 18:32:37.747 7486:7486 D/net.osmand] PerformLiveUpdateAsyncTask onPostExecute
[03-03 18:32:37.748 7486:7486 D/net.osmand] PerformLiveUpdateAsyncTask Updates quantity: null
```

Btw. I'm using the app Logcat Reader. The logcat from the development plugin looks broken, it doesn't contain the above lines (I tried all log levels).

**Closed** 2020-03-25 10:58 UTC

**Comment by vshcherb** [comment] 2020-03-25 10:59
The problem was very tricky and it was happening if the app wasn't restarted for 10 days and updates were coming and accumulating though it is fixed (extra check) is deleted. It is still recommended to notify us if you see any issue with such updates and restart
