### ISSUE TITLE
Turn lane assist errors

### ISSUE THREAD

**Issue by skylerbunny** [osmandapp/Osmand#3347] opened 2016-12-14 19:08 UTC
Now that #3052 is fixed, another couple smaller errors have made themselves obvious.

Routing from (47.3978387, -122.2920164) to (47.3958035, -122.2985595):

1. While on segment 265726357, turn:lanes is ( ||||through;slight_right|slight_right )
 a. Given assistance is (no | no | no | no | no | slight_right )
 b. Expected assistance is ( no | no | no | no | slight_right | slight_right) - in other words, both lanes should be suggested since they both contain the same arrow suggestion, even though one is a combination arrow.

2. After turning from segment 234663067 to 286359390, an upcoming turn:lanes (on segment 265002601 is ( left|left| ) ).
  a. Given assistance is  (left | no | no ). A 'turn left' vocal instruction is not given, but the lane assist highlights that left turn lane.
  b. Expected assistance is ( no | no | through ). This is particularly true since once the driver passes node 2713506156, the left turn instruction clears, and now (correctly) tells the driver to be in the through lanes to proceed through the upcoming intersection. The aforementioned was fixed by #3052.

Apologies if any of this is unclear; if clarification is needed I'll be happy to do my best to provide it.

**Comment by hakuchi** [comment] 2016-12-14 21:11
There are no voice prompts for left/right turn lanes:
_use left lane_, _use right lane_, _use slight left lane_ or similar
because some [motorway](https://www.openstreetmap.org/way/279951413) is splitting in a Y-junction into two motorways([1](https://www.openstreetmap.org/way/53837960)|[2](https://www.openstreetmap.org/way/143184790)), but on these turn lanes are no voice prompts.

**Comment by xmd5a2** [comment] 2017-01-13 14:04
Test added

**Comment by vshcherb** [comment] 2017-01-19 00:09
The issue is duplicate to what already fix (forgot the number, please add link if someone knows). The restriction is missing, it should be forbidden to turn right from (way 222243, left|left|through|through, South Kent Des Moines Road, http://www.openstreetmap.org/way/265002602) to Pacific Highway South . 
@xmd5a2  Please add relation restriction and the test should be fixed.

**Comment by skylerbunny** [comment] 2017-01-19 01:46
The issue vscherb refers to is #3052  , which I reported myself and which was properly fixed in osmand. The restriction requested is http://www.openstreetmap.org/relation/6596913 which has been in place for four months.

That said, this is a completely different problem, involving 'osmand' offline navigation and the in-app 'lanes' alerts which appear when one navigates using that navigation method. Those alerts use the 'turn:lanes' keys and values.

In the original stated issue above in #3347, (2), I am saying that although no turn instructions are given (and in fact the correct instruction or lack thereof, 'continue straight', applies thanks to the fix in #3052 ), the _lanes alert_ is suggesting the driver be in a left turn only lane, which makes no sense.

**Comment by skylerbunny** [comment] 2017-03-22 18:53
![2017-03-21 16 22 19](https://cloud.githubusercontent.com/assets/6234406/24215443/025a3814-0ef6-11e7-8ab5-cb9d4053970d.png)
![2017-03-21 16 22 26](https://cloud.githubusercontent.com/assets/6234406/24215453/0775d22c-0ef6-11e7-97a5-1ae115caf30f.png)
![2017-03-21 16 22 35](https://cloud.githubusercontent.com/assets/6234406/24215455/0a6b818e-0ef6-11e7-95bf-5ff70efc5df3.png)

Uploaded three images to visually describe the problem. In the second of the three, a person is told to get into the 'rightmost left turn lane' and they shouldn't be, since the next lanes instruction is to get into the straight-ahead lane.

**Comment by vshcherb** [comment] 2017-03-30 21:04
@hakuchi in your example there is a split from motorway -> motorway, motorway_link. These interesctions are not speakable if you keep riding motorway in most of the cases it is intended behavior though it might not be in that case. The solution could be to switch small segment to motorway or to motorway_link

**Comment by vshcherb** [comment] 2017-04-03 16:05
Some improvements has been made (so it fixes several issues). Though main issue unfortunately not possible to fix for now
http://www.openstreetmap.org/way/265002601
This road splits into segments: main road and turn right. Unfortunately neither of lanes "left|left|straight" indicates right road segment. This is not supported by algorithm. 

Shortly saying, if turn_lanes="left|left|straight;turn_right" (which reflects reality but slightly differs from the ground truth), then the bug is fixed and OsmAnd will correctly display "TL|TL|+C;TR" and so on. Otherwise that issue will stay as it is.

**Closed by vshcherb** 2017-04-03 16:05 UTC
