### ISSUE TITLE
Hungarian - Voice prompts

### ISSUE THREAD

**Issue by d4f5409d** [osmandapp/OsmAnd#17479] opened 2023-06-22 08:02 UTC
### Description
This is a list where I collect the voice navigation issues in the hu language. I tested the voice navigation both in action and in developer mode.

Connected issues: #17478

3.7, 3.8, 3.9 and 3.10 are missing "kijárat" from the end which is the hungarian word for exit.
In the sentence wit should look like "kijáraton".
_Note that 3.11 and 3.12 also missing this word, but we can't do much about that because it is a non TTS version so it can't tell about the custom exit the user._ 

_5.2 : Just a little note, it would sound better to say "hajts ki az x. kijáraton" instead of the current order of the words in the sentence._

5.3: Exit is again missing "hajts ki a második (2.) **kijáraton**"

_6.1: would sound better: "fordulj vissza x méter múlva" instead of the current one because it means the same and it is shorter._ --> I noticed an inconsistency between 6.1 and 6.2, 6.3; in 6.2 and 6.3 it's great.

_6.4: I would put "lehetséges" to the end of the sentence instead of current "lehet", it sounds better._

_**I had this much time currently, I will update this issue with more stuff as soon as I can. Stay tuned!**_

### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: 13.1
Device model: OnePlus 8

**Comment by d4f5409d** [comment] 2023-08-12 19:40
Oh boy, there are huge I meam HUGE problems with this. The navigation misses so much regarding voices. Sometimes it just forgets to say what turn is ahead.

**Comment by d4f5409d** [comment] 2023-08-13 17:10
Okay, I'm browsing the files you mentioned, and I have to repeat, there's a problem with the pre-recorded voices, rather than the TTS. The TTS works perfectly every time. But since I am degoogled, I can't use TTS (because there aren't FOSS TTS engines that support the Hungarian language)

**Comment by sonora** [comment] 2023-08-14 05:52
Regarding
 > The TTS works perfectly every time. But since I am degoogled, I can't use TTS 

According zo https://accessibleandroid.com/list-of-languages-with-available-tts-engines-on-android/, there should be quite a few options for Hungarian TTS support?

**Comment by d4f5409d** [comment] 2023-08-14 15:00
> Regarding
>  > The TTS works perfectly every time. But since I am degoogled, I can't use TTS 
> 
> According zo https://accessibleandroid.com/list-of-languages-with-available-tts-engines-on-android/, there should be quite a few options for Hungarian TTS support?

Thank you for helping me (it's unrelated to the issue), but pretty much from all of it is espeak usable, but it sounds terribly.

**Comment by sonora** [comment] 2023-08-14 16:32
Have you downloaded a good Hungarian voice for it? This psge here sounds like Hungarian  should be past experimental: https://espeak.sourceforge.net/languages.html

**Comment by d4f5409d** [comment] 2023-08-14 16:33
I checked 2, but I am sure all of them suck.

**Comment by sonora** [comment] 2023-08-14 17:02
Not sure I can help much with recotded voices: The configuration work is much the same we have to do for TTS. And in the end we likely need to create new recordings. So if you have a pull request, welcome to post it. If you have specific questions, leg me know, I will gladly assist.

**Comment by d4f5409d** [comment] 2023-08-14 19:51
I am only a user with barely any coding knowledge :/ however thanks for the assist

**Comment by sonora** [comment] 2023-08-14 22:09
I have tested a few of the examples you state above, and they seem to sound like they should, e.g. (5.3) sounds like "hajts ki a második kijáraton".

Which version of OsmAnd are you using? Please delete the hu voice and re-download it to make sure you have the latest. If the issue is still around, can you specify for a few test buttons exactly what you hear vs. what you expect to hear?

**Comment by sonora** [comment] 2023-08-16 16:10
Please download the latest "hu" recorded vice - I had made an update to all recorded voices about 6 months back, I remember there were issues with e.g. the "exit" portion.

For whatever is still present then, I think we should go through some selected test buttons, and you simply write what you hear, and what you would like to hear. And wherever it involves the same vocabulary (which is already recorded), I may be able to fix it with your help and with limited effort. 😉

**Comment by sonora** [comment] 2024-06-18 06:26
Let me close this as deprecated. For new findings we should open a new issue please.

**Closed by sonora** 2024-06-18 06:26 UTC
