### ISSUE TITLE
Cycle route node not displayed

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#6963] opened 2019-05-21 11:00 UTC
https://www.openstreetmap.org/node/41903536#map=18/50.76557/5.73329&layers=C
![photo_2019-05-21 13 58 32](https://user-images.githubusercontent.com/9365308/58090770-b618bf80-7bd0-11e9-87f7-773c49a9b19a.jpeg)
![photo_2019-05-21 13 58 40](https://user-images.githubusercontent.com/9365308/58090771-b618bf80-7bd0-11e9-827a-24b9edb55809.jpeg)

**Comment by scaidermern** [comment] 2019-05-29 06:19
Regression of #6844?

**Comment by footils** [comment] 2019-05-30 10:16
Are  you sure, #6844 is even active in your Osmand-install? you can check default.render.xml to see if it has the changes of #6844 inside.

**Comment by vshcherb** [comment] 2019-07-09 15:49
Проблема в коммите https://github.com/osmandapp/OsmAnd-resources/commit/db5dcf00c89c0c9229d0b796045c4de10254c8f2
Он меняет источник текста для cycle nodes на *cn_ref, чтобы вместо этого не отображалось имя маршрута, если точка в него входит. Но это работает только в OpenGL движке, а не в android.
Две точки, первая входит в отношение, вторая нет (synthetic test rendering):
1)Point types [rcn_ref (232), route-bicycle (108), route_bicycle (84)] Names [rcn_ref(232) - rcn_ref-rel2] id -94660 osmid -740
2)Point types [rcn_ref (232)] Names [rcn_ref(232) - rcn_ref-node] id 1659744 osmid 12966
Код стиля
<case tag="rcn_ref" value="" nameTag="rcn_ref" textOrder="38"/>
в старом движке отображает только текст с точки 1)
Получается что nameTag="rcn_ref" работает для точки, входящей в relation, но не работает для точки без relation. Тип данных в obf map идентичен.
То есть коммит фиксит одну проблему, но создаёт другую, причем только в старом движке.

**Comment by matthijskooijman** [comment] 2019-08-15 11:46
At first glance, this might be a duplicate of #5686, which also reported some missing cycle nodes last year.

However, I've also noticed *all* cycle nodes (rather than just the occasional one as in #5686) in my region have gone missing. Looking closer shows that they are displayed in some regions in the Netherlands, but not all. e.g. https://www.openstreetmap.org/node/44686124 is displayed, but https://www.openstreetmap.org/node/44739394 is not. They are in different route network relations, so I suspected this might be relevant, but I could not find any structural difference between both networks. On closer inspection, I noticed that the one that *is* displayed is part of a cycle route (not just a route network), and the one that is *not* displayed is not. I think this is also what @vshcherb is saying (with some help from Google Translate...).

What is weird, is that the example in the original post does *not* conform to this pattern (both node [78](https://www.openstreetmap.org/node/41906570) and [100](https://www.openstreetmap.org/node/41903536) are *not* part of any route relation (though they both *are* part of ways that are part of route relations...). However, looking at my own OsmAnd, I cannot actually reproduce the testcase from the original post, both 78 and 100 are hidden here. However, the nearby node [421](https://www.openstreetmap.org/node/5056986031) *is* shown for me, even though that node is not part of any route relation either. However, it is part of a [network relation](https://www.openstreetmap.org/relation/377995) that has (incorrectly?) set `route=bicycle`, like other route relations, so maybe that is it. For extra confusion, node 100 is *also* part of this same network (but not 78), but it is not shown...

![image](https://user-images.githubusercontent.com/194491/63092721-ee773200-bf62-11e9-9382-62b201e4164a.png)

All my testing is with OsmAnd 3.4.6, with live maps enabled.

**Comment by Harribo19** [comment] 2019-11-12 11:03
Bike/cycle nodes (aka fietsknooppunten)
are still missing in the ENTIRE Netherlands. 
Very annoying. It was good for years. I use Osmand+ now for 10(?) years. 
Why suddenly did they disappear? Why?

**Comment by vshcherb** [comment] 2019-11-21 20:28
@Harribo19  they are not missing completely, they are missing in case there is multiple relations on the same point i.e. hiking and cycling. 
You need to enable either cycling style or hiking option to see one of them, we're still working to show them when point has multiple names on it.

**Comment by Harribo19** [comment] 2019-11-22 09:08
Hi
Thanks for your answer.
They were missing but they are back with the latest beta update(s).

For now this is solved, thanks.

People are most doing one thing at a time: hiking or cycling.?

Success and Regards
Harribo

Verzonden door TypeApp<http://www.typeapp.com/r?b=15723>
Op 21 nov. 2019, om 21:28, vshcherb <notifications@github.com<mailto:notifications@github.com>> schreef:

@Harribo19<https://github.com/Harribo19> they are not missing completely, they are missing in case there is multiple relations on the same point i.e. hiking and cycling.
You need to enable either cycling style or hiking option to see one of them, we're still working to show them when point has multiple names on it.

**Closed** 2020-01-13 16:29 UTC
