### ISSUE TITLE
Wrong elevation on widget

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#19147] opened 2024-02-19 23:02 UTC
Wrong elevation data is displayed on elevation widget (top right corner).
Widget 49m ... Map 1548m
Map is correct.!
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/623412/003844a2-bc00-4b2d-beec-eaed3e265db6"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment] 2024-02-20 10:49
Kindly clarify whether you have activated the World altitude correction by navigating to Menu -> Download maps -> World altitude correction.

Additionally, please specify the accurate elevation for the location and provide its coordinates. Also I recommend testing the beta version to see if the issue persists there. You can access the beta version at https://osmand.net/docs/versions/nightly_versions#google-play-beta-builds.

**Comment by CJTmmr** [comment] 2024-02-20 16:52
See also: Altitude Widget does not work https://github.com/osmandapp/OsmAnd/issues/19054.
It was a typo: Latitude instead of Altitude was displayed in the widget. Fixed in next rekeare

**Comment by miramikes** [comment] 2024-02-20 20:17
> See also: Altitude Widget does not work https://github.com/osmandapp/OsmAnd/issues/19054.
> It was a typo: Latitude instead of Altitude was displayed in the widget. Fixed in next rekeare

It will be very probably the same issue ...

**Comment by sonora** [comment] 2024-02-20 21:24
Duplicate of https://github.com/osmandapp/OsmAnd/issues/18998, fixed already.

**Closed by sonora** 2024-02-20 21:24 UTC

**Comment by Sebf69** [comment] 2024-03-11 06:00
M'y elevation IS Always a 45m on altitude widget, even if i'm at 1000m or 2000m
