### ISSUE TITLE
CRASH immediately on start.

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#18980] opened 2024-01-30 10:27 UTC
### Description

See title

### Steps to reproduce

Just start

### Actual result

 crash

### Expected result

No crash

### Your Environment (required)

OsmAnd Version: OsmAnd~  4.7.0#1463m.apk 2024-01-30 10:02, OsmAnd-android-full-arm64.apk, OsmAnd-android-full-arm.apk

Android version: 10
Device model: Device Samsung tab S5e
Crash-Logs: no log written

**Comment by pebogufi** [comment] 2024-01-30 12:27
NOT fixed with OsmAnd~ 4.7.0#1469 11:47

**Comment by yuriiurshuliak** [comment] 2024-01-30 13:38
Unfortunately, this crash is not reproduced from my side, when starting the application. Please attach Crash logs files after application crash: Menu → Help → Send crash log (Send logcat log)

If you cannot specify Crash logs files, attach tombstone files: https://osmand.net/docs/user/troubleshooting/crash-logs#send-tombstone-files-android-only

**Comment by pebogufi** [comment] 2024-01-30 14:26
I rebooted device
Cleared cache
ReinstalledOsmAnd~ 4.7.0#1469
Started app
-> crash
Created bug report
Without doing something else between theese steps.
Hope it helps.

[dumpstate-2024-01-30-15-19-35.zip](https://github.com/osmandapp/OsmAnd/files/14099613/dumpstate-2024-01-30-15-19-35.zip)

**Comment by pebogufi** [comment] 2024-01-30 14:35
Same crash with OsmAnd~ 4.7.0#1469 without crashlog
On Samsung S10
Android 12

**Comment by pebogufi** [comment] 2024-01-31 07:47
Same Crash with 
OsmAnd~  4.7.0#1479m.apk (OsmAnd-android-full-arm.apk)
2024-01-31 02:26

**Comment by vshcherb** [comment] 2024-01-31 09:03
Investigating it... Hopefully fixed soon will get back to you

**Comment by sonora** [comment] 2024-01-31 19:29
Same crash here since 2 days ago, and including the latest build right now. Last build without the crash is of just before midnight on 2024-01-29.

**Comment by Chumva** [comment] 2024-01-31 19:35
@sonora can you provide exception logs?

**Comment by sonora** [comment] 2024-01-31 19:41
@Chumva I've checked, I have the same situation as described above, there is no exception.log file created...

**Comment by sonora** [comment] 2024-01-31 19:48
I am on the road right now  no acces to Studio or smilarr. Can only try what I can do with the phone and app itself.

**Comment by Corwin-Kh** [comment] 2024-01-31 20:03
have an idea of possible cause of crash. will provide new fix soon

**Comment by Corwin-Kh** [comment] 2024-01-31 21:13
Fix merged to master

**Comment by sonora** [comment] 2024-01-31 21:27
Works, no crash! Well done, good job, thanks!

**Closed** 2024-01-31 21:27 UTC
Labels: and-bugs

**Comment by pebogufi** [comment] 2024-02-01 08:00
Confirm fixed, thanks a ot 😃
