### ISSUE TITLE
Route line disconnects from current position

### ISSUE THREAD

**Issue by Davi427** [osmandapp/OsmAnd#21133] opened 2024-10-24 09:11 UTC
### Description

The route line is no longer connected to the current position, sometimes in city driving it means the route line is entirely invisible. 
Yellow arrows are still shown but depending on map colours may be invisible.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/f99b4ec2-b182-4ea1-9f50-b856b946042c"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Enter route, drive. Sometimes it happens after recalculation route, other times it just happens without apparent reason.

Exiting osmand completely and reopening it usually resolves the issue. Not ideal while driving.

### Actual result

See screenshot above

### Expected result

See the route line, connected to the current position. 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.9.0, Released: 2024-09-04
Android/iOS version: 14
Device model: Fairphone 5
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment] 2024-10-24 14:54
This issue seems to be a duplicate of https://github.com/osmandapp/OsmAnd/issues/20941 
Could you please try nightly version and see if it is working now? https://osmand.net/docs/versions/nightly_versions#nightly-builds

**Closed** 2024-10-28 12:08 UTC
