### ISSUE TITLE
Online trip recording stopped working

### ISSUE THREAD

**Issue by agturcz** [osmandapp/OsmAnd#12727] opened 2021-09-09 18:05 UTC
### Description
Online trip recording from "Trip recording" plugin stopped working on one device. It started working after forcefully stopping the Osmand and running it again.
I am attaching an archive with two logcat files, one with error manifesting before the cold restart of the app and one when it is OK.

### How to reproduce?
Unknown/non-reproducible.

### Your Environment
OsmAnd Version: OsmAnd+ 4.0.7
Android/iOS version: Android 11
Device model: Samsung Galaxy S20 FE

**Maps used (online or offline):**   
Not relevant, I believe.
[logcat.zip](https://github.com/osmandapp/OsmAnd/files/7138820/logcat.zip)

**Comment by scaidermern** [comment] 2021-09-10 12:30
I had the same behavior multiple times. I think it can be reproduced this way:

- Start OsmAnd
- Add one or more GPX waypoints
- Start recording

OsmAnd will start recording a track but will stop as soon as the display is off. It will continue after switching the display on. Also, the track recording notification is only visible if OsmAnd is in the foreground.

This situation can be resolved by either forcefully stopping and restarting OsmAnd, or by stopping track recording and starting to record a new track.

I think the problem is that OsmAnd won't start the foreground service that is required for track recording if there is already a non-empty "current track" present. OsmAnd then thinks that the foreground service already exists although it doesn't.

**Closed** 2021-09-19 17:53 UTC
