### ISSUE TITLE
Redundant navigation instructions when multiple maps for the same area are installed

### ISSUE THREAD

**Issue by icke68746** [osmandapp/OsmAnd#20939] opened 2024-09-27 18:42 UTC
### Description

I've encountered an issue with OsmAnd where redundant and unnecessary navigation instructions are given when multiple maps covering the same region are installed. For example, when driving in the Sauerland region, I had both the Germany map and the NRW (North Rhine-Westphalia) regional map installed. OsmAnd would frequently give unnecessary instructions such as telling me to "keep left" or "keep right" even when there were no changes in the road direction or lanes.

After discussing the issue in the OSM forums (https://community.openstreetmap.org/t/osmand-sinnlose-navigationsansagen-wie-abschalten/119125/17), I discovered that having multiple maps for the same area (e.g., Germany and NRW) installed at the same time causes conflicts that lead to these redundant instructions.

### Steps to reproduce

Install the Germany map and a regional map (e.g., NRW) that covers the same area.
Plan a route through a region where both maps overlap.
Follow the navigation instructions, and observe unnecessary prompts like "keep left" or "keep right" when the road continues straight.
Expected behavior: OsmAnd should handle overlapping map data without causing redundant or incorrect navigation instructions.

### Actual result

Many nonsensical driving instructions, even though you are supposed to follow the road, for example.

### Expected result

 OsmAnd should handle overlapping map data without causing redundant or incorrect navigation instructions.

### Your Environment (required)

This issue was resolved by uninstalling one of the maps (e.g., NRW or Germany). However, it would improve user experience if OsmAnd could manage multiple maps for the same area more effectively.

OsmAnd Version: 4.8.5
Android version: 14
Device model: Samsung A53
Crash-Logs: no
```

**Comment by scaidermern** [comment] 2024-09-28 06:08
Related to #15039

**Comment by yuriiurshuliak** [comment] 2024-09-28 08:15
Duplicate of #20133

**Comment by vshcherb** [comment] 2024-10-05 21:05
It's not a duplicate of https://github.com/osmandapp/OsmAnd/issues/15039 but a variation. If you have same maps installed of the same date that won't be an issue. However if your data is not consinstently up to date it starts causing multiple issues. With new routing it's even worse cause it's required to have same maps date for the whole route

**Closed by vshcherb** 2024-10-05 21:05 UTC
