### ISSUE TITLE
3D Relief doesn't work at close zoom range. 

### ISSUE THREAD

**Issue by jrzelazny** [osmandapp/OsmAnd#18253] opened 2023-09-29 23:10 UTC
### Description

I am unable to use the 3D Relief feature when the map is zoomed in, such as when navigation.

I have the most recent version of Android. Most recent version of OsmAnd+ and a Pro subscription. I have deleted and reloaded maps. I have deleted and redownloaded the app. Problem still persists.

I have four different Android devices, Samsung Galaxy S21 Ultra, Samsung Galaxy S10, Samsung Galaxy Tab S6, Kyocera Duraforce Pro 2. The behavior is exactly the same on all four devices. I checked with a friend who also has a Pro membership. He has a Google Pixel and a tablet of unknown make. He told me his app does exactly the same thing.

The map shows the proper 3D relief when zoomed out, but when zoomed in, such as when navigating, the screen goes berzerk. It goes blank, shows parts of the map, goes black. If I zoom out again, the screen returns to normal. 

When I turn off the 3D Relief feature, the app performs normally. 

### Steps to reproduce

Turn on 3D relief.

Zoom in on the map screen. 

### Actual result

Screen becomes illegible. Flashing, flickering, going blank. 

### Expected result

I expect to see a 3D relief map when zoomed in.

### Your Environment (required)

It happens on every single Android device I have access to. Everything is up-to-date. 

The app doesn't crash, so I have no crash log. It simply doesn't display the map when the zoom level is zoomed in.

**Comment by DmitryAlexei** [comment] 2023-10-01 18:29
Duplicate of https://github.com/osmandapp/OsmAnd/issues/17763
The development of the fix is already underway

**Comment by jrzelazny** [comment] 2023-10-02 03:49
Thank you. I'm looking forward to the fix. It looks like a great feature!

**Closed** 2023-10-02 10:34 UTC
