### ISSUE TITLE
Navigation with avoiding tolls buggy

### ISSUE THREAD

**Issue by timonoj** [osmandapp/OsmAnd#9822] opened 2020-09-16 12:07 UTC
Hi! I've seem to have had several issues while navigating with "avoid tolls" option on. Seems once the option is on, it fails to accept that I AM ALREADY on a toll road, and keeps jumping to secondary roads, hundreds of meters away, assuming I'm somewhere else. I ended up on a toll road due to bad navigation route, by the way, but it would be hard to replicate the issue. But I noticed it kept refusing to pinpoint my bike to the toll road, just kept jumping around it.

**Comment by Discostu36** [comment] 2020-09-16 12:37
Possible duplicate of #8085

**Comment by vshcherb** [comment] 2020-09-16 19:14
Merged to #8085

**Closed by vshcherb** 2020-09-16 19:14 UTC
