### ISSUE TITLE
Android Oreo: very bad performance

### ISSUE THREAD

**Issue by valynor** [osmandapp/Osmand#4430] opened 2017-09-12 13:08 UTC
Just updated my Nexus 6P to stock Android 8.0.0 "Oreo" which unfortunately made Osmand+ almost unusable: 
-any zooming or panning of the map is **really** slow now and by slow I mean about 3x-5x slower than it was with Android 7.1.2 
-zooming in/out just **one** level takes about 6-7 seconds now and you can see the different layers of the maps being drawn .. slowly
-even something as simple as sliding out the menu from the left is no longer smooth

I'm aware that Osmand+ was never one of the fastest map apps but it was perfectly usable anyway. 
Now it's **very** sluggish and borderline unusable. :-(

Please fix my favourite app! :)

**Comment by scaidermern** [comment] 2017-09-12 13:10
Duplicate of #4323

**Comment by vshcherb** [comment] 2017-09-12 13:11
Duplicate & WIP

**Closed by vshcherb** 2017-09-12 13:11 UTC
