### ISSUE TITLE
The app's language is used even when "local names" is selected as the map language

### ISSUE THREAD

**Issue by miklcct** [osmandapp/Osmand#5866] opened 2018-08-15 10:38 UTC
My app's language is set to English, however, the map language is set the local name.

The local name is shown only when the zoom level is high (with the scale showing 2 km or less), but English is shown in less zoom levels. I expect the local names to be shown under all circumstances.

**Comment by scaidermern** [comment] 2018-08-17 12:49
Duplicate of #4333.

**Closed** 2018-08-19 07:51 UTC
