### ISSUE TITLE
[Bug] Navigation using GPX track don't works

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#4631] opened 2017-10-22 12:58 UTC
When I try to navigate by using a manually entered GPX track, Osmand gives wrong and stupid instructions. Navigation using calculated tracks works fine.

**Comment by Thunichgud** [comment] 2017-10-22 17:29
When I try a previously calculated and stored GPX track it works fine, too. With one exception: First point (my position) is missing.

**Comment by scaidermern** [comment] 2017-10-23 07:06
Can you describe "wrong and stupid instructions" or show a screenshot?

**Comment by vshcherb** [comment] 2017-10-23 07:18
What does it mean manually entered GPX track?

**Comment by vshcherb** [comment] 2017-10-23 09:59
Can't reproduce though we've found small issue with "Save GPX as line" when snap to road is enabled.

**Comment by Thunichgud** [comment] 2017-10-23 11:39
@vshcherb:
"Manually entered GPX track": I created a route/track using the distance meter tool of Osmand (2.8.2) by entering point by point and stored the result as GPX track.
@scaidermern:
"wrong and stupid instructions": E.g. make a u-turn and some meters later again a u-turn where the track goes straight forward. Sorry, I deleted this example. It could be, that "snap to road" during creation of the track was enabled.

**Comment by vshcherb** [comment] 2017-10-23 12:28
@Thunichgud you should create either a very precise route with many points or you should use "Snap to Road" . Otherwise you will get a route as a straight arrows.
The issue with Saving was just fixed in 2.8.

**Comment by Thunichgud** [comment] 2017-10-24 11:50
@VSHCHERB:
You did close this issue to early. You should reopen this issue. 

I recreated the test track and analysed it and some others tracks, too. There are several problems:
1. I created a short test track manually in the west of the town of Bad Doberan / Germany. You will need the map of Germany_Mecklenburg-Vorpommern_Europe to test it by yourself.
- 01-Track creation.png -
While creating this track, I enabled "Snap to Road" and tried to place the points very preciously on the way. The track is about 1400 meter long and has 15 points.
- Test_SnapOnWay.gpx -
When I enabled displaying of this track and startet the navigation with hiker profile using this track, I got the following result of route instructions. You see at the instructions 3 and 4 wrong stupid instructions (U-turn and 8 m later U-turn again). 
- 02-NavigationInstructionsHiker.png
On the map is visible, that at point 10 (the problem area) the track is straight forward. There is no reason for U-turns.
- 04-NavigationProblemArea.png
After Zooming in, the U-turns are visible but there is no visible reason for the U-turns.
- 05a-NavigationProblemAreaZoom.png
When I switched off the navigation and zoomend at the same area, there was visible, that the problem seems to be a part of the GPX track (but see 2.). 
- 05b-NavigationProblemAreaZoom.png
A check of the neighbour points shows, that there is no near neighbour point, which could be the reason for the U-turns. On the following map is the point of the problem area is marked by a green flag. The nearest neighbours are marked by yellow and blue flags.
- 06-NeighbourPoints.png
Deduction: During creation or storing the track Osmand produces an artefact which causes the navigation to give wrong instructions.

2. The senseless U-turns are only produced during use of hiker profile. With car profile these U-turns are not produced in routes. And they are not visible in the displayed GPX route.
- 02-NavigationInstructionsHiker.png

3. I created a similar track (1320 meter, 16 points on the same ways) but without "Snap to Road" enabled. 
- Test_NoSnapOnWay.gpx
The navigation using this track produced a very long instruction list with wrong and stupid instructions. This route had 27 instructions while the similar route with the "Snap to Road" track had only 4 (6) instructions.
- 07-RouteInstructionsNoSnapOnWayA.png
- 08-RouteInstructionsNoSnapOnWayB.png
- 09-RouteInstructionsNoSnapOnWayC.png
- 10-RouteInstructionsNoSnapOnWayD.png
It seems that Osmand didn't use this track but made its own route calculation between the start and the endpoint with a very bad result. I presume this because the route analysis screen shows the mountain profile while routes of handmade tracks usually don't shows this mountain profile.

4. When you compare the very similar GPX tracks with and without "Snap to Road", you will see, that the track without "Snap to Road" don't shows its track length in the track list of Osmand, while the other track shows its length. There must be an error in the file format or something like this.

5. Points are often placed somewhere else outside the center circle. When I try to place a point by using the +Hinzufügen (+Add) button, the point is rather often placed somewhere outside the center circle. This behaviour happens in both cases: "Snap to Road" enabled or not.
- 11-WrongPlacingOfPoint.png

6. Points are often inaccurate connected. The connection line is often hook-shaped. (In both cases).
- 12-WrongConnectionOfPoints.png

7. The simulation of navigation by using manually created GPX tracks don't works. Try it by using my example tracks !! The blue arrow jumps only very short to the destination point and returns at once to the start point. @VSHCHERB: You should reopen the belonging issue, which you closed and deleted two days before.

[ScreenshotsAndGPX.zip](https://github.com/osmandapp/Osmand/files/1410656/ScreenshotsAndGPX.zip)

**Comment by PaulStets** [comment] 2017-12-27 13:38
![26145270_1961503537429784_1102498962_o](https://user-images.githubusercontent.com/20681525/34383150-edfeda34-eb1b-11e7-866c-21cf3b0df367.png)
Hi, I have tested both of your tracks. First of all, please note that the track without 'Snap to road' was saved as route points. This type of tracks does not support displaying the track length and other information. When this type of track is used, OsmAnd calculates the route using the navigation engine, therefore you get a lot of instructions. If you use your first track (with Snap to road) and enable the option 'Calculate route between two points' you will get the same amount of the navigation instructions. Turning this option off will still result in a correct route for me, though the track itself has the strange artifacts on it. (see screenshot 1). I have created the same track using 'Snap to road' in the pedestrian mode and was not able to reproduce the strange turns on the track. I'm attaching a screenshot with my track (in blue) overlayed on your track (in red). Seems like the issue happened because you didn't record the track correctly.
![26179249_1961502400763231_1619781330_o](https://user-images.githubusercontent.com/20681525/34383140-e692616c-eb1b-11e7-95aa-88be17843c9f.png)

**Closed by PaulStets** 2017-12-27 13:38 UTC
