### ISSUE TITLE
During map download/update, OsmAnd spends more time repeatedly reindexing than downloading.

### ISSUE THREAD

**Issue by diggernet** [osmandapp/OsmAnd#18851] opened 2023-12-31 19:19 UTC
### Description

If you have multiple maps installed (or wiki, contours, etc) and do an update or download more, OsmAnd will reindex all installed files after each download.  For example, if you have 20 files installed and want to update them, OsmAnd will download one file, index 20 files, download 1 file, index 20 files, and so on.  This makes updating or adding maps unnecessarily time consuming, as well as having a negative impact on battery life and storage wear.  OsmAnd should delay reindexing until all files are downloaded and perform a single reindex.  If there is some technical reason preventing that (since I don't know exactly what's going on under the hood), then it should at least download in batches, fetching as much as possible between indexing, to minimize the indexing.

### Steps to reproduce

1. Install some maps.
2. Install more maps or update existing maps.
3. Observe behavior.

### Actual result

Lengthy reindexing of all files between each relatively quick file download.

### Expected result

Download all (or many) files before reindexing.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.5.10
Android/iOS version: Android 13
Device model: Nokia XR20
Crash-Logs: N/A
```

**Comment by yuriiurshuliak** [comment] 2024-01-03 15:12
We're aware of this , and it does operate in that manner currently. I recommend updating the app through official platforms and testing its functionality to see if there have been any improvements in this regard.

**Comment by TheSnoozer** [comment] 2024-01-03 21:30
duplicate of https://github.com/osmandapp/OsmAnd/issues/14893

**Closed** 2024-01-05 10:53 UTC
