### ISSUE TITLE
Routing fails completely if Taylor Avenue is anywhere along the route.

### ISSUE THREAD

**Issue by WolfIcefang** [osmandapp/OsmAnd#13720] opened 2022-02-08 18:17 UTC
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Driving, with or without fuel efficiency turned on.

### Start and end points

Whenever OsmAnd tries to calculate a route eastward along Taylor Avenue at the intersection with Meachem road, it fails to calculate the route. The distance to the destination doesn't matter. OsmAnd does not automatically find a different, less optimal route automatically. I have to manually use "avoid road" to make navigation work whenever my destination is vaguely north or east of my house.

The problem is in one of these ways:
https://www.openstreetmap.org/way/509662450
https://www.openstreetmap.org/way/1012167155
https://www.openstreetmap.org/way/1012167153
and it only happens when traveling from the west to the east.
If the navigation would turn onto meachem road the calculation still fails. Even if "eastward along Taylor Avenue" is only one of many options for the route, the calculation will throw an exception (logs indicate an ArrayIndexOutOfBoundsException) and fail both fast and slow navigation.
I've edited this section of the map myself and as far as I know there isn't much special about it; however this isn't the first time I've had trouble with this intersection. I call it "the curse of Taylor Avenue at Meachem" and it's the first place I look when OsmAnd does anything weird. It used to be my testing ground for setting up lane navigation.

### Actual and expected routes

This issue is only west-to-east (not east-to-west)
![image](https://user-images.githubusercontent.com/38160450/153048093-1007a59c-5fcb-4d2d-8073-356698e98b6a.png)

However it occurs regardless of distance (admittedly starting location must be pretty close otherwise OsmAnd will just use a highway.)
![image](https://user-images.githubusercontent.com/38160450/153048213-4af38008-d300-4e02-9af1-92e9e2de55fe.png)

### Is this a regression?

I'm not actually sure if this is a regression or when it started. Until a few weeks ago, literally all of my driving destinations were south or west of my house. For the sake of privacy, I "live" in Sanders park.

## 🌍 Your Environment

**OsmAnd Version:**
OsmAnd+ 4.1.11, released: 2021-12-15
Also F-Droid's OsmAnd~ 4.1.11

<pre><code>

</code></pre>

**Device and Android/iOS version:**
Google Pixel 6 running Android 12.

**Maps used (online or offline):**

I've had the same issue with OsmAnd~'s hourly live tiles and the OsmAnd+ monthly update (currently December 31st.)

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
* I first brought this up in the OsmAnd Matrix room, and user AalEchs replied: "I guess this relation could be the reason: https://www.openstreetmap.org/relation/13550888 No u-turn but from and to are the same ways. This looks wrong. Still a bug if it breaks OsmAnd. OsmAnd should just ignore broken relations."
* I haven't tried editing the map to fix the issue myself.
* The Google Play Store thinks that OsmAnd~ IS OsmAnd+, so I can only have one version of the app installed at a time.
* Online routing services, even the new online routing feature within OsmAnd, all seem to work. (Grasshopper, OSRM, etc.)
* I didn't think to try walking or biking directions. I just realized this.
 
Log file, created after my fresh download of OsmAnd+ today:

[OsmAnd bug.txt](https://github.com/osmandapp/OsmAnd/files/8026408/OsmAnd.bug.txt)
I renamed it to be a txt file so that it could be uploaded to GitHub.

**Comment by xmd5a2** [comment] 2022-02-17 13:12
Can't reproduce "Fast route calculation failed" but if you turn "Fuel efficient way" 
![Screenshot_2022-02-17-16-10-32-069_net osmand plus](https://user-images.githubusercontent.com/5829014/154488730-1ea278d4-48d7-4884-9581-ee96d03189cd.jpg)
option off then OsmAnd will route straight to destination

**Comment by vshcherb** [comment] 2022-02-17 18:24
should be fixed in new maps

**Closed by vshcherb** 2022-02-17 18:24 UTC
Labels: routing
