### ISSUE TITLE
Flooded areas in Australia

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#6944] opened 2019-05-15 08:19 UTC
Devonport
City in Tasmania, Australia
-41.170881, 
146.3410244
https://www.openstreetmap.org/search?query=Devonport#map=14/-41.1776/146.3612
![1](https://user-images.githubusercontent.com/50198677/57759673-11dfd600-7703-11e9-9341-174d6f04ce59.jpeg)

Renison Bell TAS 7469, Australia
-41.7950698, 
145.4389657
https://www.openstreetmap.org/node/2187889657#map=10/-41.8524/145.2962
![2](https://user-images.githubusercontent.com/50198677/57759722-3a67d000-7703-11e9-96c9-ae5e39eab77f.jpeg)

**Comment by katerynakocherhina** [comment] 2019-05-15 08:59
Turners Beach
Tasmania
Australia
-41.1605061, 
146.2429275
https://www.openstreetmap.org/node/671070970#map=17/-41.15992/146.24453
![1](https://user-images.githubusercontent.com/50198677/57762809-d1835680-7708-11e9-9946-3555311c8fdc.jpeg)

**Comment by xmd5a2** [comment] 2019-06-05 13:00
Case with Devonport is duplicate of https://github.com/osmandapp/Osmand/issues/6565

**Closed** 2019-06-08 09:23 UTC
