### ISSUE TITLE
Car-Routing is ignoring turn restriction Relation: 2727832

### ISSUE THREAD

**Issue by Peter0** [osmandapp/OsmAnd#19201] opened 2024-02-28 01:17 UTC
### Describe the routing engine used (required)

- [×] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Car; avoid toll roads

### Describe your start and end points (required)

There are the same as in https://github.com/osmandapp/OsmAnd/issues/17047

### Describe the actual route (required)

Instead of turning left as mentioned in live (right) picture in comment by Zirochkabila on Apr 25, 2023, the router now wants to go ahead some meters, then do a U-turn (violating turn restriction Relation: 2727832) in order to avoid the left turn.

### Describe the expected route (required)

I expect something like mentioned in the left ("Without") picture in Zirochkabila comment.

### Describe what Maps you used (online or offline) (required)

- [×] Offline maps offered within the OsmAnd app for download, as of Feb 2024, live updates active. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: ~4.6.12
Android/iOS version: 9
Device model: Samsung Galaxy J5
```

### Anything else? (optional)

By occasion, I’ll test behaviour without live-updates.

**Comment by Peter0** [comment] 2024-03-01 18:25
The route "No live updates" is perfectly valid. It is the way I'd choose, too. The "With live updates" looks like my reason to complain.

**Comment by vshcherb** [comment] 2024-03-16 16:55
Please retest with live updates and save files @yuriiurshuliak - https://osmand.net/map/?start=50.733841,7.086799&finish=50.732713,7.087630&profile=car#16/50.7338/7.0856 if it displays like that.

If it's not a case the issue is fixed with new routing

**Comment by yuriiurshuliak** [comment] 2024-03-18 17:50
I checked it with live updates, as I see the route is not built the same as shown on the web version. Not building such a big detour.

OsmAnd~ 4.7.0#1859m, released: 2024-03-18

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/72f7c29e-7fc1-4f6a-88ea-3af54f25f631"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/3c17bfd7-19a1-4bef-ae53-a763113fc40b"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by Peter0** [comment] 2024-03-19 01:39
> I checked it with live updates, as I see the route is not built the same as shown on the web version. Not building such a big detour.

The left one is like my reasom-to-complain. The right one looks reasonable. OTG I'd say, choosing the right one or the left one from my original posting is rather a matter of taste.

**Comment by Peter0** [comment] 2024-03-19 02:12
> Please retest with live updates and save files

Is part of the posting addressed to.me?

**Comment by vshcherb** [comment] 2024-03-21 19:18
To do: web version should be the same as android

**Comment by RZR-UA** [comment] 2024-03-28 17:03
More precise Live OBF file with the bug:

8ad227820c852d2e8cbe7a2f11b8e2194d5e42bfc19a3b6f360e9cf762a6acff4b5041a13040df4782e6cfa2b5cc7379bcd21d1b7402e82d07c4a4752ba7f7e3  Germany_nordrhein_westfalen_cologne-government-region_europe_24_03_06.obf (2.5 MB)

[Germany_nordrhein_westfalen_cologne-government-region_europe_24_03_06.obf.zip](https://github.com/osmandapp/OsmAnd/files/14793192/Germany_nordrhein_westfalen_cologne-government-region_europe_24_03_06.obf.zip)

**Comment by ivanPyrohivskyi** [comment] 2024-04-25 14:32
I think problem was with file 24_03_06_17_10_before.obf (deleted at this moment). It was not fully written.
I manually checked live updates and got 2629 objects in routing section.
In original (server) file 24_03_06_17_10.obf present 19891 objects, that is wrong.
I emulated problem by creating empty *_before.obf and got 40762 objects after. So I got conclusion that 24_03_06_17_10_before.obf was really broken.

I noticed that pair of files *_before.obf and *_after.obf has similar size. And suggested request that will monitor such situation in the future.

**Closed** 2024-04-26 07:51 UTC
Labels: live-updates

**Comment by yuriiurshuliak** [comment] 2024-04-26 16:09
The bug has been fixed. The web version and the app are displayed the same.

OsmAnd~ 4.8.0#2184m, released: 2024-04-26

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/3924819b-57c1-47eb-a19d-e4912c4f512d"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Peter0** [comment] 2024-04-27 06:26
🙏
