### ISSUE TITLE
[Feature Request] No Way To Discern From Two Places In Search

### ISSUE THREAD

**Issue by seniorm0ment** [osmandapp/OsmAnd#9695] opened 2020-08-25 22:53 UTC
If I search "Target" (American retail store), I see multiple results.
First of all, there is no way to sort by closest distance

Secondly, there is no way to filter only retail stores, or only street addresses, etc. If you just use the "search all" feature. 

Thirdly, and most importantly, it is not possible to see street names. So if there are two targets, 3.5miles away, I have no clue which is which unless I specifically click on them to look, which is very frustrating.

**Comment by vshcherb** [comment] 2020-09-02 13:34
1. This is a duplicate request - to show address on POI 
2. It is possible to filter only shops: search / select shop and then type "target" it will look like "Shop target"

**Comment by jfburke3** [comment] 2021-01-22 19:59
@vshcherb Finding the stores named Target (a retail chain brand, not a type) isn't the problem.   Knowing which Target store is *where* is the problem. 

If I search for Target in the app, there is no way to know which one is where in the results list.  If I can tell that a specific one is the one on (for example) Cobb Parkway, then that's the one I want to go to, because it's closest to my eventual destination later in the day.

**Comment by scaidermern** [comment] 2021-01-24 08:19
Probably a duplicate of #3327.

**Comment by dmpr0** [comment] 2022-11-28 09:39
https://github.com/osmandapp/OsmAnd/issues/2993

**Closed** 2022-11-28 16:54 UTC
Labels: Nice to Have
