### ISSUE TITLE
[Feature request] Easier Way to calculate a route with intermediate destinations

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#4634] opened 2017-10-22 18:08 UTC
There is no easy way to calculate a route with intermediate destinations. The actual method is rather circumstantial.
Because of that, in the navigation settings screen should be a (+) button which inserts an edit line for entering a intermediate destination with the options of selection from "Favorite", "Mark on map" or "Address".

**Comment by njohnston** [comment] 2017-10-22 20:21
Possible duplicate of #4555.

**Comment by vshcherb** [comment] 2017-10-23 07:19
Short answer, yes it is in a roadmap for next version. Closed as duplicate

**Closed by vshcherb** 2017-10-23 07:19 UTC
