### ISSUE TITLE
Nod missing

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#6990] opened 2019-05-28 13:47 UTC
Netherlands in the municipality of Mierlo (Noord Brabant)
The node 37 is located at the intersection of the Eksterlaan and the Sint Catharinaweg. 
51.44091 longitude 5.60211

But it is absent in OsmAnd.
![image](https://user-images.githubusercontent.com/50198677/58466169-cd602b80-8141-11e9-8096-102740a77c98.png)
![image](https://user-images.githubusercontent.com/50198677/58466182-d224df80-8141-11e9-93e4-155f12a459f4.png)
![image](https://user-images.githubusercontent.com/50198677/58466191-d51fd000-8141-11e9-8cce-0f7da739e2ea.png)

**Comment by njohnston** [comment] 2019-05-28 15:32
Duplicate of #6963?

**Closed** 2019-06-05 07:34 UTC
