### ISSUE TITLE
Osmands data is stored in a different (sub)folders-path using obb or data path

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20150] opened 2024-06-22 07:11 UTC
### Description

When using "external memory 1 or 2" ("data") a "file" subfolder is created, containing all maps and all further (sub)data folders 
When using "multiuser 1 or 2" (obb) all data and subfolders are created directly in the "net.osmand.plus"-folder and only the "tracks"-folder is contained in the "file"-folder (this paths are predefined and can´t be changed by the user).

Is this as it is meant to be?

![Screenshot_20240622_083523_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/95540936/27f448c0-1369-425c-8954-711c46148fa9)

### Steps to reproduce

Have a look at the "files"-folder in this two data storage paths

### Actual result

no "files"-folder is used in the "obb"-path (only for "tracks")

### Expected result

I would expect the same path/subfolders in "obb" as they are created using "data" path.

### Your Environment (required)

I don´t know when this began, it´s in the 4.8.0#2559 and also in the playstores +4.8.0

**Comment by yuriiurshuliak** [comment] 2024-06-24 14:01
Duplicate of #https://github.com/osmandapp/OsmAnd/issues/13404

**Closed** 2024-07-03 20:24 UTC
