### ISSUE TITLE
Flooded islands Stockholm sweden

### ISSUE THREAD

**Issue by davidzx** [osmandapp/Osmand#7252] opened 2019-07-14 12:41 UTC
59.33146° N, 17.72379° E
Whole group of islands flood when zooming out 

Offline maps sweden Stockholm county July 1 2019

![Screenshot_20190714-143214](https://user-images.githubusercontent.com/36261877/61183749-4578a700-a645-11e9-99c3-502fc5498359.png)
![Screenshot_20190714-143227](https://user-images.githubusercontent.com/36261877/61183751-4f020f00-a645-11e9-99f9-53592d7d6091.png)
![Screenshot_20190714-144042](https://user-images.githubusercontent.com/36261877/61183759-6214df00-a645-11e9-8cca-68995774d0ae.png)

**Comment by xmd5a2** [comment] 2019-07-16 06:54
Duplicate of https://github.com/osmandapp/Osmand/issues/6587

**Closed by xmd5a2** 2019-07-16 06:54 UTC
