### ISSUE TITLE
track recording notification remains open terminating the app

### ISSUE THREAD

**Issue by ironspock** [osmandapp/OsmAnd#20676] opened 2024-08-24 16:13 UTC
### Description

Track recording notification remains active/open even in case of no track is/was recorded and app is terminated

### Steps to reproduce

launch and terminate app; track recording notification remains active/open

### Actual result

track recording notification remains active/open, even no track is recorded

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/ba3615fc-58c0-4adc-9015-05a2bc60103a"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/9c087526-8103-4a76-9ae2-53cdb02c75af"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

- track recording notification should only be active in case of active recording and putting app in background
- in case of no active recording and terminating app notification should be disappears as well

### Your Environment (required)

OsmAnd Version:  OsmAnd~ 4.8.5 (F-Droid) 
Android version: 13
Device model: Gigaset GX6

**Comment by yuriiurshuliak** [comment] 2024-08-26 09:13
Duplicate of https://github.com/osmandapp/OsmAnd/issues/20536

**Closed** 2024-08-27 13:08 UTC
