### ISSUE TITLE
Map style for railway/public transport

### ISSUE THREAD

**Issue by euphi** [osmandapp/OsmAnd#18218] opened 2023-09-24 21:52 UTC
### Describe the idea (required)

The available map styles do not show railway lines in zoom level 8 or above.
In level 8, motorways and major country roads are still shown.

For the railway or public transport map mode there should be a map style that show major railway lines in zoom level 5,6,7,8.
It also should use a coloring scheme so that railways lines are better visible than roads.

### Tell us about the expected behaviour (required)

Better visibility of railway lines in railway or public transit mode.

The new style should by default style for these modes.

### Tell us about alternatives you've considered (required)

Have a look at openrailwaymap.org .

**Comment by mikehgentry** [comment] 2023-09-25 03:00
Duplicate of #17373

**Closed** 2023-09-25 19:37 UTC
