### ISSUE TITLE
Routing through bollard with opening_hours

### ISSUE THREAD

**Issue by WebFreak001** [osmandapp/Osmand#5480] opened 2018-05-24 10:32 UTC
Version: OsmAnd 2.9.3 (2018-02-08) with Ultimate upgrade and OsmAnd Live, downloaded maps & live enabled

OsmAnd routing (no avoiding checkboxes, can't tell if offline)

Routing profile: car, fastest

How to reproduce:

Route from lat 50.59577, lon 8.67692 (Egerländer Straße (Nordstadt), Gießen) to lat 50.59462, lon 8.67633 (Asterweg, Gießen) between 08:00-19:00.

Observe that it won't route the obvious direct path, but rather routes a long indirection. I haven't tried this outside that time yet but if the same happens there it is correct behavior on these times.

The direct route has a node `barrier=bollard`, `bollard=rising`, `opening_hours=08:00-19:00` (opening_hours should probably only be interpreted with a rising bollard and not with general barriers https://wiki.openstreetmap.org/wiki/Key:bollard)

Going from top right on this screenshot to bottom left, circle is bollard: ![https://wfr.moe/f15iEz.png](https://wfr.moe/f15iEz.png)

I don't know if this happens because my map is too old? The change to this bollard is around a week old and I don't know another one to test. The Interface doesn't show any details of the bollard at all when clicking it, editing it does not seem possible using the edit plugin either.

**Comment by aceman444** [comment] 2018-05-26 18:07
The routing engine of OsmAnd does not yet support opening hours on drivable objects or barriers.
See the file https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml for what tags the engine observes.

**Comment by WebFreak001** [comment] 2018-05-27 17:20
so would you agree with tagging this "Nice to have"?

**Comment by aceman444** [comment] 2018-05-27 21:59
Sure, it would be great to have the feature.
I just wanted to say, that avoiding the bollard is not due to the map being old or so.

**Comment by WebFreak001** [comment] 2018-05-30 08:29
this bollard could eventually be removed soon, so the route for reproduction will no longer work in the future.

**Comment by vshcherb** [comment] 2018-07-18 17:41
This is definitely "nice to have" and I believe it is a duplicate of another issue

**Comment by jfburke3** [comment] 2018-11-16 17:09
Just to add support for this, here is a gate that is closed during certain hours, but open to vehicular traffic the rest of the time:
https://osm.org/go/ZSAQJT8jX?layers=NG&node=2849719270

Routing through that point shouldn't be allowed when the gate is closed.

**Comment by BjornRasmussen** [comment] 2019-03-18 01:14
Rather than using `opening_hours`, I would tag the bollard with `motor_vehicle=yes` + `motor_vehicle:conditional=no @ (Mo-Su 08:00-19:00)`.  This would be a more "correct" way to tag the bollard I think.

**Comment by WebFreak001** [comment] 2019-03-18 20:21
The wiki link I originally referred to included a hint that you might want to consider using opening_hours in an application. I think it makes more sense standardizing on that than having conditional fields changing the access who can pass from vehicles to none at given times.

https://wiki.openstreetmap.org/wiki/Conditional_restrictions the syntax looks rather heavy and only really suited for navigation here imo, though OpenStreetMaps is for much more than just navigation so it's not feasible for everyone to implement it.

**Comment by vshcherb** [comment] 2019-07-20 12:46
I think this issue will be closed cause we are going to focus on getting conditional working, it is much more common and it could be used with several tags like access, oneway, motor_vehicle, etc...
#1329 
#6271

**Closed by vshcherb** 2019-07-20 12:46 UTC
Labels: Nice to Have
