### ISSUE TITLE
Can't stop / save recording

### ISSUE THREAD

**Issue by bellera** [osmandapp/OsmAnd#11765] opened 2021-05-25 18:22 UTC
### How to reproduce?

Follow a track recording it. Stop navigation. Try to stop recording. Recording stops but re-starts immediately.

The only way I found to definitive stop the recording it's restart OsmAnd. For example reverting it to English and returning after to my local language.

### My Environment
OsmAnd Version: latest-night-builds 21-May-2021 & 25-May-2021
Android/iOS version: 8.1.0
Device model: BQ Aquaris X

**Comment by cepprice** [comment] 2021-05-30 12:31
@bellera Can you please answer few questions? Is auto-record track during navigation enabled for your profile? Are your default profile and navigation profile identical?

**Comment by bellera** [comment] 2021-05-31 12:46
> Is auto-record track during navigation enabled for your profile?

Yes.

> Are your default profile and navigation profile identical?

Yes.

Only active **Browse map** (default) and **Walking**. I'm using **Walking**. After your questions I reset them to defaults. So, now they are different. I configured also different maps. Still having the same problem.

**Comment by HubMiner** [comment] 2021-06-01 16:20
I have the same issue (skipping submitting a duplicate).

**Comment by vshcherb** [comment] 2021-06-01 22:28
Interconnected issue #11810 that track is not saved

**Comment by cepprice** [comment] 2021-06-03 05:11
@bellera @HubMiner I can't reproduce this bug, and I'm not sure whether is's a bug at all. 

The only case when trip auto-record doesn't stop for me is then profile used for navigation and default profile are equal. For example, my default profile is car, and I used for navigation. 

Trip auto-record stops with profile change after finishing navigation. So, if default and navigation profile are the same, profile change doesn't happen, and trip auto-record doesn't stop. That's correct behaviour.

If that's the case, you can switch profiles to stop trip auto-record after finishing navigation

**Comment by vshcherb** [comment] 2021-06-03 14:24
Trip recording should stop and definitely shouldn't start if there is no navigation. That what probably should be fixed

**Closed** 2021-06-04 17:22 UTC

**Comment by HubMiner** [comment] 2021-06-09 07:00
I wonder if my issue is different: I am merely recording a GPX, no navigation is used.  The issue definitely persists.

I'll be on lookout for the new version to test this fix.
