### ISSUE TITLE
[Bug] Elevation Widget Offsetting while Riding

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#15599] opened 2022-10-31 07:38 UTC
I love the new "Elevation profile" widget that allows to view the profile currently being ridden based on a gpx route file.
When cycling, it is very useful to know how long a climb/downhill is and how much it is remaining from the current position.

Unfortunately, the widget has a problem of "sliding offset".
To illustrate the problem, I run the following test, based on the following screenshots.

### How to reproduce?

- 0km. I loaded a gpx file [Yoshino-Koya.zip](https://github.com/osmandapp/OsmAnd/files/9898813/Yoshino-Koya.zip) and started navigation mode for cycling (from kilometre 137), with the Elevation Widget enabled. The widget shows with a vertical bar the current point on the elevation profile, with an elevation of 224m compatible with the current elevation of 215m (red circles). The summit of the climb is after 6km, approximatively at 580m elevation
- 1km. I turned off the phone screen, then turned it back on after 1km and took a screenshot. (I did the same for all the screenshots, to save battery). The point shown on the widget (408 elevation) is different from the actual elevation (287m)
- 2km. The summit in the elevation widget is shown at km4, which is compatible with the fact that I already climbed 2km. However, the vertical bar shows the wrong position (it should be fixed on km0?)
- 3km. The origin of the x-axis is sliding out of the field of view. The current point (km0?) is not visible anymore
- 4km. There are still 2km remaining to climb, but according to the widget I am already on the downhill (after the summit)
- 5km. The current elevation in the top-right keeps on increasing (I am still climbing), but the one indicated in the bottom widget is decreasing

![image](https://user-images.githubusercontent.com/56419637/198953615-6277e4f2-d0e4-425f-b669-c2585d4da151.png)

I hope these screenshots illustrate the problem: I believe that there is some sort of double offsetting of the curve and the x-axis, while only one of the two should be offset.

### Ideal behaviour
I like the idea of showing a 10km span in the elevation widget, but I think it's also important to show a bit of "the past".
I would suggest to:
1. Show 2km from the past (already ridden route)
2. Show 8km of the future (route to be ridden)
3. Keep the origin at 20% of the x-axis, so that labels of past/future are well visible
4. Offset the data so that numbers on the screen are always -2km, 0, 8km (i.e., past and future), so that one can directly know how much climbing/downhill is remaining from the current position.

Thanks a lot for your help and hard work!

### Your Environment
OsmAnd Version: 4.3.0#34796m released 2022-10-26
Android/iOS version: 12
Device model: Galaxy S20FE 5G

**Maps used (online or offline):**   
Offline vector maps
Overlay Strava Heatmap (ride)

**Comment by scaidermern** [comment] 2022-10-31 08:20
Duplicate of #14700.

**Comment by Dollarius** [comment] 2022-10-31 08:33
@scaidermern Thank you for pointing to your previous report! I could not find it with a simple search.

I hope my description can provide additional understanding of the problem (it is probably difficult to reproduce this behaviour without going out and riding a climb).

**Comment by vshcherb** [comment] 2022-10-31 09:51
Did you try to resync but moving the map and clicking My location back ?

Merged to #14700 https://github.com/osmandapp/OsmAnd/issues/15599

**Closed by vshcherb** 2022-10-31 09:51 UTC

**Comment by Dollarius** [comment] 2022-11-01 01:12
@vshcherb moving the map/graph and then re-sync brings back to the same configuration that I showed in the screenshots (curve data offset, axis offset)

**Comment by Dollarius** [comment] 2022-11-01 01:59
Digging into the code at 
OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/ElevationProfileWidget.java
I understand that the intended behaviour is:
1. Calculate the distance (x-axis) when the navigation is started, and keep the distance numbers (x-labels) in the graph fixed to the data as calculated at the start of navigation.
2. Rigidly slide the displayed curve only when the current position goes beyond 20% of the axis start, in order to always show 10km but keeping the current position at the 20% point of the x-axis.

The file by itself looks correct to me, but something else is shifting the distance numbers of the data during navigation.
You can clearly see this by comparing my 0km and 1km screenshots: the summit position on the elevation graph shifts from 6km to 5km (then 4, 3, 2), while it should be locked to the label 6km in all screenshots.
One possibility is that something is calling the function setupChart multiple times after creation of the chart itself.

Hope this could be of any help for solving this issue.

**Comment by Zirochkabila** [comment] 2022-11-02 16:47
**Reproduced**
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/199550490-8986304b-b922-47d6-b816-2e6decd6ea3e.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

If you activate Show slope in the Elevation profile, the data in the widgets start to differ from the first meters of navigation.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/199544440-4383b98e-dd43-4cc8-b608-0f2b3d2aeb70.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

Yes, @scaidermern is right - these two requests are similar.

**Comment by Zirochkabila** [comment] 2022-11-04 11:25
To reproduce quickly - activate Grade (Menu > Configure screen > Bottom panel > Elevation profile Settings > Show slope > Apply).
The actual location point on the graph in the Bottom Elevation widget is shifted forward, which causes the data in the widgets to be out of sync.
The video shows what elevation corresponds to the actual location - shown in the widget at the top-right of the screen and on the point moving along the route.


https://user-images.githubusercontent.com/104760013/199960815-8627aa78-4b06-40d3-8047-ff6b8bd1e3a2.mp4

**Comment by Dollarius** [comment] 2022-11-08 02:03
@vshcherb does "closed" mean "solved"?
I reckon the behaviour of the widget did not change since my report, even in the last OsmAnd version.
Thank you for your work!

**Comment by scaidermern** [comment] 2022-11-08 05:52
> @vshcherb does "closed" mean "solved"?

No, unfortunately not. This issue is closed because it is a duplicate of  #14700 - which is still unresolved. It would be really nice to have this fixed in the next version since in the current state this widget is pretty useless 😟
