### ISSUE TITLE
Bug: Doesn't work find nearest POIs

### ISSUE THREAD

**Issue by kompowiec** [osmandapp/Osmand#2844] opened 2016-07-20 14:28 UTC
I see that add new funcion - search icon in main screen. Sure is it beta so therefore can doesn't work - I click on icon, i try something find and is - i have results on screen. However i click on whatever POI - crash

also , "old version" find POI don't know why but doesen't work too. I Click on interest point with which i want find nearest POI, click on any category and nothing - empty. None results. When i try run configure map-->POI-->nearest POIs not change nothing (don't show up orange circles). I think so simply find POI It was wrong - it's probably a serious problem.

Video - https://vid.me/9Jzk
(sorry fot quality but don't have better equipment from the phone visible on film)

1. First is looking for version OsmAnd (2.4.0#13588D)
2. Afther i try find nearest POI in the classic way.
3. Run configure map-->POI (doesn't work)
4. I try use new function - crash

**Comment by kompowiec** [comment] 2016-07-22 10:49
i give Log file
Version  OsmAndF~ 2.4.0#13588D
22.07.2016 9:29:50
Apk Version : 2.4.0#13588D 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at net.osmand.plus.search.QuickSearchDialogFragment.getMyApplication(QuickSearchDialogFragment.java:375)
	at net.osmand.plus.search.QuickSearchDialogFragment.updateSearchResult(QuickSearchDialogFragment.java:256)
	at net.osmand.plus.search.QuickSearchDialogFragment.access$200(QuickSearchDialogFragment.java:44)
	at net.osmand.plus.search.QuickSearchDialogFragment$2$1.run(QuickSearchDialogFragment.java:113)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5584)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)
Version  OsmAndF~ 2.4.0#13588D
22.07.2016 9:29:50
Apk Version : 2.4.0#13588D 231
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at net.osmand.plus.search.QuickSearchDialogFragment.getMyApplication(QuickSearchDialogFragment.java:375)
	at net.osmand.plus.search.QuickSearchDialogFragment.updateSearchResult(QuickSearchDialogFragment.java:256)
	at net.osmand.plus.search.QuickSearchDialogFragment.access$200(QuickSearchDialogFragment.java:44)
	at net.osmand.plus.search.QuickSearchDialogFragment$2$1.run(QuickSearchDialogFragment.java:113)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5584)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by sonora** [comment] 2016-07-24 20:06
Partial duplicate of #2858  and  #2804 , I guess. May all have the same or a similar root cause.

**Comment by crimean** [comment] 2016-07-28 06:31
@kompowiec please try with latest nightly.

**Closed** 2016-07-28 07:54 UTC
Labels: 2.4

**Comment by kompowiec** [comment] 2016-07-30 05:44
Now Works perfectly, thank you!
