### ISSUE TITLE
Map updates with negative id break search in osm live

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#3034] opened 2016-08-31 22:14 UTC
Using  #18373m with Germany baden-württemberg maps from 1. August. 
Without live maps the names poi aren't double. With update from 31.8.16 23:59 the poi are double displayed. See screenshot.
Also some new opening hours aren't display, but shown if I edit the poi.
![img_20160901_001049](https://cloud.githubusercontent.com/assets/11144987/18148277/e2df6a2a-6fd8-11e6-8e68-297146b1155b.jpg)
![img_20160901_001034](https://cloud.githubusercontent.com/assets/11144987/18148279/e7fad5e4-6fd8-11e6-916e-1dd8cf37f269.jpg)

Greetings Simon

**Comment by vshcherb** [comment] 2016-09-01 19:45
Next time please provide osm link at least to location, so we can check OSM data first.

**Comment by vshcherb** [comment] 2016-09-01 19:48
It is hard to trace back but I believe this is a duplicate of this issue https://github.com/osmandapp/Osmand/issues/2506

**Comment by jf-simon** [comment] 2016-09-01 20:03
Here the location of "dr. Winterhalter" Lat 48.52480 Lon 8.56133
On map I haven't duplicated poi. Only in search. And with every live update it becomes worser.
![screenshot_2016-09-01-21-57-02](https://cloud.githubusercontent.com/assets/11144987/18182266/86c741f6-708f-11e6-8008-a35373ff86fd.png)
Freiwillige Feuerwehr
Position: geo:48.526554,8.564572?z=18
http://osmand.net/go?lat=48.526554&lon=8.564572&z=18

Maybe this informations will help

**Comment by PaulStets** [comment] 2017-07-04 11:55
While generating map updates POI get negative ids that cause duplicates in the Search. Location tested http://osmand.net/go?lat=48.526554&lon=8.564572&z=18
Example BinaryInspector output: route_hiking_lwn_poi Rundwanderweg 10 - Pfalzgrafenweiler Lat 48.5 Lon 8.575066 id=-156136

**Comment by vshcherb** [comment] 2017-09-04 17:29
Fixed by now.

**Closed by vshcherb** 2017-09-04 17:29 UTC
Labels: Live Updates
