### ISSUE TITLE
Routing does not consider newly OsmAnd Live updates  before reboot

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#4931] opened 2018-01-22 08:57 UTC
What I did:
- removed live folder
- restarted OsmAnd
- redownloaded live data
- restarted OsmAnd
- routed again

OsmAnd~ 3.0.0#23554m, 17-01-2018
Iran offline map date: 01-01-2018

Position:
geo:34.101357,49.70508?z=20
https://osmand.net/go?lat=34.101357&lon=49.70508&z=20

Screenshot:
![screenshot_20180122-122407](https://user-images.githubusercontent.com/8467903/35212401-e4ece842-ff51-11e7-9c28-616c58125dd6.jpg)

**Comment by PaulStets** [comment] 2018-01-23 16:09
Hi, I have followed your instructions step by step but was not able to reproduce the issue (see the screenshot of the final result). Please make sure the OsmAnd Live navigation is not turned off on your device.
![27265378_1974305852816219_1573650383_o](https://user-images.githubusercontent.com/20681525/35286341-712853ca-0068-11e8-8fe1-43967c71ee5d.png)

**Comment by iriman** [comment] 2018-01-23 16:51
Hi, yes you're right.

**Comment by CJTmmr** [comment] 2018-01-23 19:29
My experience:
The last Live-Update-file seems not to work for routing.
The rendering of the map is okay, but the last changes are not used for routing.
A day later the changes of the day before are used for routing correctly. This was probably the case when you tried to reproduce the issue

After deleting "ind.cache" and a fresh start of OsmAnd, Live-Routing is okay rightaway.
Maybe there is still a small bug in updating ind.cache?

Unfortunately I did not make screenshots...

Maybe worth reopening?
Good Luck investigating

**Comment by CJTmmr** [comment] 2018-01-26 10:56
I could create a testcase.

Yesterday JAN 25th around 21:30u I fixed a small map error [here](http://www.openstreetmap.org/#map=19/52.03060/4.86446)

Situation before edit: a small connection is missing, so a small detour in [this route](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.03129%2C4.86420%3B52.03081%2C4.86575#map=19/52.03068/4.86470)
(Osrm at this time, is not yet updated!)
![2018-01-25 17 04 57](https://user-images.githubusercontent.com/15076257/35436451-cba4e96c-028e-11e8-8396-1f17602ad068.png)

After my edit, waited another hour, then Netherlands_europe_18_01_25.obf, timestamp 2018-01-25 22:45 was available and downloaded by OsmAnd Live.
After this update: Rendering is okay: small connection piece of road in the middle.
But routing does nog take the new connection.
![2018-01-25 23 18 04](https://user-images.githubusercontent.com/15076257/35436576-4433ba20-028f-11e8-9bdf-91bdf7d0e5c0.png)

Then I deleted ind.cache. And a new start of OsmAnd (takes longer, recreating ind.cache)
After that OsmAnd uses the new connection for routing:
![2018-01-25 23 26 08](https://user-images.githubusercontent.com/15076257/35436654-8e000636-028f-11e8-83fe-3813de6f560a.png)

**Comment by CJTmmr** [comment] 2018-01-28 16:38
Edit : is appears you do not have to delete ind. cache. A fresh start of OsmAnd is enough!

**Comment by PaulStets** [comment] 2018-01-29 14:57
Fixed with https://github.com/osmandapp/OsmAnd-core/pull/70

**Closed by PaulStets** 2018-01-29 14:57 UTC
