### ISSUE TITLE
Gaps in roads -> bad routing

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#17060] opened 2023-04-26 06:25 UTC
Noticed in Google Play reviews by Mariusz "Terminus" Kocoń written on April 9th.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/27214784/234487303-a539ed11-bb0f-4f5b-b8ac-cc42ca463e1e.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  
Indeed the maps contain gaps I didn't find in OSM - https://www.openstreetmap.org/#map=18/52.17975/20.77111

**Comment by scaidermern** [comment] 2023-04-26 06:33
Probably a duplicate of #16939.

Though I'm wondering why maps haven't been repaired yet. Developers say to wait for May maps. Why are users left alone with broken routing instead of fixing the problem immediately?

**Comment by vshcherb** [comment] 2023-05-10 22:52
Duplicate https://github.com/osmandapp/OsmAnd/issues/16939

**Closed by vshcherb** 2023-05-10 22:52 UTC
