### ISSUE TITLE
Overlay of function buttons on the display

### ISSUE THREAD

**Issue by wolfwehl** [osmandapp/OsmAnd#20493] opened 2024-08-04 16:07 UTC
### Description

If you activate the lower panel, e.g. to display the time, the function buttons on the display overlap (see comparison of the two screenshots). The buttons in the background can no longer be operated.

### Steps to reproduce

Activation of the lower panel, e.g. for displaying the time

### Actual result

Overlapping of buttons

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/fc7a9cb9-208b-4e9d-bb7b-8f71a8db2115"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

No overlapping of buttons

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/59ef919b-a8f6-4102-860f-7d895a5b1b2a"  width="300" height="auto"/> </th>
  </tr>
</table>

### Your Environment (required)

OsmAnd Version: 4.7.17 (also 4.8.3)
Android/iOS version: 14
Device model: Samsung Galaxy A53 5G
Crash-Logs: no crash

**Comment by mikehgentry** [comment] 2024-08-04 17:07
Duplicate of #16138

**Closed** 2024-08-05 11:37 UTC
