### ISSUE TITLE
excluding wrong points when recording a trip

### ISSUE THREAD

**Issue by paolobenve** [osmandapp/OsmAnd#9691] opened 2020-08-24 14:16 UTC
When recording my trip (walking on mountain paths) with osmand, it sometimes records some point which is completely wrong, i.e. very far from where I am.

It often happens when I switch off the cell display.

Other similar applications have an option which permits to exclude such points from the recording.

**How does osmand manage these wrong points?** I couldn't find anything in the options.

In case that osmand doesn't manage anything similar, **this is a feature request**: it can be implemented in a very simple way, _checking the speed between two consecutive points_. With wrong points it will be _abnormally high_.

**Comment by scaidermern** [comment] 2020-08-26 07:38
Duplicate of #9133.

**Comment by vshcherb** [comment] 2020-09-02 13:45
There are GPX settings to filter out wrong points based on precision, speed

**Closed** 2020-09-02 13:45 UTC
