### ISSUE TITLE
Altitude/Slope route line

### ISSUE THREAD

**Issue by LucasBS1** [osmandapp/OsmAnd#16589] opened 2023-03-03 14:34 UTC
On the **route line customization option** there is no way to adjust the _maximum_ and _minimum_ _altitude_ or _slope_ 

On the altitude option, the colors range from below ground-level to who knows how high... And those are fixed

The same goes for slope.

Within a city or a region, there is no significant slope variation or altitude variation, so the colors never change, making these options useless.

BTW: please fix the storage access problem before fixing this one

**Comment by scaidermern** [comment] 2023-03-03 18:31
Duplicate of #12954.

**Comment by LucasBS1** [comment] 2023-03-03 18:59
True
Duplicate
And I DID search

**Closed** 2023-03-03 18:59 UTC
