### ISSUE TITLE
[Feature request] Show branch information in search if available.

### ISSUE THREAD

**Issue by s8321414** [osmandapp/OsmAnd#7913] opened 2019-11-13 03:00 UTC
Sometimes we want to search some POI that have many branches in different location, but on OsmAnd, I can't find any option to show branch information in search results, could you add this feature?

What version of OsmAnd are you using, on what device and Android/iOS version?
4.3.8 on Sony Xperia XZ1 (G8342) Android 9
Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline maps.

**Comment by EvanCarroll** [comment] 2022-09-16 01:36
This is a duplicate of this https://github.com/osmandapp/OsmAnd/issues/6947 . But I agree this feature is more than a Nice to have. I again drove to the wrong Costco today.

**Closed** 2022-09-16 11:14 UTC
Labels: Nice to Have
