### ISSUE TITLE
OsmAnd doesn't respect except=bicycle in turn restrictions

### ISSUE THREAD

**Issue by 05storm26** [osmandapp/OsmAnd#16516] opened 2023-02-22 10:17 UTC
On the road: https://www.openstreetmap.org/way/4766060/history

there is an only left turn (towards the bridge) restriction. This doesn't apply to the bicycles. This is tagged on the restriction relation.

In bicycle routing mode since the restriction has except=bicycle tag the restriction should be ignored. Currently the bicycle routing avoids going through this road if you would need to go straight on or turning right (away from the bridge) because of the turn restriction. This is incorrect.

Example:

![Screenshot_20230222_111112_OsmAnd](https://user-images.githubusercontent.com/8590289/220589643-7fbd665e-29d5-4ba1-b699-fefbc0399147.png)

Approx. coordinates of the picture: 46.25205° N, 20.15102° E

**Comment by scaidermern** [comment] 2023-02-22 12:44
Duplicate of #3882. Please add your example there.

**Closed** 2023-02-23 19:07 UTC
