### ISSUE TITLE
Easier selection of navigation route alternatives

### ISSUE THREAD

**Issue by sjvudp** [osmandapp/OsmAnd#20223] opened 2024-07-01 19:18 UTC
### Describe the idea (required)

Similar as  Route alternatives #1294, but with a different emphasis:

When finding a route to a destination you sometimes know about temporary local circumstances that OSM does not know (and probably does not want to know due to the temporary character).
Examples of such are:

- Road works with traffic lights that cause major traffic jam
- local sports events temporarily blocking a road (like bicycle race)
- accident
- flooding
- ...

In contrast to typical navigation solutions (like Google maps or TomTom), OsmAnd suggests just a single route to the destination, while other products suggest multiple routes that are similarly fast.
Moreover if you are already following a route and find out that you cannot continue (see example above), you can enter something like "road blocked for ### meters", and the other solutions remember that and find a route around.
OsmAnd has a similar mechanism, but if places **permanent** "road blocked" notes onto the map that the user has to clean up **manually** afterwards (while other products remember it just for the current route (it seems)).
To make matters worse, OsmAnd requires multiple "blockers" to be placed if the road to avoid is longer, as here:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/6734808/3e256652-f505-4a76-bb0e-ba3ae214fc69"  width="300" height="auto"/> </th>
  </tr>
</table>

### Tell us about the expected behaviour (required)

It should be (much) easier to avoid specific roads or areas when planning or following a route.

### Tell us about alternatives you've considered (required)

Place temporarily permanent "blockers" while planning or following a route, and afterwards (if you don't forget and can remember them all) manually remove those "blockers" again.

**Comment by yuriiurshuliak** [comment] 2024-07-02 08:33
Duplicate of https://github.com/osmandapp/OsmAnd/issues/11631

**Closed** 2024-07-12 13:56 UTC

**Comment by sjvudp** [comment] 2024-07-18 19:21
> Duplicate of #11631

It's not an exact duplicate, because  #11631 is about alternate routes only, but it does not cover what to do when already "on route" when something unexpected happens and you cannot follow the route (road blocked, etc.).

In "TomTom" you can say "road blocked for (...distance...) meters" (where the road is the one you are following at the moment), and then an alternate route is computed (*without* having to place manual "road blocked" marks in the map).
