### ISSUE TITLE
Implement keyboard avoiding view for save button in POI editing

### ISSUE THREAD

**Issue by dkocich** [osmandapp/Osmand#7736] opened 2019-10-24 10:11 UTC
Similar to #6669

Current
Now there are two buttons hidden under the keyboard and each time when I am going around to map I have to close keyboard so I am able to save each change.

Expected
I would like to see buttons all the time and immediately save my change without doing another unnecessary action to hide keyboard...

![Screenshot_2019-10-24-12-03-47-817_net osmand plus](https://user-images.githubusercontent.com/6165660/67475718-fe904980-f656-11e9-9560-4819677004af.png)
![Screenshot_2019-10-24-12-03-50-533_net osmand plus](https://user-images.githubusercontent.com/6165660/67475720-fe904980-f656-11e9-9d44-cac330d6d08f.png)

**Comment by scaidermern** [comment] 2019-10-24 10:21
Duplicate of #6669.

**Closed** 2019-10-30 13:32 UTC
