### ISSUE TITLE
GPX navigation options not available for OsmAnd generated tracks

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9388] opened 2020-07-04 19:33 UTC
When using a GPX track generated by OsmAnd for navigation there are no further settings available. For third party GPX tracks the following options are available:

- Reverse GPX direction
- Pass along entire track
- Calculate OsmAnd route for first and last route segment

Please make these options also available for GPX tracks generated by OsmAnd.

The second option is probably related to #9209 

The first option won't work with the new GPX route segment extension. However for reversing OsmAnd could just fall back to the traditional mode which is also used for third party GPX tracks. This is better than having no reverse option available.

**Comment by vshcherb** [comment] 2020-07-06 15:53
- Reverse GPX direction - is not possible to implement cause it messes up navigation where oneway in the wrong direction will be encountered 
- Calculate OsmAnd route for first and last route segment - should be enabled automatically and this is how it should work. So #9209 needs to be checked. 
- Pass along entire track is cumbersome option which is even hard to explain and it is not applicable for standard navigation. So it's probably should be deleted from 3rd party GPX .

Note: OsmAnd GPX file works mostly as standard map navigation and have all benefits related to it. 
Options like 1 and 2 will be part of Route preparation step and not navigation parameter and option 3 will be actually dependent on the routing profile enabled.

**Comment by vshcherb** [comment] 2020-07-06 15:54
So, I agree that the difference should be fixed and it should be no difference but the way to make it compliant will be quite different.

**Comment by scaidermern** [comment] 2020-07-06 16:24
>     * Reverse GPX direction - is not possible to implement cause it messes up navigation where oneway in the wrong direction will be encountered

True. However this is already the case for third party GPX files. For these files the reverse option is available, though.

>     * Calculate OsmAnd route for first and last route segment - should be enabled automatically and this is how it should work. So #9209 needs to be checked.

Agreed.

>     * Pass along entire track is cumbersome option which is even hard to explain and it is not applicable for standard navigation. So it's probably should be deleted from 3rd party GPX .

I see. I'm not sure if this option is really needed.

**Comment by vshcherb** [comment] 2020-07-06 23:00
For 3rd option we need to fix when people click to use it mostly it's for roundtrip routes which probably is fixed already.

**Comment by IsecacIt** [comment] 2020-07-08 08:06
>     * Pass along entire track is cumbersome option which is even hard to explain and it is not applicable for standard navigation. So it's probably should be deleted from 3rd party GPX .

Please don't, that's how I use it a 100% of the time.
I import a third-party GPX track on my phone, and I want OsmAnd to strictly follow it.

> For 3rd option we need to fix when people click to use it mostly it's for roundtrip routes which probably is fixed already.

Indeed I use it for roundtrip routes, otherwise it just says I have reached my destination.
If that's what you mean, then it's not fixed in 3.7.4

**Comment by vshcherb** [comment] 2020-07-09 20:16
There is ongoing discussion how to enable all the settings and it looks we will need to redesign first step of GPX navigation, so these parameters will be specified separately.

**Comment by Vaaltuin** [comment] 2020-07-15 13:05
Hi, I originally contacted support on this issue. Maybe it is not fully understood.
When I plan a route using measure distance, and save it as a gpx, then when I want to use this track I do not get the three options (pass along entire track etc.) If I alternatively create a route by using From and To, and save this route, I again do not get those options. If I set the creator of any non OsmAnd gpx file to "OsmAndRouterV2" then the the same problem occurs.
When I edit those gpx files by changing creator to anything but "OsmAndRouterV2" then those gpx's work perfectly

The option not to pass along the entire track is my preferred choice (I often experience that the route is not precisely what I want, sometimes due to the map wrongly indicating that one could take a route that is in fact not available, or maybe because I want to visit a POI, etc.) With OsmAndRouterV2 files forcing me to Pass along the entire track in such a case, the whole planned trip becomes useless as the navigation just silently stops functioning while the not passing along entire track has a reasonable recovery.
I thus fail to see how there could be implementation problems as all I want is not to check for OsmAndRouterV2 and then disable those functions.
I currently bypass this annoyance by editing the file after I created it with OsmAnd.

**Comment by sonora** [comment] 2020-07-16 15:11
@Vaaltuin Thank you for the research, this really makes it reproducible! Looks like OsmAnd has a problem with its own files, rather comically ... ;)

(And it seems this even affects files which do not contain any routing information, just `<trkpt>` ... )

**Comment by sonora** [comment] 2020-07-16 15:15
PS: @vshcherb All 3 of the above mentioned options
- Reverse GPX direction
- Calculate OsmAnd route for first and last route segment  (meaning: **to and from the GPX-track**, we should probably rename that). (Disabling this is e.g. needed when you try to find out the length of a tour but you are not at the trailhead currently.)
- Pass along entire track

have their justification and used to work! I think we should keep them all.

**Comment by sonora** [comment] 2020-07-16 15:44
Here is a shot at some wording we may use: https://github.com/osmandapp/Osmand/pull/9466 (Maybe someone has an even better idea?)

**Comment by scaidermern** [comment] 2020-07-16 16:39
> The option not to pass along the entire track is my preferred choice (I often experience that the route is not precisely what I want, sometimes due to the map wrongly indicating that one could take a route that is in fact not available, or maybe because I want to visit a POI, etc.) With OsmAndRouterV2 files forcing me to Pass along the entire track in such a case, the whole planned trip becomes useless as the navigation just silently stops functioning while the not passing along entire track has a reasonable recovery.
> I thus fail to see how there could be implementation problems as all I want is not to check for OsmAndRouterV2 and then disable those functions.
> I currently bypass this annoyance by editing the file after I created it with OsmAnd.

This sounds like #9209.

> @Vaaltuin Thank you for the research, this really makes it reproducible! Looks like OsmAnd has a problem with its own files, rather comically ... ;)

Yeah, it definitely has.

**Comment by max-klaus** [comment] 2020-09-03 12:27
Fixed

**Closed by max-klaus** 2020-09-03 12:27 UTC
Labels: Observed
