### ISSUE TITLE
Menu buttons hidden behind notification bar

### ISSUE THREAD

**Issue by Leo-pepe** [osmandapp/OsmAnd#13989] opened 2022-03-28 13:04 UTC
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/13710074/160403343-713611b4-6a77-4648-a6b7-bcb270ee780f.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

![Screenshot_20220328-150518](https://user-images.githubusercontent.com/13710074/160404154-6c497b7e-9b3a-46bf-8b27-89a47b8cc0ec.png)

While opening some menus the upper buttons are too far up and will be behind the notification bar.

For example opening the navigation menu. The different navigation types will be half hidden behind the notification bar and can only be guessed.

OsmAnd Version: OsmAnd 4.1.11, released: 2021-1 2-1 5
Android version: 12
Device model: Google Pixel 4a

**Comment by vshcherb** [comment] 2022-03-28 15:29
Can you try disable Full-Screen mode in OsmAnd Settigns?

**Comment by Leo-pepe** [comment] 2022-03-28 15:41
If you meant the setting in
Configure profile > General > Fullscreen mode
This did not work, even when applying to all profiles and disabling it again.

**Comment by mmh-dev** [comment] 2022-03-29 21:35
![Screenshot_1648589276](https://user-images.githubusercontent.com/60875266/160710301-8c1338e6-9e4a-417d-9474-87b903bbe30a.png)
![Screenshot_1648589282](https://user-images.githubusercontent.com/60875266/160710297-465757bb-5fa9-4c9c-b521-992a20108fcc.png)
Hi, I can't reproduce the issue, toolbar seems to be working as intended. Did you try to update the app to the latest version?

**Comment by dmpr0** [comment] 2022-03-30 16:38
@Leo-pepe 
We are still investigating the issues, it seems it depends on screen cutout type.

**Comment by Zirochkabila** [comment] 2023-01-11 09:53
OsmAnd~ 4.4.0#14086mqta, released: 2023-01-11
Still able to reproduce, after disabling Transparent status bar
Reopen or changing the orientation of the display helps


https://user-images.githubusercontent.com/104760013/211774481-dfbb06af-6262-441b-a144-35cce5ad9cfe.mp4

**Comment by vshcherb** [comment] 2023-01-26 11:54
Restart should help

**Comment by llbstr** [comment] 2023-03-29 20:50
I have the same weird issue with a pixel 4a 5g, fullscreen on/off, restart/device restart has no effect, could never get rid of it.

**Comment by DmitryAlexei** [comment] 2023-08-08 13:07
OsmAnd~ 4.6.0#586m, released: 2023-08-08 and OsmAnd 4.5.9, released: 2023-08-01

For me, there are two issues with **Transparent status bar**
- status bar isn't transparent on the map screen (and transparent in the settings menus)
- after **Transparent status bar** is been disabled, toolbar is cut off (restart of the app helps to make toolbar big again)

Steps to reproduce:
- Menu > plugins > development plugin > toggle Transparent status bar option
No matter if *Fullscreen mode* is on or not (Menu > settings > profiles > general settings > fullscreen mode)

<table style="width:100%">
 <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/8f2bc620-367e-483e-b836-e23fc7de0252"  width="300" height="auto"/> </td>
 </tr>
</table>


https://github.com/osmandapp/OsmAnd/assets/116079541/239d92c2-f597-47e3-9810-966b64d35289

**Comment by vshcherb** [comment] 2023-08-08 13:08
Issue was closed in 4.3 couldn't be reopen

**Closed by vshcherb** 2023-08-08 13:08 UTC
Labels: and-bugs
