### ISSUE TITLE
app crashes when navigating on bike

### ISSUE THREAD

**Issue by ThePilotBoi** [osmandapp/OsmAnd#17349] opened 2023-06-04 22:16 UTC
### Description
the app crashes when i am navigating on cycle profile. once i restart it asks to restart navigation. once restarted it doesnt take too long for it to crash again
### Steps to reproduce
start navigating to a destination on the cycle profile. wait until crash and repeat
### Actual result
crashes often 
### Expected result
not crashing and sucessfully navigating to destination
### Your Environment
OsmAnd Version: osmand~ 4.3.12
Android/iOS version: android 13, one ui 5
Device model: Samsung galaxy A53

**Comment by Zirochkabila** [comment] 2023-06-05 12:40
@ThePilotBoi Cannot be reproduced
Please update OsmAnd and try again
It will also be useful if you add a crash log (OsmAnd should offer it after the crash) or a log file: Menu > Help > Send logcat log

**Comment by boaz001** [comment] 2023-06-17 19:34
Try version 1 instead of version 2 (opengl).

**Comment by Zirochkabila** [comment] 2023-06-18 08:48
@boaz001 Even when using V1, in the latest, nightly version, it does not play
Please provide your profile and system settings - the failure may be caused by the settings. 
Also, it will be useful to get your crash logs

**Comment by boaz001** [comment] 2023-06-24 18:12
@Zirochkabila Thanks for the response. OsmAnd was crashing repeatedly (like every minute/minutes) while navigating an imported GPX track. This issue had similar description hence I commented here.

I am a new user of OsmAnd, no settings were changed after a fresh installation. The first setting changed was switching to V1 which turned out to fix the app closing/crashing.

[logcat.log](https://github.com/osmandapp/OsmAnd/files/11857868/logcat.log)

My env:

OsmAnd Version: 4.4.7
Android/iOS version: Android 11, one ui 3.1
Device model: Samsung Galaxy A41

**Comment by Zirochkabila** [comment] 2023-06-26 10:25
@boaz001 If you experience a crash, the system should offer to send crash logs.
If the system does not offer this, please send crash logs immediately after the crash (the one on the photo)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/2b18a5c1-27c5-4acc-acbb-c5cc886ce509"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment] 2023-07-13 15:14
Not reproduced...

**Closed by vshcherb** 2023-07-13 15:14 UTC
