### ISSUE TITLE
Navigation with an existing track does not take routing into consideration

### ISSUE THREAD

**Issue by Themanwithoutaplan** [osmandapp/Osmand#7046] opened 2019-06-17 18:34 UTC
In case you are not sure to open issue or not, please send your request to support support@osmand.net. For **general questions** about OsmAnd, please use the [Google group](https://groups.google.com/forum/#!forum/osmand).

Please be sure to have read our [FAQ](http://osmand.net/help-online) before creating an issue here. (Also, tell us in Google Groups when the FAQ is wrong or outdated.)

The best way to get help about an OsmAnd issue is to create a valid and detailed issue content.
Please give us the following information so that we can try to **reproduce** your issue:

What version of OsmAnd are you using, on what device and Android/iOS version?
Android 3.3.8 on LineageOS 16.0 / Android 9

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
OsmAnd offline maps.

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
Germany NRW, 2019-06-01

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.
OsmAnd's

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)
Bike, using byway

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.
Germany, Köln-Arnufstr. to Köln Merkenicher Ringstr.

One of the things I really like about OsmAnd is the ability to use an existing track as the basis for another journey. For example when making a return trip. Navigation in version 3 has got much better except in one respect: it seems that using an existing track no longer takes the local road situation into consideration, for example one-way streets or the ability to cross-roads. This is particularly annoying in cities where the rules can be very strict.

I recently recorded a trip from Merkenich to Sülz in Köln using OsmAndTracker. The last few hundred metres involve a one-way street and a dual carriageway with a tramline that cannot be crossed directly. On the return journey OsmAnd seems to ignore this information completely. The settings are not set to follow every way point, the route is simply reversed.

Previously navigation using an existing track was always possible but took longer to calculate. Now it seems as if the way points from an existing track are taken with no further steps.

Also, it is farily common to want to make changes to the route, for example have a slightly different start and ending point, or direction, before OsmAnd starts calculating it, ie. let the track be selected, make any changes and then start calculating. As things stand I currently find myself having to restart navigation repeatedly because OsmAnd has adjusted start, finish or route.

![2019-06-17 20 19 01](https://user-images.githubusercontent.com/1080058/59627575-d6d82480-913e-11e9-8f97-d19c48db5c45.png)

The enclosed screenshot shows OsmAnd simply ignoring the local roads – yes the original track has low granularity but I get the experience with higher tracking frequency and would expect OsmAnd to try and navigate sensibly between the waypoints. On this kind of journey I'm always going to expect to follow traffic rules, etc. and also skip waypoints that might only make sense going one way.

**Comment by scaidermern** [comment] 2019-06-18 06:01
Duplicate of #3908. A very useful feature but still not implemented unfortunately.

**Comment by Themanwithoutaplan** [comment] 2019-06-18 08:05
I just double-checked with an older version (3.2.x) of OsmAnd and, with this track at least, the behaviour is the same as 3.3 but I have definitely used this feature in the past. It is really useful in this case, where I'm trying to avoid OsmAnd's suggested route through Cologne's city centre.

**Comment by scaidermern** [comment] 2019-06-18 08:28
If the track has a decent accuracy it might *look* and *feel* like OsmAnd matches it to a road. But it actually doesn't and never has, as far as I know.

**Comment by vshcherb** [comment] 2019-06-23 20:15
You need to use track with <rtept> not with <trkpt> inside. So yes we have an idea to match with the road but that track will likely not work anyway.

**Closed by vshcherb** 2019-06-23 20:15 UTC

**Comment by Themanwithoutaplan** [comment] 2019-06-24 08:35
I'm not sure I understand the comment. I appreciate that there might be technical difficulties but I'd have thought it at least possible for the navigation to detect one-way streets.

**Comment by scaidermern** [comment] 2019-06-24 08:41
In order to detect oneway streets the track needs to be matched against the road. This step doesn't exist yet, so detecting oneway streets is currently not possible when routing along a track.
