### ISSUE TITLE
My Tracks > "Show all tracks on the map" does not what it says

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#18490] opened 2023-11-02 09:23 UTC
This may be a regression, not sure: On 4.6 builds, in My Places > Tracks, if for some folder I have there I select its 3-dots menu > "Show all tracks on the map", I would expect the effect is all contained tracks of that folder become marked as visible on the map (and probably the app even changes back to the map screen to display them?).

But it seems that instead I am forwarded to the "Visible tracks" screen for that folder (no tracks are even marked!?), and further action is required?

**Comment by scaidermern** [comment] 2023-11-02 09:40
Duplicate of #17754? :)

**Comment by sonora** [comment] 2023-11-02 10:08
> Duplicate of #17754? :)

Ah, looks like both my memory and my Issue search is broken today, I knew I had it somewhere but simply could not locate it ... :wink::wink::wink:  Thanks, Alexander!

**Comment by vshcherb** [comment] 2023-11-15 11:36
To do: It should redirect to selected folder page in with all tracks selected

**Closed** 2023-12-12 14:28 UTC
Labels: and-bugs

**Comment by vshcherb** [comment] 2023-12-12 14:34
We need to create separate task to limit with 1M points "Show track folder  on map" in future. So in that case we can automatically display once track is added to folder.

Also we can't disable folder display, so it works totally different then Switch for Favorites category
