### ISSUE TITLE
Routing inaccuracies 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6703] opened 2019-03-18 12:45 UTC
Start https://osmand.net/go?lat=50.45549&lon=30.47531&z=15
end https://osmand.net/go?lat=50.45372&lon=30.47009&z=15 
![image](https://user-images.githubusercontent.com/40493090/54530657-033ba380-498c-11e9-9c2f-0fe954697455.png)

start  https://osmand.net/go?lat=50.45549&lon=30.47531&z=15
end https://osmand.net/go?lat=50.45108&lon=30.46874&z=15 
![image](https://user-images.githubusercontent.com/40493090/54530735-40a03100-498c-11e9-9ac2-c9529a597300.png)

**Comment by pietercolpaert** [comment] 2019-03-22 10:55
I  don’t understand this issue based on just the screenshots: what are the inaccuracies precisely?

**Comment by naoliv** [comment] 2019-03-22 11:28
Maybe there is something wrong in OSM, since the same result can be seen with OSRM:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.4538%2C30.4699%3B50.4557%2C30.4757#map=16/50.4533/30.4768

The current result is this:
![](https://user-images.githubusercontent.com/982338/54819978-670be800-4c7c-11e9-9549-e654f17e6db5.png)

While the probable expected result would be this yellow route:
![](https://user-images.githubusercontent.com/982338/54819981-6bd09c00-4c7c-11e9-8208-f6600e0d7e7b.png)

**Comment by vshcherb** [comment] 2019-04-12 15:33
Cause the author of the issue is not here so it will be easier to close it.

**Closed by vshcherb** 2019-04-12 15:33 UTC
