### ISSUE TITLE
The point moves on the map when creating a route in Plan a route (OpenGL only)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16033] opened 2022-12-22 09:59 UTC
### Description
When creating a route in Plan a route, the point selection marker moves, making it difficult to select a point

### Steps to reproduce
Menu > Plan a route

### Actual result

https://user-images.githubusercontent.com/104760013/209106035-cf582715-1baf-4253-aa6d-3f016ee6f441.mp4

https://user-images.githubusercontent.com/104760013/209106573-9b0c0b63-5df1-430c-82dc-3930c48680c8.mp4

### Expected result
The point moves as in Legacy rendering

https://user-images.githubusercontent.com/104760013/209107090-76a75bfc-e75c-433b-802b-c58ba6bb6b3f.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14038mqta, released: 2022-12-22
Android/iOS version: Android 12
Device model: Poco x3

**Comment by Gregor0000** [comment] 2022-12-22 10:24
I just reported an issue with the point move function to OsmAnd support and was told that the reported behavior could be reproduced and that the problem is dealt with in this issue.
However, the problem description here doesn't match my reported bug. Therefore, I post my description again:

OsmAnd+ 4.3.3, veröffentlicht: 2022-12-13

Problem:
Once you move a point in a planned route, the rendering of the route & map is completely broken. The plan route (edit route) function can no longer be used after moving a point. Only a restart of the application helps temporarily - until you try to use "Move Point" again.

Steps to reproduce:
- create an arbitrary route using the plan route function, consisting of just 2 points (start and finish).
- save that route
- edit that route and try to move the finish point using the "Move Point" function
--> the updated route doesn't render. Map zoom is broken too.
- save that route
--> this correctly shows the updated route, but no further route editing possible in this state.

This happens for rendering version 1 and slightly differently (but also broken) for the new OpenGL rendering version 2.

For me and my usage of osmAnd, this is a major bug - introduced after the update to 4.3.

I would be very happy if you could look into that.

Thank you,

**Comment by vshcherb** [comment] 2022-12-26 15:11
Merged to internal issue

**Closed by vshcherb** 2022-12-26 15:11 UTC
